### ISSUE TITLE
Problem with template luma

### ISSUE THREAD

**Issue by Antonioele** [magento/magento2#1004]
I have install Magento2  for second time I have same problem. Less don't work with exception:

[2015-01-28 16:18:51] main.CRITICAL: exception 'LogicException' with message 'magento_import returns empty result by path css/source/extend.less' in /opt/lampp/htdocs/magento2/lib/internal/Magento/Framework/Less/File/Collector/Aggregated.php:78 Stack trace: #0 /opt/lampp/htdocs/magento2/lib/internal/Magento/Framework/Less/PreProcessor/Instruction/MagentoImport.php(97): Magento\Framework\Less\File\Collector\Aggregated->getFiles(Object(Magento\Core\Model\Theme), 'css/source/exte...') #1 /opt/lampp/htdocs/magento2/lib/internal/Magento/Framework/Less/PreProcessor/Instruction/MagentoImport.php(78): Magento\Framework\Less\PreProcessor\Instruction\MagentoImport->replace(Array, Object(Magento\Framework\View\Asset\File)) #2 [internal function]: Magento\Framework\Less\PreProcessor\Instruction\MagentoImport->Magento\Framework\Less\PreProcessor\Instruction\{closure}(Array) #3 /opt/lampp/htdocs/magento2/lib/internal/Magento/Framework/Less/PreProcessor/Instruction/MagentoImport.php(80): preg_replace_callback('#//@magento_imp...', Object(Closure), '/**\n * Copyrigh...') #4 /opt/lampp/htdocs/magento2/lib/internal/Magento/Framework/Less/FileGenerator.php(96): Magento\Framework\Less\PreProcessor\Instruction\MagentoImport->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain)) #5 /opt/lampp/htdocs/magento2/lib/internal/Magento/Framework/Css/PreProcessor/Less.php(41): Magento\Framework\Less\FileGenerator->generateLessFileTree(Object(Magento\Framework\View\Asset\PreProcessor\Chain)) #6 /opt/lampp/htdocs/magento2/lib/internal/Magento/Framework/View/Asset/Source.php(147): Magento\Framework\Css\PreProcessor\Less->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain)) #7 /opt/lampp/htdocs/magento2/lib/internal/Magento/Framework/View/Asset/Source.php(90): Magento\Framework\View\Asset\Source->preProcess(Object(Magento\Framework\View\Asset\File)) #8 /opt/lampp/htdocs/magento2/lib/internal/Magento/Framework/View/Asset/File.php(109): Magento\Framework\View\Asset\Source->getFile(Object(Magento\Framework\View\Asset\File)) #9 /opt/lampp/htdocs/magento2/lib/internal/Magento/Framework/App/StaticResource.php(106): Magento\Framework\View\Asset\File->getSourceFile() #10 /opt/lampp/htdocs/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(245): Magento\Framework\App\StaticResource->launch() #11 /opt/lampp/htdocs/magento2/pub/static.php(13): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\StaticResource)) #12 {main} [] []

**Comment by vasiliyseleznev** [comment]
Hi @Antonioele,

Let me just clarify, does it happens on clear installation?  Did you make any edits to theme LESS CSS files? Please see more about [@magento_import](https://wiki.magento.com/display/MAGE2DOC/CSS+Preprocessing+in+Magento+2#CSSPreprocessinginMagento2-The@magento_importinstruction)

**Comment by MomotenkoNatalia** [comment]
Hi @Antonioele. Thank you, for your contribution. This issue is confirmed and related ticket has been added to the backlog (MAGETWO-33413).

**Comment by vpelipenko** [comment]
@Antonioele, internal ticket is assigned to team and will be fixed during next weeks.

**Comment by snohe** [comment]
@Antonioele, this issue is now resolved in 0.74.0-beta1.  Thank you again for submitting this issue.  Should you have any other questions, please don't hesitate to reach out to us.

**Comment by wclmanoj** [comment]
Hi @MomotenkoNatalia,

I have suffer to add bundle sub products images into the order email template in EE or CE both so please help me.?

Regards,
Manoj
