### ISSUE TITLE
Minimum Order Amount error 500 on Shoppingcart if "Error to Show in Shopping Cart" is filled

### ISSUE THREAD

**Issue by Webroju** [magento/magento2#10097]
If minimum order amount is enabled, Minimum amount e.g. 100,  and I wrote something in the description field at the mimimum order amount section, and if I then delete one product at the shopping cart, so that the amount is under the minimum order amount, then an error 500 occour.

Magento 2.1.7.
Server: Nginx
PHP: 7.0.9

At the exeption log:
[2017-06-29 12:22:13] main.CRITICAL: Magento\Framework\Exception\InputException: Minimum order amount is $100.00 in /var/www/clients/client2215/web4572/web/mag2/vendor/magento/module-quote/Model/ShippingAddressManagement.php:121
Stack trace:
#0 /var/www/clients/client2215/web4572/web/mag2/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingProcessor.php(66): Magento\Quote\Model\ShippingAddressManagement->assign('4', Object(Magento\Quote\Model\Quote\Address))
#1 /var/www/clients/client2215/web4572/web/mag2/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingAssignmentProcessor.php(76): Magento\Quote\Model\Quote\ShippingAssignment\ShippingProcessor->save(Object(Magento\Quote\Model\Shipping), Object(Magento\Quote\Model\Quote))
#2 /var/www/clients/client2215/web4572/web/mag2/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingAssignmentPersister.php(34): Magento\Quote\Model\Quote\ShippingAssignment\ShippingAssignmentProcessor->save(Object(Magento\Quote\Model\Quote), Object(Magento\Quote\Model\ShippingAssignment))
....

**Comment by veloraven** [comment]
@Webroju thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.

**Comment by magento-engcom-team** [comment]
@Webroju we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
