### ISSUE TITLE
CatalogInventory ignoring extension attributes

### ISSUE THREAD

**Issue by vo1** [magento/magento2#10143]
### Preconditions
Magento CE 2.1.6

### Steps to reproduce
Add extension attributes for Magento\CatalogInventory\Api\Data\StockItemInterface in your module

```
<extension_attributes for="Magento\CatalogInventory\Api\Data\StockItemInterface">
  <attribute code="timestamp" type="string"/>
</extension_attributes>
```
API call PUT: /rest/V1/products/24-WB05/stockItems/1
`{"stockItem": { "qty":10, "timestamp": "1499176675"}}`

### Expected result
Update or ignore field "timestamp" depending on presence in database.

### Actual result
Exception `Property "Timestamp" does not have corresponding setter in class "Magento\CatalogInventory\Api\Data\StockItemInterface"`

```
#0 /var/www/project/vendor/magento/framework/Reflection/NameFinder.php(59): Magento\Framework\Reflection\NameFinder->findAccessorMethodName(Object(Zend\Code\Reflection\ClassReflection), 'Timestamp', 'getTimestamp', 'isTimestamp')
#1 /var/www/project/vendor/magento/framework/Webapi/ServiceInputProcessor.php(158): Magento\Framework\Reflection\NameFinder->getGetterMethodName(Object(Zend\Code\Reflection\ClassReflection), 'Timestamp')
#2 /var/www/project/vendor/magento/framework/Webapi/ServiceInputProcessor.php(322): Magento\Framework\Webapi\ServiceInputProcessor->_createFromArray('Magento\\Catalog...', Array)
#3 /var/www/project/vendor/magento/framework/Webapi/ServiceInputProcessor.php(119): Magento\Framework\Webapi\ServiceInputProcessor->convertValue(Array, 'Magento\\Catalog...')
#4 /var/www/project/vendor/magento/module-webapi/Controller/Rest/InputParamsResolver.php(101): Magento\Framework\Webapi\ServiceInputProcessor->process('Magento\\Catalog...', 'updateStockItem...', Array)
#5 /var/www/project/vendor/magento/module-webapi/Controller/Rest.php(299): Magento\Webapi\Controller\Rest\InputParamsResolver->resolve()
#6 /var/www/project/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#7 /var/www/project/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /var/www/project/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /var/www/project/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#10 /var/www/project/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#11 {main}
```

**Comment by veloraven** [comment]
@vo1 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by vo1** [comment]
im a noob lol. Closed. Not an issue.
