### ISSUE TITLE
Magento can't rollback transactions while Test Transparent Transaction is still active

### ISSUE THREAD

**Issue by mhoerhold** [magento/magento2#10163]
### Steps to reproduce
- Magento Test "Magento\TestFramework\Db\Adapter\Mysql" opens a "TransparentTransaction"
- Magento Core "Magento\Framework\DB\Adapter\Pdo\Mysql" opens a normal transaction
- Magento Core "Magento\Framework\DB\Adapter\Pdo\Mysql" rollback the normal transaction
- Magento Core "Magento\Framework\DB\Adapter\Pdo\Mysql" opens a new normal transaction
    - this causes an error because rollback isn't complete
    - getTransactionLevel() returns "0" but the value of "$this->_transactionLevel" is "1"

### Preconditions

1. Magento 2.1.6
2. PHP 7.0.20
3. MySQL 5.5.55

### Steps to reproduce

1. I wrote a Rest service which delegates bundled requests to the corresponding Rest Resource.
2. To test this service I used the Integration Test FW.
3. So I tried to handle two request in one method call:
    - Create an allready existing Admin User
    - Update an existing Admin User

### Expected result

I expected that this method returns the following result:
- Create faild > Magento\Framework\Validator\Exception : A user with the same user name or email already exists.
- Successfully updated the user

### Actual result

1. But what I get is:
    - Create failed > Magento\Framework\Validator\Exception : A user with the same user name or email already exists.
    - Update failed > Exception: Rolled back transaction has not been completed correctly.
2. The corresponding exceptions are:
    - Magento\Framework\Validator\Exception: A user with the same user name or email already exists.
    #0 /var/www/magento/var/generation/Netresearch/RolesManagement/Model/User/Interceptor.php(960): Magento\Framework\Model\AbstractModel->validateBeforeSave()
    #1 /var/www/magento/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(395): Netresearch\RolesManagement\Model\User\Interceptor->validateBeforeSave()
    #2 /var/www/magento/vendor/netresearch/roles-management/Model/Rest/V1/UserResource.php(392): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Netresearch\RolesManagement\Model\User\Interceptor))
    #3 /var/www/magento/vendor/netresearch/roles-management/Model/Rest/V1/UserResource.php(365): Netresearch\RolesManagement\Model\Rest\V1\UserResource->updateUserModel(Object(Netresearch\RolesManagement\Model\Rest\V1\Data\User), Object(Netresearch\RolesManagement\Model\User\Interceptor))
    #4 /var/www/magento/vendor/netresearch/roles-management/Model/Rest/V1/UserResource.php(148): Netresearch\RolesManagement\Model\Rest\V1\UserResource->createUserModel(Object(Netresearch\RolesManagement\Model\Rest\V1\Data\User), Object(Netresearch\RolesManagement\Model\User\Interceptor))
    #5 /var/www/magento/vendor/netresearch/roles-management/Model/Rest/V1/UserResource.php(218): Netresearch\RolesManagement\Model\Rest\V1\UserResource->put('Test01234-2', Object(Netresearch\RolesManagement\Model\Rest\V1\Data\User))
    #6 /var/www/magento/vendor/netresearch/roles-management/Test/Integration/Api/Rest/V1/UserResourceInterfaceTest.php(408): Netresearch\RolesManagement\Model\Rest\V1\UserResource->postList(Array)
    #7 [internal function]: Netresearch\RolesManagement\Test\Integration\Api\Rest\V1\UserResourceInterfaceTest->testPostList()
    #8 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(1054): ReflectionMethod->invokeArgs(Object(Netresearch\RolesManagement\Test\Integration\Api\Rest\V1\UserResourceInterfaceTest), Array)
    #9 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(905): PHPUnit_Framework_TestCase->runTest()
    #10 phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php(686): PHPUnit_Framework_TestCase->runBare()
    #11 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(860): PHPUnit_Framework_TestResult->run(Object(Netresearch\RolesManagement\Test\Integration\Api\Rest\V1\UserResourceInterfaceTest))
    #12 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(722): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
    #13 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(722): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
    #14 phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php(517): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
    #15 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(186): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array, true)
    #16 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(116): PHPUnit_TextUI_Command->run(Array, true)
    #17 /usr/local/bin/phpunit(584): PHPUnit_TextUI_Command::main()
    #18 {main}
    - Exception: Rolled back transaction has not been completed correctly.
#0 /var/www/magento/vendor/magento/module-resource-connections/DB/Adapter/Pdo/MysqlProxy.php(203): Magento\Framework\DB\Adapter\Pdo\Mysql->beginTransaction()
#1 /var/www/magento/vendor/magento/framework/Model/ResourceModel/AbstractResource.php(49): Magento\ResourceConnections\DB\Adapter\Pdo\MysqlProxy->beginTransaction()
#2 /var/www/magento/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(386): Magento\Framework\Model\ResourceModel\AbstractResource->beginTransaction()
#3 /var/www/magento/vendor/netresearch/roles-management/Model/Rest/V1/UserResource.php(392): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Netresearch\RolesManagement\Model\User\Interceptor))
#4 /var/www/magento/vendor/netresearch/roles-management/Model/Rest/V1/UserResource.php(365): Netresearch\RolesManagement\Model\Rest\V1\UserResource->updateUserModel(Object(Netresearch\RolesManagement\Model\Rest\V1\Data\User), Object(Netresearch\RolesManagement\Model\User\Interceptor))
#5 /var/www/magento/vendor/netresearch/roles-management/Model/Rest/V1/UserResource.php(171): Netresearch\RolesManagement\Model\Rest\V1\UserResource->createUserModel(Object(Netresearch\RolesManagement\Model\Rest\V1\Data\User), Object(Netresearch\RolesManagement\Model\User\Interceptor))
#6 /var/www/magento/vendor/netresearch/roles-management/Model/Rest/V1/UserResource.php(208): Netresearch\RolesManagement\Model\Rest\V1\UserResource->putList(Array)
#7 /var/www/magento/vendor/netresearch/roles-management/Test/Integration/Api/Rest/V1/UserResourceInterfaceTest.php(408): Netresearch\RolesManagement\Model\Rest\V1\UserResource->postList(Array)
#8 [internal function]: Netresearch\RolesManagement\Test\Integration\Api\Rest\V1\UserResourceInterfaceTest->testPostList()
#9 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(1054): ReflectionMethod->invokeArgs(Object(Netresearch\RolesManagement\Test\Integration\Api\Rest\V1\UserResourceInterfaceTest), Array)
#10 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(905): PHPUnit_Framework_TestCase->runTest()
#11 phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php(686): PHPUnit_Framework_TestCase->runBare()
#12 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(860): PHPUnit_Framework_TestResult->run(Object(Netresearch\RolesManagement\Test\Integration\Api\Rest\V1\UserResourceInterfaceTest))
#13 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(722): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#14 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(722): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#15 phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php(517): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#16 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(186): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array, true)
#17 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(116): PHPUnit_TextUI_Command->run(Array, true)
#18 /usr/local/bin/phpunit(584): PHPUnit_TextUI_Command::main()
#19 {main}

### Suggestion
The class variable "$this->_transactionLevel" shouldn't used directly. I think it's better to use getTransactionLevel() and add some protected methods e.g. "increaseTransactionLevel()" and "decreaseTransactionLevel()". This should avoid that problem, because you can override this methods inside Magento\TestFramework\Db\Adapter\Mysql.

**Comment by magento-engcom-team** [comment]
@mhoerhold , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce.

**Comment by magento-engcom-team** [comment]
@mhoerhold, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
