### ISSUE TITLE
Exception thrown by order fixture when running integration tests

### ISSUE THREAD

**Issue by JosephLeedy** [magento/magento2#10296]
### Preconditions
1. Magento 2.1.7
2. PHP 7.0.6
3. MariaDB 10.1.13
4. Magestead 2.2.2
5. PHPUnit 4.1.0

### Steps to reproduce
1. Create an integration test with at least one test method.
2. Add `@magentoDataFixture Magento/Sales/_files/order.php` annotation to PHPDoc for test method, e.g.:
```
/**
 * @magentoDataFixture Magento/Sales/_files/order.php
 */
```
3. Run integration test with PHPUnit

### Expected result
1. Test should run and pass or fail based on defined assertions

### Actual result
1. Magento throws the following exception and stack trace:
```
Magento\Eav\Model\Entity\Attribute\Exception: The value of attribute "item_id" must be set in vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93
Stack trace:
#0 vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Eav\\Mod...', Array)
#1 vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Eav\\Mod...', Array)
#2 vendor/magento/framework/Validator/UniversalFactory.php(36): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Eav\\Mod...', Array)
#3 vendor/magento/module-eav/Model/Entity/AbstractEntity.php(655): Magento\Framework\Validator\UniversalFactory->create('Magento\\Eav\\Mod...', Array)
#4 vendor/magento/module-eav/Model/Entity/AbstractEntity.php(835): Magento\Eav\Model\Entity\AbstractEntity->walkAttributes('backend/validat...', Array, NULL)
#5 vendor/magento/module-catalog/Model/ResourceModel/Product.php(641): Magento\Eav\Model\Entity\AbstractEntity->validate(Object(Magento\Catalog\Model\Product\Interceptor))
#6 vendor/magento/module-catalog/Model/ProductRepository.php(525): Magento\Catalog\Model\ResourceModel\Product->validate(Object(Magento\Catalog\Model\Product\Interceptor))
#7 vendor/magento/framework/Interception/Interceptor.php(74): Magento\Catalog\Model\ProductRepository->save(Object(Magento\Catalog\Model\Product\Interceptor), false)
#8 vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Model\ProductRepository\Interceptor->___callParent('save', Array)
#9 vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'save', Object(Magento\Catalog\Model\ProductRepository\Interceptor), Array, 'configurablePro...')
#10 vendor/magento/module-configurable-product/Model/Plugin/AroundProductRepositorySave.php(62): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Catalog\Model\Product\Interceptor), false)
#11 vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\ConfigurableProduct\Model\Plugin\AroundProductRepositorySave->aroundSave(Object(Magento\Catalog\Model\ProductRepository\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor), false)
#12 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'save', Object(Magento\Catalog\Model\ProductRepository\Interceptor), Array, 'catalogInventor...')
#13 vendor/magento/module-catalog-inventory/Model/Plugin/AroundProductRepositorySave.php(74): Magento\Catalog\Model\ProductRepository\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor), false)
#14 vendor/magento/framework/Interception/Interceptor.php(142): Magento\CatalogInventory\Model\Plugin\AroundProductRepositorySave->aroundSave(Object(Magento\Catalog\Model\ProductRepository\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#15 var/generation/Magento/Catalog/Model/ProductRepository/Interceptor.php(26): Magento\Catalog\Model\ProductRepository\Interceptor->___callPlugins('save', Array, Array)
#16 dev/tests/integration/testsuite/Magento/Catalog/_files/product_simple.php(153): Magento\Catalog\Model\ProductRepository\Interceptor->save(Object(Magento\Catalog\Model\Product\Interceptor))
#17 dev/tests/integration/testsuite/Magento/Sales/_files/order.php(12): require('...')
#18 dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(171): require('...')
#19 dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(196): Magento\TestFramework\Annotation\DataFixture->_applyOneFixture('...')
#20 dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(89): Magento\TestFramework\Annotation\DataFixture->_applyFixtures(Array)
#21 [internal function]: Magento\TestFramework\Annotation\DataFixture->startTransaction(Object(My\Module\Test\Integration\Model\OrderLogTest))
#22 dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
#23 dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(96): Magento\TestFramework\EventManager->fireEvent('startTransactio...', Array)
#24 dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(81): Magento\TestFramework\Event\Transaction->_startTransaction(Object(My\Module\Test\Integration\Model\OrderLogTest))
#25 dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(46): Magento\TestFramework\Event\Transaction->_processTransactionRequests('startTest', Object(My\Module\Test\Integration\Model\OrderLogTest))
#26 [internal function]: Magento\TestFramework\Event\Transaction->startTest(Object(My\Module\Test\Integration\Model\OrderLogTest))
#27 dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
#28 dev/tests/integration/framework/Magento/TestFramework/Event/PhpUnit.php(126): Magento\TestFramework\EventManager->fireEvent('startTest', Array)
#29 vendor/phpunit/phpunit/src/Framework/TestResult.php(387): Magento\TestFramework\Event\PhpUnit->startTest(Object(My\Module\Test\Integration\Model\OrderLogTest))
#30 vendor/phpunit/phpunit/src/Framework/TestResult.php(624): PHPUnit_Framework_TestResult->startTest(Object(My\Module\Test\Integration\Model\OrderLogTest))
#31 vendor/phpunit/phpunit/src/Framework/TestCase.php(753): PHPUnit_Framework_TestResult->run(Object(My\Module\Test\Integration\Model\OrderLogTest))
#32 vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#33 vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#34 vendor/phpunit/phpunit/src/TextUI/TestRunner.php(426): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#35 {main}

Next Exception: Error in fixture: "dev/tests/integration/testsuite/Magento/Sales/_files/order.php".
 The value of attribute "item_id" must be set in dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php:174
Stack trace:
#0 dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(196): Magento\TestFramework\Annotation\DataFixture->_applyOneFixture('...')
#1 dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(89): Magento\TestFramework\Annotation\DataFixture->_applyFixtures(Array)
#2 [internal function]: Magento\TestFramework\Annotation\DataFixture->startTransaction(Object(My\Module\Test\Integration\Model\OrderLogTest))
#3 dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
#4 dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(96): Magento\TestFramework\EventManager->fireEvent('startTransactio...', Array)
#5 dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(81): Magento\TestFramework\Event\Transaction->_startTransaction(Object(My\Module\Test\Integration\Model\OrderLogTest))
#6 dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(46): Magento\TestFramework\Event\Transaction->_processTransactionRequests('startTest', Object(My\Module\Test\Integration\Model\OrderLogTest))
#7 [internal function]: Magento\TestFramework\Event\Transaction->startTest(Object(My\Module\Test\Integration\Model\OrderLogTest))
#8 dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
#9 dev/tests/integration/framework/Magento/TestFramework/Event/PhpUnit.php(126): Magento\TestFramework\EventManager->fireEvent('startTest', Array)
#10 vendor/phpunit/phpunit/src/Framework/TestResult.php(387): Magento\TestFramework\Event\PhpUnit->startTest(Object(My\Module\Test\Integration\Model\OrderLogTest))
#11 vendor/phpunit/phpunit/src/Framework/TestResult.php(624): PHPUnit_Framework_TestResult->startTest(Object(My\Module\Test\Integration\Model\OrderLogTest))
#12 vendor/phpunit/phpunit/src/Framework/TestCase.php(753): PHPUnit_Framework_TestResult->run(Object(My\Module\Test\Integration\Model\OrderLogTest))
#13 vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#14 vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#15 vendor/phpunit/phpunit/src/TextUI/TestRunner.php(426): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#16 {main}
 dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php:100
 dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php:81
 dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php:46
 dev/tests/integration/framework/Magento/TestFramework/EventManager.php:49
 dev/tests/integration/framework/Magento/TestFramework/Event/PhpUnit.php:126
```

**Comment by orlangur** [comment]
There are a lot of integration tests using this fixture successfully passing on `develop`: https://github.com/magento/magento2/search?utf8=✓&q=Magento%2FSales%2F_files%2Forder.php&type=

You can try to debug them to see what's different compared to your test.

**Comment by JosephLeedy** [comment]
I tried to run several tests from those search results, but they each returned separate errors.

```
$ phpunit testsuite/Magento/GiftMessage/Model/OrderItemRepositoryTest.php
PHPUnit 4.1.0 by Sebastian Bergmann.

Configuration read from /var/www/public/dev/tests/integration/phpunit.xml

FPHP Fatal error:  Uncaught Error: Call to a member function getItemId() on null in /var/www/public/dev/tests/integration/testsuite/Magento/GiftMessage/Model/OrderItemRepositoryTest.php:54
Stack trace:
#0 [internal function]: Magento\GiftMessage\Model\OrderItemRepositoryTest->testGet()
#1 /var/www/public/vendor/phpunit/phpunit/src/Framework/TestCase.php(950): ReflectionMethod->invokeArgs(Object(Magento\GiftMessage\Model\OrderItemRepositoryTest), Array)
#2 /var/www/public/vendor/phpunit/phpunit/src/Framework/TestCase.php(817): PHPUnit_Framework_TestCase->runTest()
#3 /var/www/public/vendor/phpunit/phpunit/src/Framework/TestResult.php(686): PHPUnit_Framework_TestCase->runBare()
#4 /var/www/public/vendor/phpunit/phpunit/src/Framework/TestCase.php(753): PHPUnit_Framework_TestResult->run(Object(Magento\GiftMessage\Model\OrderItemRepositoryTest))
#5 /var/www/public/vendor/phpunit/phpunit/src/Framework/TestSuite.php(675): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#6 /var/www/public/vendor/phpunit/phpunit/sr in /var/www/public/dev/tests/integration/testsuite/Magento/GiftMessage/Model/OrderItemRepositoryTest.php on line 54

Fatal error: Uncaught Error: Call to a member function getItemId() on null in /var/www/public/dev/tests/integration/testsuite/Magento/GiftMessage/Model/OrderItemRepositoryTest.php on line 54

Error: Call to a member function getItemId() on null in /var/www/public/dev/tests/integration/testsuite/Magento/GiftMessage/Model/OrderItemRepositoryTest.php on line 54

Call Stack:
    0.0003     468608   1. {main}() /usr/local/bin/phpunit-4.1.0.phar:0
    0.0091     812048   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit-4.1.0.phar:584
    0.0091     812144   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit-4.1.0.phar/phpunit/TextUI/Command.php:132
    1.4578   17958256   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit-4.1.0.phar/phpunit/TextUI/Command.php:179
    1.4671   18182384   5. PHPUnit_Framework_TestSuite->run() /var/www/public/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:426
   34.1331   36498416   6. PHPUnit_Framework_TestCase->run() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestSuite.php:675
   34.1331   36498416   7. PHPUnit_Framework_TestResult->run() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestCase.php:753
   38.6188   53663704   8. PHPUnit_Framework_TestCase->runBare() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestResult.php:686
   38.6424   54535992   9. PHPUnit_Framework_TestCase->runTest() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestCase.php:817
   38.6424   54536288  10. ReflectionMethod->invokeArgs() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestCase.php:950
   38.6424   54536296  11. Magento\GiftMessage\Model\OrderItemRepositoryTest->testGet() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestCase.php:950


=== Memory Usage System Stats ===
Memory usage (OS):	91.10M (157.07% of 58.00M reported by PHP)
Estimated memory leak:	33.10M (36.33% of used memory)
```

```
$ phpunit testsuite/Magento/Sales/Model/Order/Email/Sender/OrderSenderTest.php
PHPUnit 4.1.0 by Sebastian Bergmann.

Configuration read from /var/www/public/dev/tests/integration/phpunit.xml

FPHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Payment\Helper\Data::getInfoBlockHtml() must implement interface Magento\Payment\Model\InfoInterface, null given, called in /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/OrderSender.php on line 152 and defined in /var/www/public/vendor/magento/module-payment/Helper/Data.php:204
Stack trace:
#0 /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/OrderSender.php(152): Magento\Payment\Helper\Data->getInfoBlockHtml(NULL, '1')
#1 /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/OrderSender.php(125): Magento\Sales\Model\Order\Email\Sender\OrderSender->getPaymentHtml(Object(Tmw\Migration\Model\Sales\Order\Interceptor))
#2 /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender.php(71): Magento\Sales\Model\Order\Email\Sender\OrderSender->prepareTemplate(Object(Tmw\Migration\Model\Sales\Order\Interceptor))
#3 /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/OrderSender.php(102): in /var/www/public/vendor/magento/module-payment/Helper/Data.php on line 204

Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Payment\Helper\Data::getInfoBlockHtml() must implement interface Magento\Payment\Model\InfoInterface, null given, called in /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/OrderSender.php on line 152 and defined in /var/www/public/vendor/magento/module-payment/Helper/Data.php on line 204

TypeError: Argument 1 passed to Magento\Payment\Helper\Data::getInfoBlockHtml() must implement interface Magento\Payment\Model\InfoInterface, null given, called in /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/OrderSender.php on line 152 in /var/www/public/vendor/magento/module-payment/Helper/Data.php on line 204

Call Stack:
    0.0003     468608   1. {main}() /usr/local/bin/phpunit-4.1.0.phar:0
    0.0091     812048   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit-4.1.0.phar:584
    0.0091     812144   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit-4.1.0.phar/phpunit/TextUI/Command.php:132
    1.6085   17923704   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit-4.1.0.phar/phpunit/TextUI/Command.php:179
    1.6159   18147832   5. PHPUnit_Framework_TestSuite->run() /var/www/public/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:426
   32.0216   36208560   6. PHPUnit_Framework_TestCase->run() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestSuite.php:675
   32.0216   36208560   7. PHPUnit_Framework_TestResult->run() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestCase.php:753
   33.7502   52256888   8. PHPUnit_Framework_TestCase->runBare() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestResult.php:686
   33.7515   52623080   9. PHPUnit_Framework_TestCase->runTest() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestCase.php:817
   33.7515   52623376  10. ReflectionMethod->invokeArgs() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestCase.php:950
   33.7515   52623384  11. Magento\Sales\Model\Order\Email\Sender\OrderSenderTest->testSendNewOrderEmail() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestCase.php:950
   34.4191   57616776  12. Magento\Sales\Model\Order\Email\Sender\OrderSender->send() /var/www/public/dev/tests/integration/testsuite/Magento/Sales/Model/Order/Email/Sender/OrderSenderTest.php:28
   34.4192   57616856  13. Magento\Sales\Model\Order\Email\Sender->checkAndSend() /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/OrderSender.php:102
   34.4193   57616928  14. Magento\Sales\Model\Order\Email\Sender\OrderSender->prepareTemplate() /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender.php:71
   34.4260   57916200  15. Magento\Sales\Model\Order\Email\Sender\OrderSender->getPaymentHtml() /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/OrderSender.php:125
   34.4266   57916200  16. Magento\Payment\Helper\Data->getInfoBlockHtml() /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/OrderSender.php:152


=== Memory Usage System Stats ===
Memory usage (OS):	89.22M (159.32% of 56.00M reported by PHP)
Estimated memory leak:	33.22M (37.23% of used memory)
```

```
$ phpunit testsuite/Magento/Sales/Model/Order/Email/Sender/ShipmentSenderTest.php
PHPUnit 4.1.0 by Sebastian Bergmann.

Configuration read from /var/www/public/dev/tests/integration/phpunit.xml

FPHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Payment\Helper\Data::getInfoBlockHtml() must implement interface Magento\Payment\Model\InfoInterface, null given, called in /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php on line 146 and defined in /var/www/public/vendor/magento/module-payment/Helper/Data.php:204
Stack trace:
#0 /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php(146): Magento\Payment\Helper\Data->getInfoBlockHtml(NULL, '1')
#1 /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php(111): Magento\Sales\Model\Order\Email\Sender\ShipmentSender->getPaymentHtml(Object(Tmw\Migration\Model\Sales\Order\Interceptor))
#2 /var/www/public/dev/tests/integration/testsuite/Magento/Sales/Model/Order/Email/Sender/ShipmentSenderTest.php(33): Magento\Sales\Model\Order\Email\Sender\ShipmentSender->send(Object(Magento\Sales\Model\Order\Shipment), true)
#3 [internal function]: Magento\Sales\Model\Order\Email in /var/www/public/vendor/magento/module-payment/Helper/Data.php on line 204

Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Payment\Helper\Data::getInfoBlockHtml() must implement interface Magento\Payment\Model\InfoInterface, null given, called in /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php on line 146 and defined in /var/www/public/vendor/magento/module-payment/Helper/Data.php on line 204

TypeError: Argument 1 passed to Magento\Payment\Helper\Data::getInfoBlockHtml() must implement interface Magento\Payment\Model\InfoInterface, null given, called in /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php on line 146 in /var/www/public/vendor/magento/module-payment/Helper/Data.php on line 204

Call Stack:
    0.0004     468608   1. {main}() /usr/local/bin/phpunit-4.1.0.phar:0
    0.0161     812048   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit-4.1.0.phar:584
    0.0161     812144   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit-4.1.0.phar/phpunit/TextUI/Command.php:132
    1.7776   17934944   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/local/bin/phpunit-4.1.0.phar/phpunit/TextUI/Command.php:179
    1.7849   18159072   5. PHPUnit_Framework_TestSuite->run() /var/www/public/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:426
   32.4336   36474824   6. PHPUnit_Framework_TestCase->run() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestSuite.php:675
   32.4336   36474824   7. PHPUnit_Framework_TestResult->run() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestCase.php:753
   34.0911   51610616   8. PHPUnit_Framework_TestCase->runBare() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestResult.php:686
   34.0924   51976776   9. PHPUnit_Framework_TestCase->runTest() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestCase.php:817
   34.0924   51977072  10. ReflectionMethod->invokeArgs() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestCase.php:950
   34.0924   51977080  11. Magento\Sales\Model\Order\Email\Sender\ShipmentSenderTest->testSend() /var/www/public/vendor/phpunit/phpunit/src/Framework/TestCase.php:950
   34.2904   57027208  12. Magento\Sales\Model\Order\Email\Sender\ShipmentSender->send() /var/www/public/dev/tests/integration/testsuite/Magento/Sales/Model/Order/Email/Sender/ShipmentSenderTest.php:33
   34.2961   57327816  13. Magento\Sales\Model\Order\Email\Sender\ShipmentSender->getPaymentHtml() /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php:111
   34.2964   57327888  14. Magento\Payment\Helper\Data->getInfoBlockHtml() /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php:146


=== Memory Usage System Stats ===
Memory usage (OS):  91.10M (157.06% of 58.00M reported by PHP)
Estimated memory leak:  33.10M (36.33% of used memory)
```

**Comment by JosephLeedy** [comment]
I think there is something wrong with my environment because these tests work on a clean install of M2 2.1.7 in another Magestead box.

**Comment by orlangur** [comment]
Thanks for your investigation, although sometimes tests are failing when running separately due to implicit dependencies in your env it looks like contents of `/dev/tests/` and `/vendor/` correspond to different Magento versions.

**Comment by JosephLeedy** [comment]
I tracked the issue down to a third-party extension that is overriding the Order model and causing the test order to not be saved correctly.

**Comment by tuyennn** [comment]
@JosephLeedy Could you name which 3rd party extension which made the error?
```
Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Payment\Helper\Data::getInfoBlockHtml() must implement interface Magento\Payment\Model\InfoInterface, null given, called in /var/www/public/vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php on line 146 and defined in /var/www/public/vendor/magento/module-payment/Helper/Data.php on line 204
```
I'm facing same experience on my projects but it has so many extensions to trackdown

**Comment by JosephLeedy** [comment]
I'm sorry, but I do not remember what it was.
