### ISSUE TITLE
Magento 2 Admin Login gives: There has been an error processing your request Invalid scope type ''

### ISSUE THREAD

**Issue by alainstout** [magento/magento2#10365]
When I login at Magento 2 Admin I get:

> There has been an error processing your request
> 
> Invalid scope type ''

The error log say:

```
a:4:{i:0;s:21:"Invalid scope type ''";i:1;s:6480:"#0 ROOT/vendor/magento/framework/App/Config/ScopeCodeResolver.php(48): Magento\Framework\App\ScopeResolverPool->get(NULL)
#1 ROOT/vendor/magento/framework/App/Config.php(79): Magento\Framework\App\Config\ScopeCodeResolver->resolve(NULL, NULL)
#2 ROOT/vendor/magento/module-config/Model/Config.php(480): Magento\Framework\App\Config->getValue('design/theme/th...', NULL, NULL)
#3 ROOT/app/code/Codazon/ThemeOptions/Backend/Model/Menu/Builder/Plugin.php(35): Magento\Config\Model\Config->getConfigDataValue('design/theme/th...')
#4 ROOT/app/code/Codazon/ThemeOptions/Backend/Model/Menu/Builder/Plugin.php(62): Codazon\ThemeOptions\Backend\Model\Menu\Builder\Plugin->getThemeId()
#5 ROOT/vendor/magento/framework/Interception/Interceptor.php(152): Codazon\ThemeOptions\Backend\Model\Menu\Builder\Plugin->afterGetResult(Object(Magento\Backend\Model\Menu\Builder\Interceptor), Object(Magento\Backend\Model\Menu))
#6 ROOT/var/generation/Magento/Backend/Model/Menu/Builder/Interceptor.php(26): Magento\Backend\Model\Menu\Builder\Interceptor->___callPlugins('getResult', Array, Array)
#7 ROOT/vendor/magento/module-backend/Model/Menu/Config.php(146): Magento\Backend\Model\Menu\Builder\Interceptor->getResult(Object(Magento\Backend\Model\Menu))
#8 ROOT/vendor/magento/module-backend/Model/Menu/Config.php(109): Magento\Backend\Model\Menu\Config->_initMenu()
#9 ROOT/vendor/magento/module-backend/Model/Url.php(348): Magento\Backend\Model\Menu\Config->getMenu()
#10 ROOT/vendor/magento/module-backend/Model/Url.php(308): Magento\Backend\Model\Url->_getMenu()
#11 ROOT/vendor/magento/module-backend/Controller/Adminhtml/Index/Index.php(21): Magento\Backend\Model\Url->getStartupPageUrl()
#12 ROOT/vendor/magento/framework/App/Action/Action.php(102): Magento\Backend\Controller\Adminhtml\Index\Index->execute()
#13 ROOT/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#14 ROOT/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#15 ROOT/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callParent('dispatch', Array)
#16 ROOT/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminAuthentica...')
#17 ROOT/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#18 ROOT/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 ROOT/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminMassaction...')
#20 ROOT/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 ROOT/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 ROOT/var/generation/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php(26): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#23 ROOT/vendor/magento/framework/App/FrontController.php(55): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#24 ROOT/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#25 ROOT/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#26 ROOT/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#27 ROOT/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 ROOT/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 ROOT/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#30 ROOT/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 ROOT/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#32 ROOT/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#33 {main}";s:3:"url";s:97:"admin/index/index/key/d6da202f324298e6492136f19b5200d311ec208d3fe62be48745910532c707dc/";s:11:"script_name";s:10:"/index.php";}
```

Nobody knows, google says nothing

Anyone know are familiar with this solution?

Many Thanks

**Comment by korostii** [comment]
I would guess that you've set a custom theme for the `adminhtml` area and then deleted the theme from disk manually. 
If that's the case, you'll need to either restore that theme's folder or edit the corresponding config value in your database manually (make sure to make a backup database dump before doing that).

**Comment by alainstout** [comment]
Thanks @korostii , you come as most close as you can get based on all I have searched right now. Makes perfect sense because that can be true. It probably is something small like in database. You can maybe a bit more precise where to do what? I am looking it all over but am not sure what to do. Thanks a lot again man

**Comment by korostii** [comment]
Sure, no problem.
I'd look into `SELECT * from core_config_data WHERE path = 'design/theme/theme_id';` to make sure it's the cause and what needs to be corrected. 
Here's what it normally looks like: http://take.ms/VppFM (the "stores" entries are used by multiple storefronts, you might have a single one instead and different numbers - that's fine).

**Comment by alainstout** [comment]
Thanks @korostii appreciate your support very much and a lot.

Had already checked theme_id but as far as I concern it is okay:
https://ibb.co/eRkBx5

I have changed it to NULL but then frontend site doesn't work anymore.
Or am I doing it wrong when I change 14 to NULL, have I also to change the config_id?
And you are right I only have this theme_id but I have multiple store views.
Is that maybe what's wrong?

Can it be here `SELECT * from store_group`

https://ibb.co/eRkBx5

Or `SELECT * from store_website`

https://ibb.co/nj1Ujk

Is there a fault as you see it?

I can login in admin and then they gave the error as I started this issue.

Thanks a Lot man. Your help is definitely very much appreciated.

Regards

Alain

**Comment by korostii** [comment]
Having both admin and base stores is normal, I wouldn advise not to touch those.
> https://ibb.co/eRkBx5

Yeah well as far as I understand the issue is that the theme is also being used by admin(which it shouldn't) when it's set under default (global) scope. I'd try to correct his row and then adding a new setting for the storefront on storeview level, kind of like the following:
`(,'default', 0, 'design/theme/theme_id', NULL)`
`(,'stores', 1, 'design/theme/theme_id', 14)`

**Comment by alainstout** [comment]
Dear friend @korostii have exactly did what you said, but everything is exactly the same as before. Same error but website works www.takoda.shop by the way.
Thanks Alain, Really hope you know why. Really appreciate someone being this close and you time for support man!

**Comment by korostii** [comment]
Well, I'm out of ideas on that front.

Hm, now that's interesting:
`Notice: Undefined index: default in /home/alainstout/public_html/app/code/Codazon/ThemeOptions/Framework/App/Config/Initial.php on line 72`
(at https://www.takoda.shop/nl/ )

I wonder if the error you're having is somehow related to this custom module's code. I assume it goes with the theme? Have you tried contacting the theme's vendor, maybe it's a known issue and they have a solution?

**Comment by alainstout** [comment]
@Korostii that's after I did what you recommended before it wasn't I didn't know yet didn't checked it.
Maybe they know but you've to pay for support.
There been a lot of issues this far but I think it must be fixable.

Van: korostii
Verstuurd: woensdag 2 augustus 21:34
Onderwerp: Re: [magento/magento2] Magento 2 Admin Login gives: There has been an error processing your request Invalid scope type '' (#10365)
Aan: magento/magento2
Cc: alainstout, Author


Well, I'm out of ideas on that front.
Hm, now that's interesting:
Notice: Undefined index: default in /home/alainstout/public_html/app/code/Codazon/ThemeOptions/Framework/App/Config/Initial.php on line 72
(at https://www.takoda.shop/nl/ )
I wonder if the error you're having is somehow related to this custom module's code. I assume it goes with the theme? Have you tried contacting the theme's vendor, maybe it's a known issue and they have a solution?

**Comment by magento-engcom-team** [comment]
@alainstout Please try to reproduce the issue with clean Magento installation without 3-rd party extensions. Multiple usages of third party customization are visible in the stack trace.
Admin login is a critical flow and covered with multiple automated tests which are executed extensively. 
Thank you.

**Comment by magento-engcom-team** [comment]
@alainstout we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by dfvincent** [comment]
I'm having the same issue when I try and migrate a Magento CE 1.7.0.2 to Magento Open Source 2.2.3.
Here are the steps I used:
(1) Did a fresh install of 2.2.3
(2) composer config repositories.magento composer https://repo.magento.com
(3) composer require magento/data-migration-tool:2.2.3
(4) updated my data-migration-tool/etc/1.7.0.2/config.xml file to contain my source (1.7.0.2)db and destination (2.2.3)db credentials and 1.7.0.2 crypt key.
(5) php bin/magento migrate:settings --reset vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.7.0.2/config.xml
(6) php bin/magento migrate:data --reset --auto vendor/magento/data-migration-tool/etc/opensource-to-opensource/1.7.0.2/config.xml
(7) php bin/magento indexer:reindex
(8) php -f bin/magento cache:clean

All steps worked properly.
But when I go to my website, I get the following error:
An error has happened during application run. See exception log for details. Could not write error message to log. Please use developer mode to see the message. 

Exception.log simply says:
[2018-04-20 15:26:29] main.CRITICAL: Invalid scope type ''
 {"exception":"[object] (InvalidArgumentException(code: 0):
  Invalid scope type '' at /home/.../vendor/magento/framework/App/ScopeResolverPool.php:40)"} []

I have now tried the migration procedure 6 times on mutiple servers, all configured with the correct magento stack requirements.

**Comment by dfvincent** [comment]
I WAS successful in migrating from MCE 1.7.0.2 to MOS 2.0.18
BUT when I tried to further upgrade MOS 2.0.18 to MOS 2.2.3,
the error returns:
[2018-04-20 15:26:29] main.CRITICAL: Invalid scope type ''
 {"exception":"[object] (InvalidArgumentException(code: 0):
  Invalid scope type '' at /home/.../vendor/magento/framework/App/ScopeResolverPool.php:40)"} []

**Comment by ananth-iyer** [comment]
@dfvincent Reason behind this is scope value is empty in core_config_data, run below SQL query:
**SELECT * FROM `core_config_data` WHERE `scope` = ''**

Run above query in your Magento 1 database also

You must delete the empty rows in Magento 1 then start the settings migration process.

**Comment by gkhere98** [comment]
1 exception(s):
Exception #0 (InvalidArgumentException): Invalid scope type ''

Exception #0 (InvalidArgumentException): Invalid scope type ''
<pre>#1 Magento\Framework\App\Config\ScopeCodeResolver->resolve() called at [vendor/magento/framework/App/Config.php:69]
#2 Magento\Framework\App\Config->getValue() called at [vendor/magento/framework/App/MutableScopeConfig.php:36]
#3 Magento\Framework\App\MutableScopeConfig->getValue() called at [vendor/magento/module-config/Model/Config.php:698]
#4 Magento\Config\Model\Config->getConfigDataValue() called at [app/code/Codazon/ThemeOptions/Backend/Model/Menu/Builder/Plugin.php:35]
#5 Codazon\ThemeOptions\Backend\Model\Menu\Builder\Plugin->getThemeId() called at [app/code/Codazon/ThemeOptions/Backend/Model/Menu/Builder/Plugin.php:62]
#6 Codazon\ThemeOptions\Backend\Model\Menu\Builder\Plugin->afterGetResult() called at [vendor/magento/framework/Interception/Interceptor.php:146]
#7 Magento\Backend\Model\Menu\Builder\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#8 Magento\Backend\Model\Menu\Builder\Interceptor->___callPlugins() called at [generated/code/Magento/Backend/Model/Menu/Builder/Interceptor.php:39]
#9 Magento\Backend\Model\Menu\Builder\Interceptor->getResult() called at [vendor/magento/module-backend/Model/Menu/Config.php:148]
#10 Magento\Backend\Model\Menu\Config->_initMenu() called at [vendor/magento/module-backend/Model/Menu/Config.php:111]
#11 Magento\Backend\Model\Menu\Config->getMenu() called at [vendor/magento/module-backend/Model/Url.php:365]
#12 Magento\Backend\Model\Url->_getMenu() called at [vendor/magento/module-backend/Model/Url.php:325]
#13 Magento\Backend\Model\Url->getStartupPageUrl() called at [vendor/magento/module-backend/Controller/Adminhtml/Index/Index.php:24]
#14 Magento\Backend\Controller\Adminhtml\Index\Index->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#15 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#16 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php:51]
#17 Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#18 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#19 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins() called at [generated/code/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php:26]
#20 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#21 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:151]
#22 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#23 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#24 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#25 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#26 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#27 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins() called at [generated/code/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php:39]
#28 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#29 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#30 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#31 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#32 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]

**Comment by gkhere98** [comment]
im getting this error   how can i fix it

**Comment by ananth-iyer** [comment]
@dfvincent Reason behind this is scope value is empty in core_config_data, run below SQL query:
SELECT * FROM core_config_data WHERE scope = ''

Run above query in your Magento 1 database also

You must delete the empty rows in Magento 1 then start the settings migration process.

**Comment by magenizr** [comment]
I ran into the same issue and the below query fixed it.

`DELETE FROM core_config_data WHERE scope = '';`

Make sure you check first what `SELECT FROM core_config_data WHERE scope = '';` returns, just in case you still need some config values. Creating a backup of a database is always a good advice.
