### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class '' not found 

### ISSUE THREAD

**Issue by ivanraz** [magento/magento2#10647]
Our magento site has been up for the last week and we had no issues at all, working under production mode just fine until we've  got this issue.

Magento 2.1.7 EE
PHP 7.0.21 (fpm-fcgi) (built: Jul  6 2017 09:15:35)
MySQL 5.7.18-16 Percona Server
Redis 3.2.10, for cache and storage

Don't really know how to reproduce this issue but we noticed that it usually happens when there is an activity in the back office, usual stuff like managing products and categories.

Does not happen at all at night when there's no activity.
There is no report produced when the bug happens and I'm only able to get the bits of log from our httpd error log or new relic.

httpd error log:
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class '' not found in vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93
Stack trace:
#0 vendor/magento/framework/ObjectManager/Factory/Compiled.php(95): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('', Array)
#1 vendor/magento/framework/ObjectManager/ObjectManager.php(66): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('', Array)
#2 vendor/magento/module-advanced-search/Model/SuggestedQueries.php(76): Magento\\Framework\\ObjectManager\\ObjectManager->create('')
#3 vendor/magento/module-advanced-search/Model/SuggestedQueries.php(63): Magento\\AdvancedSearch\\Model\\SuggestedQueries->getDataProvider()

new relic stack trace:

Error: Uncaught exception 'Error' with message 'Class '' not found' in .../vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93

Stack trace
.../vendor/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php (95)
.../vendor/magento/vendor/magento/framework/ObjectManager/ObjectManager.php (66)
.../vendor/magento/vendor/magento/module-advanced-search/Model/SuggestedQueries.php (76)
.../vendor/magento/vendor/magento/module-advanced-search/Model/SuggestedQueries.php (63)
.../vendor/magento/vendor/magento/module-advanced-search/Block/SearchData.php (60)
.../vendor/magento/var/view_preprocessed/html/vendor/magento/module-advanced-search/view/frontend/templates/search_data.phtml (1)
.../vendor/magento/vendor/magento/framework/View/TemplateEngine/Php.php (59)
.../vendor/magento/vendor/magento/framework/View/Element/Template.php (255)
.../vendor/magento/vendor/magento/framework/View/Element/Template.php (279)
.../vendor/magento/vendor/magento/framework/View/Element/AbstractBlock.php (659)
.../vendor/magento/vendor/magento/framework/View/Layout.php (542)
.../vendor/magento/vendor/magento/framework/View/Layout.php (518)
.../vendor/magento/vendor/magento/framework/View/Layout.php (472)
.../vendor/magento/vendor/magento/framework/View/Layout.php (569)
.../vendor/magento/vendor/magento/framework/View/Layout.php (520)
.../vendor/magento/vendor/magento/framework/View/Layout.php (472)
.../vendor/magento/vendor/magento/framework/View/Element/AbstractBlock.php (499)
.../vendor/magento/vendor/magento/module-catalog/Block/Product/ListProduct.php (235)
.../vendor/magento/var/view_preprocessed/html/app/design/frontend/Smartwave/porto/Magento_Catalog/templates/product/list.phtml (1)
.../vendor/magento/vendor/magento/framework/View/TemplateEngine/Php.php (59)
.../vendor/magento/vendor/magento/framework/View/Element/Template.php (255)
.../vendor/magento/vendor/magento/framework/View/Element/Template.php (279)
.../vendor/magento/vendor/magento/framework/View/Element/AbstractBlock.php (659)
.../vendor/magento/vendor/magento/framework/Interception/Interceptor.php (146)
.../vendor/magento/var/generation/Magento/Catalog/Block/Product/ListProduct/Interceptor.php (52)
.../vendor/magento/vendor/magento/framework/View/Layout.php (542)
.../vendor/magento/vendor/magento/framework/View/Layout.php (518)
.../vendor/magento/vendor/magento/framework/View/Layout.php (472)
.../vendor/magento/vendor/magento/framework/View/Element/AbstractBlock.php (499)
.../vendor/magento/vendor/magento/module-catalog-search/Block/Result.php (168)
.../vendor/magento/var/view_preprocessed/html/vendor/magento/module-catalog-search/view/frontend/templates/result.phtml (1)
.../vendor/magento/vendor/magento/framework/View/TemplateEngine/Php.php (59)
.../vendor/magento/vendor/magento/framework/View/Element/Template.php (255)
.../vendor/magento/vendor/magento/framework/View/Element/Template.php (279)
.../vendor/magento/vendor/magento/framework/View/Element/AbstractBlock.php (659)
.../vendor/magento/vendor/magento/framework/View/Layout.php (542)
.../vendor/magento/vendor/magento/framework/View/Layout.php (518)
.../vendor/magento/vendor/magento/framework/View/Layout.php (472)
.../vendor/magento/vendor/magento/framework/View/Layout.php (569)
.../vendor/magento/vendor/magento/framework/View/Layout.php (520)
.../vendor/magento/vendor/magento/framework/View/Layout.php (472)
.../vendor/magento/vendor/magento/framework/View/Layout.php (569)
.../vendor/magento/vendor/magento/framework/View/Layout.php (520)
.../vendor/magento/vendor/magento/framework/View/Layout.php (472)
.../vendor/magento/vendor/magento/framework/View/Layout.php (569)
.../vendor/magento/vendor/magento/framework/View/Layout.php (520)
.../vendor/magento/vendor/magento/framework/View/Layout.php (472)
.../vendor/magento/vendor/magento/framework/View/Layout.php (569)
.../vendor/magento/vendor/magento/framework/View/Layout.php (520)
.../vendor/magento/vendor/magento/framework/View/Layout.php (472)
.../vendor/magento/vendor/magento/framework/View/Layout.php (569)
.../vendor/magento/vendor/magento/framework/View/Layout.php (520)
.../vendor/magento/vendor/magento/framework/View/Layout.php (472)
.../vendor/magento/vendor/magento/framework/View/Layout.php (569)
.../vendor/magento/vendor/magento/framework/View/Layout.php (520)
.../vendor/magento/vendor/magento/framework/View/Layout.php (472)
.../vendor/magento/vendor/magento/framework/View/Layout.php (938)
.../vendor/magento/vendor/magento/framework/Interception/Interceptor.php (146)
.../vendor/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php (52)
.../vendor/magento/vendor/magento/framework/View/Result/Page.php (243)
.../vendor/magento/vendor/magento/framework/View/Result/Layout.php (164)
.../vendor/magento/vendor/magento/framework/Interception/Interceptor.php (74)
.../vendor/magento/vendor/magento/framework/Interception/Chain/Chain.php (70)
.../vendor/magento/vendor/magento/framework/Interception/Chain/Chain.php (63)
.../vendor/magento/CacheWarmer/Plugin/CollectPlugin.php (66)
.../vendor/magento/vendor/magento/framework/Interception/Chain/Chain.php (67)
.../vendor/magento/vendor/magento/framework/Interception/Chain/Chain.php (63)
.../vendor/magento/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php (74)
.../vendor/magento/vendor/magento/framework/Interception/Chain/Chain.php (67)
.../vendor/magento/vendor/magento/framework/Interception/Interceptor.php (138)
.../vendor/magento/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php (67)
.../vendor/magento/vendor/magento/framework/Interception/Interceptor.php (142)
.../vendor/magento/var/generation/Magento/Framework/View/Result/Page/Interceptor.php (39)
.../vendor/magento/vendor/magento/framework/App/Http.php (139)
.../vendor/magento/vendor/magento/framework/App/Bootstrap.php (258)
.../vendor/magento/index.php (39)

Happens on random pages in the frontend.

**Comment by misha-kotov** [comment]
Thanks for raising the issue, however we ask you to please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Community Edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.

**Comment by gofornaman** [comment]
Did u find any solution for this?

**Comment by ivanraz** [comment]
@warmachine0609, Yes.
Basically, we experienced some weird behavior in our redis backend cache storage. For some reason all the default configuration values that are stored in cache were resetted, the default configuration represent the values that you have in core_config_data table, the values were returning null.

At the time that I've opened the ticket we used magento ee 2.1.7, we compared the related code with 2.1.8 and we noticed the whole thing was pretty much refractored. We didn't upgrade yet to 2.1.8 but magento enterprise support provided us with a patch. Patch mostly consists out of the code that is in 2.1.8.

**Comment by misha-kotov** [comment]
It was an issue that was fixed in 2.1.8. You can see the description of the issue in the 2.1.8 release notes - the last bullet point in the "[Installation and Deployment](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.8EE.html#installation-and-deployment)" section

**Comment by zeeshan2523806** [comment]
do you find the solution for that ? For me i have the class exist in the defined directory, and i am trying to include that class through object manager buts somehow Magento us unable to get the class even the classname and path are also correct, please suggest.

**Comment by sangthieu** [comment]
I have same problem in magento 2.3.3

2020/05/14 23:46:34 [error] 13402#13402: *6514446 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Magento\Framework\Phrase\Renderer\Composite' not found in ../vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116
Stack trace:
#0 ../vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#1 ../vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#2 ../vendor/magento/framework/App/Area.php(248): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#3 ../vendor/magento/framework/App/Area.php(216): Magento\Framework\App\Area->_initTranslate()

**Comment by luciandex** [comment]
This error shows up (for me) after run `bin/magento setup:di:compile` command, and after that `composer dump-autoload`.

I recomend to (re)run the following commands:
`bin/magento deploy:mode:set developer`
`bin/magento c:c` (shorthand for cache:clear)

I hope someone find this helpful.
