### ISSUE TITLE
magento 2.1.8 invalid argument supplied when open stores->configuration

### ISSUE THREAD

**Issue by tomnyson** [magento/magento2#10708]
### Preconditions

1. magento 2.1.8 ,mysql 5.7 ,php 7.0
2. 

### Steps to reproduce

1. open stores
2. choose configuration
3. 

### Expected result

1.  show error
1 exception(s):
Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\newtheme\vendor\magento\module-config\Model\Config\Structure\Mapper\Sorting.php on line 34

Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\newtheme\vendor\magento\module-config\Model\Config\Structure\Mapper\Sorting.php on line 34
#0 C:\xampp\htdocs\newtheme\vendor\magento\module-config\Model\Config\Structure\Mapper\Sorting.php(34): Magento\Framework\App\ErrorHandler->handler(2, 'Invalid argumen...', 'C:\\xampp\\htdocs...', 34, Array)
#1 C:\xampp\htdocs\newtheme\vendor\magento\module-config\Model\Config\Structure\Mapper\Sorting.php(23): Magento\Config\Model\Config\Structure\Mapper\Sorting->_processConfig('\n\t\t')
#2 C:\xampp\htdocs\newtheme\vendor\magento\module-config\Model\Config\Structure\Converter.php(64): Magento\Config\Model\Config\Structure\Mapper\Sorting->map(Array)
#3 C:\xampp\htdocs\newtheme\vendor\magento\framework\Interception\Interceptor.php(146): Magento\Config\Model\Config\Structure\Converter->convert(Object(DOMDocument))
#4 C:\xampp\htdocs\newtheme\var\generation\Magento\Config\Model\Config\Structure\Converter\Interceptor.php(26): Magento\Config\Model\Config\Structure\Converter\Interceptor->___callPlugins('convert', Array, Array)
#5 C:\xampp\htdocs\newtheme\vendor\magento\module-config\Model\Config\Structure\Reader.php(115): Magento\Config\Model\Config\Structure\Converter\Interceptor->convert(Object(DOMDocument))
#6 C:\xampp\htdocs\newtheme\vendor\magento\framework\Config\Reader\Filesystem.php(127): Magento\Config\Model\Config\Structure\Reader->_readFiles(Object(Magento\Framework\Config\FileIterator))
#7 C:\xampp\htdocs\newtheme\vendor\magento\framework\Config\Data\Scoped.php(103): Magento\Framework\Config\Reader\Filesystem->read('adminhtml')
#8 C:\xampp\htdocs\newtheme\vendor\magento\framework\Config\Data\Scoped.php(81): Magento\Framework\Config\Data\Scoped->_loadScopedData()
#9 C:\xampp\htdocs\newtheme\vendor\magento\module-config\Model\Config\Structure.php(73): Magento\Framework\Config\Data\Scoped->get()
#10 C:\xampp\htdocs\newtheme\var\generation\Magento\Config\Model\Config\Structure\Interceptor.php(14): Magento\Config\Model\Config\Structure->__construct(Object(Magento\Config\Model\Config\Structure\Data), Object(Magento\Config\Model\Config\Structure\Element\Iterator\Tab), Object(Magento\Config\Model\Config\Structure\Element\FlyweightFactory), Object(Magento\Config\Model\Config\ScopeDefiner))
#11 C:\xampp\htdocs\newtheme\vendor\magento\framework\ObjectManager\Factory\AbstractFactory.php(93): Magento\Config\Model\Config\Structure\Interceptor->__construct(Object(Magento\Config\Model\Config\Structure\Data), Object(Magento\Config\Model\Config\Structure\Element\Iterator\Tab), Object(Magento\Config\Model\Config\Structure\Element\FlyweightFactory), Object(Magento\Config\Model\Config\ScopeDefiner))
#12 C:\xampp\htdocs\newtheme\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Config\\...', Array)
#13 C:\xampp\htdocs\newtheme\vendor\magento\framework\ObjectManager\ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Config\\...')
#14 C:\xampp\htdocs\newtheme\vendor\magento\framework\ObjectManager\Factory\AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Config\\...')
#15 C:\xampp\htdocs\newtheme\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Config\\...', NULL, 'configStructure', 'Magento\\Config\\...')
#16 C:\xampp\htdocs\newtheme\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Config\\...', Array, Array)
#17 C:\xampp\htdocs\newtheme\vendor\magento\framework\ObjectManager\ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Config\\...', Array)
#18 C:\xampp\htdocs\newtheme\vendor\magento\framework\App\ActionFactory.php(40): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Config\\...')
#19 C:\xampp\htdocs\newtheme\vendor\magento\framework\App\Router\Base.php(300): Magento\Framework\App\ActionFactory->create('Magento\\Config\\...')
#20 C:\xampp\htdocs\newtheme\vendor\magento\framework\App\Router\Base.php(161): Magento\Framework\App\Router\Base->matchAction(Object(Magento\Framework\App\Request\Http), Array)
#21 C:\xampp\htdocs\newtheme\vendor\magento\framework\App\FrontController.php(50): Magento\Framework\App\Router\Base->match(Object(Magento\Framework\App\Request\Http))
#22 C:\xampp\htdocs\newtheme\vendor\magento\framework\Interception\Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#23 C:\xampp\htdocs\newtheme\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#24 C:\xampp\htdocs\newtheme\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#25 C:\xampp\htdocs\newtheme\vendor\magento\framework\Module\Plugin\DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#26 C:\xampp\htdocs\newtheme\vendor\magento\framework\Interception\Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 C:\xampp\htdocs\newtheme\var\generation\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#28 C:\xampp\htdocs\newtheme\vendor\magento\framework\App\Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#29 C:\xampp\htdocs\newtheme\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#30 C:\xampp\htdocs\newtheme\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/10257765/29863692-a9a89002-8d9a-11e7-8f22-cfdf5d7abe33.png)

**Comment by tomnyson** [comment]
I fixed it
change line 96 to 
if ($children->length && trim($child->nodeValue, "\n\t ") === '') {
in conveter.php

**Comment by orlangur** [comment]
Are you able to reproduce this issue on a supported operating system: http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html ? Windows is not in the list. Issue seems to be related to tabulation symbol in some of your `xml` configuration files and thus it can be OS-agnostic.

**Comment by magento-engcom-team** [comment]
@tomnyson we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
