### ISSUE TITLE
We can't add this item to your shopping cart right now

### ISSUE THREAD

**Issue by binnykumar** [magento/magento2#10998]
![error](https://user-images.githubusercontent.com/29915861/30741526-beb81858-9fb2-11e7-88e7-18730d15615c.png)
When i am trying to add product to cart, it is showing "We can't add this item to your shopping cart right now".

This is my exception.log file output.

#44 /mnt/thebodyshoplive/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#45 /mnt/thebodyshoplive/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#46 /mnt/thebodyshoplive/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#47 /mnt/thebodyshoplive/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#48 /mnt/thebodyshoplive/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#49 /mnt/thebodyshoplive/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#50 /mnt/thebodyshoplive/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#51 /mnt/thebodyshoplive/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#52 /mnt/thebodyshoplive/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#53 {main} [] []

**Comment by binnykumar** [comment]
![error](https://user-images.githubusercontent.com/29915861/30741511-abe13dae-9fb2-11e7-84d9-ed9c7b0b7e44.png)

**Comment by jayachandrann** [comment]
Adding to the above issue, Find the server stack

Ubuntu 16.0.4 --> NGNIX --> PHP7.0 - FPM --> Redis Server
opcache has been disabled

**Comment by magento-engcom-team** [comment]
Hi @binnykumar 
Please try reproducing on clean Magento installation, as the issue may be related to third-party customizations.
If the issue persists please provide detailed report following the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines). Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by magento-engcom-team** [comment]
@binnykumar, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
