### ISSUE TITLE
MIME type is not valid image/png

### ISSUE THREAD

**Issue by versdivers** [magento/magento2#11129]
### Preconditions
1. Magento 2.2.0 (and also Magento 2.1.8)
2. PHP 7.0.2

### Steps to reproduce
1. Add Product Programmaticly with the following code 
`  $productarray
                        ->setPrice($ex_productcollection['Price'])
                        ->setName($ex_productcollection['Name'])
                        ->setSku($ex_productcollection['SKU'])
                        ->setTypeId('simple')
                        ->setVisibility(Visibility::VISIBILITY_BOTH)
                        ->setStatus(Status::STATUS_DISABLED)
                        ->setAttributeSetId(4)
                        ->setQty($ex_productcollection['Stock'])
                        ->setWeight($ex_productcollection['Weight']);`
2.  Add Images with the following code 
(and i need to say.. What a big hassle to use a local image)
```
                    if (isset($imageurl)) {

//                        $productarray->addImageToMediaGallery($imageurl, array('image' , 'small_image'), true , false );
                        $imageentry = $this->_galleryentry;
                        $content = $this->_imagecontent;
                        $imagename = pathinfo($imageurl, PATHINFO_BASENAME);
                        $imageext = pathinfo(strtolower($imageurl), PATHINFO_EXTENSION);
                        if (exif_imagetype($imageurl)) {
                            if ($imageext == 'jpg' || $imageext == 'jpeg' || $imageext == 'png' || $imageext == 'gif') {
                                var_dump($imageurl);
                                var_dump($imageext);
                                $content
                                    ->setName($imagename)
                                    ->setBase64EncodedData(base64_encode(file_get_contents($imageurl)))
                                    ->setType($this->_mime->getMimeType($imageurl));

                                var_dump($this->_mime->getMimeType($imageurl));
                                $imageentry
                                    ->setMediaType('image')
                                    ->setTypes(array('image', 'small_image', 'thumbnail'))
                                    ->setContent($content)
                                    ->setFile($imageurl);
                                try {
                                    $productarray->setMediaGalleryEntries(array($imageentry));
                                } catch (\Exception $e) {
                                    printf('Can not add Image : ' . $imageurl . ' : ' . $e);
                                };
                            }
                        }
                    }
```

3. Save image

                    try {
                        $productrep->save($productarray);
                    } catch (\Exception $e) {
                        return ('an error has occured :' . $e);
                    }

### Expected result
1.  Product is created with the needed image

### Actual result
1. Product is not created because the error : The Image MIME type is not valid 👍 
(I do var_dump the local image path , the file extension and the mime type so you can see what it processes in the first 3 lines) 

> string(87) "/data/sites/web/demoehaleeu/www/pub/media/tmp/Schermafbeelding_2017-04-26_om_121307.png"
> string(3) "png"
> string(9) "image/png"
> an error has occured :Magento\Framework\Exception\InputException: The image MIME type is not valid or not supported. in /data/sites/web/demoehaleeu/www/vendor/magento/framework/Api/ImageContentValidator.php:62
> Stack trace:
> #0 /data/sites/web/demoehaleeu/www/vendor/magento/framework/Api/ImageProcessor.php(141): Magento\Framework\Api\ImageContentValidator->isValid(Object(Magento\Framework\Api\ImageContent))
> #1 /data/sites/web/demoehaleeu/www/vendor/magento/module-catalog/Model/ProductRepository.php(391): Magento\Framework\Api\ImageProcessor->processImageContent('tmp/catalog/pro...', Object(Magento\Framework\Api\ImageContent))
> #2 /data/sites/web/demoehaleeu/www/vendor/magento/module-catalog/Model/ProductRepository.php(542): Magento\Catalog\Model\ProductRepository->processNewMediaGalleryEntry(Object(Magento\Catalog\Model\Product\Interceptor), Array)
> #3 /data/sites/web/demoehaleeu/www/vendor/magento/module-catalog/Model/ProductRepository.php(590): Magento\Catalog\Model\ProductRepository->processMediaGallery(Object(Magento\Catalog\Model\Product\Interceptor), Array)
> #4 /data/sites/web/demoehaleeu/www/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ProductRepository->save(Object(Magento\Catalog\Model\Product\Interceptor))
> #5 /data/sites/web/demoehaleeu/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ProductRepository\Interceptor->___callParent('save', Array)
> #6 /data/sites/web/demoehaleeu/www/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ProductRepository\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
> #7 /data/sites/web/demoehaleeu/www/generated/code/Magento/Catalog/Model/ProductRepository/Interceptor.php(52): Magento\Catalog\Model\ProductRepository\Interceptor->___callPlugins('save', Array, Array)
> #8 /data/sites/web/demoehaleeu/www/app/code/Designit/ExactOnline/Api/Products.php(191): Magento\Catalog\Model\ProductRepository\Interceptor->save(Object(Magento\Catalog\Model\Product\Interceptor))
> #9 /data/sites/web/demoehaleeu/www/app/code/Designit/ExactOnline/Console/Command/ExactCommand.php(82): Designit\ExactOnline\Api\Products->UpdateProducts()
> #10 /data/sites/web/demoehaleeu/www/vendor/symfony/console/Command/Command.php(266): Designit\ExactOnline\Console\Command\ExactCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #11 /data/sites/web/demoehaleeu/www/vendor/symfony/console/Application.php(875): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #12 /data/sites/web/demoehaleeu/www/vendor/symfony/console/Application.php(204): Symfony\Component\Console\Application->doRunCommand(Object(Designit\ExactOnline\Console\Command\ExactCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #13 /data/sites/web/demoehaleeu/www/vendor/magento/framework/Console/Cli.php(104): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #14 /data/sites/web/demoehaleeu/www/vendor/symfony/console/Application.php(122): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #15 /data/sites/web/demoehaleeu/www/bin/magento(23): Symfony\Component\Console\Application->run()
> #16 {main}

Importing stuff into Magento is such a big  work. Why not just have something like `->AddImage()`  . I mean you can figure the base code , name , tye , mediatype by yourself with just some functions behind it... 

Every but litterly every framework that i with before (even the bad onces) have such a function. Anyways. I hope someone can resolve this for me. I check the provided validated mime types. It says in vendor/magento/framework/Api/ImageContentValidator.php on line 26 that 'image/png' is a valid type... And like you see i vardumped image/png. So why is this even returning this error?

**Comment by versdivers** [comment]
I use use Magento\Catalog\Model\ProductRepository to save the product and Magento\Catalog\Model\Product to set the product

**Comment by versdivers** [comment]
After some deeper digging i noticed that the only problem is with png filles?

**Comment by dmanners** [comment]
Hi @versdivers do you know if the error happens on the `$sourceMimeType != $imageContent->getType()` or the `!$this->isMimeTypeValid($sourceMimeType)` part of the following if?

```
        $sourceMimeType = $imageProperties['mime'];
        if ($sourceMimeType != $imageContent->getType() || !$this->isMimeTypeValid($sourceMimeType)) {
            throw new InputException(new Phrase('The image MIME type is not valid or not supported.'));
        }
```

**Comment by versdivers** [comment]
@dmanners  i will check and let you know

**Comment by versdivers** [comment]
I will update this today

**Comment by magento-engcom-team** [comment]
@versdivers, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by ndrukajsh** [comment]
This issue is still unresolved. The problem with png files is persisting even when you try to upload images through rest API! I think that the problem is the one that @dmanners has pointed out!
