### ISSUE TITLE
Failed to read 'localstorage' property

### ISSUE THREAD

**Issue by sambalay** [magento/magento2#11253]
### Preconditions

1. Magneto 2.1.8
2. PHP 7.0

We are getting localstorage errors and unable to proceed to cart /checkout

QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'mage-cache-storage' exceeded the quota - chrome
NS_ERROR_DOM_QUOTA_REACHED: Persistent storage maximum size reached - firefox

Raw stack traceclose

r@https://xyz.com/static/frontend/Newlu/newlu/en_US/jquery/jquery.storageapi.min.js:2:1355
_callMethod@https://xyz.com/static/frontend/Newlu/newlu/en_US/jquery/jquery.storageapi.min.js:2:4101
set@https://xyz.com/static/frontend/Newlu/newlu/en_US/jquery/jquery.storageapi.min.js:2:4440
update/<@https://xyz.com/static/frontend/Newlu/newlu/en_US/Magento_Customer/js/customer-data.min.js:4:122
_.forEach@https://xyz.com/static/frontend/Newlu/newlu/en_US/underscore.min.js:7:650
update@https://xyz.com/static/frontend/Newlu/newlu/en_US/Magento_Customer/js/customer-data.min.js:4:1
reload/<@https://xyz.com/static/frontend/Newlu/newlu/en_US/Magento_Customer/js/customer-data.min.js:9:317
fire@https://xyz.com/static/frontend/Newlu/newlu/en_US/jquery.min.js:212:205
fireWith@https://xyz.com/static/frontend/Newlu/newlu/en_US/jquery.min.js:218:181
done@https://xyz.com/static/frontend/Newlu/newlu/en_US/jquery.min.js:628:86
callback@https://xyz.com/static/frontend/Newlu/newlu/en_US/jquery.min.js:655:15

Raw stack trace
Error: Failed to execute 'setItem' on 'Storage': Setting the value of 'mage-cache-storage' exceeded the quota.
    at Object.r (https://xyz.com/static/frontend/Newlu/newlu/en_US/jquery/jquery.storageapi.min.js:2:1357)
    at Object._callMethod (https://xyz.com/static/frontend/Newlu/newlu/en_US/jquery/jquery.storageapi.min.js:2:4103)
    at Object.set (https://xyz.com/static/frontend/Newlu/newlu/en_US/jquery/jquery.storageapi.min.js:2:4445)
    at https://xyz.com/static/frontend/Newlu/newlu/en_US/Magento_Customer/js/customer-data.min.js:4:130
    at Function._.each._.forEach (https://xyz.com/static/frontend/Newlu/newlu/en_US/underscore.min.js:7:650)
    at Object.update (https://xyz.com/static/frontend/Newlu/newlu/en_US/Magento_Customer/js/customer-data.min.js:4:3)
    at Object.set (https://xyz.com/static/frontend/Newlu/newlu/en_US/Magento_Customer/js/customer-data.min.js:9:168)
    at saveData (https://xyz.com/static/frontend/Newlu/newlu/en_US/Magento_Checkout/js/checkout-data.min.js:1:161)
    at getData (https://xyz.comm/static/frontend/Newlu/newlu/en_US/Magento_Checkout/js/checkout-data.min.js:1:521)
    at Object.getValidatedEmailValue (https://xyz.com/static/frontend/Newlu/newlu/en_US/Magento_Checkout/js/checkout-data.min.js:2:1576)

**Comment by orlangur** [comment]
Please check contents of localStorage in Chrome Dev Tools. Is it filled with some core-specific data or there is some extension storing too much information?

**Comment by magento-engcom-team** [comment]
@sambalay we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by ngocdb** [comment]
Same issue here. 
I am using Magento 2.1.8 with php 7.

![8fa9116b-35b2-46c3-b26b-9e362079961e](https://user-images.githubusercontent.com/3035559/33009272-eb945cfe-ce08-11e7-9d59-5e0d5e13f9a6.jpeg)

**Comment by orlangur** [comment]
@ngocdb same here: please check my comment and find out which data bloated the local storage that much.

**Comment by moazzama** [comment]
Hello @magento-engcom-team 

When i add to cart product i can not able to add to cart that issue produce on console 

js.storage.js:155 Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'mage-cache-storage' exceeded the quota.
    at Object._set (https://test.it/static/version1698989401/frontend/Local/test-Theme/it_IT/js-storage/js.storage.js:155:15)
    at Object._callMethod (https://test.it/static/version1698989401/frontend/Local/test-Theme/it_IT/js-storage/js.storage.js:441:22)
    at Object.set (https://test.it/static/version1698989401/frontend/Local/test-Theme/it_IT/js-storage/js.storage.js:470:30)
    at https://test.it/static/version1698989401/frontend/Local/test-Theme/it_IT/Magento_Customer/js/customer-data.js:167:25
    at Function.each (https://test.it/static/version1698989401/frontend/Local/test-Theme/it_IT/underscore.js:1335:17)
    at Object.update (https://test.it/static/version1698989401/frontend/Local/test-Theme/it_IT/Magento_Customer/js/customer-data.js:164:15)
    at Object.<anonymous> (https://test.it/static/version1698989401/frontend/Local/test-Theme/it_IT/Magento_Customer/js/customer-data.js:329:24)
    at fire (https://test.it/static/version1698989401/frontend/Local/test-Theme/it_IT/jquery.js:3500:50)
    at Object.fireWith [as resolveWith] (https://test.it/static/version1698989401/frontend/Local/test-Theme/it_IT/jquery.js:3630:29)
    at done (https://test.it/static/version1698989401/frontend/Local/test-Theme/it_IT/jquery.js:9796:30)
