### ISSUE TITLE
Can't install sample data

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#1129]
I tried to install latest version of magento2 (version 0.74.0-beta1), on step with installing sample data I got next issue:
```
-bash-4.1$ cd /var/www/html/magento2/
-bash-4.1$ composer require magento/sample-data:0.74.0-beta1
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magento/sample-data 0.74.0-beta1 -> satisfiable by magento/sample-data[0.74.0-beta1].
    - magento/sample-data 0.74.0-beta1 requires magento/sample-data-fixtures 0.74.0-beta1 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
``` 

Inside my composer.json I have those repositories:
```
"repositories": {
    "magento": {
        "type": "composer",
        "url": "http://packages.magento.com"
    }
}
```

**Comment by lykhouzov** [comment]
another error when i was installing sample data.
```
$ php dev/tools/Magento/Tools/SampleData/install.php --admin_username=admin
PHP Warning:  SessionHandler::read(): open(/var/lib/php5/sess_gb8ebj9rklvt47cmc2r6622thr4euc25996gca3dgrh0j6r4ekm1, O_RDWR) failed: Permission denied (13) in /home/vhosts/magento2/lib/internal/Magento/Framework/Session/SaveHandler.php on line 73
Installing theme:
.
Installing customers:
.
Installing CMS pages:
....
Installing catalog attributes:
...........................
Installing categories:
.........................................
Installing simple products:
............................................
Installing bundle products:
.
Installing downloadable products:
......
Installing grouped products:
.
Installing configurable products:
.....................................................................................................................................................
Installing Tablerate:
.........
Installing taxes:
..
Installing CMS blocks:
..................
Installing product links:
.......................................................................................................................................................................................................................................................................................................................................................................
Installing orders:
..
Installing catalog rules:
.
Installing sales rules:
....
Installing product reviews:
............................................................................................................................................................................................................................................................................................................................................................
Installing wishlists:
.
Installing Widgets:
..................PHP Fatal error:  Uncaught exception 'Exception' with message 'Warning: SessionHandler::write(): open(/var/lib/php5/sess_gb8ebj9rklvt47cmc2r6622thr4euc25996gca3dgrh0j6r4ekm1, O_RDWR) failed: Permission denied (13) in /home/vhosts/magento2/lib/internal/Magento/Framework/Session/SaveHandler.php on line 85' in /home/vhosts/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:59
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'SessionHandler:...', '/home/vhosts/ma...', 85, Array)
#1 /home/vhosts/magento2/lib/internal/Magento/Framework/Session/SaveHandler.php(85): SessionHandler->write('gb8ebj9rklvt47c...', 'MRKMFHIESONBxPs...')
#2 [internal function]: Magento\Framework\Session\SaveHandler->write('gb8ebj9rklvt47c...', 'MRKMFHIESONBxPs...')
#3 /home/vhosts/magento2/lib/internal/Magento/Framework/Session/SessionManager.php(130): session_write_close()
#4 [internal function]: Magento\Framework\Session\SessionManager->writeClose()
#5 {main}
  thrown in /home/vhosts/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php on line 59
```

**Comment by mbrinton01** [comment]
Hello @ihor-sviziev, your issue may be caused by not adding `"minimum-stability": "beta",` to your composer.json file before running `composer require magento/sample-data:0.74.0-beta1`

Please review the instructions here: http://devdocs.magento.com/guides/v1.0/install-gde/install/sample-data.html

On step #5 of **Enable sample data before you install the Magento software** you will see how to do it.

If you skip this step, you will receive the error you listed.  If this does not fix your issue please reply back.

**Comment by ihor-sviziev** [comment]
@mbrinton01 thank you, looks like I missed this change it, now this issue is gone.
@lykhouzov I think that in your php configuration sessions are located inside /var/lib/php5/, but user from which you trying to execute php script hasn't permissions to add sessions in this folder. Try to execute from user apache.
