### ISSUE TITLE
Cannot refund with Refund Shipping > 0 when the order shipping amount = 0

### ISSUE THREAD

**Issue by franckgarnier21** [magento/magento2#11336]
### Preconditions
1. Magento 2.1.9 (same code on Magento 2.2 dev)
2. Redis + Varnish + Mysql 5.6 + PHP 7 + ElasticSearch (it is not related to these stacks)

### Steps to reproduce
1. Create an order with shipping amount = 0 but where the total amount > 0
2. Create the invoice and capture with braintree for example the order amount
3. Create a credit memo with Refund Shipping > 0 , 1 for example
4. Click on Refund

### Expected result
1. The creditmemo should be created with the correct amount.

### Actual result
Error the creditmemo cannot be saved

The error message is 

> We can't save the credit memo right now.

Full Log
```
==> var/log/exception.log <==
[2017-10-10 11:15:19] report.CRITICAL: Exception: Warning: Division by zero in /var/www/magento2/production/vendor/magento/module-sales/Model/Order/Creditmemo/Total/Discount.php on line 32 in /var/www/magento2/production/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /var/www/magento2/production/vendor/magento/module-sales/Model/Order/Creditmemo/Total/Discount.php(32): Magento\Framework\App\ErrorHandler->handler(2, 'Division by zer...', '/var/www/magent...', 32, Array)
#1 /var/www/magento2/production/vendor/magento/module-sales/Model/Order/Creditmemo.php(337): Magento\Sales\Model\Order\Creditmemo\Total\Discount->collect(Object(Magento\Sales\Model\Order\Creditmemo\Interceptor))
#2 /var/www/magento2/production/vendor/magento/module-sales/Model/Order/CreditmemoFactory.php(169): Magento\Sales\Model\Order\Creditmemo->collectTotals()
#3 /var/www/magento2/production/vendor/magento/module-sales/Controller/Adminhtml/Order/CreditmemoLoader.php(209): Magento\Sales\Model\Order\CreditmemoFactory->createByInvoice(Object(Magento\Sales\Model\Order\Invoice), Array)
#4 /var/www/magento2/production/vendor/magento/module-sales/Controller/Adminhtml/Order/Creditmemo/Save.php(75): Magento\Sales\Controller\Adminhtml\Order\CreditmemoLoader->load()
#5 /var/www/magento2/production/vendor/magento/framework/App/Action/Action.php(102): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save->execute()
#6 /var/www/magento2/production/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /var/www/magento2/production/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /var/www/magento2/production/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callParent('dispatch', Array)
#9 /var/www/magento2/production/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor), Array, 'adminAuthentica...')
#10 /var/www/magento2/production/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /var/www/magento2/production/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /var/www/magento2/production/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor), Array, 'log')
#13 /var/www/magento2/production/vendor/magento/module-logging/App/Action/Plugin/Log.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /var/www/magento2/production/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Logging\App\Action\Plugin\Log->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 /var/www/magento2/production/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor), Array, 'adminMassaction...')
#16 /var/www/magento2/production/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /var/www/magento2/production/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /var/www/magento2/production/var/generation/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/Save/Interceptor.php(26): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callPlugins('dispatch', Array, Array)
#19 /var/www/magento2/production/vendor/magento/framework/App/FrontController.php(55): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/magento2/production/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /var/www/magento2/production/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#22 /var/www/magento2/production/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#23 /var/www/magento2/production/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#24 /var/www/magento2/production/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /var/www/magento2/production/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#26 /var/www/magento2/production/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /var/www/magento2/production/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#28 /var/www/magento2/production/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#29 {main} [] []
```

If you look the Magento code :
```
        /**
         * Calculate how much shipping discount should be applied
         * basing on how much shipping should be refunded.
         */
        $baseShippingAmount = (float)$creditmemo->getBaseShippingAmount();
        if ($baseShippingAmount) {
            $baseShippingDiscount = $baseShippingAmount *
                $order->getBaseShippingDiscountAmount() /
                $order->getBaseShippingAmount();
            $shippingDiscount = $order->getShippingAmount() * $baseShippingDiscount / $order->getBaseShippingAmount();
            $totalDiscountAmount = $totalDiscountAmount + $shippingDiscount;
            $baseTotalDiscountAmount = $baseTotalDiscountAmount + $baseShippingDiscount;
        }
```

You can see the if `$creditmemo->getBaseShippingAmount()` is greater than 0 and `$order->getBaseShippingAmount()` equal 0, there is a division by 0....

**Comment by orlangur** [comment]
> order with shipping amount = 0 
> credit memo with Refund Shipping > 0 , 1 for example

Is it a valid scenario? Refund Shipping may be an arbitrary number in real world?

**Comment by franckgarnier21** [comment]
It is a valid scenario because Magento allows this. At least the field should be disabled.

However, how do you manage the return shipping cost on a creditmemo.

Thanks,

**Comment by orlangur** [comment]
> It is a valid scenario because Magento allows this

Nope.

My point is - whether we must validate `Shipping Amount <= Refund Shipping` or sometimes we really need shipping refund in case of free shipping?

**Comment by magento-engcom-team** [comment]
@franckgarnier21, thank you for your report.
We've created internal ticket(s) MAGETWO-81441 to track progress on the issue.

**Comment by franckgarnier21** [comment]
@magento-engcom-team Thank you for the internal ticket tracking.

@orlangur I do not agree, but it is a different point of view. At least the error message should be more explicit. And you do not have to try a division by 0 in PHP.

Can someone explain me the use-case of the 3 different fields allowed to adjust the credit-memo total. How do we manage the return shipping cost on a creditmemo.

**Comment by orlangur** [comment]
@franckgarnier21 I'm fully support you that system should behave normally in any conditions, just depending on the scenarios used by real merchants it can be of lower severity.

So there are two possible approaches: do not allow to enter such Refund Shipping value or just avoid division by zero.

> Can someone explain me the use-case of the 3 different fields allowed to adjust the credit-memo total. How do we manage the return shipping cost on a creditmemo.

Such kind of question may be quicker answered on [Magento Stack Exchange](https://magento.stackexchange.com). https://www.magestore.com/magento-2-tutorial/magento-2-credit-memo/ may be helpful, at least "a. In the Refund Shipping field, enter any amount that is to be refunded from the shipping fee. This field initially displays the total shipping amount from the order that is available for refund. It is equal to the full shipping amount from the order, less any shipping amount that has already been refunded." looks like with 0 shipping amount refund should not be allowed.

**Comment by franckgarnier21** [comment]
Many thanks for the information.

I will create a question for the two other fields on Stack Excange.

I let you chose the best solution in order to manage this issue.

Help was appreciated.

**Comment by magento-engcom-team** [comment]
@franckgarnier21, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
