### ISSUE TITLE
Store Manager has been initialized not properly (HHVM Clean install)

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#1137]
Command line install - Magento 2 0.74.0-beta1

```
setup$ php -f index.php install --base_url=http://www.xx.co.uk/ --backend_frontname=admin --db_host=a ip --db_name=xx_prod --db_user=xx_prod --db_pass=6J3?B3]9J2a,zZ! --admin_firstname=Craig --admin_lastname=xx --admin_email=xx@hotmail.com --admin_username=admin --admin_password=admin1234 --language=en_GB --currency=GBP --timezone=Europe/London
Starting Magento installation:
File permissions check...
[Progress: 1 / 265]
Enabling Maintenance Mode...
[Progress: 2 / 265]
Installing deployment configuration...
[Progress: 3 / 265]
Installing database schema:
Schema creation/updates:
Module 'Magento_Store':
Installing schema.. 
[Progress: 4 / 265]
Module 'Magento_Directory':
Installing schema.. 
[Progress: 5 / 265]
Module 'Magento_Backend':
[Progress: 6 / 265]
Module 'Magento_Backup':
[Progress: 7 / 265]
Module 'Magento_Theme':
Installing schema.. Upgrading schema.. 
[Progress: 8 / 265]
Module 'Magento_Eav':
Installing schema.. 
[Progress: 9 / 265]
Module 'Magento_Customer':
Installing schema.. Upgrading schema.. 
[Progress: 10 / 265]
Module 'Magento_CatalogImportExport':
[Progress: 11 / 265]
Module 'Magento_Indexer':
Installing schema.. 
[Progress: 12 / 265]
Module 'Magento_Cms':
Installing schema.. 
[Progress: 13 / 265]
Module 'Magento_Search':
Installing schema.. 
[Progress: 14 / 265]
Module 'Magento_Catalog':
Installing schema.. Upgrading schema.. 
[Progress: 15 / 265]
Module 'Magento_Rule':
[Progress: 16 / 265]
Module 'Magento_CatalogInventory':
Installing schema.. 
[Progress: 17 / 265]
Module 'Magento_Payment':
[Progress: 18 / 265]
Module 'Magento_CheckoutAgreements':
Installing schema.. 
[Progress: 19 / 265]
Module 'Magento_Quote':
Installing schema.. 
[Progress: 20 / 265]
Module 'Magento_CmsUrlRewrite':
[Progress: 21 / 265]
Module 'Magento_Config':
Installing schema.. 
[Progress: 22 / 265]
Module 'Magento_ConfigurableImportExport':
[Progress: 23 / 265]
Module 'Magento_Msrp':
[Progress: 24 / 265]
Module 'Magento_Contact':
[Progress: 25 / 265]
Module 'Magento_Cookie':
[Progress: 26 / 265]
Module 'Magento_Cron':
Installing schema.. 
[Progress: 27 / 265]
Module 'Magento_Widget':
Installing schema.. 
[Progress: 28 / 265]
Module 'Magento_Bundle':
Installing schema.. 
[Progress: 29 / 265]
Module 'Magento_CustomerImportExport':
[Progress: 30 / 265]
Module 'Magento_DesignEditor':
Installing schema.. 
[Progress: 31 / 265]
Module 'Magento_Developer':
[Progress: 32 / 265]
Module 'Magento_Dhl':
[Progress: 33 / 265]
Module 'Magento_Authorization':
Installing schema.. 
[Progress: 34 / 265]
Module 'Magento_Downloadable':
Installing schema.. 
[Progress: 35 / 265]
Module 'Magento_Sales':
Installing schema.. Upgrading schema.. 
[Progress: 36 / 265]
Module 'Magento_Email':
Installing schema.. 
[Progress: 37 / 265]
Module 'Magento_Fedex':
[Progress: 38 / 265]
Module 'Magento_GiftMessage':
Installing schema.. 
[Progress: 39 / 265]
Module 'Magento_Checkout':
[Progress: 40 / 265]
Module 'Magento_GoogleAnalytics':
[Progress: 41 / 265]
Module 'Magento_GoogleOptimizer':
Installing schema.. 
[Progress: 42 / 265]
Module 'Magento_GoogleShopping':
Installing schema.. 
[Progress: 43 / 265]
Module 'Magento_GroupedImportExport':
[Progress: 44 / 265]
Module 'Magento_GroupedProduct':
[Progress: 45 / 265]
Module 'Magento_ImportExport':
Installing schema.. 
[Progress: 46 / 265]
Module 'Magento_CatalogRule':
Installing schema.. 
[Progress: 47 / 265]
Module 'Magento_User':
Installing schema.. 
[Progress: 48 / 265]
Module 'Magento_LayeredNavigation':
[Progress: 49 / 265]
Module 'Magento_Log':
Installing schema.. 
[Progress: 50 / 265]
Module 'Magento_MediaStorage':
[Progress: 51 / 265]
Module 'Magento_ConfigurableProduct':
Installing schema.. 
[Progress: 52 / 265]
Module 'Magento_Multishipping':
[Progress: 53 / 265]
Module 'Magento_Newsletter':
Installing schema.. 
[Progress: 54 / 265]
Module 'Magento_OfflinePayments':
[Progress: 55 / 265]
Module 'Magento_SalesRule':
Installing schema.. 
[Progress: 56 / 265]
Module 'Magento_PageCache':
[Progress: 57 / 265]
Module 'Magento_Centinel':
[Progress: 58 / 265]
Module 'Magento_Persistent':
Installing schema.. 
[Progress: 59 / 265]
Module 'Magento_ProductAlert':
Installing schema.. 
[Progress: 60 / 265]
Module 'Magento_Captcha':
Installing schema.. 
[Progress: 61 / 265]
Module 'Magento_Reports':
Installing schema.. 
[Progress: 62 / 265]
Module 'Magento_RequireJs':
[Progress: 63 / 265]
Module 'Magento_Review':
Installing schema.. 
[Progress: 64 / 265]
Module 'Magento_Rss':
[Progress: 65 / 265]
Module 'Magento_CatalogWidget':
[Progress: 66 / 265]
Module 'Magento_GoogleAdwords':
[Progress: 67 / 265]
Module 'Magento_OfflineShipping':
Installing schema.. 
[Progress: 68 / 265]
Module 'Magento_CatalogSearch':
Installing schema.. 
[Progress: 69 / 265]
Module 'Magento_Sendfriend':
Installing schema.. 
[Progress: 70 / 265]
Module 'Magento_Shipping':
[Progress: 71 / 265]
Module 'Magento_Sitemap':
Installing schema.. 
[Progress: 72 / 265]
Module 'Magento_AdminNotification':
Installing schema.. 
[Progress: 73 / 265]
Module 'Magento_Tax':
Installing schema.. 
[Progress: 74 / 265]
Module 'Magento_TaxImportExport':
[Progress: 75 / 265]
Module 'Magento_CatalogUrlRewrite':
Installing schema.. 
[Progress: 76 / 265]
Module 'Magento_Translation':
Installing schema.. 
[Progress: 77 / 265]
Module 'Magento_Ui':
[Progress: 78 / 265]
Module 'Magento_Ups':
[Progress: 79 / 265]
Module 'Magento_UrlRewrite':
Installing schema.. 
[Progress: 80 / 265]
Module 'Magento_Integration':
Installing schema.. 
[Progress: 81 / 265]
Module 'Magento_Usps':
[Progress: 82 / 265]
Module 'Magento_Variable':
Installing schema.. 
[Progress: 83 / 265]
Module 'Magento_Version':
[Progress: 84 / 265]
Module 'Magento_Webapi':
[Progress: 85 / 265]
Module 'Magento_Weee':
Installing schema.. 
[Progress: 86 / 265]
Module 'Magento_CurrencySymbol':
[Progress: 87 / 265]
Module 'Magento_Wishlist':
Installing schema.. 
[Progress: 88 / 265]
Schema post-updates:
Module 'Magento_Store':
[Progress: 89 / 265]
Module 'Magento_Directory':
[Progress: 90 / 265]
Module 'Magento_Backend':
[Progress: 91 / 265]
Module 'Magento_Backup':
[Progress: 92 / 265]
Module 'Magento_Theme':
[Progress: 93 / 265]
Module 'Magento_Eav':
[Progress: 94 / 265]
Module 'Magento_Customer':
[Progress: 95 / 265]
Module 'Magento_CatalogImportExport':
[Progress: 96 / 265]
Module 'Magento_Indexer':
[Progress: 97 / 265]
Module 'Magento_Cms':
[Progress: 98 / 265]
Module 'Magento_Search':
[Progress: 99 / 265]
Module 'Magento_Catalog':
[Progress: 100 / 265]
Module 'Magento_Rule':
[Progress: 101 / 265]
Module 'Magento_CatalogInventory':
[Progress: 102 / 265]
Module 'Magento_Payment':
[Progress: 103 / 265]
Module 'Magento_CheckoutAgreements':
[Progress: 104 / 265]
Module 'Magento_Quote':
[Progress: 105 / 265]
Module 'Magento_CmsUrlRewrite':
[Progress: 106 / 265]
Module 'Magento_Config':
[Progress: 107 / 265]
Module 'Magento_ConfigurableImportExport':
[Progress: 108 / 265]
Module 'Magento_Msrp':
[Progress: 109 / 265]
Module 'Magento_Contact':
[Progress: 110 / 265]
Module 'Magento_Cookie':
[Progress: 111 / 265]
Module 'Magento_Cron':
[Progress: 112 / 265]
Module 'Magento_Widget':
[Progress: 113 / 265]
Module 'Magento_Bundle':
[Progress: 114 / 265]
Module 'Magento_CustomerImportExport':
[Progress: 115 / 265]
Module 'Magento_DesignEditor':
[Progress: 116 / 265]
Module 'Magento_Developer':
[Progress: 117 / 265]
Module 'Magento_Dhl':
[Progress: 118 / 265]
Module 'Magento_Authorization':
[Progress: 119 / 265]
Module 'Magento_Downloadable':
[Progress: 120 / 265]
Module 'Magento_Sales':
[Progress: 121 / 265]
Module 'Magento_Email':
[Progress: 122 / 265]
Module 'Magento_Fedex':
[Progress: 123 / 265]
Module 'Magento_GiftMessage':
[Progress: 124 / 265]
Module 'Magento_Checkout':
[Progress: 125 / 265]
Module 'Magento_GoogleAnalytics':
[Progress: 126 / 265]
Module 'Magento_GoogleOptimizer':
[Progress: 127 / 265]
Module 'Magento_GoogleShopping':
[Progress: 128 / 265]
Module 'Magento_GroupedImportExport':
[Progress: 129 / 265]
Module 'Magento_GroupedProduct':
[Progress: 130 / 265]
Module 'Magento_ImportExport':
[Progress: 131 / 265]
Module 'Magento_CatalogRule':
[Progress: 132 / 265]
Module 'Magento_User':
[Progress: 133 / 265]
Module 'Magento_LayeredNavigation':
[Progress: 134 / 265]
Module 'Magento_Log':
[Progress: 135 / 265]
Module 'Magento_MediaStorage':
[Progress: 136 / 265]
Module 'Magento_ConfigurableProduct':
[Progress: 137 / 265]
Module 'Magento_Multishipping':
[Progress: 138 / 265]
Module 'Magento_Newsletter':
[Progress: 139 / 265]
Module 'Magento_OfflinePayments':
[Progress: 140 / 265]
Module 'Magento_SalesRule':
[Progress: 141 / 265]
Module 'Magento_PageCache':
[Progress: 142 / 265]
Module 'Magento_Centinel':
[Progress: 143 / 265]
Module 'Magento_Persistent':
[Progress: 144 / 265]
Module 'Magento_ProductAlert':
[Progress: 145 / 265]
Module 'Magento_Captcha':
[Progress: 146 / 265]
Module 'Magento_Reports':
[Progress: 147 / 265]
Module 'Magento_RequireJs':
[Progress: 148 / 265]
Module 'Magento_Review':
[Progress: 149 / 265]
Module 'Magento_Rss':
[Progress: 150 / 265]
Module 'Magento_CatalogWidget':
[Progress: 151 / 265]
Module 'Magento_GoogleAdwords':
[Progress: 152 / 265]
Module 'Magento_OfflineShipping':
[Progress: 153 / 265]
Module 'Magento_CatalogSearch':
[Progress: 154 / 265]
Module 'Magento_Sendfriend':
[Progress: 155 / 265]
Module 'Magento_Shipping':
[Progress: 156 / 265]
Module 'Magento_Sitemap':
[Progress: 157 / 265]
Module 'Magento_AdminNotification':
[Progress: 158 / 265]
Module 'Magento_Tax':
[Progress: 159 / 265]
Module 'Magento_TaxImportExport':
[Progress: 160 / 265]
Module 'Magento_CatalogUrlRewrite':
[Progress: 161 / 265]
Module 'Magento_Translation':
[Progress: 162 / 265]
Module 'Magento_Ui':
[Progress: 163 / 265]
Module 'Magento_Ups':
[Progress: 164 / 265]
Module 'Magento_UrlRewrite':
[Progress: 165 / 265]
Module 'Magento_Integration':
[Progress: 166 / 265]
Module 'Magento_Usps':
[Progress: 167 / 265]
Module 'Magento_Variable':
[Progress: 168 / 265]
Module 'Magento_Version':
[Progress: 169 / 265]
Module 'Magento_Webapi':
[Progress: 170 / 265]
Module 'Magento_Weee':
[Progress: 171 / 265]
Module 'Magento_CurrencySymbol':
[Progress: 172 / 265]
Module 'Magento_Wishlist':
[Progress: 173 / 265]
[Progress: 174 / 265]
Installing user configuration...
[Progress: 175 / 265]
Installing data...
Data install/update:
Module 'Magento_Store':
[Progress: 176 / 265]
Module 'Magento_Directory':
Installing data.. 
[Progress: 177 / 265]
Module 'Magento_Backend':
[Progress: 178 / 265]
Module 'Magento_Backup':
[Progress: 179 / 265]
Module 'Magento_Theme':
Installing data.. 
[Progress: 180 / 265]
Module 'Magento_Eav':
Installing data.. 
[Progress: 181 / 265]
Module 'Magento_Customer':
Installing data.. 
[Progress: 182 / 265]
Module 'Magento_CatalogImportExport':
[Progress: 183 / 265]
Module 'Magento_Indexer':
[Progress: 184 / 265]
Module 'Magento_Cms':
Installing data.. 
[Progress: 185 / 265]
Module 'Magento_Search':
[Progress: 186 / 265]
Module 'Magento_Catalog':
Installing data.. 
[Progress: 187 / 265]
Module 'Magento_Rule':
[Progress: 188 / 265]
Module 'Magento_CatalogInventory':
Installing data.. 
[Progress: 189 / 265]
Module 'Magento_Payment':
[Progress: 190 / 265]
Module 'Magento_CheckoutAgreements':
[Progress: 191 / 265]
Module 'Magento_Quote':
Installing data.. 
[Progress: 192 / 265]
Module 'Magento_CmsUrlRewrite':
[Progress: 193 / 265]
Module 'Magento_Config':
Installing data.. 
[Progress: 194 / 265]
Module 'Magento_ConfigurableImportExport':
[Progress: 195 / 265]
Module 'Magento_Msrp':
Installing data.. 
[Progress: 196 / 265]
Module 'Magento_Contact':
[Progress: 197 / 265]
Module 'Magento_Cookie':
[Progress: 198 / 265]
Module 'Magento_Cron':
[Progress: 199 / 265]
Module 'Magento_Widget':
Installing data.. 
[Progress: 200 / 265]
Module 'Magento_Bundle':
Installing data.. 
[Progress: 201 / 265]
Module 'Magento_CustomerImportExport':
[Progress: 202 / 265]
Module 'Magento_DesignEditor':
[Progress: 203 / 265]
Module 'Magento_Developer':
[Progress: 204 / 265]
Module 'Magento_Dhl':
Installing data.. 
[Progress: 205 / 265]
Module 'Magento_Authorization':
Installing data.. 
[Progress: 206 / 265]
Module 'Magento_Downloadable':
Installing data.. 
[Progress: 207 / 265]
Module 'Magento_Sales':
Installing data.. 
[Progress: 208 / 265]
Module 'Magento_Email':
[Progress: 209 / 265]
Module 'Magento_Fedex':
Installing data.. 
[Progress: 210 / 265]
Module 'Magento_GiftMessage':
Installing data.. 
[Progress: 211 / 265]
Module 'Magento_Checkout':
Installing data.. 
[Progress: 212 / 265]
Module 'Magento_GoogleAnalytics':
[Progress: 213 / 265]
Module 'Magento_GoogleOptimizer':
[Progress: 214 / 265]
Module 'Magento_GoogleShopping':
Installing data.. 
[Progress: 215 / 265]
Module 'Magento_GroupedImportExport':
[Progress: 216 / 265]
Module 'Magento_GroupedProduct':
Installing data.. 
[Progress: 217 / 265]
Module 'Magento_ImportExport':
[Progress: 218 / 265]
Module 'Magento_CatalogRule':
Installing data.. 
[Progress: 219 / 265]
Module 'Magento_User':
[Progress: 220 / 265]
Module 'Magento_LayeredNavigation':
[Progress: 221 / 265]
Module 'Magento_Log':
Installing data.. 
[Progress: 222 / 265]
Module 'Magento_MediaStorage':
[Progress: 223 / 265]
Module 'Magento_ConfigurableProduct':
Installing data.. 
[Progress: 224 / 265]
Module 'Magento_Multishipping':
[Progress: 225 / 265]
Module 'Magento_Newsletter':
[Progress: 226 / 265]
Module 'Magento_OfflinePayments':
[Progress: 227 / 265]
Module 'Magento_SalesRule':
Installing data.. 
[Progress: 228 / 265]
Module 'Magento_PageCache':
[Progress: 229 / 265]
Module 'Magento_Centinel':
[Progress: 230 / 265]
Module 'Magento_Persistent':
[Progress: 231 / 265]
Module 'Magento_ProductAlert':
[Progress: 232 / 265]
Module 'Magento_Captcha':
[Progress: 233 / 265]
Module 'Magento_Reports':
Installing data.. 
[Progress: 234 / 265]
Module 'Magento_RequireJs':
[Progress: 235 / 265]
Module 'Magento_Review':
Installing data.. 
[Progress: 236 / 265]
Module 'Magento_Rss':
[Progress: 237 / 265]
Module 'Magento_CatalogWidget':
[Progress: 238 / 265]
Module 'Magento_GoogleAdwords':
[Progress: 239 / 265]
Module 'Magento_OfflineShipping':
[Progress: 240 / 265]
Module 'Magento_CatalogSearch':
[Progress: 241 / 265]
Module 'Magento_Sendfriend':
[Progress: 242 / 265]
Module 'Magento_Shipping':
[Progress: 243 / 265]
Module 'Magento_Sitemap':
[Progress: 244 / 265]
Module 'Magento_AdminNotification':
[Progress: 245 / 265]
Module 'Magento_Tax':
Installing data.. 
[Progress: 246 / 265]
Module 'Magento_TaxImportExport':
[Progress: 247 / 265]
Module 'Magento_CatalogUrlRewrite':
Installing data.. 
[Progress: 248 / 265]
Module 'Magento_Translation':
[Progress: 249 / 265]
Module 'Magento_Ui':
[Progress: 250 / 265]
Module 'Magento_Ups':
[Progress: 251 / 265]
Module 'Magento_UrlRewrite':
[Progress: 252 / 265]
Module 'Magento_Integration':
[Progress: 253 / 265]
Module 'Magento_Usps':
Installing data.. 
[Progress: 254 / 265]
Module 'Magento_Variable':
[Progress: 255 / 265]
Module 'Magento_Version':
[Progress: 256 / 265]
Module 'Magento_Webapi':
[Progress: 257 / 265]
Module 'Magento_Weee':
Installing data.. 
[Progress: 258 / 265]
Module 'Magento_CurrencySymbol':
[Progress: 259 / 265]
Module 'Magento_Wishlist':
[Progress: 260 / 265]
[Progress: 261 / 265]
Installing admin user...
[Progress: 262 / 265]
Enabling caches:
Current status:
Array
(
    [config] => 1
    [layout] => 1
    [block_html] => 1
    [view_files_fallback] => 1
    [view_files_preprocessing] => 1
    [collections] => 1
    [db_ddl] => 1
    [eav] => 1
    [full_page] => 1
    [translate] => 1
    [config_integration] => 1
    [config_integration_api] => 1
    [config_webservice] => 1
)

[Progress: 263 / 265]
Disabling Maintenance Mode:
[Progress: 264 / 265]
Post installation file permissions check...
```

```
Store Manager has been initialized not properly
#0 /var/www/vhosts/magento2-capistrano/releases/20150325105152/app/code/Magento/Store/Model/StorageFactory.php(167): Magento\Store\Model\Storage\Db->getStore()
#1 /var/www/vhosts/magento2-capistrano/releases/20150325105152/app/code/Magento/Store/Model/StorageFactory.php(117): Magento\Store\Model\StorageFactory->_reinitStores()
#2 /var/www/vhosts/magento2-capistrano/releases/20150325105152/app/code/Magento/Store/Model/StoreManager.php(121): Magento\Store\Model\StorageFactory->get()
#3 /var/www/vhosts/magento2-capistrano/releases/20150325105152/app/code/Magento/Store/Model/StoreManager.php(175): Magento\Store\Model\StoreManager->_getStorage()
#4 /var/www/vhosts/magento2-capistrano/shared/var/generation/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore()
#5 /var/www/vhosts/magento2-capistrano/releases/20150325105152/app/code/Magento/Store/Model/Resolver/Store.php(29): Magento\Store\Model\StoreManagerInterface\Proxy->getStore()
#6 /var/www/vhosts/magento2-capistrano/releases/20150325105152/lib/internal/Magento/Framework/App/Config/ScopePool.php(117): Magento\Store\Model\Resolver\Store->getScope()
#7 /var/www/vhosts/magento2-capistrano/releases/20150325105152/lib/internal/Magento/Framework/App/Config/ScopePool.php(72): Magento\Framework\App\Config\ScopePool->_getScopeCode()
#8 /var/www/vhosts/magento2-capistrano/releases/20150325105152/lib/internal/Magento/Framework/App/Config.php(43): Magento\Framework\App\Config\ScopePool->getScope()
#9 /var/www/vhosts/magento2-capistrano/releases/20150325105152/lib/internal/Magento/Framework/View/DesignExceptions.php(64): Magento\Framework\App\Config->getValue()
#10 /var/www/vhosts/magento2-capistrano/releases/20150325105152/app/code/Magento/PageCache/Model/App/CacheIdentifierPlugin.php(43): Magento\Framework\View\DesignExceptions->getThemeByRequest()
#11 /var/www/vhosts/magento2-capistrano/shared/var/generation/Magento/Framework/App/PageCache/Identifier/Interceptor.php(109): Magento\PageCache\Model\App\CacheIdentifierPlugin->afterGetValue()
#12 /var/www/vhosts/magento2-capistrano/shared/var/generation/Magento/Framework/App/PageCache/Identifier/Interceptor.php(124): Magento\Framework\App\PageCache\Identifier\Interceptor->___callPlugins()
#13 /var/www/vhosts/magento2-capistrano/releases/20150325105152/lib/internal/Magento/Framework/App/PageCache/Kernel.php(51): Magento\Framework\App\PageCache\Identifier\Interceptor->getValue()
#14 /var/www/vhosts/magento2-capistrano/releases/20150325105152/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\PageCache\Kernel->load()
#15 (): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#16 /var/www/vhosts/magento2-capistrano/shared/var/generation/Magento/Framework/App/FrontController/Interceptor.php(100): call_user_func_array()
#17 /var/www/vhosts/magento2-capistrano/shared/var/generation/Magento/Framework/App/FrontController/Interceptor.php(124): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#18 /var/www/vhosts/magento2-capistrano/releases/20150325105152/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch()
#19 /var/www/vhosts/magento2-capistrano/releases/20150325105152/lib/internal/Magento/Framework/App/Bootstrap.php(245): Magento\Framework\App\Http->launch()
#20 /var/www/vhosts/magento2-capistrano/releases/20150325105152/index.php(39): Magento\Framework\App\Bootstrap->run()
#21 {main}
```

```
HipHop VM 3.7.0-dev (rel)
Compiler: heads/master-0-g62687825a2fdb86376b1749b1710bdfd9be6d1be
Repo schema: 317d5666575bd0e482c63cab2a39f8f4714f8678
```

**Comment by craigcarnell** [comment]
https://github.com/facebook/hhvm/issues/3623

**Comment by craigcarnell** [comment]
Nevermind

**Comment by IonutPerfectWeb** [comment]
+1, also have this problem
