### ISSUE TITLE
Exception: Notice: Array to string conversion Magento 2.1.8

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#11424]
Magento 2.1.8
PHP 7
Mysql 5.7
Debian

We are seeing the below error on exception log 

[2017-10-13 07:20:01] main.CRITICAL: Exception: Notice: Array to string conversion in /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 2929 in /var/www/vhosts/magento2.1.8//httpdocs/vendor/magento/framework/App/ErrorHandler.php:61$
Stack trace:
#0 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(2929): Magento\Framework\App\ErrorHandler->handler(8, 'Array to string...', '/var/www/vhosts...', 2929, Array)
#1 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Model/ResourceModel/AbstractResource.php(168): Magento\Framework\DB\Adapter\Pdo\Mysql->prepareColumnValue(Array, Array)
#2 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(728): Magento\Framework\Model\ResourceModel\AbstractResource->_prepareDataForTable(Object(Magento\Quote\Model\Quote\Addres$
#3 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(784): Magento\Framework\Model\ResourceModel\Db\AbstractDb->prepareDataForUpdate(Object(Magento\Quote\Model\Quote\Address\I$
#4 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(403): Magento\Framework\Model\ResourceModel\Db\AbstractDb->updateObject(Object(Magento\Quote\Model\Quote\Address\Intercept$
#5 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Model/AbstractModel.php(631): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Magento\Quote\Model\Quote\Address\Interceptor))
#6 /var/www/vhosts/magento2.1.8/httpdocs/var/generation/Magento/Quote/Model/Quote/Address/Interceptor.php(1649): Magento\Framework\Model\AbstractModel->save()
#7 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-quote/Model/ShippingAddressManagement.php(125): Magento\Quote\Model\Quote\Address\Interceptor->save()
#8 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingProcessor.php(66): Magento\Quote\Model\ShippingAddressManagement->assign('1654', Object(Magento\Quote\Model\Quote\Addr$
#9 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingAssignmentProcessor.php(110): Magento\Quote\Model\Quote\ShippingAssignment\ShippingProcessor->save(Object(Magento\Quot$
#10 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingAssignmentPersister.php(34): Magento\Quote\Model\Quote\ShippingAssignment\ShippingAssignmentProcessor->save(Object(Ma$
#11 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-quote/Model/QuoteRepository/SaveHandler.php(133): Magento\Quote\Model\Quote\ShippingAssignment\ShippingAssignmentPersister->save(Object(Magento\Quote\Model\Quote\$
#12 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-quote/Model/QuoteRepository/SaveHandler.php(106): Magento\Quote\Model\QuoteRepository\SaveHandler->processShippingAssignment(Object(Magento\Quote\Model\Quote\Inte$
#13 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-quote/Model/QuoteRepository.php(161): Magento\Quote\Model\QuoteRepository\SaveHandler->save(Object(Magento\Quote\Model\Quote\Interceptor))
#14 /var/www/vhosts/magento2.1.8/httpdocs/var/generation/Magento/Quote/Model/QuoteRepository/Interceptor.php(76): Magento\Quote\Model\QuoteRepository->save(Object(Magento\Quote\Model\Quote\Interceptor))
#15 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-checkout/Model/ShippingInformationManagement.php(156): Magento\Quote\Model\QuoteRepository\Interceptor->save(Object(Magento\Quote\Model\Quote\Interceptor))
#16 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Checkout\Model\ShippingInformationManagement->saveAddressInformation('1654', Object(Magento\Checkout\Model\ShippingIn$
#17 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Checkout\Model\ShippingInformationManagement\Interceptor->___callParent('saveAddressInfo...', Array)
#18 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'saveAddressInfo...', Object(Magento\Checkout\$
#19 /var/www/vhosts/magento2.1.8/httpdocs/app/code/Amasty/Orderattr/Plugin/Order/ShippingInformationManagement.php(37): Magento\Checkout\Model\ShippingInformationManagement\Interceptor->Magento\Framework\Interception\{closure}$
#20 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Interception/Interceptor.php(142): Amasty\Orderattr\Plugin\Order\ShippingInformationManagement->aroundSaveAddressInformation(Object(Magento\Checkout\Model\Ship$
#21 /var/www/vhosts/magento2.1.8/httpdocs/var/generation/Magento/Checkout/Model/ShippingInformationManagement/Interceptor.php(26): Magento\Checkout\Model\ShippingInformationManagement\Interceptor->___callPlugins('saveAddressIn$
#22 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-checkout/Model/GuestShippingInformationManagement.php(44): Magento\Checkout\Model\ShippingInformationManagement\Interceptor->saveAddressInformation('1654', Object$
#23 [internal function]: Magento\Checkout\Model\GuestShippingInformationManagement->saveAddressInformation('17c537ade1cf4e3...', Object(Magento\Checkout\Model\ShippingInformation))
#24 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#25 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#26 /var/www/vhosts/magento2.1.8/httpdocs/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#28 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\App\Http->launch()
#29 /var/www/vhosts/magento2.1.8/httpdocs/var/generation/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#30 /var/www/vhosts/magento2.1.8/httpdocs/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#31 /var/www/vhosts/magento2.1.8/httpdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#32 {main} [] []

**Comment by ishakhsuvarov** [comment]
@nmallepally, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by magento-engcom-team** [comment]
@nmallepally, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
