### ISSUE TITLE
Error when editing Attribut

### ISSUE THREAD

**Issue by ghost** [magento/magento2#11623]
### Preconditions

1. Magento 2.2
2. Php 7
3. Appache 2.4
### Steps to reproduce

1. store/attibutes/product
2. Edit ean attribute. I have add this attribute myself without problem but now, not possible to edit this attribute.
 

### Expected result

1. Attribute page edition

### Actual result

1.
1 exception(s):
Exception #0 (InvalidArgumentException): Unable to unserialize value.

Exception #0 (InvalidArgumentException): Unable to unserialize value.
#0 /var/www/html/vendor/magento/module-swatches/Block/Adminhtml/Product/Attribute/Edit/Form.php(78): Magento\Framework\Serialize\Serializer\Json->unserialize('')
#1 /var/www/html/vendor/magento/module-swatches/Block/Adminhtml/Product/Attribute/Edit/Form.php(59): Magento\Swatches\Block\Adminhtml\Product\Attribute\Edit\Form->getAdditionalData(Array)
#2 /var/www/html/vendor/magento/module-eav/Block/Adminhtml/Attribute/Edit/Main/AbstractMain.php(280): Magento\Swatches\Block\Adminhtml\Product\Attribute\Edit\Form->addValues(Array)
#3 /var/www/html/vendor/magento/module-backend/Block/Widget/Form.php(145): Magento\Eav\Block\Adminhtml\Attribute\Edit\Main\AbstractMain->_initFormValues()
#4 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(666): Magento\Backend\Block\Widget\Form->_beforeToHtml()
#5 /var/www/html/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#6 /var/www/html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('main_schedule_b...')
#7 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main_schedule_b...')
#8 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main_schedule_b...')
#9 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main_schedule_b...', true)
#10 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main_schedule_b...')
#11 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main')
#12 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#13 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#14 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', true)
#15 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement('main', true)
#16 /var/www/html/vendor/magento/module-catalog/Block/Adminhtml/Product/Attribute/Edit/Tabs.php(41): Magento\Framework\View\Element\AbstractBlock->getChildHtml('main')
#17 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(666): Magento\Catalog\Block\Adminhtml\Product\Attribute\Edit\Tabs->_beforeToHtml()
#18 /var/www/html/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#19 /var/www/html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('attribute_edit_...')
#20 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('attribute_edit_...')
#21 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('attribute_edit_...')
#22 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('attribute_edit_...', true)
#23 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('attribute_edit_...')
#24 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('left')
#25 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('left')
#26 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('left')
#27 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('left', true)
#28 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('left')
#29 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('side.col')
#30 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('side.col')
#31 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('side.col')
#32 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('side.col', true)
#33 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('side.col')
#34 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#35 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#36 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#37 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#38 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#39 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.content')
#40 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#41 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#42 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#43 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#44 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#45 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#46 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#47 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#48 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#49 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('backend.page')
#50 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#51 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#52 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#53 /var/www/html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#54 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#55 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#56 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#57 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#58 /var/www/html/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#59 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#60 /var/www/html/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#61 /var/www/html/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#62 /var/www/html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#63 /var/www/html/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#64 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#65 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent('launch', Array)
#66 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#67 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#68 /var/www/html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#69 /var/www/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#70 {main}

**Comment by ghost** [comment]
Solved with store Manager.

edit catalog_eav_attribute table

check the 'null' box in additional_data field for attribute with problem.

![solved](https://user-images.githubusercontent.com/17496183/31859642-c2f817b0-b70e-11e7-8531-72421d11de98.png)
