### ISSUE TITLE
Configurable product Price not updated when choosing other variation in frontend

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#11647]
### Preconditions

1. Magento version 2.1.8
2. 

### Steps to reproduce

1.  Add configurable product
2. Add variations based on attribute size (swatch)
3. Set different prices for each variation

### Expected result

1. Would expect a different price when choosing different size swatch  in frontend product page but price isn't updated

### Actual result

1. Price stays the same
2. url http://www.thehouseofthings.com/thotstaging/gramercy-zebra-rug.html

**Comment by magento-engcom-team** [comment]
@hemendraajmera We can't reproduce this issue. Please install clean and fresh Magento, and try to reproduce this issue again.

**Comment by hemendraajmera** [comment]
Fresh install need to install and configure all data.

**Comment by hemendraajmera** [comment]
Can you please share URL for reference

**Comment by hemendraajmera** [comment]
![image](https://user-images.githubusercontent.com/2478037/31890348-6c7f228a-b820-11e7-9cf3-9f7a9c80a1f0.png)

Please refer above product variant and check on below URL
http://www.thehouseofthings.com/thotstaging/gramercy-zebra-rug.html

**Comment by orlangur** [comment]
@hemendraajmera it seems like your store is broken.

When I open product page there is JS error in console:
```
mailchimpjs.js:1 Uncaught TypeError: require is not a function
    at mailchimpjs.js:1
```

When I choose size swatch:
```
swatch-renderer.js:947 Uncaught TypeError: $(...).AddFotoramaVideoEvents is not a function
    at $.(anonymous function).(anonymous function).updateBaseImage (http://www.thehouseofthings.com/thotstaging/pub/static/frontend/Advaiya/thot/en_US/Magento_Swatches/js/swatch-renderer.js:947:58)
    at $.(anonymous function).(anonymous function).updateBaseImage (http://www.thehouseofthings.com/thotstaging/pub/static/frontend/Advaiya/thot/en_US/jquery/jquery-ui.js:402:25)
    at $.(anonymous function).(anonymous function)._ProductMediaCallback (http://www.thehouseofthings.com/thotstaging/pub/static/frontend/Advaiya/thot/en_US/Magento_Swatches/js/swatch-renderer.js:902:18)
    at $.(anonymous function).(anonymous function)._ProductMediaCallback (http://www.thehouseofthings.com/thotstaging/pub/static/frontend/Advaiya/thot/en_US/jquery/jquery-ui.js:402:25)
    at Object.mediaSuccessCallback [as success] (http://www.thehouseofthings.com/thotstaging/pub/static/frontend/Advaiya/thot/en_US/Magento_Swatches/js/swatch-renderer.js:768:29)
    at fire (http://www.thehouseofthings.com/thotstaging/pub/static/frontend/Advaiya/thot/en_US/jquery.js:3232:32)
    at Object.fireWith [as resolveWith] (http://www.thehouseofthings.com/thotstaging/pub/static/frontend/Advaiya/thot/en_US/jquery.js:3362:8)
    at done (http://www.thehouseofthings.com/thotstaging/pub/static/frontend/Advaiya/thot/en_US/jquery.js:9840:15)
    at XMLHttpRequest.callback (http://www.thehouseofthings.com/thotstaging/pub/static/frontend/Advaiya/thot/en_US/jquery.js:10311:9)
```

Before reporting bugs to this repo please make sure they are not caused by store customizations.

**Comment by magento-engcom-team** [comment]
@hemendraajmera We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by hemendraajmera** [comment]
I have reproduced the issue and the issue is related to CSS. I have changed product-info-main class to --product-info-main, that is the reason it will not work.

Thanks for your support.
