### ISSUE TITLE
Upgrade support

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#1194]
Hi,

As we are at beta 4 I am planning on begenning some development work. But I don't want my database to be useless in future upgrades (beta 5, beta 6, rc1 etc).

Will the code supplied by yourselves run sql update scripts as the version changes in modules as in previous versions of Magento?

I don't want to be in a position where I have created a lot of work in the back end to lose it all!

I did try upgrading from beta1 to beta 4 and I had an error. I just gave up and reinstalled, this was not an issue for now but it will be in the future.

Also, is there scripts for converting CE 1.9.xx DBs to 2.xx?

**Comment by choukalos** [comment]
We'll be releasing our migration tool soon.  @ilol can provide more details on when.  Check out our Dev RC webinar for details on the migration tool ( https://vimeo.com/123755065 ).  @tanya-soroka can provide details on our upgrade plans through merchant beta.

**Comment by craigcarnell** [comment]
@ilol @choukalos @tanya-soroka 

I've just upgraded from beta 4 to beta 5. I am instructed to run bin/magento setup:upgrade.. It doesn't work!

```
./magento setup:upgrade --verbose
Cache cleared successfully
File system cleanup:
/var/www/vhosts/magento2-capistrano/releases/20150420113227/var/generation/Magento
Updating modules:


                                                     
  [Magento\Framework\Exception\FileSystemException]  
  File "%1" cannot be opened %2                      
                                                     


Exception trace:
 () at /var/www/vhosts/magento2-capistrano/releases/20150420113227/lib/internal/Magento/Framework/Filesystem/Driver/File.php:472
 Magento\Framework\Filesystem\Driver\File->fileOpen() at /var/www/vhosts/magento2-capistrano/releases/20150420113227/lib/internal/Magento/Framework/Filesystem/File/Read.php:62
 Magento\Framework\Filesystem\File\Read->open() at /var/www/vhosts/magento2-capistrano/releases/20150420113227/lib/internal/Magento/Framework/Filesystem/File/Read.php:51
 Magento\Framework\Filesystem\File\Read->__construct() at /var/www/vhosts/magento2-capistrano/releases/20150420113227/lib/internal/Magento/Framework/Filesystem/File/Write.php:23
 Magento\Framework\Filesystem\File\Write->__construct() at /var/www/vhosts/magento2-capistrano/releases/20150420113227/lib/internal/Magento/Framework/Filesystem/File/WriteFactory.php:43
 Magento\Framework\Filesystem\File\WriteFactory->create() at /var/www/vhosts/magento2-capistrano/releases/20150420113227/lib/internal/Magento/Framework/Filesystem/Directory/Write.php:234
 Magento\Framework\Filesystem\Directory\Write->openFile() at /var/www/vhosts/magento2-capistrano/releases/20150420113227/lib/internal/Magento/Framework/Filesystem/Directory/Write.php:248
 Magento\Framework\Filesystem\Directory\Write->writeFile() at /var/www/vhosts/magento2-capistrano/releases/20150420113227/lib/internal/Magento/Framework/App/DeploymentConfig/Writer.php:111
 Magento\Framework\App\DeploymentConfig\Writer->saveConfig() at /var/www/vhosts/magento2-capistrano/releases/20150420113227/setup/src/Magento/Setup/Model/Installer.php:330
 Magento\Setup\Model\Installer->createModulesConfig() at /var/www/vhosts/magento2-capistrano/releases/20150420113227/setup/src/Magento/Setup/Model/Installer.php:885
 Magento\Setup\Model\Installer->updateModulesSequence() at /var/www/vhosts/magento2-capistrano/releases/20150420113227/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php:55
 Magento\Setup\Console\Command\UpgradeCommand->execute() at /var/www/vhosts/magento2-capistrano/shared/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /var/www/vhosts/magento2-capistrano/shared/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /var/www/vhosts/magento2-capistrano/shared/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /var/www/vhosts/magento2-capistrano/shared/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /var/www/vhosts/magento2-capistrano/releases/20150420113227/bin/magento:12


setup:upgrade [--magento_init_params="..."]
```

HTML output:

```
Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. %1The following modules are outdated:%2%3
#0 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#1 /var/www/vhosts/magento2-capistrano/releases/20150420113227/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): call_user_func_array(Array, Array)
#2 /var/www/vhosts/magento2-capistrano/releases/20150420113227/lib/internal/Magento/Framework/Interception/Chain/Chain.php(58): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#3 /var/www/vhosts/magento2-capistrano/releases/20150420113227/app/code/Magento/PageCache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#4 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#5 /var/www/vhosts/magento2-capistrano/releases/20150420113227/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): call_user_func_array(Array, Array)
#6 /var/www/vhosts/magento2-capistrano/shared/var/generation/Magento/Framework/App/FrontController/Interceptor.php(95): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#7 /var/www/vhosts/magento2-capistrano/releases/20150420113227/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\App\FrontController\{closure}(Object(Magento\Framework\App\Request\Http))
#8 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#9 /var/www/vhosts/magento2-capistrano/shared/var/generation/Magento/Framework/App/FrontController/Interceptor.php(100): call_user_func_array(Array, Array)
#10 /var/www/vhosts/magento2-capistrano/shared/var/generation/Magento/Framework/App/FrontController/Interceptor.php(124): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#11 /var/www/vhosts/magento2-capistrano/releases/20150420113227/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#12 /var/www/vhosts/magento2-capistrano/releases/20150420113227/lib/internal/Magento/Framework/App/Bootstrap.php(245): Magento\Framework\App\Http->launch()
#13 /var/www/vhosts/magento2-capistrano/releases/20150420113227/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#14 {main}
```

**Comment by craigcarnell** [comment]
@choukalos I successfully upgraded from beta4 to beta5 (except for an issue which was down to permissions)

**Comment by ilol** [comment]
@craigcarnell, please try the tool here (https://github.com/magento/data-migration-tool-ce). Please, give me your opinion about one. Thanks
