### ISSUE TITLE
Source generation failure with hirak/presstisimo plugin

### ISSUE THREAD

**Issue by joshuaadickerson** [magento/magento2#12085]
I tried to do a composer install and I get an error from Magento. It's failing on the hirak/presstisimo plugin that allows parallel Composer install. 

### Preconditions

1. `composer global require hirak/prestissimo`
2. Magento 2.2
3. PHP 7.1

### Steps to reproduce

1. Run `composer global require hirak/prestissimo`
2. Run `composer install -o`

### Expected result

1. No errors on install

### Actual result
```Installing composer dependencies...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
Source class "\Hirak\Prestissimo\ParallelizedComposerInterface" for "Hirak\Prestissimo\ParallelizedComposerRepository" generation does not exist.#0 /var/www/html/vendor/magento/framework/Code/Generator.php(112): Magento\Framework\Code\Generator->tryToLoadSourceClass('Hirak\\Prestissi...', Object(Magento\Framework\ObjectManager\Code\Generator\Repository))
#1 /var/www/html/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Hirak\\Prestissi...')
#2 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Hirak\\Prestissi...')
#3 [internal function]: spl_autoload_call('Hirak\\Prestissi...')
#4 /var/www/html/var/composer_home/vendor/hirak/prestissimo/src/Plugin.php(63): class_exists('Hirak\\Prestissi...')
#5 /var/www/html/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(236): Hirak\Prestissimo\Plugin->activate(Object(Composer\Composer), Object(Composer\IO\BufferIO))
#6 /var/www/html/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Hirak\Prestissimo\Plugin))
#7 /var/www/html/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(261): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage))
#8 /var/www/html/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(79): Composer\Plugin\PluginManager->loadRepository(Object(Composer\Repository\InstalledFilesystemRepository))
#9 /var/www/html/vendor/composer/composer/src/Composer/Factory.php(377): Composer\Plugin\PluginManager->loadInstalledPlugins()
#10 /var/www/html/vendor/composer/composer/src/Composer/Factory.php(569): Composer\Factory->createComposer(Object(Composer\IO\BufferIO), Array, false)
#11 /var/www/html/vendor/magento/framework/Composer/ComposerFactory.php(47): Composer\Factory::create(Object(Composer\IO\BufferIO), '/var/www/html/c...')
#12 /var/www/html/vendor/magento/framework/Composer/ComposerInformation.php(362): Magento\Framework\Composer\ComposerFactory->create()
#13 /var/www/html/vendor/magento/framework/Composer/ComposerInformation.php(375): Magento\Framework\Composer\ComposerInformation->getComposer()
#14 /var/www/html/vendor/magento/framework/Composer/ComposerInformation.php(242): Magento\Framework\Composer\ComposerInformation->getLocker()
#15 /var/www/html/vendor/magento/framework/App/ProductMetadata.php(104): Magento\Framework\Composer\ComposerInformation->getSystemPackages()
#16 /var/www/html/vendor/magento/framework/App/ProductMetadata.php(65): Magento\Framework\App\ProductMetadata->getSystemPackageVersion()
#17 /var/www/html/vendor/magento/framework/Console/Cli.php(91): Magento\Framework\App\ProductMetadata->getVersion()
#18 /var/www/html/bin/magento(22): Magento\Framework\Console\Cli->__construct('Magento CLI')
#19 {main}```

<!--- (This may be platform independent comment) -->

**Comment by magento-engcom-team** [comment]
@joshuaadickerson, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by magento-engcom-team** [comment]
@joshuaadickerson, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by spras** [comment]
We reproduce this issue, on 2.2.5, **after login in Back-Office.** 

I occurs when hirak/prestissimo is installed globally in  var/composer_home/
