### ISSUE TITLE
When applying new theme i get "Something went wrong while saving this configuration"

### ISSUE THREAD

**Issue by jtlindsey** [magento/magento2#12156]
### Preconditions

1. Magento 2.2.0
2. Nginx 1.10.3
3. PHP7
4. Ubuntu Server 16.04 LTS

### Steps to reproduce

1. Default installation, go to web admin > Content > Configuration
2. Click "Edit" under action column for a row with a Website, Store and Store View content.
3. The applied theme says "Magento Luma". In dropdown choose anything else ("Magento Blank", or "No Theme").
4. Click "Save Configuration" 

### Expected result

1. New theme applied with no errors.

### Actual result

Web view has the following message:

`Something went wrong while saving this configuration: Warning: is_file() expects parameter 1 to be a valid path, string given in /opt/magento2ce/vendor/colinmollenhour/cache-backend-file/File.php on line 512`

Looking at `tail -f /opt/magento2ce/var/log/system.log` when completing step 4, i get:

```
[2017-11-09 18:24:42] main.CRITICAL: Exception message: Warning: is_file() expects parameter 1 to be a valid path, string given in /opt/magento2ce/vendor/colinmollenhour/cache-backend-file/File.php on line 512
Trace: #0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'is_file() expec...', '/opt/magento2ce...', 512, Array)
#1 /opt/magento2ce/vendor/colinmollenhour/cache-backend-file/File.php(512): is_file('/opt/magento2ce...')
#2 /opt/magento2ce/vendor/colinmollenhour/cache-backend-file/File.php(227): Cm_Cache_Backend_File->_cleanNew('matchingTag', Array)
#3 /opt/magento2ce/vendor/magento/zendframework1/library/Zend/Cache/Core.php(465): Cm_Cache_Backend_File->clean('matchingTag', Array)
#4 /opt/magento2ce/vendor/magento/framework/Cache/Core.php(98): Zend_Cache_Core->clean('matchingTag', Array)
#5 /opt/magento2ce/vendor/magento/framework/Cache/Frontend/Adapter/Zend.php(79): Magento\Framework\Cache\Core->clean('matchingTag', Array)
#6 /opt/magento2ce/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(91): Magento\Framework\Cache\Frontend\Adapter\Zend->clean('matchingTag', Array)
#7 /opt/magento2ce/vendor/magento/framework/Cache/Frontend/Decorator/TagScope.php(75): Magento\Framework\Cache\Frontend\Decorator\Bare->clean('matchingTag', Array)
#8 /opt/magento2ce/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(91): Magento\Framework\Cache\Frontend\Decorator\TagScope->clean('matchingTag', Array)
#9 /opt/magento2ce/vendor/magento/framework/Cache/Frontend/Decorator/Logger.php(47): Magento\Framework\Cache\Frontend\Decorator\Bare->clean('all', Array, 'all')
#10 /opt/magento2ce/vendor/magento/framework/App/Cache.php(102): Magento\Framework\Cache\Frontend\Decorator\Logger->clean()
#11 /opt/magento2ce/vendor/magento/framework/App/Cache/Proxy.php(103): Magento\Framework\App\Cache->clean(Array)
#12 /opt/magento2ce/vendor/magento/framework/Model/AbstractModel.php(803): Magento\Framework\App\Cache\Proxy->clean(Array)
#13 /opt/magento2ce/generated/code/Magento/Robots/Model/Config/Value/Interceptor.php(440): Magento\Framework\Model\AbstractModel->cleanModelCache()
#14 /opt/magento2ce/vendor/magento/framework/Model/AbstractModel.php(815): Magento\Robots\Model\Config\Value\Interceptor->cleanModelCache()
#15 /opt/magento2ce/vendor/magento/framework/App/Config/Value.php(122): Magento\Framework\Model\AbstractModel->afterSave()
#16 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Config\Value->afterSave()
#17 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Robots\Model\Config\Value\Interceptor->___callParent('afterSave', Array)
#18 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Robots\Model\Config\Value\Interceptor->Magento\Framework\Interception\{closure}()
#19 /opt/magento2ce/generated/code/Magento/Robots/Model/Config/Value/Interceptor.php(78): Magento\Robots\Model\Config\Value\Interceptor->___callPlugins('afterSave', Array, Array)
#20 /opt/magento2ce/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(832): Magento\Robots\Model\Config\Value\Interceptor->afterSave()
#21 /opt/magento2ce/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(418): Magento\Framework\Model\ResourceModel\Db\AbstractDb->processAfterSaves(Object(Magento\Robots\Model\Config\Value\Interceptor))
#22 /opt/magento2ce/vendor/magento/framework/Model/AbstractModel.php(647): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Magento\Robots\Model\Config\Value\Interceptor))
#23 /opt/magento2ce/generated/code/Magento/Robots/Model/Config/Value/Interceptor.php(362): Magento\Framework\Model\AbstractModel->save()
#24 /opt/magento2ce/vendor/magento/framework/DB/Transaction.php(129): Magento\Robots\Model\Config\Value\Interceptor->save()
#25 /opt/magento2ce/vendor/magento/module-theme/Model/Design/Config/Storage.php(132): Magento\Framework\DB\Transaction->save()
#26 /opt/magento2ce/vendor/magento/module-theme/Model/DesignConfigRepository.php(93): Magento\Theme\Model\Design\Config\Storage->save(Object(Magento\Theme\Model\Data\Design\Config))
#27 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Theme\Model\DesignConfigRepository->save(Object(Magento\Theme\Model\Data\Design\Config))
#28 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Theme\Model\DesignConfigRepository\Interceptor->___callParent('save', Array)
#29 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Theme\Model\DesignConfigRepository\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Theme\Model\Data\Design\Config))
#30 /opt/magento2ce/generated/code/Magento/Theme/Model/DesignConfigRepository/Interceptor.php(39): Magento\Theme\Model\DesignConfigRepository\Interceptor->___callPlugins('save', Array, Array)
#31 /opt/magento2ce/vendor/magento/module-theme/Controller/Adminhtml/Design/Config/Save.php(75): Magento\Theme\Model\DesignConfigRepository\Interceptor->save(Object(Magento\Theme\Model\Data\Design\Config))
#32 /opt/magento2ce/generated/code/Magento/Theme/Controller/Adminhtml/Design/Config/Save/Interceptor.php(24): Magento\Theme\Controller\Adminhtml\Design\Config\Save->execute()
#33 /opt/magento2ce/vendor/magento/framework/App/Action/Action.php(107): Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor->execute()
#34 /opt/magento2ce/vendor/magento/module-backend/App/AbstractAction.php(229): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#35 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#36 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor->___callParent('dispatch', Array)
#37 /opt/magento2ce/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#38 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#39 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#40 /opt/magento2ce/generated/code/Magento/Theme/Controller/Adminhtml/Design/Config/Save/Interceptor.php(39): Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor->___callPlugins('dispatch', Array, NULL)
#41 /opt/magento2ce/vendor/magento/framework/App/FrontController.php(55): Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#42 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#43 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#44 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#45 /opt/magento2ce/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#46 /opt/magento2ce/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#47 /opt/magento2ce/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#48 /opt/magento2ce/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#49 {main} [] []
```

**Comment by jtlindsey** [comment]
Also, right now the _default_ theme is working, just can't change it:

![theme1](https://user-images.githubusercontent.com/7409277/32622772-034cbdb0-c552-11e7-8276-f25b281a08d0.png)

**Comment by jtlindsey** [comment]
Running `chown -R :www-data var/cache/mage-tags/` similar to #3 in the original setup [docs](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/nginx.html) got past the error message. But I'm not sure why I would have to keep running that command. SGID is set on the magento2ce dir and i've tested it by creating a new file as root and see it gets the correct group ownership. All files in the '/opt/magento2ce' have `appsuser:www-data` for ownership.  And there were no permission related errors in the logs as you can see from original post.

~~I'm going to run the sticky bit with `-R` like `chmod -R g+s /opt/magento2ce/` to see if that prevents future errors unless i find something else.~~

Update, even with sticky bit set we also randomly get the following error msg and i have to re-run the command `chown -R :www-data var/cache/mage-tags/` from the project dir:
```
1 exception(s):
Exception #0 (Exception): Warning: file_put_contents(/opt/magento2ce/var/cache//mage-tags/mage---3d0_TRANSLATE): failed to open stream: Permission denied in /opt/magento2ce/vendor/colinmollenhour/cache-backend-file/File.php on line 663

Exception #0 (Exception): Warning: file_put_contents(/opt/magento2ce/var/cache//mage-tags/mage---3d0_TRANSLATE): failed to open stream: Permission denied in /opt/magento2ce/vendor/colinmollenhour/cache-backend-file/File.php on line 663
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'file_put_conten...', '/opt/magento2ce...', 663, Array)
#1 /opt/magento2ce/vendor/colinmollenhour/cache-backend-file/File.php(663): file_put_contents('/opt/magento2ce...', '3d0_TRANSLATE_E...', 10)
#2 /opt/magento2ce/vendor/colinmollenhour/cache-backend-file/File.php(179): Cm_Cache_Backend_File->_updateIdsTags(Array, Array, 'merge')
#3 /opt/magento2ce/vendor/magento/zendframework1/library/Zend/Cache/Core.php(390): Cm_Cache_Backend_File->save('{"123":"123","\\...', '3d0_TRANSLATE_E...', Array, false)
#4 /opt/magento2ce/vendor/magento/framework/Cache/Core.php(74): Zend_Cache_Core->save('{"123":"123","\\...', '3d0_TRANSLATE_E...', Array, false, 8)
#5 /opt/magento2ce/vendor/magento/framework/Cache/Frontend/Adapter/Zend.php(47): Magento\Framework\Cache\Core->save('{"123":"123","\\...', 'TRANSLATE_EN_US...', Array, false)
#6 /opt/magento2ce/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(75): Magento\Framework\Cache\Frontend\Adapter\Zend->save('{"123":"123","\\...', 'translate_en_US...', Array, false)
#7 /opt/magento2ce/vendor/magento/framework/Cache/Frontend/Decorator/TagScope.php(51): Magento\Framework\Cache\Frontend\Decorator\Bare->save('{"123":"123","\\...', 'translate_en_US...', Array, false)
#8 /opt/magento2ce/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(75): Magento\Framework\Cache\Frontend\Decorator\TagScope->save('{"123":"123","\\...', 'translate_en_US...', Array, false)
#9 /opt/magento2ce/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(75): Magento\Framework\Cache\Frontend\Decorator\Bare->save('{"123":"123","\\...', 'translate_en_US...', Array, false)
#10 /opt/magento2ce/vendor/magento/framework/App/Cache/Type/AccessProxy.php(85): Magento\Framework\Cache\Frontend\Decorator\Bare->save('{"123":"123","\\...', 'translate_en_US...', Array, false)
#11 /opt/magento2ce/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(75): Magento\Framework\App\Cache\Type\AccessProxy->save('{"123":"123","\\...', 'translate_en_US...', Array, false)
#12 /opt/magento2ce/vendor/magento/framework/Cache/Frontend/Decorator/TagScope.php(51): Magento\Framework\Cache\Frontend\Decorator\Bare->save('{"123":"123","\\...', 'translate_en_US...', Array, false)
#13 /opt/magento2ce/vendor/magento/framework/Translate.php(494): Magento\Framework\Cache\Frontend\Decorator\TagScope->save('{"123":"123","\\...', 'translate_en_US...', Array, false)
#14 /opt/magento2ce/vendor/magento/framework/Translate.php(190): Magento\Framework\Translate->_saveCache()
#15 /opt/magento2ce/vendor/magento/framework/App/Area.php(244): Magento\Framework\Translate->loadData(NULL, false)
#16 /opt/magento2ce/vendor/magento/framework/App/Area.php(215): Magento\Framework\App\Area->_initTranslate()
#17 /opt/magento2ce/vendor/magento/framework/App/Area.php(142): Magento\Framework\App\Area->_loadPart('translate')
#18 /opt/magento2ce/vendor/magento/framework/View/DesignLoader.php(55): Magento\Framework\App\Area->load('translate')
#19 /opt/magento2ce/vendor/magento/framework/App/Action/Plugin/Design.php(48): Magento\Framework\View\DesignLoader->load()
#20 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Framework\App\Action\Plugin\Design->beforeDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Magento\Framework\App\Request\Http))
#21 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#22 /opt/magento2ce/generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php(26): Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#23 /opt/magento2ce/vendor/magento/framework/App/FrontController.php(55): Magento\Cms\Controller\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#26 /opt/magento2ce/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /opt/magento2ce/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#29 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /opt/magento2ce/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /opt/magento2ce/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#32 /opt/magento2ce/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#33 /opt/magento2ce/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#34 /opt/magento2ce/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#35 {main}
```

**Comment by jtlindsey** [comment]
After doing more testing, the issue seems to only happen when `magento setup:upgrade` is run as 'appsuser' or if `bin/magento setup:di:compile` is run as `appsuser`. For reference here is web server user and checking groups:

```
# ps aux | grep nginx
root     23987  0.0  0.0  14224   992 pts/0    S+   18:18   0:00 grep --color=auto nginx
root     26437  0.0  0.0 125928  1740 ?        Ss   18:01   0:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
www-data 26438  0.0  0.1 126304  5740 ?        S    18:01   0:00 nginx: worker process
www-data 26439  0.0  0.0 125928  3392 ?        S    18:01   0:00 nginx: worker process
www-data 26440  0.0  0.1 126460  6060 ?        S    18:01   0:00 nginx: worker process
www-data 26441  0.0  0.0 125928  3392 ?        S    18:01   0:00 nginx: worker process


# groups appsuser 
appsuser : appsuser www-data
```


The permissions that end up wrong are always in `var/cache/mage-tags/` They have the web server file owner (appsuser) as the user and group owner when it should be `appsuser:www-data` like the rest of '/opt/magento2ce/` directory.

Running the following always resolves the issue:
`chown -R :www-data var/cache/mage-tags/`

**Comment by magento-engcom-team** [comment]
@jtlindsey , please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by jtlindsey** [comment]
Ref Magento Stack Exchange [here](https://magento.stackexchange.com/questions/200954/permissions-problem-with-magento-2-2-0-nginx-ubuntu-server-only-in-var-cache-m)
