### ISSUE TITLE
Exception when trying to add new integration from backend

### ISSUE THREAD

**Issue by karimsamir** [magento/magento2#12833]
Preconditions
Magento 2.0.7

Steps to reproduce
Login to backend
Go to system->integrations
Click "add new integration". or "reauthoirze"

Expected result
There should be a form to add new integration or or "reauthoirze" existing web service

Actual result
It throws an exception, details below:

main.CRITICAL: exception 'Magento\Framework\Exception\AuthorizationException' with message 'We can't find the role for the user you wanted.' in /magento/vendor/magento/module-authorization/Model/Acl/AclRetriever.php:78

Stack trace:

[2017-12-20 16:41:46] main.CRITICAL: exception 'Magento\Framework\Exception\AuthorizationException' with message 'We can't find the role for the user you wanted.' in /magento/vendor/magento/module-authorization/Model/Acl/AclRetriever.php:78
Stack trace:
#0 /magento/vendor/magento/module-integration/Model/Plugin/Integration.php(99): Magento\Authorization\Model\Acl\AclRetriever->getAllowedResourcesByUser(1, 1)
#1 /magento/vendor/magento/module-integration/Model/Plugin/Integration.php(81): Magento\Integration\Model\Plugin\Integration->_addAllowedResources(Object(Magento\Integration\Model\Integration))
#2 /magento/vendor/magento/framework/Interception/Interceptor.php(150): Magento\Integration\Model\Plugin\Integration->afterGet(Object(Magento\Integration\Model\IntegrationService\Interceptor), Object(Magento\Integration\Model\Integration))
#3 /magento/var/generation/Magento/Integration/Model/IntegrationService/Interceptor.php(65): Magento\Integration\Model\IntegrationService\Interceptor->___callPlugins('get', Array, Array)
#4 /magento/vendor/magento/module-integration/Controller/Adminhtml/Integration/Edit.php(26): Magento\Integration\Model\IntegrationService\Interceptor->get(1)
#5 /magento/var/generation/Magento/Integration/Controller/Adminhtml/Integration/Edit/Interceptor.php(25): Magento\Integration\Controller\Adminhtml\Integration\Edit->execute()
#6 /magento/vendor/magento/framework/App/Action/Action.php(102): Magento\Integration\Controller\Adminhtml\Integration\Edit\Interceptor->execute()
#7 /magento/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#8 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /magento/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#10 /magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Integration\Controller\Adminhtml\Integration\Edit\Interceptor->___callParent('dispatch', Array)
#11 /magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Integra...', 'dispatch', Object(Magento\Integration\Controller\Adminhtml\Integration\Edit\Interceptor), Array, 'adminAuthentica...')
#12 /magento/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#13 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Integration\Controller\Adminhtml\Integration\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /magento/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#15 /magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Integra...', 'dispatch', Object(Magento\Integration\Controller\Adminhtml\Integration\Edit\Interceptor), Array, 'designLoader')
#16 /magento/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#17 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Integration\Controller\Adminhtml\Integration\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /magento/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#19 /magento/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Integra...', 'dispatch', Object(Magento\Integration\Controller\Adminhtml\Integration\Edit\Interceptor), Array, 'adminMassaction...')
#20 /magento/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Integration\Controller\Adminhtml\Integration\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Integration\Controller\Adminhtml\Integration\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /magento/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#23 /magento/var/generation/Magento/Integration/Controller/Adminhtml/Integration/Edit/Interceptor.php(40): Magento\Integration\Controller\Adminhtml\Integration\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#24 /magento/vendor/magento/framework/App/FrontController.php(55): Magento\Integration\Controller\Adminhtml\Integration\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#25 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /magento/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#27 /magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#28 /magento/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#29 /magento/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#30 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /magento/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#32 /magento/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#33 /magento/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /magento/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#35 /magento/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#36 {main} [] []

**Comment by magento-engcom-team** [comment]
@karimsamir , thank you for your report.
We were not able to reproduce this issue on the clean installation by following the steps you provided.
Please try to reproduce this issue on a clean installation.

**Comment by karimsamir** [comment]
I don't know how did this happen, but finally, I found the fix, inserting a row in table authorization_role like this

```
INSERT INTO `authorization_role` 
	(
	`parent_id`, `tree_level`, `sort_order`, `role_type`, `user_id`, 
	`user_type`, `role_name`
	)
	values
	('0', '1', '0', 'U', '1', 
'1', '11');
```
where user_id is the id on integration in `integration` table
I don't why it was removed in the first place, it might help anyone

**Comment by magento-engcom-team** [comment]
So on a clean installation, you also aren't able to reproduce this issue. Do we understand you right?

**Comment by magento-engcom-team** [comment]
@karimsamir, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
