### ISSUE TITLE
error during installation 

### ISSUE THREAD

**Issue by stefanorg** [magento/magento2#1283]
Magento Version: 0.74.0-beta9

```
Installing user configuration...
[ERROR] exception 'Magento\Framework\Exception\LocalizedException' with message 'Source class "\arrayArgumentInterpreter" for "arrayArgumentInterpreterProxy" generation does not exist.' in /var/www/app/lib/internal/Magento/Framework/Code/Generator.php:181
Stack trace:
#0 /var/www/app/lib/internal/Magento/Framework/Code/Generator.php(103): Magento\Framework\Code\Generator->tryToLoadSourceClass('arrayArgumentIn...', Object(Magento\Framework\ObjectManager\Code\Generator\Proxy))
#1 /var/www/app/lib/internal/Magento/Framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('arrayArgumentIn...')
#2 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('arrayArgumentIn...')
#3 [internal function]: spl_autoload_call('arrayArgumentIn...')
#4 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Relations/Runtime.php(38): class_exists('arrayArgumentIn...')
#5 /var/www/app/lib/internal/Magento/Framework/Interception/PluginList/PluginList.php(130): Magento\Framework\ObjectManager\Relations\Runtime->has('arrayArgumentIn...')
#6 /var/www/app/lib/internal/Magento/Framework/Interception/PluginList/PluginList.php(301): Magento\Framework\Interception\PluginList\PluginList->_inheritPlugins('arrayArgumentIn...')
#7 /var/www/app/lib/internal/Magento/Framework/Interception/PluginList/PluginList.php(249): Magento\Framework\Interception\PluginList\PluginList->_loadScopedData()
#8 /var/www/app/var/generation/Magento/Store/Model/Resource/Website/Interceptor.php(185): Magento\Framework\Interception\PluginList\PluginList->getNext('Magento\\Store\\M...', 'getReadConnecti...')
#9 /var/www/app/lib/internal/Magento/Framework/Model/Resource/Db/Collection/AbstractCollection.php(121): Magento\Store\Model\Resource\Website\Interceptor->getReadConnection()
#10 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(107): Magento\Framework\Model\Resource\Db\Collection\AbstractCollection->__construct(Object(Magento\Framework\Data\Collection\EntityFactory), Object(Magento\Framework\Logger\Monolog), Object(Magento\Framework\Data\Collection\Db\FetchStrategy\Cache), Object(Magento\Framework\Event\Manager\Proxy), NULL, NULL)
#11 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(91): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Store\\M...', Array)
#12 /var/www/app/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Store\\M...', Array)
#13 /var/www/app/var/generation/Magento/Store/Model/Resource/Website/CollectionFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create('\\Magento\\Store\\...', Array)
#14 /var/www/app/app/code/Magento/Store/Model/Storage/Db.php(198): Magento\Store\Model\Resource\Website\CollectionFactory->create()
#15 /var/www/app/app/code/Magento/Store/Model/Storage/Db.php(468): Magento\Store\Model\Storage\Db->_initStores()
#16 /var/www/app/app/code/Magento/Store/Model/StorageFactory.php(142): Magento\Store\Model\Storage\Db->reinitStores()
#17 /var/www/app/app/code/Magento/Store/Model/StorageFactory.php(117): Magento\Store\Model\StorageFactory->_reinitStores(Object(Magento\Store\Model\Storage\Db), Array)
#18 /var/www/app/app/code/Magento/Store/Model/StoreManager.php(121): Magento\Store\Model\StorageFactory->get(Array)
#19 /var/www/app/app/code/Magento/Store/Model/StoreManager.php(175): Magento\Store\Model\StoreManager->_getStorage()
#20 /var/www/app/var/generation/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore(NULL)
#21 /var/www/app/app/code/Magento/Store/Model/Resolver/Store.php(29): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL)
#22 /var/www/app/lib/internal/Magento/Framework/App/Config/ScopePool.php(119): Magento\Store\Model\Resolver\Store->getScope(NULL)
#23 /var/www/app/lib/internal/Magento/Framework/App/Config/ScopePool.php(74): Magento\Framework\App\Config\ScopePool->_getScopeCode('store', NULL)
#24 /var/www/app/lib/internal/Magento/Framework/App/Config.php(45): Magento\Framework\App\Config\ScopePool->getScope('store', NULL)
#25 /var/www/app/lib/internal/Magento/Framework/Session/Config.php(152): Magento\Framework\App\Config->getValue('web/cookie/cook...', 'store')
#26 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Framework\Session\Config->__construct(Object(Magento\Framework\ValidatorFactory), Object(Magento\Framework\App\Config), Object(Magento\Framework\Stdlib\String), Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Filesystem), Object(Magento\Framework\App\DeploymentConfig), 'store', 'web/cookie/cook...')
#27 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(91): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#28 /var/www/app/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#29 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#30 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'sessionConfig', 'Magento\\Backend...')
#31 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Backend...', Array, Array)
#32 /var/www/app/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Backend...')
#33 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Backend...')
#34 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Backend...', NULL, 'session', 'Magento\\Backend...')
#35 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Backend...', Array, Array)
#36 /var/www/app/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Backend...')
#37 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#38 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'roleLocator', 'Magento\\Framewo...')
#39 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#40 /var/www/app/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#41 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#42 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'authorization', 'Magento\\Config\\...')
#43 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Config\\...', Array, Array)
#44 /var/www/app/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Config\\...', Array)
#45 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(238): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Config\\...')
#46 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Config\\...', NULL, 'element', 'Magento\\Config\\...')
#47 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Config\\...', Array, Array)
#48 /var/www/app/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Config\\...')
#49 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Config\\...')
#50 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Config\\...', NULL, 'childrenIterato...', 'Magento\\Config\\...')
#51 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Config\\...', Array, Array)
#52 /var/www/app/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Config\\...', Array)
#53 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(238): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Config\\...')
#54 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Config\\...', NULL, 'element', 'Magento\\Config\\...')
#55 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Config\\...', Array, Array)
#56 /var/www/app/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Config\\...')
#57 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Config\\...')
#58 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Config\\...', NULL, 'tabIterator', 'Magento\\Config\\...')
#59 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Config\\...', Array, Array)
#60 /var/www/app/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Config\\...')
#61 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Config\\...')
#62 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Config\\...', NULL, 'configStructure', 'Magento\\Config\\...')
#63 /var/www/app/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(84): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Config\\...', Array, Array)
#64 /var/www/app/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Config\\...', Array)
#65 /var/www/app/app/code/Magento/Config/Model/Config/Factory.php(35): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Config\\...', Array)
#66 /var/www/app/setup/src/Magento/Setup/Model/Installer.php(801): Magento\Config\Model\Config\Factory->create()
#67 [internal function]: Magento\Setup\Model\Installer->installUserConfig(Array)
#68 /var/www/app/setup/src/Magento/Setup/Model/Installer.php(288): call_user_func_array(Array, Array)
#69 /var/www/app/setup/src/Magento/Setup/Controller/Install.php(87): Magento\Setup\Model\Installer->install(Array)
#70 /var/www/app/vendor/zendframework/zend-mvc/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#71 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#72 /var/www/app/vendor/zendframework/zend-eventmanager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#73 /var/www/app/vendor/zendframework/zend-eventmanager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#74 /var/www/app/vendor/zendframework/zend-mvc/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#75 /var/www/app/vendor/zendframework/zend-mvc/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#76 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#77 /var/www/app/vendor/zendframework/zend-eventmanager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#78 /var/www/app/vendor/zendframework/zend-eventmanager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#79 /var/www/app/vendor/zendframework/zend-mvc/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#80 /var/www/app/setup/index.php(26): Zend\Mvc\Application->run()
#81 {main}
```

**Comment by stefanorg** [comment]
with a fresh clone of the repo and a new "composer install" everything works fine!
