### ISSUE TITLE
Product images won't load in developer mode

### ISSUE THREAD

**Issue by octoxan** [magento/magento2#13105]
### Preconditions
1. Magento version 2.2.1
2. PHP version 7.0

### Steps to reproduce
1. Create a custom theme, don't even overwrite any files yet
2. Switch to the theme and developer mode
3. Get errors on any page trying to get product images

### Expected result
1. It to load images and not crash

### Actual result
```
1 exception(s):
Exception #0 (Exception): Warning: getimagesize(): Filename cannot be empty in /var/www/example.test/public/vendor/magento/module-catalog/Model/Product/Image.php on line 890

Exception #0 (Exception): Warning: getimagesize(): Filename cannot be empty in /var/www/example.test/public/vendor/magento/module-catalog/Model/Product/Image.php on line 890
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'getimagesize():...', '/var/www/supert...', 890, Array)
#1 /var/www/example.test/public/vendor/magento/module-catalog/Model/Product/Image.php(890): getimagesize('')
#2 /var/www/example.test/public/vendor/magento/module-catalog/Helper/Image.php(552): Magento\Catalog\Model\Product\Image->getResizedImageInfo()
#3 /var/www/example.test/public/vendor/magento/module-catalog/Block/Product/ImageBuilder.php(132): Magento\Catalog\Helper\Image->getResizedImageInfo()
#4 /var/www/example.test/public/vendor/magento/module-catalog/Block/Product/AbstractProduct.php(516): Magento\Catalog\Block\Product\ImageBuilder->create()
#5 /var/www/example.test/public/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Block\Product\AbstractProduct->getImage(Object(Magento\Catalog\Model\Product\Interceptor), 'product_base_im...', Array)
#6 /var/www/example.test/public/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Block\Product\View\Interceptor->___callParent('getImage', Array)
#7 /var/www/example.test/public/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Block\Product\View\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor), 'product_base_im...')
#8 /var/www/example.test/public/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(455): Magento\Catalog\Block\Product\View\Interceptor->___callPlugins('getImage', Array, Array)
#9 /var/www/example.test/public/vendor/magento/module-catalog/view/frontend/templates/product/view/opengraph/general.phtml(14): Magento\Catalog\Block\Product\View\Interceptor->getImage(Object(Magento\Catalog\Model\Product\Interceptor), 'product_base_im...')
#10 /var/www/example.test/public/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/supert...')
#11 /var/www/example.test/public/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Interceptor), '/var/www/supert...', Array)
#12 /var/www/example.test/public/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(544): Magento\Framework\View\Element\Template->fetchView('/var/www/supert...')
#13 /var/www/example.test/public/vendor/magento/framework/View/Element/Template.php(300): Magento\Catalog\Block\Product\View\Interceptor->fetchView('/var/www/supert...')
#14 /var/www/example.test/public/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#15 /var/www/example.test/public/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(869): Magento\Framework\View\Element\AbstractBlock->toHtml()
#16 /var/www/example.test/public/vendor/magento/framework/View/Layout.php(558): Magento\Catalog\Block\Product\View\Interceptor->toHtml()
#17 /var/www/example.test/public/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('opengraph.gener...')
#18 /var/www/example.test/public/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('opengraph.gener...')
#19 /var/www/example.test/public/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('opengraph.gener...')
#20 /var/www/example.test/public/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('opengraph.gener...', true)
#21 /var/www/example.test/public/vendor/magento/framework/View/Element/AbstractBlock.php(511): Magento\Framework\View\Layout\Interceptor->renderElement('opengraph.gener...', true)
#22 /var/www/example.test/public/vendor/magento/module-theme/view/frontend/templates/html/container.phtml(10): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#23 /var/www/example.test/public/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/supert...')
#24 /var/www/example.test/public/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Framework\View\Element\Template), '/var/www/supert...', Array)
#25 /var/www/example.test/public/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/supert...')
#26 /var/www/example.test/public/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#27 /var/www/example.test/public/vendor/magento/framework/View/Result/Page.php(250): Magento\Framework\View\Element\AbstractBlock->toHtml()
#28 /var/www/example.test/public/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#29 /var/www/example.test/public/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#30 /var/www/example.test/public/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#31 /var/www/example.test/public/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#32 /var/www/example.test/public/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#33 /var/www/example.test/public/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#34 /var/www/example.test/public/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#35 /var/www/example.test/public/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#36 {main}
```

**Comment by jagritijoshi** [comment]
Hello 
   Its working in my local environment.Please flush the cache and reload this page.

**Comment by magento-engcom-team** [comment]
@octoxan , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by magento-engcom-team** [comment]
@octoxan, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
