### ISSUE TITLE
[Magento 2.1.11] After set minimum price get error during clear basket

### ISSUE THREAD

**Issue by Sylvesterx1** [magento/magento2#13118]
# Preconditions
1.  Magento 2.1.11 
2.  VPS Linux Debian 9
3. Basket cleaning error (after set minimum price order). 

### Address site to check error:
- http://brandswearxv.nazwa.pl/

### Description of the problem: 
- When I set the minimum order price, for example 200 euro.  and I will add products to the basket, then try to clean the basket or remove a single product receives an error.
when I turn off the minimum order price -  problem disappears.  

### What did I do to solve the problem?
- I thought the problem was with my template, I changed the template to standard (Luma). The problem is still the same, so the problem is with the magento application.

# Expected result
- solving the problem with cleaning the basket

Error code:
` Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Framework\Exception\InputException::__construct() must be an instance of Magento\Framework\Phrase, string given, called in /home/brandswearxv/ftp/vendor/magento/module-quote/Model/ShippingAddressManagement.php on line 121 and defined in /home/brandswearxv/ftp/vendor/magento/framework/Exception/InputException.php:51 Stack trace: #0 /home/brandswearxv/ftp/vendor/magento/module-quote/Model/ShippingAddressManagement.php(121): Magento\Framework\Exception\InputException->__construct('Minimalne zam\xC3\xB3...') #1 /home/brandswearxv/ftp/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingProcessor.php(66): Magento\Quote\Model\ShippingAddressManagement->assign('66', Object(Magento\Quote\Model\Quote\Address)) #2 /home/brandswearxv/ftp/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingAssignmentProcessor.php(110): Magento\Quote\Model\Quote\ShippingAssignment\ShippingProcessor->save(Object(Magento\Quote\Model\Shipping), Object(Magento\Quote in /home/brandswearxv/ftp/vendor/magento/framework/Exception/InputException.php on line 51 enter image description here magento-2.1 shareeditdeleteflag asked Dec 27 '17 at 16:01 Sylvester 719 add a comment `

File ShippingAddressManagement.php:
`    $address->setSameAsBilling($sameAsBilling);
    $address->setSaveInAddressBook($saveInAddressBook);
    $address->setCollectShippingRates(true);
    if (!$quote->validateMinimumAmount($quote->getIsMultiShipping())) {
        throw new InputException($this->getMinimumAmountErrorMessage()->getMessage());
    }
    try {
        $address->save();
    } catch (\Exception $e) {
        $this->logger->critical($e);
        throw new InputException(__('Unable to save address. Please check input data.'));
    }
    return $quote->getShippingAddress()->getId();
}`

Line 121 in file ShippingAddressManagement.php:

`throw new InputException($this->getMinimumAmountErrorMessage()->getMessage());`

**Comment by magento-engcom-team** [comment]
@Sylvesterx1 Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by Sylvesterx1** [comment]
@magento-engcom-team Ticket update.

**Comment by magento-engcom-team** [comment]
@Sylvesterx1 Thanks for your report. We weren't able to reproduce it with a clean instance of Magento. Could you please clarify what kind of product are you adding? Also please try to reproduce it with a clean instance of Magento and let us know if you still can reproduce the issue, thank you.

**Comment by Sylvesterx1** [comment]
@magento-engcom-team, adds any product to the basket and then I can not clean it. I did not make any modifications to the files. Do you know how to solve this problem? Thanks for your help.

**Comment by magento-engcom-team** [comment]
@Sylvesterx1 We made a [video](https://streamable.com/g3ltt) where we are trying to follow your description. Please watch and let us know if we missed something. Thank you
 https://streamable.com/g3ltt

**Comment by magento-engcom-team** [comment]
@Sylvesterx1, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
