### ISSUE TITLE
Cannot edit product after migration 1.9 -> 2.2.2

### ISSUE THREAD

**Issue by ValoKoski** [magento/magento2#13188]
### Preconditions
CentOS 7
Magento 2.2.2 (Origin 1.9.x)
MariaDB, PHP7

### Steps to reproduce
migrate from 1.9. to 2.2.2

### Actual result
Everything went ok. Customers, Products, Store settings are ok. When You try to edit migrated product then error occured and i didn't find any help for this:

{"0":"The configuration parameter \"formElement\" is a required for \"NULL\" field.","1":"#0 \/var\/www\/html\/vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php(159): Magento\\Ui\\Component\\Form\\Field->prepare()\n#1 \/var\/www\/html\/vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php(156): Magento\\Framework\\View\\Layout\\Generator\\UiComponent->prepareComponent(Object(Magento\\Ui\\Component\\Form\\Field))\n#2 \/var\/www\/html\/vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php(156): Magento\\Framework\\View\\Layout\\Generator\\UiComponent->prepareComponent(Object(Magento\\Ui\\Component\\Container))\n#3 \/var\/www\/html\/vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php(156): Magento\\Framework\\View\\Layout\\Generator\\UiComponent->prepareComponent(Object(Magento\\Ui\\Component\\Form\\Fieldset))\n#4 \/var\/www\/html\/vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php(156): Magento\\Framework\\View\\Layout\\Generator\\UiComponent->prepareComponent(Object(Magento\\Ui\\Component\\Container))\n#5 \/var\/www\/html\/vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php(137): Magento\\Framework\\View\\Layout\\Generator\\UiComponent->prepareComponent(Object(Magento\\Ui\\Component\\Form))\n#6 \/var\/www\/html\/vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php(97): Magento\\Framework\\View\\Layout\\Generator\\UiComponent->generateComponent(Object(Magento\\Framework\\View\\Layout\\Data\\Structure), 'product_form', Array, Object(Magento\\Framework\\View\\Layout\\Interceptor))\n#7 \/var\/www\/html\/vendor\/magento\/framework\/View\/Layout\/GeneratorPool.php(80): Magento\\Framework\\View\\Layout\\Generator\\UiComponent->process(Object(Magento\\Framework\\View\\Layout\\Reader\\Context), Object(Magento\\Framework\\View\\Layout\\Generator\\Context))\n#8 \/var\/www\/html\/vendor\/magento\/framework\/View\/Layout.php(344): Magento\\Framework\\View\\Layout\\GeneratorPool->process(Object(Magento\\Framework\\View\\Layout\\Reader\\Context), Object(Magento\\Framework\\View\\Layout\\Generator\\Context))\n#9 \/var\/www\/html\/vendor\/magento\/framework\/View\/Layout\/Builder.php(129): Magento\\Framework\\View\\Layout->generateElements()\n#10 \/var\/www\/html\/vendor\/magento\/framework\/View\/Page\/Builder.php(55): Magento\\Framework\\View\\Layout\\Builder->generateLayoutBlocks()\n#11 \/var\/www\/html\/vendor\/magento\/framework\/View\/Layout\/Builder.php(65): Magento\\Framework\\View\\Page\\Builder->generateLayoutBlocks()\n#12 \/var\/www\/html\/vendor\/magento\/framework\/View\/Layout.php(254): Magento\\Framework\\View\\Layout\\Builder->build()\n#13 \/var\/www\/html\/vendor\/magento\/framework\/View\/Layout.php(875): Magento\\Framework\\View\\Layout->build()\n#14 \/var\/www\/html\/vendor\/magento\/module-backend\/Model\/View\/Result\/Page.php(26): Magento\\Framework\\View\\Layout->getBlock('menu')\n#15 \/var\/www\/html\/vendor\/magento\/module-catalog\/Controller\/Adminhtml\/Product\/Edit.php(69): Magento\\Backend\\Model\\View\\Result\\Page->setActiveMenu('Magento_Catalog...')\n#16 \/var\/www\/html\/vendor\/magento\/framework\/App\/Action\/Action.php(107): Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit->execute()\n#17 \/var\/www\/html\/vendor\/magento\/module-backend\/App\/AbstractAction.php(229): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#18 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Backend\\App\\AbstractAction->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#19 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->___callParent('dispatch', Array)\n#20 \/var\/www\/html\/vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php(143): Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#21 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch(Object(Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#22 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#23 \/var\/www\/html\/generated\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Product\/Edit\/Interceptor.php(26): Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#24 \/var\/www\/html\/vendor\/magento\/framework\/App\/FrontController.php(55): Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#25 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#26 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#27 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#28 \/var\/www\/html\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#29 \/var\/www\/html\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#30 \/var\/www\/html\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#31 \/var\/www\/html\/index.php(44): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#32 {main}","url":"\/adminXXXXXXXXXX\/catalog\/product\/edit\/id\/1799\/key\/da682c054164a977bce0ea422a9229ab0bd13f20214da3b8f32cf0202a086808\/","script_name":"\/index.php"}

**Comment by ValoKoski** [comment]
found it.. remove from "eav_attribute_set" table everything with "Migration_Default" and case closed.
