### ISSUE TITLE
Magento 2 REST Web API calls leak the full database query

### ISSUE THREAD

**Issue by KSaho** [magento/magento2#13232]
I've just had an interesting issue with the Magento 2 Web API.

**Preconditions:**
PHP 7.0.22-0ubuntu0.16.04.1
Magento CE 2.2.2
redis-cli 4.0.2
mysql 5.7.20

**Steps to reproduce:**
Default install
Set Mage environment to production
Use page cache (Redis) - Not sure if this has anything to do with it.
Call the Web API (REST API: catalogProductRepositoryV1 GET products/) from a local machine to the server and saturate the number of connections with 160 pages + 10 items per page (1600 items total). Each page is a connection. I used my own Python (3.5) scripts with grequests.

**Expected result:**
If the issue is that the query is too large, the connection should break from MySQL's end and Magento should return a JSON message with the issue, otherwise return the JSON items.

**Actual result:**
MySQL will crash, and in one instance it leaked the query. This could be an attack vector for leaking information from the server.

**Additional information:**
I have been trying all morning to reproduce the SQL leak, but I could not. I do not know what specific circumstances caused the SQL leak.

EDIT: Just reproduced the query leak, same steps as above, just focus on saturating the connections, however, MySQL, I reconfigured so it can handle the connections and it no longer crashes, however the leak still occurs.

Full output:
`
b'SELECT `t_d`.`attribute_id`, `e`.`entity_id`, `t_d`.`value` AS `default_value`, `t_s`.`value` AS `store_value`, IF(t_s.value_id IS NULL, t_d.value, t_s.value) AS `value` FROM `catalog_product_entity_varchar` AS `t_d`\n INNER JOIN `catalog_product_entity` AS `e` ON e.entity_id = t_d.entity_id\n LEFT JOIN `catalog_product_entity_varchar` AS `t_s` ON t_s.attribute_id = t_d.attribute_id AND t_s.entity_id = t_d.entity_id AND t_s.store_id = 1 WHERE (e.entity_id IN (128, 129, 130, 131, 132, 133, 135, 136, 137, 138)) AND (t_d.attribute_id IN (\'144\', \'162\', \'135\', \'165\', \'114\', \'100\', \'116\', \'183\', \'141\', \'140\', \'164\', \'145\', \'147\', \'163\', \'155\', \'96\', \'156\', \'134\', \'137\', \'168\', \'87\', \'109\', \'166\', \'159\', \'148\', \'150\', \'125\', \'172\', \'86\', \'84\', \'136\', \'138\', \'118\', \'73\', \'160\', \'106\', \'104\', \'151\', \'154\', \'124\', \'153\', \'88\', \'110\', \'152\', \'161\', \'133\', \'89\', \'111\', \'158\', \'157\', \'139\', \'121\', \'122\', \'167\')) AND (t_d.store_id = IFNULL(t_s.store_id, 0)){"message":"Internal Error. Details are available in Magento log file. Report ID: webapi-5a5ea7373dc5c"}'
`

**Comment by piotrekkaminski** [comment]
We are not able to reproduce this - with 2000 parallel requests and after a while the mysql server did stop responding but didn't crash and as soon as the server worked through the requests everything went back to normal. Is there any specific configuration that you used?

**Comment by KrunoSaho** [comment]
I can give you my env and config files in private, but it will be in 3 days as I am off today (due to 43*C heat), and the next two days are the weekend.

Aside from simply enabling the WebAPI I didn't do anything to the configuration in that regard. Keep in mind it is hard and takes a number of attempts for the SQL to leak. It doesn't always happen. This could be some weird combination of configuration somewhere in the system, but the main issue is Magento 2 isn't sanitising what it returns to the user as it looks like the exception message is mingled with the return result.

I will try to isolate the code that returns the values on Monday to see if I can fix this.

**Comment by KSaho** [comment]
I have been working on this issue whenever I have spare time during work hours, and here is what I found.
I set max_allowed_packet=1G (Maximum you can set according to https://dev.mysql.com/doc/refman/5.7/en/packet-too-large.html) and the new error message it now normally returns, (it still leaks the query from time to time), is below:

`
b'<!doctype html>\n<html xmlns="http://www.w3.org/1999/xhtml" >\n<head>\n    <title>There has been an error processing your request</title>\n    <base href="URL_REMOVED" />\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n    <meta name="robots" content="*"/>\n    <link rel="stylesheet" href="css/styles.css" type="text/css" />\n    <link rel="icon" href="images/favicon.ico" type="image/x-icon" />\n    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />\n</head>\n<body>\n    <main class="page-main">\n        \n<h1>There has been an error processing your request</h1>\n    <p><em>Exception printing is disabled by default for security reasons.</em></p>\n\n    <p>Error log record number: NUMBER_REMOVED</p>\n    </main>\n</body>\n</html>\n'
`

This looks like the appropriate response. The issue which causes the error is:
`
{"0":"Warning: Error while sending QUERY packet. PID=4701 in REMOVED_PATH\/vendor\/magento\/zendframework1\/library\/Zend\/Db\/Statement\/Pdo.php on line 228","1":"#0 [internal function]: Magento\\Framework\\App\\ErrorHandler->handler(2, 'Error while sen...', 'REMOVED_PATH\/v...', 228, Array)\n#1 REMOVED_PATH\/vendor\/magento\/zendframework1\/library\/Zend\/Db\/Statement\/Pdo.php(228): PDOStatement->execute(Array)\n#2 REMOVED_PATH\/vendor\/magento\/framework\/DB\/Statement\/Pdo\/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)\n#3 REMOVED_PATH\/vendor\/magento\/zendframework1\/library\/Zend\/Db\/Statement.php(303): Magento\\Framework\\DB\\Statement\\Pdo\\Mysql->_execute(Array)\n#4 REMOVED_PATH\/vendor\/magento\/zendframework1\/library\/Zend\/Db\/Adapter\/Abstract.php(480): Zend_Db_Statement->execute(Array)\n#5 REMOVED_PATH\/vendor\/magento\/zendframework1\/library\/Zend\/Db\/Adapter\/Pdo\/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `flag`.*...', Array)\n#6 REMOVED_PATH\/vendor\/magento\/framework\/DB\/Adapter\/Pdo\/Mysql.php(517): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `flag`.*...', Array)\n#7 REMOVED_PATH\/vendor\/magento\/framework\/DB\/Adapter\/Pdo\/Mysql.php(580): Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->_query('SELECT `flag`.*...', Array)\n#8 REMOVED_PATH\/vendor\/magento\/zendframework1\/library\/Zend\/Db\/Adapter\/Abstract.php(756): Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->query(Object(Magento\\Framework\\DB\\Select), Array)\n#9 REMOVED_PATH\/vendor\/magento\/framework\/Model\/ResourceModel\/Db\/AbstractDb.php(348): Zend_Db_Adapter_Abstract->fetchRow(Object(Magento\\Framework\\DB\\Select))\n#10 REMOVED_PATH\/vendor\/magento\/module-deploy\/Model\/DeploymentConfig\/Hash.php(128): Magento\\Framework\\Model\\ResourceModel\\Db\\AbstractDb->load(Object(Magento\\Framework\\Flag), 'config_hash', 'flag_code')\n#11 REMOVED_PATH\/vendor\/magento\/module-deploy\/Model\/DeploymentConfig\/Hash.php(112): Magento\\Deploy\\Model\\DeploymentConfig\\Hash->getFlagObject()\n#12 REMOVED_PATH\/vendor\/magento\/module-deploy\/Model\/DeploymentConfig\/ChangeDetector.php(68): Magento\\Deploy\\Model\\DeploymentConfig\\Hash->get()\n#13 REMOVED_PATH\/vendor\/magento\/module-deploy\/Model\/Plugin\/ConfigChangeDetector.php(48): Magento\\Deploy\\Model\\DeploymentConfig\\ChangeDetector->hasChanges()\n#14 REMOVED_PATH\/vendor\/magento\/framework\/Interception\/Interceptor.php(121): Magento\\Deploy\\Model\\Plugin\\ConfigChangeDetector->beforeDispatch(Object(Magento\\Webapi\\Controller\\Rest\\Interceptor), Object(Magento\\Framework\\App\\Request\\Http))\n#15 REMOVED_PATH\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#16 REMOVED_PATH\/generated\/code\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(26): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#17 REMOVED_PATH\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#18 REMOVED_PATH\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#19 REMOVED_PATH\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#20 REMOVED_PATH\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#21 {main}","url":"\/index.php\/rest\/V1\/products\/?searchCriteria[pageSize]=10&searchCriteria[currentPage]=24","script_name":"\/index.php"}
`

I've tested trying to leak the query on my local machine and can't seem to do it. It looks like the issue could be related to the size of the query.


EDIT:
I wanted to add that this issue seems related to:
https://github.com/magento/magento2/issues/9630

Which is why I initially posted my response there, however I felt that this is pretty urgent and is more severe, and so I moved it into its own topic.

**Comment by KSaho** [comment]
Something odd has happened.
I upgraded to Python 3.6, installed grequests and I no longer have this issue.

With Python 3.5 and grequests anytime the items per page < 18, it will sometimes fail and leak the SQL query, however this issue does not exist with Python 3.6 and grequests.

The issue summary is now:
A certain version combination of Python and grequests causes Magento 2.2.2 to leak a SQL query. This can not be replicated, to the best of my ability, under PHP with curl or multicurl, regardless of the number of connections.

Python:
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux

GRequests:
Name: grequests
Version: 0.3.0
Summary: Requests + Gevent
Home-page: https://github.com/kennethreitz/grequests
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: BSD
Location: /usr/local/lib/python3.5/dist-packages
Requires: gevent, requests

GEvent:
Name: gevent
Version: 1.2.2
Summary: Coroutine-based network library
Home-page: http://www.gevent.org/
Author: Jason Madden
Author-email: jason@nextthought.com
License: MIT
Location: /usr/local/lib/python3.5/dist-packages
Requires: greenlet

Greenlet:
Name: greenlet
Version: 0.4.12
Summary: Lightweight in-process concurrent programming
Home-page: https://github.com/python-greenlet/greenlet
Author: Alexey Borzenkov
Author-email: snaury@gmail.com
License: MIT License
Location: /usr/local/lib/python3.5/dist-packages
Requires: 

EDIT: Added more info, and clarified a statement.

**Comment by ghost** [comment]
Hi @KSaho We were not able to reproduce this issue by following the steps you provided.
If with version of python 3.6 this issue no longer exist, maybe the problem not in magento side ?

**Comment by KrunoSaho** [comment]
I have had this issue with Python 3.7 as well and with Magento 2.2.5. I really do not know what is causing this, however it is much rarer now. I do not know how the server's MySQL query leaks out to an external connection. I have looked at the Magento code where the REST call is returned, and it doesn't seem to be an issue within the Magento 2 code as far as I can see. MySQL fails the query, but then where in the stack is the exception (with the query details) returned? This only happens with the Magento 2 REST calls, and more specifically the V1/product calls.

**Comment by ghost** [comment]
@KrunoSaho  yes seems like it's a bug,  response must include only execption or details in log file, but not query details.

**Comment by KrunoSaho** [comment]
It is bother returned, and in the log file (the exception and query details). I should mention that the full output in my original post also was also recorded in var/log/exception.log IIRC.

**Comment by ghost** [comment]
@KrunoSaho still not able to reproduce this, can you please, if you have time, to provide a short video about this ?

**Comment by KrunoSaho** [comment]
I will try to capture this issue on video when I am at work.

**Comment by magento-engcom-team** [comment]
@KSaho we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by KSaho** [comment]
I just want to update everyone on this issue.

I have been able to reproduce this, and it is an Apache issue from my experience.

Apache runs out of memory on certain Magento REST API calls, and this is what causes the query to leak as Apache simply returns whatever IO was related to that call, which would be the MySQL query, which was requested by Magento given the REST call. Keep in mind I had modified Apache's settings repeatedly regarding memory, and even on 8GB of RAM it is not necessarily enough for Apache to not run out of memory. I tried a variety of settings over time and it would be a coin toss as to which REST call would cause issues at what time. The issue with this is that it was inconsistent.

The system would not always run out of memory either at first glance, which is why I found reproducing this bug difficult, and the system did not always log when it ran out of memory, normally I would get a memory spike if the server ran out of memory, shown on my monitoring tool, but this did not happen, and to top things off the server recovered from the out of memory problem instantly which didn't rouse my suspicion because things would work as though nothing happened.

I have since moved onto using Nginx and all problems ceased, downgraded memory for server usage, and I can open up 50,000 connections simultaneously without issue or any noticeable spike in memory.

Guys, you can keep this issue closed as I just wanted to update everyone in case they were concerned.
