### ISSUE TITLE
After upgrade - Setup version for module 'Magento_Centinel' is not specified

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#1328]
```
Setup version for module 'Magento_Centinel' is not specified
#0 /var/www/vhosts/magento2-capistrano/releases/20150601113108/lib/internal/Magento/Framework/Module/DbVersionInfo.php(56): Magento\Framework\Module\DbVersionInfo->isModuleVersionEqual('Magento_Centine...', '2.0.0')
#1 /var/www/vhosts/magento2-capistrano/releases/20150601113108/lib/internal/Magento/Framework/Module/DbVersionInfo.php(79): Magento\Framework\Module\DbVersionInfo->isSchemaUpToDate('Magento_Centine...')
#2 /var/www/vhosts/magento2-capistrano/releases/20150601113108/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(55): Magento\Framework\Module\DbVersionInfo->getDbVersionErrors()
#3 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#4 /var/www/vhosts/magento2-capistrano/releases/20150601113108/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): call_user_func_array(Array, Array)
#5 /var/www/vhosts/magento2-capistrano/releases/20150601113108/lib/internal/Magento/Framework/Interception/Chain/Chain.php(58): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#6 /var/www/vhosts/magento2-capistrano/releases/20150601113108/app/code/Magento/PageCache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#7 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#8 /var/www/vhosts/magento2-capistrano/releases/20150601113108/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): call_user_func_array(Array, Array)
#9 /var/www/vhosts/magento2-capistrano/shared/var/generation/Magento/Framework/App/FrontController/Interceptor.php(95): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#10 /var/www/vhosts/magento2-capistrano/releases/20150601113108/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\App\FrontController\{closure}(Object(Magento\Framework\App\Request\Http))
#11 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /var/www/vhosts/magento2-capistrano/shared/var/generation/Magento/Framework/App/FrontController/Interceptor.php(100): call_user_func_array(Array, Array)
#13 /var/www/vhosts/magento2-capistrano/shared/var/generation/Magento/Framework/App/FrontController/Interceptor.php(124): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#14 /var/www/vhosts/magento2-capistrano/releases/20150601113108/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /var/www/vhosts/magento2-capistrano/releases/20150601113108/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#16 /var/www/vhosts/magento2-capistrano/releases/20150601113108/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#17 {main}
```

**Comment by mazhalai** [comment]
@craigcarnell can you please try again after clearing your `var` folder?

**Comment by craigcarnell** [comment]
@mazhalai Already tried that, just did it again and same result

**Comment by mazhalai** [comment]
@craigcarnell just confirming the steps you followed, you upgraded to `0.74.0-beta11` ran `composer install` and then got the error while running `bin/magento setup:upgrade`?

**Comment by buskamuza** [comment]
@craigcarnell , module `Magento_Centinel` has been removed in version `0.74.0-beta11`. I believe, the module's folder is absent, so the application can't read setup_version from it.
It's probably an issue with the upgrade command - it should refresh list of modules in `app/etc/config.php` before starting DB upgrade.
For now, I'd suggest you one of the following options:
1. remove `Magento_Centinel` from `app/etc/config.php` manually and try upgrade again. It may lead to incorrect sequence of the remaining modules. But in general you should be OK.
2. if you usually enable all modules, run `./bin/magento module:enable --all`. It should re-generate list of modules.
Meanwhile I'll create an internal issue to investigate this problem. Thanks for reporting it.

**Comment by craigcarnell** [comment]
@mazhalai @buskamuza It works, I didn't run bin/magento setup:upgrade

Perhaps it's worth adding a message to tell the user to run this when you upgrade, instead of getting an error message?

**Comment by mazhalai** [comment]
@craigcarnell thank you for your report. Can you provide exact steps to reproduce this error?

**Comment by Valentyn-Kubrak** [comment]
I have the same error in beta 1.0.0. I created module from tutorials https://github.com/magento/magento2-samples/tree/master/sample-module-newpage
with own namespace. My module.xml
```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Module/etc/module.xsd">
    <module name="Tutorials_Page" schema_version="1.0.0" setup_version="1.0.0"/>
</config>


```

Error

```
a:4:{i:0;s:58:"Setup version for module 'Tutorials_Page' is not specified";i:1;s:1452:"#0 /var/www/magento2stage2/lib/internal/Magento/Framework/Module/DbVersionInfo.php(56): Magento\Framework\Module\DbVersionInfo->isModuleVersionEqual('Tutorials_Page', false)
#1 /var/www/magento2stage2/lib/internal/Magento/Framework/Module/DbVersionInfo.php(79): Magento\Framework\Module\DbVersionInfo->isSchemaUpToDate('Tutorials_Page')
#2 /var/www/magento2stage2/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(55): Magento\Framework\Module\DbVersionInfo->getDbVersionErrors()
#3 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#4 /var/www/magento2stage2/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#5 /var/www/magento2stage2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#6 /var/www/magento2stage2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /var/www/magento2stage2/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#8 /var/www/magento2stage2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#9 {main}";s:3:"url";s:7:"/admin/";s:11:"script_name";s:10:"/index.php";}
```
