### ISSUE TITLE
Some bundle products can not be ordered while logged in

### ISSUE THREAD

**Issue by kmrant** [magento/magento2#13388]
### Preconditions

1. Magento 2.2.2, PHP 7.0.22, Mysql 5.0.12

### Steps to reproduce

1. Add bundle product to shopping cart.
2. Make order.
3. Choose any shipping method or any payment method.
4. Place order

### Expected result

1. Order should be placed.

### Actual result

1. Error: No such entity with orderId: XXXXX, XXXXX being a number that is different for each product.

2. Screenshots
![duo2_low_res](https://user-images.githubusercontent.com/30792086/35441579-b72ee1a4-02ac-11e8-9122-f33aed910e6b.png)
![piccollo_low_res](https://user-images.githubusercontent.com/30792086/35441595-c9d2ed14-02ac-11e8-91f2-20a84ec8704e.png)
![vu solo-se-v2_low_res](https://user-images.githubusercontent.com/30792086/35441601-cc77537a-02ac-11e8-9876-30727c8a39cc.png)
![b315 p-58-mimo_low_res](https://user-images.githubusercontent.com/30792086/35441606-cea6ecbe-02ac-11e8-8df5-2e28a5526251.png)

3. Stack trace:

#0 /var/www/kehitys2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(24220, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))↵
#1 /var/www/kehitys2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)↵
#2 /var/www/kehitys2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}(24220, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))↵
#3 /var/www/kehitys2/generated/code/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(26): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)↵
#4 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(24220, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))↵
#5 /var/www/kehitys2/vendor/magento/module-webapi/Controller/Rest.php(330): call_user_func_array(Array, Array)↵
#6 /var/www/kehitys2/vendor/magento/module-webapi/Controller/Rest.php(239): Magento\Webapi\Controller\Rest->processApiRequest()↵
#7 /var/www/kehitys2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))↵
#8 /var/www/kehitys2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)↵
#9 /var/www/kehitys2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))↵
#10 /var/www/kehitys2/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)↵
#11 /var/www/kehitys2/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))↵
#12 /var/www/kehitys2/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()↵
#13 /var/www/kehitys2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))↵
#14 {main}"

**Comment by kmrant** [comment]
Hi,

Could you check the issue? Do you need any extra information? Thanks.

**Comment by magento-engcom-team** [comment]
@kmrant thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

![checkout](https://user-images.githubusercontent.com/31669971/36020275-06bd050c-0d7a-11e8-9399-b112f6ebb94f.png)

**Comment by magento-engcom-team** [comment]
@kmrant, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
