### ISSUE TITLE
Error in Installing Magento 2.1.11 on production(CentOS,Apache)

### ISSUE THREAD

**Issue by manishg345** [magento/magento2#13422]
I am facing the following errors while installing magento 2.1.11 on production:

Notice: Undefined property: DOMDocument::$documentElement in /var/www/html/lexingtoncontainer/vendor/magento/framework/ObjectManager/Config/Mapper/Dom.php on line 58

Notice: Trying to get property of non-object in /var/www/html/lexingtoncontainer/vendor/magento/framework/ObjectManager/Config/Mapper/Dom.php on line 58

Warning: Invalid argument supplied for foreach() in /var/www/html/lexingtoncontainer/vendor/magento/framework/ObjectManager/Config/Mapper/Dom.php on line 58

Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Config\CacheInterface in /var/www/html/lexingtoncontainer/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:73 Stack trace: #0 /var/www/html/lexingtoncontainer/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') #1 /var/www/html/lexingtoncontainer/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...') #2 /var/www/html/lexingtoncontainer/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'cache', 'Magento\\Framewo...') #3 /var/www/html/lexingtoncontainer/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\ in /var/www/html/lexingtoncontainer/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 73.

![magento_error](https://user-images.githubusercontent.com/12373187/35551282-6601aba8-05b4-11e8-8962-bdb467b2baca.png)

**Comment by RahulBhut21** [comment]
try to reinstall Magento. because it not set DOM object values.

**Comment by magento-engcom-team** [comment]
@manishg345, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by ghost** [comment]
make sure the `extension=dom.so` is enabled  in the **php.ini** file
