### ISSUE TITLE
Deploy error :"/pub/static/frontend/<My>/<Theme>/en_US/css/email.css): failed to open stream: No such fi     le or directory           "

### ISSUE THREAD

**Issue by daotoan-hd** [magento/magento2#13533]
### I create a new theme and deploy. i get this error
```
[Magento\Framework\Exception\FileSystemException]                            
  Cannot read contents from file "/home/someone/magento-2.2.2-3/apps/magento/  
  htdocs/pub/static/frontend/Doctor/earth/en_US/css/email.css" Warning!file_g  
  et_contents(/home/someone/magento-2.2.2-3/apps/magento/htdocs/pub/static/fr  
  ontend/Doctor/earth/en_US/css/email.css): failed to open stream: No such fi  
  le or directory
```

```
#0 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/magento/framework/App/View/Asset/Publisher.php(73): Magento\Framework\View\Asset\File->getSourceFile()
#1 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/magento/framework/App/View/Asset/Publisher.php(61): Magento\Framework\App\View\Asset\Publisher->publishAsset(Object(Magento\Framework\View\Asset\File))
#2 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/magento/module-deploy/Service/DeployStaticFile.php(89): Magento\Framework\App\View\Asset\Publisher->publish(Object(Magento\Framework\View\Asset\File))
#3 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/magento/module-deploy/Service/DeployPackage.php(189): Magento\Deploy\Service\DeployStaticFile->deployFile('css/email.less', Array)
#4 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/magento/module-deploy/Service/DeployPackage.php(136): Magento\Deploy\Service\DeployPackage->processFile(Object(Magento\Deploy\Package\PackageFile), Object(Magento\Deploy\Package\Package))
#5 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/magento/module-deploy/Service/DeployPackage.php(107): Magento\Deploy\Service\DeployPackage->deployEmulated(Object(Magento\Deploy\Package\Package), Array, false)
#6 [internal function]: Magento\Deploy\Service\DeployPackage->Magento\Deploy\Service\{closure}()
#7 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/magento/framework/App/State.php(186): call_user_func_array(Object(Closure), Array)
#8 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/magento/module-deploy/Service/DeployPackage.php(108): Magento\Framework\App\State->emulateAreaCode('frontend', Object(Closure))
#9 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/magento/module-deploy/Process/Queue.php(281): Magento\Deploy\Service\DeployPackage->deploy(Object(Magento\Deploy\Package\Package), Array)
#10 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/magento/module-deploy/Process/Queue.php(200): Magento\Deploy\Process\Queue->execute(Object(Magento\Deploy\Package\Package))
#11 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/magento/module-deploy/Process/Queue.php(162): Magento\Deploy\Process\Queue->assertAndExecute('frontend/Doctor...', Array, Array)
#12 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/magento/module-deploy/Strategy/QuickDeploy.php(76): Magento\Deploy\Process\Queue->process()
#13 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/magento/module-deploy/Service/DeployStaticContent.php(109): Magento\Deploy\Strategy\QuickDeploy->deploy(Array)
#14 /home/someone/magento-2.2.2-3/apps/magento/htdocs/setup/src/Magento/Setup/Console/Command/DeployStaticContentCommand.php(140): Magento\Deploy\Service\DeployStaticContent->deploy(Array)
#15 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/symfony/console/Command/Command.php(242): Magento\Setup\Console\Command\DeployStaticContentCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/symfony/console/Application.php(842): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DeployStaticContentCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/magento/framework/Console/Cli.php(104): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/someone/magento-2.2.2-3/apps/magento/htdocs/vendor/symfony/console/Application.php(117): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/someone/magento-2.2.2-3/apps/magento/htdocs/bin/magento(23): Symfony\Component\Console\Application->run()
#21 {main}

```
I don't create file email.css in my theme. i don't know why i get this error.
PLEASE HELP ME ! I CAN'T FIX IT

**Comment by orlangur** [comment]
> /pub/static/frontend/Doctor/earth/en_US/css/email.css

There seems to be a problem with third-party extension or theme. 

GitHub is intended for bug reports in Magento core modules, please use [Magento Stack Exchange](https://magento.stackexchange.com) for troubleshooting in third-party extensions.

**Comment by magento-engcom-team** [comment]
@alovn2000, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only. 
Also try some useful resources from [Frontend Developer Guide](http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/bk-frontend-dev-guide.html)

**Comment by magento-engcom-team** [comment]
@alovn2000, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
