### ISSUE TITLE
Upgrade to 2.1.10 from 2.1.7 Online Payment Capture is not working

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#13583]
### Preconditions

1. Magento 2.1.10, PHP 7, MySQL 5.6.*
2. Nginx

### Steps to reproduce

1. Earlier I have Magento 2.1.7 version and then upgraded to 2.1.10
2. For the Payment method, I have **Authorize.net CIM** extension 
3. On Making payment on frontend, everything is fine.
4. When I go to admin for process the order and Click on Invoice and then select "Capture Online" and click on Submit Invoice then I got an error. 

### Expected result

1. Invoice for  Capture Online is processed without any error.

### Actual result

1. I got an error from the server is 

> PHP Fatal error: Uncaught Error: Call to a member function getOrderStatusByState() on null in /home/xyz/public_html/vendor/magento/module-sales/Model/Order/Payment/State/CaptureCommand.php:54
Stack trace:
#0 /home/xyz/public_html/vendor/magento/module-sales/Model/Order/Payment/Operations/CaptureOperation.php(101): Magento\Sales\Model\Order\Payment\State\CaptureCommand->execute(Object(Magento\Sales\Model\Order\Payment\Interceptor), '7.66', Object(Magento\Sales\Model\Order\Interceptor))
#1 /home/xyz/public_html/vendor/magento/module-sales/Model/Order/Payment/Processor.php(85): Magento\Sales\Model\Order\Payment\Operations\CaptureOperation->capture(Object(Magento\Sales\Model\Order\Payment\Interceptor), Object(Magento\Sales\Model\Order\Invoice))
#2 /home/xyz/public_html/vendor/magento/module-sales/Model/Order/Payment.php(447): Magento\Sales\Model\Order\Payment\Processor->capture(Object(Magento\Sales\Model\Order\Payment\Interceptor), Object(Magento\Sales\Model\Order\Invoice))
#3 / in /home/xyz/public_html/vendor/magento/module-sales/Model/Order/Payment/State/CaptureCommand.php on line 54

**Comment by magento-engcom-team** [comment]
@RishabhRkRai , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release and  without any extensions.

**Comment by magento-engcom-team** [comment]
@RishabhRkRai, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by davidbrandastic** [comment]
@magento-engcom-team I encountered this issue today as well while debugging an issue with Paradox Labs CIM + OneStepCheckout; however, it was not able to be consistently reproduced in the environment in which I was working.  Magento 2.1.12

@RishabhRkRai which CIM extension/version are you using?  And is this with the default Magento checkout?

**Comment by scottsb** [comment]
I also just saw this error, and it came from a Paradox Labs module (the core TokenBase, not CIM itself). Seems to be a third-party bug, not a core Magento bug.

**Comment by scottsb** [comment]
This seems to be a bug in the Paradox Labs TokenBase module, not Magento. (The TokenBase module is included with both their Authorize.net CIM product as well as Adaptive Subscriptions.) It also seems they already resolved it in a version released in September 2017, so you may just need to upgrade.

It popped up due to commit d66b810e854c9cc4fc97ba715119bac48d5223a9, but that commit only causes a problem because the old TokenBase version inherited and overrode that class without calling the parent constructor.

**Comment by SpencerRohan** [comment]
Our team hit this bug in February.  We believe that Magento's codebase changed for at least versions 2.1.10 and 2.1.11 without doing a composer update. Meaning Magento merged code changes to a older version. https://github.com/magento/devdocs/issues/1746
