### ISSUE TITLE
Profiler enabled and isAjax in _REQUEST

### ISSUE THREAD

**Issue by vpietri** [magento/magento2#1359]
Hi

When profiler is  enabled and you call any page with ```isAjax=1``` as parameter in url you got the following error.

```
Fatal error: Uncaught exception 'Exception' with message 'Recoverable Error: Argument 1 passed to Zend_Controller_Plugin_Abstract::setResponse() must be an instance of Zend_Controller_Response_Abstract, instance of Magento\Framework\HTTP\PhpEnvironment\Response given, called in /var/www/magento2/ce-2/lib/internal/Magento/Framework/Profiler/Driver/Standard/Output/Firebug.php on line 61 and defined in /var/www/magento2/ce-2/vendor/magento/zendframework1/library/Zend/Controller/Plugin/Abstract.php on line 70' in /var/www/magento2/ce-2/lib/internal/Magento/Framework/App/ErrorHandler.php:59 Stack trace: #0 /var/www/magento2/ce-2/vendor/magento/zendframework1/library/Zend/Controller/Plugin/Abstract.php(70): Magento\Framework\App\ErrorHandler->handler(4096, 'Argument 1 pass...', '/var/www/magent...', 70, Array) #1 /var/www/magento2/ce-2/lib/internal/Magento/Framework/Profiler/Driver/Standard/Output/Firebug.php(61): Zend_Controller_Plugin_Abstract->setResponse(Object(Magento\Framework\HTTP\PhpEnvironment\Response)) #2 /var/www/ma in /var/www/magento2/ce-2/lib/internal/Magento/Framework/App/ErrorHandler.php on line 59
```

**Comment by dsikkema** [comment]
Hi @vpietri, can you describe which profiler you were using and how you enabled it?
Thanks!

**Comment by vpelipenko** [comment]
Closed. There is no response. @vpietri, feel free to reopen, when you see this issue unresolved.
