### ISSUE TITLE
Askit - 

### ISSUE THREAD

**Issue by webdevNYC** [magento/magento2#13621]

**Comment by webdevNYC** [comment]
Them I tried to create a question thru the admin and another error, please see below.  Them if I reload the page on the admin for Askit, the question shows there as created, and if I change the status from peddling to approved it doesn't show on the front end of that product.

ERROR _ CREATING QUESTION

Fatal error: Uncaught Error: Call to a member function getText() on null in /chroot/home/ddsgadge/ddsgadget.com/html/app/code/Swissup/Askit/Model/Notification/Admin.php:54 Stack trace: #0 /chroot/home/ddsgadge/ddsgadget.com/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Swissup\Askit\Model\Notification\Admin->execute(Object(Magento\Framework\Event\Observer)) #1 /chroot/home/ddsgadge/ddsgadget.com/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Swissup\Askit\Model\Notification\Admin), Object(Magento\Framework\Event\Observer)) #2 /chroot/home/ddsgadge/ddsgadget.com/html/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer)) #3 /chroot/home/ddsgadge/ddsgadget.com/html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('askit_message_a...', Array) #4 /chroot/home in /chroot/home/ddsgadge/ddsgadget.com/html/app/code/Swissup/Askit/Model/Notification/Admin.php on line 54
