### ISSUE TITLE
LabelGenerator fails to handle shipment error array

### ISSUE THREAD

**Issue by pemann** [magento/magento2#13681]
### Preconditions

1. Magento 2.1.x or Magento 2.2.x open source(community edition)
2. Download via composer. Using composer-create command.

### Steps to reproduce

1. At admin panel send a shipment and create shipping labels
2. Make the shipment fail somehow

### Expected result

1. Magento should successfully handle shipment errors

### Actual result

1. Magento fails to create LocalizedException from the shipment errors. This is because at LabelGenerator.php in function "create" the error array is not handled properly:

if ($response->hasErrors()) {
    throw new \Magento\Framework\Exception\LocalizedException(__($response->getErrors()));
}

**It fails because $response->getErrors() is an array and __() (Phrase) does not work with arrays.**

[2018-02-15 12:03:18] main.CRITICAL: Exception: Notice: Array to string conversion in /mg2/vendor/magento/framework/Phrase.php on line 69 in
 /mg2/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /mg2/vendor/magento/framework/Phrase.php(69): Magento\Framework\App\ErrorHandler->handler(8, 'Array to string...', '/mg2/vendor/mag...', 
69, Array)
#1 /mg2/app/functions.php(21): Magento\Framework\Phrase->__construct(Array, Array)
#2 /mg2/vendor/magento/module-shipping/Model/Shipping/LabelGenerator.php(79): __(Array)
....

**Comment by magento-engcom-team** [comment]
@pemann, thank you for your report.
We were not able to reproduce this issue by following the steps you provided (we have tested UPS and FedEx shipping methods). Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation.

**Comment by magento-engcom-team** [comment]
@pemann we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
