### ISSUE TITLE
JS Error on products using swatches for configuration when configuration set via URL

### ISSUE THREAD

**Issue by harrigo** [magento/magento2#13891]
I have a set of shoes that use swatches for both size and colour. When visiting via a url that sets the configurations automatically only the first swatch is set and errors are shown within console.

### Preconditions

1. Magento 2.2.1 - 2.2.3

### Steps to reproduce
1. Create 2 attribute sets using swatches e.g colour and size.
2. Set up a configurable product that uses these 2 attribute sets for configurations so you can set a colour and size with swatches.
3. Visit the product URL with configurations defined e.g magento2.com/product.html?ps=MTkwPTQ3OCYxOTQ9NTIx#190=478&194=521

### Expected result
1. Both swatches are set correctly image changes to correct image for defined configuration.

### Actual result
1. Only one swatch is set, image is therefore incorect and the following errors are shown within console.

> swatch-renderer.js:1168 Uncaught TypeError: Cannot read property 'updateData' of undefined
>     at $.(anonymous function).(anonymous function).processUpdateBaseImage (/static/version1519813156/frontend/Buzz/buzzluma/en_GB/Magento_Swatches/js/swatch-renderer.js:1168:25)
>     at $.(anonymous function).(anonymous function).processUpdateBaseImage (/static/version1519813156/frontend/Buzz/buzzluma/en_GB/jquery/jquery-ui.js:402:25)
>     at $.(anonymous function).(anonymous function).updateBaseImage (/static/version1519813156/frontend/Buzz/buzzluma/en_GB/Magento_Swatches/js/swatch-renderer.js:1137:22)
>     at $.(anonymous function).(anonymous function).updateBaseImage (/static/version1519813156/frontend/Buzz/buzzluma/en_GB/jquery/jquery-ui.js:402:25)
>     at $.(anonymous function).(anonymous function)._loadMedia (/static/version1519813156/frontend/Buzz/buzzluma/en_GB/Magento_Swatches/js/swatch-renderer.js:671:22)
>     at $.(anonymous function).(anonymous function)._loadMedia (/static/version1519813156/frontend/Buzz/buzzluma/en_GB/jquery/jquery-ui.js:402:25)
>     at $.(anonymous function).(anonymous function)._OnClick (/static/version1519813156/frontend/Buzz/buzzluma/en_GB/Magento_Swatches/js/swatch-renderer.js:722:21)
>     at $.(anonymous function).(anonymous function)._OnClick (/static/version1519813156/frontend/Buzz/buzzluma/en_GB/jquery/jquery-ui.js:402:25)
>     at HTMLDivElement.<anonymous> (/static/version1519813156/frontend/Buzz/buzzluma/en_GB/Magento_Swatches/js/swatch-renderer.js:616:32)
>     at HTMLDivElement.dispatch (/static/version1519813156/frontend/Buzz/buzzluma/en_GB/jquery.js:5226:27)

**Comment by magento-engcom-team** [comment]
@harrigo, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation of latest release.

**Comment by magento-engcom-team** [comment]
@harrigo we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
