### ISSUE TITLE
Not able to save customer from admin panel

### ISSUE THREAD

**Issue by arijit-de93** [magento/magento2#13959]
### Preconditions

1. Magento 2.3
2. php 7.1
3. MySQL 14.14
4. Ubuntu 17

### Steps to reproduce

1. Login to admin panel.
2. Go to Customer
3. Click on Add Customer
4. Provide data except Date of Birth and click on save.
7. Getting error 'Something went wrong while saving the customer'

### Expected result

1. It should save the customer.

### Actual result

1. Something went wrong while saving the customer.
2. Log:-
[2018-03-05 15:18:18] main.CRITICAL: Exception message: Warning: A non-numeric value encountered in /var/www/html/arijit/magento4/vendor/magento/zendframework1/library/Zend/Locale/Math/PhpMath.php on line 94
Trace: #0 /var/www/html/arijit/magento4/vendor/magento/zendframework1/library/Zend/Locale/Math/PhpMath.php(94): Magento\Framework\App\ErrorHandler->handler(2, 'A non-numeric v...', '/var/www/html/a...', 94, Array)
#1 /var/www/html/arijit/magento4/vendor/magento/zendframework1/library/Zend/Locale/Format.php(385): Zend_Locale_Math_PhpMath::Sub('0', '', 0)
#2 /var/www/html/arijit/magento4/vendor/magento/zendframework1/library/Zend/Locale/Format.php(662): Zend_Locale_Format::toNumber('', Array)
#3 /var/www/html/arijit/magento4/vendor/magento/zendframework1/library/Zend/Filter/NormalizedToLocalized.php(106): Zend_Locale_Format::toFloat('', Array)
#4 /var/www/html/arijit/magento4/vendor/magento/framework/Data/Form/Filter/Date.php(65): Zend_Filter_NormalizedToLocalized->filter('')
#5 /var/www/html/arijit/magento4/vendor/magento/module-customer/Model/Metadata/Form/AbstractData.php(196): Magento\Framework\Data\Form\Filter\Date->inputFilter('')
#6 /var/www/html/arijit/magento4/vendor/magento/module-customer/Model/Metadata/Form/Date.php(20): Magento\Customer\Model\Metadata\Form\AbstractData->_applyInputFilter('')
#7 /var/www/html/arijit/magento4/vendor/magento/module-customer/Model/Metadata/Form.php(242): Magento\Customer\Model\Metadata\Form\Date->extractValue(Object(Magento\Framework\App\Request\Http))
#8 /var/www/html/arijit/magento4/vendor/magento/module-customer/Controller/Adminhtml/Index/Save.php(74): Magento\Customer\Model\Metadata\Form->extractData(Object(Magento\Framework\App\Request\Http), 'customer')
#9 /var/www/html/arijit/magento4/vendor/magento/module-customer/Controller/Adminhtml/Index/Save.php(44): Magento\Customer\Controller\Adminhtml\Index\Save->_extractData('adminhtml_custo...', 'customer', Array, 'customer')
#10 /var/www/html/arijit/magento4/vendor/magento/module-customer/Controller/Adminhtml/Index/Save.php(186): Magento\Customer\Controller\Adminhtml\Index\Save->_extractCustomerData()
#11 /var/www/html/arijit/magento4/generated/code/Magento/Customer/Controller/Adminhtml/Index/Save/Interceptor.php(24): Magento\Customer\Controller\Adminhtml\Index\Save->execute()
#12 /var/www/html/arijit/magento4/vendor/magento/framework/App/Action/Action.php(107): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->execute()
#13 /var/www/html/arijit/magento4/vendor/magento/module-backend/App/AbstractAction.php(229): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/arijit/magento4/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /var/www/html/arijit/magento4/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callParent('dispatch', Array)
#16 /var/www/html/arijit/magento4/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /var/www/html/arijit/magento4/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/arijit/magento4/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#19 /var/www/html/arijit/magento4/generated/code/Magento/Customer/Controller/Adminhtml/Index/Save/Interceptor.php(39): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callPlugins('dispatch', Array, NULL)
#20 /var/www/html/arijit/magento4/vendor/magento/framework/App/FrontController.php(55): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/arijit/magento4/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/arijit/magento4/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#23 /var/www/html/arijit/magento4/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/arijit/magento4/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#25 /var/www/html/arijit/magento4/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /var/www/html/arijit/magento4/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#27 /var/www/html/arijit/magento4/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#28 /var/www/html/arijit/magento4/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#29 {main} [] []
3. Screenshot attached.
![customersaveerror](https://user-images.githubusercontent.com/16597334/36983385-3c2d41ce-20b8-11e8-89cb-b70d46a6113f.PNG)

**Comment by magento-engcom-team** [comment]
@arijit-de, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

![screenshot_1](https://user-images.githubusercontent.com/31669971/37030762-d6523962-2144-11e8-9f18-bd936519fcdf.png)

**Comment by lano-vargas** [comment]
@magento-engcom-team Same issue here 2.2.2 on Fresh Instalation.

**Comment by lano-vargas** [comment]
@arijit-de  https://github.com/magento/magento2/issues/13311

**Comment by magento-engcom-team** [comment]
@arijit-de , we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by punkstar** [comment]
In our testing, we believe this to be a problem with PhpMath and a PHP version between 7.1.0 and 7.1.14. We stopped experiencing this bug after we upgraded to 7.1.15. Sorry I can't give more details, but it was quite difficult to reproduce.

**Comment by thomas-kl1** [comment]
Hi guys, this issue is related to the date of birth.
The value must be set unless you have disabled the field in the admin config.

**Comment by arijit-de93** [comment]
Yes, its related to DOB, not sure if its PHP version problem.

**Comment by thomas-kl1** [comment]
No it's not, but it seems ok with Magento 2.2.4

**Comment by arijit-de93** [comment]
Which PHP version you are using?

**Comment by homer14b** [comment]
Yes, occurs when trying to save customer with an empty DOB from admin panel. Reproduceable on M 2.2.2 with PHP 7.1.15.

**Comment by developer-vtnetzwelt** [comment]
I am also facing the same issue on version - 2.2.3.  On php-7.0.30 its working fine and on php-7.1.20  its giving same issue -  "Warning: A non-numeric value encountered in /home/www-data/staging.risch-shoes.com/vendor/magento/zendframework1/library/Zend/Locale/Math/PhpMath.php on line 94"
