### ISSUE TITLE
API Error during productWithMediaGallery invokation => Property :"EntryData" does not exist

### ISSUE THREAD

**Issue by naspar** [magento/magento2#1417]
Hello Team,

I am facing a weird issue while trying to create/import a new product into M2 by using the API service.

Here is the API I am using :
Catalog - ProductRepositoryInterface - productWithMediaGallery
http://devdocs.magento.com/guides/v1.0/rest/restApi/restCollection/Magento/Catalog/Api/ProductRepositoryInterface/productWithMediaGallery.html

here below the error I found in the exception log while hitting the API service :
```
main.CRITICAL: exception 'Exception' with message 'Report ID: webapi-558da858ef77e; Message: Property :"EntryData" does not exist in the provided class: "Magento\Framework\Api\Data\ImageContentInterface".' in /home/user/workspace/public_html/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:194
```

and here below the json used during the HTTPcLient post invokation :
```
{"product":{"visibility":4,"attribute_set_id":4,"type_id":"simple","price":"45.0","media_gallery_entries":[{"types":["image","small_image"],"disabled":false,"position":1,"content":{"entry_data":"_9j_4AAQSkZJRgABAQEAYABgAAD__gAyUHJvY2Vzc2VkIEJ5IGVCYXkgd2l0aCBJbWFnZU1hZ2ljaywgejEuMS4wLiB8fEIy_9sAQwAGBAUGBQQGBgUGBwcGCAoQCgoJCQoUDg8MEBcUGBgXFBYWGh0lHxobIxwWFiAsICMmJykqKRkfLTAtKDAlKCko_9sAQwEHBwcKCAoTCgoTKBoWGigoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgo_8AAEQgBdQH0AwEiAAIRAQMRAf_EABwAAAICAwEBAAAAAAAAAAAAAAECAAMEBQYHCP_EAD8QAAE...<cutted_here>","mime_type":"image\/type","name":"pic_name"}}],"name":"product_name","sku":"26184971166","status":1,"custom_attributes":[{"value":"product_name","attribute_code":"description"}]}}
```
and as last, my piece of java code I have been using to import category and product - just want to mention that post/get calls are working fairly smoothly except the aforementioned error :

```
StringEntity input = new StringEntity(productObj.toJSONString(),"UTF-8");
			
			input.setContentEncoding("UTF-8");
			input.setContentType("application/json;charset=UTF-8");
			post.setEntity(input);
			
			HttpResponse response = client.execute(post);
			
			if (response.getStatusLine().getStatusCode() != 200) {
				System.out.println("Response Code\t: " + response.getStatusLine().getStatusCode()+"\n");
				System.out.println("Response Code\t: " + response.getStatusLine().getReasonPhrase()+"\n");
			}
```
Just let me know if you need more info .. many thanks for all your commitment in making this framework so amazing !!

**Comment by naspar** [comment]
Hi Guys .. any advice / fix for this issue ?

it is very critical as i can't insert products and link images using the API service.

I am getting error 500 from the server , the API service can't manage the request or properly handle the error exception.

Please let me know if you need more info from my end.

Thanks,

**Comment by joanhe** [comment]
Thanks @naspar for reporting this issue. Internal issue MAGEDOC-2426 is created to update the document.

**Comment by bluk** [comment]
Can you change your `media_gallery_entries` data to be:

```
"media_gallery_entries": [
    {
        "types": ["image","small_image"],
        "disabled":false,
        "position":1,
        "content":{
            "base64_encoded_data" : "_9j_4AAQSkZJRgABAQEAYABgAAD__gAyUHJvY2Vzc2VkIEJ5IGVCYXkgd2l0aCBJbWFnZU1hZ2ljaywgejEuMS4wLiB8fEIy_9sAQwAGBAUGBQQGBgUGBwcGCAoQCgoJCQoUDg8MEBcUGBgXFBYWGh0lHxobIxwWFiAsICMmJykqKRkfLTAtKDAlKCko_9sAQwEHBwcKCAoTCgoTKBoWGigoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgo_8AAEQgBdQH0AwEiAAIRAQMRAf_EABwAAAICAwEBAAAAAAAAAAAAAAECAAMEBQYHCP_EAD8QAAE...<cutted_here>",
            "type": "image/jpeg",
            "name":"pic_name.jpg"
        }
    }
]
```

Notably `entry_data` became `base64_encoded_data`, `mime_type` became just `type`. Also, I changed the `type` value to be `image/jpeg` and added a `.jpg` extension to the `name` of the file to be saved. The field names were changed as the API was being stabilized.

This is what I used to try:

```
{
  "product": {
    "sku": "randomsku",
    "name": "sku-5550e875431621.27617263",
    "visibility": 4,
    "type_id": "simple",
    "price": 3.62,
    "status": 1,
    "attribute_set_id": 4,
    "custom_attributes": [
      {
        "attribute_code": "cost",
        "value": ""
      },
      {
        "attribute_code": "description",
        "value": "Description"
      }
    ],
    "media_gallery_entries": [
      {
        "position": 1,
        "disabled": true,
        "label": "tiny1",
        "types": [],
        "content": {
          "type": "image/jpeg",
          "name": "tiny11431365749.jpg",
          "base64_encoded_data": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wgARCABgAGADASIAAhEBAxEB/8QAGwABAQADAQEBAAAAAAAAAAAAAAUCAwQHAQb/xAAZAQEAAwEBAAAAAAAAAAAAAAAAAgMFBgH/2gAMAwEAAhADEAAAAf35gZpqyVJNFJNFJNFJq21xTaU2yXm5wdJqd7meOlz4nU0b7JehWI9jmspNpTY+eb83T86bV5tFHCmHNj2fTVuxyun6FYj2Oby02lNj55uOp1wAAPQrEexzGSm0psfPNx1OuAAB6FYj2OYyWGamE1SWSmqQmqQmqQ1bSuP/xAAiEAAABgICAwEBAAAAAAAAAAAAAQIDBBQQNAUwERITIjP/2gAIAQEAAQUC7VrS2i/FF+KL8UX4ovxRfii/FF+KG3EuoxP0eji9DE/RD7SCb9W2R9TIzcP2N0zbaNRoHF6GJ+iJH8Hy/Bk34X6fQlGptoyNscXoYn6IMiPBJSQMiMePAIiLHF6GJ+j0cXoYn6PRxehifo9HF6GJ+j0cXoYWhLiKEUUIooRRQiihFFCKKEUUIobbS0jt/8QAHxEAAgEFAAMBAAAAAAAAAAAAAAECAxESMlEQICEx/9oACAEDAQE/ATCXDCXDCXDCXPENkTbirmdv0zQndXKm7IbIkrpolTu7mDuR+L6VN2Q2XrU3ZDZetTd+M5dM5dM5dM5d8f/EACMRAAEDBAIDAAMAAAAAAAAAAAEAAgMTM1JxERIEIDEQIVH/2gAIAQIBAT8BVGTEqjJiVRkxKoyYlEcfVDcbtSvLG9gFVDf0/wCozsCY7s3leRedtQ3G7Uje7C3+qSDs7lUT255TAQ0AryLztqG43fr5F521Dcbv18i87f4rSZFVpMiq0mRVaTIonn6v/8QAJhAAAQIEBgIDAQAAAAAAAAAAAgABAxARMxIhMHGBsTFRIjJBYf/aAAgBAQAGPwLVciejMrwq8KvCrwq8KvCrwq8Kxg9R9zi7aIc9zi7SIqZrEzL5A4t7WEQxO3lFQfk3lk2JpBz3OLtIk38dXTKv5VfZwL2ojVxUbyho/wCSDnucXaWcsmZZszyyZmkHPc4u2iHPc4u2iHPc4u2iHPc4u2iHPc3EmqzqyKsirIqyKsirIqyKsisANQfWt//EACAQAAEDAwUBAAAAAAAAAAAAAAEAEfAQMWEhMEGhsVH/2gAIAQEAAT8h3QBronhTipxU4qcVOKnFTipxQIGawVn52e36Vn5oAN93fKalqbaF3QCPgtqdCGV9BmRBILobZR2Y0DF3fNO36Vn5p4PU8bVgktdkYA1Cx61bsHJnRRMEAHnRDwBIB24p2/Ss/NALACPhoUcI/QF28BAAYAAfAnfWPgp2/Ss/Oz2/Ss/Oz2/Ss/Oz2/Ss/Oz2/SoA10DypxU4qcVOKnFTipxU4oEDFYN7/9oADAMBAAIAAwAAABDv/wD/AP8A/wD/AOuvlf7DPn1f/vvvlf8A7775W/8A/wD/AP8A/8QAIBEAAgIDAAMAAwAAAAAAAAAAAAERYSGRoSBBUTGBwf/aAAgBAwEBPxBKcIvaL2i9ovaGmnDO5DSimLj+Mhhi6l9ga5Xyn6FKT2drO5F+ImsM/TMcwnPefsRoX5HazuXj2s7l49rE4yi9svbL2y9sbbcs/8QAIhEBAAIABwACAwAAAAAAAAAAAQARITFBUaGx8SBhgZHB/9oACAECAQE/EAVonmM8xnmM8xiKhTOE7jcTQrbWBtg/ybQ+lobW0V+aiCW4Xo6Zg1SmxAI6zmu5wnccLQn7JfGsQG702pOYugAbyvGzUusM7zwmeibTmu5wnfx5rucJ38ea7go2T3Ge4z3Ge4xFatn/xAAmEAABAgUDBAMBAAAAAAAAAAABABEhMWHR8TBB8BAggZFRcaGx/9oACAEBAAE/ENUA93lgWIsWIsWIsWIsWIsWIsWIsWIsRfKkSBYsf0deNRqfONR0YXGERMg8HbdEjjEJCcZAE/KZHMDIAmTgSQ7gAwQdKJQKuEAAYd26IZOMPCw8H7fnGo6cChGGkSnKicj2j6bAABk/TJ4AqJawPmBQr4IjRlDwgkdxJyTb+j2/ONR0ITXMDgqaoO8goaAEEgI/1Co42GCrpDQf12/ONRqfONRqfONRqfONRqfAD3aWBZi5Zi5Zi5Zi5Zi5Zi5Zi5Zi5F8qTIBy5/Trf//Z"
        }
      },
      {
        "position": 2,
        "disabled": false,
        "label": "tiny2",
        "types": [
          "image",
          "small_image"
        ],
        "content": {
          "type": "image/jpeg",
          "name": "tiny21431365749.jpg",
          "base64_encoded_data": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wgARCABgAGADASIAAhEBAxEB/8QAGwABAQADAQEBAAAAAAAAAAAAAAUCAwQHAQb/xAAZAQEAAwEBAAAAAAAAAAAAAAAAAgMFBgH/2gAMAwEAAhADEAAAAf35gZpqyVJNFJNFJNFJq21xTaU2yXm5wdJqd7meOlz4nU0b7JehWI9jmspNpTY+eb83T86bV5tFHCmHNj2fTVuxyun6FYj2Oby02lNj55uOp1wAAPQrEexzGSm0psfPNx1OuAAB6FYj2OYyWGamE1SWSmqQmqQmqQ1bSuP/xAAiEAAABgICAwEBAAAAAAAAAAAAAQIDBBQQNAUwERITIjP/2gAIAQEAAQUC7VrS2i/FF+KL8UX4ovxRfii/FF+KG3EuoxP0eji9DE/RD7SCb9W2R9TIzcP2N0zbaNRoHF6GJ+iJH8Hy/Bk34X6fQlGptoyNscXoYn6IMiPBJSQMiMePAIiLHF6GJ+j0cXoYn6PRxehifo9HF6GJ+j0cXoYWhLiKEUUIooRRQiihFFCKKEUUIobbS0jt/8QAHxEAAgEFAAMBAAAAAAAAAAAAAAECAxESMlEQICEx/9oACAEDAQE/ATCXDCXDCXDCXPENkTbirmdv0zQndXKm7IbIkrpolTu7mDuR+L6VN2Q2XrU3ZDZetTd+M5dM5dM5dM5d8f/EACMRAAEDBAIDAAMAAAAAAAAAAAEAAgMTM1JxERIEIDEQIVH/2gAIAQIBAT8BVGTEqjJiVRkxKoyYlEcfVDcbtSvLG9gFVDf0/wCozsCY7s3leRedtQ3G7Uje7C3+qSDs7lUT255TAQ0AryLztqG43fr5F521Dcbv18i87f4rSZFVpMiq0mRVaTIonn6v/8QAJhAAAQIEBgIDAQAAAAAAAAAAAgABAxARMxIhMHGBsTFRIjJBYf/aAAgBAQAGPwLVciejMrwq8KvCrwq8KvCrwq8Kxg9R9zi7aIc9zi7SIqZrEzL5A4t7WEQxO3lFQfk3lk2JpBz3OLtIk38dXTKv5VfZwL2ojVxUbyho/wCSDnucXaWcsmZZszyyZmkHPc4u2iHPc4u2iHPc4u2iHPc4u2iHPc3EmqzqyKsirIqyKsirIqyKsisANQfWt//EACAQAAEDAwUBAAAAAAAAAAAAAAEAEfAQMWEhMEGhsVH/2gAIAQEAAT8h3QBronhTipxU4qcVOKnFTipxQIGawVn52e36Vn5oAN93fKalqbaF3QCPgtqdCGV9BmRBILobZR2Y0DF3fNO36Vn5p4PU8bVgktdkYA1Cx61bsHJnRRMEAHnRDwBIB24p2/Ss/NALACPhoUcI/QF28BAAYAAfAnfWPgp2/Ss/Oz2/Ss/Oz2/Ss/Oz2/Ss/Oz2/SoA10DypxU4qcVOKnFTipxU4oEDFYN7/9oADAMBAAIAAwAAABDv/wD/AP8A/wD/AOuvlf7DPn1f/vvvlf8A7775W/8A/wD/AP8A/8QAIBEAAgIDAAMAAwAAAAAAAAAAAAERYSGRoSBBUTGBwf/aAAgBAwEBPxBKcIvaL2i9ovaGmnDO5DSimLj+Mhhi6l9ga5Xyn6FKT2drO5F+ImsM/TMcwnPefsRoX5HazuXj2s7l49rE4yi9svbL2y9sbbcs/8QAIhEBAAIABwACAwAAAAAAAAAAAQARITFBUaGx8SBhgZHB/9oACAECAQE/EAVonmM8xnmM8xiKhTOE7jcTQrbWBtg/ybQ+lobW0V+aiCW4Xo6Zg1SmxAI6zmu5wnccLQn7JfGsQG702pOYugAbyvGzUusM7zwmeibTmu5wnfx5rucJ38ea7go2T3Ge4z3Ge4xFatn/xAAmEAABAgUDBAMBAAAAAAAAAAABABEhMWHR8TBB8BAggZFRcaGx/9oACAEBAAE/ENUA93lgWIsWIsWIsWIsWIsWIsWIsWIsRfKkSBYsf0deNRqfONR0YXGERMg8HbdEjjEJCcZAE/KZHMDIAmTgSQ7gAwQdKJQKuEAAYd26IZOMPCw8H7fnGo6cChGGkSnKicj2j6bAABk/TJ4AqJawPmBQr4IjRlDwgkdxJyTb+j2/ONR0ITXMDgqaoO8goaAEEgI/1Co42GCrpDQf12/ONRqfONRqfONRqfONRqfAD3aWBZi5Zi5Zi5Zi5Zi5Zi5Zi5Zi5F8qTIBy5/Trf//Z"
        }
      }
    ]
  }
}
```

**Comment by keharper** [comment]
I've updated the documentation to reflect Bryant's new example.

**Comment by naspar** [comment]
Hi @bluk and @keharper ,
thank you for supporting and sorry for my late reply .. I spent the whole day to figure it out but now it's time to give it up and ask for your help !

Basically the API call gets executed without issue but I can't see the image associated to the product . .either in the admin or in the frontend .. there is only the product itself with the basic information . For simplify my debugging I have create a json very similar to yours sent yesterday and it doesn't work - here below the json I get back from M2 which make me assume the call has been properly executed :

```
{"product":{"visibility":4,"attribute_set_id":4,"type_id":"simple","price":"145.0","media_gallery_entries":[{"types":[],"disabled":true,"position":1,"label":"tiny1","content":{"name":"pic1.jpg","type":"image\/jpeg","base64_encoded_data":"your_encoded_data"}},{"types":["image","small_image"],"disabled":false,"position":2,"label":"tiny2","content":{"name":"pic2.jpg","type":"image\/jpeg","base64_encoded_data":"your_encoded_data"}}],"name":"name","extension_attributes":{"stock_item":{"is_in_stock":true,"show_default_notification_message":false,"min_sale_qty":1,"qty":"3","use_config_min_qty":1,"is_qty_decimal":false}},"sku":"261851403821","status":1,"custom_attributes":[{"description","attribute_code":"description"}]}}
```
Would you recommend to install the beta16 and try with the latest base code ?

Thanks Again!

**Comment by bluk** [comment]
@naspar You may want to try it with the latest base code. Also, did you look into the store specific view? There's a dropdown to view the store specific information.

**Comment by naspar** [comment]
Many thanks for your support, this is now working like a charm!
Sorry for my late answer .. I needed to reinstall magento from scratch and try the latest base-code.

**Comment by chrisjubb** [comment]
when I POST that data to the end point I get this error:
```
<message>The image does not exist.</message>
```


full stack trace:
```


<?xml version="1.0"?>
<response>
  <message>The image does not exist.</message>
  <trace>#0 /usr/share/nginx/html/app/code/Magento/Catalog/Model/ProductRepository.php(462): Magento\Catalog\Model\Product\Attribute\Backend\Media-&gt;addImage(Object(Magento\Catalog\Model\Product\Interceptor), 'tmp/catalog/pro...', Array, true, true)
#1 /usr/share/nginx/html/app/code/Magento/Catalog/Model/ProductRepository.php(534): Magento\Catalog\Model\ProductRepository-&gt;processNewMediaGalleryEntry(Object(Magento\Catalog\Model\Product\Interceptor), Array)
#2 /usr/share/nginx/html/app/code/Magento/Catalog/Model/ProductRepository.php(574): Magento\Catalog\Model\ProductRepository-&gt;processMediaGallery(Object(Magento\Catalog\Model\Product\Interceptor), Array)
#3 [internal function]: Magento\Catalog\Model\ProductRepository-&gt;save(Object(Magento\Catalog\Model\Product\Interceptor), false)
#4 /usr/share/nginx/html/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#5 /usr/share/nginx/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Catalog\Model\ProductRepository\Interceptor-&gt;___callParent('save', Array)
#6 /usr/share/nginx/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain-&gt;invokeNext('Magento\Catalog...', 'save', Object(Magento\Catalog\Model\ProductRepository\Interceptor), Array, 'configurablePro...')
#7 /usr/share/nginx/html/app/code/Magento/ConfigurableProduct/Model/Plugin/AroundProductRepositorySave.php(62): Magento\Framework\Interception\Chain\Chain-&gt;Magento\Framework\Interception\Chain\{closure}(Object(Magento\Catalog\Model\Product\Interceptor), false)
#8 [internal function]: Magento\ConfigurableProduct\Model\Plugin\AroundProductRepositorySave-&gt;aroundSave(Object(Magento\Catalog\Model\ProductRepository\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor), false)
#9 /usr/share/nginx/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#10 /usr/share/nginx/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain-&gt;invokeNext('Magento\Catalog...', 'save', Object(Magento\Catalog\Model\ProductRepository\Interceptor), Array, 'catalogInventor...')
#11 /usr/share/nginx/html/app/code/Magento/CatalogInventory/Model/Plugin/AroundProductRepositorySave.php(49): Magento\Framework\Interception\Chain\Chain-&gt;Magento\Framework\Interception\Chain\{closure}(Object(Magento\Catalog\Model\Product\Interceptor), false)
#12 [internal function]: Magento\CatalogInventory\Model\Plugin\AroundProductRepositorySave-&gt;aroundSave(Object(Magento\Catalog\Model\ProductRepository\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor), false)
#13 /usr/share/nginx/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#14 /usr/share/nginx/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain-&gt;invokeNext('Magento\Catalog...', 'save', Object(Magento\Catalog\Model\ProductRepository\Interceptor), Array, 'downloadableAro...')
#15 /usr/share/nginx/html/app/code/Magento/Downloadable/Model/Plugin/AroundProductRepositorySave.php(49): Magento\Framework\Interception\Chain\Chain-&gt;Magento\Framework\Interception\Chain\{closure}(Object(Magento\Catalog\Model\Product\Interceptor), false)
#16 [internal function]: Magento\Downloadable\Model\Plugin\AroundProductRepositorySave-&gt;aroundSave(Object(Magento\Catalog\Model\ProductRepository\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor), false)
#17 /usr/share/nginx/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#18 /usr/share/nginx/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain-&gt;invokeNext('Magento\Catalog...', 'save', Object(Magento\Catalog\Model\ProductRepository\Interceptor), Array, 'bundleSaveOptio...')
#19 /usr/share/nginx/html/app/code/Magento/Bundle/Model/Plugin/BundleSaveOptions.php(42): Magento\Framework\Interception\Chain\Chain-&gt;Magento\Framework\Interception\Chain\{closure}(Object(Magento\Catalog\Model\Product\Interceptor), false)
#20 [internal function]: Magento\Bundle\Model\Plugin\BundleSaveOptions-&gt;aroundSave(Object(Magento\Catalog\Model\ProductRepository\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor), false)
#21 /usr/share/nginx/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#22 /usr/share/nginx/html/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain-&gt;invokeNext('Magento\Catalog...', 'save', Object(Magento\Catalog\Model\ProductRepository\Interceptor), Array, 'transactionWrap...')
#23 /usr/share/nginx/html/app/code/Magento/Catalog/Model/Plugin/ProductRepository/TransactionWrapper.php(44): Magento\Catalog\Model\ProductRepository\Interceptor-&gt;Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor), false)
#24 [internal function]: Magento\Catalog\Model\Plugin\ProductRepository\TransactionWrapper-&gt;aroundSave(Object(Magento\Catalog\Model\ProductRepository\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor), false)
#25 /usr/share/nginx/html/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#26 /usr/share/nginx/html/var/generation/Magento/Catalog/Model/ProductRepository/Interceptor.php(52): Magento\Catalog\Model\ProductRepository\Interceptor-&gt;___callPlugins('save', Array, Array)
#27 [internal function]: Magento\Catalog\Model\ProductRepository\Interceptor-&gt;save(Object(Magento\Catalog\Model\Product\Interceptor), false)
#28 /usr/share/nginx/html/app/code/Magento/Webapi/Controller/Rest.php(180): call_user_func_array(Array, Array)
#29 /usr/share/nginx/html/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest-&gt;dispatch(Object(Magento\Framework\App\Request\Http))
#30 /usr/share/nginx/html/lib/internal/Magento/Framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor-&gt;dispatch(Object(Magento\Framework\App\Request\Http))
#31 /usr/share/nginx/html/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\Http-&gt;launch()
#32 /usr/share/nginx/html/pub/index.php(37): Magento\Framework\App\Bootstrap-&gt;run(Object(Magento\Framework\App\Http))
#33 {main}</trace>
</response>
```

**Comment by piotrekkaminski** [comment]
The original issue should be fixed already.

**Comment by jrosell** [comment]
@bluk exactly using your example and I get "There is no MediaGalleryEntryConverter for given type" in magento 2.1 I use.
