### ISSUE TITLE
Magento 2.2.2 - Tablerates not working on Cart Page

### ISSUE THREAD

**Issue by Vikram0811** [magento/magento2#14171]
I am using `Tablerates` as my shipping method and the condition is set to `Price vs Destination`.

**Use case One**

    Free Shipping over $200

**Use case Two**

    If zip code falls under Zone 1 i.e. 28682-28685, `$20` flat rate shipping fee

**Use case Three**

    If zip code falls under Zone 2 i.e. 28360-28365, `$50` flat rate shipping fee

 Below is how my CSV looks like

    Country   Region/State Zip/Postal Code Order Subtotal(and above) Shipping Price																					
    USA	    NC	         28682	             0	                                         20
    USA	    NC	         28682	             201	                                 0						   															
    USA	    NC	         28360	             0	                                         50
    USA	    NC	         28360	             201	                                 0

Upload works, as is reflected in the table `shipping_tablerate` as seen in below image

![shipping-table](https://user-images.githubusercontent.com/4048181/37587966-d0ec1d84-2b86-11e8-833e-0773e9136d11.png)

But when user check shipping price on `cart` page for zip code whose shipping price should be `$20`, it always takes `$50`.  It can be seen in below image. Currently the user is logged in

![cart-estimate](https://user-images.githubusercontent.com/4048181/37588048-14394134-2b87-11e8-89fe-17bf0ca6581a.png)

Although when `Subtotal` goes beyond `$200`, it shows shipping price `$0` which is correct as per tablerates. Moreover on checkout page, it shows correct shipping price based on zip code selected. It happens only on cart page. 

Estimate Shipping and Tax also shows correct shipping price based on zip code entered. But when I click on selected price it throws below exception

`/rest/default/V1/carts/mine/totals-information 500 (Internal Server Error)`

How do I resolve this and display correct shipping price on cart page?

Thanks.

**Comment by ishakhsuvarov** [comment]
Hi @Vikram0811 
Thank you for reporting.

Could you please attach logged exception, which happened during the `/rest/default/V1/carts/mine/totals-information 500 (Internal Server Error)` request?

**Comment by Vikram0811** [comment]
Hi,

The response I get

`{"messages":{"error":[{"code":500,"message":"Fatal Error: 'Uncaught TypeError: Argument 1 passed to Magento\\Quote\\Model\\Cart\\Totals::setExtensionAttributes() must be an instance of Magento\\Quote\\Api\\Data\\TotalsExtensionInterface, instance of Magento\\Quote\\Api\\Data\\AddressExtension given, called in \/home\/storeq\/public_html\/vendor\/magento\/framework\/Api\/DataObjectHelper.php on line 125 and defined in \/home\/storeq\/public_html\/vendor\/magento\/module-quote\/Model\/Cart\/Totals.php:592\nStack trace:\n#0 \/home\/storeq\/public_html\/vendor\/magento\/framework\/Api\/DataObjectHelper.php(125): Magento\\Quote\\Model\\Cart\\Totals->setExtensionAttributes(Object(Magento\\Quote\\Api\\Data\\AddressExtension))\n#1 \/home\/storeq\/public_html\/vendor\/magento\/framework\/Api\/DataObjectHelper.php(85): Magento\\Framework\\Api\\DataObjectHelper->_setDataValues(Object(Magento\\Quote\\Model\\Cart\\Totals), Array, 'Magento\\\\Quote\\\\A...')\n#2 \/home\/storeq\/public_html\/vendor\/magento\/module-quote\/Model\/Cart\/CartTotalRepository.php(103): Magento\\Framework\\Api\\DataObjectHelper->populateWithArray(Object(Magento\\Quote\\Model\\Cart\\Tota' in '\/home\/storeq\/public_html\/vendor\/magento\/module-quote\/Model\/Cart\/Totals.php' on line 592","trace":"Trace is not available."}]}}`

**Comment by AnshuMishra17** [comment]
I am working on this at #dmcdindia

**Comment by AnshuMishra17** [comment]
I have tried to replicate the issue on Magento 2.2-develop branch and I was not able to replicate the issue and the shipping was working fine for me as expected.
I have tested the issue on Magento 2.2.2 and Magento 2.2.4 as well and on both the versions shipping table rate calculation is fine.
![screen shot 2018-05-19 at 12 42 20 pm](https://user-images.githubusercontent.com/3141554/40266138-7fee4594-5b63-11e8-939a-5f2051a8800d.png)
![screen shot 2018-05-19 at 12 43 12 pm](https://user-images.githubusercontent.com/3141554/40266139-804d54d0-5b63-11e8-9642-0f72d05b78cb.png)
![screen shot 2018-05-19 at 12 43 31 pm](https://user-images.githubusercontent.com/3141554/40266140-80b90c5c-5b63-11e8-9925-544505883d9b.png)
![screen shot 2018-05-19 at 12 44 09 pm](https://user-images.githubusercontent.com/3141554/40266142-8133d0ae-5b63-11e8-955f-aae18b8a2d20.png)

**Comment by magento-engcom-team** [comment]
Hi @Vikram0811 
Comment above states that issue is not reproducible. Could you please re-check?

**Comment by magento-engcom-team** [comment]
@Vikram0811 we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
