### ISSUE TITLE
authorize.net direct post "Unable to serialized value" in v2.2.2

### ISSUE THREAD

**Issue by treii28** [magento/magento2#14400]
Magento 2.2.2
Php 7.0
mysql 14.14 dist 5.7.21
Ubuntu linux OS v16.04 Apache/2.4.18 (Ubuntu)

### Steps to reproduce
Add item to cart, fill in address, payment, shipping options, click submit.

### Expected result
Order item

### Actual result
Pop-up with " Attention Sorry, but something went wrong. Please contact the seller."

var/report exception:

> {
> "0":"Unable to serialize value.","1":"#0 /srv/magento/vendor/magento/framework/Serialize/JsonConverter.php(26): Magento\Framework\Serialize\Serializer\Json->serialize(Array)
> #1 /srv/magento/vendor/magento/framework/DataObject.php(334): Magento\Framework\Serialize\JsonConverter::convert(Array)
> #2 /srv/magento/vendor/magento/zendframework1/library/Zend/Json.php(134): Magento\Framework\DataObject->toJson()
> #3 /srv/magento/vendor/magento/framework/Json/Encoder.php(37): Zend_Json::encode(Object(Magento\Framework\DataObject))
> #4 /srv/magento/vendor/magento/framework/Json/Helper/Data.php(48): Magento\Framework\Json\Encoder->encode(Object(Magento\Framework\DataObject))
> #5 /srv/magento/vendor/magento/module-authorizenet/Controller/Directpost/Payment/Place.php(154): Magento\Framework\Json\Helper\Data->jsonEncode(Object(Magento\Framework\DataObject))
> #6 /srv/magento/vendor/magento/module-authorizenet/Controller/Directpost/Payment/Place.php(102): Magento\Authorizenet\Controller\Directpost\Payment\Place->placeCheckoutOrder()
> #7 /srv/magento/vendor/magento/framework/App/Action/Action.php(107): Magento\Authorizenet\Controller\Directpost\Payment\Place->execute()
> #8 /srv/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
> #9 /srv/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Authorizenet\Controller\Directpost\Payment\Place\Interceptor->___callParent('dispatch', Array)
> #10 /srv/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Authorizenet\Controller\Directpost\Payment\Place\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
> #11 /srv/magento/generated/code/Magento/Authorizenet/Controller/Directpost/Payment/Place/Interceptor.php(26): Magento\Authorizenet\Controller\Directpost\Payment\Place\Interceptor->___callPlugins('dispatch', Array, Array)
> #12 /srv/magento/vendor/magento/framework/App/FrontController.php(55): Magento\Authorizenet\Controller\Directpost\Payment\Place\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> #13 /srv/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
> #14 /srv/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
> #15 /srv/magento/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
> #16 /srv/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #17 /srv/magento/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
> #18 /srv/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #19 /srv/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
> #20 /srv/magento/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
> #21 /srv/magento/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> #22 /srv/magento/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
> #23 /srv/magento/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
> #24 {main}","url":"/authorizenet/directpost_payment/place/","script_name":"/index.php"
> }

**Comment by treii28** [comment]
I cannot be one hundred percent certain, but I believe the data either wasn't fully converted or was otherwise out of sync as the values (although showing an hash in the database) were blank in the admin screens. I re-entered the credentials and I am at least getting the transaction to go through without exceptions. (of course, now I'm getting errors about the hash, but have opened a ticket with authorize)
Since my current issue is a new one, if it's necessary to address the 'response hash validation failed' here, i will open a new ticket.
I'm guessing this was a data field not properly converted when upgrading to 2.2 or perhaps that got out of sync when replicating server records from our third-party developer.
