### ISSUE TITLE
Custom Payment Methods not showing on checkout

### ISSUE THREAD

**Issue by mimdev** [magento/magento2#14477]
### Preconditions
1. Magento 2.1.9
2. PHP 5.6
3. Ubuntu 16

### Steps to reproduce
1. Add products to cart and checkout
2. Payment Methods not showing  (Only Paypal)

### Expected result
1.  Many choices payment method
2. screenshot
![figure2](https://user-images.githubusercontent.com/8605399/38164501-ffd42384-3505-11e8-9845-dfe63f2f5cc8.png)

### Actual result
1. exception.log: 
[2018-03-28 19:38:24] main.CRITICAL: exception 'Exception' with message 'Notice: Array to string conversion in /var/www/html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 2929' in /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /var/www/html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(2929): Magento\Framework\App\ErrorHandler->handler(8, 'Array to string...', '/var/www/html/v...', 2929, Array)
#1 /var/www/html/vendor/magento/framework/Model/ResourceModel/AbstractResource.php(168): Magento\Framework\DB\Adapter\Pdo\Mysql->prepareColumnValue(Array, Array)
#2 /var/www/html/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(728): Magento\Framework\Model\ResourceModel\AbstractResource->_prepareDataForTable(Object(Magento\Quote\Model\Quote\Address), 'quote_address')
#3 /var/www/html/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(784): Magento\Framework\Model\ResourceModel\Db\AbstractDb->prepareDataForUpdate(Object(Magento\Quote\Model\Quote\Address))
#4 /var/www/html/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(403): Magento\Framework\Model\ResourceModel\Db\AbstractDb->updateObject(Object(Magento\Quote\Model\Quote\Address))
#5 /var/www/html/vendor/magento/framework/Model/AbstractModel.php(631): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Magento\Quote\Model\Quote\Address))
#6 /var/www/html/vendor/magento/module-quote/Model/ShippingAddressManagement.php(125): Magento\Framework\Model\AbstractModel->save()
#7 /var/www/html/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingProcessor.php(66): Magento\Quote\Model\ShippingAddressManagement->assign('71', Object(Magento\Quote\Model\Quote\Address))
#8 /var/www/html/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingAssignmentProcessor.php(110): Magento\Quote\Model\Quote\ShippingAssignment\ShippingProcessor->save(Object(Magento\Quote\Model\Shipping), Object(Magento\Quote\Model\Quote))
#9 /var/www/html/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingAssignmentPersister.php(34): Magento\Quote\Model\Quote\ShippingAssignment\ShippingAssignmentProcessor->save(Object(Magento\Quote\Model\Quote), Object(Magento\Quote\Model\ShippingAssignment))
#10 /var/www/html/vendor/magento/module-quote/Model/QuoteRepository/SaveHandler.php(133): Magento\Quote\Model\Quote\ShippingAssignment\ShippingAssignmentPersister->save(Object(Magento\Quote\Model\Quote), Object(Magento\Quote\Model\ShippingAssignment))
#11 /var/www/html/vendor/magento/module-quote/Model/QuoteRepository/SaveHandler.php(106): Magento\Quote\Model\QuoteRepository\SaveHandler->processShippingAssignment(Object(Magento\Quote\Model\Quote))
#12 /var/www/html/vendor/magento/module-quote/Model/QuoteRepository.php(161): Magento\Quote\Model\QuoteRepository\SaveHandler->save(Object(Magento\Quote\Model\Quote))
#13 /var/www/html/vendor/magento/module-checkout/Model/ShippingInformationManagement.php(156): Magento\Quote\Model\QuoteRepository->save(Object(Magento\Quote\Model\Quote))
#14 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Checkout\Model\ShippingInformationManagement->saveAddressInformation('71', Object(Magento\Checkout\Model\ShippingInformation))
#15 /var/www/html/var/generation/Magento/Checkout/Model/ShippingInformationManagement/Interceptor.php(26): Magento\Checkout\Model\ShippingInformationManagement\Interceptor->___callPlugins('saveAddressInfo...', Array, Array)
#16 /var/www/html/vendor/magento/module-checkout/Model/GuestShippingInformationManagement.php(45): Magento\Checkout\Model\ShippingInformationManagement\Interceptor->saveAddressInformation('71', Object(Magento\Checkout\Model\ShippingInformation))
#17 [internal function]: Magento\Checkout\Model\GuestShippingInformationManagement->saveAddressInformation('35a2c05016bbdc8...', Object(Magento\Checkout\Model\ShippingInformation))
#18 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#19 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#20 /var/www/html/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#23 /var/www/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#24 {main} [] []
[2018-03-28 19:38:24] main.CRITICAL: exception 'Magento\Framework\Exception\InputException' with message 'Unable to save address. Please check input data.' in /var/www/html/vendor/magento/module-quote/Model/ShippingAddressManagement.php:128
Stack trace:
#0 /var/www/html/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingProcessor.php(66): Magento\Quote\Model\ShippingAddressManagement->assign('71', Object(Magento\Quote\Model\Quote\Address))
#1 /var/www/html/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingAssignmentProcessor.php(110): Magento\Quote\Model\Quote\ShippingAssignment\ShippingProcessor->save(Object(Magento\Quote\Model\Shipping), Object(Magento\Quote\Model\Quote))
#2 /var/www/html/vendor/magento/module-quote/Model/Quote/ShippingAssignment/ShippingAssignmentPersister.php(34): Magento\Quote\Model\Quote\ShippingAssignment\ShippingAssignmentProcessor->save(Object(Magento\Quote\Model\Quote), Object(Magento\Quote\Model\ShippingAssignment))
#3 /var/www/html/vendor/magento/module-quote/Model/QuoteRepository/SaveHandler.php(133): Magento\Quote\Model\Quote\ShippingAssignment\ShippingAssignmentPersister->save(Object(Magento\Quote\Model\Quote), Object(Magento\Quote\Model\ShippingAssignment))
#4 /var/www/html/vendor/magento/module-quote/Model/QuoteRepository/SaveHandler.php(106): Magento\Quote\Model\QuoteRepository\SaveHandler->processShippingAssignment(Object(Magento\Quote\Model\Quote))
#5 /var/www/html/vendor/magento/module-quote/Model/QuoteRepository.php(161): Magento\Quote\Model\QuoteRepository\SaveHandler->save(Object(Magento\Quote\Model\Quote))
#6 /var/www/html/vendor/magento/module-checkout/Model/ShippingInformationManagement.php(156): Magento\Quote\Model\QuoteRepository->save(Object(Magento\Quote\Model\Quote))
#7 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Checkout\Model\ShippingInformationManagement->saveAddressInformation('71', Object(Magento\Checkout\Model\ShippingInformation))
#8 /var/www/html/var/generation/Magento/Checkout/Model/ShippingInformationManagement/Interceptor.php(26): Magento\Checkout\Model\ShippingInformationManagement\Interceptor->___callPlugins('saveAddressInfo...', Array, Array)
#9 /var/www/html/vendor/magento/module-checkout/Model/GuestShippingInformationManagement.php(45): Magento\Checkout\Model\ShippingInformationManagement\Interceptor->saveAddressInformation('71', Object(Magento\Checkout\Model\ShippingInformation))
#10 [internal function]: Magento\Checkout\Model\GuestShippingInformationManagement->saveAddressInformation('35a2c05016bbdc8...', Object(Magento\Checkout\Model\ShippingInformation))
#11 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#13 /var/www/html/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /var/www/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#16 /var/www/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#17 {main} [] []

2. screenshot:  
![figure1](https://user-images.githubusercontent.com/8605399/38164493-eb393d88-3505-11e8-994d-a183518e254d.png)

**Comment by ghost** [comment]
Hi @mimdev can you provide more information about your scenarios steps ? I cannot reproduce by yours scenarios steps.

**Comment by ghost** [comment]
@mimdev , we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
