### ISSUE TITLE
Apache error when any product page(s) is accessed or reloaded when under Specific Apache setup

### ISSUE THREAD

**Issue by GlobalOutsourcing** [magento/magento2#14650]
### Preconditions
1. Magento 2.2.3 (Developer Mode) Magento Ultimo, custom child theme
2. CPU | Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 core(s))
3. Plesk Onyx v17.5.3_build1705170317.16
4. OS | CentOS Linux 7.4.1708 (Core)
5. PHP version 7.1.16  - Run PHP as FastCGI application served by Apache
6. MySQL  Ver 15.1 Distrib 10.1.32-MariaDB, for Linux (x86_64) using readline 5.1

### Steps to reproduce
1. Ensure Magento 2.2.3 is running under PHP version 7.1.16  with PHP as FastCGI application served by Apache
2. Navigate to the Apache error.log location on the server
3. Navigate to any product page on frontend
4. Refresh the Apache error.log location and open the log and check last logged errors
5. Errors show for the product page in logs as follows:

`mod_fcgid: stderr: PHP Fatal error: Uncaught Error: Call to a member function getId() on null in MYSERVER/vendor/magento/module-review/Block/Product/View.php:131, referer: https://MYSITE.COM/MYPRODUCTPAGE.html					

mod_fcgid: stderr: Stack trace:, referer: https://MYSITE.COM/MYPRODUCTPAGE.html					

mod_fcgid: stderr: #0 MYSERVER/generated/code/Magento/Review/Block/Product/View/ListView/Interceptor.php(63): Magento\\Review\\Block\\Product\\View->getReviewsCollection(), referer: https://MYSITE.COM/MYPRODUCTPAGE.html					

mod_fcgid: stderr: #1 MYSERVER/vendor/magento/module-review/Block/Product/View/ListView.php(44): Magento\\Review\\Block\\Product\\View\\ListView\\Interceptor->getReviewsCollection(), referer: https://MYSITE.COM/MYPRODUCTPAGE.html					

mod_fcgid: stderr: #2 
MYSERVER/vendor/magento/framework/View/Element/AbstractBlock.php(272): Magento\\Review\\Block\\Product\\View\\ListView->_prepareLayout(), referer: https://MYSITE.COM/MYPRODUCTPAGE.html					

mod_fcgid: stderr: #3 MYSERVER/generated/code/Magento/Review/Block/Product/View/ListView/Interceptor.php(674): Magento\\Framework\\View\\Element\\AbstractBlock->setLayout(Object(Magento\\Framework\\View\\Layout\\Interceptor)), referer: https://MYSITE.COM/MYPRODUCTPAGE.html					 

mod_fcgid: stderr: #4 
MYSERVER/vendor/magento/framework/View/Layout/Generator/Block.php(150):  MYSERVER/vendor/magento/module-review/Block/Product/View.php on line 131, referer: https://MYSITE.COM/MYPRODUCTPAGE.html					

(32)Broken pipe: mod_fcgid: ap_pass_brigade failed in handle_request_ipc function`

6. No errors are logged at the frontend/browser side of Magento 2, only in Apache error log (See 2. Further digging, I found the following post:  in "This may be a platform independent comment" section at the end of this issue for additional information about this)

### Expected result
1. Magento 2.2.3 is running under PHP version 7.1.16  with PHP as FastCGI application served by Apache
2. Navigate to any product page or refresh any product page
3. Apache error log does not throw errors as above 

### Actual result
1. When running Magento 2.2.3 under PHP version 7.1.16  with PHP as FastCGI application served by Apache mode
2. Then navigating to any product page or product page is refreshed at the frontend of Magento 2.2.3
2. Apache logs errors as mentioned above

I am not very technical but after researching, I have found the following information and steps to attempt and resolve this issue:

1. [https://support.plesk.com/hc/en-us/articles/213399589-Websites-are-slow-and-a-warning-appears-in-logs-mod-fcgid-ap-pass-brigade-failed](url)

I attempted both solutions provided in the above link after following the step by step guide, however, the errors still persist and were not resolved.

2. Further digging, I found the following post: 

[https://talk.plesk.com/threads/ap_pass_brigade-failed-in-handle_request_ipc-function.345955/](url)

Comments about this issue on the post above:

a) "This error can occur when asynchronous requests are used by a website. These do not directly show up as an erroneous result on a web page, but they trigger the execution of PHP scripts. If such scripts fail during their execution and do not return a result, this or similar strange errors are logged. What you need to do is to identify the JavaScript (AJAX) calls to your PHP scripts and find out why the execution of these scripts is failing."

b) "Just found this Avian’s Blog: On "ap_pass_brigade failed"

Is what hes saying true "but in the end there is nothing you can do about it on the server side. The 500 response in the log is also clearly an artifact in this case, since it's the client that caused the error, not the server, and no error page was actually delivered"

c) "clients that close the connection before waiting for the server to respond." -> "in the article is what I was referring to in my explanation. The client is indeed closing it, but it is doing so, because it does not receive a response from the AJAX call, and that again is caused by a faulty script of the website."

This article may provide more information: [https://www.tablix.org/~avian/blog/archives/2016/05/on_ap_pass_brigade_failed/](url)

Can you please let me know if this issue is due to Magento 2 because as you can see in the "Steps to reproduce 5."  errors in the Apache log, the errors are triggered for example by files in directories of Magento such as: 

`/vendor/magento/module-review/Block/Product/View.php:131`
`MYSERVER/generated/code/Magento/Review/Block/Product/View/ListView/Interceptor.php(63): Magento\\Review\\Block\\Product\\View->getReviewsCollection()`

3. I spoke to a developer and he provided this information which might be helpful also:

"It looks like a conflict that renders the page in background several times.

For instance Magento's registry registry('current_product') returns null on the product page which means something breaks this variable in Magento's registry."

Please correct me if am wrong and apologise in advance if this is not a Magento 2 error/bug, if so then let me know and will close this and will keep looking for how to resolve this.

Thanks for any help.

**Comment by ghost** [comment]
Hi @GlobalOutsourcing I'm not able to reproduce, Maybe problem in your environment ?

**Comment by ghost** [comment]
@GlobalOutsourcing , we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by hunterallen** [comment]
I receive this issue frequently in Magento 2.4. Usually from Google Bots. Did you ever find a solution?
