### ISSUE TITLE
After 2.2 command line upgrade got error code when disabling maintenance mode

### ISSUE THREAD

**Issue by flnative** [magento/magento2#14689]
### Preconditions

1. Updating 2.1 to 2.2 release via command line
2. PHP 7.0.28

### Steps to reproduce

1. Went thru series of command line updates and fixes to composer and then upgrade
2. Did this fix: "I believe I have a solution for this. When I looked in core_config_data I found that the theme_id stored for scope_id 0 was set to "NULL". This appears to be how it was stored in previous versions. I looked at the theme table and got the ID of my adminhtml theme and set that in core_config_data for scope_id 0. Now I can run setup:upgrade again."

3. Tried to take site off maintenance mode.

### Expected result

1. Working website with latest Magento update.

### Actual result

1. There has been an error processing your request
Source class "\robotsResultPage" for "robotsResultPageFactory" generation does not exist.

From the log: (I replaced domain and root name)
{"0":"Source class \"\\robotsResultPage\" for \"robotsResultPageFactory\" generation does not exist.","1":"#0 \/chroot\/home\/YYY\/replaced.com\/html\/vendor\/magento\/framework\/Code\/Generator.php(112): Magento\\Framework\\Code\\Generator->tryToLoadSourceClass('robotsResultPag...', Object(Magento\\Framework\\ObjectManager\\Code\\Generator\\Factory))\n#1 \/chroot\/home\/YYY\/replaced.com\/html\/vendor\/magento\/framework\/Code\/Generator\/Autoloader.php(35): Magento\\Framework\\Code\\Generator->generateClass('robotsResultPag...')\n#2 [internal function]: Magento\\Framework\\Code\\Generator\\Autoloader->load('robotsResultPag...')\n#3 [internal function]: spl_autoload_call('robotsResultPag...')\n#4 \/chroot\/home\/YYY\/replaced.com\/html\/vendor\/magento\/framework\/ObjectManager\/Relations\/Runtime.php(38): class_exists('robotsResultPag...')\n#5 \/chroot\/home\/YYY\/replaced.com\/html\/vendor\/magento\/framework\/Interception\/PluginList\/PluginList.php(146): Magento\\Framework\\ObjectManager\\Relations\\Runtime->has('robotsResultPag...')\n#6 \/chroot\/home\/YYY\/replaced.com\/html\/vendor\/magento\/framework\/Interception\/PluginList\/PluginList.php(317): Magento\\Framework\\Interception\\PluginList\\PluginList->_inheritPlugins('robotsResultPag...')\n#7 \/chroot\/home\/YYY\/replaced.com\/html\/vendor\/magento\/framework\/Interception\/PluginList\/PluginList.php(266): Magento\\Framework\\Interception\\PluginList\\PluginList->_loadScopedData()\n#8 \/chroot\/home\/YYY\/replaced.com\/html\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(22): Magento\\Framework\\Interception\\PluginList\\PluginList->getNext('Magento\\\\Framewo...', 'dispatch')\n#9 \/chroot\/home\/YYY\/replaced.com\/html\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/chroot\/home\/YYY\/replaced.com\/html\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#11 \/chroot\/home\/YYY\/replaced2.com\/html\/index.php(50): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#12 {main}","url":"\/","script_name":"\/index.php"}

**Comment by magento-engcom-team** [comment]
Hi @flnative Thank you for your report
Have you cleared `var/cache`, `var/page_cache`,  `generated/code` directories before upgrade? Please take a look at all required steps in this article: http://devdocs.magento.com/guides/v2.2/comp-mgr/cli/cli-upgrade.html#upgrade-cli-upgr

**Comment by magento-engcom-team** [comment]
Hi @flnative we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
