### ISSUE TITLE
You cannot define a correlation name 'company_order' more than once

### ISSUE THREAD

**Issue by julienha** [magento/magento2#14774]
In the administration, when viewing orders from a customer, an error "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later." occurred.

### Preconditions

Magento version : 2.2.3 Enterprise with b2b extension
PHP version : 7.0.23
MySQL version : 5.7.20

### Steps to reproduce

1. Create a company
2. Create a new customer and assign him to the company
3. In the store, log in with this customer and submit an order
4. In the admin, display the customer informations and open the "Orders" tab to view customer's orders

### Expected result

1. List of the customer's orders

### Actual result

1. Error "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

**Screenshot**
![customer details](https://user-images.githubusercontent.com/30929309/39000096-76b57baa-43f3-11e8-92c6-6a892a6d01a4.png)

**Stack**
```
1 exception(s):
Exception #0 (Zend_Db_Select_Exception): You cannot define a correlation name 'company_order' more than once

Exception #0 (Zend_Db_Select_Exception): You cannot define a correlation name 'company_order' more than once
#0 /var/www/dev.marsmarket.be/vendor/magento/framework/DB/Select.php(297): Zend_Db_Select->_join('left join', Array, 'main_table.enti...', Array, NULL)
#1 /var/www/dev.marsmarket.be/vendor/magento/zendframework1/library/Zend/Db/Select.php(378): Magento\Framework\DB\Select->_join('left join', Array, 'main_table.enti...', Array, NULL)
#2 /var/www/dev.marsmarket.be/vendor/magento/module-company/Plugin/Sales/Model/ResourceModel/Order/Grid/CollectionPlugin.php(32): Zend_Db_Select->joinLeft(Array, 'main_table.enti...', Array)
#3 /var/www/dev.marsmarket.be/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Company\Plugin\Sales\Model\ResourceModel\Order\Grid\CollectionPlugin->beforeLoad(Object(Magento\Sales\Model\ResourceModel\Order\Grid\Collection\Interceptor))
#4 /var/www/dev.marsmarket.be/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\ResourceModel\Order\Grid\Collection\Interceptor->Magento\Framework\Interception\{closure}()
#5 /var/www/dev.marsmarket.be/generated/code/Magento/Sales/Model/ResourceModel/Order/Grid/Collection/Interceptor.php(26): Magento\Sales\Model\ResourceModel\Order\Grid\Collection\Interceptor->___callPlugins('load', Array, Array)
#6 /var/www/dev.marsmarket.be/vendor/magento/framework/Data/Collection.php(831): Magento\Sales\Model\ResourceModel\Order\Grid\Collection\Interceptor->load()
#7 /var/www/dev.marsmarket.be/vendor/magento/module-backend/view/adminhtml/templates/widget/grid/extended.phtml(183): Magento\Framework\Data\Collection->getIterator()
#8 /var/www/dev.marsmarket.be/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/dev.ma...')
#9 /var/www/dev.marsmarket.be/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Customer\Block\Adminhtml\Edit\Tab\Orders), '/var/www/dev.ma...', Array)
#10 /var/www/dev.marsmarket.be/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/dev.ma...')
#11 /var/www/dev.marsmarket.be/vendor/magento/module-backend/Block/Template.php(124): Magento\Framework\View\Element\Template->_toHtml()
#12 /var/www/dev.marsmarket.be/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Backend\Block\Template->_toHtml()
#13 /var/www/dev.marsmarket.be/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#14 /var/www/dev.marsmarket.be/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('adminhtml.custo...')
#15 /var/www/dev.marsmarket.be/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('adminhtml.custo...')
#16 /var/www/dev.marsmarket.be/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('adminhtml.custo...')
#17 /var/www/dev.marsmarket.be/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('adminhtml.custo...', true)
#18 /var/www/dev.marsmarket.be/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('adminhtml.custo...')
#19 /var/www/dev.marsmarket.be/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#20 /var/www/dev.marsmarket.be/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#21 /var/www/dev.marsmarket.be/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#22 /var/www/dev.marsmarket.be/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#23 /var/www/dev.marsmarket.be/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#24 /var/www/dev.marsmarket.be/generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#25 /var/www/dev.marsmarket.be/vendor/magento/framework/View/Result/Layout.php(182): Magento\Framework\View\Layout\Interceptor->getOutput()
#26 /var/www/dev.marsmarket.be/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Layout->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#27 /var/www/dev.marsmarket.be/generated/code/Magento/Framework/View/Result/Layout/Interceptor.php(24): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#28 /var/www/dev.marsmarket.be/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Layout\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#29 /var/www/dev.marsmarket.be/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#30 /var/www/dev.marsmarket.be/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#31 {main}
```

**Comment by magento-engcom-team** [comment]
@julienha thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by 0franco** [comment]
Same issue here, some link to forward?

**Comment by PivitParkour94** [comment]
Is there any information for this? It would be super useful
