### ISSUE TITLE
while adding catalog/helper/image in di.xml producing this error

### ISSUE THREAD

**Issue by deepak956** [magento/magento2#14870]
magento version 2.1.5 while adding <preference for="Magento\Catalog\Helper\Image" type="I95Dev\Imageseo\Helper\Catalog\Image" /> this error has risied please guide me ranout for this issue

a:4:{i:0;s:37:"Object DOMDocument should be created.";i:1;s:11777:"#0 D:\xampp\htdocs\mages215\vendor\magento\framework\View\Element\UiComponent\Config\Reader.php(95): Magento\Framework\View\Element\UiComponent\Config\DomMerger->getDom()
#1 D:\xampp\htdocs\mages215\vendor\magento\module-ui\Model\Manager.php(258): Magento\Framework\View\Element\UiComponent\Config\Reader->read()
#2 D:\xampp\htdocs\mages215\vendor\magento\module-ui\Model\Manager.php(166): Magento\Ui\Model\Manager->prepare('minicart')
#3 D:\xampp\htdocs\mages215\vendor\magento\framework\View\Element\UiComponentFactory.php(144): Magento\Ui\Model\Manager->prepareData('minicart')
#4 D:\xampp\htdocs\mages215\vendor\magento\framework\View\Layout\Generator\UiComponent.php(125): Magento\Framework\View\Element\UiComponentFactory->create('minicart', NULL, Array)
#5 D:\xampp\htdocs\mages215\vendor\magento\framework\View\Layout\Generator\UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'minicart', Array, Object(Magento\Framework\View\Layout\Interceptor))
#6 D:\xampp\htdocs\mages215\vendor\magento\framework\View\Layout\GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#7 D:\xampp\htdocs\mages215\vendor\magento\framework\View\Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#8 D:\xampp\htdocs\mages215\var\generation\Magento\Framework\View\Layout\Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#9 D:\xampp\htdocs\mages215\vendor\magento\framework\View\Layout\Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#10 D:\xampp\htdocs\mages215\vendor\magento\framework\View\Page\Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#11 D:\xampp\htdocs\mages215\vendor\magento\framework\View\Layout\Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#12 D:\xampp\htdocs\mages215\vendor\magento\framework\View\Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#13 D:\xampp\htdocs\mages215\vendor\magento\framework\View\Layout.php(859): Magento\Framework\View\Layout->build()
#14 D:\xampp\htdocs\mages215\var\generation\Magento\Framework\View\Layout\Interceptor.php(414): Magento\Framework\View\Layout->getBlock('page_content_he...')
#15 D:\xampp\htdocs\mages215\vendor\magento\module-cms\Helper\Page.php(171): Magento\Framework\View\Layout\Interceptor->getBlock('page_content_he...')
#16 D:\xampp\htdocs\mages215\vendor\magento\module-cms\Controller\Index\Index.php(43): Magento\Cms\Helper\Page->prepareResultPage(Object(Magento\Cms\Controller\Index\Index\Interceptor), 'home')
#17 D:\xampp\htdocs\mages215\var\generation\Magento\Cms\Controller\Index\Index\Interceptor.php(24): Magento\Cms\Controller\Index\Index->execute(NULL)
#18 D:\xampp\htdocs\mages215\vendor\magento\framework\App\Action\Action.php(102): Magento\Cms\Controller\Index\Index\Interceptor->execute()
#19 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#20 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Cms\Controller\Index\Index\Interceptor->___callParent('dispatch', Array)
#21 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'customer-app-ac...')
#22 D:\xampp\htdocs\mages215\vendor\magento\module-customer\Model\App\Action\ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#23 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'contextPlugin')
#25 D:\xampp\htdocs\mages215\vendor\magento\module-store\App\Action\Plugin\Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#26 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'storeCheck')
#28 D:\xampp\htdocs\mages215\vendor\magento\module-store\App\Action\Plugin\StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#29 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'tax-app-action-...')
#31 D:\xampp\htdocs\mages215\vendor\magento\module-tax\Model\App\Action\ContextPlugin.php(91): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#32 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(67): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'weee-app-action...')
#34 D:\xampp\htdocs\mages215\vendor\magento\module-weee\Model\App\Action\ContextPlugin.php(112): Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#35 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Interceptor.php(142): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#36 D:\xampp\htdocs\mages215\var\generation\Magento\Cms\Controller\Index\Index\Interceptor.php(39): Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#37 D:\xampp\htdocs\mages215\vendor\magento\framework\App\FrontController.php(55): Magento\Cms\Controller\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#38 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#39 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#40 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#41 D:\xampp\htdocs\mages215\vendor\magento\module-store\App\FrontController\Plugin\RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#42 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#43 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#44 D:\xampp\htdocs\mages215\vendor\magento\framework\Module\Plugin\DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#45 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#46 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#47 D:\xampp\htdocs\mages215\vendor\magento\module-page-cache\Model\App\FrontController\BuiltinPlugin.php(73): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#48 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Chain\Chain.php(67): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#49 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#50 D:\xampp\htdocs\mages215\vendor\magento\module-page-cache\Model\App\FrontController\VarnishPlugin.php(55): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#51 D:\xampp\htdocs\mages215\vendor\magento\framework\Interception\Interceptor.php(142): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#52 D:\xampp\htdocs\mages215\var\generation\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#53 D:\xampp\htdocs\mages215\vendor\magento\framework\App\Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#54 D:\xampp\htdocs\mages215\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#55 D:\xampp\htdocs\mages215\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#56 {main}";s:3:"url";s:10:"/mages215/";s:11:"script_name";s:19:"/mages215/index.php";}

**Comment by magento-engcom-team** [comment]
@deepak956 thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by magento-engcom-team** [comment]
@deepak956 
we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
