### ISSUE TITLE
2.2.3 Products add have problem

### ISSUE THREAD

**Issue by kingboyno1** [magento/magento2#15117]
When I trying to add the products,It's will show the below information,Can't add any Simple and Configurable products

**Preconditions**

Magento 2.2.3 Add products
PHP 7.0.28
Glame theme

# **Steps to reproduce**

Want to add the products

E.g Add one catalogue,I'm want to upload the products in the catalogue.
But when click " Add products" No matter Simple or configurable products.

# **Expected result**

Update the products to the website:

# **Actually result:**

Fatal error: Uncaught TypeError: Argument 3 passed to Magento\Framework\View\Element\UiComponentFactory::mergeMetadataElement() must be of the type array, null given, called in /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 371 and defined in /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php:321 Stack trace: #0 /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(371): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataElement(Array, 'configurableExi...', NULL, false) #1 /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(396): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false) #2 /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(396): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false) #3 /home/justuniq/public_html/vendor/magento/framework/ in /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 321

**Comment by magento-engcom-team** [comment]
Hi @kingboyno1 
Please provide exact and clear steps to reproduce, as it is impossible to reproduce the issue with the information provided.
Thanks

**Comment by magento-engcom-team** [comment]
@kingboyno1 we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by ayasoftware** [comment]
I got the same error when I tried to edit a product. 

Fatal error: Uncaught TypeError: Argument 3 passed to Magento\Framework\View\Element\UiComponentFactory::mergeMetadataElement() must be of the type array, null given, called in /home/efurniture/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 379 and defined in /home/efurniture/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php:329 Stack trace: #0 /home/efurniture/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(379): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataElement(Array, 'configurableExi...', NULL, false) #1 /home/efurniture/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(404): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false) #2 /home/efurniture/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(404): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false) #3 /home/efurniture/public_html/vendor/magent in /home/efurniture/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 329

**Comment by Usman1493** [comment]
Facing the same issue in Magento 2.2.5. Any Solution?

**Comment by kennedyabitbol** [comment]
Please refer to this also https://github.com/magento/magento2/issues/7825#issuecomment-268759362

**Comment by Eddcapone** [comment]
I face the same problem after upgrading from Open Source to Enterprise 2.3.5-p1

**Comment by Jeeva-Rathinam** [comment]
> When I trying to add the products,It's will show the below information,Can't add any Simple and Configurable products
> 
> **Preconditions**
> 
> Magento 2.2.3 Add products
> PHP 7.0.28
> Glame theme
> 
> # **Steps to reproduce**
> Want to add the products
> 
> E.g Add one catalogue,I'm want to upload the products in the catalogue.
> But when click " Add products" No matter Simple or configurable products.
> 
> # **Expected result**
> Update the products to the website:
> 
> # **Actually result:**
> Fatal error: Uncaught TypeError: Argument 3 passed to Magento\Framework\View\Element\UiComponentFactory::mergeMetadataElement() must be of the type array, null given, called in /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 371 and defined in /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php:321 Stack trace: #0 /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(371): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataElement(Array, 'configurableExi...', NULL, false) #1 /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(396): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false) #2 /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(396): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false) #3 /home/justuniq/public_html/vendor/magento/framework/ in /home/justuniq/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 321

I am getting the same issue, could you pls help me how you solved this issue?

**Comment by Jeeva-Rathinam** [comment]
> I got the same error when I tried to edit a product.
> 
> Fatal error: Uncaught TypeError: Argument 3 passed to Magento\Framework\View\Element\UiComponentFactory::mergeMetadataElement() must be of the type array, null given, called in /home/efurniture/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 379 and defined in /home/efurniture/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php:329 Stack trace: #0 /home/efurniture/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(379): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataElement(Array, 'configurableExi...', NULL, false) #1 /home/efurniture/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(404): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false) #2 /home/efurniture/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(404): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false) #3 /home/efurniture/public_html/vendor/magent in /home/efurniture/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php on line 329

I am getting the same issue, could you pls help me how you solved this issue?

**Comment by wajahatbashir** [comment]
Hi,

I just updated Magento 2.3.0 to 2.3.5, but now i add or edit products in Admin catalog, Now I am getting error, Hpow to i'll fix this issue. anyone can help me.

1 exception(s):
Exception #0 (Exception): Notice: Undefined index: quantity in /chroot/home/ad6ab1e8/trendscasa.com/html/faksouq235/vendor/magento/framework/View/Element/UiComponentFactory.php on line 412
