### ISSUE TITLE
Running 'setup:static-content:deploy' with minification options enabled results in PHP warning

### ISSUE THREAD

**Issue by hostep** [magento/magento2#1535]
Using 1.0.0-beta

I enabled a bunch of minification & merging options for html, js & css through the backend configuration.
And now I get this error:

```
➜ php bin/magento setup:static-content:deploy
Requested languages: en_US
=== frontend -> Magento/luma -> en_US ===
PHP Warning:  Uncaught exception 'ErrorException' with message 'require_once(/home/magento2prev/apps/default/vendor/magento/framework/Code/Minifier/Adapter/Js/../../../../../../JSMin/jsmin.php): failed to open stream: No such file or directory' in /home/magento2prev/apps/default/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php:9
Stack trace:
#0 /home/magento2prev/apps/default/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php(9): Composer\Util\ErrorHandler::handle(2, 'require_once(/h...', '/home/magento2p...', 9, Array)
#1 /home/magento2prev/apps/default/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php(9): require_once()
#2 /home/magento2prev/apps/default/vendor/composer/ClassLoader.php(412): include('/home/magento2p...')
#3 /home/magento2prev/apps/default/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/home/magento2p...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Magento\\Framewo...')
#5 [internal function]: spl_autoload_call('Magento\\Framewo... in /home/magento2prev/apps/default/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php on line 9
PHP Fatal error:  main(): Failed opening required '/home/magento2prev/apps/default/vendor/magento/framework/Code/Minifier/Adapter/Js/../../../../../../JSMin/jsmin.php' (include_path='/home/magento2prev/apps/default/magento/var/generation:/home/magento2prev/apps/default/magento/lib/internal:/home/magento2prev/apps/default/magento/var/generation:/home/magento2prev/apps/default/magento/lib/internal:/home/magento2prev/apps/default/vendor/magento/zendframework1/library:/home/magento2prev/apps/default/vendor/phpunit/php-file-iterator:/home/magento2prev/apps/default/vendor/phpunit/phpunit:/home/magento2prev/apps/default/vendor/symfony/yaml:.:/usr/share/php:/usr/share/pear') in /home/magento2prev/apps/default/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php on line 9
```

It might have something to do with how I set up my composer.json, I added these lines:
```json
    "extra": {
        "magento-root-dir": "magento",
        "magento-deploystrategy": "copy"
    }
```

**UPDATE**: This is how my directory structure looks:
```
.
├── composer.json
├── composer.lock
├── composer.phar
├── magento
└── vendor
```

**Comment by mazhalai** [comment]
@hostep Can you please post the complete composer.json file?

**Comment by hostep** [comment]
Sure, here you go:

```json
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "1.0.0-beta",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "magento/product-community-edition": "1.0.0-beta",
        "magento/sample-data": "1.0.0-beta"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.0.6",
        "lib-libxml": "*",
        "ext-ctype": "*",
        "ext-gd": "*",
        "ext-spl": "*",
        "ext-dom": "*",
        "ext-simplexml": "*",
        "ext-mcrypt": "*",
        "ext-hash": "*",
        "ext-curl": "*",
        "ext-iconv": "*",
        "ext-intl": "*",
        "ext-xsl": "*",
        "ext-mbstring": "*",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "magento/lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "magento/setup/src/Magento/Setup/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "magento/dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "magento/dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "magento/dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "magento/dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "magento/dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "repositories": [
        {
            "type": "composer",
            "url": "http://packages.magento.com/"
        }
    ],
    "extra": {
        "magento-root-dir": "magento",
        "magento-deploystrategy": "copy"
    }
}
```

Not sure if it matters, but I ran composer using this command: `php composer.phar install --prefer-dist --optimize-autoloader`

**Comment by hostep** [comment]
Ok, this has something to do with the `--optimize-autoloader` flag when running composer. If I don't use that flag, everything works as it should.

Steps te reproduce:
* Create an empty database (`magento2test` in my case)
* Create a composer.json file, with this contents: https://github.com/magento/magento2-community-edition/blob/6c6258d9c77aeea0ff04c1863cb6920a71b7ff81/composer.json
* Run:
```
➜ composer install --optimize-autoloader

➜ php bin/magento setup:install --db-name=magento2test --db-user=root --db-password=*** --admin-user=admin --admin-password=admin123 --admin-firstname=Ad --admin-lastname=Min --admin-email=admin@example.com

➜ mysql -u root -p magento2test -e "INSERT INTO core_config_data (scope, scope_id, path, value) VALUES ('default', 0, 'dev/js/minify_files', 1);"

➜ php bin/magento setup:static-content:deploy
Requested languages: en_US
=== adminhtml -> Magento/backend -> en_US ===
PHP Warning:  Uncaught exception 'ErrorException' with message 'require_once(/Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/../../../../../../JSMin/jsmin.php): failed to open stream: No such file or directory' in /Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php:9
Stack trace:
#0 /Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php(9): Composer\Util\ErrorHandler::handle(2, 'require_once(/U...', '/Users/myuserna...', 9, Array)
#1 /Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php(9): require_once()
#2 /Users/myusername/Projects/magento2test/vendor/composer/ClassLoader.php(412): include('/Users/myuserna...')
#3 /Users/myusername/Projects/magento2test/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/Users/myuserna...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Magento\\Framewo...')
#5 [inte in /Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php on line 9
PHP Stack trace:
PHP   1. {main}() /Users/myusername/Projects/magento2test/bin/magento:0
PHP   2. Symfony\Component\Console\Application->run() /Users/myusername/Projects/magento2test/bin/magento:18
PHP   3. Symfony\Component\Console\Application->doRun() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   6. Magento\Setup\Console\Command\DeployStaticContentCommand->execute() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
PHP   7. Magento\Setup\Model\Deployer->deploy() /Users/myusername/Projects/magento2test/setup/src/Magento/Setup/Console/Command/DeployStaticContentCommand.php:132
PHP   8. Magento\Setup\Model\Deployer->deployFile() /Users/myusername/Projects/magento2test/setup/src/Magento/Setup/Model/Deployer.php:132
PHP   9. Magento\Framework\View\Asset\MinifyService->getAssets() /Users/myusername/Projects/magento2test/setup/src/Magento/Setup/Model/Deployer.php:278
PHP  10. Magento\Framework\View\Asset\MinifyService->getAssetDecorated() /Users/myusername/Projects/magento2test/vendor/magento/framework/View/Asset/MinifyService.php:77
PHP  11. Magento\Framework\View\Asset\MinifyService->getAdapter() /Users/myusername/Projects/magento2test/vendor/magento/framework/View/Asset/MinifyService.php:149
PHP  12. Magento\Framework\ObjectManager\ObjectManager->get() /Users/myusername/Projects/magento2test/vendor/magento/framework/View/Asset/MinifyService.php:117
PHP  13. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/ObjectManager.php:71
PHP  14. Magento\Framework\Interception\ObjectManager\Config\Developer->getInstanceType() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:72
PHP  15. Magento\Framework\Interception\Config\Config->hasPlugins() /Users/myusername/Projects/magento2test/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:39
PHP  16. Magento\Framework\Interception\Config\Config->_inheritInterception() /Users/myusername/Projects/magento2test/vendor/magento/framework/Interception/Config/Config.php:176
PHP  17. Magento\Framework\ObjectManager\Relations\Runtime->has() /Users/myusername/Projects/magento2test/vendor/magento/framework/Interception/Config/Config.php:153
PHP  18. class_exists() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
PHP  19. spl_autoload_call() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
PHP  20. Composer\Autoload\ClassLoader->loadClass() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
PHP  21. Composer\Autoload\includeFile() /Users/myusername/Projects/magento2test/vendor/composer/ClassLoader.php:301
PHP  22. include() /Users/myusername/Projects/magento2test/vendor/composer/ClassLoader.php:412

Warning: Uncaught exception 'ErrorException' with message 'require_once(/Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/../../../../../../JSMin/jsmin.php): failed to open stream: No such file or directory' in /Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php:9
Stack trace:
#0 /Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php(9): Composer\Util\ErrorHandler::handle(2, 'require_once(/U...', '/Users/myuserna...', 9, Array)
#1 /Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php(9): require_once()
#2 /Users/myusername/Projects/magento2test/vendor/composer/ClassLoader.php(412): include('/Users/myuserna...')
#3 /Users/myusername/Projects/magento2test/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/Users/myuserna...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Magento\\Framewo...')
#5 [inte in /Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php on line 9

Call Stack:
    0.0002     231640   1. {main}() /Users/myusername/Projects/magento2test/bin/magento:0
    3.2293   76847648   2. Symfony\Component\Console\Application->run() /Users/myusername/Projects/magento2test/bin/magento:18
    3.2299   76890240   3. Symfony\Component\Console\Application->doRun() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Application.php:126
    3.2301   76891160   4. Symfony\Component\Console\Application->doRunCommand() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Application.php:195
    3.2301   76891656   5. Symfony\Component\Console\Command\Command->run() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Application.php:874
    3.2304   76895416   6. Magento\Setup\Console\Command\DeployStaticContentCommand->execute() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
    4.1065   81530080   7. Magento\Setup\Model\Deployer->deploy() /Users/myusername/Projects/magento2test/setup/src/Magento/Setup/Console/Command/DeployStaticContentCommand.php:132
    5.3344   91080400   8. Magento\Setup\Model\Deployer->deployFile() /Users/myusername/Projects/magento2test/setup/src/Magento/Setup/Model/Deployer.php:132
    5.4040   92042064   9. Magento\Framework\View\Asset\MinifyService->getAssets() /Users/myusername/Projects/magento2test/setup/src/Magento/Setup/Model/Deployer.php:278
    5.4309   92706584  10. Magento\Framework\View\Asset\MinifyService->getAssetDecorated() /Users/myusername/Projects/magento2test/vendor/magento/framework/View/Asset/MinifyService.php:77
    5.4309   92707208  11. Magento\Framework\View\Asset\MinifyService->getAdapter() /Users/myusername/Projects/magento2test/vendor/magento/framework/View/Asset/MinifyService.php:149
    5.4309   92707432  12. Magento\Framework\ObjectManager\ObjectManager->get() /Users/myusername/Projects/magento2test/vendor/magento/framework/View/Asset/MinifyService.php:117
    5.4309   92707568  13. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/ObjectManager.php:71
    5.4309   92707704  14. Magento\Framework\Interception\ObjectManager\Config\Developer->getInstanceType() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:72
    5.4310   92707704  15. Magento\Framework\Interception\Config\Config->hasPlugins() /Users/myusername/Projects/magento2test/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:39
    5.4310   92707704  16. Magento\Framework\Interception\Config\Config->_inheritInterception() /Users/myusername/Projects/magento2test/vendor/magento/framework/Interception/Config/Config.php:176
    5.4310   92709232  17. Magento\Framework\ObjectManager\Relations\Runtime->has() /Users/myusername/Projects/magento2test/vendor/magento/framework/Interception/Config/Config.php:153
    5.4310   92709280  18. class_exists() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
    5.4310   92709720  19. spl_autoload_call() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
    5.4310   92709792  20. Composer\Autoload\ClassLoader->loadClass() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
    5.4310   92709792  21. Composer\Autoload\includeFile() /Users/myusername/Projects/magento2test/vendor/composer/ClassLoader.php:301
    5.4311   92715120  22. include('/Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php') /Users/myusername/Projects/magento2test/vendor/composer/ClassLoader.php:412

PHP Fatal error:  main(): Failed opening required '/Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/../../../../../../JSMin/jsmin.php' (include_path='/Users/myusername/Projects/magento2test/var/generation:/Users/myusername/Projects/magento2test/lib/internal:/Users/myusername/Projects/magento2test/var/generation:/Users/myusername/Projects/magento2test/lib/internal:/Users/myusername/Projects/magento2test/vendor/phpunit/php-file-iterator:/Users/myusername/Projects/magento2test/vendor/phpunit/phpunit:/Users/myusername/Projects/magento2test/vendor/symfony/yaml:/Users/myusername/Projects/magento2test/vendor/magento/zendframework1/library:.:') in /Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php on line 9
PHP Stack trace:
PHP   1. {main}() /Users/myusername/Projects/magento2test/bin/magento:0
PHP   2. Symfony\Component\Console\Application->run() /Users/myusername/Projects/magento2test/bin/magento:18
PHP   3. Symfony\Component\Console\Application->doRun() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   6. Magento\Setup\Console\Command\DeployStaticContentCommand->execute() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
PHP   7. Magento\Setup\Model\Deployer->deploy() /Users/myusername/Projects/magento2test/setup/src/Magento/Setup/Console/Command/DeployStaticContentCommand.php:132
PHP   8. Magento\Setup\Model\Deployer->deployFile() /Users/myusername/Projects/magento2test/setup/src/Magento/Setup/Model/Deployer.php:132
PHP   9. Magento\Framework\View\Asset\MinifyService->getAssets() /Users/myusername/Projects/magento2test/setup/src/Magento/Setup/Model/Deployer.php:278
PHP  10. Magento\Framework\View\Asset\MinifyService->getAssetDecorated() /Users/myusername/Projects/magento2test/vendor/magento/framework/View/Asset/MinifyService.php:77
PHP  11. Magento\Framework\View\Asset\MinifyService->getAdapter() /Users/myusername/Projects/magento2test/vendor/magento/framework/View/Asset/MinifyService.php:149
PHP  12. Magento\Framework\ObjectManager\ObjectManager->get() /Users/myusername/Projects/magento2test/vendor/magento/framework/View/Asset/MinifyService.php:117
PHP  13. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/ObjectManager.php:71
PHP  14. Magento\Framework\Interception\ObjectManager\Config\Developer->getInstanceType() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:72
PHP  15. Magento\Framework\Interception\Config\Config->hasPlugins() /Users/myusername/Projects/magento2test/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:39
PHP  16. Magento\Framework\Interception\Config\Config->_inheritInterception() /Users/myusername/Projects/magento2test/vendor/magento/framework/Interception/Config/Config.php:176
PHP  17. Magento\Framework\ObjectManager\Relations\Runtime->has() /Users/myusername/Projects/magento2test/vendor/magento/framework/Interception/Config/Config.php:153
PHP  18. class_exists() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
PHP  19. spl_autoload_call() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
PHP  20. Composer\Autoload\ClassLoader->loadClass() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
PHP  21. Composer\Autoload\includeFile() /Users/myusername/Projects/magento2test/vendor/composer/ClassLoader.php:301
PHP  22. include() /Users/myusername/Projects/magento2test/vendor/composer/ClassLoader.php:412

Fatal error: main(): Failed opening required '/Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/../../../../../../JSMin/jsmin.php' (include_path='/Users/myusername/Projects/magento2test/var/generation:/Users/myusername/Projects/magento2test/lib/internal:/Users/myusername/Projects/magento2test/var/generation:/Users/myusername/Projects/magento2test/lib/internal:/Users/myusername/Projects/magento2test/vendor/phpunit/php-file-iterator:/Users/myusername/Projects/magento2test/vendor/phpunit/phpunit:/Users/myusername/Projects/magento2test/vendor/symfony/yaml:/Users/myusername/Projects/magento2test/vendor/magento/zendframework1/library:.:') in /Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php on line 9

Call Stack:
    0.0002     231640   1. {main}() /Users/myusername/Projects/magento2test/bin/magento:0
    3.2293   76847648   2. Symfony\Component\Console\Application->run() /Users/myusername/Projects/magento2test/bin/magento:18
    3.2299   76890240   3. Symfony\Component\Console\Application->doRun() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Application.php:126
    3.2301   76891160   4. Symfony\Component\Console\Application->doRunCommand() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Application.php:195
    3.2301   76891656   5. Symfony\Component\Console\Command\Command->run() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Application.php:874
    3.2304   76895416   6. Magento\Setup\Console\Command\DeployStaticContentCommand->execute() /Users/myusername/Projects/magento2test/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
    4.1065   81530080   7. Magento\Setup\Model\Deployer->deploy() /Users/myusername/Projects/magento2test/setup/src/Magento/Setup/Console/Command/DeployStaticContentCommand.php:132
    5.3344   91080400   8. Magento\Setup\Model\Deployer->deployFile() /Users/myusername/Projects/magento2test/setup/src/Magento/Setup/Model/Deployer.php:132
    5.4040   92042064   9. Magento\Framework\View\Asset\MinifyService->getAssets() /Users/myusername/Projects/magento2test/setup/src/Magento/Setup/Model/Deployer.php:278
    5.4309   92706584  10. Magento\Framework\View\Asset\MinifyService->getAssetDecorated() /Users/myusername/Projects/magento2test/vendor/magento/framework/View/Asset/MinifyService.php:77
    5.4309   92707208  11. Magento\Framework\View\Asset\MinifyService->getAdapter() /Users/myusername/Projects/magento2test/vendor/magento/framework/View/Asset/MinifyService.php:149
    5.4309   92707432  12. Magento\Framework\ObjectManager\ObjectManager->get() /Users/myusername/Projects/magento2test/vendor/magento/framework/View/Asset/MinifyService.php:117
    5.4309   92707568  13. Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/ObjectManager.php:71
    5.4309   92707704  14. Magento\Framework\Interception\ObjectManager\Config\Developer->getInstanceType() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:72
    5.4310   92707704  15. Magento\Framework\Interception\Config\Config->hasPlugins() /Users/myusername/Projects/magento2test/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:39
    5.4310   92707704  16. Magento\Framework\Interception\Config\Config->_inheritInterception() /Users/myusername/Projects/magento2test/vendor/magento/framework/Interception/Config/Config.php:176
    5.4310   92709232  17. Magento\Framework\ObjectManager\Relations\Runtime->has() /Users/myusername/Projects/magento2test/vendor/magento/framework/Interception/Config/Config.php:153
    5.4310   92709280  18. class_exists() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
    5.4310   92709720  19. spl_autoload_call() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
    5.4310   92709792  20. Composer\Autoload\ClassLoader->loadClass() /Users/myusername/Projects/magento2test/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
    5.4310   92709792  21. Composer\Autoload\includeFile() /Users/myusername/Projects/magento2test/vendor/composer/ClassLoader.php:301
    5.4311   92715120  22. include('/Users/myusername/Projects/magento2test/vendor/magento/framework/Code/Minifier/Adapter/Js/Jsmin.php') /Users/myusername/Projects/magento2test/vendor/composer/ClassLoader.php:412
```

**Comment by daim2k5** [comment]
@hostep do you get still the error? If yes please reopen the issue
