### ISSUE TITLE
Setup version for module is not specified

### ISSUE THREAD

**Issue by Valentyn-Kubrak** [magento/magento2#1565]
I have the  error in beta 1.0.0. I created module from tutorial https://github.com/magento/magento2-samples/tree/master/sample-module-newpage
with own namespace. My module.xml

```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Module/etc/module.xsd">
    <module name="Tutorials_Page" schema_version="1.0.0" setup_version="1.0.0"/>
</config>
```
Error
```
a:4:{i:0;s:58:"Setup version for module 'Tutorials_Page' is not specified";i:1;s:1452:"#0 /var/www/magento2stage2/lib/internal/Magento/Framework/Module/DbVersionInfo.php(56): Magento\Framework\Module\DbVersionInfo->isModuleVersionEqual('Tutorials_Page', false)
#1 /var/www/magento2stage2/lib/internal/Magento/Framework/Module/DbVersionInfo.php(79): Magento\Framework\Module\DbVersionInfo->isSchemaUpToDate('Tutorials_Page')
#2 /var/www/magento2stage2/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(55): Magento\Framework\Module\DbVersionInfo->getDbVersionErrors()
#3 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#4 /var/www/magento2stage2/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#5 /var/www/magento2stage2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#6 /var/www/magento2stage2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /var/www/magento2stage2/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#8 /var/www/magento2stage2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#9 {main}";s:3:"url";s:7:"/admin/";s:11:"script_name";s:10:"/index.php";}
```

**Comment by Valentyn-Kubrak** [comment]
Looks like magento didn't add record in setup_module, but when I added it manually - the same error

**Comment by mazhalai** [comment]
@Valentyn-Kubrak please remove `schema_version`, it is no longer used.
