### ISSUE TITLE
When I try to change frontend theme : something went wrong while saving this configuration: Area is already set

### ISSUE THREAD

**Issue by Pruthviraj26** [magento/magento2#15651]
```
[2018-06-01 06:31:42] main.CRITICAL: Exception message: Area is already set
Trace: #0 D:\wamp64\www\cmssetup\magento2\generated\code\Magento\Email\Model\Template\Interceptor.php(284): Magento\Email\Model\AbstractTemplate->setForcedArea('design_email_he...')
#1 D:\wamp64\www\cmssetup\magento2\vendor\magento\module-theme\Model\Design\Config\Validator.php(117): Magento\Email\Model\Template\Interceptor->setForcedArea('design_email_he...')
#2 D:\wamp64\www\cmssetup\magento2\vendor\magento\module-theme\Model\Design\Config\Validator.php(68): Magento\Theme\Model\Design\Config\Validator->getTemplateText('design_email_he...', Object(Magento\Theme\Model\Data\Design\Config))
#3 D:\wamp64\www\cmssetup\magento2\vendor\magento\module-theme\Model\DesignConfigRepository.php(91): Magento\Theme\Model\Design\Config\Validator->validate(Object(Magento\Theme\Model\Data\Design\Config))
#4 D:\wamp64\www\cmssetup\magento2\vendor\magento\framework\Interception\Interceptor.php(58): Magento\Theme\Model\DesignConfigRepository->save(Object(Magento\Theme\Model\Data\Design\Config))
#5 D:\wamp64\www\cmssetup\magento2\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Theme\Model\DesignConfigRepository\Interceptor->___callParent('save', Array)
#6 D:\wamp64\www\cmssetup\magento2\vendor\magento\framework\Interception\Interceptor.php(153): Magento\Theme\Model\DesignConfigRepository\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Theme\Model\Data\Design\Config))
#7 D:\wamp64\www\cmssetup\magento2\generated\code\Magento\Theme\Model\DesignConfigRepository\Interceptor.php(39): Magento\Theme\Model\DesignConfigRepository\Interceptor->___callPlugins('save', Array, Array)
#8 D:\wamp64\www\cmssetup\magento2\vendor\magento\module-theme\Controller\Adminhtml\Design\Config\Save.php(75): Magento\Theme\Model\DesignConfigRepository\Interceptor->save(Object(Magento\Theme\Model\Data\Design\Config))
#9 D:\wamp64\www\cmssetup\magento2\generated\code\Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor.php(24): Magento\Theme\Controller\Adminhtml\Design\Config\Save->execute()
#10 D:\wamp64\www\cmssetup\magento2\vendor\magento\framework\App\Action\Action.php(107): Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor->execute()
#11 D:\wamp64\www\cmssetup\magento2\vendor\magento\module-backend\App\AbstractAction.php(229): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#12 D:\wamp64\www\cmssetup\magento2\vendor\magento\framework\Interception\Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#13 D:\wamp64\www\cmssetup\magento2\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor->___callParent('dispatch', Array)
#14 D:\wamp64\www\cmssetup\magento2\vendor\magento\module-backend\App\Action\Plugin\Authentication.php(143): Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 D:\wamp64\www\cmssetup\magento2\vendor\magento\framework\Interception\Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 D:\wamp64\www\cmssetup\magento2\vendor\magento\framework\Interception\Interceptor.php(153): Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 D:\wamp64\www\cmssetup\magento2\generated\code\Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor.php(39): Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor->___callPlugins('dispatch', Array, NULL)
#18 D:\wamp64\www\cmssetup\magento2\vendor\magento\framework\App\FrontController.php(55): Magento\Theme\Controller\Adminhtml\Design\Config\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#19 D:\wamp64\www\cmssetup\magento2\vendor\magento\framework\Interception\Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#20 D:\wamp64\www\cmssetup\magento2\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#21 D:\wamp64\www\cmssetup\magento2\vendor\magento\framework\Interception\Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#22 D:\wamp64\www\cmssetup\magento2\generated\code\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#23 D:\wamp64\www\cmssetup\magento2\vendor\magento\framework\App\Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#24 D:\wamp64\www\cmssetup\magento2\generated\code\Magento\Framework\App\Http\Interceptor.php(24): Magento\Framework\App\Http->launch()
#25 D:\wamp64\www\cmssetup\magento2\vendor\magento\framework\App\Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#26 D:\wamp64\www\cmssetup\magento2\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
```

**Comment by DanielRuf** [comment]
This will be fixed in 2.2.5 and is already fixed in the develop branch.

**Comment by DanielRuf** [comment]
See https://github.com/magento/magento2/pull/15137

**Comment by DanielRuf** [comment]
Feel free to reopen if the changes from the pull request do not fix this on your side.
