### ISSUE TITLE
ProductRepository Save with Associated Product Ids bug.

### ISSUE THREAD

**Issue by yongred** [magento/magento2#16349]
When use $product->setAssociatedProductIds($ids), and then use ProductRepository->save($product);   An exception occurs after save.

### Preconditions

1. Magento 2.3
2. PHP 7.2

### Steps to reproduce

1. Direct Inject Magento\Catalog\Api\ProductRepositoryInterface in constructor
2. create an Magento\Catalog\Model\Product object
3. $productObj->setAssociatedProductIds($ids);
4.  $this->productRepository->save($productObj);

### Expected result

1. created product with links between parent and children products without exception.

### Actual result

1. created product.
2. throws exception after save
Exception messages:
{"0":"Products \"26\" and \"23\" have the same set of attribute values.","1":"#0 \/var\/www\/html\/src\/vendor\/magento\/module-configurable-product\/Model\/Plugin\/ProductRepositorySave.php(83): Magento\\ConfigurableProduct\\Model\\Plugin\\ProductRepositorySave->validateProductLinks(Array, Array)\n#1 \/var\/www\/html\/src\/vendor\/magento\/framework\/Interception\/Interceptor.php(146): Magento\\ConfigurableProduct\\Model\\Plugin\\ProductRepositorySave->afterSave(Object(Magento\\Catalog\\Model\\ProductRepository\\Interceptor), Object(Magento\\Catalog\\Model\\Product\\Interceptor), Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#2 \/var\/www\/html\/src\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Catalog\\Model\\ProductRepository\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#3 \/var\/www\/html\/src\/generated\/code\/Magento\/Catalog\/Model\/ProductRepository\/Interceptor.php(52):

**Comment by magento-engcom-team** [comment]
Hi @yongred. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@yongred do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ananth-iyer** [comment]
It could be product ids 23 & 26 respective attribute's values are same or can you run reindex.

**Comment by yongred** [comment]
Hi, @Ananth747 no, they don't have duplicated attributes that causes that error. If I use $product->save(); no error will occur.

**Comment by Ananth747** [comment]
What is the value of attribute id 23 % 26?

**Comment by ananth-iyer** [comment]
Debug the code:
Class: `Magento\ConfigurableProduct\Model\Plugin\ProductRepositorySave`
Function: `validateProductLinks`
Line: `110`

`print_r` without `exit/die` on variable **$valueMap** and check whats the value. You should find duplicate value in this variable.

```
if (isset($valueMap[$valueKey])) {
       throw new InputException(
           __(
         'Products "%1" and "%2" have the same set of attribute values.',
         $productId,
         $valueMap[$valueKey]
        )
 );
}
```

**Comment by yongred** [comment]
actually, its due to $valueKey being always ''
`
private function validateProductLinks(array $attributeCodes, array $linkIds)
    {
        $valueMap = [];

        foreach ($linkIds as $productId) {
            $variation = $this->productFactory->create()->load($productId);
            $valueKey = '';
`

because the $extensionAttributes->getConfigurableProductOptions(); is returning empty.
Magento\ConfigurableProduct\Model\Plugin\ProductRepositorySave
 Line 70
`
        $configurableLinks = (array) $extensionAttributes->getConfigurableProductLinks();
        $configurableOptions = (array) $extensionAttributes->getConfigurableProductOptions();

        if (empty($configurableLinks) && empty($configurableOptions)) {
            return $result;
        }

        $attributeCodes = [];
        /** @var OptionInterface $configurableOption */
        foreach ($configurableOptions as $configurableOption) {
            $eavAttribute = $this->productAttributeRepository->get($configurableOption->getAttributeId());
            $attributeCode = $eavAttribute->getAttributeCode();
            $attributeCodes[] = $attributeCode;
        }
        $this->validateProductLinks($attributeCodes, $configurableLinks);
        $result->getTypeInstance()->resetConfigurableAttributes($product);

        return $result;
    }
`

**Comment by ananth-iyer** [comment]
Please check value of **$valueMap** when you save from admin side

**Comment by ghost** [comment]
@yongred, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce.

**Comment by ghost** [comment]
@yongred, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by swaibar** [comment]
I can confirm I came across this today.  It is very frustrating as my script to update products does not throw exceptions and keep going.  It fatal errors and stops for each one making a script impossible unless I hack the core code to change this to an exception.

**Comment by nopenopenope** [comment]
The issue appears in Magento 2.4.3 as well. I use this code to generate Configurable products, where the configurable attributes are always different:
```

$product = $this->collection->addAttributeToFilter('sku', ['eq' => $data['sku']])->getFirstItem();

        $product->setData([
            ProductAttributeInterface::CODE_SKU => $data['sku'],
            ProductAttributeInterface::CODE_NAME => $data['name'],
            ProductAttributeInterface::CODE_WEIGHT => $data['weight'] ?? 1,
            ProductAttributeInterface::CODE_DESCRIPTION => $data['description'],
            ProductAttributeInterface::CODE_STATUS => 1,
            ProductAttributeInterface::CODE_PRICE => 0,
            Product::ATTRIBUTE_SET_ID => 4,
            Product::VISIBILITY => 4,
            Product::TYPE_ID => Manager::TYPE_CONFIGURABLE,
            Product::STORE_ID => 1,
            'category_ids' => [3],
            'tax_class_id' => 1,
            'stock_data' => [
                'is_in_stock' => 1,
                'qty' => 0,
                'max_sale_qty' => 999,
                'min_sale_qty' => 1,
                'manage_stock' => 0,
                'use_config_manage_stock' => 0,
            ],
        ]);

        foreach ($data['custom_attributes'] as $key => $value) {
            if (in_array($key, $this->_allowedCustomAttributes)) {
                $product->setData($key, $this->creator->getValueFromCustomAttributes($key, $value));
            }
        }

        $product->setAffectConfigurableProductAttributes(4)
            ->setNewVariationsAttributeSetId(4);

        $product = $this->repository->save($product);

        if(!isset($data['configurable_attributes']) || !count($data['configurable_attributes'])) {
            $data['configurable_attributes'] = $this->_allowedCustomAttributes;
        }

        if (isset($data['configurable_attributes'])) {
            $eavIds = $this->creator->getEavIdsForCodes($data['configurable_attributes']);
            $existingIds = $product->getTypeInstance()->getConfigurableAttributesAsArray($product);
            $pos = 0;
            foreach (array_diff($eavIds, array_keys($existingIds)) as $id) {
                $attribModel = $this->creator->getAttributeFactory($id, $product);
                $attribModel->setData([
                    'attribute_id' => $id,
                    'product_id' => $product->getId(),
                    'position' => $pos++,
                ]);
                $attribModel->getResource()->save($attribModel);
            }
            
            $this->assign($product, $data);
            $indexToRenew = ['catalog_product_attribute', 'inventory'];
            foreach($indexToRenew as $indexName) {
                $indexer = $this->indexerRegistry->get($indexName);
                if(!$indexer->isScheduled()) {
                    $indexer->reindexList([$product->getId()]);
                }
            }
        }

        $product = $this->repository->save($product);

```

Inside `$data['child_products]` I pass Interceptor Classes of previously generated Simples. The simples do always have *different* attributes assigned for the Attribute that is also being passed to the configurable as being the configurable attribute (`$data['configurable_attributes']`). 

The issue does NOT occour if I save the same set of products _again_, it only happens ONCE per creation of a set of Simples + Configurables. I do renew indexes like above also on creation for simples, but IMO it should not be relevant to run re-indexing on individual product creation/updating.
