### ISSUE TITLE
Issue with compile after upgrade to 2.2.5 - Cannot instantiate abstract class of Block/Product/View

### ISSUE THREAD

**Issue by wedob13** [magento/magento2#16740]
Hello, 
i recently upgrade to **2.2.5** from **2.1.9** and the e-shop is on production mode.

When i change something in .less i proceed with the following steps ( as always ) to see my reflected changes live. 

**
- **bin/magento cache:clean ,** 
- **bin/magento cache:flush ,** 
- **bin/magento setup:upgrade,** 
- **bin/magento setup:di:compile,** 
- **bin/magento setup:static-content:deploy -f Language_Pack****

However after the update every time i run compile , when i visit a product page i get  the following error:

[12-Jul-2018 10:35:59 UTC] PHP Fatal error:  Uncaught Error: Cannot instantiate abstract class Magento\Catalog\Block\Product\View\AbstractView in /home/SITE/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111
Stack trace:
#0 /home/SITE/public_html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Catalog...', Array)
#1 /home/SITE/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Catalog...', Array)
#2 /home/SITE/public_html/vendor/magento/framework/View/Element/BlockFactory.php(45): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Catalog...', Array)
#3 /home/SITE/public_html/vendor/magento/framework/View/Layout/Generator/Block.php(269): Magento\Framework\View\Element\BlockFactory->createBlock('Magento\\Catalog...', Array)
#4 /home/SITE/public_html/vendor/magento/framework/View/Layout/Gene in /home/SITE/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111

and in order for  the product page to work i have to run setup upgrade and static content deploy right away, without compile in between! 

Any thoughts :( ?

**Comment by magento-engcom-team** [comment]
Hi @wedob13. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@wedob13 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@wedob13 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided.Please provide more detailed steps to reproduce or try to reproduce this issue ona clean installation or latest release.

**Comment by ghost** [comment]
@wedob13 , we are closing this issue due to inactivity. 
If you'd like to updateit, please reopen the issue.
