### ISSUE TITLE
Magento2 Installation Error

### ISSUE THREAD

**Issue by laupkram** [magento/magento2#1727]
I just pulled the current commits today https://github.com/magento/magento2/commit/9a960ca60ca4d6828e63f89a4a29d3f5815ab70c
and while installing I encountered the following errors 

```
Module 'Magento_Indexer':
Running recurring..
[ERROR] exception 'Exception' with message 'Recoverable Error: Argument 1 passed to Magento\Indexer\Model\Config\Data::__construct() must be an instance of Magento\Framework\Indexer\Config\Reader, instance of Magento\Indexer\Model\Config\Reader given, called in /home/magento2_dev/public_html/var/generation/Magento/Indexer/Model/Config/Data/Interceptor.php on line 14 and defined in /home/magento2_dev/public_html/app/code/Magento/Indexer/Model/Config/Data.php on line 22' in /home/magento2_dev/public_html/lib/internal/Magento/Framework/App/ErrorHandler.php:67
Stack trace:
#0 /home/magento2_dev/public_html/app/code/Magento/Indexer/Model/Config/Data.php(22): Magento\Framework\App\ErrorHandler->handler(4096, 'Argument 1 pass...', '/home/magento2...', 22, Array)
#1 /home/magento2_dev/public_html/var/generation/Magento/Indexer/Model/Config/Data/Interceptor.php(14): Magento\Indexer\Model\Config\Data->__construct(Object(Magento\Indexer\Model\Config\Reader), Object(Magento\Framework\App\Cache\Type\Config), Object(Magento\Indexer\Model\Resource\Indexer\State\Collection), 'indexer_config')
#2 /home/magento2_dev/public_html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(103): Magento\Indexer\Model\Config\Data\Interceptor->__construct(Object(Magento\Indexer\Model\Config\Reader), Object(Magento\Framework\App\Cache\Type\Config), Object(Magento\Indexer\Model\Resource\Indexer\State\Collection), 'indexer_config')
#3 /home/magento2_dev/public_html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Indexer...', Array)
#4 /home/magento2_dev/public_html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Indexer...')
#5 /home/magento2_dev/public_html/var/generation/Magento/Indexer/Model/Config/Data/Proxy.php(84): Magento\Framework\ObjectManager\ObjectManager->get('\\Magento\\Indexe...')
#6 /home/magento2_dev/public_html/var/generation/Magento/Indexer/Model/Config/Data/Proxy.php(103): Magento\Indexer\Model\Config\Data\Proxy->_getSubject()
#7 /home/magento2_dev/public_html/app/code/Magento/Indexer/Model/Config.php(32): Magento\Indexer\Model\Config\Data\Proxy->get()
#8 /home/magento2_dev/public_html/app/code/Magento/Indexer/Setup/Recurring.php(90): Magento\Indexer\Model\Config->getIndexers()
#9 /home/magento2_dev/public_html/setup/src/Magento/Setup/Model/Installer.php(789): Magento\Indexer\Setup\Recurring->install(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext))
#10 /home/magento2_dev/public_html/setup/src/Magento/Setup/Model/Installer.php(700): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema')
#11 [internal function]: Magento\Setup\Model\Installer->installSchema()
#12 /home/magento2_dev/public_html/setup/src/Magento/Setup/Model/Installer.php(299): call_user_func_array(Array, Array)
#13 /home/magento2_dev/public_html/setup/src/Magento/Setup/Controller/Install.php(88): Magento\Setup\Model\Installer->install(Array)
#14 /home/magento2_dev/public_html/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#15 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#16 /home/magento2_dev/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#17 /home/magento2_dev/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /home/magento2_dev/public_html/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /home/magento2_dev/public_html/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#20 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#21 /home/magento2_dev/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#22 /home/magento2_dev/public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#23 /home/magento2_dev/public_html/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#24 /home/magento2_dev/public_html/setup/index.php(31): Zend\Mvc\Application->run()
#25 {main}
```

I passed every requirements

my specs

Ubuntu 14.0.4
PHP 5.5.27
Apache 2.4
MySQL 5.6 (Percona)

**Comment by laupkram** [comment]
I just remove the /var/generation and it now works fine
