### ISSUE TITLE
My Orders - User Cannot View Placed Order

### ISSUE THREAD

**Issue by michelve** [magento/magento2#17804]
### Preconditions
Magento 2.2.5
PHP v7.1.20
Ubuntu 18.04.1
Porto Theme 3.1.3

### Steps to reproduce
     - User A places and order on magento. then user A goes to my account and click on My Orders menu, Then user A find and click View order link.
     - User A encouters error: Exception #0 (Exception): Notice: Undefined offset: 1 in /var/www/html/vendor/magento/module-sales/Model/Order.php on line 1205

### Expected result
![screen shot 2018-08-26 at 1 43 57 pm](https://user-images.githubusercontent.com/4137743/44631181-aa94b280-a936-11e8-942a-fb29c4041abb.png)

### Actual result
![screen shot 2018-08-26 at 1 43 41 pm](https://user-images.githubusercontent.com/4137743/44631184-ae283980-a936-11e8-80e8-dc68de8656bb.png)

### Error
```
1 exception(s):
Exception #0 (Exception): Notice: Undefined offset: 1 in /var/www/html/vendor/magento/module-sales/Model/Order.php on line 1205

Exception #0 (Exception): Notice: Undefined offset: 1 in /var/www/html/vendor/magento/module-sales/Model/Order.php on line 1205
#0 /var/www/html/vendor/magento/module-sales/Model/Order.php(1205): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined offse...', '/var/www/html/v...', 1205, Array)
#1 /var/www/html/generated/code/Magento/Sales/Model/Order/Interceptor.php(570): Magento\Sales\Model\Order->getShippingMethod(true)
#2 /var/www/html/vendor/temando/module-shipping-m2/Observer/PrepareMyOrderInfoObserver.php(70): Magento\Sales\Model\Order\Interceptor->getShippingMethod(true)
#3 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Temando\Shipping\Observer\PrepareMyOrderInfoObserver->execute(Object(Magento\Framework\Event\Observer))
#4 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Temando\Shipping\Observer\PrepareMyOrderInfoObserver), Object(Magento\Framework\Event\Observer))
#5 /var/www/html/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#6 /var/www/html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('layout_generate...', Array)
#7 /var/www/html/vendor/magento/framework/View/Layout/Builder.php(134): Magento\Framework\Event\Manager\Proxy->dispatch('layout_generate...', Array)
#8 /var/www/html/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#9 /var/www/html/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#10 /var/www/html/vendor/magento/framework/View/Layout.php(254): Magento\Framework\View\Layout\Builder->build()
#11 /var/www/html/vendor/magento/framework/View/Layout.php(876): Magento\Framework\View\Layout->build()
#12 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('customer_accoun...')
#13 /var/www/html/vendor/magento/module-sales/Controller/AbstractController/View.php(55): Magento\Framework\View\Layout\Interceptor->getBlock('customer_accoun...')
#14 /var/www/html/generated/code/Magento/Sales/Controller/Order/View/Interceptor.php(24): Magento\Sales\Controller\AbstractController\View->execute()
#15 /var/www/html/vendor/magento/framework/App/Action/Action.php(107): Magento\Sales\Controller\Order\View\Interceptor->execute()
#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Order\View\Interceptor->___callParent('dispatch', Array)
#18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Order\View\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#19 /var/www/html/generated/code/Magento/Sales/Controller/Order/View/Interceptor.php(39): Magento\Sales\Controller\Order\View\Interceptor->___callPlugins('dispatch', Array, Array)
#20 /var/www/html/vendor/magento/framework/App/FrontController.php(55): Magento\Sales\Controller\Order\View\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#23 /var/www/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /var/www/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#26 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#29 /var/www/html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#31 /var/www/html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#32 /var/www/html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#33 {main}
```

### File Order.php - on line 1205

```php
/**
     * Retrieve shipping method
     *
     * @param bool $asObject return carrier code and shipping method data as object
     * @return string|\Magento\Framework\DataObject
     */
    public function getShippingMethod($asObject = false)
    {
        $shippingMethod = parent::getShippingMethod();
        if (!$asObject) {
            return $shippingMethod;
        } else {
            list($carrierCode, $method) = explode('_', $shippingMethod, 2);
            return new \Magento\Framework\DataObject(['carrier_code' => $carrierCode, 'method' => $method]);
        }
    }
```

**Comment by magento-engcom-team** [comment]
Hi @michelve. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@michelve do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@michelve, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by ananth-iyer** [comment]
@michelve Are you using temando shipping module?

**Comment by michelve** [comment]
@Ananth747 - yes it is enabled (Temando_Shipping) but im using shipstation

**Comment by ananth-iyer** [comment]
@michelve If you don't need Temando_Shipping extension then you can disable it and test again

**Comment by ghost** [comment]
@michelve, thank you for your report.
We were not able to reproduce this issue by following the steps you provided, both with and without Temando_Shipping module. If you'd like to update issue, please reopen it.
![image](https://user-images.githubusercontent.com/40756187/45548060-9bb16980-b82b-11e8-8457-b94b16008288.png)

**Comment by digitalbricklayer** [comment]
I also have this same exception. The customer reported that their credit card details were not asked for when they placed the order. When I try to view the order in the backend an error occurs and a stack trace like the one above is created.

**Comment by p-bystritsky** [comment]
@digitalbricklayer, please provide clear and obvious steps to reproduce issue on a clean Magento 2 installation.

**Comment by CompactCodeEU** [comment]
You get this error when there is no shipping method set in the database for that order

**Comment by trajces** [comment]
I had the same issue and in my case there was a wrong convention for Shipping Method in **sales_order** table in the column **shipping_method**.
The convention should be carriercode_method (example: **custom_custom**)
