### ISSUE TITLE
DB Plaintext Password sent to browser

### ISSUE THREAD

**Issue by byronlbailey** [magento/magento2#19273]
Magento 2.2.6

When there is a connectivity problem between the Magento Process (in this case, running in Apache) and the database (in this case MySQL), the below stack trace is displayed to the end user.  As you can see, the stack trace includes the database password.  The stack trace is included below.  The desired behavior is to not show any passwords in any logs or error messages, except perhaps debug/trace logs.

```
PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/t/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:128 Stack trace: #0 /var/www/html/t/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(128): PDO->__construct('mysql:host=loca...', 'magento', 'MY_PASSWORD', Array)   <== Password is here

Rest of stack trace
#1 /var/www/html/t/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect() #2 /var/www/html/t/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(398): Zend_Db_Adapter_Pdo_Mysql->_connect() #3 /var/www/html/t/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(460): Magento\Framework\DB\Adapter\Pdo\Mysql->_connect() #4 /var/www/html/t/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `store_w...', Array) #5 /var/www/html/t/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(533): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `store_w...', Array) #6 /var/www/html/t/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(605): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `store_w...', Array) #7 /var/www/html/t/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array) #8 /var/www/html/t/vendor/magento/module-store/App/Config/Source/RuntimeConfigSource.php(87): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select)) #9 /var/www/html/t/vendor/magento/module-store/App/Config/Source/RuntimeConfigSource.php(57): Magento\Store\App\Config\Source\RuntimeConfigSource->getEntities('store_website', 'code') #10 /var/www/html/t/vendor/magento/framework/App/Config/ConfigSourceAggregated.php(40): Magento\Store\App\Config\Source\RuntimeConfigSource->get('') #11 /var/www/html/t/generated/code/Magento/Framework/App/Config/ConfigSourceAggregated/Proxy.php(95): Magento\Framework\App\Config\ConfigSourceAggregated->get('') #12 /var/www/html/t/vendor/magento/module-store/App/Config/Type/Scopes.php(63): Magento\Framework\App\Config\ConfigSourceAggregated\Proxy->get() #13 /var/www/html/t/vendor/magento/framework/App/Config.php(131): Magento\Store\App\Config\Type\Scopes->get('stores/8') #14 /var/www/html/t/vendor/magento/module-store/Model/StoreRepository.php(103): Magento\Framework\App\Config->get('scopes', 'stores/8', Array) #15 /var/www/html/t/vendor/magento/module-store/Model/StoreRepository.php(122): Magento\Store\Model\StoreRepository->getById('8') #16 /var/www/html/t/vendor/magento/module-store/Model/StoreResolver.php(171): Magento\Store\Model\StoreRepository->getActiveStoreById('8') #17 /var/www/html/t/vendor/magento/module-store/Model/StoreResolver.php(109): Magento\Store\Model\StoreResolver->getDefaultStoreById('8') #18 /var/www/html/t/vendor/magento/module-store/Model/StoreManager.php(157): Magento\Store\Model\StoreResolver->getCurrentStoreId() #19 /var/www/html/t/generated/code/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore(NULL) #20 /var/www/html/t/vendor/magento/module-store/Model/Resolver/Store.php(29): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL) #21 /var/www/html/t/vendor/magento/framework/App/Config/ScopeCodeResolver.php(49): Magento\Store\Model\Resolver\Store->getScope(NULL) #22 /var/www/html/t/vendor/magento/framework/App/Config.php(69): Magento\Framework\App\Config\ScopeCodeResolver->resolve('stores', NULL) #23 /var/www/html/t/vendor/magento/module-developer/Model/Logger/Handler/Debug.php(63): Magento\Framework\App\Config->getValue('dev/debug/debug...', 'stores') #24 /var/www/html/t/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(29): Magento\Developer\Model\Logger\Handler\Debug->isHandling(Array) #25 /var/www/html/t/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array) #26 /var/www/html/t/vendor/magento/framework/Logger/Monolog.php(48): Monolog\Logger->addRecord(400, 'SQLSTATE[HY000]...', Array) #27 /var/www/html/t/vendor/monolog/monolog/src/Monolog/Logger.php(616): Magento\Framework\Logger\Monolog->addRecord(400, 'SQLSTATE[HY000]...', Array) #28 /var/www/html/t/vendor/magento/framework/App/Bootstrap.php(262): Monolog\Logger->error('SQLSTATE[HY000]...') #29 /var/www/html/t/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #30 {main} Next Zend_Db_Adapter_Exception: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/t/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:144 Stack trace: #0 /var/www/html/t/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect() #1 /var/www/html/t/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(398): Zend_Db_Adapter_Pdo_Mysql->_connect() #2 /var/www/html/t/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(460): Magento\Framework\DB\Adapter\Pdo\Mysql->_connect() #3 /var/www/html/t/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `store_w...', Array) #4 /var/www/html/t/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(533): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `store_w...', Array) #5 /var/www/html/t/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(605): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `store_w...', Array) #6 /var/www/html/t/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array) #7 /var/www/html/t/vendor/magento/module-store/App/Config/Source/RuntimeConfigSource.php(87): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select)) #8 /var/www/html/t/vendor/magento/module-store/App/Config/Source/RuntimeConfigSource.php(57): Magento\Store\App\Config\Source\RuntimeConfigSource->getEntities('store_website', 'code') #9 /var/www/html/t/vendor/magento/framework/App/Config/ConfigSourceAggregated.php(40): Magento\Store\App\Config\Source\RuntimeConfigSource->get('') #10 /var/www/html/t/generated/code/Magento/Framework/App/Config/ConfigSourceAggregated/Proxy.php(95): Magento\Framework\App\Config\ConfigSourceAggregated->get('') #11 /var/www/html/t/vendor/magento/module-store/App/Config/Type/Scopes.php(63): Magento\Framework\App\Config\ConfigSourceAggregated\Proxy->get() #12 /var/www/html/t/vendor/magento/framework/App/Config.php(131): Magento\Store\App\Config\Type\Scopes->get('stores/8') #13 /var/www/html/t/vendor/magento/module-store/Model/StoreRepository.php(103): Magento\Framework\App\Config->get('scopes', 'stores/8', Array) #14 /var/www/html/t/vendor/magento/module-store/Model/StoreRepository.php(122): Magento\Store\Model\StoreRepository->getById('8') #15 /var/www/html/t/vendor/magento/module-store/Model/StoreResolver.php(171): Magento\Store\Model\StoreRepository->getActiveStoreById('8') #16 /var/www/html/t/vendor/magento/module-store/Model/StoreResolver.php(109): Magento\Store\Model\StoreResolver->getDefaultStoreById('8') #17 /var/www/html/t/vendor/magento/module-store/Model/StoreManager.php(157): Magento\Store\Model\StoreResolver->getCurrentStoreId() #18 /var/www/html/t/generated/code/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore(NULL) #19 /var/www/html/t/vendor/magento/module-store/Model/Resolver/Store.php(29): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL) #20 /var/www/html/t/vendor/magento/framework/App/Config/ScopeCodeResolver.php(49): Magento\Store\Model\Resolver\Store->getScope(NULL) #21 /var/www/html/t/vendor/magento/framework/App/Config.php(69): Magento\Framework\App\Config\ScopeCodeResolver->resolve('stores', NULL) #22 /var/www/html/t/vendor/magento/module-developer/Model/Logger/Handler/Debug.php(63): Magento\Framework\App\Config->getValue('dev/debug/debug...', 'stores') #23 /var/www/html/t/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(29): Magento\Developer\Model\Logger\Handler\Debug->isHandling(Array) #24 /var/www/html/t/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array) #25 /var/www/html/t/vendor/magento/framework/Logger/Monolog.php(48): Monolog\Logger->addRecord(400, 'SQLSTATE[HY000]...', Array) #26 /var/www/html/t/vendor/monolog/monolog/src/Monolog/Logger.php(616): Magento\Framework\Logger\Monolog->addRecord(400, 'SQLSTATE[HY000]...', Array) #27 /var/www/html/t/vendor/magento/framework/App/Bootstrap.php(262): Monolog\Logger->error('SQLSTATE[HY000]...') #28 /var/www/html/t/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #29 {main}
```

**Comment by magento-engcom-team** [comment]
Hi @byronlbailey. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@byronlbailey do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by DanielRuf** [comment]
> When there is a connectivity problem between the Magento Process (in this case, running in Apache) and the database (in this case MySQL), the below stack trace is displayed to the end user. As you can see, the stack trace includes the database password. The stack trace is included below. The desired behavior is to not show any passwords in any logs or error messages, except perhaps debug/trace logs.

In general: you should disable that errors are shown in production (`display_errors `).

**Comment by DanielRuf** [comment]
See https://bugs.php.net/bug.php?id=67206

**Comment by ghost** [comment]
Hi @byronlbailey  thank you for you report, this bug not related to magento, this issue related to your configurations settings.
