### ISSUE TITLE
Magento 2.2.6 update to Magento 2.3 Failed

### ISSUE THREAD

**Issue by wd7080** [magento/magento2#19483]
<b>Preconditions</b>
Magento 2.2.6
Current PHP Version: PHP 7.1.22
<b>Steps to reproduce</b>
1. Go to System > Web Setup Wizard
2. Click on system upgrades
3. Start the update process.

The update process will stop at step 2 with the below error message:
Check Component Dependency
We found conflicting component dependencies. Hide detail

Command "update" failed: Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
```
- magento/product-community-edition 2.3.0 requires magento/magento2-base 2.3.0 -> satisfiable by magento/magento2-base[2.3.0].
- Conclusion: don't install symfony/console v2.8.38
- Conclusion: don't install symfony/console v4.1.6|install symfony/console v2.8.38
- Conclusion: don't install symfony/console v4.1.7|install symfony/console v2.8.38
- Conclusion: don't install symfony/console v4.1.8|install symfony/console v2.8.38
- Conclusion: don't install symfony/console v3.4.19|install symfony/console v4.1.6|install symfony/console v4.1.7|install symfony/console v4.1.8
- Conclusion: don't install symfony/console v4.1.2|install symfony/console v2.8.38|install symfony/console v3.4.19
- Conclusion: don't install symfony/console v4.1.3|install symfony/console v2.8.38|install symfony/console v3.4.19
- Conclusion: don't install symfony/console v4.1.4|install symfony/console v2.8.38|install symfony/console v3.4.19
- Installation request for magento/product-community-edition 2.3.0 -> satisfiable by magento/product-community-edition[2.3.0].
- Conclusion: don't install symfony/console v4.1.5|install symfony/console v2.8.38|install symfony/console v3.4.19
- Installation request for sebastian/phpcpd 2.0.4 -> satisfiable by sebastian/phpcpd[2.0.4].
- Conclusion: don't install symfony/console v3.4.18|install symfony/console v4.1.2|install symfony/console v4.1.3|install symfony/console v4.1.4|install symfony/console v4.1.5|install symfony/console v4.1.6|install symfony/console v4.1.7|install symfony/console v4.1.8
- sebastian/phpcpd 2.0.4 requires symfony/console ~2.7|^3.0 -> satisfiable by symfony/console[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.40, v2.7.41, v2.7.42, v2.7.43, v2.7.44, v2.7.45, v2.7.46, v2.7.47, v2.7.48, v2.7.49, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.37, v2.8.38, v2.8.39, v2.8.4, v2.8.40, v2.8.41, v2.8.42, v2.8.43, v2.8.44, v2.8.45, v2.8.46, v2.8.47, v2.8.48, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
- Can only install one of: symfony/console[v4.1.0, v2.7.0].
- Can only install one of: symfony/console[v4.1.0, v2.7.1].
- Can only install one of: symfony/console[v4.1.0, v2.7.10].
- Can only install one of: symfony/console[v4.1.0, v2.7.11].
- Can only install one of: symfony/console[v4.1.0, v2.7.12].
- Can only install one of: symfony/console[v4.1.0, v2.7.13].
- Can only install one of: symfony/console[v4.1.0, v2.7.14].
- Can only install one of: symfony/console[v4.1.0, v2.7.15].
- Can only install one of: symfony/console[v4.1.0, v2.7.16].
- Can only install one of: symfony/console[v4.1.0, v2.7.17].
- Can only install one of: symfony/console[v4.1.0, v2.7.18].
- Can only install one of: symfony/console[v4.1.0, v2.7.19].
- Can only install one of: symfony/console[v4.1.0, v2.7.2].
- Can only install one of: symfony/console[v4.1.0, v2.7.20].
- Can only install one of: symfony/console[v4.1.0, v2.7.21].
- Can only install one of: symfony/console[v4.1.0, v2.7.22].
- Can only install one of: symfony/console[v4.1.0, v2.7.23].
- Can only install one of: symfony/console[v4.1.0, v2.7.24].
- Can only install one of: symfony/console[v4.1.0, v2.7.25].
- Can only install one of: symfony/console[v4.1.0, v2.7.26].
- Can only install one of: symfony/console[v4.1.0, v2.7.27].
- Can only install one of: symfony/console[v4.1.0, v2.7.28].
- Can only install one of: symfony/console[v4.1.0, v2.7.29].
- Can only install one of: symfony/console[v4.1.0, v2.7.3].
- Can only install one of: symfony/console[v4.1.0, v2.7.30].
- Can only install one of: symfony/console[v4.1.0, v2.7.31].
- Can only install one of: symfony/console[v4.1.0, v2.7.32].
- Can only install one of: symfony/console[v4.1.0, v2.7.33].
- Can only install one of: symfony/console[v4.1.0, v2.7.34].
- Can only install one of: symfony/console[v4.1.0, v2.7.35].
- Can only install one of: symfony/console[v4.1.0, v2.7.36].
- Can only install one of: symfony/console[v4.1.0, v2.7.37].
- Can only install one of: symfony/console[v4.1.0, v2.7.38].
- Can only install one of: symfony/console[v4.1.0, v2.7.39].
- Can only install one of: symfony/console[v4.1.0, v2.7.4].
- Can only install one of: symfony/console[v4.1.0, v2.7.40].
- Can only install one of: symfony/console[v4.1.0, v2.7.41].
- Can only install one of: symfony/console[v4.1.0, v2.7.42].
- Can only install one of: symfony/console[v4.1.0, v2.7.43].
- Can only install one of: symfony/console[v4.1.0, v2.7.44].
- Can only install one of: symfony/console[v4.1.0, v2.7.45].
- Can only install one of: symfony/console[v4.1.0, v2.7.46].
- Can only install one of: symfony/console[v4.1.0, v2.7.47].
- Can only install one of: symfony/console[v4.1.0, v2.7.48].
- Can only install one of: symfony/console[v4.1.0, v2.7.49].
- Can only install one of: symfony/console[v4.1.0, v2.7.5].
- Can only install one of: symfony/console[v4.1.0, v2.7.6].
- Can only install one of: symfony/console[v4.1.0, v2.7.7].
- Can only install one of: symfony/console[v4.1.0, v2.7.8].
- Can only install one of: symfony/console[v4.1.0, v2.7.9].
- Can only install one of: symfony/console[v4.1.0, v2.8.0].
- Can only install one of: symfony/console[v4.1.0, v2.8.1].
- Can only install one of: symfony/console[v4.1.0, v2.8.10].
- Can only install one of: symfony/console[v4.1.0, v2.8.11].
- Can only install one of: symfony/console[v4.1.0, v2.8.12].
- Can only install one of: symfony/console[v4.1.0, v2.8.13].
- Can only install one of: symfony/console[v4.1.0, v2.8.14].
- Can only install one of: symfony/console[v4.1.0, v2.8.15].
- Can only install one of: symfony/console[v4.1.0, v2.8.16].
- Can only install one of: symfony/console[v4.1.0, v2.8.17].
- Can only install one of: symfony/console[v4.1.0, v2.8.18].
- Can only install one of: symfony/console[v4.1.0, v2.8.19].
- Can only install one of: symfony/console[v4.1.0, v2.8.2].
- Can only install one of: symfony/console[v4.1.0, v2.8.20].
- Can only install one of: symfony/console[v4.1.0, v2.8.21].
- Can only install one of: symfony/console[v4.1.0, v2.8.22].
- Can only install one of: symfony/console[v4.1.0, v2.8.23].
- Can only install one of: symfony/console[v4.1.0, v2.8.24].
- Can only install one of: symfony/console[v4.1.0, v2.8.25].
- Can only install one of: symfony/console[v4.1.0, v2.8.26].
- Can only install one of: symfony/console[v4.1.0, v2.8.27].
- Can only install one of: symfony/console[v4.1.0, v2.8.28].
- Can only install one of: symfony/console[v4.1.0, v2.8.29].
- Can only install one of: symfony/console[v4.1.0, v2.8.3].
- Can only install one of: symfony/console[v4.1.0, v2.8.30].
- Can only install one of: symfony/console[v4.1.0, v2.8.31].
- Can only install one of: symfony/console[v4.1.0, v2.8.32].
- Can only install one of: symfony/console[v4.1.0, v2.8.33].
- Can only install one of: symfony/console[v4.1.0, v2.8.34].
- Can only install one of: symfony/console[v4.1.0, v2.8.35].
- Can only install one of: symfony/console[v4.1.0, v2.8.36].
- Can only install one of: symfony/console[v4.1.0, v2.8.37].
- Can only install one of: symfony/console[v4.1.0, v2.8.39].
- Can only install one of: symfony/console[v4.1.0, v2.8.4].
- Can only install one of: symfony/console[v4.1.0, v2.8.40].
- Can only install one of: symfony/console[v4.1.0, v2.8.41].
- Can only install one of: symfony/console[v4.1.0, v2.8.42].
- Can only install one of: symfony/console[v4.1.0, v2.8.43].
- Can only install one of: symfony/console[v4.1.0, v2.8.44].
- Can only install one of: symfony/console[v4.1.0, v2.8.45].
- Can only install one of: symfony/console[v4.1.0, v2.8.46].
- Can only install one of: symfony/console[v4.1.0, v2.8.47].
- Can only install one of: symfony/console[v4.1.0, v2.8.48].
- Can only install one of: symfony/console[v4.1.0, v2.8.5].
- Can only install one of: symfony/console[v4.1.0, v2.8.6].
- Can only install one of: symfony/console[v4.1.0, v2.8.7].
- Can only install one of: symfony/console[v4.1.0, v2.8.8].
- Can only install one of: symfony/console[v4.1.0, v2.8.9].
- Can only install one of: symfony/console[v4.1.0, v3.0.0].
- Can only install one of: symfony/console[v4.1.0, v3.0.1].
- Can only install one of: symfony/console[v4.1.0, v3.0.2].
- Can only install one of: symfony/console[v4.1.0, v3.0.3].
- Can only install one of: symfony/console[v4.1.0, v3.0.4].
- Can only install one of: symfony/console[v4.1.0, v3.0.5].
- Can only install one of: symfony/console[v4.1.0, v3.0.6].
- Can only install one of: symfony/console[v4.1.0, v3.0.7].
- Can only install one of: symfony/console[v4.1.0, v3.0.8].
- Can only install one of: symfony/console[v4.1.0, v3.0.9].
- Can only install one of: symfony/console[v4.1.0, v3.1.0].
- Can only install one of: symfony/console[v4.1.0, v3.1.1].
- Can only install one of: symfony/console[v4.1.0, v3.1.10].
- Can only install one of: symfony/console[v4.1.0, v3.1.2].
- Can only install one of: symfony/console[v4.1.0, v3.1.3].
- Can only install one of: symfony/console[v4.1.0, v3.1.4].
- Can only install one of: symfony/console[v4.1.0, v3.1.5].
- Can only install one of: symfony/console[v4.1.0, v3.1.6].
- Can only install one of: symfony/console[v4.1.0, v3.1.7].
- Can only install one of: symfony/console[v4.1.0, v3.1.8].
- Can only install one of: symfony/console[v4.1.0, v3.1.9].
- Can only install one of: symfony/console[v4.1.0, v3.2.0].
- Can only install one of: symfony/console[v4.1.0, v3.2.1].
- Can only install one of: symfony/console[v4.1.0, v3.2.10].
- Can only install one of: symfony/console[v4.1.0, v3.2.11].
- Can only install one of: symfony/console[v4.1.0, v3.2.12].
- Can only install one of: symfony/console[v4.1.0, v3.2.13].
- Can only install one of: symfony/console[v4.1.0, v3.2.14].
- Can only install one of: symfony/console[v4.1.0, v3.2.2].
- Can only install one of: symfony/console[v4.1.0, v3.2.3].
- Can only install one of: symfony/console[v4.1.0, v3.2.4].
- Can only install one of: symfony/console[v4.1.0, v3.2.5].
- Can only install one of: symfony/console[v4.1.0, v3.2.6].
- Can only install one of: symfony/console[v4.1.0, v3.2.7].
- Can only install one of: symfony/console[v4.1.0, v3.2.8].
- Can only install one of: symfony/console[v4.1.0, v3.2.9].
- Can only install one of: symfony/console[v4.1.0, v3.3.0].
- Can only install one of: symfony/console[v4.1.0, v3.3.1].
- Can only install one of: symfony/console[v4.1.0, v3.3.10].
- Can only install one of: symfony/console[v4.1.0, v3.3.11].
- Can only install one of: symfony/console[v4.1.0, v3.3.12].
- Can only install one of: symfony/console[v4.1.0, v3.3.13].
- Can only install one of: symfony/console[v4.1.0, v3.3.14].
- Can only install one of: symfony/console[v4.1.0, v3.3.15].
- Can only install one of: symfony/console[v4.1.0, v3.3.16].
- Can only install one of: symfony/console[v4.1.0, v3.3.17].
- Can only install one of: symfony/console[v4.1.0, v3.3.18].
- Can only install one of: symfony/console[v4.1.0, v3.3.2].
- Can only install one of: symfony/console[v4.1.0, v3.3.3].
- Can only install one of: symfony/console[v4.1.0, v3.3.4].
- Can only install one of: symfony/console[v4.1.0, v3.3.5].
- Can only install one of: symfony/console[v4.1.0, v3.3.6].
- Can only install one of: symfony/console[v4.1.0, v3.3.7].
- Can only install one of: symfony/console[v4.1.0, v3.3.8].
- Can only install one of: symfony/console[v4.1.0, v3.3.9].
- Can only install one of: symfony/console[v4.1.0, v3.4.0].
- Can only install one of: symfony/console[v4.1.0, v3.4.1].
- Can only install one of: symfony/console[v4.1.0, v3.4.10].
- Can only install one of: symfony/console[v4.1.0, v3.4.11].
- Can only install one of: symfony/console[v4.1.0, v3.4.12].
- Can only install one of: symfony/console[v4.1.0, v3.4.13].
- Can only install one of: symfony/console[v4.1.0, v3.4.14].
- Can only install one of: symfony/console[v4.1.0, v3.4.15].
- Can only install one of: symfony/console[v4.1.0, v3.4.16].
- Can only install one of: symfony/console[v4.1.0, v3.4.17].
- Can only install one of: symfony/console[v4.1.0, v3.4.2].
- Can only install one of: symfony/console[v4.1.0, v3.4.3].
- Can only install one of: symfony/console[v4.1.0, v3.4.4].
- Can only install one of: symfony/console[v4.1.0, v3.4.5].
- Can only install one of: symfony/console[v4.1.0, v3.4.6].
- Can only install one of: symfony/console[v4.1.0, v3.4.7].
- Can only install one of: symfony/console[v4.1.0, v3.4.8].
- Can only install one of: symfony/console[v4.1.0, v3.4.9].
```
<b>Fixes</b>
I run the following command:
`composer require --dev phpunit/phpunit:~6.2.0 friendsofphp/php-cs-fixer:~2.10.1 lusitanian/oauth:~0.8.10 pdepend/pdepend:2.5.2 sebastian/phpcpd:~3.0.0 squizlabs/php_codesniffer:3.2.2 --no-update`

This solved the problem and I was able to upgrade Magento to 2.3 from the backend but it created another problem:
Service Temporarily Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

I tried to run this command: 
`bin/magento setup:static-content:deploy`

I received this error on my SSH:
```
#0 /chroot/home/[MY ROOT]/vendor/zendframework/zend-servicemanager/src/Config.php(137): Zend\ServiceManager\ServiceManager->addAbstractFactory('Zend\\Mvc\\Contro...')
#1 /chroot/home/[MY ROOT]/vendor/zendframework/zend-modulemanager/src/Listener/ServiceListener.php(225): Zend\ServiceManager\Config->configureServiceManager(Object(Zend\Mvc\Controller\ControllerManager))
#2 [internal function]: Zend\ModuleManager\Listener\ServiceListener->onLoadModulesPost(Object(Zend\ModuleManager\ModuleEvent))
#3 /chroot/home[MY ROOT]/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent))
```
How can I fix this issue?

**Comment by magento-engcom-team** [comment]
Hi @wd7080. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@wd7080 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @wd7080  please look -> https://github.com/magento/magento2/issues/19446
