### ISSUE TITLE
When i try to run integration tests, i receive error 'There are no commands defined in the "cache" namespace.'

### ISSUE THREAD

**Issue by dvamst** [magento/magento2#2001]
Steps to reproduce:
```
cd dev/tests/integration
phpunit -c phpunit.xml.dist
```

Error message:

```
exception 'Exception' with message '


  [InvalidArgumentException]
  There are no commands defined in the "cache" namespace.


' in /mst/projects/magento2/src/lib/internal/Magento/Framework/Shell.php:61
Stack trace:
#0 /mst/projects/magento2/src/dev/tests/integration/framework/Magento/TestFramework/Application.php(464): Magento\Framework\Shell->execute('php -f %s cache...', Array)
#1 /mst/projects/magento2/src/dev/tests/integration/framework/bootstrap.php(74): Magento\TestFramework\Application->install()
#2 /Users/.../.composer/vendor/phpunit/phpunit/src/Util/Fileloader.php(58): include_once('/mst/projects/m...')
#3 /Users/.../.composer/vendor/phpunit/phpunit/src/Util/Fileloader.php(42): PHPUnit_Util_Fileloader::load('/mst/projects/m...')
#4 /Users/.../.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(792): PHPUnit_Util_Fileloader::checkAndLoad('/mst/projects/m...')
#5 /Users/.../.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(622): PHPUnit_TextUI_Command->handleBootstrap('/mst/projects/m...')
#6 /Users/.../.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(114): PHPUnit_TextUI_Command->handleArguments(Array)
#7 /Users/.../.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(104): PHPUnit_TextUI_Command->run(Array, true)
#8 /Users/.../.composer/vendor/phpunit/phpunit/phpunit(36): PHPUnit_TextUI_Command::main()
#9 {main}

Next exception 'Magento\Framework\Exception\LocalizedException' with message 'Command returned non-zero exit code:
`php -f '/mst/projects/magento2/src/bin/magento' cache:disable --bootstrap='MAGE_DIRS[etc][path]=/mst/projects/magento2/src/dev/tests/integration/tmp/sandbox-0-f23d6c7dcc8c9a5dc09f50ba2f96aed5/etc&MAGE_DIRS[var][path]=/mst/projects/magento2/src/dev/tests/integration/tmp/sandbox-0-f23d6c7dcc8c9a5dc09f50ba2f96aed5/var&MAGE_DIRS[media][path]=/mst/projects/magento2/src/dev/tests/integration/tmp/sandbox-0-f23d6c7dcc8c9a5dc09f50ba2f96aed5/media&MAGE_DIRS[static][path]=/mst/projects/magento2/src/dev/tests/integration/tmp/sandbox-0-f23d6c7dcc8c9a5dc09f50ba2f96aed5/pub_static&MAGE_DIRS[generation][path]=/mst/projects/magento2/src/dev/tests/integration/tmp/sandbox-0-f23d6c7dcc8c9a5dc09f50ba2f96aed5/var/generation&MAGE_DIRS[cache][path]=/mst/projects/magento2/src/dev/tests/integration/tmp/sandbox-0-f23d6c7dcc8c9a5dc09f50ba2f96aed5/var/cache&MAGE_DIRS[log][path]=/mst/projects/magento2/src/dev/tests/integration/tmp/sandbox-0-f23d6c7dcc8c9a5dc09f50ba2f96aed5/var/log&MAGE_DIRS[design][path]=/mst/projects/magento2/src/app/design&MAGE_DIRS[session][path]=/mst/projects/magento2/src/dev/tests/integration/tmp/sandbox-0-f23d6c7dcc8c9a5dc09f50ba2f96aed5/var/session&MAGE_DIRS[tmp][path]=/mst/projects/magento2/src/dev/tests/integration/tmp/sandbox-0-f23d6c7dcc8c9a5dc09f50ba2f96aed5/var/tmp&MAGE_DIRS[upload][path]=/mst/projects/magento2/src/dev/tests/integration/tmp/sandbox-0-f23d6c7dcc8c9a5dc09f50ba2f96aed5/var/upload&MAGE_MODE=developer' 2>&1`' in /mst/projects/magento2/src/lib/internal/Magento/Framework/Shell.php:62
Stack trace:
#0 /mst/projects/magento2/src/dev/tests/integration/framework/Magento/TestFramework/Application.php(464): Magento\Framework\Shell->execute('php -f %s cache...', Array)
#1 /mst/projects/magento2/src/dev/tests/integration/framework/bootstrap.php(74): Magento\TestFramework\Application->install()
#2 /Users/.../.composer/vendor/phpunit/phpunit/src/Util/Fileloader.php(58): include_once('/mst/projects/m...')
#3 /Users/.../.composer/vendor/phpunit/phpunit/src/Util/Fileloader.php(42): PHPUnit_Util_Fileloader::load('/mst/projects/m...')
#4 /Users/.../.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(792): PHPUnit_Util_Fileloader::checkAndLoad('/mst/projects/m...')
#5 /Users/.../.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(622): PHPUnit_TextUI_Command->handleBootstrap('/mst/projects/m...')
#6 /Users/.../.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(114): PHPUnit_TextUI_Command->handleArguments(Array)
#7 /Users/.../.composer/vendor/phpunit/phpunit/src/TextUI/Command.php(104): PHPUnit_TextUI_Command->run(Array, true)
#8 /Users/.../.composer/vendor/phpunit/phpunit/phpunit(36): PHPUnit_TextUI_Command::main()
#9 {main}

=== Memory Usage System Stats ===
Memory usage (OS):	16.83M (517.79% of 3.25M reported by PHP)
Estimated memory leak:	13.58M (80.69% of used memory)
```

Tested on the latest Magento develop branch.

**Comment by mazhalai** [comment]
@dvamst did you install magento before running tests? tests rely on some CLI commands to clean cache, and some CLI commands do not work unless magento is installed.

**Comment by dvamst** [comment]
Yes, i did. Magento is installed and frontend is working fine.

**Comment by mazhalai** [comment]
@dvamst Please try cleaning your  root `var` folder and the `tmp` directory inside integration tests.

**Comment by dvamst** [comment]
@mazhalai Done. Still see the same error.

**Comment by mazhalai** [comment]
@dvamst `composer install` in root? in addition to above cleaning of folders.

**Comment by dvamst** [comment]
@mazhalai yes, sure. Frontend is running fine.

**Comment by dvamst** [comment]
@mazhalai I have reinstalled magento from scratch. Now tests are working. I'll close the issue.
