### ISSUE TITLE
Custom theme requires registration.php

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#2046]
My custom theme does not show up unless I add registration.php. This is not mentioned in the video or docs.

**Comment by mazhalai** [comment]
@craigcarnell I'm told: we are working on docs intensively :)

**Comment by alankent** [comment]
Let me guess - you got a fairly new code drop?  The team just pushed some code allowing 'module in vendor' which was achieved using a registration.php script (it reports the directory the package is in).  The devs are keeping the docs team busy for sure!

**Comment by tdobbs** [comment]
@craigcarnell we're planning on updating docs for this feature by the end of this week.

**Comment by craigcarnell** [comment]
Thanks :+1:

**Comment by craigcarnell** [comment]
Latest develop branch

```
Required parameter 'theme_dir' was not passed
#0 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Design/Fallback/Rule/Theme.php(69): Magento\Framework\View\Design\Fallback\Rule\Simple->getPatternDirs(Array)
#1 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Design/FileResolution/Fallback/Resolver/Simple.php(93): Magento\Framework\View\Design\Fallback\Rule\Theme->getPatternDirs(Array)
#2 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Design/FileResolution/Fallback/Resolver/Simple.php(64): Magento\Framework\View\Design\FileResolution\Fallback\Resolver\Simple->resolveFile(Object(Magento\Framework\View\Design\Fallback\Rule\Theme), 'i18n/en_GB.csv', Array)
#3 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Design/FileResolution/Fallback/LocaleFile.php(42): Magento\Framework\View\Design\FileResolution\Fallback\Resolver\Simple->resolve('locale', 'i18n/en_GB.csv', 'frontend', Object(Magento\Theme\Model\Theme), 'en_GB', NULL)
#4 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/FileSystem.php(103): Magento\Framework\View\Design\FileResolution\Fallback\LocaleFile->getFile('frontend', Object(Magento\Theme\Model\Theme), 'en_GB', 'i18n/en_GB.csv')
#5 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Translate.php(335): Magento\Framework\View\FileSystem->getLocaleFileName('i18n/en_GB.csv', Array)
#6 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Translate.php(281): Magento\Framework\Translate->_getThemeTranslationFile('en_GB')
#7 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Translate.php(180): Magento\Framework\Translate->_loadThemeTranslation()
#8 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/App/Area.php(240): Magento\Framework\Translate->loadData(NULL, false)
#9 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/App/Area.php(211): Magento\Framework\App\Area->_initTranslate()
#10 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/App/Area.php(138): Magento\Framework\App\Area->_loadPart('translate')
#11 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/DesignLoader.php(55): Magento\Framework\App\Area->load('translate')
#12 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/App/Action/Plugin/Design.php(38): Magento\Framework\View\DesignLoader->load()
#13 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#15 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'customer-app-ac...')
#16 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#17 [internal function]: Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#19 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'contextPlugin')
#20 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Store/App/Action/Plugin/Context.php(98): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#21 [internal function]: Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#23 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'storeCheck')
#24 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#25 [internal function]: Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#27 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'weee-app-action...')
#28 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#29 [internal function]: Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#31 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Index\Index\Interceptor), Array, 'tax-app-action-...')
#32 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Tax/Model/App/Action/ContextPlugin.php(91): Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#33 [internal function]: Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Cms\Controller\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#35 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Cms/Controller/Index/Index/Interceptor.php(39): Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/App/FrontController.php(54): Magento\Cms\Controller\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#38 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#39 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#40 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#41 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Store/App/FrontController/Plugin/RequestPreprocessor.php(89): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#42 [internal function]: Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#43 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#44 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#45 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#46 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#47 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#48 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'storeCookieVali...')
#49 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Store/Model/Plugin/StoreCookie.php(78): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#50 [internal function]: Magento\Store\Model\Plugin\StoreCookie->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#51 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#52 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#53 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/PageCache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#54 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#55 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#56 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#57 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#58 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#59 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#60 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#61 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#62 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#63 /Users/ccarnell/Sites/vax-uk2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#64 {main}
```

**Comment by alankent** [comment]
You opened and closed this a few times - is it working for you now? Here is a sample registration.php file for a theme (from the blank theme): https://github.com/magento/magento2/blob/develop/app/design/frontend/Magento/blank/registration.php

If there is still a problem please let us know!

**Comment by craigcarnell** [comment]
@alankent Slight issue with my net connection, it's ok now thanks

**Comment by andidhouse** [comment]
Hi there,
when i put the registration file in the /Vendor folder then backend is not accessible any more. Anyone the same problem? Double checked data twice.

I also find it a little bit confusing that with a registration file you can take your hole backend of :-1:

**Comment by mazhalai** [comment]
@andidhouse why do you need a registration.php file in Vendor? Also please do no post on already closed issues, create a new one.
