### ISSUE TITLE
Class Magento\Catalog\Model\Resource\Category\Attribute\Collection does not exist

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#2072]
Latest develop. Do you guys even test stuff? ;)

```
Class Magento\Catalog\Model\Resource\Category\Attribute\Collection does not exist
#0 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Catalog...')
#1 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Catalog...')
#2 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Catalog...')
#3 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...', Array)
#4 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Validator/UniversalFactory.php(36): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Catalog...', Array)
#5 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Eav/Model/Config.php(386): Magento\Framework\Validator\UniversalFactory->create('Magento\\Catalog...')
#6 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Eav/Model/Config.php(430): Magento\Eav\Model\Config->_initAttributes(Object(Magento\Eav\Model\Entity\Type))
#7 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php(492): Magento\Eav\Model\Config->getAttribute('catalog_categor...', 'name')
#8 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php(476): Magento\Eav\Model\Entity\Collection\AbstractCollection->addAttributeToSelect('name', false)
#9 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Catalog/Model/ResourceModel/Category/Tree.php(398): Magento\Eav\Model\Entity\Collection\AbstractCollection->addAttributeToSelect(Array)
#10 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Catalog/Model/ResourceModel/Category/Tree.php(351): Magento\Catalog\Model\ResourceModel\Category\Tree->_getDefaultCollection(false)
#11 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Catalog/Model/ResourceModel/Category/Tree.php(174): Magento\Catalog\Model\ResourceModel\Category\Tree->getCollection(false)
#12 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Catalog/Model/ResourceModel/Category.php(634): Magento\Catalog\Model\ResourceModel\Category\Tree->addCollectionData(NULL, false, '4', true, true)
#13 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Catalog/Model/ResourceModel/Category/Interceptor.php(193): Magento\Catalog\Model\ResourceModel\Category->getCategories('4', 0, false, false, true)
#14 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Catalog/Model/Category.php(947): Magento\Catalog\Model\ResourceModel\Category\Interceptor->getCategories('4', 0, false, false, true)
#15 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Catalog/Model/Category/Interceptor.php(466): Magento\Catalog\Model\Category->getCategories('4', 0, false, false, true)
#16 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Catalog/Helper/Category.php(115): Magento\Catalog\Model\Category\Interceptor->getCategories('4', 0, false, false, true)
#17 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Catalog/Observer/AddCatalogToTopmenuItemsObserver.php(54): Magento\Catalog\Helper\Category->getStoreCategories()
#18 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(76): Magento\Catalog\Observer\AddCatalogToTopmenuItemsObserver->execute(Object(Magento\Framework\Event\Observer))
#19 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Catalog\Observer\AddCatalogToTopmenuItemsObserver), 'execute', Object(Magento\Framework\Event\Observer))
#20 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#21 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('page_block_html...', Array)
#22 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Theme/Block/Html/Topmenu.php(74): Magento\Framework\Event\Manager\Proxy->dispatch('page_block_html...', Array)
#23 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Theme/view/frontend/templates/html/topmenu.phtml(18): Magento\Theme\Block\Html\Topmenu->getHtml('level-top', 'submenu', 0)
#24 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/Users/ccarnell...')
#25 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Theme\Block\Html\Topmenu), '/Users/ccarnell...', Array)
#26 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Element/Template.php(275): Magento\Framework\View\Element\Template->fetchView('/Users/ccarnell...')
#27 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(652): Magento\Framework\View\Element\Template->_toHtml()
#28 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#29 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('catalog.topnav')
#30 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('catalog.topnav')
#31 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('catalog.topnav')
#32 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('catalog.topnav', true)
#33 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(496): Magento\Framework\View\Layout\Interceptor->renderElement('catalog.topnav', true)
#34 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Theme/view/frontend/templates/html/container.phtml(10): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#35 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/Users/ccarnell...')
#36 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Framework\View\Element\Template), '/Users/ccarnell...', Array)
#37 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Element/Template.php(275): Magento\Framework\View\Element\Template->fetchView('/Users/ccarnell...')
#38 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(652): Magento\Framework\View\Element\Template->_toHtml()
#39 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#40 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('store.menu')
#41 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('store.menu')
#42 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('store.menu')
#43 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('store.menu', true)
#44 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/Theme/view/frontend/templates/html/sections.phtml(26): Magento\Framework\View\Layout\Interceptor->renderElement('store.menu')
#45 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/Users/ccarnell...')
#46 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Framework\View\Element\Template), '/Users/ccarnell...', Array)
#47 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Element/Template.php(275): Magento\Framework\View\Element\Template->fetchView('/Users/ccarnell...')
#48 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(652): Magento\Framework\View\Element\Template->_toHtml()
#49 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#50 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('navigation.sect...')
#51 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('navigation.sect...')
#52 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('navigation.sect...')
#53 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('navigation.sect...', true)
#54 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('navigation.sect...')
#55 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.top')
#56 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.top')
#57 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.top')
#58 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.top', true)
#59 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.top')
#60 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#61 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#62 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#63 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#64 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#65 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#66 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#67 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#68 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#69 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#70 [internal function]: Magento\Framework\View\Layout->getOutput()
#71 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Interceptor.php(144): call_user_func_array(Array, Array)
#72 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#73 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#74 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#75 [internal function]: Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#76 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#77 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#78 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#79 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/PageCache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#80 [internal function]: Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#81 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#82 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#83 /Users/ccarnell/Sites/vax-uk2/app/code/Magento/PageCache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#84 [internal function]: Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#85 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#86 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#87 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/App/Http.php(119): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#88 /Users/ccarnell/Sites/vax-uk2/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#89 /Users/ccarnell/Sites/vax-uk2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#90 {main}
```

**Comment by orlangur** [comment]
In order to achieve PHP7 strict compatibility `Resource` occurrences as part of namespace were replaced with `ResourceModel`.

`git grep -i 'Magento\\Catalog\\Model\\Resource\\Category\\Attribute\\Collection'` shows there are no occurrences of class you mentioned in code.

But, `git grep -i 'Magento\\Catalog\\Model\\ResourceModel\\Category\\Attribute\\Collection'
app/code/Magento/Catalog/Setup/CategorySetup.php:                'entity_attribute_collection' => 'Magento\Catalog\Model\ResourceModel\Category\Attribute\Collection',` reveals the problem: as class name was replaced directly in install script, you need to clean up database and re-install.

Of course, you can replace `\Resource\ -> \ResourceModel\` in database if you don't want to clean it up but it seems like there is no way currently for smooth automatic upgrade.

**Comment by dfediuk** [comment]
Looks like the Magento team does not test the code on friday's evenings. Here is the critical bug from the last friday: https://github.com/magento/magento2/issues/2007

**Comment by antonkril** [comment]
As @orlangur explained system requires re-install after the Resource renaming story. But re-install requirement is issue itself.

**Comment by dfediuk** [comment]
I do not know why is it rocket science for Magento team to do proper upgrade script so I have done it by myself: https://mage2.pro/t/130
The bug looks like an [ordinary](https://github.com/magento/magento2/issues/2007) Magento team friday's laziness.
The advice to just drop database and reinstall looks crazy too because surely there are tens of developers who have already insvested hundreds (and thousands) man-hours to their future Magento 2 stores.

**Comment by alankent** [comment]
We have upgrade scripts between officially supported releases, as we have done for years. We don't currently do this for every single GitHub push due to the overhead it creates. Grabbing the latest code from 'develop' GitHub is not recommended for production sites (and never will be). Production sites should use official releases.  After GA is out (Real Soon Now), we will move to quarterly official releases (with patches as required), so it won't be this long drought of waiting for an official stable release with proper upgrades.

And yes, I would expect the next week or two to be a little less stable as lots of different threads of work come to completion after 2 years of development. We do have automated test frameworks which must pass, but I am being realistic - things go wrong. Knowing human nature, I would expect a bit of a scramble to get "one list thing" in before we start locking things down to get stability before GA. We just got 'vendor' directory support in, but a bit close to the wire given its potential impact. (But it is just *so* nice for developers using the official release practice.)

We are discussing internally how to do release candidates. I will raise the topic of schema upgrades between release candidates in the discussion. Thanks!

**Comment by craigcarnell** [comment]
@alankent I can appreciate the code changing frequently, but it seems there is just issue after issue with something broken. Closing for now.

**Comment by SerhiyShkolyarenko** [comment]
@craigcarnell anyway we took this bug in progress to prevent other users reinstalling.

**Comment by SerhiyShkolyarenko** [comment]
delivered upgrade scripts.
