### ISSUE TITLE
Magento 2.3 - clean install - Unable to apply patch for Magento_InventorySales

### ISSUE THREAD

**Issue by patvdleer** [magento/magento2#21003]
Completely clean setup, new server about an hour old, installed Ubuntu 18.04, Apache 2, MySQL 5.7 and PHP 7.1. When trying to run the Magento 2.3 setup it failed.

### Preconditions (*)

1. Magento 2.3.0
```
PHP 7.1.26-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jan 11 2019 14:13:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.26-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

### Steps to reproduce (*)

1. Clean install
2. follow setup guide

### Expected result (*)

1. Install?

### Actual result (*)

![image](https://user-images.githubusercontent.com/1138136/52308703-50485500-299e-11e9-98e6-a3c388b43b9c.png)

```
Module 'Magento_InventorySales':
[ERROR] Magento\Framework\Setup\Exception: Unable to apply patch Magento\InventorySales\Setup\Patch\Schema\InitializeWebsiteDefaultSock for module Magento_InventorySales. Original exception message: No such entity. in /var/www/vhosts/[HOST_REDACTED]/httpdocs/vendor/magento/framework/Setup/Patch/PatchApplier.php:232
Stack trace:
#0 /var/www/vhosts/[HOST_REDACTED]/httpdocs/setup/src/Magento/Setup/Model/Installer.php(1000): Magento\Framework\Setup\Patch\PatchApplier->applySchemaPatch('Magento_Invento...')
#1 /var/www/vhosts/[HOST_REDACTED]/httpdocs/setup/src/Magento/Setup/Model/Installer.php(831): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema', Array)
#2 [internal function]: Magento\Setup\Model\Installer->installSchema(Array)
#3 /var/www/vhosts/[HOST_REDACTED]/httpdocs/setup/src/Magento/Setup/Model/Installer.php(367): call_user_func_array(Array, Array)
#4 /var/www/vhosts/[HOST_REDACTED]/httpdocs/setup/src/Magento/Setup/Controller/Install.php(109): Magento\Setup\Model\Installer->install(Array)
#5 /var/www/vhosts/[HOST_REDACTED]/httpdocs/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Magento\Setup\Controller\Install->startAction()
#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /var/www/vhosts/[HOST_REDACTED]/httpdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /var/www/vhosts/[HOST_REDACTED]/httpdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /var/www/vhosts/[HOST_REDACTED]/httpdocs/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#10 /var/www/vhosts/[HOST_REDACTED]/httpdocs/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /var/www/vhosts/[HOST_REDACTED]/httpdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /var/www/vhosts/[HOST_REDACTED]/httpdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/vhosts/[HOST_REDACTED]/httpdocs/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#15 /var/www/vhosts/[HOST_REDACTED]/httpdocs/setup/index.php(39): Zend\Mvc\Application->run()
#16 {main}
```

**Comment by magento-engcom-team** [comment]
Hi @patvdleer. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@patvdleer do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @patvdleer thank you for you report, please open issue here -> https://github.com/magento-engcom/msi
