### ISSUE TITLE
wrong filename on products list

### ISSUE THREAD

**Issue by arosiek** [magento/magento2#2128]
Warning: file_exists(): File name is longer than the maximum allowed path length on this platform (4096): <?xml version="1.0" encoding="UTF-8"?>  <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> <xs:element name="view"> <xs:complexType> <xs:choice maxOccurs="unbounded"> <xs:element name="vars" maxOccurs="unbounded"> <xs:complexType> <xs:sequence> <xs:element name="var" type="varType" maxOccurs="unbounded"/> </xs:sequence> <xs:attribute name="module" type="xs:string" use="required"/> </xs:complexType> <xs:unique name="varNameIdentifier"> <xs:selector xpath="var"/> <xs:field xpath="@name"/> </xs:unique> </xs:element> <xs:element name="exclude" minOccurs="0" type="excludeType"/> <xs:element name="media" minOccurs="0" type="mediaType"/> </xs:choice> </xs:complexType> <xs:unique name="varsModuleIdentifier"> <xs:selector xpath="vars"/> <xs:field xpath="@module"/> </xs:unique> </xs:element> <xs:complexType name="varType" mixed="true"> <xs:sequence minOccurs="0" maxOccurs="unbounded"> <xs:element name="var" type="varType"/> </xs:sequence> <xs:attribute name="name" type="xs:string" use="required"/> <xs:attribute name="value" type="xs:string"/> </xs:complexType> <xs:complexType name="mediaType" mixed="true"> <xs:all><xs:element name="images" type="imageType" minOccurs="0"/><xs:element name="videos" type="videoType" minOccurs="0"/></xs:all> </xs:complexType> <xs:complexType name="excludeType"> <xs:sequence> <xs:element name="item" type="itemType" maxOccurs="unbounded"/> </xs:sequence> </xs:complexType> <xs:complexType name="itemType"> <xs:simpleContent> <xs:extension base="xs:string"> <xs:attribute name="type" use="required"> <xs:simpleType> <xs:restriction base="xs:string"> <xs:enumeration value="file"/> <xs:enumeration value="directory"/> </xs:restriction> </xs:simpleType> </xs:attribute> </xs:extension> </xs:simpleContent> </xs:complexType> <xs:complexType name="imageType"> <xs:sequence> <xs:element name="image" minOccurs="1" maxOccurs="unbounded"> <xs:complexType> <xs:sequence> <xs:element name="width" type="xs:positiveInteger" minOccurs="0"/> <xs:element name="height" type="xs:positiveInteger" minOccurs="0"/> <xs:element name="constrain" type="xs:boolean" minOccurs="0"/> <xs:element name="aspect_ratio" type="xs:boolean" minOccurs="0"/> <xs:element name="frame" type="xs:boolean" minOccurs="0"/> <xs:element name="transparency" type="xs:boolean" minOccurs="0"/> <xs:element name="background" minOccurs="0"> <xs:simpleType> <xs:restriction base="xs:string"> <xs:pattern value="\[(\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\]"/> </xs:restriction> </xs:simpleType> </xs:element> </xs:sequence> <xs:attribute name="id" type="xs:string" use="required"/> <xs:attribute name="type"> <xs:simpleType> <xs:restriction base="xs:string"> <xs:enumeration value="thumbnail"/> <xs:enumeration value="small_image"/> <xs:enumeration value="image"/> <xs:enumeration value="swatch_image"/> <xs:enumeration value="swatch_thumb"/> </xs:restriction> </xs:simpleType> </xs:attribute> </xs:complexType> </xs:element> </xs:sequence> <xs:attribute name="module" type="xs:string" use="required"/> </xs:complexType> <xs:complexType name="videoType"> <xs:sequence> <xs:element name="video" minOccurs="1" maxOccurs="unbounded"> <xs:complexType> <xs:sequence> <xs:element name="play_if_base" type="xs:boolean" minOccurs="0"/> <xs:element name="show_related" type="xs:boolean" minOccurs="0"/> <xs:element name="video_auto_restart" type="xs:boolean" minOccurs="0"/> </xs:sequence> <xs:attribute name="id" type="xs:string" use="required"/> <xs:attribute name="type" use="required"> <xs:simpleType> <xs:restriction base="xs:string"> <xs:enumeration value="play_if_base"/> <xs:enumeration value="show_related"/> <xs:enumeration value="video_auto_restart"/> </xs:restriction> </xs:simpleType> </xs:attribute> </xs:complexType> </xs:element> </xs:sequence> <xs:attribute name="module" type="xs:string" use="required"/> </xs:complexType> </xs:schema> in /home/arosiek/public_html/magento_clean/magento2/lib/internal/Magento/Framework/Config/Dom.php on line 277

**Comment by orlangur** [comment]
> Warning: file_exists(): File name is longer than the maximum allowed path length on this platform (4096): 

Interesting. So, what is the platform and what is the file it trying yo check?

**Comment by alankent** [comment]
The error message almost looks like it is using the whole document contents as the file name!! Is there more of the stack trace?

**Comment by buskamuza** [comment]
Hi @arosiek ,

thanks for reporting the issue. I've created an internal ticket to investigate and fix it MAGETWO-44227

**Comment by jacquesbh** [comment]
Below the complete trace.
PHP:
```
PHP 5.6.14-1~dotdeb+7.1 (cli) (built: Oct  2 2015 02:42:28)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

Nginx : `nginx version: nginx/1.8.0`

```
Warning: file_exists(): File name is longer than the maximum allowed path length on this platform (4096): &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;!--
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
--&gt;
&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
    &lt;xs:element name=&quot;view&quot;&gt;
        &lt;xs:complexType&gt;
            &lt;xs:choice maxOccurs=&quot;unbounded&quot;&gt;
                &lt;xs:element name=&quot;vars&quot; maxOccurs=&quot;unbounded&quot;&gt;
                    &lt;xs:complexType&gt;
                        &lt;xs:sequence&gt;
                            &lt;xs:element name=&quot;var&quot; type=&quot;varType&quot; maxOccurs=&quot;unbounded&quot;/&gt;
                        &lt;/xs:sequence&gt;
                        &lt;xs:attribute name=&quot;module&quot; type=&quot;xs:string&quot; use=&quot;required&quot;/&gt;
                    &lt;/xs:complexType&gt;
                    &lt;xs:unique name=&quot;varNameIdentifier&quot;&gt;
                        &lt;xs:selector xpath=&quot;var&quot;/&gt;
                        &lt;xs:field xpath=&quot;@name&quot;/&gt;
                    &lt;/xs:unique&gt;
                &lt;/xs:element&gt;
                &lt;xs:element name=&quot;exclude&quot; minOccurs=&quot;0&quot; type=&quot;excludeType&quot;/&gt;
                &lt;xs:element name=&quot;media&quot; minOccurs=&quot;0&quot; type=&quot;mediaType&quot;/&gt;
            &lt;/xs:choice&gt;
        &lt;/xs:complexType&gt;
        &lt;xs:unique name=&quot;varsModuleIdentifier&quot;&gt;
            &lt;xs:selector xpath=&quot;vars&quot;/&gt;
            &lt;xs:field xpath=&quot;@module&quot;/&gt;
        &lt;/xs:unique&gt;
    &lt;/xs:element&gt;
    &lt;xs:complexType name=&quot;varType&quot; mixed=&quot;true&quot;&gt;
        &lt;xs:sequence minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
            &lt;xs:element name=&quot;var&quot; type=&quot;varType&quot;/&gt;
        &lt;/xs:sequence&gt;
        &lt;xs:attribute name=&quot;name&quot; type=&quot;xs:string&quot; use=&quot;required&quot;/&gt;
        &lt;xs:attribute name=&quot;value&quot; type=&quot;xs:string&quot;/&gt;
    &lt;/xs:complexType&gt;
    &lt;xs:complexType name=&quot;mediaType&quot; mixed=&quot;true&quot;&gt;
        &lt;xs:all&gt;&lt;xs:element name=&quot;images&quot; type=&quot;imageType&quot; minOccurs=&quot;0&quot;/&gt;&lt;xs:element name=&quot;videos&quot; type=&quot;videoType&quot; minOccurs=&quot;0&quot;/&gt;&lt;/xs:all&gt;
    &lt;/xs:complexType&gt;
    &lt;xs:complexType name=&quot;excludeType&quot;&gt;
        &lt;xs:sequence&gt;
            &lt;xs:element name=&quot;item&quot; type=&quot;itemType&quot; maxOccurs=&quot;unbounded&quot;/&gt;
        &lt;/xs:sequence&gt;
    &lt;/xs:complexType&gt;
    &lt;xs:complexType name=&quot;itemType&quot;&gt;
        &lt;xs:simpleContent&gt;
            &lt;xs:extension base=&quot;xs:string&quot;&gt;
                &lt;xs:attribute name=&quot;type&quot; use=&quot;required&quot;&gt;
                    &lt;xs:simpleType&gt;
                        &lt;xs:restriction base=&quot;xs:string&quot;&gt;
                            &lt;xs:enumeration value=&quot;file&quot;/&gt;
                            &lt;xs:enumeration value=&quot;directory&quot;/&gt;
                        &lt;/xs:restriction&gt;
                    &lt;/xs:simpleType&gt;
                &lt;/xs:attribute&gt;
            &lt;/xs:extension&gt;
        &lt;/xs:simpleContent&gt;
    &lt;/xs:complexType&gt;

    

    &lt;xs:complexType name=&quot;imageType&quot;&gt;
        &lt;xs:sequence&gt;
            &lt;xs:element name=&quot;image&quot; minOccurs=&quot;1&quot; maxOccurs=&quot;unbounded&quot;&gt;
                &lt;xs:complexType&gt;
                    &lt;xs:sequence&gt;
                        &lt;xs:element name=&quot;width&quot; type=&quot;xs:positiveInteger&quot; minOccurs=&quot;0&quot;/&gt;
                        &lt;xs:element name=&quot;height&quot; type=&quot;xs:positiveInteger&quot; minOccurs=&quot;0&quot;/&gt;
                        &lt;xs:element name=&quot;constrain&quot; type=&quot;xs:boolean&quot; minOccurs=&quot;0&quot;/&gt;
                        &lt;xs:element name=&quot;aspect_ratio&quot; type=&quot;xs:boolean&quot; minOccurs=&quot;0&quot;/&gt;
                        &lt;xs:element name=&quot;frame&quot; type=&quot;xs:boolean&quot; minOccurs=&quot;0&quot;/&gt;
                        &lt;xs:element name=&quot;transparency&quot; type=&quot;xs:boolean&quot; minOccurs=&quot;0&quot;/&gt;
                        &lt;xs:element name=&quot;background&quot; minOccurs=&quot;0&quot;&gt;
                            &lt;xs:simpleType&gt;
                                &lt;xs:restriction base=&quot;xs:string&quot;&gt;
                                    &lt;xs:pattern value=&quot;\[(\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\]&quot;/&gt;
                                &lt;/xs:restriction&gt;
                            &lt;/xs:simpleType&gt;
                        &lt;/xs:element&gt;
                    &lt;/xs:sequence&gt;
                    &lt;xs:attribute name=&quot;id&quot; type=&quot;xs:string&quot; use=&quot;required&quot;/&gt;
                    &lt;xs:attribute name=&quot;type&quot;&gt;
                        &lt;xs:simpleType&gt;
                            &lt;xs:restriction base=&quot;xs:string&quot;&gt;
                                &lt;xs:enumeration value=&quot;thumbnail&quot;/&gt;
                                &lt;xs:enumeration value=&quot;small_image&quot;/&gt;
                                &lt;xs:enumeration value=&quot;image&quot;/&gt;
                                &lt;xs:enumeration value=&quot;swatch_image&quot;/&gt;
                                &lt;xs:enumeration value=&quot;swatch_thumb&quot;/&gt;
                            &lt;/xs:restriction&gt;
                        &lt;/xs:simpleType&gt;
                    &lt;/xs:attribute&gt;
                &lt;/xs:complexType&gt;
            &lt;/xs:element&gt;
        &lt;/xs:sequence&gt;
        &lt;xs:attribute name=&quot;module&quot; type=&quot;xs:string&quot; use=&quot;required&quot;/&gt;
    &lt;/xs:complexType&gt;

    

    &lt;xs:complexType name=&quot;videoType&quot;&gt;
        &lt;xs:sequence&gt;
            &lt;xs:element name=&quot;video&quot; minOccurs=&quot;1&quot; maxOccurs=&quot;unbounded&quot;&gt;
                &lt;xs:complexType&gt;
                    &lt;xs:sequence&gt;
                        &lt;xs:element name=&quot;play_if_base&quot; type=&quot;xs:boolean&quot; minOccurs=&quot;0&quot;/&gt;
                        &lt;xs:element name=&quot;show_related&quot; type=&quot;xs:boolean&quot; minOccurs=&quot;0&quot;/&gt;
                        &lt;xs:element name=&quot;video_auto_restart&quot; type=&quot;xs:boolean&quot; minOccurs=&quot;0&quot;/&gt;
                    &lt;/xs:sequence&gt;
                    &lt;xs:attribute name=&quot;id&quot; type=&quot;xs:string&quot; use=&quot;required&quot;/&gt;
                    &lt;xs:attribute name=&quot;type&quot; use=&quot;required&quot;&gt;
                        &lt;xs:simpleType&gt;
                            &lt;xs:restriction base=&quot;xs:string&quot;&gt;
                                &lt;xs:enumeration value=&quot;play_if_base&quot;/&gt;
                                &lt;xs:enumeration value=&quot;show_related&quot;/&gt;
                                &lt;xs:enumeration value=&quot;video_auto_restart&quot;/&gt;
                            &lt;/xs:restriction&gt;
                        &lt;/xs:simpleType&gt;
                    &lt;/xs:attribute&gt;
                &lt;/xs:complexType&gt;
            &lt;/xs:element&gt;
        &lt;/xs:sequence&gt;
        &lt;xs:attribute name=&quot;module&quot; type=&quot;xs:string&quot; use=&quot;required&quot;/&gt;
    &lt;/xs:complexType&gt;
&lt;/xs:schema&gt;
 in /vagrant/magento/lib/internal/Magento/Framework/Config/Dom.php on line 277
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'file_exists(): ...', '/vagrant/magent...', 277, Array)
#1 /vagrant/magento/lib/internal/Magento/Framework/Config/Dom.php(277): file_exists('<?xml version="...')
#2 /vagrant/magento/lib/internal/Magento/Framework/Config/Dom.php(374): Magento\Framework\Config\Dom::validateDomDocument(Object(DOMDocument), '<?xml version="...', '%message%\nLine:...')
#3 /vagrant/magento/lib/internal/Magento/Framework/Config/AbstractXml.php(99): Magento\Framework\Config\Dom->validate('<?xml version="...', NULL)
#4 /vagrant/magento/lib/internal/Magento/Framework/Config/AbstractXml.php(85): Magento\Framework\Config\AbstractXml->_performValidate()
#5 /vagrant/magento/lib/internal/Magento/Framework/Config/AbstractXml.php(38): Magento\Framework\Config\AbstractXml->_merge(Array)
#6 /vagrant/magento/lib/internal/Magento/Framework/Config/View.php(54): Magento\Framework\Config\AbstractXml->__construct(Array)
#7 /vagrant/magento/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(105): Magento\Framework\Config\View->__construct(Array, Object(Magento\Framework\View\Xsd\Reader), Object(Magento\Framework\Config\Dom\UrnResolver), Object(Magento\Framework\View\Xsd\Media\TypeDataExtractorPool), Array)
#8 /vagrant/magento/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#9 /vagrant/magento/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#10 /vagrant/magento/lib/internal/Magento/Framework/Config/ViewFactory.php(35): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#11 /vagrant/magento/lib/internal/Magento/Framework/View/Config.php(134): Magento\Framework\Config\ViewFactory->create(Array)
#12 /vagrant/magento/app/code/Magento/Catalog/Helper/Image.php(789): Magento\Framework\View\Config->getViewConfig()
#13 /vagrant/magento/app/code/Magento/Catalog/Helper/Image.php(833): Magento\Catalog\Helper\Image->getConfigView()
#14 /vagrant/magento/app/code/Magento/Checkout/Block/Cart/Sidebar.php(75): Magento\Catalog\Helper\Image->getFrame()
#15 /vagrant/magento/var/generation/Magento/Checkout/Block/Cart/Sidebar/Interceptor.php(37): Magento\Checkout\Block\Cart\Sidebar->getImageHtmlTemplate()
#16 /vagrant/magento/app/code/Magento/Checkout/Block/Cart/Sidebar.php(65): Magento\Checkout\Block\Cart\Sidebar\Interceptor->getImageHtmlTemplate()
#17 [internal function]: Magento\Checkout\Block\Cart\Sidebar->getConfig()
#18 /vagrant/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(144): call_user_func_array(Array, Array)
#19 /vagrant/magento/var/generation/Magento/Checkout/Block/Cart/Sidebar/Interceptor.php(26): Magento\Checkout\Block\Cart\Sidebar\Interceptor->___callPlugins('getConfig', Array, Array)
#20 /vagrant/magento/app/code/Magento/Checkout/view/frontend/templates/cart/minicart.phtml(45): Magento\Checkout\Block\Cart\Sidebar\Interceptor->getConfig()
#21 /vagrant/magento/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/vagrant/magent...')
#22 /vagrant/magento/lib/internal/Magento/Framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Cart\Sidebar\Interceptor), '/vagrant/magent...', Array)
#23 /vagrant/magento/var/generation/Magento/Checkout/Block/Cart/Sidebar/Interceptor.php(297): Magento\Framework\View\Element\Template->fetchView('/vagrant/magent...')
#24 /vagrant/magento/lib/internal/Magento/Framework/View/Element/Template.php(275): Magento\Checkout\Block\Cart\Sidebar\Interceptor->fetchView('/vagrant/magent...')
#25 /vagrant/magento/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(652): Magento\Framework\View\Element\Template->_toHtml()
#26 /vagrant/magento/var/generation/Magento/Checkout/Block/Cart/Sidebar/Interceptor.php(609): Magento\Framework\View\Element\AbstractBlock->toHtml()
#27 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(542): Magento\Checkout\Block\Cart\Sidebar\Interceptor->toHtml()
#28 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('minicart')
#29 /vagrant/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('minicart')
#30 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('minicart')
#31 /vagrant/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('minicart', true)
#32 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('minicart')
#33 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('header-wrapper')
#34 /vagrant/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('header-wrapper')
#35 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('header-wrapper')
#36 /vagrant/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('header-wrapper', true)
#37 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('header-wrapper')
#38 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('header.containe...')
#39 /vagrant/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('header.containe...')
#40 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('header.containe...')
#41 /vagrant/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('header.containe...', true)
#42 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('header.containe...')
#43 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#44 /vagrant/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#45 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#46 /vagrant/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#47 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#48 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#49 /vagrant/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#50 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#51 /vagrant/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#52 /vagrant/magento/lib/internal/Magento/Framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#53 [internal function]: Magento\Framework\View\Layout->getOutput()
#54 /vagrant/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(144): call_user_func_array(Array, Array)
#55 /vagrant/magento/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#56 /vagrant/magento/lib/internal/Magento/Framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#57 /vagrant/magento/lib/internal/Magento/Framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#58 [internal function]: Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#59 /vagrant/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#60 /vagrant/magento/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#61 /vagrant/magento/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#62 /vagrant/magento/app/code/Magento/PageCache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#63 [internal function]: Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#64 /vagrant/magento/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#65 /vagrant/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#66 /vagrant/magento/app/code/Magento/PageCache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#67 [internal function]: Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#68 /vagrant/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#69 /vagrant/magento/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#70 /vagrant/magento/lib/internal/Magento/Framework/App/Http.php(119): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#71 /vagrant/magento/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#72 /vagrant/magento/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#73 {main}
```

**Comment by jacquesbh** [comment]
The wrong commit is here: (after a long bisect)
https://github.com/magento/magento2/commit/f3a12f2e114320b3a5bdcfd1efb11aeb7ccf707e

**Comment by maghamed** [comment]
Fix for this issue delivered to mainline, could you @arosiek  please check this out whether it fixed your problem ? Thanks
