### ISSUE TITLE
Notice: Undefined index: suggestions

### ISSUE THREAD

**Issue by aario** [magento/magento2#21595]
### Preconditions (*)

1. Magento ver. 2.3.0
2. elasticsearch 5.6.15
```
{
  "name" : "DDmTWzF",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "_1X4dlvuQKiqumyfbDyazQ",
  "version" : {
    "number" : "5.6.15",
    "build_hash" : "fe7575a",
    "build_date" : "2019-02-13T16:21:45.880Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
```

### Steps to reproduce (*)
1. Configure magento 2 to use elasticsearch with all default settings
2. Search for anything
3. Reindex magento 2
4. Search for anything

### Expected result (*)

1. It should search

### Actual result (*)

1. Below error appears:
```
1 exception(s):
Exception #0 (Exception): Notice: Undefined index: suggestions in /var/www/html/app/code/Magento/Elasticsearch/Model/DataProvider/Suggestions.php on line 168

Exception #0 (Exception): Notice: Undefined index: suggestions in /var/www/html/app/code/Magento/Elasticsearch/Model/DataProvider/Suggestions.php on line 168
#0 /var/www/html/app/code/Magento/Elasticsearch/Model/DataProvider/Suggestions.php(168): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/var/www/html/a...', 168, Array)
#1 /var/www/html/app/code/Magento/Elasticsearch/Model/DataProvider/Suggestions.php(103): Magento\Elasticsearch\Model\DataProvider\Suggestions->getSuggestions(Object(Magento\Search\Model\Query))
#2 /var/www/html/app/code/Magento/AdvancedSearch/Model/SuggestedQueries.php(66): Magento\Elasticsearch\Model\DataProvider\Suggestions->getItems(Object(Magento\Search\Model\Query))
#3 /var/www/html/app/code/Magento/AdvancedSearch/Block/SearchData.php(60): Magento\AdvancedSearch\Model\SuggestedQueries->getItems(Object(Magento\Search\Model\Query))
#4 /var/www/html/app/code/Magento/AdvancedSearch/view/frontend/templates/search_data.phtml(13): Magento\AdvancedSearch\Block\SearchData->getItems()
#5 /var/www/html/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/var/www/html/a...')
#6 /var/www/html/lib/internal/Magento/Framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\AdvancedSearch\Block\Suggestions), '/var/www/html/a...', Array)
#7 /var/www/html/lib/internal/Magento/Framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template->fetchView('/var/www/html/a...')
#8 /var/www/html/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(668): Magento\Framework\View\Element\Template->_toHtml()
#9 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#10 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('search_suggesti...')
#11 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('search_suggesti...')
#12 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('search_suggesti...', false)
#13 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('additional', false)
#14 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('additional')
#15 /var/www/html/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(508): Magento\Framework\View\Layout->renderElement('additional', true)
#16 /var/www/html/app/code/Magento/CatalogSearch/Block/Result.php(115): Magento\Framework\View\Element\AbstractBlock->getChildHtml('additional')
#17 /var/www/html/app/code/Magento/CatalogSearch/view/frontend/templates/result.phtml(29): Magento\CatalogSearch\Block\Result->getAdditionalHtml()
#18 /var/www/html/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/var/www/html/a...')
#19 /var/www/html/lib/internal/Magento/Framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\CatalogSearch\Block\Result), '/var/www/html/a...', Array)
#20 /var/www/html/lib/internal/Magento/Framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template->fetchView('/var/www/html/a...')
#21 /var/www/html/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(668): Magento\Framework\View\Element\Template->_toHtml()
#22 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#23 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('search.result')
#24 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('search.result')
#25 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('search.result', false)
#26 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('content', false)
#27 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('content')
#28 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('content', false)
#29 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('main', false)
#30 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('main')
#31 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('main', false)
#32 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('columns', false)
#33 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#34 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('columns', false)
#35 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('main.content', false)
#36 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#37 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('main.content', false)
#38 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#39 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#40 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#41 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('root', false)
#42 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('root')
#43 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(954): Magento\Framework\View\Layout->renderElement('root')
#44 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#45 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#46 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#47 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(39): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#48 /var/www/html/lib/internal/Magento/Framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput()
#49 /var/www/html/lib/internal/Magento/Framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#50 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#51 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#52 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#53 /var/www/html/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(26): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#54 /var/www/html/lib/internal/Magento/Framework/App/View.php(221): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#55 /var/www/html/app/code/Magento/CatalogSearch/Controller/Result/Index.php(154): Magento\Framework\App\View->renderLayout()
#56 /var/www/html/app/code/Magento/CatalogSearch/Controller/Result/Index.php(98): Magento\CatalogSearch\Controller\Result\Index->getNotCacheableResult(Object(Magento\CatalogSearch\Helper\Data), Object(Magento\Search\Model\Query))
#57 /var/www/html/lib/internal/Magento/Framework/App/Action/Action.php(108): Magento\CatalogSearch\Controller\Result\Index->execute()
#58 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#59 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent('dispatch', Array)
#60 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#61 /var/www/html/generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php(26): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#62 /var/www/html/lib/internal/Magento/Framework/App/FrontController.php(159): Magento\CatalogSearch\Controller\Result\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#63 /var/www/html/lib/internal/Magento/Framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor))
#64 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#65 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#66 /var/www/html/app/code/Magento/Store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#67 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#68 /var/www/html/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#69 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#70 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#71 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#72 /var/www/html/lib/internal/Magento/Framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#73 /var/www/html/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#74 /var/www/html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#75 {main}
```

**Comment by magento-engcom-team** [comment]
Hi @aario. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@aario do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @aario thank you for your report, magento supports, elasticsearch2.4 5.2.x and 6.0 https://github.com/magento/magento2/pull/21458
