### ISSUE TITLE
Installation gets stuck at 59%

### ISSUE THREAD

**Issue by McPeon** [magento/magento2#21718]
Hello guys,

I'm trying to install Magento 2.3.0 with Sample Data on my Webserver. 
Everything works just fine in the setup process, until I get to the installation part.

At 59% installation it gets stuck and I get following console message:
```
Starting Magento installation:
File permissions check...

Required extensions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_Store':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Variable':

Module 'Magento_Eav':

Module 'Magento_AdminNotification':

Module 'MSP_ReCaptcha':

Module 'Magento_Config':

Module 'Magento_Indexer':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Search':

Module 'Magento_Amqp':

Module 'Magento_Security':

Module 'Magento_User':

Module 'Magento_Authorization':

Module 'Magento_Customer':

Module 'Magento_Rule':

Module 'Magento_Backup':

Module 'Magento_Cms':

Module 'Magento_Catalog':

Module 'Magento_GraphQl':

Module 'Magento_BundleImportExport':

Module 'Magento_CatalogRule':

Module 'Magento_CacheInvalidate':

Module 'Magento_Quote':

Module 'Magento_SalesSequence':

Module 'Magento_Integration':

Module 'Magento_EavGraphQl':

Module 'Magento_CatalogImportExport':

Module 'Magento_Payment':

Module 'Magento_CatalogInventory':

Module 'Magento_Cron':

Module 'Magento_Msrp':

Module 'Magento_CatalogSearch':

Module 'Magento_Sales':

Module 'Magento_Checkout':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_CatalogUrlRewriteGraphQl':

Module 'Magento_Widget':

Module 'Magento_Vault':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Paypal':

Module 'Magento_CmsGraphQl':

Module 'Magento_Downloadable':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_CmsUrlRewriteGraphQl':

Module 'MSP_TwoFactorAuth':
Installing schema... Upgrading schema... 

Module 'Magento_ConfigurableImportExport':

Module 'Magento_UrlRewrite':

Module 'Magento_StoreGraphQl':

Module 'Magento_ConfigurableProduct':

Module 'Magento_GroupedProduct':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Email':

Module 'Magento_CurrencySymbol':

Module 'Klarna_Core':
Installing schema... Upgrading schema... 

Module 'Magento_Analytics':

Module 'Magento_CustomerGraphQl':

Module 'Magento_CustomerImportExport':

Module 'Magento_SampleData':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Amazon_Core':

Module 'Magento_Tax':

Module 'Magento_CatalogGraphQl':

Module 'Magento_ImportExport':

Module 'Magento_Weee':

Module 'Magento_Authorizenet':

Module 'Magento_BundleGraphQl':

Module 'Magento_AdvancedSearch':

Module 'Magento_Newsletter':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_GoogleAdwords':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_ConfigurableProductGraphQl':

Module 'Magento_GroupedImportExport':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_GroupedProductGraphQl':

Module 'Magento_CatalogSampleData':

Module 'Magento_DownloadableImportExport':

Module 'Magento_Braintree':

Module 'Magento_InstantPurchase':

Module 'Magento_CatalogAnalytics':

Module 'Magento_Inventory':

Module 'Magento_InventoryAdminUi':

Module 'Magento_InventoryApi':

Module 'Magento_InventoryBundleProduct':

Module 'Magento_InventoryBundleProductAdminUi':

Module 'Magento_InventoryCatalog':

Module 'Magento_InventorySales':

Module 'Magento_InventoryCatalogAdminUi':

Module 'Magento_InventoryCatalogApi':

Module 'Magento_InventoryCatalogSearch':

Module 'Magento_InventoryConfigurableProduct':

Module 'Magento_InventoryConfigurableProductAdminUi':

Module 'Magento_InventoryConfigurableProductIndexer':

Module 'Magento_InventoryConfiguration':

Module 'Magento_InventoryConfigurationApi':

Module 'Magento_InventoryGroupedProduct':

Module 'Magento_InventoryGroupedProductAdminUi':

Module 'Magento_InventoryGroupedProductIndexer':

Module 'Magento_InventoryImportExport':

Module 'Magento_InventoryIndexer':

Module 'Magento_InventoryLowQuantityNotification':

Module 'Magento_InventoryLowQuantityNotificationAdminUi':

Module 'Magento_InventoryLowQuantityNotificationApi':

Module 'Magento_InventoryMultiDimensionalIndexerApi':

Module 'Magento_InventoryProductAlert':

Module 'Magento_InventoryReservations':

Module 'Magento_InventoryReservationsApi':

Module 'Magento_InventoryCache':

Module 'Magento_InventorySalesAdminUi':

Module 'Magento_InventorySalesApi':

Module 'Magento_InventorySalesFrontendUi':

Module 'Magento_InventoryShipping':

Module 'Magento_Shipping':

Module 'Magento_InventorySourceDeductionApi':

Module 'Magento_InventorySourceSelection':

Module 'Magento_InventorySourceSelectionApi':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_MessageQueue':

Module 'Magento_GroupedProductSampleData':

Module 'Magento_MsrpSampleData':

Module 'Magento_Multishipping':

Module 'Magento_MysqlMq':

Module 'Magento_NewRelicReporting':

Module 'Magento_ProductAlert':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_OfflineShipping':

Module 'Magento_PageCache':

Module 'Magento_Captcha':

Module 'Klarna_Ordermanagement':

Module 'Magento_Persistent':

Module 'Magento_Reports':

Module 'Magento_Bundle':

Module 'Magento_ProductVideo':

Module 'Amazon_Login':
Installing schema... Upgrading schema... 

Module 'Magento_QuoteAnalytics':

Module 'Magento_QuoteGraphQl':

Module 'Magento_ReleaseNotification':

Module 'Magento_Review':

Module 'Magento_RequireJs':

Module 'Magento_SendFriend':

Module 'Magento_ReviewAnalytics':

Module 'Magento_BundleSampleData':

Module 'Magento_Robots':

Module 'Magento_Rss':

Module 'Magento_ThemeSampleData':

Module 'Amazon_Payment':
Upgrading schema... 

Module 'Magento_SalesAnalytics':

Module 'Magento_SalesInventory':

Module 'Magento_OfflineShippingSampleData':

Module 'Magento_DownloadableSampleData':

Module 'Magento_TaxSampleData':

Module 'Magento_ConfigurableSampleData':

Module 'Magento_ProductLinksSampleData':

Module 'Magento_Elasticsearch':

Module 'Magento_CustomerAnalytics':

Module 'Magento_Wishlist':

Module 'Magento_InventoryShippingAdminUi':

Module 'Magento_Signifyd':

Module 'Magento_Sitemap':

Module 'Magento_CatalogInventoryGraphQl':

Module 'Magento_DownloadableGraphQl':

Module 'Magento_Webapi':

Module 'Magento_SwaggerWebapi':

Module 'Magento_SwaggerWebapiAsync':

Module 'Magento_Swatches':

Module 'Magento_SwatchesGraphQl':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_SwatchesSampleData':

Module 'Magento_ReviewSampleData':

Module 'Magento_TaxGraphQl':

Module 'Magento_TaxImportExport':

Module 'Magento_CustomerSampleData':

Module 'Magento_ConfigurableProductSales':

Module 'Magento_CmsSampleData':

Module 'Magento_Tinymce3':

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_SalesSampleData':

Module 'Magento_UrlRewriteGraphQl':

Module 'Magento_AsynchronousOperations':

Module 'Magento_Usps':

Module 'Magento_CatalogRuleSampleData':

Module 'Klarna_Kp':
Installing schema... Upgrading schema... 

Module 'Magento_Version':

Module 'Magento_Swagger':

Module 'Magento_WebapiAsync':

Module 'Magento_WebapiSecurity':

Module 'Magento_SalesRuleSampleData':

Module 'Magento_WeeeGraphQl':

Module 'Magento_CatalogWidget':

Module 'Magento_WidgetSampleData':

Module 'Dotdigitalgroup_Email':
Installing schema... Upgrading schema... 

Module 'Magento_WishlistAnalytics':

Module 'Magento_WishlistSampleData':

Module 'Temando_Shipping':
Upgrading schema... 

Module 'Vertex_Tax':
Installing schema... Upgrading schema... 

Schema post-updates:
Module 'Magento_Store':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Variable':

Module 'Magento_Eav':

Module 'Magento_AdminNotification':

Module 'MSP_ReCaptcha':

Module 'Magento_Config':

Module 'Magento_Indexer':
Running schema recurring...

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Search':

Module 'Magento_Amqp':
Running schema recurring...

Module 'Magento_Security':

Module 'Magento_User':

Module 'Magento_Authorization':

Module 'Magento_Customer':

Module 'Magento_Rule':

Module 'Magento_Backup':

Module 'Magento_Cms':

Module 'Magento_Catalog':
Running schema recurring...

Module 'Magento_GraphQl':

Module 'Magento_BundleImportExport':

Module 'Magento_CatalogRule':

Module 'Magento_CacheInvalidate':

Module 'Magento_Quote':

Module 'Magento_SalesSequence':
Running schema recurring...

Module 'Magento_Integration':
Running schema recurring...

Module 'Magento_EavGraphQl':

Module 'Magento_CatalogImportExport':

Module 'Magento_Payment':

Module 'Magento_CatalogInventory':
Running schema recurring...

Module 'Magento_Cron':
Running schema recurring...

Module 'Magento_Msrp':

Module 'Magento_CatalogSearch':

Module 'Magento_Sales':

Module 'Magento_Checkout':

Module 'Magento_CatalogUrlRewrite':
Running schema recurring...

Module 'Magento_CatalogUrlRewriteGraphQl':

Module 'Magento_Widget':

Module 'Magento_Vault':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Paypal':

Module 'Magento_CmsGraphQl':

Module 'Magento_Downloadable':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_CmsUrlRewriteGraphQl':

Module 'MSP_TwoFactorAuth':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_UrlRewrite':

Module 'Magento_StoreGraphQl':

Module 'Magento_ConfigurableProduct':
Running schema recurring...

Module 'Magento_GroupedProduct':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Email':

Module 'Magento_CurrencySymbol':

Module 'Klarna_Core':

Module 'Magento_Analytics':

Module 'Magento_CustomerGraphQl':

Module 'Magento_CustomerImportExport':

Module 'Magento_SampleData':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Amazon_Core':

Module 'Magento_Tax':

Module 'Magento_CatalogGraphQl':

Module 'Magento_ImportExport':

Module 'Magento_Weee':
Running schema recurring...

Module 'Magento_Authorizenet':

Module 'Magento_BundleGraphQl':

Module 'Magento_AdvancedSearch':

Module 'Magento_Newsletter':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_GoogleAdwords':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_ConfigurableProductGraphQl':

Module 'Magento_GroupedImportExport':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_GroupedProductGraphQl':

Module 'Magento_CatalogSampleData':

Module 'Magento_DownloadableImportExport':

Module 'Magento_Braintree':

Module 'Magento_InstantPurchase':

Module 'Magento_CatalogAnalytics':

Module 'Magento_Inventory':

Module 'Magento_InventoryAdminUi':

Module 'Magento_InventoryApi':

Module 'Magento_InventoryBundleProduct':

Module 'Magento_InventoryBundleProductAdminUi':

Module 'Magento_InventoryCatalog':

Module 'Magento_InventorySales':

Module 'Magento_InventoryCatalogAdminUi':

Module 'Magento_InventoryCatalogApi':

Module 'Magento_InventoryCatalogSearch':

Module 'Magento_InventoryConfigurableProduct':

Module 'Magento_InventoryConfigurableProductAdminUi':

Module 'Magento_InventoryConfigurableProductIndexer':

Module 'Magento_InventoryConfiguration':

Module 'Magento_InventoryConfigurationApi':

Module 'Magento_InventoryGroupedProduct':

Module 'Magento_InventoryGroupedProductAdminUi':

Module 'Magento_InventoryGroupedProductIndexer':

Module 'Magento_InventoryImportExport':

Module 'Magento_InventoryIndexer':

Module 'Magento_InventoryLowQuantityNotification':

Module 'Magento_InventoryLowQuantityNotificationAdminUi':

Module 'Magento_InventoryLowQuantityNotificationApi':

Module 'Magento_InventoryMultiDimensionalIndexerApi':

Module 'Magento_InventoryProductAlert':

Module 'Magento_InventoryReservations':

Module 'Magento_InventoryReservationsApi':

Module 'Magento_InventoryCache':

Module 'Magento_InventorySalesAdminUi':

Module 'Magento_InventorySalesApi':

Module 'Magento_InventorySalesFrontendUi':

Module 'Magento_InventoryShipping':

Module 'Magento_Shipping':

Module 'Magento_InventorySourceDeductionApi':

Module 'Magento_InventorySourceSelection':

Module 'Magento_InventorySourceSelectionApi':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_MessageQueue':

Module 'Magento_GroupedProductSampleData':

Module 'Magento_MsrpSampleData':

Module 'Magento_Multishipping':

Module 'Magento_MysqlMq':
Running schema recurring...

Module 'Magento_NewRelicReporting':

Module 'Magento_ProductAlert':
Running schema recurring...

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_OfflineShipping':

Module 'Magento_PageCache':

Module 'Magento_Captcha':

Module 'Klarna_Ordermanagement':

Module 'Magento_Persistent':

Module 'Magento_Reports':
Running schema recurring...

Module 'Magento_Bundle':
Running schema recurring...

Module 'Magento_ProductVideo':

Module 'Amazon_Login':

Module 'Magento_QuoteAnalytics':

Module 'Magento_QuoteGraphQl':

Module 'Magento_ReleaseNotification':

Module 'Magento_Review':

Module 'Magento_RequireJs':

Module 'Magento_SendFriend':

Module 'Magento_ReviewAnalytics':

Module 'Magento_BundleSampleData':

Module 'Magento_Robots':

Module 'Magento_Rss':

Module 'Magento_ThemeSampleData':

Module 'Amazon_Payment':

Module 'Magento_SalesAnalytics':

Module 'Magento_SalesInventory':

Module 'Magento_OfflineShippingSampleData':

Module 'Magento_DownloadableSampleData':

Module 'Magento_TaxSampleData':

Module 'Magento_ConfigurableSampleData':

Module 'Magento_ProductLinksSampleData':

Module 'Magento_Elasticsearch':

Module 'Magento_CustomerAnalytics':

Module 'Magento_Wishlist':
Running schema recurring...

Module 'Magento_InventoryShippingAdminUi':

Module 'Magento_Signifyd':

Module 'Magento_Sitemap':

Module 'Magento_CatalogInventoryGraphQl':

Module 'Magento_DownloadableGraphQl':

Module 'Magento_Webapi':

Module 'Magento_SwaggerWebapi':

Module 'Magento_SwaggerWebapiAsync':

Module 'Magento_Swatches':

Module 'Magento_SwatchesGraphQl':

Module 'Magento_SwatchesLayeredNavigation':

Module 'Magento_SwatchesSampleData':

Module 'Magento_ReviewSampleData':

Module 'Magento_TaxGraphQl':

Module 'Magento_TaxImportExport':

Module 'Magento_CustomerSampleData':

Module 'Magento_ConfigurableProductSales':

Module 'Magento_CmsSampleData':

Module 'Magento_Tinymce3':

Module 'Magento_Translation':

Module 'Magento_GoogleOptimizer':

Module 'Magento_Ups':

Module 'Magento_SalesSampleData':

Module 'Magento_UrlRewriteGraphQl':

Module 'Magento_AsynchronousOperations':

Module 'Magento_Usps':

Module 'Magento_CatalogRuleSampleData':

Module 'Klarna_Kp':

Module 'Magento_Version':

Module 'Magento_Swagger':

Module 'Magento_WebapiAsync':

Module 'Magento_WebapiSecurity':

Module 'Magento_SalesRuleSampleData':

Module 'Magento_WeeeGraphQl':

Module 'Magento_CatalogWidget':

Module 'Magento_WidgetSampleData':

Module 'Dotdigitalgroup_Email':
Running schema recurring...

Module 'Magento_WishlistAnalytics':

Module 'Magento_WishlistSampleData':

Module 'Temando_Shipping':

Module 'Vertex_Tax':


Installing user configuration...

Enabling caches:
Current status:
Array
(
[config] => 1
[layout] => 1
[block_html] => 1
[collections] => 1
[reflection] => 1
[db_ddl] => 1
[compiled_config] => 1
[eav] => 1
[customer_notification] => 1
[config_integration] => 1
[config_integration_api] => 1
[full_page] => 1
[config_webservice] => 1
[translate] => 1
[vertex] => 1
)


Installing data...
Data install/update:
Module 'Magento_Store':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Variable':

Module 'Magento_Eav':

Module 'Magento_AdminNotification':

Module 'MSP_ReCaptcha':
Upgrading data... 

Module 'Magento_Config':

Module 'Magento_Indexer':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Search':

Module 'Magento_Amqp':

Module 'Magento_Security':

Module 'Magento_User':

Module 'Magento_Authorization':

Module 'Magento_Customer':

Module 'Magento_Rule':

Module 'Magento_Backup':

Module 'Magento_Cms':

Module 'Magento_Catalog':

Module 'Magento_GraphQl':

Module 'Magento_BundleImportExport':

Module 'Magento_CatalogRule':

Module 'Magento_CacheInvalidate':

Module 'Magento_Quote':

Module 'Magento_SalesSequence':

Module 'Magento_Integration':

Module 'Magento_EavGraphQl':

Module 'Magento_CatalogImportExport':

Module 'Magento_Payment':

Module 'Magento_CatalogInventory':

Module 'Magento_Cron':

Module 'Magento_Msrp':

Module 'Magento_CatalogSearch':

Module 'Magento_Sales':

Module 'Magento_Checkout':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_CatalogUrlRewriteGraphQl':

Module 'Magento_Widget':

Module 'Magento_Vault':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Paypal':

Module 'Magento_CmsGraphQl':

Module 'Magento_Downloadable':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_CmsUrlRewriteGraphQl':

Module 'MSP_TwoFactorAuth':
Installing data... Upgrading data... 

Module 'Magento_ConfigurableImportExport':

Module 'Magento_UrlRewrite':

Module 'Magento_StoreGraphQl':

Module 'Magento_ConfigurableProduct':

Module 'Magento_GroupedProduct':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Email':

Module 'Magento_CurrencySymbol':

Module 'Klarna_Core':
Upgrading data... 

Module 'Magento_Analytics':

Module 'Magento_CustomerGraphQl':

Module 'Magento_CustomerImportExport':

Module 'Magento_SampleData':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Amazon_Core':
Upgrading data... 

Module 'Magento_Tax':

Module 'Magento_CatalogGraphQl':

Module 'Magento_ImportExport':

Module 'Magento_Weee':

Module 'Magento_Authorizenet':

Module 'Magento_BundleGraphQl':

Module 'Magento_AdvancedSearch':

Module 'Magento_Newsletter':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_GoogleAdwords':

Module 'Magento_GoogleAnalytics':

Module 'Magento_Ui':

Module 'Magento_ConfigurableProductGraphQl':

Module 'Magento_GroupedImportExport':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_GroupedProductGraphQl':

Module 'Magento_CatalogSampleData':
[ERROR] Magento\Framework\Setup\Exception: Rolled back transaction has not been completed correctly. in /homepages/21/d774584132/htdocs/Magento/vendor/magento/framework/Setup/Patch/PatchApplier.php:167
Stack trace:
#0 /homepages/21/d774584132/htdocs/Magento/setup/src/Magento/Setup/Model/Installer.php(1002): Magento\Framework\Setup\Patch\PatchApplier->applyDataPatch('Magento_Catalog...')
#1 /homepages/21/d774584132/htdocs/Magento/setup/src/Magento/Setup/Model/Installer.php(874): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data', Array)
#2 [internal function]: Magento\Setup\Model\Installer->installDataFixtures(Array)
#3 /homepages/21/d774584132/htdocs/Magento/setup/src/Magento/Setup/Model/Installer.php(367): call_user_func_array(Array, Array)
#4 /homepages/21/d774584132/htdocs/Magento/setup/src/Magento/Setup/Controller/Install.php(109): Magento\Setup\Model\Installer->install(Array)
#5 /homepages/21/d774584132/htdocs/Magento/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Magento\Setup\Controller\Install->startAction()
#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /homepages/21/d774584132/htdocs/Magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /homepages/21/d774584132/htdocs/Magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /homepages/21/d774584132/htdocs/Magento/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#10 /homepages/21/d774584132/htdocs/Magento/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /homepages/21/d774584132/htdocs/Magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /homepages/21/d774584132/htdocs/Magento/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /homepages/21/d774584132/htdocs/Magento/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#15 /homepages/21/d774584132/htdocs/Magento/setup/index.php(39): Zend\Mvc\Application->run()
#16 {main}

```

You can view my PHP Settings at http://balkangoods.de/phpinfo.php
I'm really kind of desparate.

Thanks in advance for any help!

Best regards
McPeon

**Comment by magento-engcom-team** [comment]
Hi @McPeon. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@McPeon do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @McPeon would be great if you share with your configuration, because this information not enough to reproduce your issue.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @McPeon thank you for your report, i'm not able to reproduce following steps you described, please provide more detail information.

**Comment by McPeon** [comment]
I use PHP 7.2 and a MySQL 5.7 Database on a shared Webhost.

Do you need any other information?

**Comment by huykon** [comment]
I have same problem now, did you have solution to resolve?

**Comment by McPeon** [comment]
No, I'm sorry.
I still don't know how to fix it.

**Comment by MichaelDD71** [comment]
I have same problem now, did you have solution to resolve?
My Provider is 1and1
PHP 7.2 and a MySQL 5.7 Database

**Comment by huykon** [comment]
I downloaded Magento version 2.3.1 and installed and It's working now 💃

**Comment by pdubost** [comment]
Exact same issue here. Also with 1and1 (shared).
Using Magento-CE-2.3.1_sample_data-2019-03-18-06-46-56.zip

I suspect some timeout issue? Has anyone tried editing php.ini perhaps?

**Comment by rohit030** [comment]
Re: Magento 2 installation stuck at 66%
In your php.ini file increase values of below parameters.

max_execution_time = 18000
max_input_time = 1800
memory_limit = 1024M
Note : Make sure you increase max_input_time value to at least 1800 and it will works !!
