### ISSUE TITLE
Magento root directory is not specified - hhvm

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#2191]
Only happens with HHVM (3.10) not using PHP 7. Trying to run /setup in latest code, using nginx.

```
\nFatal error: Uncaught exception 'LogicException' with message 'Magento root directory is not specified.' in /Users/ccarnell/Sites/magento2/setup/src/Magento/Setup/Mvc/Bootstrap/InitParamListener.php:152\nStack trace:\n#0 /Users/ccarnell/Sites/magento2/setup/src/Magento/Setup/Mvc/Bootstrap/InitParamListener.php(78): Magento\\Setup\\Mvc\\Bootstrap\\InitParamListener->createDirectoryList()\n#1 (): Magento\\Setup\\Mvc\\Bootstrap\\InitParamListener->onBootstrap()\n#2 /Users/ccarnell/Sites/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func()\n#3 /Users/ccarnell/Sites/magento2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\\EventManager\\EventManager->triggerListeners()\n#4 /Users/ccarnell/Sites/magento2/vendor/zendframework/zend-mvc/src/Application.php(157): Zend\\EventManager\\EventManager->trigger()\n#5 /Users/ccarnell/Sites/magento2/vendor/zendframework/zend-mvc/src/Application.php(261): Zend\\Mvc\\Application->bootstrap()\n#6 /Users/ccarnell/Sites/magento2/setup/index.php(31): Zend\\Mvc\\Application::init()\n#7 {main}
```

top of my nginx config:
```
# Magento Vars
  set $MAGE_ROOT /Users/ccarnell/Sites/magento2;
  
  
    set $MAGE_MODE developer;
  

  root $MAGE_ROOT/pub;
  
  index index.php;
  autoindex off;
  charset off;
  
  add_header 'X-Content-Type-Options' 'nosniff';
  add_header 'X-XSS-Protection' '1; mode=block';

  location /setup {
      root $MAGE_ROOT;
      location ~ ^/setup/index.php {
          fastcgi_pass   unix:/usr/local/var/run/hhvm/hhvm.sock;
          fastcgi_index  index.php;
          fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
          include        fastcgi_params;
      }
  
      location ~ ^/setup/(?!pub/). {
          deny all;
      }
  }
```

**Comment by mazhalai** [comment]
@craigcarnell have you tried setting it in the server directive?  https://github.com/magento/magento2/blob/develop/nginx.conf.sample#L12

**Comment by craigcarnell** [comment]
@mazhalai What happens when you multiple vhost confs?

**Comment by mazhalai** [comment]
@craigcarnell refer to tutorial [here](https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-virtual-hosts-server-blocks-on-ubuntu-12-04-lts--3)

**Comment by craigcarnell** [comment]
@mazhalai Nevermind, it's already in server. So it's still an issue here.

**Comment by mazhalai** [comment]
@craigcarnell can you check if the MAGE_DIR value is set correctly using a breakpoint or var_dump here: https://github.com/magento/magento2/blob/develop/setup/config/autoload/global.php

**Comment by cscd98** [comment]
@mazhalai Where exactly in this file am I supposed to put var_dump?

Also I get the same issue with the bin/magento command line tool if I set the env to be hhvm instead of php

**Comment by mazhalai** [comment]
@craigcarnell you can store the return value in a variable, var_dump that value and then return it.

**Comment by cscd98** [comment]
@mazhalai Could you give me the exact code to place here? Thanks

**Comment by mazhalai** [comment]
Replace lines 11 to 15 with:

```
$temporaryVariable =  [
    InitParamListener::BOOTSTRAP_PARAM => [
        Bootstrap::INIT_PARAM_FILESYSTEM_DIR_PATHS => [DirectoryList::ROOT => [DirectoryList::PATH => BP]],
    ]
];
var_dump($temporaryVariable);
return $temporaryVariable;
```

**Comment by cscd98** [comment]
@mazhalai I have tried this now but unfortunately I now get:

```
\nFatal error: Cannot instantiate interface Magento\\Framework\\Config\\CacheInterface in /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 73
```

**Comment by cscd98** [comment]
@mazhalai If I try from the command line instead:

```
hhvm bin/magento index:reindex
Magento root directory is not specified.#0 /Users/ccarnell/Sites/vax-uk2/setup/src/Magento/Setup/Mvc/Bootstrap/InitParamListener.php(91): Magento\Setup\Mvc\Bootstrap\InitParamListener->createDirectoryList()
#1 (): Magento\Setup\Mvc\Bootstrap\InitParamListener->onBootstrap()
#2 /Users/ccarnell/Sites/vax-uk2/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func()
#3 /Users/ccarnell/Sites/vax-uk2/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners()
#4 /Users/ccarnell/Sites/vax-uk2/vendor/zendframework/zend-mvc/src/Application.php(157): Zend\EventManager\EventManager->trigger()
#5 /Users/ccarnell/Sites/vax-uk2/vendor/zendframework/zend-mvc/src/Application.php(261): Zend\Mvc\Application->bootstrap()
#6 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Console/Cli.php(66): Zend\Mvc\Application::init()
#7 /Users/ccarnell/Sites/vax-uk2/bin/magento(23): Magento\Framework\Console\Cli->__construct()
#8 {main}
```

**Comment by mw-msolovev** [comment]
@craigcarnell Hi, i have the same problem with Magento 2.0.2 EE and Apache on Yosemite. Did you find any solution? Thanks in advance

**Comment by cscd98** [comment]
@mw-msolovev No I didn't. I'm using PHP 7.0.3 which runs great now

**Comment by vzabaznov** [comment]
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment]
Hi, @craigcarnell thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.
