### ISSUE TITLE
Unable to reset the Custom attribtue value related to  category 

### ISSUE THREAD

**Issue by chaluvadiswamy** [magento/magento2#2251]
I Have created the New attribute for category to upload the thumbnail image ,for first when i add the image its taking , then i edit /delete the image for custom image attribute it showing error as mentioned below

```
Notice: Array to string conversion in D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Data\Form\Element\Image.php on line 51
#0 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Data\Form\Element\Image.php(51): Magento\Framework\App\ErrorHandler->handler(8, 'Array to string...', 'D:\\serversetup\\...', 51, Array)
#1 D:\serversetup\htdocs\mage2\app\code\Magento\Backend\view\adminhtml\templates\widget\form\renderer\fieldset\element.phtml(40): Magento\Framework\Data\Form\Element\Image->getElementHtml()
#2 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\TemplateEngine\Php.php(59): include('D:\\serversetup\\...')
#3 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Widget\Form\Renderer\Fieldset\Element), 'D:/serversetup/...', Array)
#4 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Element\Template.php(275): Magento\Framework\View\Element\Template->fetchView('D:/serversetup/...')
#5 D:\serversetup\htdocs\mage2\app\code\Magento\Backend\Block\Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#6 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(652): Magento\Backend\Block\Template->_toHtml()
#7 D:\serversetup\htdocs\mage2\app\code\Magento\Backend\Block\Widget\Form\Renderer\Fieldset\Element.php(45): Magento\Framework\View\Element\AbstractBlock->toHtml()
#8 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Data\Form\Element\AbstractElement.php(458): Magento\Backend\Block\Widget\Form\Renderer\Fieldset\Element->render(Object(Magento\Catalog\Block\Adminhtml\Category\Helper\Image))
#9 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Data\Form\Element\AbstractElement.php(472): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#10 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Data\Form\Element\Fieldset.php(229): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#11 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Data\Form\Element\Fieldset.php(106): Magento\Framework\Data\Form\Element\Fieldset->_elementsToHtml(Array)
#12 D:\serversetup\htdocs\mage2\app\code\Magento\Backend\view\adminhtml\templates\widget\form\renderer\fieldset.phtml(84): Magento\Framework\Data\Form\Element\Fieldset->getBasicChildrenHtml()
#13 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\TemplateEngine\Php.php(59): include('D:\\serversetup\\...')
#14 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Widget\Form\Renderer\Fieldset), 'D:/serversetup/...', Array)
#15 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Element\Template.php(275): Magento\Framework\View\Element\Template->fetchView('D:/serversetup/...')
#16 D:\serversetup\htdocs\mage2\app\code\Magento\Backend\Block\Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#17 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(652): Magento\Backend\Block\Template->_toHtml()
#18 D:\serversetup\htdocs\mage2\app\code\Magento\Backend\Block\Widget\Form\Renderer\Fieldset.php(45): Magento\Framework\View\Element\AbstractBlock->toHtml()
#19 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Data\Form\Element\AbstractElement.php(458): Magento\Backend\Block\Widget\Form\Renderer\Fieldset->render(Object(Magento\Framework\Data\Form\Element\Fieldset))
#20 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Data\Form\Element\AbstractElement.php(472): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#21 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Data\Form.php(322): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#22 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Data\Form.php(337): Magento\Framework\Data\Form->toHtml()
#23 D:\serversetup\htdocs\mage2\app\code\Magento\Backend\Block\Widget\Form.php(98): Magento\Framework\Data\Form->getHtml()
#24 D:\serversetup\htdocs\mage2\var\generation\Magento\Catalog\Block\Adminhtml\Category\Tab\Attributes\Interceptor.php(51): Magento\Backend\Block\Widget\Form->getFormHtml()
#25 D:\serversetup\htdocs\mage2\app\code\Magento\Backend\view\adminhtml\templates\widget\form.phtml(15): Magento\Catalog\Block\Adminhtml\Category\Tab\Attributes\Interceptor->getFormHtml()
#26 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\TemplateEngine\Php.php(59): include('D:\\serversetup\\...')
#27 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Adminhtml\Category\Tab\Attributes\Interceptor), 'D:/serversetup/...', Array)
#28 D:\serversetup\htdocs\mage2\var\generation\Magento\Catalog\Block\Adminhtml\Category\Tab\Attributes\Interceptor.php(272): Magento\Framework\View\Element\Template->fetchView('D:/serversetup/...')
#29 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Element\Template.php(275): Magento\Catalog\Block\Adminhtml\Category\Tab\Attributes\Interceptor->fetchView('D:/serversetup/...')
#30 D:\serversetup\htdocs\mage2\app\code\Magento\Backend\Block\Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#31 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(652): Magento\Backend\Block\Template->_toHtml()
#32 D:\serversetup\htdocs\mage2\var\generation\Magento\Catalog\Block\Adminhtml\Category\Tab\Attributes\Interceptor.php(597): Magento\Framework\View\Element\AbstractBlock->toHtml()
#33 D:\serversetup\htdocs\mage2\app\code\Magento\Catalog\Block\Adminhtml\Category\Tabs.php(161): Magento\Catalog\Block\Adminhtml\Category\Tab\Attributes\Interceptor->toHtml()
#34 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(257): Magento\Catalog\Block\Adminhtml\Category\Tabs->_prepareLayout()
#35 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Layout.php(723): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor))
#36 D:\serversetup\htdocs\mage2\var\generation\Magento\Framework\View\Layout\Interceptor.php(349): Magento\Framework\View\Layout->createBlock('Magento\\Catalog...', 'tabs', Array)
#37 D:\serversetup\htdocs\mage2\app\code\Magento\Catalog\Block\Adminhtml\Category\Edit\Form.php(71): Magento\Framework\View\Layout\Interceptor->createBlock('Magento\\Catalog...', 'tabs')
#38 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(257): Magento\Catalog\Block\Adminhtml\Category\Edit\Form->_prepareLayout()
#39 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Layout.php(723): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor))
#40 D:\serversetup\htdocs\mage2\var\generation\Magento\Framework\View\Layout\Interceptor.php(349): Magento\Framework\View\Layout->createBlock('Magento\\Catalog...', 'category.edit.f...', Array)
#41 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(375): Magento\Framework\View\Layout\Interceptor->createBlock('Magento\\Catalog...', 'category.edit.f...', Array)
#42 D:\serversetup\htdocs\mage2\app\code\Magento\Backend\Block\Widget\Form\Container.php(108): Magento\Framework\View\Element\AbstractBlock->addChild('form', 'Magento\\Catalog...')
#43 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Element\AbstractBlock.php(257): Magento\Backend\Block\Widget\Form\Container->_prepareLayout()
#44 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Layout\Generator\Block.php(139): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor))
#45 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Layout\GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#46 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Layout.php(329): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#47 D:\serversetup\htdocs\mage2\var\generation\Magento\Framework\View\Layout\Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#48 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Layout\Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#49 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Page\Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#50 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Layout\Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#51 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#52 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\View\Layout.php(838): Magento\Framework\View\Layout->build()
#53 D:\serversetup\htdocs\mage2\var\generation\Magento\Framework\View\Layout\Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#54 D:\serversetup\htdocs\mage2\app\code\Magento\Backend\Model\View\Result\Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#55 D:\serversetup\htdocs\mage2\var\generation\Magento\Backend\Model\View\Result\Page\Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Catalog...')
#56 D:\serversetup\htdocs\mage2\app\code\Magento\Catalog\Controller\Adminhtml\Category\Edit.php(114): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Catalog...')
#57 D:\serversetup\htdocs\mage2\var\generation\Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Category\Edit->execute()
#58 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\App\Action\Action.php(102): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->execute()
#59 D:\serversetup\htdocs\mage2\app\code\Magento\Backend\App\AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#60 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#61 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Interception\Interceptor.php(74): call_user_func_array(Array, Array)
#62 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Interception\Chain\Chain.php(70): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->___callParent('dispatch', Array)
#63 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Array, 'adminAuthentica...')
#64 D:\serversetup\htdocs\mage2\app\code\Magento\Backend\App\Action\Plugin\Authentication.php(135): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#65 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#66 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Interception\Chain\Chain.php(68): call_user_func_array(Array, Array)
#67 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Array, 'designLoader')
#68 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\App\Action\Plugin\Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#69 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#70 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Interception\Chain\Chain.php(68): call_user_func_array(Array, Array)
#71 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Interception\Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Array, 'adminMassaction...')
#72 D:\serversetup\htdocs\mage2\app\code\Magento\Backend\App\Action\Plugin\MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#73 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#74 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Interception\Interceptor.php(141): call_user_func_array(Array, Array)
#75 D:\serversetup\htdocs\mage2\var\generation\Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#76 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\App\FrontController.php(45): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#77 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#78 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Interception\Interceptor.php(74): call_user_func_array(Array, Array)
#79 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Interception\Chain\Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#80 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Interception\Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#81 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Module\Plugin\DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#82 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#83 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\Interception\Interceptor.php(141): call_user_func_array(Array, Array)
#84 D:\serversetup\htdocs\mage2\var\generation\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#85 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\App\Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#86 D:\serversetup\htdocs\mage2\lib\internal\Magento\Framework\App\Bootstrap.php(257): Magento\Framework\App\Http->launch()
#87 D:\serversetup\htdocs\mage2\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#88 {main}
```

Can one help on this , i have echo the image URL it is printing correctly ('lib\internal\Magento\Framework\Data\Form\Element\Image.php')

**Comment by Vinai** [comment]
Please refer to the [forums](https://community.magento.com) or [magento stack exchange](http://magento.stackexchange.com/) for technical questions. In your case probably the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2 would ) would be the most appropriate.
Please feel free to reopen this issue if you think you have encountered a bug in Magento 2.
