### ISSUE TITLE
Symlinked module ui_componet file not read 

### ISSUE THREAD

**Issue by 0m3r** [magento/magento2#2257]
I add my custom module like a symlink in magento2 project
~~~
$  ls -l /var/www/local.magentocommerce2.com/htdocs/app/code/TM
lrwxrwxrwx 1 user www-data 45 лис  3 17:19 /var/www/local.magentocommerce2.com/htdocs/app/code/TM -> /var/www/local.magentocommerce2.com/vendor/tm
~~~
But mage2 shows me  such error
~~~
Cannot read contents from file "/var/www/local.magentocommerce2.com/htdocs/var/www/local.magentocommerce2.com/vendor/tm/Askit/view/adminhtml/ui_component/askit_question_listing.xml" Warning!file_get_contents(/var/www/local.magentocommerce2.com/htdocs/var/www/local.magentocommerce2.com/vendor/tm/Askit/view/adminhtml/ui_component/askit_question_listing.xml): failed to open stream: No such file or directory
#0 /var/www/local.magentocommerce2.com/htdocs/lib/internal/Magento/Framework/Filesystem/Directory/Read.php(214): Magento\Framework\Filesystem\Driver\File->fileGetContents('/var/www/local....', NULL, NULL)
#1 /var/www/local.magentocommerce2.com/htdocs/lib/internal/Magento/Framework/View/Element/UiComponent/Config/FileCollector/AggregatedFileCollector.php(81): Magento\Framework\Filesystem\Directory\Read->readFile('/var/www/local....')
#2 /var/www/local.magentocommerce2.com/htdocs/lib/internal/Magento/Framework/View/Element/UiComponent/Config/Reader.php(47): Magento\Framework\View\Element\UiComponent\Config\FileCollector\AggregatedFileCollector->collectFiles()
#3 /var/www/local.magentocommerce2.com/htdocs/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(101): Magento\Framework\View\Element\UiComponent\Config\Reader->__construct(Object(Magento\Framework\View\Element\UiComponent\Config\FileCollector\AggregatedFileCollector), Object(Magento\Framework\View\Element\UiComponent\Config\Converter), Object(Magento\Framework\View\Element\UiComponent\Config\DomMerger))
#4 /var/www/local.magentocommerce2.com/htdocs/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#5 /var/www/local.magentocommerce2.com/htdocs/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#6 /var/www/local.magentocommerce2.com/htdocs/lib/internal/Magento/Framework/View/Element/UiComponent/Config/ReaderFactory.php(40): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#7 /var/www/local.magentocommerce2.com/htdocs/app/code/Magento/Ui/Model/Manager.php(247): Magento\Framework\View\Element\UiComponent\Config\ReaderFactory->create(Array)
#8 /var/www/local.magentocommerce2.com/htdocs/app/code/Magento/Ui/Model/Manager.php(261): Magento\Ui\Model\Manager->getReader('askit_question_...')
#9 /var/www/local.magentocommerce2.com/htdocs/app/code/Magento/Ui/Model/Manager.php(169): Magento\Ui\Model\Manager->prepare('askit_question_...')
#10 /var/www/local.magentocommerce2.com/htdocs/lib/internal/Magento/Framework/View/Element/UiComponentFactory.php(139): Magento\Ui\Model\Manager->prepareData('askit_question_...')
#11 /var/www/local.magentocommerce2.com/htdocs/lib/internal/Magento/Framework/View/Layout/Generator/UiComponent.php(125): Magento\Framework\View\Element\UiComponentFactory->create('askit_question_...', NULL, Array)
#12 /var/www/local.magentocommerce2.com/htdocs/lib/internal/Magento/Framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'askit_question_...', Array, Object(Magento\Framework\View\Layout\Interceptor))
#13 /var/www/local.magentocommerce2.com/htdocs/lib/internal/Magento/Framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
~~~

Look like a getRelativePath func not correct work with symlink
~~~php
namespace Magento\Framework\View\Element\UiComponent\Config\FileCollector;
...
foreach ($files as $file) {
            $filePath = $fileReader->getRelativePath($file->getFilename());
~~~

**Comment by 0m3r** [comment]
I solved myself 
* unlink previous "wrong" location (/var/www/local.magentocommerce2.com/vendor/tm)
* move module to /var/www/local.magentocommerce2.com/htdocs/vendor/tm 
* ln -s /var/www/local.magentocommerce2.com/htdocs/vendor/tm /var/www/local.magentocommerce2.com/htdocs/app/code/TM
