### ISSUE TITLE
Deployment Breaks After Upgrading to Magento 2.3.2

### ISSUE THREAD

**Issue by sreenathnr** [magento/magento2#23648]
### Preconditions (*)

Magento 2.3.2
1. After Magento, upgrading from Magento 2.3.1 to 2.3.2

### Steps to reproduce (*)

1. Multi-stock Inventory Modules are enabled in Magento 2.3.1
2. Upgrade Magento 2.3.2 from Magento 2.3.1 by using composer.
3. Deployment initiated

### Expected result (*)

1. Deployment is a success with no Errors

### Actual result (*)

1. Deployment has the below errors.

 `Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\HTTP\ClientInterface in /opt/lampp/htdocs/flowerbx/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /opt/lampp/htdocs/flowerbx/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#1 /opt/lampp/htdocs/flowerbx/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#2 /opt/lampp/htdocs/flowerbx/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'client', 'Magento\\Invento...')
#3 /opt/lampp/htdocs/flowerbx/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Invento...', Array, Array in /opt/lampp/htdocs/flowerbx/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50`

**Comment by sreenathnr** [comment]
Some other users reporting the same error in https://github.com/magento/magento2/issues/22189

**Comment by mibbinvc** [comment]
I am also getting the Issue on ReservationBuilderInterface after upgrade to 2.3.2. 

```

  Fatal error: Uncaught Error: Cannot instantiate interface Magento\InventoryReservationsApi\Model\ReservationBuilderInterface in /opt/lampp/htdocs/example/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /opt/lampp/htdocs/example/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Invento...')
magento/magento2#1 /opt/lampp/htdocs/example/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Invento...')
magento/magento2#2 /opt/lampp/htdocs/example/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Invento...', NULL, 'reservationBuil...', 'Magento\\Invento...')
magento/magento2#3 /opt/lampp/htdocs/example/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArguments in /opt/lampp/htdocs/example/vendor/magento/framework/ObjectManager/Factory/Dynamic

**Comment by sreenathnr** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sreenathnr. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sreenathnr, here is your [Magento instance](https://i-23648-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23648-2-3-develop.instances.magento-community.engineering/admin](https://i-23648-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sreenathnr** [comment]
@magento-engcom-team I got the error in `bin/magento setup:upgrade`

**Comment by PashaIhnatjo** [comment]
Please, check file app/code/etc/di.xml. 
it must contain a this line:
preference for="Magento\Framework\HTTP\ClientInterface" type="Magento\Framework\HTTP\Client\Curl"

**Comment by sriharsha184** [comment]
@PashaIhnatjo or anyone
Could you please explain briefly how you fixed this issue,We got this issue while giving magento commands after upgrading to 2.3.2.

`Cannot instantiate interface Magento\InventoryReservationsApi\Model\ReservationBuilderInterface in /opt/lampp/htdocs/example/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50`

**Comment by PashaIhnatjo** [comment]
@sriharsha184  in my case the problem was that the file di.xml was from version 2.3.1

**Comment by ryanpalmerweb** [comment]
@sriharsha184 

It's likely you have a module enabled with some dependencies for this

We managed to get around this by disabling Magento_InventoryReservationCli in config.php

**Comment by sdzhepa** [comment]
Hello @sreenathnr 

Could you please check your di.xml after upgrade as mentioned https://github.com/magento/magento2/issues/23648#issuecomment-511375618
We had this issue previously but it has been fixed
- in `2.3-develop`: https://github.com/magento/magento2/blob/2.3-develop/app/etc/di.xml#L213
- in `2.3.2` : https://github.com/magento/magento2/blob/2.3.2/app/etc/di.xml#L212

to: @sriharsha184 and @ryanpalmerweb 
`Cannot instantiate interface Magento\InventoryReservationsApi\Model\ReservationBuilderInterface in /opt/lampp/htdocs/example/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50`

It looks like another issue and I suppose it could be related to Multi-source Inventory Modules
Could you please create this issue with details in the https://github.com/magento/inventory/issues .

**Comment by densen45** [comment]
The workaround from @ryanpalmerweb works great.

> It's likely you have a module enabled with some dependencies for this
> 
> We managed to get around this by disabling Magento_InventoryReservationCli in config.php

Thank you very much!

---

We had disabled all the Magento_Inventory* modules before (in 2.3.0) and thus were not able to deploy after we had upgraded to 2.3.2.

We have disabled the four following modules in the app/etc/config.php and the deploy is working again (upgrade to 2.3.2 successfully completed):
* Magento_InventoryExportStock
* Magento_InventoryExportStockApi
* Magento_InventoryGraphQl
* Magento_InventoryReservationCli

**Comment by LucasMali** [comment]
Recently upgraded from 2.2.8 to 2.3.1, had some issues that we were told would be fixed if we upgraded to 2.3.2 and now seeing that same error.

```
Cannot instantiate interface Magento\InventoryReservationsApi\Model\ReservationBuilderInterface in MAGE_ROOT/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
```
Steps that were taken so far (not in any given order):
• Flushed cache
• Removed the generated/code folder
• ran s:up and s:di:c
• disabled the following:

```
List of disabled modules:
Magento_InventoryReservations
Magento_InventoryReservationCli
Magento_InventoryReservationsApi
```

**Comment by ryanpalmerweb** [comment]
@LucasMaliszewski Disable those modules and clear the generated after, after that are you sure there are no other Magento_Inventory modules enabled which are linked to this? Could you post your module:status?

**Comment by LucasMali** [comment]
@ryanpalmerweb 
```
List of enabled modules:
Magento_Store
Magento_Directory
Magento_Theme
Magento_Eav
Magento_AdvancedPricingImportExport
Magento_Rule
Magento_Customer
Magento_Backend
Magento_Amqp
Magento_Config
Magento_User
Magento_Authorization
Magento_AdminNotification
Magento_Indexer
Magento_Variable
Magento_Backup
Magento_Cms
Magento_Quote
Magento_SalesSequence
Magento_Catalog
Magento_CatalogInventory
Magento_Bundle
Magento_GraphQl
Magento_BundleImportExport
Magento_BundleImportExportStaging
Magento_Payment
Magento_CacheInvalidate
Magento_CatalogUrlRewrite
Magento_AdvancedCatalog
Magento_Security
Magento_MediaStorage
Magento_EavGraphQl
Magento_CatalogImportExport
Magento_CatalogImportExportStaging
Magento_Sales
Magento_CatalogInventoryGraphQl
Magento_Msrp
Magento_CatalogPageBuilderAnalytics
Magento_CatalogPageBuilderAnalyticsStaging
Magento_Search
Magento_Widget
Magento_Checkout
Magento_SalesRule
Magento_CatalogRule
Magento_Downloadable
Magento_GiftCard
Magento_Captcha
Magento_StoreGraphQl
Magento_Wishlist
Magento_CustomerCustomAttributes
Magento_AuthorizenetAcceptjs
Magento_Ui
Magento_CheckoutAddressSearch
Magento_CheckoutAgreements
Magento_Staging
Magento_CloudComponents
Magento_AdvancedCheckout
Magento_CmsGraphQl
Magento_CmsPageBuilderAnalytics
Magento_CmsPageBuilderAnalyticsStaging
Magento_CmsStaging
Magento_CmsUrlRewrite
Magento_CmsUrlRewriteGraphQl
Magento_Integration
Magento_ConfigurableProduct
Magento_ProductAlert
Magento_CatalogGraphQl
Magento_ConfigurableProductSales
Magento_Reports
Magento_Contact
Magento_Cookie
Magento_Cron
Magento_CurrencySymbol
Magento_CustomAttributeManagement
Magento_AdvancedRule
Magento_Analytics
Magento_CustomerBalance
Magento_CustomerSegment
Magento_CustomerFinance
Magento_CustomerGraphQl
Magento_CustomerImportExport
Magento_CatalogWidget
Magento_Vault
Magento_Deploy
Magento_Developer
Magento_Dhl
Magento_AdvancedSearch
Magento_DirectoryGraphQl
Magento_TargetRule
Magento_DownloadableGraphQl
Magento_ImportExport
Magento_Tax
Magento_Paypal
Magento_BundleGraphQl
Magento_CatalogSearch
Magento_Elasticsearch
Magento_WebsiteRestriction
Magento_Email
Magento_EncryptionKey
Magento_Enterprise
Magento_Eway
Magento_Fedex
Magento_Weee
Magento_GiftCardAccount
Magento_GiftCardGraphQl
Magento_GiftCardImportExport
Magento_GiftRegistry
Magento_GiftMessage
Magento_GiftMessageStaging
Magento_UrlRewrite
Magento_GiftWrapping
Magento_GiftWrappingStaging
Magento_GoogleAdwords
Magento_GoogleAnalytics
Magento_GoogleOptimizer
Magento_GoogleOptimizerStaging
Magento_PageCache
Magento_UrlRewriteGraphQl
Magento_GraphQlCache
Magento_GroupedProduct
Magento_GroupedImportExport
Magento_GroupedCatalogInventory
Magento_GroupedProductGraphQl
Magento_GroupedProductStaging
Magento_DownloadableImportExport
Magento_CatalogStaging
Magento_InstantPurchase
Magento_CatalogAnalytics
Magento_Inventory
Magento_InventoryAdminUi
Magento_InventoryApi
Magento_InventoryBundleProduct
Magento_InventoryBundleProductAdminUi
Magento_InventoryCatalog
Magento_InventorySales
Magento_InventoryCatalogAdminUi
Magento_InventoryCatalogApi
Magento_InventoryCatalogSearch
Magento_InventoryConfigurableProduct
Magento_InventoryConfigurableProductAdminUi
Magento_InventoryConfigurableProductIndexer
Magento_InventoryConfiguration
Magento_InventoryConfigurationApi
Magento_InventoryDistanceBasedSourceSelection
Magento_InventoryDistanceBasedSourceSelectionAdminUi
Magento_InventoryDistanceBasedSourceSelectionApi
Magento_InventoryElasticsearch
Magento_InventoryIndexer
Magento_InventorySalesApi
Magento_InventoryGroupedProduct
Magento_InventoryGroupedProductAdminUi
Magento_InventoryGroupedProductIndexer
Magento_InventoryImportExport
Magento_InventoryCache
Magento_InventoryLowQuantityNotification
Magento_InventoryLowQuantityNotificationAdminUi
Magento_InventoryLowQuantityNotificationApi
Magento_InventoryMultiDimensionalIndexerApi
Magento_InventoryProductAlert
Magento_InventorySalesAdminUi
Magento_InventorySalesFrontendUi
Magento_InventorySetupFixtureGenerator
Magento_InventoryShipping
Magento_Shipping
Magento_InventorySourceDeductionApi
Magento_InventorySourceSelection
Magento_InventorySourceSelectionApi
Magento_Invitation
Magento_LayeredNavigation
Magento_LayeredNavigationStaging
Magento_Logging
Magento_Marketplace
Magento_CatalogEvent
Magento_MessageQueue
Magento_CatalogRuleConfigurable
Magento_MsrpConfigurableProduct
Magento_MsrpGroupedProduct
Magento_MsrpStaging
Magento_MultipleWishlist
Magento_Multishipping
Magento_MysqlMq
Magento_NewRelicReporting
Magento_Newsletter
Magento_OfflinePayments
Magento_OfflineShipping
Magento_VersionsCms
Magento_PageBuilder
Magento_Banner
Magento_AdminGws
Magento_PaymentStaging
Magento_Braintree
Magento_PaypalCaptcha
Magento_PaypalOnBoarding
MSP_ReCaptcha
Magento_Persistent
Magento_PersistentHistory
Magento_PricePermissions
Magento_ConfigurableProductStaging
Magento_ProductVideo
Magento_ProductVideoStaging
Magento_PromotionPermissions
Magento_BannerPageBuilderAnalytics
Magento_QuoteAnalytics
Magento_QuoteGraphQl
Magento_ReleaseNotification
Magento_Reminder
Magento_CatalogStagingPageBuilder
Magento_RequireJs
Magento_ResourceConnections
Magento_Review
Magento_ReviewAnalytics
Magento_ReviewStaging
Magento_Reward
Magento_RewardGraphQl
Magento_SalesRuleStaging
Magento_Rma
Magento_RmaGraphQl
Magento_RmaStaging
Magento_Robots
Magento_Rss
Magento_AdvancedSalesRule
Magento_BannerCustomerSegment
Magento_SalesAnalytics
Magento_Signifyd
Magento_SalesGraphQl
Magento_SalesInventory
Magento_CatalogRuleStaging
Magento_RewardStaging
Magento_BannerPageBuilder
Magento_SampleData
Magento_ScalableCheckout
Magento_ScalableInventory
Magento_ScalableOms
Magento_ScheduledImportExport
Magento_CatalogPermissions
Magento_SearchStaging
Magento_CustomerAnalytics
Magento_SendFriend
Magento_SendFriendGraphQl
Magento_InventoryShippingAdminUi
Magento_SalesArchive
Magento_Sitemap
Magento_CheckoutStaging
Magento_StagingPageBuilder
Magento_Authorizenet
Magento_ConfigurableProductGraphQl
Magento_Support
Magento_Webapi
Magento_SwaggerWebapi
Magento_SwaggerWebapiAsync
Magento_Swatches
Magento_SwatchesGraphQl
Magento_SwatchesLayeredNavigation
Magento_DownloadableStaging
Magento_CatalogInventoryStaging
Magento_TaxGraphQl
Magento_TaxImportExport
Magento_Elasticsearch6
Magento_ThemeGraphQl
Magento_Tinymce3
Magento_Tinymce3Banner
Magento_Translation
Magento_CheckoutAddressSearchGiftRegistry
Magento_Ups
Magento_CatalogUrlRewriteStaging
Magento_CatalogUrlRewriteGraphQl
Magento_AsynchronousOperations
Magento_Usps
Magento_ConfigurableImportExport
Magento_Cybersource
Magento_VaultGraphQl
Magento_Version
Magento_GoogleTagManager
Magento_VisualMerchandiser
Magento_Swagger
Magento_WebapiAsync
Magento_WebapiSecurity
Magento_ElasticsearchCatalogPermissions
Magento_GiftCardStaging
Magento_WeeeGraphQl
Magento_WeeeStaging
Magento_PageBuilderAnalytics
Magento_BundleStaging
Magento_WishlistAnalytics
Magento_WishlistGraphQl
Magento_Worldpay
Amazon_Core
Amazon_Login
Amazon_Payment
Bronto_M2
Bronto_Connector
Bronto_Integration
Bronto_Contact
Bronto_Coupon
Bronto_Email
Bronto_Cart
Bronto_Product
Bronto_Browse
Bronto_Notification
Bronto_Optin
Bronto_Order
Bronto_Inventory
Bronto_Rating
Bronto_Redemption
ClassyLlama_AvaTax
Dotdigitalgroup_Email
Dotdigitalgroup_Enterprise
Ebizmarts_Mandrill
Fastly_Cdn
Klarna_Core
Klarna_Ordermanagement
Klarna_Kp
Magento_PaypalReCaptcha
MSP_TwoFactorAuth
MagicToolbox_MagicZoomPlus
Mirasvit_Core
Mirasvit_Dashboard
Mirasvit_Report
Mirasvit_Seo
Mirasvit_SeoAutolink
Mirasvit_SeoContent
Mirasvit_SeoFilter
Mirasvit_SeoMarkup
Mirasvit_SeoReport
Mirasvit_SeoSitemap
Mirasvit_SeoToolbar
ParadoxLabs_TokenBase
ParadoxLabs_Authnetcim
Wizkunde_WebSSO
Temando_Shipping
Vertex_Tax

List of disabled modules:
Magento_InventoryExportStockApi
Magento_InventoryReservations
Magento_InventoryReservationCli
Magento_InventoryReservationsApi
Magento_InventoryExportStock
Magento_InventoryGraphQl
```

**Comment by ryanpalmerweb** [comment]
We've got all of the Magento_Inventory* modules disabled on our install, however we are not reliant on stock control

I can see that your problem is being caused by the dependency in Magento_InventorySales - try turning this off, or if that causes more issue then what about turning the others on.

**Comment by LucasMali** [comment]
@ryanpalmerweb That was the fix, I ran through the config.php and disabled all the Magento_Inventory*

**Comment by sreenathnr** [comment]
@LucasMaliszewski I need to enable the MSI module.

**Comment by sdzhepa** [comment]
Based on multiple comments here, it seems this issue will be resolved faster if move it to the dedicated repository related only to Magento Inventory Project (a.k.a MSI)
