### ISSUE TITLE
Methods of getImageUploadConfigData()->getIsResizeEnabled() in uploader.phtml template returns null in back-end module

### ISSUE THREAD

**Issue by clion007** [magento/magento2#23825]
I found the issue when a third extension call on getImageUploadConfigData()->getIsResizeEnabled() method in vendor\magento\module-backend\view\adminhtml\templates\media\uploader.phtml and how should I update the extension to fix this error?

### Preconditions (*)

1. Magento version: 2.3.1 or later and 2.2.8 or later
2. apache2, php7.1.x, ubuntu latest version

### Steps to reproduce (*)

1. Try to load extension edit index block in site back-end
2. Any third extension call on \Magento\Backend\Block\Media\Uploader->getImageUploadConfigData()->getIsResizeEnabled() method in vendor\magento\module-backend\view\adminhtml\templates\media\uploader.phtml template

### Expected result (*)

1. Methods to update the extension and fix the issue
2. Return the getIsResizeEnabled method result and show the block in site back-end edit index page

### Actual result (*)

Stack trace:
--
  | #0 /*/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
  | #1 /*/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php-&gt;render(Object(Magento\Backend\Block\Media\Uploader), '/var/www/html/C...', Array)
  | #2 /*/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template-&gt;fetchView('/var/www/html/C...')
  | #3 /*/vendor/magento/module-backend/Block/Template.php(129): Magento\Framework\View\Element\Template-&gt;_toHtml()
  | #4 /*/vendor/magento/framework/View/Element/AbstractBlock.php(1094): Magento\Backend\Block\Template-&gt;_toHtml()
  | #5 /*/vendor/magento/framework/View/Element/AbstractBlock.php(1098): Magento\Framework\View\Element\AbstractBlock-&gt; in /*/vendor/magento/module-backend/view/adminhtml/templates/media/uploader.phtml on line 18

**Comment by clion007** [comment]
I fixed the bug in extension like below:
1. Go to the Vendor_dir\Module_dir\Block\Adminhtml\[model_dir\]Helper\Form\Gallery\Content.php
2. Add system class as below:
use Magento\Framework\App\ObjectManager;
use Magento\Backend\Block\DataProviders\ImageUploadConfig as ImageUploadConfigDataProvider;
3. Add param "ImageUploadConfigDataProvider $imageUploadConfigDataProvider = null" to the  public function __construct and try to get $this->imageUploadConfigDataProvider after parent::__construct($context, $jsonEncoder, $mediaConfig, $data) method as below:
        parent::__construct($context, $jsonEncoder, $mediaConfig, $data);
        try {
            /** Try for old magento version where ImageUploadConfigDataProvider does not exist */
            if (class_exists(ImageUploadConfigDataProvider::class)) {
                $this->imageUploadConfigDataProvider = $imageUploadConfigDataProvider
                    ?: ObjectManager::getInstance()->get(ImageUploadConfigDataProvider::class);
            } elseif (class_exists(ImageUploadConfigDataProvider::class)) {
                /** Workaround for Magento 2.2.8 or later and 2.3.1 or later */
                $this->imageUploadConfigDataProvider = ObjectManager::getInstance()->get(ImageUploadConfigDataProvider::class);
            }
        } catch (\Exception $e) {}
4. modify the addChild method in protected function _prepareLayout as below:
        $this->addChild(
            'uploader',
            \Magento\Backend\Block\Media\Uploader::class,
            ['image_upload_config_data' => $this->imageUploadConfigDataProvider]
        );
5. OK, now it should worked.
