### ISSUE TITLE
Maximum shipping amount allowed to refund is: $0.00

### ISSUE THREAD

**Issue by kassner** [magento/magento2#2385]
Hi,

Currently is not possible to create a second partial refund after refunding the entire shipping amount, even if there is an amount available for refund.

Steps to reproduce:

1. Create an order with 2 products and any shipping amount;
2. Create an invoice with all items + shipping amount;
3. Click the button "Credit memo" button in order view;
4. Remove one product from the form but leave the shipping amount untouched (defaults to full amount);
5. Click "Refund Offline";
6. Credit memo should be created correctly;
7. Click in "Credit memo" button again;
8. Instead of the refund form, the error "Maximum shipping amount allowed to refund is: $0.00" is shown (printed exception on the body with developer mode on).

Other info:

1. You can create as many credit memos as is possible within the rules, as long as the shipping amount not yet refunded is above $0.00;
2. If you create a credit memo only for the shipping amount, the next time you come back to the for you still can refund the shipping amount that was already refunded along with an item, and it works, but the next time (3rd) you try to refund an item that was left behind, you get the error `The most money available to refund is $0.00.`.

Tested version: `2.0.0-rc2`

Stack trace:

```
#0 /var/www/app/code/Magento/Sales/Model/Order/Creditmemo.php(338): Magento\Sales\Model\Order\Creditmemo\Total\Shipping->collect(Object(Magento\Sales\Model\Order\Creditmemo))
#1 /var/www/app/code/Magento/Sales/Model/Order/CreditmemoFactory.php(79): Magento\Sales\Model\Order\Creditmemo->collectTotals()
#2 /var/www/app/code/Magento/Sales/Controller/Adminhtml/Order/CreditmemoLoader.php(211): Magento\Sales\Model\Order\CreditmemoFactory->createByOrder(Object(Magento\Sales\Model\Order), Array)
#3 /var/www/app/code/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/NewAction.php(64): Magento\Sales\Controller\Adminhtml\Order\CreditmemoLoader->load()
#4 /var/www/var/generation/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/NewAction/Interceptor.php(25): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction->execute()
#5 /var/www/lib/internal/Magento/Framework/App/Action/Action.php(102): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor->execute()
#6 /var/www/app/code/Magento/Backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#7 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /var/www/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#9 /var/www/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor->___callParent('dispatch', Array)
#10 /var/www/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor), Array, 'adminAuthentica...')
#11 /var/www/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(135): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#12 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /var/www/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#14 /var/www/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor), Array, 'designLoader')
#15 /var/www/lib/internal/Magento/Framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#16 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 /var/www/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#18 /var/www/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor), Array, 'adminMassaction...')
#19 /var/www/app/code/Magento/Backend/App/Action/Plugin/MassactionKey.php(33): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /var/www/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#22 /var/www/var/generation/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/NewAction/Interceptor.php(40): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor->___callPlugins('dispatch', Array, Array)
#23 /var/www/lib/internal/Magento/Framework/App/FrontController.php(55): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#24 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /var/www/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#26 /var/www/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#27 /var/www/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#28 /var/www/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#29 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /var/www/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#31 /var/www/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'storeCookieVali...')
#32 /var/www/app/code/Magento/Store/Model/Plugin/StoreCookie.php(78): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#33 [internal function]: Magento\Store\Model\Plugin\StoreCookie->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34 /var/www/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#35 /var/www/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /var/www/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /var/www/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#38 /var/www/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#39 {main}
```

Thanks!

**Comment by valdislav** [comment]
@kassner Thank you for reporting this issue. Internal issue MAGETWO-45612 is created for this.

**Comment by NadiyaS** [comment]
Hi @kassner,
 fix was delivered to mainline. Please see commit [212a2d](https://github.com/magento/magento2/commit/212a2d8a6a86ef2f661268247e83f7c0072777c6)
