### ISSUE TITLE
Can not save the product after MSRP modules are disabled

### ISSUE THREAD

**Issue by gaurangpadhiyar007** [magento/magento2#24065]
### Preconditions (*)

Magento version 2.3.2

### Steps to reproduce (*)

1. Disable MSRP modules
2. Try to save the product.

### Expected result (*)

1. Save the product.

### Actual result (*)

Fatal error: Uncaught Error: Cannot instantiate interface Magento\InventoryApi\Api\SourceItemRepositoryInterface in vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50 Stack trace: #0 vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Invento...') #1 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Invento...') #2 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Invento...', NULL, 'sourceItemRepos...', 'Magento\\Invento...') #3 vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50

**Comment by gaurangpadhiyar007** [comment]
Auto resolved,
