### ISSUE TITLE
Couldnot Place Order - A server error stopped your order from being placed. Please try to place your order again

### ISSUE THREAD

**Issue by ninjacoder30** [magento/magento2#24133]
Magento 2.3.2 Enterprise Edition.

Check / Money order :- Payment Method.

On Checkout - Place Order getting following error

```
message: "A server error stopped your order from being placed. Please try to place your order again."
trace: "#0 /var/www/vhosts/mt-phoenix/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(100, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))↵#1 /var/www/vhosts/mt-phoenix/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)↵#2 /var/www/vhosts/mt-phoenix/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}(100, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))↵#3 /var/www/vhosts/mt-phoenix/generated/code/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(26): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)↵#4 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(100, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))↵#5 /var/www/vhosts/mt-phoenix/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)↵#6 /var/www/vhosts/mt-phoenix/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))↵#7 /var/www/vhosts/mt-phoenix/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))↵#8 /var/www/vhosts/mt-phoenix/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)↵#9 /var/www/vhosts/mt-phoenix/vendor/magento/module-company/Plugin/Webapi/Controller/RestPlugin.php(84): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))↵#10 /var/www/vhosts/mt-phoenix/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Company\Plugin\Webapi\Controller\RestPlugin->aroundDispatch(Object(Magento\Webapi\Controller\Rest\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))↵#11 /var/www/vhosts/mt-phoenix/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))↵#12 /var/www/vhosts/mt-phoenix/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)↵#13 /var/www/vhosts/mt-phoenix/vendor/magento/framework/App/Http.php(137): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))↵#14 /var/www/vhosts/mt-phoenix/vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http->launch()↵#15 /var/www/vhosts/mt-phoenix/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))↵#16 {main}"
```

**Comment by engcom-Bravo** [comment]
Hi, @saigadekar. Its not a core bug of Magento - the one this repository is intended for. If it were that nobody else using 2.3.2 could place an order with Check/Money Order Payment Method. So please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. Thanks for applying.

**Comment by chapagain** [comment]
In my case, it was the sequence tables missing for the store.

**var/log/exception.log**

> Next Zend_Db_Statement_Exception: SQLSTATE[42S02]: Base table or view
> not found: 1146 Table 'xxx.sequence_order_3' doesn't exist, query was:
> INSERT INTO `sequence_order_3` () VALUES () in
> /app/xxx/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:109

`n98-magerun2.phar sales:sequence:add [store_id]` didn't work for me.

So, I had to manually create the missing sequence tables. 

    CREATE TABLE `sequence_order_3` (`sequence_value` int(10) unsigned NOT NULL AUTO_INCREMENT, PRIMARY KEY (`sequence_value`));
    CREATE TABLE `sequence_invoice_3` (`sequence_value` int(10) unsigned NOT NULL AUTO_INCREMENT, PRIMARY KEY (`sequence_value`));
    CREATE TABLE `sequence_creditmemo_3` (`sequence_value` int(10) unsigned NOT NULL AUTO_INCREMENT, PRIMARY KEY (`sequence_value`));
    CREATE TABLE `sequence_shipment_3` (`sequence_value` int(10) unsigned NOT NULL AUTO_INCREMENT, PRIMARY KEY (`sequence_value`));
    CREATE TABLE `sequence_rma_item_3` (`sequence_value` int(10) unsigned NOT NULL AUTO_INCREMENT, PRIMARY KEY (`sequence_value`));
 
And, that fixed the issue for me.
