### ISSUE TITLE
/rest/default/schema - rest API schema request returns 500 error

### ISSUE THREAD

**Issue by magnetic5355** [magento/magento2#2417]
Release 2.0 (worked on RC2) - schema will not load. API stil functions.

[2015-11-19 03:26:10] main.CRITICAL: exception 'LogicException' with message 'Report ID: webapi-564d4152b7a95; Message: Class "array[]" does not exist. Please note that namespace must be specified.' in FAKEPATH\lib\internal\Magento\Framework\Webapi\ErrorProcessor.php:194
Stack trace:
#0 FAKEPATH\lib\internal\Magento\Framework\Webapi\ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(LogicException))
#1 FAKEPATH\app\code\Magento\Webapi\Controller\Rest.php(163): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(LogicException))
#2 FAKEPATH\var\generation\Magento\Webapi\Controller\Rest\Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 FAKEPATH\lib\internal\Magento\Framework\App\Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 FAKEPATH\lib\internal\Magento\Framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 FAKEPATH\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []

**Comment by choukalos** [comment]
Hello @caesarcxiv I'm on GA and am not able to reproduce this issue.  I've tried with both the ?services=all parameter and without it.

I can use the GUI to see the schema:  http://BASEURL/swagger which really just calls the following to get the info http://BASEURL/rest/default/schema?services=all .

**Comment by magnetic5355** [comment]
Hello i've tried these : http://BASEURL/swagger, http://BASEURL/rest/default/schema?services=all and http://BASEURL/rest/default/schema and I still get the same error logged above.

**Comment by alankent** [comment]
The error message below makes me suspect there is a service contract that is not specifying the fully qualified path name to a type. This is a guess however. Do you have any of your own service contracts defined? Can you find "array[]" or even "array" there somewhere?

```
    Class "array[]" does not exist. Please note that namespace must be specified.
```

The error message could certainly do with improving to provide better context. If we can find the cause of the error we can look at fixing up the error message for future similar situations.

**Comment by maksek** [comment]
closing due inactivity from @caesarcxiv on @alankent last request.

**Comment by tim-reynolds** [comment]
@maksek I would ask that this possibly be reopened. I am having this issue. Specifically with regard to the system generating information for the interface \Magento\Sales\Api\ShipOrderInterface.php 

The error they are having is caused by the parameters to the execute function (for parameter $items, although the issue also lies with $tracks and $packages). 

We are currently running on : 
Magento 2 Enterprise 2.1.2. 
PHP 7.0.10-2
Apache 2.4.7

It seems to me as though the reflection classes are not grabbing the actual class type from the doc block above the method and instead are passing in array[] as the type for the parameter.

And, now, thinking about it, I can see in the class: magento2/vendor/magento/framework/Reflection/TypeProcessor.php

That the regular expression matching for the parameter in the function getParamType is failing to match the param in the docblock for this particular parameter... but not for others. I don't know why. Perhaps I have stumbled upon a bug with the regular expression engine in the version of PHP we are using. I am upgrading my local version just to be certain.  Upgraded to 7.0.14 and it is still happening. 

I have created a simple test program that uses base64 encoded values for the regular expressions and the doc blocks from 3 cases (2 that pass, one that fails) to illustrate the issue. I encoded the strings to any possible differences such as newline characters will be preserved. Here is that test program: 

```
<?php
    
    $test_cases = array(
        array(
            'title' => 'Working Test 1',
            'block' => 'QHBhcmFtIHN0cmluZ1tdICRzdG9yZUNvZGVzCkByZXR1cm4gXE1hZ2VudG9cU3RvcmVcQXBpXERhdGFcU3RvcmVDb25maWdJbnRlcmZhY2VbXQogICAg',
            'regex' => 'L1xAcGFyYW1ccysoW1x3XFxfXStcW1xdKVxzK1wkc3RvcmVDb2Rlcwov'
            ),array(
            'title' => 'Working Test 2',
            'block' => 'QXNzaWduIGEgcHJvZHVjdCBsaW5rIHRvIGFub3RoZXIgcHJvZHVjdAoKQHBhcmFtIHN0cmluZyAkc2t1CkBwYXJhbSBcTWFnZW50b1xDYXRhbG9nXEFwaVxEYXRhXFByb2R1Y3RMaW5rSW50ZXJmYWNlW10gJGl0ZW1zCkB0aHJvd3MgXE1hZ2VudG9cRnJhbWV3b3JrXEV4Y2VwdGlvblxOb1N1Y2hFbnRpdHlFeGNlcHRpb24KQHRocm93cyBcTWFnZW50b1xGcmFtZXdvcmtcRXhjZXB0aW9uXENvdWxkTm90U2F2ZUV4Y2VwdGlvbgpAcmV0dXJuIGJvb2wKICAgIA==',
            'regex' => 'L1xAcGFyYW1ccysoW1x3XFxfXStcW1xdKVxzK1wkaXRlbXMKLw=='
            ),array(
            'title' => 'Failing Test 1',
            'block' => 'Q3JlYXRlcyBuZXcgU2hpcG1lbnQgZm9yIGdpdmVuIE9yZGVyLg0KDQpAcGFyYW0gaW50ICRvcmRlcklkDQpAcGFyYW0gXE1hZ2VudG9cU2FsZXNcQXBpXERhdGFcU2hpcG1lbnRJdGVtQ3JlYXRpb25JbnRlcmZhY2VbXSAkaXRlbXMNCkBwYXJhbSBib29sICRub3RpZnkNCkBwYXJhbSBib29sICRhcHBlbmRDb21tZW50DQpAcGFyYW0gXE1hZ2VudG9cU2FsZXNcQXBpXERhdGFcU2hpcG1lbnRDb21tZW50Q3JlYXRpb25JbnRlcmZhY2V8bnVsbCAkY29tbWVudA0KQHBhcmFtIFxNYWdlbnRvXFNhbGVzXEFwaVxEYXRhXFNoaXBtZW50VHJhY2tDcmVhdGlvbkludGVyZmFjZVtdICR0cmFja3MNCkBwYXJhbSBcTWFnZW50b1xTYWxlc1xBcGlcRGF0YVxTaGlwbWVudFBhY2thZ2VDcmVhdGlvbkludGVyZmFjZVtdICRwYWNrYWdlcw0KQHBhcmFtIFxNYWdlbnRvXFNhbGVzXEFwaVxEYXRhXFNoaXBtZW50Q3JlYXRpb25Bcmd1bWVudHNJbnRlcmZhY2V8bnVsbCAkYXJndW1lbnRzDQpAcmV0dXJuIGludCBJZCBvZiBjcmVhdGVkIFNoaXBtZW50Lg0KICAgIA==',
            'regex' => 'L1xAcGFyYW1ccysoW1x3XFxfXStcW1xdKVxzK1wkaXRlbXMKLw=='
            ),
    );
    
    foreach($test_cases as $test_case)
    {
        $matches = array();
        $block = base64_decode($test_case['block']);
        $regex = base64_decode($test_case['regex']);
        $title = $test_case['title'];
        $result =  preg_match($regex, $block, $matches);
        if(!$result)
        {
            echo "TEST CASE ($title) FAILED. No Matches.\n";
        }
        else
        {
            echo "TEST CASE ($title) PASSED! Matches:\n";
            print_r($matches);
    
        }
    }
    echo "DONE\n";
```

The output from that test case is: 

```
TEST CASE (Working Test 1) PASSED! Matches:
Array
(
    [0] => @param string[] $storeCodes

    [1] => string[]
)
TEST CASE (Working Test 2) PASSED! Matches:
Array
(
    [0] => @param \Magento\Catalog\Api\Data\ProductLinkInterface[] $items

    [1] => \Magento\Catalog\Api\Data\ProductLinkInterface[]
)
TEST CASE (Failing Test 1) FAILED. No Matches.
DONE
```


The stack trace we see is:

```
[2016-12-07 21:49:38] report.CRITICAL: LogicException: Class "array[]" does not exist. Please note that namespace must be specified. in /var/www/html/magento2/vendor/magento/framework/Reflection/TypeProcessor.php:156
Stack trace:
#0 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\Reflection\TypeProcessor->register('array[]')
#1 /var/www/html/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\Reflection\TypeProcessor\Interceptor->___callParent('register', Array)
#2 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'register', Object(Magento\Framework\Reflection\TypeProcessor\Interceptor), Array, 'add_methods_typ...')
#3 /var/www/html/magento2/app/code/Client/Extension/Model/Plugin/AddMethodsTypeProcessor.php(18): Magento\Framework\Reflection\TypeProcessor\Interceptor->Magento\Framework\Interception\{closure}('array[]')
#4 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(142): LMR\Ebridge\Model\Plugin\AddMethodsTypeProcessor->aroundRegister(Object(Magento\Framework\Reflection\TypeProcessor\Interceptor), Object(Closure), 'array[]')
#5 /var/www/html/magento2/var/generation/Magento/Framework/Reflection/TypeProcessor/Interceptor.php(25): Magento\Framework\Reflection\TypeProcessor\Interceptor->___callPlugins('register', Array, Array)
#6 /var/www/html/magento2/vendor/magento/module-webapi/Model/Config/ClassReflector.php(91): Magento\Framework\Reflection\TypeProcessor\Interceptor->register('array[]')
#7 /var/www/html/magento2/vendor/magento/module-webapi/Model/Config/ClassReflector.php(72): Magento\Webapi\Model\Config\ClassReflector->extractMethodData(Object(Zend\Code\Reflection\MethodReflection))
#8 /var/www/html/magento2/vendor/magento/module-webapi/Model/ServiceMetadata.php(119): Magento\Webapi\Model\Config\ClassReflector->reflectClassMethods('Magento\\Sales\\A...', Array)
#9 /var/www/html/magento2/vendor/magento/module-webapi/Model/ServiceMetadata.php(148): Magento\Webapi\Model\ServiceMetadata->initServicesMetadata()
#10 /var/www/html/magento2/vendor/magento/module-webapi/Model/ServiceMetadata.php(165): Magento\Webapi\Model\ServiceMetadata->getServicesConfig()
#11 /var/www/html/magento2/vendor/magento/module-webapi/Model/Soap/Wsdl/Generator.php(366): Magento\Webapi\Model\ServiceMetadata->getServiceMetadata('lMROrdersplitSu...')
#12 /var/www/html/magento2/vendor/magento/module-webapi/Model/AbstractSchemaGenerator.php(169): Magento\Webapi\Model\Soap\Wsdl\Generator->getServiceMetadata('lMROrdersplitSu...')
#13 /var/www/html/magento2/vendor/magento/module-webapi/Model/Soap/Wsdl/Generator.php(374): Magento\Webapi\Model\AbstractSchemaGenerator->getAllowedServicesMetadata(Array)
#14 /var/www/html/magento2/vendor/magento/module-webapi/Model/AbstractSchemaGenerator.php(104): Magento\Webapi\Model\Soap\Wsdl\Generator->getAllowedServicesMetadata(Array)
#15 /var/www/html/magento2/vendor/magento/module-webapi/Model/Soap/Server.php(140): Magento\Webapi\Model\AbstractSchemaGenerator->generate(Array, 'http', 'dev.lmr.com', 'http://dev.lmr....')
#16 /var/www/html/magento2/vendor/magento/module-webapi/Model/Soap/Server.php(123): Magento\Webapi\Model\Soap\Server->getWsdlLocalUri()
#17 /var/www/html/magento2/var/generation/Magento/Webapi/Model/Soap/Server/Proxy.php(95): Magento\Webapi\Model\Soap\Server->handle()
#18 /var/www/html/magento2/vendor/magento/module-webapi/Controller/Soap.php(145): Magento\Webapi\Model\Soap\Server\Proxy->handle()
#19 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Webapi\Controller\Soap->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/html/magento2/var/generation/Magento/Webapi/Controller/Soap/Interceptor.php(26): Magento\Webapi\Controller\Soap\Interceptor->___callPlugins('dispatch', Array, Array)
#21 /var/www/html/magento2/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Soap\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#23 /var/www/html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#24 {main}

Next Exception: Report ID: webapi-584883f2c4ed3; Message: Class "array[]" does not exist. Please note that namespace must be specified. in /var/www/html/magento2/vendor/magento/framework/Webapi/ErrorProcessor.php:195
Stack trace:
#0 /var/www/html/magento2/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(LogicException))
#1 /var/www/html/magento2/var/generation/Magento/Framework/Webapi/ErrorProcessor/Proxy.php(95): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(LogicException))
#2 /var/www/html/magento2/vendor/magento/module-webapi/Controller/Soap.php(181): Magento\Framework\Webapi\ErrorProcessor\Proxy->maskException(Object(LogicException))
#3 /var/www/html/magento2/vendor/magento/module-webapi/Controller/Soap.php(148): Magento\Webapi\Controller\Soap->_prepareErrorResponse(Object(LogicException))
#4 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Webapi\Controller\Soap->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /var/www/html/magento2/var/generation/Magento/Webapi/Controller/Soap/Interceptor.php(26): Magento\Webapi\Controller\Soap\Interceptor->___callPlugins('dispatch', Array, Array)
#6 /var/www/html/magento2/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Soap\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /var/www/html/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#8 /var/www/html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#9 {main} [] []
```

**Comment by tim-reynolds** [comment]
I added a piece of output code to my test case, to output the files using json_encoding so I could see exactly what the characters used are...

This is an issue of \r\n vs \n in the file in question. SIGH.

I would suggest updating the regular expression to include an optional \r

So line 558 in magento2/vendor/magento/framework/Reflection/TypeProcessor.php goes from:
`$pattern = "/\@param\s+([\w\\\_]+\[\])\s+\\\${$param->getName()}\n/";`

To 

`$pattern = "/\@param\s+([\w\\\_]+\[\])\s+\\\${$param->getName()}\r?\n/";`

I would send a pull request, but I don't have time this minute to create a unit test (my environment is seutp for enterprise, not community)
