### ISSUE TITLE
Error 500 on checkout while payment is "successful"

### ISSUE THREAD

**Issue by charliecc07** [magento/magento2#24448]
Trying to place an order on a multi-store site and this problem only affects one store based in the US. Go through checkout as normal, and just as you hit place an order button to confirm payment -> get an error 500. According to Adyen, the payment was taken but the callback returns without a token leading to the error 500.

I've got this error:

"1567179274000","08/30/2019 10:34:34.000 -0500","[30-Aug-2019 15:34:34 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Email\Model\Template::setVars() must be of the type array, null given, called in /srv/magento/swarovski-stage/deploys/0.0.0.420/vendor/magento/framework/Mail/Template/TransportBuilder.php on line 270 and defined in /srv/magento/swarovski-stage/deploys/0.0.0.420/vendor/magento/module-email/Model/Template.php:403
Stack trace:
#0 /srv/magento/swarovski-stage/deploys/0.0.0.420/vendor/magento/framework/Mail/Template/TransportBuilder.php(270): Magento\Email\Model\Template->setVars(NULL)
#1 /srv/magento/swarovski-stage/deploys/0.0.0.420/vendor/magento/framework/Mail/Template/TransportBuilder.php(281): Magento\Framework\Mail\Template\TransportBuilder->getTemplate()
#2 /srv/magento/swarovski-stage/deploys/0.0.0.420/vendor/magento/framework/Mail/Template/TransportBuilder.php(241): Magento\Framework\Mail\Template\TransportBuilder->prepareMessage()
#3 /srv/magento/swarovski-stage/deploys/0.0.0.420/vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php(78): Magento in /srv/magento/swarovski-stage/deploys/0.0.0.420/vendor/magento/module-email/Model/Template.php on line 403","swarovski-magento-web-i-0c73713b6c2498ad3","1178","PHP Error Logs","swarovski/stage/

**Comment by shikhamis11** [comment]
hello @charliecc07 
Thank you for your report. Please correct the format of the issue you can check 
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by shikhamis11** [comment]
@charliecc07 I am closing this issue due to inactivity ... feel free to reopen this after correcting the issue description

**Comment by domnoble** [comment]
+1 ive got this same issue on a production website, spent the last couple of days trying to fix it to no avail, this error crops up with multiple third party smtp modules, the emails still send but when it returns back to the customer they get this error, its got to be related to magento or possibly a messed up migration, perhaps eav_attributes ?

**Comment by domnoble** [comment]
using magento 2.3.2 this is the error i get :

```Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Email\Model\Template::setVars() must be of the type array, null given, called in /usr/local/apache2/htdocs/vendor/magento/framework/Mail/Template/TransportBuilder.php on line 368 and defined in /usr/local/apache2/htdocs/vendor/magento/module-email/Model/Template.php:403 Stack trace: #0 /usr/local/apache2/htdocs/vendor/magento/framework/Mail/Template/TransportBuilder.php(368): Magento\Email\Model\Template->setVars(NULL) #1 /usr/local/apache2/htdocs/vendor/magento/framework/Mail/Template/TransportBuilder.php(380): Magento\Framework\Mail\Template\TransportBuilder->getTemplate() #2 /usr/local/apache2/htdocs/vendor/magento/framework/Mail/Template/TransportBuilder.php(337): Magento\Framework\Mail\Template\TransportBuilder->prepareMessage() #3 /usr/local/apache2/htdocs/vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php(91): Magento\Framework\Mail\Template\TransportBuilder->getTransport() #4 /usr/local/apache2/htdocs/vendor/magento/module-sales/Model/Order in /usr/local/apache2/htdocs/vendor/magento/module-email/Model/Template.php on line 403```

**Comment by domnoble** [comment]
disabling third party smtp modules makes it go away but then obviously the emails get dropped because they arent signed

**Comment by vishalpatel14** [comment]
This issue still exit in core 2.3.3. Its not regarding any 3 party SMTP issue or any Email sender name issue.
Below is the same debug trace of code same as above.

<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to Magento\Email\Model\Template::setVars() must be of the type array, null given, called in vendor/magento/framework/Mail/Template/TransportBuilder.php on line 368 and defined in vendor/magento/module-email/Model/Template.php:403
Stack trace:
#0 vendor/magento/framework/Mail/Template/TransportBuilder.php(368): Magento\Email\Model\Template-&gt;setVars(NULL)
#1 vendor/magento/framework/Mail/Template/TransportBuilder.php(380): Magento\Framework\Mail\Template\TransportBuilder-&gt;getTemplate()
#2 vendor/magento/framework/Mail/Template/TransportBuilder.php(337): Magento\Framework\Mail\Template\TransportBuilder-&gt;prepareMessage()
#3 vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php(91): Magento\Framework\Mail\Template\TransportBuilder-&gt;getTransport()
#4 vendor/magento/mod in <b>vendor/magento/module-email/Model/Template.php</b> on line <b>403</b><br />

**Comment by nicholasscottfish** [comment]
This issue is not resolved, I have raised a PR that fixes it:

https://github.com/magento/magento2/pull/25758

**Comment by vishalpatel14** [comment]
Hello @nicholasscottfish 

This issue have been resolved by some one in the development branch and i got response that it will be deployed in new version in 2.3.4. It does not need change in the code the file you mention.

It has the issue with this file below is the path of file and the solution.

vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php

And the function in the file should be like this.

public function sendCopyTo()
    {
        $copyTo = $this->identityContainer->getEmailCopyTo();

        if (!empty($copyTo) && $this->identityContainer->getCopyMethod() == 'copy') {
           
            foreach ($copyTo as $email) {
                 $this->configureEmailTemplate();
                $this->transportBuilder->addTo($email);
                $transport = $this->transportBuilder->getTransport();
                $transport->sendMessage();
            }
        }
    }

Hence above is the solution.

**Comment by nicholasscottfish** [comment]
Hi @vishalpatel14,

Thanks for the update on this, do you happen to have a link to the fix so that I can access the diff file?

I still do think the default value should be an empty [] instead of null as null would never be an accepted value, but this looks to be a more concrete fix.

Thanks for sharing!

**Comment by PaulEmich** [comment]
> Hi @vishalpatel14,
> 
> Thanks for the update on this, do you happen to have a link to the fix so that I can access the diff file?
> 
> I still do think the default value should be an empty [] instead of null as null would never be an accepted value, but this looks to be a more concrete fix.
> 
> Thanks for sharing!

Not sure if you are still looking for the diff, but this commit is merged in the 2.4 branch:
https://github.com/magento/magento2/commit/dbf2c29bef8ec4a768156bd7ace0c99647bec631#diff-fd5e8d031335fde4387c31484dfcb308

**Comment by vishalpatel14** [comment]
Hi @pauluse 

Yes I got it I can see the change code mention in your comment link. Hence seems like it will be available in next release.

Thanks
