### ISSUE TITLE
Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Url\RouteParamsPreprocessorInterface

### ISSUE THREAD

**Issue by kweste** [magento/magento2#24649]
I used one-click install to install my theme, transferred over all of the theme files and ran:

` php bin/magento setup:upgrade`

but I got the following error:

```
Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Url\RouteParamsPreprocessorInterface in /home/customer/www/xxx/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:73
Stack trace:
#0 /home/customer/www/xxx/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#1 /home/customer/www/xxx/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#2 /home/customer/www/xxx/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'routeParamsPrep...', 'Magento\\Framewo...')
#3 /home/customer/www/xxx/public_html/vendor/magento/framework/ObjectManager/Factory/D in /home/customer/www/xxx/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 73

```

**To recreate:** Fresh install of Magento, copy over theme files for Necessary theme, and then run php mangeto/bin setup:upgrade

**I've tried** clearing my cache and generation folder and var/* but it doesn't make a difference

Someone please advise :(

**Comment by engcom-Charlie** [comment]
Hello @kweste !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the Necessary theme support, for advice or general discussion about this issue.
Thanks for your report!
