### ISSUE TITLE
Running the integration tests fails with 'Error: Cannot instantiate interface...'

### ISSUE THREAD

**Issue by psdevhh** [magento/magento2#24664]
### Preconditions (*)

1. Magento 2.3-develop branch was installed (PHP 7.2, MySQL 5.7.26, both frontend & admin work fine)
2. M2 was configured to run integration tests as described at [https://devdocs.magento.com/guides/v2.3/test/integration/integration_test_execution.html](https://devdocs.magento.com/guides/v2.3/test/integration/integration_test_execution.html)

### Steps to reproduce (*)

1. Install Magento 2.3-develop branch
2. `cd dev/tests/integration`
3. `../../../vendor/bin/phpunit`

### Expected result (*)

1. Expected to run the integration test suite

### Actual result (*)

```
ps@~/Projects/magento2/dev/tests/integration(2.3-develop)$ ../../../vendor/bin/phpunit
PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\Framework\App\DesignInterface in /Users/ps/Projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /Users/ps/Projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#1 /Users/ps/Projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#2 /Users/ps/Projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'design', 'Magento\\Framewo...')
#3 /Users/ps/Projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime(' in /Users/ps/Projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php on line 50

Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\App\DesignInterface in /Users/ps/Projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /Users/ps/Projects/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#1 /Users/ps/Projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#2 /Users/ps/Projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'design', 'Magento\\Framewo...')
#3 /Users/ps/Projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime(' in /Users/ps/Projects/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php on line 50

=== Memory Usage System Stats ===
Memory usage (OS):	28.50M (203.57% of 14.00M reported by PHP)
Estimated memory leak:	14.50M (50.88% of used memory)
```

**Comment by engcom-Charlie** [comment]
Hello @psdevhh .
I reproduced same errors when i had bad configuration of `install-config-mysql.php.dist` file.
Please check the data of this file and if you don't use Redis please detele this: 
`  'amqp-host' => 'localhost',
    'amqp-port' => '5672',
    'amqp-user' => 'guest',
    'amqp-password' => 'guest',`.
I have to close this issue, but i am waiting for your response.
Thanks for your report!

**Comment by psdevhh** [comment]
Hi @engcom-Charlie
You're right, turns out I had to specify `localhost` instead of `127.0.0.1` as mysql host to get the tests working. As usual, the error messages are very helpful in such cases ;) Thanks a lot for your help!
