### ISSUE TITLE
Magento Installation ReflectionException 

### ISSUE THREAD

**Issue by tmudarikwa** [magento/magento2#2501]
Hi there, 

I am trying to install Magento 2 Community Edition on an Ubuntu system over an existing database that we used for our Magento 1.9.2 and some prior versions. I managed to get to 71% through the installation but I keep getting a Reflection Exception that I have tried to resolve by applying some of the suggested fixes like deleting the [Magento2 folder]/var/generation folder. But all these hasn't seem to be a success for me. 

The console log provides the following information : 

```
Module 'Magento_Catalog':
Installing data.. 
[ERROR] exception 'ReflectionException' with message 'Class catalog/category_attribute_backend_urlkey does not exist' in /var/www/html/frewprocess/vendor/magento/framework/Code/Reader/ClassReader.php:19
Stack trace:
#0 /var/www/html/frewprocess/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('catalog/categor...')
#1 /var/www/html/frewprocess/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('catalog/categor...')
#2 /var/www/html/frewprocess/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('catalog/categor...')
#3 /var/www/html/frewprocess/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('catalog/categor...', Array)
#4 /var/www/html/frewprocess/vendor/magento/framework/Validator/UniversalFactory.php(36): Magento\Framework\ObjectManager\ObjectManager->create('catalog/categor...', Array)
#5 /var/www/html/frewprocess/vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php(498): Magento\Framework\Validator\UniversalFactory->create('catalog/categor...')
#6 /var/www/html/frewprocess/var/generation/Magento/Catalog/Model/ResourceModel/Eav/Attribute/Interceptor.php(1103): Magento\Eav\Model\Entity\Attribute\AbstractAttribute->getBackend()
#7 /var/www/html/frewprocess/vendor/magento/module-catalog/Model/ResourceModel/AbstractResource.php(205): Magento\Catalog\Model\ResourceModel\Eav\Attribute\Interceptor->getBackend()
#8 /var/www/html/frewprocess/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(1033): Magento\Catalog\Model\ResourceModel\AbstractResource->_setAttributeValue(Object(Magento\Catalog\Model\Category\Interceptor), Array)
#9 /var/www/html/frewprocess/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(996): Magento\Eav\Model\Entity\AbstractEntity->_loadModelAttributes(Object(Magento\Catalog\Model\Category\Interceptor))
#10 /var/www/html/frewprocess/vendor/magento/module-catalog/Model/ResourceModel/AbstractResource.php(635): Magento\Eav\Model\Entity\AbstractEntity->load(Object(Magento\Catalog\Model\Category\Interceptor), 1, NULL)
#11 /var/www/html/frewprocess/var/generation/Magento/Catalog/Model/ResourceModel/Category/Interceptor.php(362): Magento\Catalog\Model\ResourceModel\AbstractResource->load(Object(Magento\Catalog\Model\Category\Interceptor), 1, NULL)
#12 /var/www/html/frewprocess/vendor/magento/framework/Model/AbstractModel.php(516): Magento\Catalog\Model\ResourceModel\Category\Interceptor->load(Object(Magento\Catalog\Model\Category\Interceptor), 1, NULL)
#13 /var/www/html/frewprocess/var/generation/Magento/Catalog/Model/Category/Interceptor.php(1480): Magento\Framework\Model\AbstractModel->load(1, NULL)
#14 /var/www/html/frewprocess/vendor/magento/module-catalog/Setup/InstallData.php(49): Magento\Catalog\Model\Category\Interceptor->load(1)
#15 /var/www/html/frewprocess/setup/src/Magento/Setup/Model/Installer.php(798): Magento\Catalog\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext))
#16 /var/www/html/frewprocess/setup/src/Magento/Setup/Model/Installer.php(746): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data')
#17 [internal function]: Magento\Setup\Model\Installer->installDataFixtures()
#18 /var/www/html/frewprocess/setup/src/Magento/Setup/Model/Installer.php(331): call_user_func_array(Array, Array)
#19 /var/www/html/frewprocess/setup/src/Magento/Setup/Controller/Install.php(97): Magento\Setup\Model\Installer->install(Array)
#20 /var/www/html/frewprocess/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#21 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#22 /var/www/html/frewprocess/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#23 /var/www/html/frewprocess/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#24 /var/www/html/frewprocess/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#25 /var/www/html/frewprocess/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#26 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#27 /var/www/html/frewprocess/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#28 /var/www/html/frewprocess/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#29 /var/www/html/frewprocess/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#30 /var/www/html/frewprocess/setup/index.php(31): Zend\Mvc\Application->run()
#31 {main}
```

**Comment by mazhalai** [comment]
This looks weird `Class catalog/category_attribute_backend_urlkey does not exist` since in M2 we do not use underscores in classnames. Please create a new database, or clean the existing one (or drop and recreate database) and try again.

**Comment by tmudarikwa** [comment]
Thank you for the prompt response @mazhalai . Will start on the clean up process and see how that goes.

**Comment by davidalger** [comment]
@tmudarikwa Is this still an issue for you or was it resolved by cleaning things up?

**Comment by tmudarikwa** [comment]
@davidalger  no it is not an issue anymore. The database clean up cleared up things.
