### ISSUE TITLE
Cannot instantiate interface Magento\Downloadable\Api\DomainManagerInterface

### ISSUE THREAD

**Issue by mamsincl** [magento/magento2#25074]
The following issue occured during bin/magento setup:upgrade:
PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\Downloadable\Api\DomainManagerInterface in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116

### Preconditions (*)

Magento 2 Commerce 2.3.3 after upgrade from 2.3.2

Upgrade process happened as:
1. `composer require magento/product-enterprise-edition=2.3.3 --no-update`
2. `composer require --dev allure-framework/allure-phpunit:~1.2.0 friendsofphp/php-cs-fixer:~2.14.0 lusitanian/oauth:~0.8.10 magento/magento-coding-standard:~3.0.0 magento/magento2-functional-testing-framework:2.4.3 pdepend/pdepend:2.5.2 phpmd/phpmd:@stable phpunit/phpunit:~6.5.0 sebastian/phpcpd:~3.0.0 squizlabs/php_codesniffer:~3.4.0 --sort-packages --no-update`
3. `composer update`
4. branch created

### Steps to reproduce (*)

Deploy process happening in CI/CD environment as following
1. deploy branch (git)
2. `composer install --ignore-platform-reqs --prefer-dist --no-suggest` (docker container, that is why ignoring platform requirements)
3. `php -d memory_limit=-1 bin/magento setup:di:compile`
4. `php -d memory_limit=-1 bin/magento setup:static-content:deploy --theme ~XXXX~/~YYYY~ en_GB --force --jobs $(nproc --all)` 
5. `php -d memory_limit=-1 bin/magento setup:static-content:deploy --theme Magento/backend en_US en_GB --force --jobs $(nproc --all)`
6. `php bin/magento setup:upgrade --keep-generated` 
7. `php bin/magento cache:clean config`

happening during step 6

It's been not tried in vanilla since my tight timeframe

### Expected result (*)

1. setup:upgrade is finishing without error

### Actual result (*)

```Module 'Magento_SalesRule':
Module 'Magento_CatalogRule':
Module 'Magento_Downloadable':
PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\Downloadable\Api\DomainManagerInterface in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116
Stack trace:
#0 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\FaCannot instantiate interface Magento\Downloadable\Api\DomainManagerInterface
ctory\AbstractFactory->createObject('Magento\\Downloa...', Array)
#1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Downloa...')
#2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Downloa...')
#3 /var/www/html/vendo
The advice is that all servers running PHP version 7.1.x, 7.2.x, 7.3.x or lower upgrade to the following minor point releases:

7.1.32r/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Downloa...', Array)
#4 /var/www/html/vendor/magento/framework/Setup/Patch/PatchApplier.php(149): Magento\Framework\ObjectManager\ObjectManager->create('\\Magento\\Downlo...', Arra in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 116
{"messages":{"error":[{"code":500,"message":"Fatal Error: 'Uncaught Error: Cannot instantiate interface Magento\\Downloadable\\Api\\DomainManagerInterface in \/var\/www\/html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:116\nStack trace:\n#0 \/var\/www\/html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(108): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Downloa...', Array)\n#1 \/var\/www\/html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Downloa...')\n#2 \/var\/www\/html\/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\\\Downloa...')\n#3 \/var\/www\/html\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(56): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Downloa...', Array)\n#4 \/var\/www\/html\/vendor\/magento\/framework\/Setup\/Patch\/PatchApplier.php(149): Magento\\Framework\\ObjectManager\\ObjectManager->create('\\\\Magento\\\\Downlo...', Arra' in '\/var\/www\/html\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php' on line 116","trace":"Trace is not available."}]}}
```

**Comment by mamsincl** [comment]
running `php -d memory_limit=-1 bin/magento setup:di:compile` twice (w/o doing anything between) will picking up the preference for Magento\Downloadable\Api\DomainManagerInterface into **_generate/metadata/global.php_** at second time

**Comment by mrtuvn** [comment]
Just recognised Magento\Downloadable\Api\DomainManagerInterface not available in 2.3-develop branch
Hey you guys @magento-admin can update missing to 2.3-develop

**Comment by engcom-Delta** [comment]
Hi @mamsincl Unfortunately, I am not able to reproduce issue by steps you described on clean 2.3-develop(git version) and  2.3.3 (composer version)

**Testing scenario:**

- Install magento
- Run `php bin/magento setup:di:compile`
- Run `php bin/magento setup:static-content:deploy -f`
- Run `php bin/magento setup:upgrade --keep-generated`

**Result:**
:heavy_check_mark: Upgrade complete successfully 

Could you provide more details how to reproduce it locally?

**Comment by engcom-Charlie** [comment]
We are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
