### ISSUE TITLE
Error While installing Magento 2.0

### ISSUE THREAD

**Issue by duongquyet** [magento/magento2#2543]
Hi,
I'm trying install magento 2 on our server but it doesn't work. 
![screen](https://cloud.githubusercontent.com/assets/5326675/11450112/3f49941a-95c4-11e5-848c-98de3647e7da.png)

```
Starting Magento installation:
File permissions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Cleaning up database...
Cleaning up database `plazathe_magento2`

Installing database schema:
Schema creation/updates:
Module 'Magento_Store':
Installing schema..

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':
Installing schema..

Module 'Magento_Theme':
Installing schema..

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':
Installing schema..

Module 'Magento_Customer':
Installing schema.. Upgrading schema..

Module 'Magento_BundleImportExport':

Module 'Magento_AdminNotification':
Installing schema..

Module 'Magento_CacheInvalidate':

Module 'Magento_Indexer':
Installing schema..

Module 'Magento_Cms':
Installing schema..

Module 'Magento_CatalogImportExport':

Module 'Magento_Catalog':
Installing schema.. Upgrading schema..

Module 'Magento_Rule':

Module 'Magento_Msrp':

Module 'Magento_Search':
Installing schema.. Upgrading schema..

Module 'Magento_Bundle':
Installing schema.. Upgrading schema..

Module 'Magento_Quote':
Installing schema.. Upgrading schema..

Module 'Magento_CatalogUrlRewrite':
Installing schema..

Module 'Magento_Widget':
Installing schema..

Module 'Magento_SalesSequence':
Installing schema..

Module 'Magento_CheckoutAgreements':
Installing schema.. Upgrading schema..

Module 'Magento_Payment':

Module 'Magento_Downloadable':
Installing schema..

Module 'Magento_CmsUrlRewrite':

Module 'Magento_Config':
Installing schema..

Module 'Magento_ConfigurableImportExport':

Module 'Magento_CatalogInventory':
Installing schema..

Module 'Magento_SampleData':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':
Installing schema..

Module 'Magento_CurrencySymbol':

Module 'Magento_CatalogSearch':
Installing schema..

Module 'Magento_CustomerImportExport':

Module 'Magento_CustomerSampleData':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':
Installing schema..

Module 'Magento_User':
Installing schema.. Upgrading schema..

Module 'Magento_ImportExport':
Installing schema.. Upgrading schema..

Module 'Magento_Sales':
Installing schema..

Module 'Magento_CatalogRule':
Installing schema..

Module 'Magento_Email':
Installing schema..

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':
Installing schema..

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_GoogleOptimizer':
Installing schema..

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_Tax':
Installing schema..

Module 'Magento_DownloadableImportExport':

Module 'Magento_Braintree':

Module 'Magento_Integration':
Installing schema..

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_ConfigurableProduct':
Installing schema..

Module 'Magento_MsrpSampleData':

Module 'Magento_Multishipping':

Module 'Magento_NewRelicReporting':
Installing schema..

Module 'Magento_Newsletter':
Installing schema..

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':
Installing schema..

Module 'Magento_OfflineShipping':
Installing schema..

Module 'Magento_PageCache':

Module 'Magento_Captcha':
Installing schema..

Module 'Magento_Paypal':
Installing schema..

Module 'Magento_Persistent':
Installing schema..

Module 'Magento_ProductAlert':
Installing schema..

Module 'Magento_Weee':
Installing schema..

Module 'Magento_ProductVideo':
Installing schema..

Module 'Magento_CatalogSampleData':

Module 'Magento_Reports':
Installing schema..

Module 'Magento_RequireJs':

Module 'Magento_Review':
Installing schema..

Module 'Magento_BundleSampleData':

Module 'Magento_Rss':

Module 'Magento_DownloadableSampleData':

Module 'Magento_Authorizenet':

Module 'Magento_OfflineShippingSampleData':

Module 'Magento_ConfigurableSampleData':

Module 'Magento_SalesSampleData':

Module 'Magento_ProductLinksSampleData':

Module 'Magento_ThemeSampleData':

Module 'Magento_ReviewSampleData':

Module 'Magento_SendFriend':
Installing schema..

Module 'Magento_Ui':
Installing schema..

Module 'Magento_Sitemap':
Installing schema..

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Swagger':

Module 'Magento_Swatches':
Installing schema..

Module 'Magento_SwatchesSampleData':

Module 'Magento_GroupedProductSampleData':

Module 'Magento_TaxImportExport':

Module 'Magento_TaxSampleData':

Module 'Magento_GoogleAdwords':

Module 'Magento_CmsSampleData':

Module 'Magento_Translation':
Installing schema..

Module 'Magento_Shipping':

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':
Installing schema..

Module 'Magento_CatalogRuleSampleData':

Module 'Magento_Usps':

Module 'Magento_Variable':
Installing schema..

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_SalesRuleSampleData':

Module 'Magento_CatalogWidget':

Module 'Magento_WidgetSampleData':

Module 'Magento_Wishlist':
Installing schema..

Module 'Magento_WishlistSampleData':

Schema post-updates:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':

Module 'Magento_Theme':

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':

Module 'Magento_Customer':

Module 'Magento_BundleImportExport':

Module 'Magento_AdminNotification':

Module 'Magento_CacheInvalidate':

Module 'Magento_Indexer':
Running recurring..

Module 'Magento_Cms':

Module 'Magento_CatalogImportExport':

Module 'Magento_Catalog':

Module 'Magento_Rule':

Module 'Magento_Msrp':

Module 'Magento_Search':

Module 'Magento_Bundle':

Module 'Magento_Quote':

Module 'Magento_CatalogUrlRewrite':

Module 'Magento_Widget':

Module 'Magento_SalesSequence':

Module 'Magento_CheckoutAgreements':

Module 'Magento_Payment':

Module 'Magento_Downloadable':

Module 'Magento_CmsUrlRewrite':

Module 'Magento_Config':

Module 'Magento_ConfigurableImportExport':

Module 'Magento_CatalogInventory':

Module 'Magento_SampleData':

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_CatalogSearch':

Module 'Magento_CustomerImportExport':

Module 'Magento_CustomerSampleData':

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':

Module 'Magento_Authorization':

Module 'Magento_User':

Module 'Magento_ImportExport':

Module 'Magento_Sales':

Module 'Magento_CatalogRule':

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':

Module 'Magento_GiftMessage':

Module 'Magento_Checkout':

Module 'Magento_GoogleAnalytics':

Module 'Magento_GoogleOptimizer':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':

Module 'Magento_Tax':

Module 'Magento_DownloadableImportExport':

Module 'Magento_Braintree':

Module 'Magento_Integration':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_ConfigurableProduct':

Module 'Magento_MsrpSampleData':

Module 'Magento_Multishipping':

Module 'Magento_NewRelicReporting':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':

Module 'Magento_OfflineShipping':

Module 'Magento_PageCache':

Module 'Magento_Captcha':

Module 'Magento_Paypal':

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':

Module 'Magento_Weee':

Module 'Magento_ProductVideo':

Module 'Magento_CatalogSampleData':

Module 'Magento_Reports':

Module 'Magento_RequireJs':

Module 'Magento_Review':

Module 'Magento_BundleSampleData':

Module 'Magento_Rss':

Module 'Magento_DownloadableSampleData':

Module 'Magento_Authorizenet':

Module 'Magento_OfflineShippingSampleData':

Module 'Magento_ConfigurableSampleData':

Module 'Magento_SalesSampleData':

Module 'Magento_ProductLinksSampleData':

Module 'Magento_ThemeSampleData':

Module 'Magento_ReviewSampleData':

Module 'Magento_SendFriend':

Module 'Magento_Ui':

Module 'Magento_Sitemap':

Module 'Magento_CatalogRuleConfigurable':

Module 'Magento_Swagger':

Module 'Magento_Swatches':

Module 'Magento_SwatchesSampleData':

Module 'Magento_GroupedProductSampleData':

Module 'Magento_TaxImportExport':

Module 'Magento_TaxSampleData':

Module 'Magento_GoogleAdwords':

Module 'Magento_CmsSampleData':

Module 'Magento_Translation':

Module 'Magento_Shipping':

Module 'Magento_Ups':

Module 'Magento_UrlRewrite':

Module 'Magento_CatalogRuleSampleData':

Module 'Magento_Usps':

Module 'Magento_Variable':

Module 'Magento_Version':

Module 'Magento_Webapi':

Module 'Magento_SalesRuleSampleData':

Module 'Magento_CatalogWidget':

Module 'Magento_WidgetSampleData':

Module 'Magento_Wishlist':

Module 'Magento_WishlistSampleData':


Installing user configuration...

Enabling caches:
Current status:
Array
(
[config] => 1
[layout] => 1
[block_html] => 1
[collections] => 1
[reflection] => 1
[db_ddl] => 1
[eav] => 1
[config_integration] => 1
[config_integration_api] => 1
[full_page] => 1
[translate] => 1
[config_webservice] => 1
)


Installing data...
Data install/update:
Module 'Magento_Store':

Module 'Magento_AdvancedPricingImportExport':

Module 'Magento_Directory':
Installing data..

Module 'Magento_Theme':
Installing data..

Module 'Magento_Backend':

Module 'Magento_Backup':

Module 'Magento_Eav':
Installing data..

Module 'Magento_Customer':
Installing data.. Upgrading data..

Module 'Magento_BundleImportExport':

Module 'Magento_AdminNotification':

Module 'Magento_CacheInvalidate':

Module 'Magento_Indexer':
Installing data..

Module 'Magento_Cms':
Installing data..

Module 'Magento_CatalogImportExport':

Module 'Magento_Catalog':
Installing data.. Upgrading data..

Module 'Magento_Rule':

Module 'Magento_Msrp':
Installing data..

Module 'Magento_Search':

Module 'Magento_Bundle':
Installing data..

Module 'Magento_Quote':
Installing data..

Module 'Magento_CatalogUrlRewrite':
Installing data..

Module 'Magento_Widget':
Installing data..

Module 'Magento_SalesSequence':
Installing data..

Module 'Magento_CheckoutAgreements':

Module 'Magento_Payment':

Module 'Magento_Downloadable':
Installing data..

Module 'Magento_CmsUrlRewrite':

Module 'Magento_Config':
Installing data..

Module 'Magento_ConfigurableImportExport':

Module 'Magento_CatalogInventory':
Installing data..

Module 'Magento_SampleData':
Installing data..

Module 'Magento_Contact':

Module 'Magento_Cookie':

Module 'Magento_Cron':

Module 'Magento_CurrencySymbol':

Module 'Magento_CatalogSearch':
Installing data..

Module 'Magento_CustomerImportExport':

Module 'Magento_CustomerSampleData':
Installing data..

Module 'Magento_Deploy':

Module 'Magento_Developer':

Module 'Magento_Dhl':
Installing data..

Module 'Magento_Authorization':
Installing data..

Module 'Magento_User':
Upgrading data..

Module 'Magento_ImportExport':

Module 'Magento_Sales':
Installing data.. Upgrading data..

Module 'Magento_CatalogRule':
Installing data..

Module 'Magento_Email':

Module 'Magento_EncryptionKey':

Module 'Magento_Fedex':
Installing data..

Module 'Magento_GiftMessage':
Installing data..

Module 'Magento_Checkout':
Installing data..

Module 'Magento_GoogleAnalytics':

Module 'Magento_GoogleOptimizer':

Module 'Magento_GroupedImportExport':

Module 'Magento_GroupedProduct':
Installing data..

Module 'Magento_Tax':
Installing data.. Upgrading data..

Module 'Magento_DownloadableImportExport':

Module 'Magento_Braintree':

Module 'Magento_Integration':

Module 'Magento_LayeredNavigation':

Module 'Magento_Marketplace':

Module 'Magento_MediaStorage':

Module 'Magento_ConfigurableProduct':
Installing data..

Module 'Magento_MsrpSampleData':
Installing data..

Module 'Magento_Multishipping':

Module 'Magento_NewRelicReporting':

Module 'Magento_Newsletter':

Module 'Magento_OfflinePayments':

Module 'Magento_SalesRule':
Installing data..

Module 'Magento_OfflineShipping':

Module 'Magento_PageCache':

Module 'Magento_Captcha':

Module 'Magento_Paypal':
Installing data..

Module 'Magento_Persistent':

Module 'Magento_ProductAlert':

Module 'Magento_Weee':
Installing data..

Module 'Magento_ProductVideo':
Upgrading data..

Module 'Magento_CatalogSampleData':
Installing data..

Module 'Magento_Reports':
Installing data..

Module 'Magento_RequireJs':

Module 'Magento_Review':
Installing data..

Module 'Magento_BundleSampleData':
Installing data..

Module 'Magento_Rss':

Module 'Magento_DownloadableSampleData':
Installing data..

Module 'Magento_Authorizenet':

Module 'Magento_OfflineShippingSampleData':
Installing data..

Module 'Magento_ConfigurableSampleData':
Installing data.. 
```

Please help me to resolve this issue. Thanks.

**Comment by bchatard** [comment]
@duongquyet can you provide information about your server (PHP version, MySQL etc)?

**Comment by duongquyet** [comment]
Some information of our server:
PHP Version 5.6.15
mysqlnd 5.0.11
memory_limit 128M 
post_max_size 8M 
max_file_uploads 20 
max_execution_time 30

**Comment by bchatard** [comment]
@duongquyet can you try to install Magento without Sample Data. When it's ok, install Sample Data from CLI (more verbose than setup wizard) ?

BTW, Magento 2 memory limit must be 768M (set in htaccess), the issue caome from here maybe.

**Comment by mazhalai** [comment]
@duongquyet can you please check your server and php logs to check if there is any error? Also, the `max_execution_time` is too low. it is recommended to be set to [18000](https://github.com/magento/magento2/blob/develop/.htaccess#L41)

**Comment by mcekutis** [comment]
Have simmilar problem, just getting error info:

```
Module 'Magento_ConfigurableSampleData':
Installing data.. 
[ERROR] Exception: Warning: Error while sending QUERY packet. PID=8102 in /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228 in /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'Error while sen...', '/home/speedbad/...', 228, Array)
#1 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#2 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#3 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#4 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#5 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE `setup_m...', Array)
#6 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(444): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE `setup_m...', Array)
#7 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(499): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('UPDATE `setup_m...', Array)
#8 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(635): Magento\Framework\DB\Adapter\Pdo\Mysql->query('UPDATE `setup_m...', Array)
#9 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/magento/framework/Module/ModuleResource.php(129): Zend_Db_Adapter_Abstract->update('setup_module', Array, '(module = 'Mage...')
#10 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/setup/src/Magento/Setup/Model/Installer.php(808): Magento\Framework\Module\ModuleResource->setDataVersion('Magento_Configu...', '2.0.0')
#11 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/setup/src/Magento/Setup/Model/Installer.php(746): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data')
#12 [internal function]: Magento\Setup\Model\Installer->installDataFixtures()
#13 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/setup/src/Magento/Setup/Model/Installer.php(331): call_user_func_array(Array, Array)
#14 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/setup/src/Magento/Setup/Controller/Install.php(97): Magento\Setup\Model\Installer->install(Array)
#15 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#16 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#17 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#18 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#21 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#22 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#23 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#24 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#25 /home/speedbad/domains/ridikiuliai.lt/public_html/learn/setup/index.php(31): Zend\Mvc\Application->run()
#26 {main}
```

**Comment by mazhalai** [comment]
@mcekutis what is the value of `max_allowed_packet` in mysql?

**Comment by duongquyet** [comment]
Hi,
Thanks you guys. I changed memory_limit 128M to 512M, max_execution_time 30 to 1800. Now, I can install it. But I get other problem. Our site have a lot bug. You can see my screen for more detail.
![screen](https://cloud.githubusercontent.com/assets/5326675/11525969/04956bf8-988c-11e5-9b7a-1d978fc5ba75.png)
![screen2](https://cloud.githubusercontent.com/assets/5326675/11525970/04a9ab22-988c-11e5-8fc4-2bf3805293a7.png)

**Comment by mazhalai** [comment]
@duongquyet please open a new issue. This is not related to this thread.

**Comment by davidalger** [comment]
@duongquyet for that last issue, you may reference #2412 as there is a good chance that is the issue you're experiencing.

**Comment by jissereitsma** [comment]
FYI, in my case, increasing the MySQL `max_allowed_packet` solved this issue
