### ISSUE TITLE
main.CRITICAL: Exception message: Each getter must have description with @return annotation. See Magento\Tax\Api\Data\TaxDetailsInterface::getSubtotal()

### ISSUE THREAD

**Issue by thomvanderboon** [magento/magento2#2555]
Symptoms:
Unable to add products to cart: Error: We can't add this item to your shopping cart right now.
Unable to register as new customer on store front: Error: We can't save the customer.
Unable to register new customer at backend: Error (No error displayed, but customer not created)

System:
New magento 2 install, no sample data installed

Output of exeption.log:

```
[2015-11-29 12:46:19] main.CRITICAL: Exception message: Each getter must have description with @return annotation. See Magento\Tax\Api\Data\TaxDetailsInterface::getSubtotal()
Trace: #0 /home/vdbeu/public_html/vendor/magento/framework/Reflection/MethodsMap.php(163): Magento\Framework\Reflection\TypeProcessor->getGetterReturnType(Object(Zend\Code\Reflection\MethodReflection))
#1 /home/vdbeu/public_html/vendor/magento/framework/Reflection/MethodsMap.php(100): Magento\Framework\Reflection\MethodsMap->getMethodMapViaReflection('\\Magento\\Tax\\Ap...')
#2 /home/vdbeu/public_html/vendor/magento/framework/Reflection/MethodsMap.php(75): Magento\Framework\Reflection\MethodsMap->getMethodsMap('\\Magento\\Tax\\Ap...')
#3 /home/vdbeu/public_html/vendor/magento/framework/Api/DataObjectHelper.php(157): Magento\Framework\Reflection\MethodsMap->getMethodReturnType('\\Magento\\Tax\\Ap...', 'getAppliedTaxes')
#4 /home/vdbeu/public_html/vendor/magento/framework/Api/DataObjectHelper.php(129): Magento\Framework\Api\DataObjectHelper->setComplexValue(Object(Magento\Tax\Model\TaxDetails\TaxDetails), 'getAppliedTaxes', 'setAppliedTaxes', Array, '\\Magento\\Tax\\Ap...')
#5 /home/vdbeu/public_html/vendor/magento/framework/Api/DataObjectHelper.php(85): Magento\Framework\Api\DataObjectHelper->_setDataValues(Object(Magento\Tax\Model\TaxDetails\TaxDetails), Array, '\\Magento\\Tax\\Ap...')
#6 /home/vdbeu/public_html/vendor/magento/module-tax/Model/TaxCalculation.php(197): Magento\Framework\Api\DataObjectHelper->populateWithArray(Object(Magento\Tax\Model\TaxDetails\TaxDetails), Array, '\\Magento\\Tax\\Ap...')
#7 /home/vdbeu/public_html/vendor/magento/module-tax/Model/Sales/Total/Quote/Subtotal.php(43): Magento\Tax\Model\TaxCalculation->calculateTax(Object(Magento\Tax\Model\Sales\Quote\QuoteDetails), '1')
#8 /home/vdbeu/public_html/vendor/magento/module-quote/Model/Quote/TotalsCollector.php(265): Magento\Tax\Model\Sales\Total\Quote\Subtotal->collect(Object(Magento\Quote\Model\Quote), Object(Magento\Quote\Model\ShippingAssignment), Object(Magento\Quote\Model\Quote\Address\Total))
#9 /home/vdbeu/public_html/vendor/magento/module-quote/Model/Quote/TotalsCollector.php(144): Magento\Quote\Model\Quote\TotalsCollector->collectAddressTotals(Object(Magento\Quote\Model\Quote), Object(Magento\Quote\Model\Quote\Address))
#10 /home/vdbeu/public_html/vendor/magento/module-quote/Model/Quote.php(1922): Magento\Quote\Model\Quote\TotalsCollector->collect(Object(Magento\Quote\Model\Quote))
#11 /home/vdbeu/public_html/vendor/magento/module-checkout/Model/Cart.php(562): Magento\Quote\Model\Quote->collectTotals()
#12 [internal function]: Magento\Checkout\Model\Cart->save()
#13 /home/vdbeu/public_html/vendor/magento/framework/Interception/Interceptor.php(144): call_user_func_array(Array, Array)
#14 /home/vdbeu/public_html/var/generation/Magento/Checkout/Model/Cart/Interceptor.php(182): Magento\Checkout\Model\Cart\Interceptor->___callPlugins('save', Array, Array)
#15 /home/vdbeu/public_html/vendor/magento/module-checkout/Controller/Cart/Add.php(108): Magento\Checkout\Model\Cart\Interceptor->save()
#16 [internal function]: Magento\Checkout\Controller\Cart\Add->execute()
#17 /home/vdbeu/public_html/vendor/magento/framework/Interception/Interceptor.php(144): call_user_func_array(Array, Array)
#18 /home/vdbeu/public_html/var/generation/Magento/Checkout/Controller/Cart/Add/Interceptor.php(26): Magento\Checkout\Controller\Cart\Add\Interceptor->___callPlugins('execute', Array, Array)
#19 /home/vdbeu/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Checkout\Controller\Cart\Add\Interceptor->execute()
#20 [internal function]: Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /home/vdbeu/public_html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#22 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Checkout\Controller\Cart\Add\Interceptor->___callParent('dispatch', Array)
#23 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Array, 'designLoader')
#24 /home/vdbeu/public_html/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#25 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#27 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Array, 'storeCheck')
#28 /home/vdbeu/public_html/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#29 [internal function]: Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#31 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Array, 'contextPlugin')
#32 /home/vdbeu/public_html/vendor/magento/module-store/App/Action/Plugin/Context.php(98): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#33 [internal function]: Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#35 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Array, 'customer-app-ac...')
#36 /home/vdbeu/public_html/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#37 [internal function]: Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#38 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#39 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Array, 'tax-app-action-...')
#40 /home/vdbeu/public_html/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#41 [internal function]: Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#42 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#43 /home/vdbeu/public_html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Checkou...', 'dispatch', Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Array, 'weee-app-action...')
#44 /home/vdbeu/public_html/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Checkout\Controller\Cart\Add\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#45 [internal function]: Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Checkout\Controller\Cart\Add\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#46 /home/vdbeu/public_html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#47 /home/vdbeu/public_html/var/generation/Magento/Checkout/Controller/Cart/Add/Interceptor.php(39): Magento\Checkout\Controller\Cart\Add\Interceptor->___callPlugins('dispatch', Array, Array)
#48 /home/vdbeu/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Checkout\Controller\Cart\Add\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#49 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#50 /home/vdbeu/public_html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#51 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#52 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#53 /home/vdbeu/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(89): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#54 [internal function]: Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#55 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#56 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#57 /home/vdbeu/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#58 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#59 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#60 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'storeCookieVali...')
#61 /home/vdbeu/public_html/vendor/magento/module-store/Model/Plugin/StoreCookie.php(78): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#62 [internal function]: Magento\Store\Model\Plugin\StoreCookie->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#63 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#64 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#65 /home/vdbeu/public_html/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#66 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#67 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#68 /home/vdbeu/public_html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#69 /home/vdbeu/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#70 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#71 /home/vdbeu/public_html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#72 /home/vdbeu/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#73 /home/vdbeu/public_html/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#74 /home/vdbeu/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#75 /home/vdbeu/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#76 {main} [] []
```

**Comment by dmitrii-fediuk** [comment]
https://github.com/magento/magento2/issues/2468

**Comment by thomvanderboon** [comment]
Output for log when unable to save new customer:

```
[2015-11-30 05:24:09] main.CRITICAL: Exception message: Each getter must have description with @return annotation. See Magento\Customer\Api\Data\CustomerInterface::getId()
Trace: #0 /home/vdbeu/public_html/vendor/magento/framework/Reflection/MethodsMap.php(163): Magento\Framework\Reflection\TypeProcessor->getGetterReturnType(Object(Zend\Code\Reflection\MethodReflection))
#1 /home/vdbeu/public_html/vendor/magento/framework/Reflection/MethodsMap.php(100): Magento\Framework\Reflection\MethodsMap->getMethodMapViaReflection('\\Magento\\Custom...')
#2 /home/vdbeu/public_html/vendor/magento/framework/Reflection/DataObjectProcessor.php(77): Magento\Framework\Reflection\MethodsMap->getMethodsMap('\\Magento\\Custom...')
#3 /home/vdbeu/public_html/vendor/magento/framework/Api/ExtensibleDataObjectConverter.php(46): Magento\Framework\Reflection\DataObjectProcessor->buildOutputDataArray(Object(Magento\Customer\Model\Data\Customer), '\\Magento\\Custom...')
#4 /home/vdbeu/public_html/vendor/magento/module-customer/Model/ResourceModel/CustomerRepository.php(160): Magento\Framework\Api\ExtensibleDataObjectConverter->toNestedArray(Object(Magento\Customer\Model\Data\Customer), Array, '\\Magento\\Custom...')
#5 [internal function]: Magento\Customer\Model\ResourceModel\CustomerRepository->save(Object(Magento\Customer\Model\Data\Customer), '64e4d941eff531a...')
#6 /home/vdbeu/public_html/vendor/magento/framework/Interception/Interceptor.php(144): call_user_func_array(Array, Array)
#7 /home/vdbeu/public_html/var/generation/Magento/Customer/Model/ResourceModel/CustomerRepository/Interceptor.php(27): Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->___callPlugins('save', Array, Array)
#8 /home/vdbeu/public_html/vendor/magento/module-customer/Model/AccountManagement.php(527): Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->save(Object(Magento\Customer\Model\Data\Customer), '64e4d941eff531a...')
#9 /home/vdbeu/public_html/vendor/magento/module-customer/Model/AccountManagement.php(484): Magento\Customer\Model\AccountManagement->createAccountWithPasswordHash(Object(Magento\Customer\Model\Data\Customer), '64e4d941eff531a...', 'http://vdb.eu/w...')
#10 /home/vdbeu/public_html/vendor/magento/module-customer/Controller/Account/CreatePost.php(233): Magento\Customer\Model\AccountManagement->createAccount(Object(Magento\Customer\Model\Data\Customer), 'Mjah1970', 'http://vdb.eu/w...')
#11 /home/vdbeu/public_html/var/generation/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(24): Magento\Customer\Controller\Account\CreatePost->execute()
#12 /home/vdbeu/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Customer\Controller\Account\CreatePost\Interceptor->execute()
#13 [internal function]: Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /home/vdbeu/public_html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#15 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent('dispatch', Array)
#16 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'designLoader')
#17 /home/vdbeu/public_html/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#18 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#20 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'customer-app-ac...')
#21 /home/vdbeu/public_html/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#22 [internal function]: Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#24 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'storeCheck')
#25 /home/vdbeu/public_html/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#26 [internal function]: Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#28 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'contextPlugin')
#29 /home/vdbeu/public_html/vendor/magento/module-store/App/Action/Plugin/Context.php(98): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#30 [internal function]: Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#32 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'customer_accoun...')
#33 /home/vdbeu/public_html/vendor/magento/module-customer/Controller/Plugin/Account.php(60): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#34 [internal function]: Magento\Customer\Controller\Plugin\Account->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#36 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'tax-app-action-...')
#37 /home/vdbeu/public_html/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#38 [internal function]: Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#39 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#40 /home/vdbeu/public_html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'dispatch', Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Array, 'weee-app-action...')
#41 /home/vdbeu/public_html/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#42 [internal function]: Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#43 /home/vdbeu/public_html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#44 /home/vdbeu/public_html/var/generation/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(39): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins('dispatch', Array, Array)
#45 /home/vdbeu/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Customer\Controller\Account\CreatePost\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#46 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#47 /home/vdbeu/public_html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#48 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#49 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#50 /home/vdbeu/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(89): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#51 [internal function]: Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#52 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#53 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#54 /home/vdbeu/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#55 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#56 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#57 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'storeCookieVali...')
#58 /home/vdbeu/public_html/vendor/magento/module-store/Model/Plugin/StoreCookie.php(78): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#59 [internal function]: Magento\Store\Model\Plugin\StoreCookie->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#60 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#61 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#62 /home/vdbeu/public_html/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#63 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#64 /home/vdbeu/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#65 /home/vdbeu/public_html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#66 /home/vdbeu/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#67 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#68 /home/vdbeu/public_html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#69 /home/vdbeu/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#70 /home/vdbeu/public_html/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#71 /home/vdbeu/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#72 /home/vdbeu/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#73 {main} [] []
```

**Comment by thomvanderboon** [comment]
OK. Problem solved. My hosting provider moved my site to another server with the newer PHP version. Problem is solved after the move.

**Comment by davidalger** [comment]
@thomvanderboon Do you know version of PHP you were on compared to now?

**Comment by thomvanderboon** [comment]
PHP: 5.5.30 -> 5.6.15
Zend Engine: 2,5 -> 2.6

**Comment by davidalger** [comment]
@thomvanderboon Thanks for the added information. I'm guessing not, but do you have any way to know what the php.ini settings were on the old installation? Specifically I'm wondering if this may have had something to do with the opcode cache being configured to discard code comments: http://php.net/manual/en/opcache.configuration.php#ini.opcache.save-comments

**Comment by thomvanderboon** [comment]
_grin_ saved the phpinfo() page of both servers for this kind of questions:

Old server: '--enable-opcache'
New server: '--disable-opcache'

**Comment by NadiyaS** [comment]
@thomvanderboon. Thanks for reporting the cause of the problem. This issue is closed.

**Comment by acharrex** [comment]
If you use Zend Opcache, the following parameters must be configured to 1:
opcache.save_comments
opcache.load_comments

**Comment by ihor-sviziev** [comment]
I had similar issue during customer creation.

I found in documentation that opcache.save_comments should be set to 1:
http://devdocs.magento.com/guides/v2.1/install-gde/prereq/php-settings.html#php-required-opcache
