### ISSUE TITLE
Product Attributes - Error on 'Add New Attribute'

### ISSUE THREAD

**Issue by x-mago** [magento/magento2#2557]
When I hit the 'Add New Attribute' Button, I get the Error:

```
a:4:{i:0;s:37:"Object DOMDocument should be created.";i:1;s:10098:"#0 /var/www/read-greek/vendor/magento/framework/View/Element/UiComponent/Config/Reader.php(95
): Magento\Framework\View\Element\UiComponent\Config\DomMerger->getDom()
#1 /var/www/read-greek/vendor/magento/module-ui/Model/Manager.php(261): Magento\Framework\View\Element\UiComponent\Config\Reader->read()
#2 /var/www/read-greek/vendor/magento/module-ui/Model/Manager.php(169): Magento\Ui\Model\Manager->prepare('main_schedule_b...')
#3 /var/www/read-greek/vendor/magento/framework/View/Element/UiComponentFactory.php(139): Magento\Ui\Model\Manager->prepareData('main_schedule_b...')
#4 /var/www/read-greek/vendor/magento/framework/View/Layout/Generator/UiComponent.php(125): Magento\Framework\View\Element\UiComponentFactory->create('main_sche
dule_b...', NULL, Array)
#5 /var/www/read-greek/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponen
t(Object(Magento\Framework\View\Layout\Data\Structure), 'main_schedule_b...', Array, Object(Magento\Framework\View\Layout\Interceptor))
#6 /var/www/read-greek/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\F
ramework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#7 /var/www/read-greek/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\
Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#8 /var/www/read-greek/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#9 /var/www/read-greek/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#10 /var/www/read-greek/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#11 /var/www/read-greek/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#12 /var/www/read-greek/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#13 /var/www/read-greek/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#14 /var/www/read-greek/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('breadcrumbs')
#15 /var/www/read-greek/vendor/magento/module-backend/Model/View/Result/Page.php(80): Magento\Framework\View\Layout\Interceptor->getBlock('breadcrumbs')
#16 /var/www/read-greek/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(37): Magento\Backend\Model\View\Result\Page->addBreadcrumb(Object(
Magento\Framework\Phrase), Object(Magento\Framework\Phrase), NULL)
#17 /var/www/read-greek/vendor/magento/module-catalog/Controller/Adminhtml/Product/Attribute.php(92): Magento\Backend\Model\View\Result\Page\Interceptor->addBre
adcrumb(Object(Magento\Framework\Phrase), Object(Magento\Framework\Phrase))
#18 /var/www/read-greek/vendor/magento/module-catalog/Controller/Adminhtml/Product/Attribute/Edit.php(55): Magento\Catalog\Controller\Adminhtml\Product\Attribut
e->createActionPage(Object(Magento\Framework\Phrase))
#19 /var/www/read-greek/var/generation/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Edit/Interceptor.php(25): Magento\Catalog\Controller\Adminhtml\Pro
duct\Attribute\Edit->execute()
#20 /var/www/read-greek/vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Product\Attribute\Edit\Interceptor->execute()
#21 /var/www/read-greek/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/read-greek/vendor/magento/module-catalog/Controller/Adminhtml/Product/Attribute.php(72): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#23 [internal function]: Magento\Catalog\Controller\Adminhtml\Product\Attribute->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /var/www/read-greek/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#25 /var/www/read-greek/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Adminhtml\Product\Attribute\Edit\Interceptor->___callParent('dispatch', Array)
#26 /var/www/read-greek/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Attribute\Edit\Interceptor), Array, 'adminAuthentica...')
#27 /var/www/read-greek/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Attribute\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /var/www/read-greek/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#30 /var/www/read-greek/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Attribute\Edit\Interceptor), Array, 'designLoader')
#31 /var/www/read-greek/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#32 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Attribute\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 /var/www/read-greek/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
[...]
```

**Comment by dwdonline** [comment]
I get this same error when trying to view/edit a product attribute.

**Comment by Styopchik** [comment]
Approve. Same error on adding/viewing/editting attributes

**Comment by puffpackage** [comment]
Also having the same problem, I feel it's connected to my other similar error when flushing magento cache

**Comment by vzabaznov** [comment]
@x-mago  thanks for reporting, our functionality has been changed and bug cannot be reproduced
Fell free to write comment, or open a new GitHub issue if you feel that issue has not been resolved
