### ISSUE TITLE
Integration Test Fixture Setup Issue

### ISSUE THREAD

**Issue by NicholasRoge** [magento/magento2#25621]
### Preconditions (*)

1. Magento Version: 2.3.3 EE
2. PHP Version:  7.2.24
3. Installed via `composer create-project --repository=https://repo.magento.com/ magento/project-community-edition:2.3.3`

### Steps to reproduce (*)

1. `composer create-project --repository=https://repo.magento.com/ magento/project-community-edition:2.3.3 magento2`
2. [Configure the framework for test environment](https://devdocs.magento.com/guides/v2.3/test/integration/integration_test_execution.html#configure-the-framework-for-test-environment)
3. `cd magento2/dev/tests/integration`
4. `../../../vendor/bin/phpunit --configuration phpunit.xml.dist --filter '^Magento\\(AdminGws\\Model\\ModelsTest|Indexer\\Console\\Command\\IndexerReindexCommandTest)'`

### Expected result (*)

1. Expected all tests to pass.

### Actual result (*)

1. Test fails due to variable in fixture being unset:

```
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Magento\AdminGws\Model\Models
 ✔ Customer save [287.17 ms]
Error in fixture: "\/magento\/dev\/tests\/integration\/testsuite\/Magento\/Store\/_files\/second_store_group_with_second_website.php".
 Notice: Undefined variable: objectManager in /magento/dev/tests/integration/testsuite/Magento/Store/_files/second_store_group_with_second_website.php:14.
 #0 /magento/dev/tests/integration/testsuite/Magento/Store/_files/second_store_group_with_second_website.php(14): {closure}(8, 'Undefined varia...', '/magento/dev/te...', 14, Array)
#1 /magento/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(214): require('/magento/dev/te...')
#2 /magento/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(244): Magento\TestFramework\Annotation\DataFixture->_applyOneFixture('/magento/dev/te...')
#3 /magento/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(60): Magento\TestFramework\Annotation\DataFixture->_applyFixtures(Array)
#4 [internal function]: Magento\TestFramework\Annotation\DataFixture->startTestTransactionRequest(Object(Magento\Indexer\Console\Command\IndexerReindexCommandTest), Object(Magento\TestFramework\Event\Param\Transaction))
#5 /magento/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
#6 /magento/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(76): Magento\TestFramework\EventManager->fireEvent('startTestTransa...', Array)
#7 /magento/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(46): Magento\TestFramework\Event\Transaction->_processTransactionRequests('startTest', Object(Magento\Indexer\Console\Command\IndexerReindexCommandTest))
#8 [internal function]: Magento\TestFramework\Event\Transaction->startTest(Object(Magento\Indexer\Console\Command\IndexerReindexCommandTest))
#9 /magento/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
#10 /magento/dev/tests/integration/framework/Magento/TestFramework/Event/PhpUnit.php(126): Magento\TestFramework\EventManager->fireEvent('startTest', Array)
#11 /magento/vendor/phpunit/phpunit/src/Framework/TestResult.php(395): Magento\TestFramework\Event\PhpUnit->startTest(Object(Magento\Indexer\Console\Command\IndexerReindexCommandTest))
#12 /magento/vendor/phpunit/phpunit/src/Framework/TestResult.php(637): PHPUnit\Framework\TestResult->startTest(Object(Magento\Indexer\Console\Command\IndexerReindexCommandTest))
#13 /magento/vendor/phpunit/phpunit/src/Framework/TestCase.php(894): PHPUnit\Framework\TestResult->run(Object(Magento\Indexer\Console\Command\IndexerReindexCommandTest))
#14 /magento/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#15 /magento/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#16 /magento/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#17 /magento/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(545): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#18 /magento/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#19 /magento/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#20 /magento/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#21 {main}

=== Memory Usage System Stats ===
Memory usage (OS):	725.95M (100.20% of 724.50M reported by PHP)
Estimated memory leak:	1.45M (0.20% of used memory)

----------------------------------------------------------------------
FAILED 1 of 1
 - /magento/dev/tests/integration> /magento/vendor/bin/phpunit --filter=^Magento\\(AdminGws\\Model\\Models|Indexer\\Console\\Command\\IndexerReindexCommand)
```

### Cause

Test failure is caused by fixtures using require_once or include_once to include another fixture.  In this particular case, the problematic fixture is [`dev/tests/integration/testsuite/Magento/Store/_files/second_store_group_with_second_website.php`](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/integration/testsuite/Magento/Store/_files/second_store_group_with_second_website.php#L9).  The `Magento/Store/_files/website.php` fixture is required for the first time via the @magentoDataFixture annotation attached to the `Magento\AdminGws\Model\ModelsTest::testCustomerSave`, and then for a second time by proxy in the `Magento\Indexer\Console\Command\IndexerReindexCommandTest::testReindexAll` test.  The second time it's required, however, it's required using require_once and so doesn't actually run, causing the `$objectManager` variable to be unset.

Other fixtures with the same issue:  [`Magento/Store/_files/second_store_group_with_second_website_rollback.php`](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/integration/testsuite/Magento/Store/_files/second_store_group_with_second_website_rollback.php), [`Magento/Catalog/_files/products_for_search_rollback.php`](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/integration/testsuite/Magento/Catalog/_files/products_for_search_rollback.php), [`Magento/Catalog/_files/category_backend.php`](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/integration/testsuite/Magento/Catalog/_files/category_backend.php), [`Magento/Store/_files/second_store_with_second_currency_rollback.php`](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/integration/testsuite/Magento/Store/_files/second_store_with_second_currency_rollback.php), [`Magento/Store/_files/second_store_with_second_currency.php`](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/integration/testsuite/Magento/Store/_files/second_store_with_second_currency.php), [`Magento/Tax/_files/tax_calculation_data_aggregated.php`](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/integration/testsuite/Magento/Tax/_files/tax_calculation_data_aggregated.php), [`Magento/Store/_files/second_store_group_with_second_website.php`](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/integration/testsuite/Magento/Store/_files/second_store_group_with_second_website.php)

**Comment by sdzhepa** [comment]
Hello @NicholasRoge 

Thank you for contribution and collaboration!

I moved this issue into  [Magento Commerce private repository](https://github.com/magento/partners-magento2ee/issues) where it could be fixed and delivered by Solution Partners Contribution Program.

[Current repository](https://github.com/magento/magento2) and [issue tracker](https://github.com/magento/magento2/issues) aimed at Magento Open Source version only and the main focus is community contribution/collaboration. It described in [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and it is a part of the issue report template:
> Verify, that the issue you are about to report does not relate to the Magento Commerce. GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub. You can report Commerce-related issues in one of two ways:
> - You can use the Support portal associated with your account
> - If you are a Partner reporting on behalf of a merchant, use the Partner portal.
