### ISSUE TITLE
Shipment create via API salesShipmentRepositoryV1 throw Fatal error

### ISSUE THREAD

**Issue by milindsingh** [magento/magento2#26741]
### Preconditions (*)

1. Magento 2.3.1 with MSI enabled
2. Single Default Source for Inventory
3. The order created from Admin Panel

### Steps to reproduce (*)

1.  Create an order created from Admin Panel
2. Create Shipment via API:

```json
{
  "entity": {
    "increment_id": "000000003",
    "order_id": 3,
    "items": [
        {
          "sku": "WSH12-32-Red",
          "qty": 1
        }
      ],
    "tracks": [
      {
        "order_id": 3,
        "qty": 1,
        "track_number": "123",
        "title": "Test",
        "carrier_code": "dhl"
      }
    ]  
  }
}
```

### Expected result (*)

1. Shipment is created in Admin

### Actual result (*)

1. Fatal Error on API Response
```json
can't parse JSON.  Raw result:

<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute() must be of the type string, null given, called in /opt/lampp7.2/htdocs/magento/2.3.sample/vendor/magento/module-inventory-sales/Model/GetSkuFromOrderItem.php on line 48 and defined in /opt/lampp7.2/htdocs/magento/2.3.sample/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php:20
Stack trace:
#0 /opt/lampp7.2/htdocs/magento/2.3.sample/vendor/magento/module-inventory-sales/Model/GetSkuFromOrderItem.php(48): Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor-&gt;execute(NULL)
magento/inventory#1 /opt/lampp7.2/htdocs/magento/2.3.sample/vendor/magento/module-inventory-shipping/Model/GetItemsToDeductFromShipment.php(75): Magento\InventorySales\Model\GetSkuFromOrderItem-&gt;execute(Object(Magento\Sales\Model\Order\Item\Interceptor))
magento/inventory#2 /opt/lampp7.2/htdocs/magento/2.3.sample/vendor/magento/module- in <b>/opt/lampp7.2/htdocs/magento/2.3.sample/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php</b> on line <b>20</b><br />
{"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/398581820999"}]}}
```

Note: **Works after disabling the MSI modules.**

**Comment by shikhamis11** [comment]
also I noticed one issue .. If we create shipment by disabling MSI with the payload ` {
  "entity": {
    "increment_id": "000000003",
    "order_id": 3,
    "items": [
        {
          "sku": "WSH12-32-Red",
          "qty": 1
        }
      ],
    "tracks": [
      {
        "order_id": 3,
        "qty": 1,
        "track_number": "123",
        "title": "Test",
        "carrier_code": "dhl"
      }
    ]  
  }
}`
I am able to generate multiple shipment for same product for single quantity .. and also the shipment increment id is same 
![issue_shipment](https://user-images.githubusercontent.com/25526037/74089824-3f5b8380-4acb-11ea-97a4-d43aa58cbe5e.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31301` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
