### ISSUE TITLE
phpstan stops working after upgrading from 2.2.5 to 2.3.3

### ISSUE THREAD

**Issue by nmklong** [magento/magento2#27016]
### Preconditions (*)

1. Magento version: 2.3.3 (upgraded from 2.2.5)

### Steps to reproduce (*)

1. After finishing upgrade, try to run php stan:
```
./vendor/bin/phpstan analyse --no-progress  --error-format=raw --memory-limit=3G -l 5 app/code/
```

### Expected result (*)

1. phpstan can run normally

### Actual result (*)

1. It will throw an error:
```
Fatal error: Uncaught Exception: Warning: include(): Unable to find the wrapper "phar" - did you forget to enable it when you configured PHP? in /Users/devprojects/my-magento/vendor/composer/ClassLoader.php on line 444 in /Users/devprojects/my-magento/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /Users/devprojects/my-magento/vendor/composer/ClassLoader.php(444): Magento\Framework\App\ErrorHandler->handler(2, 'include(): Unab...', '/Users/devprojects/...', 444, Array)
#1 /Users/devprojects/my-magento/vendor/composer/ClassLoader.php(444): include()
#2 /Users/devprojects/my-magento/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('phar:///Users/l...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Hoa\\Event\\Bucke...')
#4 phar:///Users/devprojects/my-magento/vendor/phpstan/phpstan/phpstan/vendor/hoa/stream/Stream.php(237): spl_autoload_call('Hoa\\Event\\Bucke...')
#5 pha in phar:///Users/devprojects/my-magento/vendor/phpstan/phpstan/phpstan/src/Reflection/Runtime/RuntimeReflectionProvider.php on line 164
```
2. When looking at app/bootstrap.php, there is this line that is unregistering phar:
```
error_reporting(E_ALL);
if (in_array('phar', \stream_get_wrappers())) {
    stream_wrapper_unregister('phar');
}
```

Is this a bug in Magento 2.3.3? I notice 2.3.4 is still having the unregistering code above, what would be a temporary solution?

Any help is appreciated, thanks.

**Comment by nmklong** [comment]
I have found the problem in my docker setup
