### ISSUE TITLE
Magento 2.3.3: Init vector must be a string of 32 bytes

### ISSUE THREAD

**Issue by nmklong** [magento/magento2#27017]
### Preconditions (*)

1. Magento version: 2.3.3

### Steps to reproduce (*)

1. Run phpstan after installing from composer:
```
./vendor/bin/phpstan analyse --no-progress  --error-format=raw --memory-limit=3G -l 5 app/code
```

### Expected result (*)

1. phpstan completes successfully

### Actual result (*)

1. Localized Exception was thrown, and i cannot trace down where to fix this:
```
Magento\Framework\Exception\LocalizedException: Init vector must be a string of 32 bytes. in /Users/dev-projects/my-magento/vendor/magento/framework/Encryption/Adapter/Mcrypt.php:81
Stack trace:
#0 /Users/dev-projects/my-magento/vendor/magento/framework/Encryption/Encryptor.php(548): Magento\Framework\Encryption\Adapter\Mcrypt->__construct('115649382234153...', 'rijndael-256', 'cbc', '{s')
#1 /Users/dev-projects/my-magento/vendor/magento/framework/Encryption/Encryptor.php(448): Magento\Framework\Encryption\Encryptor->getCrypt('115649382234153...', 2, '{s')
#2 /Users/dev-projects/my-magento/vendor/magento/module-config/App/Config/Type/System.php(252): Magento\Framework\Encryption\Encryptor->decrypt('6:"design";a:9:...')
#3 /Users/dev-projects/my-magento/vendor/magento/framework/Cache/LockGuardedCacheLoader.php(69): Magento\Config\App\Config\Type\System->Magento\Config\App\Config\Type\{closure}()
#4 /Users/dev-projects/my-magento/vendor/magento/module-config/App/Config/Type/System.php(261): Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData('SYSTEM_CONFIG', Object(Closure), Object(Closure), Object(Closure))
#5 /Users/dev-projects/my-magento/vendor/magento/module-config/App/Config/Type/System.php(195): Magento\Config\App\Config\Type\System->loadDefaultScopeData('default')
#6 /Users/dev-projects/my-magento/vendor/magento/module-config/App/Config/Type/System.php(169): Magento\Config\App\Config\Type\System->getWithParts('default/newreli...')
#7 /Users/dev-projects/my-magento/vendor/magento/framework/App/Config.php(132): Magento\Config\App\Config\Type\System->get('default/newreli...')
#8 /Users/dev-projects/my-magento/vendor/magento/framework/App/Config.php(80): Magento\Framework\App\Config->get('system', 'default/newreli...')
#9 /Users/dev-projects/my-magento/vendor/magento/framework/App/Config.php(93): Magento\Framework\App\Config->getValue('newrelicreporti...', 'default', NULL)
#10 /Users/dev-projects/my-magento/vendor/magento/module-new-relic-reporting/Model/Config.php(94): Magento\Framework\App\Config->isSetFlag('newrelicreporti...')
#11 /Users/dev-projects/my-magento/vendor/magento/module-new-relic-reporting/Plugin/HttpPlugin.php(49): Magento\NewRelicReporting\Model\Config->isNewRelicEnabled()
#12 /Users/dev-projects/my-magento/vendor/magento/framework/Interception/Interceptor.php(121): Magento\NewRelicReporting\Plugin\HttpPlugin->beforeCatchException(Object(Magento\Framework\App\Http\Interceptor), Object(Magento\Framework\App\Bootstrap), Object(Zend_Db_Adapter_Exception))
#13 /Users/dev-projects/my-magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Bootstrap), Object(Zend_Db_Adapter_Exception))
#14 /Users/dev-projects/my-magento/generated/code/Magento/Framework/App/Http/Interceptor.php(39): Magento\Framework\App\Http\Interceptor->___callPlugins('catchException', Array, Array)
#15 /Users/dev-projects/my-magento/vendor/magento/framework/App/Bootstrap.php(267): Magento\Framework\App\Http\Interceptor->catchException(Object(Magento\Framework\App\Bootstrap), Object(Zend_Db_Adapter_Exception))
#16 /Users/dev-projects/my-magento/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#17 /Users/dev-projects/my-magento/vendor/composer/ClassLoader.php(444): include('/Users/lnguyen/...')
#18 /Users/dev-projects/my-magento/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/lnguyen/...')
#19 [internal function]: Composer\Autoload\ClassLoader->loadClass('index')
#20 [internal function]: spl_autoload_call('index')
#21 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Reflection/Runtime/RuntimeReflectionProvider.php(168): class_exists('index')
#22 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Reflection/ReflectionProvider/ChainReflectionProvider.php(25): PHPStan\Reflection\Runtime\RuntimeReflectionProvider->hasClass('index')
#23 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Reflection/ReflectionProvider/MemoizingReflectionProvider.php(30): PHPStan\Reflection\ReflectionProvider\ChainReflectionProvider->hasClass('index')
#24 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Broker/Broker.php(53): PHPStan\Reflection\ReflectionProvider\MemoizingReflectionProvider->hasClass('index')
#25 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/Constant/ConstantStringType.php(210): PHPStan\Broker\Broker->hasClass('index')
#26 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/UnionType.php(124): PHPStan\Type\Constant\ConstantStringType->generalize()
#27 [internal function]: PHPStan\Type\UnionType::PHPStan\Type\{closure}(Object(PHPStan\Type\Constant\ConstantStringType))
#28 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/UnionType.php(127): array_map(Object(Closure), Array)
#29 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/VerbosityLevel.php(58): PHPStan\Type\UnionType->PHPStan\Type\{closure}()
#30 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/UnionType.php(176): PHPStan\Type\VerbosityLevel->handle(Object(Closure), Object(Closure))
#31 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/ArrayType.php(91): PHPStan\Type\UnionType->describe(Object(PHPStan\Type\VerbosityLevel))
#32 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/VerbosityLevel.php(58): PHPStan\Type\ArrayType->PHPStan\Type\{closure}()
#33 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/ArrayType.php(101): PHPStan\Type\VerbosityLevel->handle(Object(Closure), Object(Closure), Object(Closure))
#34 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/Constant/ConstantArrayType.php(392): PHPStan\Type\ArrayType->describe(Object(PHPStan\Type\VerbosityLevel))
#35 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/VerbosityLevel.php(58): PHPStan\Type\Constant\ConstantArrayType->PHPStan\Type\Constant\{closure}()
#36 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/Constant/ConstantArrayType.php(397): PHPStan\Type\VerbosityLevel->handle(Object(Closure), Object(Closure), Object(Closure))
#37 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/UnionTypeHelper.php(64): PHPStan\Type\Constant\ConstantArrayType->describe(Object(PHPStan\Type\VerbosityLevel))
#38 [internal function]: PHPStan\Type\UnionTypeHelper::PHPStan\Type\{closure}(Object(PHPStan\Type\Constant\ConstantArrayType), Object(PHPStan\Type\Constant\ConstantArrayType))
#39 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/UnionTypeHelper.php(65): usort(Array, Object(Closure))
#40 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/UnionType.php(39): PHPStan\Type\UnionTypeHelper::sortTypes(Array)
#41 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/TypeCombinator.php(324): PHPStan\Type\UnionType->__construct(Array)
#42 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/TypeCombinator.php(416): PHPStan\Type\TypeCombinator::union(Object(PHPStan\Type\Constant\ConstantArrayType), Object(PHPStan\Type\Constant\ConstantArrayType))
#43 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/TypeCombinator.php(419): PHPStan\Type\TypeCombinator::PHPStan\Type\{closure}()
#44 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Type/TypeCombinator.php(204): PHPStan\Type\TypeCombinator::processArrayTypes(Array, Array)
#45 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/VariableTypeHolder.php(36): PHPStan\Type\TypeCombinator::union(Object(PHPStan\Type\ArrayType), Object(PHPStan\Type\ArrayType))
#46 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/MutatingScope.php(1946): PHPStan\Analyser\VariableTypeHolder->and(Object(PHPStan\Analyser\VariableTypeHolder))
#47 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/MutatingScope.php(1932): PHPStan\Analyser\MutatingScope->mergeVariableHolders(Array, Array)
#48 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(403): PHPStan\Analyser\MutatingScope->mergeWith(Object(PHPStan\Analyser\MutatingScope))
#49 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(199): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\If_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#50 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(383): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\If_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#51 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(199): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\If_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#52 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(445): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Foreach_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#53 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(199): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Foreach_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#54 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(301): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#55 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(199): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#56 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(358): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#57 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(199): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#58 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(342): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#59 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(168): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#60 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/FileAnalyser.php(92): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#61 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Analyser/Analyser.php(54): PHPStan\Analyser\FileAnalyser->analyseFile('/Users/lnguyen/...', Object(PHPStan\Rules\Registry), Object(PHPStan\Analyser\InferrablePropertyTypesFromConstructorHelper))
#62 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Command/AnalyseApplication.php(105): PHPStan\Analyser\Analyser->analyse(Array, false, NULL, Object(Closure), false, Object(PHPStan\Analyser\InferrablePropertyTypesFromConstructorHelper))
#63 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/src/Command/AnalyseCommand.php(86): PHPStan\Command\AnalyseApplication->analyse(Array, false, Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\ErrorFormatter\RawErrorFormatter), false, false, '/Users/lnguyen/...', Object(_HumbugBox069fea7e7fc7\Symfony\Component\Console\Input\ArgvInput))
#64 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Command/Command.php(228): PHPStan\Command\AnalyseCommand->execute(Object(_HumbugBox069fea7e7fc7\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBox069fea7e7fc7\Symfony\Component\Console\Output\ConsoleOutput))
#65 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(858): _HumbugBox069fea7e7fc7\Symfony\Component\Console\Command\Command->run(Object(_HumbugBox069fea7e7fc7\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBox069fea7e7fc7\Symfony\Component\Console\Output\ConsoleOutput))
#66 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(236): _HumbugBox069fea7e7fc7\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_HumbugBox069fea7e7fc7\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBox069fea7e7fc7\Symfony\Component\Console\Output\ConsoleOutput))
#67 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(137): _HumbugBox069fea7e7fc7\Symfony\Component\Console\Application->doRun(Object(_HumbugBox069fea7e7fc7\Symfony\Component\Console\Input\ArgvInput), Object(_HumbugBox069fea7e7fc7\Symfony\Component\Console\Output\ConsoleOutput))
#68 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/bin/phpstan(63): _HumbugBox069fea7e7fc7\Symfony\Component\Console\Application->run()
#69 phar:///Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan/bin/phpstan(64): _HumbugBox069fea7e7fc7\{closure}()
#70 /Users/dev-projects/my-magento/vendor/phpstan/phpstan/phpstan(6): require('phar:///Users/d...')
#71 {main}
```

**Comment by nmklong** [comment]
I have found the problem in my docker setup

**Comment by ka2le** [comment]
> I have found the problem in my docker setup

Could you explain what your problem was?

I am getting the exact same issue when trying to upgrade from Magento 2.2.11 to 2.3 and have tried a lot of different things without success.
