### ISSUE TITLE
Cannot invoice orders which contain bundle products comprised of physical and virtual products

### ISSUE THREAD

**Issue by iosos-excel** [magento/magento2#27144]
### Preconditions (*)

1. Magento 2.3.3 or Magento 2.3.4

### Steps to reproduce (*)

1. In the admin, create a sample physical product (This item has weight)
2. Create a sample virtual product (This item has no weight)
3. Create a sample bundle product
    * Set "Dynamic Price" to "No"
    * In "Bundle Items" add 2 options
        * Assign the sample physical product to option 1
        * Assign the sample virtual product to option 2
4. In the front-end, add the sample bundle product to cart
5. Check out using any payment method (I used Purchase Order, but we originally found this bug in a Braintree credit card order)
6. Back in the admin, invoice the sample order

### Expected result (*)

1. Order is successfully invoiced

### Actual result (*)

1. Browser displays a 500 error
2. The order is not invoiced
2. The Apache error log contains the following:
```
PHP Fatal error: Uncaught TypeError: Return value of Magento\InventorySourceSelection\Model\Request\InventoryRequest::getItems() must be of the type array, null returned in /www/vendor/magento/module-inventory-source-selection/Model/Request/InventoryRequest.php:102
Stack trace:
#0 /www/vendor/magento/module-inventory-source-selection-api/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php(97): Magento\InventorySourceSelection\Model\Request\InventoryRequest->getItems()
#1 /www/vendor/magento/module-inventory-source-selection/Model/Algorithms/PriorityBasedAlgorithm.php(73): Magento\InventorySourceSelectionApi\Model\Algorithms\Result\GetDefaultSortedSourcesResult->execute(Object(Magento\InventorySourceSelection\Model\Request\InventoryRequest), Array)
#2 /www/vendor/magento/module-inventory-source-selection-api/Model/SourceSelectionService.php(61) in /www/vendor/magento/module-inventory-source-selection/Model/Request/InventoryRequest.php on line 102
```

### Additional information
* Does not happen if the bundle product contains only virtual products
* Does not happen if the price of the bundle product is set to dynamic

**Comment by iosos-excel** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @iosos-excel. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @iosos-excel, here is your [Magento instance](https://i-27144-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27144-2-3-4.instances.magento-community.engineering/admin_eee7](https://i-27144-2-3-4.instances.magento-community.engineering/admin_eee7)
Login: `840f8935` Password: `076d19a5b913`
Instance will be terminated in up to 3 hours.

**Comment by iosos-excel** [comment]
I cannot reproduce the issue in the Magento instance provided. However, the instance is missing the entire inventory source system, which is where the error seems to occur according to the logs. If I install a totally fresh/vanilla Magento 2.3.4 on my machine the inventory system is present and the issue is reproducible.

**Comment by Renu05** [comment]
Hi @iosos-excel ,

I have tested in Vanilla Magento 2.3.4  . I am able to reproduce the above said error.

**Steps Followed :** 
I have added bundle product in cart which contains both virtual product and simple product and dynamic price is set to No.
After successful order place when i am trying to create a invoice for this order i am getting the error.

**Got Following error** : 
> Fatal error: Uncaught TypeError: Return value of Magento\InventorySourceSelection\Model\Request\InventoryRequest::getItems() must be of the type array, null returned in /var/www/html/magento234ee/vendor/magento/module-inventory-source-selection/Model/Request/InventoryRequest.php:102 Stack trace: #0 /var/www/html/magento234ee/vendor/magento/module-inventory-source-selection-api/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php(97): Magento\InventorySourceSelection\Model\Request\InventoryRequest->getItems() magento/magento2#1 /var/www/html/magento234ee/vendor/magento/module-inventory-source-selection/Model/Algorithms/PriorityBasedAlgorithm.php(73): Magento\InventorySourceSelectionApi\Model\Algorithms\Result\GetDefaultSortedSourcesResult->execute(Object(Magento\InventorySourceSelection\Model\Request\InventoryRequest), Array) magento/magento2#2 /var/www/html/magento234ee/vendor/magento/module-inventory-source-selection-api/Model/SourceSelectionService.php(61): Magento\InventorySourceSelection\Model\Algorithms\PriorityBasedAlgorithm->execute(Object(M in /var/www/html/magento234ee/vendor/magento/module-inventory-source-selection/Model/Request/InventoryRequest.php on line 102

**Comment by sdzhepa** [comment]
Due to the description and discussion under
This issue seems related to [Magento Inventory Project (a.k.a MSI)](https://github.com/magento/inventory)
Transfer this issue into https://github.com/magento/inventory/issues
