### ISSUE TITLE
Script moving plugin triggered on JSON Response

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27649]
### Preconditions (*)
When triggering raw (without content) JSON output from Controller, Script moving plugin is being triggered, causing failure.

### Steps to reproduce (*)
```php
public function execute()
    {
        return $this->resultFactory->create(ResultFactory::TYPE_JSON);
    }
```

### Expected result (*)
Controller output:
```
[
  
]
```

### Actual result (*)
```
Fatal error: Uncaught TypeError: strpos() expects parameter 1 to be string, null given in /var/www/html/vendor/magento/module-theme/Controller/Result/JsFooterPlugin.php:44 Stack trace: #0 /var/www/html/vendor/magento/module-theme/Controller/Result/JsFooterPlugin.php(44): strpos(NULL, '</body') #1 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Theme\Controller\Result\JsFooterPlugin->beforeSendResponse(Object(Magento\Framework\App\Response\Http\Interceptor)) #2 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Response\Http\Interceptor->Magento\Framework\Interception\{closure}() #3 /var/www/html/generated/code/Magento/Framework/App/Response/Http/Interceptor.php(117): Magento\Framework\App\Response\Http\Interceptor->___callPlugins('sendResponse', Array, Array) #4 /var/www/html/vendor/magento/framework/App/Bootstrap.php(262): Magento\Framework\App\Response\Http\Interceptor->sendResponse() #5 /var/www/html/pub/index.php(40): Magento\Framework\App\ in /var/www/html/vendor/magento/module-theme/Controller/Result/JsFooterPlugin.php on line 44
```

**Comment by mrtuvn** [comment]
@lbajsarowicz maybe this problem related with this PR https://github.com/magento/magento2/pull/27270/

**Comment by ihor-sviziev** [comment]
Hi @lbajsarowicz,
Seems like this issue was already fixed in https://github.com/magento/magento2/commit/ff1aa7e5f0a37bf13c9c466c50297843bd949d47 and not reproducing anymore in 2.4-develop branch.

Could you confirm that?

**Comment by lbajsarowicz** [comment]
Looks like it is.
