### ISSUE TITLE
POST /rest/V1/carts/1/items

### ISSUE THREAD

**Issue by pborges** [magento/magento2#2782]
Posting

```
{
    "cartItem": {
        "itemId":1,
        "qty": 1
    }
}
```

to

```
/rest/V1/carts/1/items
```

results in

```
{
  "message": "No such entity with %fieldName = %fieldValue",
  "parameters": {
    "fieldName": "cartId",
    "fieldValue": null
  }
}
```

and sending

```
{
    "cartItem": {
        "itemId":1,
        "cartId":1,
        "qty": 1
    }
}
```

results in

```
{
  "message": "Internal Error. Details are available in Magento log file. Report ID: webapi-5678ac6216cf5"
}
```

log excerpt

```
[2015-12-22 01:50:26] main.CRITICAL: exception 'LogicException' with message 'Report ID: webapi-5678ac6216cf5; Message: Property "CartId" does not have corresponding setter in class "Magento\Quote\Api\Data\CartItemInterface".' in /var/www/magento2/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:194
Stack trace:
#0 /var/www/magento2/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(LogicException))
#1 /var/www/magento2/app/code/Magento/Webapi/Controller/Rest.php(163): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(LogicException))
#2 /var/www/magento2/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/magento2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /var/www/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 /var/www/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []
```

Sending the following works as expected

```
{
    "cartItem": {
        "itemId":1,
        "quoteId":1,
        "qty": 1
    }
}
``
```

**Comment by ishakhsuvarov** [comment]
@pborges Thank you for reporting this.
We have 2 internal tickets aimed at fixing described issue `MAGETWO-46732` and `MAGETWO-46852`.
I'll post an update to this ticket when it is fixed.

**Comment by ishakhsuvarov** [comment]
@pborges Closing the ticket for now as the issue seems to be already fixed in the `develop` branch. Please reopen if you have any additional questions.

**Comment by mukdam** [comment]
I have same issue in magento 2.0.4

**Comment by webspeaks** [comment]
Occurs in 2.0.7 as well. Any update?

**Comment by nickmarx12345678** [comment]
same issue in 2.0.x
