### ISSUE TITLE
Argument 4 passed to Magento\Developer\Model\View\Asset\PreProcessor\FrontendCompilation::processContent() must be an instance of Magento\Framework\View\Asset\File\FallbackContext

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#27949]
### Preconditions (*)

1.Magento 2.4-develop, 2.3.4+
2. php 7.3

### Steps to reproduce (*)

1. Enable developer mode
2. Go to Admin -> Stores -> Configuration ->Developer -> Frontend development workflow and Enable **Client side less compilation** 
3. In the Css settings tab enable **Merge css files** (this is must have)

### Expected result (*)

1. Page should render without error

### Actual result (*)

Page return error

Fatal error: Uncaught TypeError: Argument 4 passed to Magento\Developer\Model\View\Asset\PreProcessor\FrontendCompilation::processContent() must be an instance of Magento\Framework\View\Asset\File\FallbackContext, instance of Magento\Framework\View\Asset\File\Context given, called in /var/www/html/vendor/magento/module-developer/Model/View/Asset/PreProcessor/FrontendCompilation.php on line 90 and defined in /var/www/html/vendor/magento/module-developer/Model/View/Asset/PreProcessor/FrontendCompilation.php:107 Stack trace: #0 /var/www/html/vendor/magento/module-developer/Model/View/Asset/PreProcessor/FrontendCompilation.php(90): Magento\Developer\Model\View\Asset\PreProcessor\FrontendCompilation->processContent('7f8cd4729905343...', '@import 'source...', '', Object(Magento\Framework\View\Asset\File\Context)) #1 /var/www/html/vendor/magento/module-developer/Model/View/Asset/PreProcessor/PreprocessorStrategy.php(74): Magento\Developer\Model\View\Asset\PreProcessor\FrontendCompilation->process(Object(Magento\Framework\View\As in /var/www/html/vendor/magento/module-developer/Model/View/Asset/PreProcessor/FrontendCompilation.php on line 107

Maybe fallback mechanism fail to find merged asset files

**Comment by magento-engcom-team** [comment]
@engcom-Delta Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33871` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @mrtuvn  @engcom-Delta @engcom-Kilo 

Could you please provide more details about steps to reproduce
```
1. Enable developer mode 
2. Enable Client side compilation
3. Enable Merge css files (this is must have)
```

Which exact CLI commands or steps in Admin Panel were run. In which order

This information will help to Triage and prioritize  this issue quicker and easier

**Comment by mrtuvn** [comment]
You can follow this order
#1 enable developer mode via cli
#2 go to admin change less compilation to frontend instead server
#3 enable minify css

**Comment by NikolayCherevan** [comment]
@mrtuvn mrtuvn, but what can i do when apmin panel does not working.. i can't change  "less compilation to client instead server"

**Comment by mrtuvn** [comment]
@NikolayCherevan that is not my case. Problem only relate with working admin

**Comment by engcom-Alfa** [comment]
The issue is reproducible on 2.4-develop

![Peek 2020-07-19 18-00](https://user-images.githubusercontent.com/51679138/87950919-96b94300-cab0-11ea-8bc3-400bd34fad4c.gif)

**Comment by engcom-Alfa** [comment]
Hi @mrtuvn . Thanks for collaboration. This PR was reviewed on Community Contribution Triage meeting. The recording of the meeting you can look by the [link](https://www.youtube.com/watch?v=4dFuALJ0L4I&t=24s)

**Comment by usman786cs** [comment]
I'm also facing this issue, I wanted to set client side compilation because browser was not picking latest version of css after every deployment. 


Any progress on this please?

**Comment by sunilit42** [comment]
@sivaschenko 
i think for client side we need to restict via code like you can not able to use css merge for client side mode

is that work then i will work on this?

**Comment by vrielsa** [comment]
@magento I am working on this

**Comment by ArunRackron** [comment]
php bin/magento deploy:mode:set production -s

php bin/magento setup:static-content:deploy -f

its working for me

**Comment by ArunRackron** [comment]
after that set developer mode : 
php bin/magento deploy:mode:set developer

**Comment by ArunRackron** [comment]
php bin/magento config:set dev/css/merge_css_files 0

its working for me

**Comment by engcom-Bravo** [comment]
Hi @mrtuvn,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is still reproducible.Kindly refer the screenshots.


<img width="1440" alt="Screenshot 2024-11-25 at 10 05 04" src="https://github.com/user-attachments/assets/79cfbabb-ef1d-4d81-b03d-df5cd2893cb1">


Page return error.Hence Confirming the issue.

Thanks.
