### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#2806]
Trying to convert my db to m2. Not a really helpful error message!:

```
SQLSTATE[HY000] [2002] No such file or directory
#0 /Users/ccarnell/Sites/vax-uk2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect()
#1 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(332): Zend_Db_Adapter_Pdo_Mysql->_connect()
#2 /Users/ccarnell/Sites/vax-uk2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(861): Magento\Framework\DB\Adapter\Pdo\Mysql->_connect()
#3 /Users/ccarnell/Sites/vax-uk2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(931): Zend_Db_Adapter_Abstract->quote('uk_default', NULL)
#4 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(1354): Zend_Db_Adapter_Abstract->quoteInto('`store_website`...', 'uk_default', NULL, NULL)
#5 /Users/ccarnell/Sites/vax-uk2/vendor/magento/zendframework1/library/Zend/Db/Select.php(1007): Magento\Framework\DB\Adapter\Pdo\Mysql->quoteInto('`store_website`...', 'uk_default', NULL)
#6 /Users/ccarnell/Sites/vax-uk2/vendor/magento/zendframework1/library/Zend/Db/Select.php(477): Zend_Db_Select->_where('`store_website`...', 'uk_default', NULL, true)
#7 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/DB/Select.php(107): Zend_Db_Select->where('`store_website`...', 'uk_default', NULL)
#8 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(367): Magento\Framework\DB\Select->where('`store_website`...', 'uk_default')
#9 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(341): Magento\Framework\Model\ResourceModel\Db\AbstractDb->_getLoadSelect('`store_website`...', 'uk_default', Object(Magento\Store\Model\Website\Interceptor))
#10 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Store/Model/ResourceModel/Website/Interceptor.php(102): Magento\Framework\Model\ResourceModel\Db\AbstractDb->load(Object(Magento\Store\Model\Website\Interceptor), 'uk_default', 'code')
#11 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Model/AbstractModel.php(516): Magento\Store\Model\ResourceModel\Website\Interceptor->load(Object(Magento\Store\Model\Website\Interceptor), 'uk_default', 'code')
#12 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-store/Model/Website.php(236): Magento\Framework\Model\AbstractModel->load('uk_default', 'code')
#13 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Store/Model/Website/Interceptor.php(24): Magento\Store\Model\Website->load('uk_default', 'code')
#14 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-store/Model/WebsiteRepository.php(64): Magento\Store\Model\Website\Interceptor->load('uk_default', 'code')
#15 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Store/Model/WebsiteRepository/Interceptor.php(24): Magento\Store\Model\WebsiteRepository->get('uk_default')
#16 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-store/Model/StoreResolver/Website.php(46): Magento\Store\Model\WebsiteRepository\Interceptor->get('uk_default')
#17 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-store/Model/StoreResolver.php(125): Magento\Store\Model\StoreResolver\Website->getAllowedStoreIds('uk_default')
#18 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-store/Model/StoreResolver.php(111): Magento\Store\Model\StoreResolver->readStoresData()
#19 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-store/Model/StoreResolver.php(80): Magento\Store\Model\StoreResolver->getStoresData()
#20 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-store/Model/StoreManager.php(151): Magento\Store\Model\StoreResolver->getCurrentStoreId()
#21 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Store/Model/StoreManager/Interceptor.php(76): Magento\Store\Model\StoreManager->getStore(NULL)
#22 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager\Interceptor->getStore(NULL)
#23 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Store/Model/StoreManagerInterface/Proxy/Interceptor.php(63): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL)
#24 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-store/Model/Resolver/Store.php(29): Magento\Store\Model\StoreManagerInterface\Proxy\Interceptor->getStore(NULL)
#25 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/App/Config/ScopePool.php(119): Magento\Store\Model\Resolver\Store->getScope(NULL)
#26 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/App/Config/ScopePool.php(74): Magento\Framework\App\Config\ScopePool->_getScopeCode('store', NULL)
#27 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/App/Config.php(45): Magento\Framework\App\Config\ScopePool->getScope('store', NULL)
#28 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Locale/Resolver.php(90): Magento\Framework\App\Config->getValue('general/locale/...', 'store')
#29 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Locale/Resolver.php(107): Magento\Framework\Locale\Resolver->getDefaultLocale()
#30 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Locale/Resolver.php(64): Magento\Framework\Locale\Resolver->setLocale(NULL)
#31 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(103): Magento\Framework\Locale\Resolver->__construct(Object(Magento\Framework\App\Config), 'general/locale/...', 'store', NULL)
#32 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#33 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#34 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#35 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'localeResolver', 'Magento\\Framewo...')
#36 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#37 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#38 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#39 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'pageConfig', 'Magento\\Framewo...')
#40 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#41 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#42 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(273): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#43 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(249): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray(Array)
#44 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, NULL, NULL, 'generators', 'Magento\\Framewo...')
#45 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#46 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#47 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#48 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'generatorPool', 'Magento\\Framewo...')
#49 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#50 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#51 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#52 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'layout', 'Magento\\Framewo...')
#53 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#54 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#55 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#56 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'context', 'Magento\\Review\\...')
#57 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Review\\...', Array, Array)
#58 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Review\\...')
#59 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Review\\...')
#60 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Review\\...', NULL, 'reviewRenderer', 'Mirasvit\\Search...')
#61 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Mirasvit\\Search...', Array, Array)
#62 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Mirasvit\\Search...')
#63 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(273): Magento\Framework\ObjectManager\ObjectManager->get('Mirasvit\\Search...')
#64 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(285): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray(Array)
#65 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(249): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray(Array)
#66 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, NULL, Array, 'indexes', 'Mirasvit\\Search...')
#67 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Mirasvit\\Search...', Array, Array)
#68 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Mirasvit\\Search...')
#69 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Mirasvit\\Search...')
#70 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Mirasvit\\Search...', NULL, 'indexPool', 'Mirasvit\\Search...')
#71 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Mirasvit\\Search...', Array, Array)
#72 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Mirasvit\\Search...')
#73 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Mirasvit\\Search...')
#74 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Mirasvit\\Search...', NULL, 'result', 'Mirasvit\\Search...')
#75 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Mirasvit\\Search...', Array, Array)
#76 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Mirasvit\\Search...')
#77 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/PluginList/PluginList.php(233): Magento\Framework\ObjectManager\ObjectManager->get('Mirasvit\\Search...')
#78 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Interceptor.php(139): Magento\Framework\Interception\PluginList\PluginList->getPlugin('Magento\\Framewo...', 'front-controlle...')
#79 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#80 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#81 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#82 /Users/ccarnell/Sites/vax-uk2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#83 {main}
```

**Comment by danielc1234** [comment]
What method are you using?

**Comment by mazhalai** [comment]
@craigcarnell can you please give us more details on how to reproduce this?

**Comment by cscd98** [comment]
@mazhalai @danielc1234 Used the data migration tool and then visited the site.

**Comment by cscd98** [comment]
Probably a Mac OS X issue with PHP 7 and percona so closing
