### ISSUE TITLE
HTTP ERROR 500  When click on import page

### ISSUE THREAD

**Issue by imtiaz0405** [magento/magento2#28115]
Hi , 
I have just setup new magneto 2.3.5 website .Evert hing working fine. In the admin panel when  click on the import button i  am getting 500 Internal Server Error. Please help to resolve this issue

Error Logs here.
```
[05-May-2020 20:03:21 UTC] PHP Fatal error:  Uncaught TypeError: Return value of Magento\ImportExport\Model\Import\ImageDirectoryBaseProvider::getDirectoryRelativePath() must be of the type string, null returned in /vendor/magento/module-import-export/Model/Import/ImageDirectoryBaseProvider.php:62

Stack trace:
#0 /vendor/magento/module-import-export/Block/Adminhtml/Import/Edit/Form.php(246): Magento\ImportExport\Model\Import\ImageDirectoryBaseProvider->getDirectoryRelativePath()

#1 /home3/wbminter/public_html/wbm/vendor/magento/module-backend/Block/Widget/Form.php(156): Magento\ImportExport\Block\Adminhtml\Import\Edit\Form->_prepareForm()

#2 /vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Backend\Block\Widget\Form->_beforeToHtml()

#3 vendor/magento/framework/View/Element/AbstractBlock.php(1104): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()

#4 //vendor/magento/module-import-export/Model/Import/ImageDirectoryBaseProvider.php on line 
```

**Comment by Sutharsan27** [comment]
@imtiaz0405 Can you please be more specific on the option which you choose within Magento Admin for Import? I need to recreate this issue in Magento 2.3.5 and update the exact steps to reproduce

**Comment by imtiaz0405** [comment]
Hi Sir, I have resolved the issue by set time, country  in the general settings . 

the issue was that when i click on the import link to upload the CSV file for the products,the error appear. The link not open.
