### ISSUE TITLE
Uncaught Error: Mismatched anonymous define() module: function(t,g,u)

### ISSUE THREAD

**Issue by evokul** [magento/magento2#28489]
### Summary (*)

I have a fresh installation of Magento but this error is showing on all of the pages.This may be duplicate of some other but I cannot find solution for my problem so asking here.
![image](https://user-images.githubusercontent.com/5388434/83628491-2dd84300-a5b6-11ea-85a9-561f29ce017b.png)
When I trace back it get me to minicart file and points here :
![image](https://user-images.githubusercontent.com/5388434/83628514-3e88b900-a5b6-11ea-9292-6b6b963ff9b9.png)
Please let me know what I am missing or doing wrong I checked there is no jQuery conflicts and did deploy cache clean etc. I have a child theme of luma. Actually I did replaced it's 2.3.4 database with 2.2.7 magento site. So codebase is 2.3.4 and db is 2.2.7 is this create problem? tried disabling all modules and child theme but error is still there.
### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by evokul** [comment]
Please proceed with this further

**Comment by evokul** [comment]
@magento-admin

**Comment by engcom-Lima** [comment]
Hello @evokul 
Yes, replacement on 2.3.4 database with 2.2.7 magento site can create this problem.
If you have a database backup, you can make upgrade to 2.3.5-p1 
As for the functionality of the site, is it working fine?

**Comment by engcom-Delta** [comment]
@evokul,  we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by abrar71** [comment]
The issue is valid and properly reported

**Comment by magefast** [comment]
Have same JS Error.

Error was called by External Js - added via admin panel in Header Scripts. 
In my case - was JS by Cookiebot

**Comment by sibelius** [comment]
any workaround for this?

**Comment by winds1983** [comment]
Same issue in 2.4.4:
```
Uncaught Error: Mismatched anonymous define() module: function($){"use strict";return $.effects.define("blind","hide",(function(options,done){var map=

{up:["bottom","top"],vertical:["bottom","top"],down:["top","bottom"],left:["right","left"],horizontal:["right","left"],right:["left","right"]}
,element=$(this),direction=options.direction||"up",start=element.cssClip(),animate={clip:$.extend({},start)},placeholder=$.effects.createPlaceholder(element);animate.clip[map[direction][0]]=animate.clip[map[direction][1]],"show"===options.mode&&(element.cssClip(animate.clip),placeholder&&placeholder.css($.effects.clipToBox(animate)),animate.clip=start),placeholder&&placeholder.animate($.effects.clipToBox(animate),options.duration,options.easing),element.animate(animate,{queue:!1,duration:options.duration,easing:options.easing,complete:done})}))}
```

Any solution for this?

**Comment by lakshmana** [comment]
@winds1983 same issue on 2.4.4. At first I thought it was linked to this patch`MDVA-44887` Do you find any solution. 
```
Uncaught Error: Mismatched anonymous define() module: function($){"use strict";return $.effects.define("fade","toggle",(function(e,t){var n="show"===e.mode;$(this).css("opacity",n?0:1).animate({opacity:n?1:0},{queue:!1,duration:e.duration,easing:e.easing,complete:t})}))}
https://requirejs.org/docs/errors.html#mismatch
    at makeError (require.min.js:17:53)
    at intakeDefines (require.min.js:81:132)
    at localRequire (require.min.js:104:1)
    at defContext.require (mixins.min.js:11:401)
    at requirejs (require.min.js:123:16)

**Comment by gwharton** [comment]
> @winds1983 same issue on 2.4.4. At first I thought it was linked to this patch`MDVA-44887` Do you find any solution.
> 
> ```
> Uncaught Error: Mismatched anonymous define() module: function($){"use strict";return $.effects.define("fade","toggle",(function(e,t){var n="show"===e.mode;$(this).css("opacity",n?0:1).animate({opacity:n?1:0},{queue:!1,duration:e.duration,easing:e.easing,complete:t})}))}
> https://requirejs.org/docs/errors.html#mismatch
>     at makeError (require.min.js:17:53)
>     at intakeDefines (require.min.js:81:132)
>     at localRequire (require.min.js:104:1)
>     at defContext.require (mixins.min.js:11:401)
>     at requirejs (require.min.js:123:16)
>     
> ```

I also see this on 2.4.4. Any solutions?

**Comment by gwharton** [comment]
> @winds1983 same issue on 2.4.4. At first I thought it was linked to this patch`MDVA-44887` Do you find any solution.
> 
> ```
> Uncaught Error: Mismatched anonymous define() module: function($){"use strict";return $.effects.define("fade","toggle",(function(e,t){var n="show"===e.mode;$(this).css("opacity",n?0:1).animate({opacity:n?1:0},{queue:!1,duration:e.duration,easing:e.easing,complete:t})}))}
> https://requirejs.org/docs/errors.html#mismatch
>     at makeError (require.min.js:17:53)
>     at intakeDefines (require.min.js:81:132)
>     at localRequire (require.min.js:104:1)
>     at defContext.require (mixins.min.js:11:401)
>     at requirejs (require.min.js:123:16)
>     
> ```

I'm figuring you are using magepack with 2.4.4 

You need to exclude the file jquery/ui-modules/effects/effect-fade from your magepack.config.js file

If this file is excluded from packing, it works fine.

**Comment by sarfarazbheda** [comment]
We are also facing the same issue, Are there any fixes?

**Comment by lakshmana** [comment]
@sarfarazbheda as hinted above, you have to remove the from magepack.config.js either manually or by script before running `magepack bundle`
`RUN sed -i '/jquery\/ui-modules\/effects/d' ./magepack.config.js`
