### ISSUE TITLE
issue with magento to

### ISSUE THREAD

**Issue by wadrajab** [magento/magento2#28626]
Hello Everyone,

I'm trying to open Magento from a local server ( XAMPP ) but this error keeps showing for me

any ideas how can I solve this issue?

Fatal error: Uncaught ReflectionException: Class Magento\Framework\App\ResourceConnection\Proxy does not exist in /Applications/XAMPP/xamppfiles/htdocs/world/vendor/magento/framework/Code/Reader/ClassReader.php:26 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/world/vendor/magento/framework/Code/Reader/ClassReader.php(26): ReflectionClass->__construct('Magento\\Framewo...') #1 /Applications/XAMPP/xamppfiles/htdocs/world/vendor/magento/framework/ObjectManager/Definition/Runtime.php(54): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Framewo...') #2 /Applications/XAMPP/xamppfiles/htdocs/world/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(48): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Framewo...') #3 /Applications/XAMPP/xamppfiles/htdocs/world/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') #4 /Applications/XAMPP/xamppfiles/htdocs/world/ven in /Applications/XAMPP/xamppfiles/htdocs/world/vendor/magento/framework/Code/Reader/ClassReader.php on line 26

**Comment by engcom-Delta** [comment]
Hello @wadrajab 
Could you provide more details for reproduce this issue?
Please add version of magento.
Is Class `Magento\Framework\App\ResourceConnection\Proxy` exists in youre magento?

Thank you!

**Comment by engcom-Alfa** [comment]
Hi @wadrajab .
I'm closing this issue due to inactivity.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
