### ISSUE TITLE
Recoverable Error: session_regenerate_id(): Failed to create(read) session ID: user (path: 127.0.0.1:11211)

### ISSUE THREAD

**Issue by johnbendi** [magento/magento2#2873]
I get the above error when trying to access the admin area. Below is the detailed stacktrace:

```
Recoverable Error: session_regenerate_id(): Failed to create(read) session ID: user (path: 127.0.0.1:11211) in /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/Session/SessionManager.php on line 473
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(4096, 'session_regener...', '/usr/share/ngin...', 473, Array)
#1 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/Session/SessionManager.php(473): session_regenerate_id(true)
#2 /usr/share/nginx/html/magedemo/app/code/Magento/Backend/Model/Auth/Session.php(229): Magento\Framework\Session\SessionManager->regenerateId()
#3 /usr/share/nginx/html/magedemo/app/code/Magento/Backend/Model/Auth.php(156): Magento\Backend\Model\Auth\Session->processLogin()
#4 /usr/share/nginx/html/magedemo/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(205): Magento\Backend\Model\Auth->login('admin', 'bbullish2015')
#5 /usr/share/nginx/html/magedemo/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(157): Magento\Backend\App\Action\Plugin\Authentication->_performLogin(Object(Magento\Framework\App\Request\Http))
#6 /usr/share/nginx/html/magedemo/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(125): Magento\Backend\App\Action\Plugin\Authentication->_processNotLoggedInUser(Object(Magento\Framework\App\Request\Http))
#7 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#8 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#9 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Array, 'designLoader')
#10 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#11 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#13 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminMassaction...')
#14 /usr/share/nginx/html/magedemo/app/code/Magento/Backend/App/Action/Plugin/MassactionKey.php(33): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#17 /usr/share/nginx/html/magedemo/var/generation/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php(39): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#18 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/App/FrontController.php(55): Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#19 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#21 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#22 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#23 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#24 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#26 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'storeCookieVali...')
#27 /usr/share/nginx/html/magedemo/app/code/Magento/Store/Model/Plugin/StoreCookie.php(78): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 [internal function]: Magento\Store\Model\Plugin\StoreCookie->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#30 /usr/share/nginx/html/magedemo/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#31 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /usr/share/nginx/html/magedemo/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#33 /usr/share/nginx/html/magedemo/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#34 {main}
```

None of the discussions regardng this issue elsewhere has helped me. I'm on ubuntu 15.10, php7, nginx. I also have latest develop branch.

**Comment by johnbendi** [comment]
Additional bug reference: https://bugs.php.net/bug.php?id=71187

**Comment by johnbendi** [comment]
My temporary workaround as I understand it:
![magento_savehandler_read_patch](https://cloud.githubusercontent.com/assets/1025834/12083575/25071f4c-b2a6-11e5-9506-781b362e5c6b.png)
As can be seen from the image I had to cast the `SaveHandler` `read` method's return value to a string.

**Comment by dooblem** [comment]
Hello,
We also got the problem. The fix works. At least it allows login in backoffice.
But we decided not to use memcached for now.

**Comment by veloraven** [comment]
@johnbendi thank you for your feedback.
Is this issue still actual?
If it is please provide the used Magento version and information if it was clear install or upgrade from some previous version.
If it is not, please close it.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
