### ISSUE TITLE
Fatal error when using Custom Admin URL

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#28804]
### Preconditions (*)
1. Magento 2.4-develop
2. Set custom Admin URL using Admin Panel (not `env.php`)

### Steps to reproduce (*)
1. Open `https://custom-domain.test/backend`

### Expected result (*)
1. Login screen displayed

### Actual result (*)
```
Fatal error: Uncaught TypeError: explode() expects parameter 2 to be string, null given in /var/www/html/lib/internal/Magento/Framework/App/Router/Base.php:182 Stack trace: #0 /var/www/html/lib/internal/Magento/Framework/App/Router/Base.php(182): explode('/', NULL) #1 /var/www/html/lib/internal/Magento/Framework/App/Router/Base.php(165): Magento\Framework\App\Router\Base->parseRequest(Object(Magento\Framework\App\Request\Http)) #2 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\Router\Base->match(Object(Magento\Framework\App\Request\Http)) #3 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Backend\App\Router\Interceptor->___callParent('match', Array) #4 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Backend\App\Router\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #5 /var/www/html/generated/code/Magento/Backend/App/Router/Interceptor.php(26 in /var/www/html/lib/internal/Magento/Framework/App/Router/Base.php on line 182
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28804-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28804-2-4-develop.instances.magento-community.engineering/admin_ef33](https://i-28804-2-4-develop.instances.magento-community.engineering/admin_ef33)
Login: `660145c2` Password: `19ac19771dc1`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28804-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28804-2-4-develop.instances.magento-community.engineering/admin_04ee](https://i-28804-2-4-develop.instances.magento-community.engineering/admin_04ee)
Login: `053ae396` Password: `b11cdbadba22`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@lbajsarowicz : Tested in 2.4 develop instances. I have created a custom URL - https://i-28804-2-4-develop.instances.magento-community.engineering/backend/ . What I did is correct?

Custom Admin URL:
![image](https://user-images.githubusercontent.com/58288685/87763682-cbb86200-c832-11ea-8b2b-3758f26d00f5.png)

404 Error:
![image](https://user-images.githubusercontent.com/58288685/87763732-dd9a0500-c832-11ea-9c55-deb2141f8b5b.png)

**Comment by engcom-Delta** [comment]
Hi @lbajsarowicz thank you for your report, I'm not able to reproduce issue by general steps you described on clean 2.4-develop
**Manual testing scenario:**
- Create additional virtualhost for url `http://admin.magento2dev.loc`. 
- Set Admin Base URL
 ![image](https://user-images.githubusercontent.com/51681379/88920082-e0561a80-d274-11ea-8f81-f42438fb539a.png)
- Save Config

**Result:**
:heavy_check_mark: Login screen displayed
![image](https://user-images.githubusercontent.com/51681379/88921850-e0a3e500-d277-11ea-984a-00e556820937.png)

:heavy_check_mark: Successfully logged into admin
![image](https://user-images.githubusercontent.com/51681379/88921956-12b54700-d278-11ea-8160-285607de8ef9.png)


Could you provide additional information how `Admin Base URL` was configured in your case?

**Comment by engcom-Delta** [comment]
@lbajsarowicz,  we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by lbajsarowicz** [comment]
2022, issue is still with us :) 

```
TypeError: explode(): Argument #2 ($string) must be of type string, null given in /var/www/html/vendor/magento/framework/App/Router/Base.php:182
Stack trace:
#0 /var/www/html/vendor/magento/framework/App/Router/Base.php(182): explode('/', NULL)
#1 /var/www/html/vendor/magento/framework/App/Router/Base.php(165): Magento\Framework\App\Router\Base->parseRequest(Object(Magento\Framework\App\Request\Http))
#2 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Router\Base->match(Object(Magento\Framework\App\Request\Http))
#3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Router\Base\Interceptor->___callParent('match', Array)
#4 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Router\Base\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#5 /var/www/html/generated/code/Magento/Framework/App/Router/Base/Interceptor.php(23): Magento\Framework\App\Router\Base\Interceptor->___callPlugins('match', Array, Array)
#6 /var/www/html/vendor/magento/framework/App/FrontController.php(144): Magento\Framework\App\Router\Base\Interceptor->match(Object(Magento\Framework\App\Request\Http))
#7 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#9 /var/www/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#11 /var/www/html/vendor/fastly/magento2/Model/FrontControllerPlugin.php(135): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Fastly\Cdn\Model\FrontControllerPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /var/www/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 /var/www/html/modules/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php(32): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Infortis\Cgen\Plugin\Magento\Framework\App\FrontController->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#19 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#21 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#22 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#23 {main}
```
