### ISSUE TITLE
module-catalog_Model_ProductLink_Data_ListCriteria::__construct error on sku of all integers

### ISSUE THREAD

**Issue by eraq** [magento/magento2#28841]
### Preconditions (*)

1. 2.3.5
2.

### Steps to reproduce (*)

1. to produce create a configurable product with sku '5751', 
2. attempt to pragmatically get then save this product with no changes

### Expected result (*)

1. product save successfully
2.

### Actual result (*)

1. type enforcement error occurs, error pasted below
2. 
"messages": {
        "error": [
            {
                "code": 500,
                "message": "Fatal Error: 'Uncaught TypeError: Argument 1 passed to Magento\\Catalog\\Model\\ProductLink\\Data\\ListCriteria::__construct() must be of the type string, integer given, called in C:\\wamp64\\www\\magento.local\\htdocs\\vendor\\magento\\module-catalog\\Model\\ProductLink\\Repository.php on line 178 and defined in C:\\wamp64\\www\\magento.local\\htdocs\\vendor\\magento\\module-catalog\\Model\\ProductLink\\Data\\ListCriteria.php:38\nStack trace:\n#0 C:\\wamp64\\www\\magento.local\\htdocs\\vendor\\magento\\module-catalog\\Model\\ProductLink\\Repository.php(178): Magento\\Catalog\\Model\\ProductLink\\Data\\ListCriteria->__construct(5751, NULL, Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#1 C:\\wamp64\\www\\magento.local\\htdocs\\vendor\\magento\\module-catalog\\Model\\Product.php(1463): Magento\\Catalog\\Model\\ProductLink\\Repository->getList(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#2 C:\\wamp64\\www\\magento.local\\htdocs\\generated\\code\\Magento\\Catalog\\Model\\Product\\Interceptor.php(817): Magento\\Catalog\\Model\\Product->getProductLinks()\n#3 C:\\wamp64\\www\\magento.local' in 'C:\\wamp64\\www\\magento.local\\htdocs\\vendor\\magento\\module-catalog\\Model\\ProductLink\\Data\\ListCriteria.php' on line 38",
                "trace": "Trace is not available."
            }
        ]
    }

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

**S0**

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

Note: easy fix would be strval() around return of method getSku() as there are other methods such as ListCriteria::getBelongsToProductSku that suffer the same error

**Comment by eraq** [comment]
as a follow up, the issue only occurs if you use the new suggested save via ProductRepositoryInterface..
so `$product->save();` works fine, but `$this->$_productRepositoryInterface->save($product);` fails.
