### ISSUE TITLE
Class Magento\Catalog\Model\Product\Image\CacheFactory does not exist

### ISSUE THREAD

**Issue by davidtwco** [magento/magento2#2889]
Hi,

I've just installed Magento 2 and migrated my data to the new database, having done this, I now log in to the admin panel and see a white page with the following text:

```
Class Magento\Catalog\Model\Product\Image\CacheFactory does not exist
#0 /var/www/html/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Magento\\Catalog...')
#1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\\Catalog...')
#2 [internal function]: spl_autoload_call('Magento\\Catalog...')
#3 /var/www/html/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Catalog...')
#4 /var/www/html/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Catalog...')
#5 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Catalog...')
#6 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...', Array)
#7 /var/www/html/vendor/magento/framework/Data/Collection/EntityFactory.php(37): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Catalog...', Array)
#8 /var/www/html/vendor/magento/framework/Data/Collection.php(610): Magento\Framework\Data\Collection\EntityFactory->create('Magento\\Catalog...')
#9 /var/www/html/vendor/magento/framework/Data/Collection/AbstractDb.php(569): Magento\Framework\Data\Collection->getNewEmptyItem()
#10 /var/www/html/vendor/magento/framework/Data/Collection/AbstractDb.php(550): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#11 /var/www/html/vendor/magento/module-backend/Block/Widget/Grid/Extended.php(476): Magento\Framework\Data\Collection\AbstractDb->load()
#12 /var/www/html/vendor/magento/module-backend/Block/Dashboard/Tab/Products/Ordered.php(80): Magento\Backend\Block\Widget\Grid\Extended->_prepareCollection()
#13 /var/www/html/vendor/magento/module-backend/Block/Widget/Grid.php(402): Magento\Backend\Block\Dashboard\Tab\Products\Ordered->_prepareCollection()
#14 /var/www/html/vendor/magento/module-backend/Block/Widget/Grid/Extended.php(503): Magento\Backend\Block\Widget\Grid->_prepareGrid()
#15 /var/www/html/vendor/magento/module-backend/Block/Widget/Grid.php(467): Magento\Backend\Block\Widget\Grid\Extended->_prepareGrid()
#16 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(651): Magento\Backend\Block\Widget\Grid->_beforeToHtml()
#17 /var/www/html/vendor/magento/module-backend/Block/Dashboard/Grids.php(53): Magento\Framework\View\Element\AbstractBlock->toHtml()
#18 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(257): Magento\Backend\Block\Dashboard\Grids->_prepareLayout()
#19 /var/www/html/vendor/magento/framework/View/Layout.php(744): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor))
#20 /var/www/html/var/generation/Magento/Framework/View/Layout/Interceptor.php(349): Magento\Framework\View\Layout->createBlock('Magento\\Backend...', 'dashboard.grids', Array)
#21 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(375): Magento\Framework\View\Layout\Interceptor->createBlock('Magento\\Backend...', 'dashboard.grids', Array)
#22 /var/www/html/vendor/magento/module-backend/Block/Dashboard.php(54): Magento\Framework\View\Element\AbstractBlock->addChild('grids', 'Magento\\Backend...')
#23 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(257): Magento\Backend\Block\Dashboard->_prepareLayout()
#24 /var/www/html/vendor/magento/framework/View/Layout/Generator/Block.php(139): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor))
#25 /var/www/html/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#26 /var/www/html/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#27 /var/www/html/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#28 /var/www/html/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#29 /var/www/html/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#30 /var/www/html/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#31 /var/www/html/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#32 /var/www/html/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#33 /var/www/html/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#34 /var/www/html/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#35 /var/www/html/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Backend...')
#36 /var/www/html/vendor/magento/module-backend/Controller/Adminhtml/Dashboard/Index.php(35): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Backend...')
#37 /var/www/html/var/generation/Magento/Backend/Controller/Adminhtml/Dashboard/Index/Interceptor.php(24): Magento\Backend\Controller\Adminhtml\Dashboard\Index->execute()
#38 /var/www/html/vendor/magento/framework/App/Action/Action.php(102): Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->execute()
#39 /var/www/html/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#40 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#41 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#42 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->___callParent('dispatch', Array)
#43 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Array, 'adminAuthentica...')
#44 /var/www/html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#45 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#46 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#47 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Array, 'designLoader')
#48 /var/www/html/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#49 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#50 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#51 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Array, 'adminMassaction...')
#52 /var/www/html/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#53 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#54 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#55 /var/www/html/var/generation/Magento/Backend/Controller/Adminhtml/Dashboard/Index/Interceptor.php(39): Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#56 /var/www/html/vendor/magento/framework/App/FrontController.php(55): Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#57 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#58 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#59 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#60 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#61 /var/www/html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#62 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#63 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#64 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'storeCookieVali...')
#65 /var/www/html/vendor/magento/module-store/Model/Plugin/StoreCookie.php(78): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#66 [internal function]: Magento\Store\Model\Plugin\StoreCookie->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#67 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#68 /var/www/html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#69 /var/www/html/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#70 /var/www/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#71 /var/www/html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#72 {main}
```

This appears to be the same issue as seen in #2738, but I do not wish to install sample data over my migrated data. I had this issue only on the Categories and Catalog pages before migration.

**Comment by benmarks** [comment]
@DavidTWco Can you state which `MAGE_MODE` you're running in and confirm that you've taken appropriate steps w/r/t caches and code generation?

**Comment by davidtwco** [comment]
@benmarks I'm using nginx and my configuration has `set $MAGE_MODE developer;` and `fastcgi_param  MAGE_MODE $MAGE_MODE;` so I'm pretty sure I'm in developer mode.

Given the holiday period, this was initially set up pre-holiday, so I'm a little hazy on the exact steps and details that I performed. As far as caches and code generation is concerned, I'm pretty sure I've set the permissions for the magento directory correctly - I definitely followed those steps during installation.

```
drwxrwx---  4 magento-owner www-data   4096 Dec 21 12:24 app
drwxrwx---  2 magento-owner www-data   4096 Dec 21 12:24 bin
-rw-rw----  1 magento-owner www-data 434532 Dec 21 12:24 CHANGELOG.md
-rw-rw----  1 magento-owner www-data   1899 Jan  5 09:06 composer.json
-rw-rw----  1 magento-owner www-data 316799 Jan  5 09:07 composer.lock
-rw-rw----  1 magento-owner www-data   3425 Dec 21 12:24 CONTRIBUTING.md
-rw-rw----  1 magento-owner www-data  10011 Dec 21 12:24 CONTRIBUTOR_LICENSE_AGREEMENT.html
-rw-rw----  1 magento-owner www-data    631 Dec 21 12:24 COPYING.txt
drwxrwx---  4 magento-owner www-data   4096 Dec 21 12:24 dev
-rw-rw----  1 magento-owner www-data   2918 Dec 21 12:24 Gruntfile.js
-rw-rw----  1 magento-owner www-data   7592 Dec 21 12:24 .htaccess
-rw-rw----  1 magento-owner www-data   6419 Dec 21 12:24 .htaccess.sample
-rw-rw----  1 magento-owner www-data   1358 Dec 21 12:24 index.php
drwxrwx---  4 magento-owner www-data   4096 Dec 21 12:24 lib
-rw-rw----  1 magento-owner www-data  10374 Dec 21 12:24 LICENSE_AFL.txt
-rw-rw----  1 magento-owner www-data  10364 Dec 21 12:24 LICENSE.txt
-rw-rw----  1 magento-owner www-data   4108 Dec 21 12:24 nginx.conf.sample
drwxrwxr-x 30 david         david      4096 Dec 22 10:00 node_modules
-rw-rw----  1 magento-owner www-data   1283 Dec 22 09:58 package.json
-rw-rw----  1 magento-owner www-data   1659 Dec 21 12:24 .php_cs
-rw-rw----  1 magento-owner www-data    804 Dec 21 12:24 php.ini.sample
drwxrwx---  2 magento-owner www-data   4096 Dec 21 12:24 phpserver
drwxrwx---  6 magento-owner www-data   4096 Dec 21 12:24 pub
drwxrwx---  7 magento-owner www-data   4096 Dec 21 12:24 setup
-rw-rw----  1 magento-owner www-data   3731 Dec 21 12:24 .travis.yml
drwxrwx---  7 magento-owner www-data   4096 Dec 21 12:24 update
drwxrwx--- 10 magento-owner www-data   4096 Jan  5 09:32 var
drwxrwx--- 27 magento-owner www-data   4096 Jan  5 09:07 vendor
```

If there are other steps in the installation then I likely followed them but I can't remember any off-hand.

**Comment by davidtwco** [comment]
Infact my mistake, enabling developer mode using the command line tool has fixed this issue, apologies.

**Comment by benmarks** [comment]
Interesting, and thanks for the followup. Is there any way we can improve messaging about how to enable developer mode? Was it our documentation which sent you down the wrong path?

**Comment by davidtwco** [comment]
Not particularly, I think the documentation was pretty clear, I was mislead by the `nginx.conf.sample` file which looked like it set the `MAGE_MODE` variable and I assumed then that was it - perhaps if it were clearer which mode you are currently in?

**Comment by benmarks** [comment]
> I was mislead by the nginx.conf.sample file which looked like it set the MAGE_MODE variable

Yes, this is confusing, perhaps we should remove it.

> perhaps if it were clearer which mode you are currently in

I had a similar thought in the shower this morning (I live a rich & full life), though my idea was for an admin panel indication which wouldn't have helped you... You can determine the mode via CLI though by running `$ bin/magento deploy:mode:show`

**Comment by davidtwco** [comment]
Perhaps it could be displayed as a status message at the top of any commands from the magento binary?

```
$ bin/magento migrate:data ...
Current Magento Mode: DEVELOPER
...
```

Or something to that effect, however I experienced the issue that I had before migration too, at which it's possible the binary hasn't been used - so maybe it should be added to the web installer?
