### ISSUE TITLE
Catalog Search index PHP Fatal error:  Uncaught Error: Wrong parameters for Elasticsearch\Common\Exceptions\ServerErrorResponseException([string $message [, long $code [, Throwable $previous = NULL]]])

### ISSUE THREAD

**Issue by JamesX88** [magento/magento2#29454]
### Preconditions (*)

1. Magento 2.4.0
2. Apache 2.4.42
3. PHP v7.4.3

### Steps to reproduce (*)

1. Attempt to reindex via command: sudo -u www-data php bin/magento indexer:reindex catalogsearch_fulltext

### Expected result (*)

1. I expect the Catalog Search to reindex properly

### Actual result (*)

root@cbdev:/var/www/html# sudo -u www-data php bin/magento indexer:reindex catalogsearch_fulltext
Catalog Search index PHP Fatal error:  Uncaught Error: Wrong parameters for Elasticsearch\Common\Exceptions\ServerErrorResponseException([string $message [, long $code [, Throwable $previous = NULL]]]) in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:665
Stack trace:
#0 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(665): Exception->__construct()
#1 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(320): Elasticsearch\Connections\Connection->process5xxError()
#2 /var/www/html/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}()
#3 /var/www/html/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then()
#4 /var/www/html/vendor/ezimuel/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then()
#5 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Con in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 665

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by JamesX88** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @JamesX88. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @JamesX88, here is your [Magento instance](https://i-29454-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29454-2-4-develop.instances.magento-community.engineering/admin_d420](https://i-29454-2-4-develop.instances.magento-community.engineering/admin_d420)
Login: `61a72bef` Password: `9a35d7498317`
Instance will be terminated in up to 3 hours.

**Comment by JamesX88** [comment]
I'm unable to test cli commands on the develop instance. My issue is on a vanilla 2.4.0 fresh install with no products created yet.

**Comment by JamesX88** [comment]
Here are some perhaps relevant logs from /var/log/elasticsearch/elasticsearch.log

`
[2020-08-10T13:43:33,628][WARN ][r.suppressed             ] [crownbees] path: /_alias/magento2_product_1, params: {name=magento2_product_1}
org.elasticsearch.discovery.MasterNotDiscoveredException: null
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onTimeout(TransportMasterNodeAction.java:220) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:325) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:252) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:598) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:636) [elasticsearch-7.8.1.jar:7.8.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
[2020-08-10T13:43:35,045][WARN ][o.e.c.c.ClusterFormationFailureHelper] [crownbees] master not discovered or elected yet, an election requires a node with id [MF6oCvwkSK2ajdfgDDBbpg], have discovered [{crownbees}{73nJ8SATRqW9RdpiMYaJrw}{htnkp_6uQ8Oq4jfif2L46A}{localhost}{127.0.0.1:9300}{dilmrt}{ml.machine_memory=8348585984, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}] which is not a quorum; discovery will continue using [127.0.0.1:9301, 127.0.0.1:9302, 127.0.0.1:9303, 127.0.0.1:9304, 127.0.0.1:9305, [::1]:9300, [::1]:9301, [::1]:9302, [::1]:9303, [::1]:9304, [::1]:9305] from hosts providers and [{crownbees}{73nJ8SATRqW9RdpiMYaJrw}{htnkp_6uQ8Oq4jfif2L46A}{localhost}{127.0.0.1:9300}{dilmrt}{ml.machine_memory=8348585984, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}] from last-known cluster state; node term 646, last-accepted version 31 in term 2
[2020-08-10T13:43:43,435][WARN ][r.suppressed             ] [crownbees] path: /_alias/magento2_product_1, params: {name=magento2_product_1}
org.elasticsearch.discovery.MasterNotDiscoveredException: null
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onTimeout(TransportMasterNodeAction.java:220) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:325) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:252) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:598) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:636) [elasticsearch-7.8.1.jar:7.8.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
`

**Comment by JamesX88** [comment]
This issue was resolved by downgrading from ElasticSearch 7.8.x (latest) to 7.6.2 explicitly.

**Comment by JamesX88** [comment]
@magento give me 2.4-develop instance

**Comment by JamesX88** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment]
Hi JamesX88 ,

The issue was not reproduced. Request you to kindly try to reproduce the issue on latest Magento instance, or provide more details to the issue.

Attached is the screenshot

<img width="490" alt="Screenshot 2021-05-31 at 1 41 51 PM" src="https://user-images.githubusercontent.com/51681435/120162699-45bcc400-c216-11eb-8925-8db787989031.png">


Thanks,

**Comment by engcom-Lima** [comment]
Hi @JamesX88,

Hoping, your issue is resolved and also we did not get any response from you more than 14 days. Hence closing this ticket.

Please feel free to raise the new ticket or reopen the existing ticket. if you have any issue.

**Comment by muhamedrafyq** [comment]
> This issue was resolved by downgrading from ElasticSearch 7.8.x (latest) to 7.6.2 explicitly.

Worked for me Thanks
