### ISSUE TITLE
`/var/generation/Magento/Framework/App/Response` folder missing

### ISSUE THREAD

**Issue by jkristoffer** [magento/magento2#2977]
On the `develop` as of date, I noticed that installing with the CLI omits the folder `/var/generation/Magento/Framework/App/Response` and gave me permission issues.

I had to work around it by removing the generation folder and accessing the server from a browser which generates the above mentioned folder an no more permission issues.

This is the command I use to install magento:

`/var/www/html/magento2/bin/magento setup:install --admin-firstname=Jane --admin-lastname=Doe --admin-email=your.mail@mail.com --admin-user=admin --admin-password='Gl0r10u5F00d'--base-url={{base_url}} --db-host=localhost --db-name=magento --db-user=magento --db-password=magento --language=en_US --currency=SGD --timezone=Asia/Singapore --session-save=db`

Deleting the `generation` folder required me to reapply my database configurations by executing the following:

`/var/www/html/magento2/bin/magento setup:config:set --db-host=localhost --db-name=magento --db-user=magento --db-password=magento`

After all this, I'm able to access the magento website. The setup i'm running all this is in a Centos:6 Docker container.

---

This is error I received before applying my workaround 

```
exception 'Magento\Framework\Exception\LocalizedException' with message 'Can't create directory /var/www/html/magento2/var/generation/Magento/Framework/App/ResourceConnection/.' in /var/www/html/magento2/lib/internal/Magento/Framework/Code/Generator.php:103
Stack trace:
#0 /var/www/html/magento2/lib/internal/Magento/Framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Magento\\Framewo...')
#1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\\Framewo...')
#2 [internal function]: spl_autoload_call('Magento\\Framewo...')
#3 /var/www/html/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Framewo...')
#4 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Framewo...')
#5 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Framewo...')
#6 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#7 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#8 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'resource', 'Magento\\Framewo...')
#9 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#10 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#11 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#12 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'frontendFactory', 'Magento\\Framewo...')
#13 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#14 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#15 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#16 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'frontendPool', 'Magento\\Framewo...')
#17 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#18 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#19 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#20 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'cacheFrontendPo...', 'Magento\\Framewo...')
#21 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#22 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#23 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#24 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'cache', 'Magento\\Framewo...')
#25 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#26 /var/www/html/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#27 /var/www/html/magento2/lib/internal/Magento/Framework/App/ObjectManager/Environment/Developer.php(68): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#28 /var/www/html/magento2/lib/internal/Magento/Framework/App/ObjectManagerFactory.php(181): Magento\Framework\App\ObjectManager\Environment\Developer->configureObjectManager(Object(Magento\Framework\Interception\ObjectManager\Config\Developer), Array)
#29 /var/www/html/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(385): Magento\Framework\App\ObjectManagerFactory->create(Array)
#30 /var/www/html/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(232): Magento\Framework\App\Bootstrap->initObjectManager()
#31 /var/www/html/magento2/index.php(38): Magento\Framework\App\Bootstrap->createApplication('Magento\\Framewo...')
#32 {main}
```

**Comment by mazhalai** [comment]
Can you confirm that your var directory has the recommended permissions? You shouldn't have to delete the generation folder, unless you updated the code base and require a re-compile(in production mode).

**Comment by jkristoffer** [comment]
I can confirm the directory has the recommended permissions. The issue seems to be a missing folder `/var/generation/Magento/Framework/App/Response`

**Comment by mazhalai** [comment]
@jkristoffer is this still an issue?

**Comment by mazhalai** [comment]
@jkristoffer closing as non responsive.
