### ISSUE TITLE
Cannot install M2.1.4 and cannot run bin/magento anymore Cannot instantiate interface Magento\MediaGallerySynchronizationApi\Model\ImportFilesInterface

### ISSUE THREAD

**Issue by seansan** [magento/magento2#30568]
### Preconditions  and Steps to reproduce (*) (*)
Install Magento 2.4.0 then your modules, then 2.4.1
composer update (works fine)
then run bin/magento and nothing works anymore
after adding erorr 

### Expected result (*)
Upgrade should work

### Actual result (*)

Fatal error: Uncaught Error: Cannot instantiate interface Magento\MediaGallerySynchronizationApi\Model\ImportFilesInterface in /home/sohbv/public_html/m2_dev/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /home/sohbv/public_html/m2_dev/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#1 /home/sohbv/public_html/m2_dev/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#2 /home/sohbv/public_html/m2_dev/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#3 /home/sohbv/public_html/m2_dev/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#4 /home/sohbv/public_html/m2_dev/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php in /home/sohbv/public_html/m2_dev/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 50

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

DOnt know how to proceeed with Magento

Tried

rm -rf var/cache/* var/session/* var/log/* var/tmp/* var/generation/* var/page_cache/* var/view_preprocessed/* pub/static/* generated/*

and after even

rm -rf vendor/*

then ran composer update

**Comment by seansan** [comment]
You also need to flush redis cache when upgrading .. maybe this is something that magento can BUILD IN >.. take the values from env.php and remove alle caches during upgrade
