### ISSUE TITLE
The specified path is not allowed

### ISSUE THREAD

**Issue by kassner** [magento/magento2#31582]
### Preconditions

1. Magento 2.3.6; (the error seems to happen on 2.4, but the message is different: `The path is not allowed: media/something-invalid.xml`)

### Steps to reproduce

1. Make sure the file `var/resource_config.json` does not exist;
2. Access `{BASEURL}/media/something-invalid.xml`;
3. _expected results don't happen_;
4. Now the `var_resoruce_config.json` file exists is generated;
5. Access `{BASEURL}/media/something-invalid.xml`;
6. _expected results happen_;

### Expected result

1. 404 error;
2. No errors logged;

### Actual result (*)

1. 404 error :+1:;
2. 
```
The specified path is not allowed.
#0 /var/www/magento/vendor/magento/framework/App/Bootstrap.php(261): Magento\MediaStorage\App\Media->launch()
#1 /var/www/magento/pub/get.php(84): Magento\Framework\App\Bootstrap->run(Object(Magento\MediaStorage\App\Media))
#2 {main}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible.
Accessing the site with url: http://<yourstoeurl>/media/something-invalid.xml giving 404 error but also below error is getting generated in logs.  (var/log/system.log)
[2022-09-13T10:11:33.372312+00:00] main.ERROR: The path is not allowed: media/something-invalid.xml [] 
Note: This issue is not observed for other urls ex: http://mg24.local/media/fewffefe.html. No error logs generated.
![image](https://user-images.githubusercontent.com/60198231/189876266-feb79f1f-9e32-4fe1-a106-7d587f7c00d0.png)
