### ISSUE TITLE
Error: Call to a member function addressGetAttributeValidationClass() on null

### ISSUE THREAD

**Issue by steven-hardy** [magento/magento2#32065]
### Preconditions (*)

1. 2.4.1
2. PHP 7.4

### Steps to reproduce (*)

1. When navigating through the customer account, you click on edit address.
2. I have replaced these files from the 2.4 master branch so they have not been modified in any way

### Expected result (*)

1. I expect to be able to go through to customer/address/edit/id/3/
2. 
![image](https://user-images.githubusercontent.com/50919787/107390941-1e6bab00-6af0-11eb-9e35-3ffdd6e1e98b.png)

### Actual result (*)

1. Here is the error that I am presented with:
```
Error: Call to a member function addressGetAttributeValidationClass() on null in vendor/magento/module-customer/view/frontend/templates/address/edit.phtml:23 Stack trace: #0 vendor/magento/framework/View/TemplateEngine/Php.php(71): include() #1 vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Customer\Block\Address\Edit), '/Users/steven/S...', Array) #2 vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView('/Users/steven/S...') #3 vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Framework\View\Element\Template->_toHtml() #4 vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() #5 vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache() #6 vendor/magento/framework/View/Layout.php(566): Magento\Framework\View\Element\AbstractBlock->toHtml() #7 vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Layout->_renderBlock('customer_addres...') #8 generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('customer_addres...') #9 vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('customer_addres...') #10 generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('customer_addres...', false) #11 vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement('customer_addres...', false) #12 vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('content_schedul...', false) #13 generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('content_schedul...') #14 vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content_schedul...') #15 generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('content_schedul...', false) #16 vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement('content_schedul...', false) #17 vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('content_schedul...', false) #18 generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('content_schedul...') #19 vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content_schedul...') #20 generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('content_schedul...', false) #21 vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement('content_schedul...', false) #22 vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('content_schedul...', false) #23 generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('content_schedul...') #24 vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content_schedul...') #25 generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('content_schedul...', false) #26 vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement('content_schedul...', false) #27 vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('content_schedul...', false) #28 generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('content_schedul...') #29 vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content_schedul...') #30 generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('content_schedul...', false) #31 vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement('content_schedul...', false) #32 vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('content', false) #33 generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('content') #34 vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content') #35 generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('content', false) #36 vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement('content', false) #37 vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('main', false) #38 generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('main') #39 vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main') #40 generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('main', false) #41 vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement('main', false) #42 vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('columns', false) #43 generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('columns') #44 vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns') #45 generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('columns', false) #46 vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement('columns', false) #47 vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('main.content', false) #48 generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('main.content') #49 vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content') #50 generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('main.content', false) #51 vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement('main.content', false) #52 vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false) #53 generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper') #54 vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper') #55 generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('page.wrapper', false) #56 vendor/magento/framework/View/Layout.php(594): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false) #57 vendor/magento/framework/View/Layout.php(544): Magento\Framework\View\Layout->_renderContainer('root', false) #58 generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('root') #59 vendor/magento/framework/View/Layout.php(497): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root') #60 generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('root', true) #61 vendor/magento/framework/View/Layout.php(963): Magento\Framework\View\Layout\Interceptor->renderElement('root') #62 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput() #63 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array) #64 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() #65 generated/code/Magento/Framework/View/Layout/Interceptor.php(347): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array) #66 vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput() #67 vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor)) #68 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor)) #69 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array) #70 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor)) #71 generated/code/Magento/Framework/View/Result/Page/Interceptor.php(95): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array) #72 vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor)) #73 generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch() #74 vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch() #75 index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #76 /Users/steven/.composer/vendor/laravel/valet/server.php(219): require('/Users/steven/S...') #77 {main}
```
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by steven-hardy** [comment]
@magento give me 2.4-develop instance

**Comment by steven-hardy** [comment]
This is not happening in the instance that you have given me. I would like to know what I can do to resolve this. The theme is custom built however, we have not changed anything to do with the `module-customer`

**Comment by steven-hardy** [comment]
![image](https://user-images.githubusercontent.com/50919787/107399669-e5840400-6af8-11eb-82f8-3938c05add50.png)
This is the expected result.

**Comment by mrtuvn** [comment]
why do you need to replace file with 2.4 master branch ? Have you test with 2.4.2 new release?
Maybe some files modify and not sync with magento
https://github.com/magento/magento2/blob/2.4.2/app/code/Magento/Customer/view/frontend/layout/customer_address_form.xml
https://github.com/magento/magento2/blob/2.4.2/app/code/Magento/Customer/view/frontend/templates/address/edit.phtml

**Comment by steven-hardy** [comment]
We have managed to find the problem file. There is no issue here with Magento. It is the custom file that we have created that was the issue. Reverting /app/code/Magento/Customer/view/frontend/layout/customer_address_form.xml solved our issue.

**Comment by steven-hardy** [comment]
Closing

**Comment by mrtuvn** [comment]
Glad it's help
