### ISSUE TITLE
Declarative schema bug : default value cannot be negative on signed int

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#32303]
### Preconditions (*)

Magento 2.4.1

### Steps to reproduce (*)

Create a table with thoses columns : 

```
<column xsi:type="int" name="some_name" unsigned="false" nullable="false" identity="false" default="-1" comment="Some Name"/>
```

Note that `unsigned` is set to false.

### Expected result (*)

Table is created

### Actual result (*)

```
Element 'column', attribute 'default': [facet 'pattern'] The value '-1' is not accepted by the pattern '\d+|null'.
```

### Additional Information
Attaching module which helps in issue reproduction:
[Magz.zip](https://github.com/magento/magento2/files/9775478/Magz.zip)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround. (When migrating from M1 for instance)_
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Nuranto** [comment]
Still relevant

**Comment by engcom-Alfa** [comment]
HI @Nuranto 
We have followed the steps that you have provided and we are not able to reproduce the issue. The table was created successfully , please refer the attached screenshot
![image](https://user-images.githubusercontent.com/51679138/118468915-dc6f8800-b722-11eb-8d32-bf5dcf8076e8.png)

**Comment by Nuranto** [comment]
Just tested again on Magento 2.4.2, and I still got : 
```
The XML in file "/var/www/html/app/code/**/**/etc/db_schema.xml" is invalid:
Element 'column', attribute 'default': [facet 'pattern'] The value '-1' is not accepted by the pattern '\d+|null'.
Line: 17

Element 'column', attribute 'default': '-1' is not a valid value of the local atomic type.
Line: 17

Verify the XML and try again.
```


For some reason I don't understand, in your case, you probably didn't went through `\d+|null` (`vendor/magento/framework/Setup/Declaration/Schema/etc/types/integers/integer.xsd`) validation regexp, which do fail with negative value.

**Comment by gabrieldagama** [comment]
Hi @Nuranto, can you clarify on which action are you having the error? For example, I do get the XSD validation error on my PHPStorm, but if I try to run `php bin/magento setup:db-schema:upgrade` it does work and the column is added.

Maybe you can clarify and add more details on the step to reproduce the problem?

Thanks.

**Comment by Nuranto** [comment]
I got it while running `setup:upgrade`.
I have obviously the same error when running `setup:db-schema:upgrade`, but with a trace. Here it is if that can helps : 
```
#0 /var/www/html/vendor/magento/framework/Config/Reader/Filesystem.php(132): Magento\Framework\Config\Reader\Filesystem->_readFiles(Array)
#1 /var/www/html/vendor/magento/framework/Setup/Declaration/Schema/Declaration/ReaderComposite.php(46): Magento\Framework\Config\Reader\Filesystem->read('all')
#2 /var/www/html/vendor/magento/framework/Setup/Declaration/Schema/SchemaConfig.php(76): Magento\Framework\Setup\Declaration\Schema\Declaration\ReaderComposite->read('all')
#3 /var/www/html/setup/src/Magento/Setup/Model/DeclarationInstaller.php(57): Magento\Framework\Setup\Declaration\Schema\SchemaConfig->getDeclarationConfig()
#4 /var/www/html/setup/src/Magento/Setup/Model/Installer.php(846): Magento\Setup\Model\DeclarationInstaller->installSchema(Array)
#5 /var/www/html/setup/src/Magento/Setup/Model/Installer.php(894): Magento\Setup\Model\Installer->declarativeInstallSchema(Array)
#6 /var/www/html/setup/src/Magento/Setup/Console/Command/DbSchemaUpgradeCommand.php(83): Magento\Setup\Model\Installer->installSchema(Array)
#7 /var/www/html/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DbSchemaUpgradeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DbSchemaUpgradeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#13 {main} [] []
```

Here is my db_schema.xml schema and table tags : 

```
<?xml version="1.0"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Setup/Declaration/Schema/etc/schema.xsd">
    <table name="table_name" resource="default" engine="innodb" comment="Table comment">
```

Is it the same as yours ?

I don't know what else could differs...

PHP version : 7.4.12, running on a Docker `php:7.4-apache` based image.

**Comment by engcom-Hotel** [comment]
Hello @Nuranto,

We have tried to reproduce this issue in Magento 2.4-develop with the mentioned steps but for us the table is creating successfully. So we are unable to reproduce the issue. Please find below our db_schema.xml file content:

![image](https://user-images.githubusercontent.com/51681618/134862887-d3e38c16-a27e-44aa-ab10-e8264f316a7b.png)


Below is the screenshot of `bin/magento setup:upgrade` command:

![image](https://user-images.githubusercontent.com/51681618/134862627-c9aefe06-9e22-4de9-b3af-4909d6b59d85.png)

Below is the screenshot of table created in database:

![image](https://user-images.githubusercontent.com/51681618/134862731-7f61625b-ee7b-4bd8-8018-f37d81b44000.png)

Please let us know if we missed any step, in order to reproduce the issue.

Thanks

**Comment by Nuranto** [comment]
I still reproduce this bug on 2.4.3.

I don't know why you cannot reproduce, but let's look at `xsd` : for `int`, `src/vendor/magento/framework/Setup/Declaration/Schema/etc/types/integers/integer.xsd` applies, and the regex is `\d+|null` which does not accepts negative values. It should be `-?\d+|null`, right ?

If you can't reproduce, maybe something in your configuration makes the validation to be skipped ? Or maybe regex has different behaviour regarding PHP or libxml version ? ( mine : PHP 7.4.19, libxml Version => 2.9.4 )

**Comment by engcom-Hotel** [comment]
Hello @Nuranto,

I have checked the versions for PHP and libxml they are as follows:
- PHP 7.4.20
- libxml 2.9.4

I request you to please try to reproduce it in Magento 2.4-develop and let us know if you are able to reproduce it.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @Nuranto,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by sufyanrightpoint** [comment]
Still reproducible in 2.4.4

**Comment by engcom-Hotel** [comment]
Hello @sufyanrightpoint,

Are the steps to reproduce is same as mentioned in the main description or different? If different can you please provide detailed information on that to proceed further on this issue?

Thanks

**Comment by sufyanrightpoint** [comment]
> Hello @sufyanrightpoint,
> 
> Are the steps to reproduce is same as mentioned in the main description or different? If different can you please provide detailed information on that to proceed further on this issue?
> 
> Thanks

The steps are the same as above. The only difference I had was that I was using the existing `sales_order` table

```
<table name="sales_order" resource="default">
        <column xsi:type="int" name="export_to_bpcs" unsigned="false" nullable="false" default="-1" identity="false" comment="Export to BPCS"/>
    </table>
```

**Comment by engcom-Hotel** [comment]
Hello @sufyanrightpoint,

Thanks for your reply!

We are reopening this issue for further processing.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @sufyanrightpoint @Nuranto,

Thanks for the report and collaboration!

We are able to reproduce the issue in the latest development branch i.e 2.4-develop with the provided steps. As a piece of additional information, we are attaching the module which helps in the reproduction of the issue.

Thanks
