### ISSUE TITLE
Can't add product via rest api with nginx server

### ISSUE THREAD

**Issue by peteandmad** [magento/magento2#32654]
### Preconditions (*)
1. Magento 2.3.5-p2.
2. Nginx web server.

### Steps to reproduce (*)
1. Try using rest api to add product to cart.

### Expected result (*)

1. product add to cart successfully.

### Actual result (*)

1. appears this log error
```
2021/04/02 05:16:36 [error] 1094#1094: *21803 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Magento\InventorySales\Model\IsProductSalableForRequestedQtyCondition\bccomp() in /var/www/html/vendor/magento/module-inventory-sales/Model/IsProductSalableForRequestedQtyCondition/IsSalableWithReservationsCondition.php:93
Stack trace:
#0 /var/www/html/vendor/magento/module-inventory-sales/Model/IsProductSalableForRequestedQtyCondition/IsProductSalableForRequestedQtyConditionChain.php(222): Magento\InventorySales\Model\IsProductSalableForRequestedQtyCondition\IsSalableWithReservationsCondition->execute('1611247073', 1, 1)
#1 /var/www/html/vendor/magento/module-inventory-sales/Model/IsProductSalableForRequestedQtyCondition/IsProductSalableForRequestedQtyConditionChain.php(162): Magento\InventorySales\Model\IsProductSalableForRequestedQtyCondition\IsProductSalableForRequestedQtyConditionChain->processSufficientConditions('1611247073', 1, 1)
#2 /var/www/html/vendor/magento/module-inventory-sales/Plugin/StockState/CheckQuoteItemQtyPlugi" while reading response header from upstream, client: xx.xx.xx.xx, server: xx.com, request: "GET /rest/V1/carts/mine HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "xx.com"
2021/04/02 05:17:03 [error] 1094#1094: *22267 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Magento\InventorySales\Model\IsProductSalableForRequestedQtyCondition\bccomp() in /var/www/html/vendor/magento/module-inventory-sales/Model/IsProductSalableForRequestedQtyCondition/IsSalableWithReservationsCondition.php:93
Stack trace:
#0 /var/www/html/vendor/magento/module-inventory-sales/Model/IsProductSalableForRequestedQtyCondition/IsProductSalableForRequestedQtyConditionChain.php(222): Magento\InventorySales\Model\IsProductSalableForRequestedQtyCondition\IsSalableWithReservationsCondition->execute('1611247073', 1, 1)
#1 /var/www/html/vendor/magento/module-inventory-sales/Model/IsProductSalableForRequestedQtyCondition/IsProductSalableForRequestedQtyConditionChain.php(162): Magento\InventorySales\Model\IsProductSalableForRequestedQtyCondition\IsProductSalableForRequestedQtyConditionChain->processSufficientConditions('1611247073', 1, 1)
#2 /var/www/html/vendor/magento/module-inventory-sales/Plugin/StockState/CheckQuoteItemQtyPlugi" while reading response header from upstream, client: xx.xx.xx.xx, server: xx.com, request: "GET /rest/V1/carts/mine HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "xx.com"
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by peteandmad** [comment]
For more Information I was already install

`apt-get install -y php7.2-bcmath`

**Comment by ihor-sviziev** [comment]
Hi @peteandmad,
It looks like you don't have installed one of the required PHP extensions.
Could you try to run the `composer install` command? It should say which extension you have missing.

**Comment by ihor-sviziev** [comment]
Hi @peteandmad,
I am closing this issue now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!
