### ISSUE TITLE
Very large configurable products fail to index in ElasticSearch

### ISSUE THREAD

**Issue by jurvi** [magento/magento2#32703]
### Preconditions (*)

1. Magento 2.4.2 with ElasticSearch 7.7
2. Very large configurable product, in our case 1440 variants leading to over 32766 characters long name that gets concatenated from all variants' names.

### Steps to reproduce (*)

1. Just run reindexing with a very large configurable product as mentioned in preconditions

### Expected result (*)

1. Reindex success, very large configurable product is found in ES index

### Actual result (*)

1. Error message in ES container, very large configurable product is not indexed

`{"type": "server", "timestamp": "2021-04-09T13:25:32,754Z", "level": "DEBUG", "component": "o.e.a.b.TransportShardBulkAction", "cluster.name": "docker-cluster", "node.name": "elasticsearch.magento2.local", "message": "[magento2_product_29_v3][0] failed to execute bulk item (index) index {[magento2_product_29_v3][document][39571], source[n/a, actual length: [64.7kb], max length: 2kb]}", "cluster.uuid": "KIBD_2DdSSGk8BiMkZqDpw", "node.id": "6Nnn7o8QRhOCX4uVdd8J3g" ,
"stacktrace": ["java.lang.IllegalArgumentException: DocValuesField \"name.sort_name\" is too large, must be <= 32766"`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

This same bug was already mentioned before in AT LEAST 2 other issues, yet it's clearly still around in 2.4.2:

#28966 
#30514

Code that is causing this issue seems to be in Magento\Elasticsearch\Model\Adapter\BatchDataMapper\ProductDataMapper.php line 314:

`$attributeValues = [$productId => implode(' ', $attributeValues)];`

**Comment by Mecalux-Developer** [comment]
We have the same problem, with products from more than 400 children.

**Comment by engcom-Alfa** [comment]
I imported 480 configurable products and that implicitly generate 32640 simple products based on attributes configuration used.
Later, tried re indexing using elastic search 7.7 and I got an error as below:

_manjunath.ks@BLR1-LHP-N71760 MINGW64 /c/xampp/htdocs/magento2 (2.4-develop)
$ php bin/magento indexer:reindex
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:06
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Product EAV index process error during indexation process:
SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

Stock index process error during indexation process:
SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

Product Price index process error during indexation process:
SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search index process error during indexation process:
SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

PHP Fatal error:  Uncaught Exception: User Error: Some transactions have not been committed or rolled back in C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\DB\Ada
pter\Pdo\Mysql.php on line 4050 in C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\App\ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(256, 'Some transactio...', 'C:\\xampp\\htdocs...', 4050, Array)
#1 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(4050): trigger_error('Some transactio...', 256)
#2 [internal function]: Magento\Framework\DB\Adapter\Pdo\Mysql->__destruct()
#3 {main}
  thrown in C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\App\ErrorHandler.php on line 61

Fatal error: Uncaught Exception: User Error: Some transactions have not been committed or rolled back in C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\DB\Adapter\
Pdo\Mysql.php on line 4050 in C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\App\ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(256, 'Some transactio...', 'C:\\xampp\\htdocs...', 4050, Array)
#1 C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\DB\Adapter\Pdo\Mysql.php(4050): trigger_error('Some transactio...', 256)
#2 [internal function]: Magento\Framework\DB\Adapter\Pdo\Mysql->__destruct()
#3 {main}
  thrown in C:\xampp\htdocs\magento2\lib\internal\Magento\Framework\App\ErrorHandler.php on line 61

manjunath.ks@BLR1-LHP-N71760 MINGW64 /c/xampp/htdocs/magento2 (2.4-develop)_

**So, the issue is confirmed using elastic search 7.7.**

Note: Followed to the above steps, I retried using elastic search 7.12 and didn't reproduce with this elastic search latest version.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42444` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sabareesh-warlock** [comment]
@engcom-Alfa  @magento-engcom-team  @gabrieldagama  I am not getting any Error but iam having the more than 200 simple product under the some configurable product but it is not indexing in the ES. Iam working on Magento 2.4.2 and ElasticSearch 7.5.2

**Comment by sabareesh-warlock** [comment]
> We have the same problem, with products from more than 400 children.

@Mecalux-Developer  Did you find any solution for this problem

**Comment by freakpol** [comment]
Actually, solution proposed here https://github.com/magento/magento2/issues/30514 is doing well.
At least as a workaround until magento fixes the issue officially.

**Comment by hostep** [comment]
This is probably a duplicate of #30514, which now has a fix in core magento I believe: [ACP2E-3521: [CLOUD] Issue with Products are Not Visible in Frontend After Saving in Magento Admin](https://github.com/magento/magento2/commit/713f7c8d0fb670d15841302779e6c19fbe398638)
