### ISSUE TITLE
Provide full backtrace in exception log

### ISSUE THREAD

**Issue by onlinebizsoft** [magento/magento2#32751]
### Summary (*)

Since Magento 2.2.x and newer, Magento do not provide a full backtrace for exception. Refer to this ticket https://github.com/magento/magento2/issues/13128

### Examples (*)

The issue can be seen whenever an exception happen. I know with xdebug and a test case then developer can get a backtrace on their local environment but in fact, bugs are hard to replicate sometime and when it happens randomly on a production environment, a full backtrace is helpful

**Currently** all information we get for an exception as below
[2018-01-11 09:29:22] main.CRITICAL: Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "1986" already exists. {"exception":"[object] (Exception(code: 0): Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "1986" already exists. at /home/led/domain.com/vendor/magento/framework/Data/Collection.php:404)"} []
[2018-01-11 09:30:27] main.CRITICAL: Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "1986" already exists. {"exception":"[object] (Exception(code: 0): Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "1986" already exists. at /home/led/domain.com/vendor/magento/framework/Data/Collection.php:404)"} []
[2018-01-11 09:42:29] main.CRITICAL: Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "1986" already exists. {"exception":"[object] (Exception(code: 0): Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "1986" already exists. at /home/led/domain.com/vendor/magento/framework/Data/Collection.php:404)"} []

We **expected** something as below 
Exception #0 (Exception): Item (Magento/CatalogInventory/Model/Stock/Status/Interceptor) with the same ID "98" already exists.
#0 lib/internal/Magento/Framework/Data/AbstractSearchResult.php(233): Magento/Framework/Data/AbstractSearchResult->addItem(Object(Magento/CatalogInventory/Model/Stock/Status/Interceptor))
#1 lib/internal/Magento/Framework/Data/AbstractSearchResult.php(102): Magento/Framework/Data/AbstractSearchResult->load()
#2 app/code/Magento/CatalogInventoryConfigurableProduct/Plugin/GetInStockAttributeOptionsPlugin.php(62): Magento/Framework/Data/AbstractSearchResult->getItems()
#3 lib/internal/Magento/Framework/Interception/Interceptor.php(146): Magento/CatalogInventoryConfigurableProduct/Plugin/GetInStockAttributeOptionsPlugin->afterGetAttributeOptions(Object(Magento/ConfigurableProduct/Model/AttributeOptionProvider/Interceptor), Array, Object(Magento/Catalog/Model/ResourceModel/Eav/Attribute/Interceptor), '128')
..........
..............)

### Proposed solution

The issue were explained and proposed a solution here
https://github.com/magento/magento2/issues/13128#issuecomment-816591671
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by onlinebizsoft** [comment]
@MJTheOne @daiduongvo18 @hostep @lbajsarowicz

**Comment by lbajsarowicz** [comment]
I'm not sure what feedback you expect?

> developer can get a backtrace on their local environment

Actually, it's not true, something you've noticed in the logs but you have no idea why this class was called. To investigate the issue, you need information about who called it and how.

**Comment by onlinebizsoft** [comment]
> I'm not sure what feedback you expect?
> 
> > developer can get a backtrace on their local environment
> 
> Actually, it's not true, something you've noticed in the logs but you have no idea why this class was called. To investigate the issue, you need information about who called it and how.

I'm just tagging you here to follow up the new issue :) You know with xdebug and if you can replicate the issue locally then you can have backtrace information.

**Comment by onlinebizsoft** [comment]
@engcom-Echo will this be available for 2.4.3 please? :)

**Comment by onlinebizsoft** [comment]
Can you take a look at @mrtuvn @ihor-sviziev ?

**Comment by ihor-sviziev** [comment]
Hi @onlinebizsoft,
Could you provide more information on how to reproduce the issue, what is expected, and actual results? Some screenshots or logs would be beneficial.

**Comment by onlinebizsoft** [comment]
@ihor-sviziev I have edit the description to add more information

**Comment by ihor-sviziev** [comment]
@sidolov @gabrieldagama @sivaschenko, I think this should be a high priority, as missing the exception stack trace is a terrible thing for debugging issues on production.

PS: we have a custom logger that includes the exception stack trace. That's why I didn't notice it earlier.

**Comment by onlinebizsoft** [comment]
Since few years @ihor-sviziev @sidolov
