### ISSUE TITLE
Installation stops at 36% (Can't create directory)

### ISSUE THREAD

**Issue by rbaprado** [magento/magento2#3276]
I have gone thourgh http://devdocs.magento.com/guides/v2.0/install-gde/install-quick-ref.html and changed ownership and permissions accondingly, but I got this when installing:

```
Module 'Magento_Indexer':
[ERROR] Magento\Framework\Exception\LocalizedException: Can't create directory /home/buzz/Projetos/First Energy/site/var/generation/Magento/Store/Model/StoreManagerInterface/. in /home/buzz/Projetos/First Energy/site/vendor/magento/framework/Code/Generator.php:103
```

A few additional details:

```
[buzz@megazord site]$ egrep -i '^user|^group' /etc/httpd/conf/httpd.conf
User http
Group http
```

```
[buzz@megazord site]$ groups buzz
wheel http vboxusers wireshark buzz
[buzz@megazord site]$ groups http
buzz http
```

```
[buzz@megazord site]$ ls -l
total 860
drwxrwx---  4 buzz http   4096 Fev  3 15:44 app
drwxrwx---  2 buzz http   4096 Fev  3 15:44 bin
-rw-rw----  1 buzz http 437404 Fev  3 15:44 CHANGELOG.md
-rw-rw----  1 buzz http   1851 Jan 28 02:32 composer.json
-rw-rw----  1 buzz http 316041 Fev  3 15:44 composer.lock
-rw-rw----  1 buzz http   3425 Fev  3 15:44 CONTRIBUTING.md
-rw-rw----  1 buzz http  10011 Fev  3 15:44 CONTRIBUTOR_LICENSE_AGREEMENT.html
-rw-rw----  1 buzz http    631 Fev  3 15:44 COPYING.txt
drwxrwx---  4 buzz http   4096 Fev  3 15:44 dev
-rw-rw----  1 buzz http   2918 Fev  3 15:44 Gruntfile.js
-rw-rw----  1 buzz http   1358 Fev  3 15:44 index.php
drwxrwx---  4 buzz http   4096 Fev  3 15:44 lib
-rw-rw----  1 buzz http  10374 Fev  3 15:44 LICENSE_AFL.txt
-rw-rw----  1 buzz http  10364 Fev  3 15:44 LICENSE.txt
-rw-rw----  1 buzz http   4108 Fev  3 15:44 nginx.conf.sample
-rw-rw----  1 buzz http   1427 Fev  3 15:44 package.json
-rw-rw----  1 buzz http    804 Fev  3 15:44 php.ini.sample
drwxrwx---  2 buzz http   4096 Fev  3 15:44 phpserver
drwxrwx---  6 buzz http   4096 Fev  3 15:44 pub
-rw-rw----  1 buzz http   4388 Jan 28 02:32 README.md
drwxrwx---  7 buzz http   4096 Fev  3 15:44 setup
drwxrwx---  7 buzz http   4096 Fev  3 15:43 update
drwxrwx---  2 buzz http   4096 Fev  3 15:44 var
drwxrwx--- 27 buzz http   4096 Fev  3 15:44 vendor
```

I tried installing from both a download zip file and using composer. I also read in another issue about setting the sticky bit for var/generation but it does not exist prior to installation...

**Comment by mazhalai** [comment]
@rbaprado can you please show contents of var directory with permissions? Also, are you installing via web or CLI?

**Comment by rbaprado** [comment]
If you asked me 5 minutes ago I would be able to... I just managed to install by changing app/etc var/ and pub permissions as 777 prior to running setup.

But, answering your question, I was trying using the web setup. I guess 770 and 660 for those directories is not enough. Probably there is something that needs to be updated in the setup script or in the installation docs.

**Comment by rbaprado** [comment]
Bad news: after installation I could not run the backend:
`An error has happened during application run. See exception log for details.`

[exception.log.zip](https://github.com/magento/magento2/files/116160/exception.log.zip)

**Comment by rbaprado** [comment]
```
[buzz@megazord site]$ ls -l var/
total 28
drwxrwx---  2 buzz buzz 4096 Fev  3 16:19 backups
drwxrwx--- 19 http http 4096 Fev  3 16:22 cache
drwxrwxrwx  3 http http 4096 Fev  3 16:17 composer_home
drwxrwx---  5 http http 4096 Fev  3 16:19 generation
drwxrwx---  2 http http 4096 Fev  3 16:27 log
drwxrwx---  3 http http 4096 Fev  3 16:20 page_cache
drwxrwx---  2 http http 4096 Fev  3 16:24 session
```

**Comment by mazhalai** [comment]
@rbaprado are you installing EE? did you run `composer install`?

**Comment by rbaprado** [comment]
Nope, CE, and I ran `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition site`

**Comment by mazhalai** [comment]
Can you please check permissions of ALL folders within `var/generation`?

**Comment by rbaprado** [comment]
You got it.
[permissions.txt](https://github.com/magento/magento2/files/116186/permissions.txt)

**Comment by mazhalai** [comment]
Cannot reproduce it :( can you please give more details as to OS, magento version, php version, and server?

**Comment by rbaprado** [comment]
Sure:

```
[buzz@megazord ~]$ uname -a
Linux megazord 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux

[buzz@megazord ~]$ php --version
PHP 7.0.3 (cli) (built: Feb  2 2016 18:23:27) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

[buzz@megazord ~]$ apachectl -V
Server version: Apache/2.4.18 (Unix)
Server built:   Dec 14 2015 08:05:54
Server's Module Magic Number: 20120211:52
Server loaded:  APR 1.5.2, APR-UTIL 1.5.4
Compiled using: APR 1.5.2, APR-UTIL 1.5.4
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/usr/bin/suexec"
 -D DEFAULT_PIDLOG="/run/httpd/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"                                          
 -D DEFAULT_ERRORLOG="logs/error_log"                                                        
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"                                                   
 -D SERVER_CONFIG_FILE="conf/httpd.conf"
```

I am using the latest Magento version (2.0.2)

**Comment by mazhalai** [comment]
Please try on a supported OS of Ubuntu or Centos. It should be fine, but we haven't tested on other flavors of linux. Also, another suggestion is to try installing via [command line|http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-install.html].

**Comment by rbaprado** [comment]
I do not have any other distribution here to test, but will try using the command line. I'll keep you posted.

**Comment by rbaprado** [comment]
It just gets weirder... Today, with the exact some procedure, the installation hangs at 71%:

```
Installing data.. 
[ERROR] Magento\Framework\Exception\LocalizedException: Invalid entity_type specified: catalog_product in /home/buzz/Projetos/First Energy/site/vendor/magento/module-eav/Model/Config.php:348
Stack trace:
#0 /home/buzz/Projetos/First Energy/site/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(290): Magento\Eav\Model\Config->getEntityType('catalog_product')
#1 /home/buzz/Projetos/First Energy/site/var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(362): Magento\Eav\Model\Entity\AbstractEntity->setType('catalog_product')
#2 /home/buzz/Projetos/First Energy/site/vendor/magento/module-catalog/Model/ResourceModel/Product.php(114): Magento\Catalog\Model\ResourceModel\Product\Interceptor->setType('catalog_product')
#3 /home/buzz/Projetos/First Energy/site/var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(24): Magento\Catalog\Model\ResourceModel\Product->getEntityType()
#4 /home/buzz/Projetos/First Energy/site/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(772): Magento\Catalog\Model\ResourceModel\Product\Interceptor->getEntityType()
#5 /home/buzz/Projetos/First Energy/site/var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(557): Magento\Eav\Model\Entity\AbstractEntity->getEntityIdField()
#6 /home/buzz/Projetos/First Energy/site/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(1817): Magento\Catalog\Model\ResourceModel\Product\Interceptor->getEntityIdField()
#7 /home/buzz/Projetos/First Energy/site/var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(674): Magento\Eav\Model\Entity\AbstractEntity->getDefaultAttributes()
#8 /home/buzz/Projetos/First Energy/site/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php(195): Magento\Catalog\Model\ResourceModel\Product\Interceptor->getDefaultAttributes()
#9 /home/buzz/Projetos/First Energy/site/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php(486): Magento\Eav\Model\Entity\Collection\AbstractCollection->_prepareStaticFields()
#10 /home/buzz/Projetos/First Energy/site/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php(163): Magento\Catalog\Model\ResourceModel\Product\Collection->_prepareStaticFields()
#11 /home/buzz/Projetos/First Energy/site/vendor/magento/module-catalog/Model/ResourceModel/Collection/AbstractCollection.php(60): Magento\Eav\Model\Entity\Collection\AbstractCollection->__construct(Object(Magento\Framework\Data\Collection\EntityFactory), Object(Magento\Framework\Logger\Monolog), Object(Magento\Framework\Data\Collection\Db\FetchStrategy\Query), Object(Magento\Framework\Event\Manager\Proxy), Object(Magento\Eav\Model\Config), Object(Magento\Framework\App\ResourceConnection), Object(Magento\Eav\Model\EntityFactory), Object(Magento\Catalog\Model\ResourceModel\Helper), Object(Magento\Framework\Validator\UniversalFactory), NULL)
#12 /home/buzz/Projetos/First Energy/site/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php(312): Magento\Catalog\Model\ResourceModel\Collection\AbstractCollection->__construct(Object(Magento\Framework\Data\Collection\EntityFactory), Object(Magento\Framework\Logger\Monolog), Object(Magento\Framework\Data\Collection\Db\FetchStrategy\Query), Object(Magento\Framework\Event\Manager\Proxy), Object(Magento\Eav\Model\Config), Object(Magento\Framework\App\ResourceConnection), Object(Magento\Eav\Model\EntityFactory), Object(Magento\Catalog\Model\ResourceModel\Helper), Object(Magento\Framework\Validator\UniversalFactory), Object(Magento\Store\Model\StoreManager), NULL)
#13 [internal function]: Magento\Catalog\Model\ResourceModel\Product\Collection->__construct(Object(Magento\Framework\Data\Collection\EntityFactory), Object(Magento\Framework\Logger\Monolog), Object(Magento\Framework\Data\Collection\Db\FetchStrategy\Query), Object(Magento\Framework\Event\Manager\Proxy), Object(Magento\Eav\Model\Config), Object(Magento\Framework\App\ResourceConnection), Object(Magento\Eav\Model\EntityFactory), Object(Magento\Catalog\Model\ResourceModel\Helper), Object(Magento\Framework\Validator\UniversalFactory), Object(Magento\Store\Model\StoreManager), Object(Magento\Framework\Module\Manager), Object(Magento\Catalog\Model\Indexer\Product\Flat\State), Object(Magento\Framework\App\Config), Object(Magento\Catalog\Model\Product\OptionFactory), Object(Magento\Catalog\Model\ResourceModel\Url\Proxy), Object(Magento\Framework\Stdlib\DateTime\Timezone), Object(Magento\Customer\Model\Session\Proxy), Object(Magento\Framework\Stdlib\DateTime), Object(Magento\Customer\Model\GroupManagement), NULL)
#14 /home/buzz/Projetos/First Energy/site/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(202): ReflectionClass->newInstanceArgs(Array)
#15 /home/buzz/Projetos/First Energy/site/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Catalog...', Array)
#16 /home/buzz/Projetos/First Energy/site/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...', Array)
#17 /home/buzz/Projetos/First Energy/site/var/generation/Magento/Catalog/Model/ResourceModel/Product/CollectionFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Catalog...', Array)
#18 /home/buzz/Projetos/First Energy/site/vendor/magento/module-catalog/Model/Category.php(465): Magento\Catalog\Model\ResourceModel\Product\CollectionFactory->create()
#19 /home/buzz/Projetos/First Energy/site/var/generation/Magento/Catalog/Model/Category/Interceptor.php(102): Magento\Catalog\Model\Category->getProductCollection()
#20 /home/buzz/Projetos/First Energy/site/vendor/magento/module-catalog-url-rewrite/Observer/UrlRewriteHandler.php(105): Magento\Catalog\Model\Category\Interceptor->getProductCollection()
#21 /home/buzz/Projetos/First Energy/site/vendor/magento/module-catalog-url-rewrite/Observer/UrlRewriteHandler.php(84): Magento\CatalogUrlRewrite\Observer\UrlRewriteHandler->getCategoryProductsUrlRewrites(Object(Magento\Catalog\Model\Category\Interceptor), 0, NULL)
#22 /home/buzz/Projetos/First Energy/site/vendor/magento/module-catalog-url-rewrite/Observer/CategoryProcessUrlRewriteSavingObserver.php(55): Magento\CatalogUrlRewrite\Observer\UrlRewriteHandler->generateProductUrlRewrites(Object(Magento\Catalog\Model\Category\Interceptor))
#23 /home/buzz/Projetos/First Energy/site/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Magento\CatalogUrlRewrite\Observer\CategoryProcessUrlRewriteSavingObserver->execute(Object(Magento\Framework\Event\Observer))
#24 /home/buzz/Projetos/First Energy/site/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\CatalogUrlRewrite\Observer\CategoryProcessUrlRewriteSavingObserver), Object(Magento\Framework\Event\Observer))
#25 /home/buzz/Projetos/First Energy/site/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#26 /home/buzz/Projetos/First Energy/site/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('catalog_categor...', Array)
#27 /home/buzz/Projetos/First Energy/site/vendor/magento/framework/Model/AbstractModel.php(786): Magento\Framework\Event\Manager\Proxy->dispatch('catalog_categor...', Array)
#28 /home/buzz/Projetos/First Energy/site/vendor/magento/module-catalog/Model/Category.php(1071): Magento\Framework\Model\AbstractModel->afterSave()
#29 /home/buzz/Projetos/First Energy/site/var/generation/Magento/Catalog/Model/Category/Interceptor.php(583): Magento\Catalog\Model\Category->afterSave()
#30 /home/buzz/Projetos/First Energy/site/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(1154): Magento\Catalog\Model\Category\Interceptor->afterSave()
#31 /home/buzz/Projetos/First Energy/site/var/generation/Magento/Catalog/Model/ResourceModel/Category/Interceptor.php(739): Magento\Eav\Model\Entity\AbstractEntity->save(Object(Magento\Catalog\Model\Category\Interceptor))
#32 /home/buzz/Projetos/First Energy/site/vendor/magento/framework/Model/AbstractModel.php(615): Magento\Catalog\Model\ResourceModel\Category\Interceptor->save(Object(Magento\Catalog\Model\Category\Interceptor))
#33 /home/buzz/Projetos/First Energy/site/var/generation/Magento/Catalog/Model/Category/Interceptor.php(1532): Magento\Framework\Model\AbstractModel->save()
#34 /home/buzz/Projetos/First Energy/site/vendor/magento/module-catalog/Setup/InstallData.php(58): Magento\Catalog\Model\Category\Interceptor->save()
#35 /home/buzz/Projetos/First Energy/site/setup/src/Magento/Setup/Model/Installer.php(798): Magento\Catalog\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext))
#36 /home/buzz/Projetos/First Energy/site/setup/src/Magento/Setup/Model/Installer.php(746): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data')
#37 [internal function]: Magento\Setup\Model\Installer->installDataFixtures()
#38 /home/buzz/Projetos/First Energy/site/setup/src/Magento/Setup/Model/Installer.php(331): call_user_func_array(Array, Array)
#39 /home/buzz/Projetos/First Energy/site/setup/src/Magento/Setup/Controller/Install.php(97): Magento\Setup\Model\Installer->install(Array)
#40 /home/buzz/Projetos/First Energy/site/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#41 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#42 /home/buzz/Projetos/First Energy/site/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#43 /home/buzz/Projetos/First Energy/site/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#44 /home/buzz/Projetos/First Energy/site/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#45 /home/buzz/Projetos/First Energy/site/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#46 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#47 /home/buzz/Projetos/First Energy/site/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#48 /home/buzz/Projetos/First Energy/site/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#49 /home/buzz/Projetos/First Energy/site/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#50 /home/buzz/Projetos/First Energy/site/setup/index.php(31): Zend\Mvc\Application->run()
#51 {main}
```

**Comment by ghost** [comment]
I'm jumping into a thread without having read all of it but have you set your PHP `memory_limit` to at least 768M? Take a look at these [recommended settings](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/php-ubuntu.html#instgde-prereq-timezone) and see if they help.

Also, between installations either delete your entire Magento 2 directory or at least the contents of directories under `var`.

**Comment by rbaprado** [comment]
Changing the memory limit did the trick as it seems. The installation went smoothly. Thank you all.
