### ISSUE TITLE
TypeError: Argument 1 passed to Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute() must be of the type string, null given Magento 2.4.2

### ISSUE THREAD

**Issue by ss-sabareesh** [magento/magento2#33273]
### Preconditions (*)

1.  Magento 2.4.2
2.  PHP 7.4
3. MySQL 8.0

### Steps to reproduce (*)

1. When i try to search the product iam getting this issue in the response at network.
2. The keyword i searched for **Mounting rail** 

### Expected result (*)

1. If there is no such product need to show the result as no data found or any other error but if it comes can't search in the page again, need to go to **ui_bookmarks** and remove the **product_listing** config value. if there is no data return need not show this must show the no data found.

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/68388960/122407873-91ee5f00-cf9f-11eb-9bee-024aea2df576.png)

**Request URL:** http://mydomain/admin_1fhn34/mui/index/render/?namespace=product_listing&paging%5BpageSize%5D=20&paging%5Bcurrent%5D=1&filters%5Bplaceholder%5D=true&search=Mounting+rail&sorting%5Bfield%5D=entity_id&sorting%5Bdirection%5D=asc&isAjax=true

**Response:**
```
TypeError: Argument 1 passed to Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute() must be of the type string, null given, called in /var/www/html/vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php on line 108 and defined in /var/www/html/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php:20
Stack trace:
#0 /var/www/html/vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php(108): Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor->execute()
#1 /var/www/html/vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php(75): Magento\InventorySales\Model\GetProductSalableQty->validateProductType()
#2 /var/www/html/vendor/magento/module-inventory-sales-admin-ui/Model/GetSalableQuantityDataBySku.php(74): Magento\InventorySales\Model\GetProductSalableQty->execute()
#3 /var/www/html/vendor/magento/module-inventory-sales-admin-ui/Ui/Component/Listing/Column/SalableQuantity.php(70): Magento\InventorySalesAdminUi\Model\GetSalableQuantityDataBySku->execute()
#4 /var/www/html/vendor/magento/framework/View/Element/UiComponent/Context.php(397): Magento\InventorySalesAdminUi\Ui\Component\Listing\Column\SalableQuantity->prepareDataSource()
#5 /var/www/html/vendor/magento/framework/View/Element/UiComponent/Context.php(394): Magento\Framework\View\Element\UiComponent\Context->prepareDataSource()
#6 /var/www/html/vendor/magento/framework/View/Element/UiComponent/Context.php(394): Magento\Framework\View\Element\UiComponent\Context->prepareDataSource()
#7 /var/www/html/vendor/magento/framework/View/Element/UiComponent/Context.php(255): Magento\Framework\View\Element\UiComponent\Context->prepareDataSource()
#8 /var/www/html/vendor/magento/framework/View/Element/UiComponent/ContentType/Json.php(69): Magento\Framework\View\Element\UiComponent\Context->getDataSourceData()
#9 /var/www/html/vendor/magento/module-ui/Component/AbstractComponent.php(158): Magento\Framework\View\Element\UiComponent\ContentType\Json->render()
#10 /var/www/html/vendor/magento/module-ui/Controller/Adminhtml/Index/Render.php(91): Magento\Ui\Component\AbstractComponent->render()
#11 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Ui\Controller\Adminhtml\Index\Render->execute()
#12 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callParent()
#13 /var/www/html/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}()
#14 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute()
#15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}()
#16 /var/www/html/generated/code/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(23): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callPlugins()
#17 /var/www/html/vendor/magento/framework/App/Action/Action.php(111): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->execute()
#18 /var/www/html/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#19 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#20 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callParent()
#21 /var/www/html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}()
#22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}()
#24 /var/www/html/generated/code/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(32): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callPlugins()
#25 /var/www/html/vendor/magento/framework/App/FrontController.php(186): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->dispatch()
#26 /var/www/html/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest()
#27 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#28 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#29 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#30 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#31 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#32 /var/www/html/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http->launch()
#33 /var/www/html/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#34 {main}
```

**Comment by sabareesh-warlock** [comment]
@engcom-Dash  Did we got any update on this issue.

**Comment by sabareesh-warlock** [comment]
@engcom-Dash  still i can't fix this issue can i get any suggestion

**Comment by engcom-Lima** [comment]
Hi @sabareesh-warlock,

We tried to reproduce this issue but we are getting "We couldn't find any records." and not same error as you are getting.

Attached screenshot of the same:
<img width="1440" alt="Product Screen" src="https://user-images.githubusercontent.com/60198022/130222159-c9ebe57e-8dac-416c-b70b-d3d4edea37e1.png">

Please update if this issue is resolved ? Or advise if you did anything differently ?

**Comment by engcom-Lima** [comment]
Closing this issue as there is no update from the reporter for more than 17 days now.
