### ISSUE TITLE
strpos() expects parameter 1 to be string, array given | magento/module-eav

### ISSUE THREAD

**Issue by Morgy93** [magento/magento2#33588]
### Preconditions (*)

- Magento 2.4.2
- PHP 7.4

### Steps to reproduce (*)

1. Add any dropdown attribute to advanced search (Admin: Stores -> Attributes -> Product - > Add New Attribute /Choose existing attribute ex: color
Input Type should be: Dropdown
Storefront Properties: Use in Search: Yes, Visible in Advanced Search: Yes)
2. Front-end - Go to `/catalogsearch/advanced/result/?color%5B%5D=49,50` (Used color Attribute)

**Issue:** "There has been an error processing your request" Error message is getting displayed
**Note**: There is no issue with Text Attribute. URL is working for Text attribute. Issue is observed for dropdown attribute.
This seems to be reported in #25438 but said to be fixed and closed, so I open up another one.

### Expected result (*)

It should not throw an unhandled error.
![image](https://user-images.githubusercontent.com/60198231/130946302-8a0ecc14-6b5b-485a-bba9-9bc3455ce9cb.png)

### Actual result (*)

There has been an error processing your request Error message is getting displayed on UI
![image](https://user-images.githubusercontent.com/60198231/130946247-832ba68d-455a-4b82-93d1-866f3cc163b2.png)

```

Exception #0 (Exception): 

[2021-10-07T06:43:05.660813+00:00] main.CRITICAL: Exception: Notice: Undefined index: label in /var/www/html/mg24/magento2/app/code/Magento/CatalogSearch/Model/Advanced.php on line 420 in /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:61
Stack trace:
#0 /var/www/html/mg24/magento2/app/code/Magento/CatalogSearch/Model/Advanced.php(420): Magento\Framework\App\ErrorHandler->handler()
#1 /var/www/html/mg24/magento2/app/code/Magento/CatalogSearch/Model/Advanced.php(206): Magento\CatalogSearch\Model\Advanced->getPreparedSearchCriteria()
#2 /var/www/html/mg24/magento2/app/code/Magento/CatalogSearch/Controller/Advanced/Result.php(62): Magento\CatalogSearch\Model\Advanced->addFilters()
#3 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\CatalogSearch\Controller\Advanced\Result->execute()
#4 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callParent()
#5 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}()
#6 /var/www/html/mg24/magento2/generated/code/Magento/CatalogSearch/Controller/Advanced/Result/Interceptor.php(23): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callPlugins()
#7 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Action/Action.php(111): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->execute()
#8 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#9 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callParent()
#10 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}()
#11 /var/www/html/mg24/magento2/generated/code/Magento/CatalogSearch/Controller/Advanced/Result/Interceptor.php(32): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callPlugins()
#12 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/FrontController.php(245): Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->dispatch()
#13 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#14 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#15 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#16 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#17 /var/www/html/mg24/magento2/app/code/Magento/Store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#18 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#19 /var/www/html/mg24/magento2/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#20 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#21 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#22 /var/www/html/mg24/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#23 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#24 /var/www/html/mg24/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#25 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#26 /var/www/html/mg24/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#27 {main} {"report_id":"a4896b6ef63c77f8d3ed38c58ef08f57836f8cf479917c986425a700daebd851"} []
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Morgy93** [comment]
@magento give me 2.4-develop instance

**Comment by Morgy93** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Steps to reproduce:
1. Admin: Stores -> Attributes -> Product
2. Choose color attribute
3. Storefront Properties: 
3.1. Use in Search: Yes
3.2. Visible in Advanced Search: Yes
4. Go to `/catalogsearch/advanced/result/?color[][error]=1` (e.g. https://375bf3eb74a91732b9990b21f37518e9-2-4-develop.instances.magento-community.engineering/catalogsearch/advanced/result/?color[][error]=1)
5. See error
![image](https://user-images.githubusercontent.com/7961978/126967467-1b62636d-1908-47a6-b45e-1d26f91f25ec.png)

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
**Steps to reproduce:**
1. Admin: Stores -> Attributes -> Product - > Add New Attribute /Choose existing attribute ex: color
Input Type should be: Dropdown
Storefront Properties: Use in Search: Yes, Visible in Advanced Search: Yes
2. Front-end - Go to http://yourmagentostore.com/catalogsearch/advanced/result/?attributename[][error]=1 
Ex: https://magento2.4.local/catalogsearch/advanced/result/?test_data[][error]=1 
**Issue: There has been an error processing your request Error message is getting displayed
Note: There is no issue with Text Attribute. URL is working for Text attribute. Issue is observed for dropdown attribute.**
![image](https://user-images.githubusercontent.com/60198231/127451913-8e3c85dc-f741-4c10-a52b-8da91011cdf1.png)

![image](https://user-images.githubusercontent.com/60198231/127451969-d1d47fb4-e190-40e0-bbeb-1fa3319c14c5.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42933` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by SilinMykola** [comment]
@magento I am working on this

**Comment by engcom-Hotel** [comment]
Hello @Morgy93,

It seems that this issue is a duplicate of the [issue](https://github.com/magento/magento2/issues/33589). So we are closing this ticket.

Duplicate #33589 

Thanks

**Comment by Morgy93** [comment]
Same "rant" like here https://github.com/magento/magento2/issues/33586#issuecomment-932714311
Let me just copy my comment, sadly it's the same story here.

-----

Still reproducible on latest 2.4-develop, but #33589 got closed as fixed.

So it CANNOT be a duplicate! Like @engcom-Hotel stated here https://github.com/magento/magento2/issues/33588#issuecomment-891795773
The code is unchanged, I checked. Please reopen this issue!

How is it possible to get a little reaction from someone from the Magento staff since 3 Aug?
Do I need to ping all of them? Cannot be the solution. Still I don't know another way. Please don't be mad.
@magento-engcom-team @engcom-Alfa @engcom-Bravo @engcom-Charlie @engcom-Dash @engcom-Delta @magento-team

@ihor-sviziev I had positive experience with you in the past, maybe you can help 🙏

**Comment by ihor-sviziev** [comment]
@Morgy93 can you reproduce the issue on the test instance?

**Comment by Morgy93** [comment]
@ihor-klymchuk Yes, that is right in the first sentence of the second block.
I used the Magento instance that I ordered here https://github.com/magento/magento2/issues/33586#issuecomment-932712301

**Comment by ihor-sviziev** [comment]
@engcom-Alfa, 
could you double-check if the issue still reproducing?

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch but the issue is not reproducible:
Configured Color Attribute as per below. But there is no exception observed when used URL: /catalogsearch/advanced/result/?color[][error]=1
![image](https://user-images.githubusercontent.com/60198231/135852229-41bc326a-4818-4945-83fb-13b37afba6f5.png)
![image](https://user-images.githubusercontent.com/60198231/135852698-db90d73d-2fa6-4dec-b9e9-701d36e187df.png)

@Morgy93 , can you please recheck on the latest pull of Magento 2.4-develop.
Thank you.

**Comment by Morgy93** [comment]
@magento give me 2.4-develop instance

**Comment by Morgy93** [comment]
@engcom-November 

![image](https://user-images.githubusercontent.com/7961978/135858324-02ac57f7-6380-449f-98c6-ca34fafb2acf.png)

Any chance to see what the error is on the demo instances?

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Adding labels again to create a JIRA ticket

**Comment by engcom-Delta** [comment]
Hi @Morgy93 ,

Thanks for your reporting and collaboration.
We have re-verified the issue in latest 2.4-develop instance and the issue is reproducible.
Kindly refer the screenshots.

**Steps to reproduce**
1. Add any dropdown attribute to advanced search (Admin: Stores -> Attributes -> Product - > Add New Attribute /Choose existing attribute ex: color
Input Type should be: Dropdown
Storefront Properties: Use in Search: Yes, Visible in Advanced Search: Yes)
2. Front-end - Go to /catalogsearch/advanced/result/?color%5B%5D=49,50 (Used color Attribute)
3. Issue -  "There has been an error processing your request" Error message is getting displayed
![image](https://github.com/user-attachments/assets/c15b32af-73a5-4e86-b0e4-b2c7d2d467dd)

Thanks.
