### ISSUE TITLE
[Magento 2.0.2] Custom theme not showing in admin

### ISSUE THREAD

**Issue by matthieusibille** [magento/magento2#3408]
Hello,
I was working previously on Magento 2.0.0 and I successfully installed a custom theme by following the Magento doc.
Because of the upgrade bugs I had to do a fresh install of magento 2.0.2. But now I can't install my custom theme. I just copied all the files I had on app/design/frontend/Linescort/beret-theme but the theme is not showing on the admin panel.
My structure is like so :

```
app/design/frontend/Linescort/beret-theme
-------- etc
------------- view.xml
-------- i18n
-------- media
-------- web
-------- registration.php
-------- theme.xml
```

**theme.xml**

```
<theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/theme.xsd">
    <title>Thème Béret Français</title> <!-- your theme's name -->
    <parent>Magento/blank</parent> <!-- the parent theme, in case your theme inherits from an existing theme -->

</theme>
```

**registraton.php**

```
<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::THEME,
    'frontend/Linescort/beret-theme',
    __DIR__
);
?>
```

I don't have a composer.json, I didn't need one with Magento 2.0.0 and even with one, it doesn't work anyway.
Permissions on the folder /Linescort are 755
I empied the cache, re-deploy but nothing worked.

Is this a bug or did i forget something?

Thank you for your help
Regards

**Comment by quienti** [comment]
Have you try `bin/magento setup:upgrade` ?

**Comment by matthieusibille** [comment]
I just did and it didn't fix the issue unfortunately.
edit : Do i need to re-run the compile command too?

**Comment by quienti** [comment]
I have never used this command and I have my custom theme so...
Did you check if you had anything in our log ?

**Comment by matthieusibille** [comment]
When i refresh the Theme admin panel I have this in my system.log :

`[2016-02-15 14:09:59] main.CRITICAL: No such entity. [] []`

And in my exception.log

```
[2016-02-15 14:09:59] main.CRITICAL: exception 'Magento\Framework\Exception\NoSuchEntityException' with message 'No such entity.' in /home/www/leberetfrancais2/vendor/magento/module-store/Model/WebsiteRepository.php:85
Stack trace:
#0 /home/www/leberetfrancais2/vendor/magento/module-store/Model/Store.php(542): Magento\Store\Model\WebsiteRepository->getById('2')
#1 /home/www/leberetfrancais2/var/generation/Magento/Store/Model/Store/Interceptor.php(115): Magento\Store\Model\Store->getWebsite()
#2 /home/www/leberetfrancais2/vendor/magento/module-store/Model/Config/Reader/Store.php(71): Magento\Store\Model\Store\Interceptor->getWebsite()
#3 /home/www/leberetfrancais2/vendor/magento/framework/App/Config/ScopePool.php(86): Magento\Store\Model\Config\Reader\Store->read('beret')
#4 /home/www/leberetfrancais2/vendor/magento/framework/App/Config.php(45): Magento\Framework\App\Config\ScopePool->getScope('store', Object(Magento\Store\Model\Store\Interceptor))
#5 /home/www/leberetfrancais2/vendor/magento/module-theme/Model/View/Design.php(182): Magento\Framework\App\Config->getValue('design/theme/th...', 'store', Object(Magento\Store\Model\Store\Interceptor))
#6 /home/www/leberetfrancais2/var/generation/Magento/Theme/Model/View/Design/Proxy.php(119): Magento\Theme\Model\View\Design->getConfigurationDesignTheme('frontend', Array)
#7 /home/www/leberetfrancais2/vendor/magento/module-theme/Model/Config/Customization.php(156): Magento\Theme\Model\View\Design\Proxy->getConfigurationDesignTheme('frontend', Array)
#8 /home/www/leberetfrancais2/vendor/magento/module-theme/Model/Config/Customization.php(98): Magento\Theme\Model\Config\Customization->_getConfigurationThemeId(Object(Magento\Store\Model\Store\Interceptor))
#9 /home/www/leberetfrancais2/vendor/magento/module-theme/Model/Config/Customization.php(173): Magento\Theme\Model\Config\Customization->getStoresByThemes()
#10 /home/www/leberetfrancais2/vendor/magento/module-theme/Model/Config/Customization.php(68): Magento\Theme\Model\Config\Customization->_prepareThemeCustomizations()
#11 /home/www/leberetfrancais2/vendor/magento/module-theme/Model/Config/Customization.php(117): Magento\Theme\Model\Config\Customization->getAssignedThemeCustomizations()
#12 /home/www/leberetfrancais2/vendor/magento/module-theme/Observer/CheckThemeIsAssignedObserver.php(48): Magento\Theme\Model\Config\Customization->isThemeAssignedToStore(Object(Magento\Theme\Model\Theme\Data))
#13 /home/www/leberetfrancais2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Magento\Theme\Observer\CheckThemeIsAssignedObserver->execute(Object(Magento\Framework\Event\Observer))
#14 /home/www/leberetfrancais2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Theme\Observer\CheckThemeIsAssignedObserver), Object(Magento\Framework\Event\Observer))
#15 /home/www/leberetfrancais2/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#16 /home/www/leberetfrancais2/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('theme_save_afte...', Array)
#17 /home/www/leberetfrancais2/vendor/magento/framework/Model/AbstractModel.php(786): Magento\Framework\Event\Manager\Proxy->dispatch('theme_save_afte...', Array)
#18 /home/www/leberetfrancais2/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(829): Magento\Framework\Model\AbstractModel->afterSave()
#19 /home/www/leberetfrancais2/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(408): Magento\Framework\Model\ResourceModel\Db\AbstractDb->processAfterSaves(Object(Magento\Theme\Model\Theme\Data))
#20 /home/www/leberetfrancais2/vendor/magento/framework/Model/AbstractModel.php(615): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Magento\Theme\Model\Theme\Data))
#21 /home/www/leberetfrancais2/vendor/magento/module-theme/Model/Theme/Registration.php(113): Magento\Framework\Model\AbstractModel->save()
#22 /home/www/leberetfrancais2/vendor/magento/module-theme/Model/Theme/Registration.php(72): Magento\Theme\Model\Theme\Registration->_registerThemeRecursively(Object(Magento\Theme\Model\Theme\Data))
#23 /home/www/leberetfrancais2/vendor/magento/module-theme/Model/Theme/Plugin/Registration.php(56): Magento\Theme\Model\Theme\Registration->register()
#24 [internal function]: Magento\Theme\Model\Theme\Plugin\Registration->beforeDispatch(Object(Magento\Theme\Controller\Adminhtml\System\Design\Theme\Index\Interceptor), Object(Magento\Framework\App\Request\Http))
#25 /home/www/leberetfrancais2/vendor/magento/framework/Interception/Interceptor.php(122): call_user_func_array(Array, Array)
#26 /home/www/leberetfrancais2/var/generation/Magento/Theme/Controller/Adminhtml/System/Design/Theme/Index/Interceptor.php(40): Magento\Theme\Controller\Adminhtml\System\Design\Theme\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#27 /home/www/leberetfrancais2/vendor/magento/framework/App/FrontController.php(55): Magento\Theme\Controller\Adminhtml\System\Design\Theme\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#28 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#29 /home/www/leberetfrancais2/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#30 /home/www/leberetfrancais2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#31 /home/www/leberetfrancais2/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#32 /home/www/leberetfrancais2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#33 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34 /home/www/leberetfrancais2/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#35 /home/www/leberetfrancais2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /home/www/leberetfrancais2/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /home/www/leberetfrancais2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#38 /home/www/leberetfrancais2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#39 {main} [] []
```

**Comment by matthieusibille** [comment]
line #24 may be the issue here but I have no idea what to do to fix it

**Comment by mrkhoa99** [comment]
Hi,
You try to remove hyphen of the theme name: `beret-theme` => `berettheme`

**Comment by matthieusibille** [comment]
I just tried, still the same issue

**Comment by quienti** [comment]
You have upgrade your Magento 2.0.0 to 2.0.2 ?

**Comment by matthieusibille** [comment]
No, i tried to upgrade but there were many bugs so it couldn't be done with the Setup Wizard in the admin. Instead I did a fresh install of Magento 2.0.2.

**Comment by quienti** [comment]
Hummm

I don't know right now...
I have a custom theme on Magento 2.0.2, I had a problem when I upgraged Magento 2.0.0 to 2.0.2, but I have seen never this error.

**Comment by matthieusibille** [comment]
How did you upgrade? I couldn't do it with the web wizard, nor with composer.

**Comment by quienti** [comment]
Oh my God!
I do not remember exactly, but I have spent many hours to find a solution.

**Comment by matthieusibille** [comment]
Can i just copy /Vendor and it will upgrade magento to 2.0.2? I did it on localhost and it did the trick but i'm not sure that the right way to do it and if i can expect issues.
In the magento doc it says that you can upgrade by replacing the "magento code base" of a 2.0.0 by one of a 2.0.2 install, but is it just /vendor? Or are there more files to replace as well?

**Comment by matthieusibille** [comment]
I managed to find a workaround. I upgraded my previous 2.0.0 install with the vendor folder of a 2.0.2 install, did a setup:upgrade and composer update and it worked.
It's a shame that magento doc is vague about this way to upgrade, " replace magento code base" is not a proper way to explain how to proceed for new users. They should be more specific.

**Comment by SyedMuneebb** [comment]
You also need to run some commands to upgrade the setup, to flush the cache etc. Here's a guide that can help you: [Custom Theme Magento 2](https://magenticians.com/create-custom-theme-magento-2/)
