### ISSUE TITLE
[Static tests] Phpstan fails on checking CLI command

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#34881]
I found this issue during working on https://github.com/magento/magento2/pull/34817#issuecomment-995544761 - there was a static test failure from phpstan (that's not related to changes in that PR)

### Steps to reproduce (*)

1. Check out the 2.4-develop branch (tested on the following commit https://github.com/magento/magento2/commit/d0dccd89217f4c2021271e2a4cd71b698177fea4) 
2. Run `composer install`
2. Try to run the following command:
```bash
./vendor/bin/phpstan.phar analyze --configuration=./dev/tests/static/testsuite/Magento/Test/Php/_files/phpstan/phpstan.neon --level 1 app/code/Magento/SampleData/Console/Command/SampleDataRemoveCommand.php  --debug
```

### Expected result (*)

1. We should have some information if the class has passed the static test check
2. There be any internal errors

### Actual result (*)

1. We have an internal error:
![image](https://user-images.githubusercontent.com/1873745/147333607-2cedaa10-2a4e-4847-aad5-79b168d8bd2a.png)
the output with the `--debug` flag is following:
```
@ihor-sviziev ➜ /workspaces/magento2 (2.4-develop) $ vendor/bin/phpstan.phar analyze --configuration=./dev/tests/static/testsuite/Magento/Test/Php/_files/phpstan/phpstan.neon --level 1 app/code/Magento/SampleData/Console/Command/SampleDataRemoveCommand.php  --debug
/workspaces/magento2/app/code/Magento/SampleData/Console/Command/SampleDataRemoveCommand.php
Uncaught Error: Class "Magento\Framework\Code\Generator\ClassGenerator" not found in /workspaces/magento2/lib/internal/Magento/Framework/TestFramework/Unit/Autoloader/FactoryGenerator.php:32
#0 /workspaces/magento2/lib/internal/Magento/Framework/TestFramework/Unit/Autoloader/GeneratedClassesAutoloader.php(61): Magento\Framework\TestFramework\Unit\Autoloader\FactoryGenerator->generate('Composer\\Consol...')
#1 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/SourceLocator/AutoloadSourceLocator.php(221): Magento\Framework\TestFramework\Unit\Autoloader\GeneratedClassesAutoloader->load('Composer\\Consol...')
#2 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/SourceLocator/FileReadTrapStreamWrapper.php(50): PHPStan\Reflection\BetterReflection\SourceLocator\AutoloadSourceLocator::PHPStan\Reflection\BetterReflection\SourceLocator\{closure}()
#3 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/SourceLocator/AutoloadSourceLocator.php(233): PHPStan\Reflection\BetterReflection\SourceLocator\FileReadTrapStreamWrapper::withStreamWrapperOverride(Object(Closure))
#4 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/SourceLocator/AutoloadSourceLocator.php(116): PHPStan\Reflection\BetterReflection\SourceLocator\AutoloadSourceLocator->locateClassByName('Composer\\Consol...')
#5 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/SourceLocator/ClassWhitelistSourceLocator.php(32): PHPStan\Reflection\BetterReflection\SourceLocator\AutoloadSourceLocator->locateIdentifier(Object(PHPStan\Reflection\BetterReflection\Reflector\MemoizingClassReflector), Object(PHPStan\BetterReflection\Identifier\Identifier))
#6 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLocator.php(31): PHPStan\Reflection\BetterReflection\SourceLocator\ClassWhitelistSourceLocator->locateIdentifier(Object(PHPStan\Reflection\BetterReflection\Reflector\MemoizingClassReflector), Object(PHPStan\BetterReflection\Identifier\Identifier))
#7 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/MemoizingSourceLocator.php(31): PHPStan\BetterReflection\SourceLocator\Type\AggregateSourceLocator->locateIdentifier(Object(PHPStan\Reflection\BetterReflection\Reflector\MemoizingClassReflector), Object(PHPStan\BetterReflection\Identifier\Identifier))
#8 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/ClassReflector.php(39): PHPStan\BetterReflection\SourceLocator\Type\MemoizingSourceLocator->locateIdentifier(Object(PHPStan\Reflection\BetterReflection\Reflector\MemoizingClassReflector), Object(PHPStan\BetterReflection\Identifier\Identifier))
#9 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/Reflector/MemoizingClassReflector.php(25): PHPStan\BetterReflection\Reflector\ClassReflector->reflect('Composer\\Consol...')
#10 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/BetterReflectionProvider.php(111): PHPStan\Reflection\BetterReflection\Reflector\MemoizingClassReflector->reflect('Composer\\Consol...')
#11 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/ChainReflectionProvider.php(25): PHPStan\Reflection\BetterReflection\BetterReflectionProvider->hasClass('Composer\\Consol...')
#12 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/MemoizingReflectionProvider.php(31): PHPStan\Reflection\ReflectionProvider\ChainReflectionProvider->hasClass('Composer\\Consol...')
#13 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Rules/ClassCaseSensitivityCheck.php(28): PHPStan\Reflection\ReflectionProvider\MemoizingReflectionProvider->hasClass('Composer\\Consol...')
#14 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Namespaces/ExistingNamesInUseRule.php(96): PHPStan\Rules\ClassCaseSensitivityCheck->checkClassNames(Array)
#15 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Namespaces/ExistingNamesInUseRule.php(50): PHPStan\Rules\Namespaces\ExistingNamesInUseRule->checkClasses(Array)
#16 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(77): PHPStan\Rules\Namespaces\ExistingNamesInUseRule->processNode(Object(PhpParser\Node\Stmt\Use_), Object(PHPStan\Analyser\MutatingScope))
#17 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(311): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\Use_), Object(PHPStan\Analyser\MutatingScope))
#18 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(253): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Use_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#19 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(468): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#20 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(221): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#21 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(164): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#22 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(52): PHPStan\Analyser\FileAnalyser->analyseFile('/workspaces/mag...', Array, Object(PHPStan\Rules\Registry), NULL)
#23 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(56): PHPStan\Analyser\Analyser->analyse(Array, Object(Closure), NULL, true, Array)
#24 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(146): PHPStan\Command\AnalyserRunner->runAnalyser(Array, Array, Object(Closure), NULL, true, true, '/workspaces/mag...', NULL, NULL, Object(_PHPStan_c862bb974\Symfony\Component\Console\Input\ArgvInput))
#25 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(78): PHPStan\Command\AnalyseApplication->runAnalyser(Array, Array, true, '/workspaces/mag...', Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), Object(_PHPStan_c862bb974\Symfony\Component\Console\Input\ArgvInput))
#26 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(144): PHPStan\Command\AnalyseApplication->analyse(Array, true, Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), false, true, '/workspaces/mag...', Array, Object(_PHPStan_c862bb974\Symfony\Component\Console\Input\ArgvInput))
#27 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(228): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_c862bb974\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_c862bb974\Symfony\Component\Console\Output\ConsoleOutput))
#28 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(856): _PHPStan_c862bb974\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_c862bb974\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_c862bb974\Symfony\Component\Console\Output\ConsoleOutput))
#29 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(237): _PHPStan_c862bb974\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_c862bb974\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_c862bb974\Symfony\Component\Console\Output\ConsoleOutput))
#30 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(138): _PHPStan_c862bb974\Symfony\Component\Console\Application->doRun(Object(_PHPStan_c862bb974\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_c862bb974\Symfony\Component\Console\Output\ConsoleOutput))
#31 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(82): _PHPStan_c862bb974\Symfony\Component\Console\Application->run()
#32 phar:///workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(83): _PHPStan_c862bb974\{closure}()
#33 /workspaces/magento2/vendor/phpstan/phpstan/phpstan.phar(6): require('phar:///workspa...')
#34 {main
```

### Additional info

I did the investigation - it looks like for some reason, phpstan can't find the Magento\Framework\Code\Generator\ClassGenerator, as the composer autoloader isn't triggered for some reason.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Dear @ihor-sviziev,

We have tried to reproduce the issue in Magento 2.4-develop branch and it is reproducible for us with the mentioned steps. Please have a look at the below screenshot for reference:
![image](https://user-images.githubusercontent.com/51681618/147352468-1749d97d-5916-43f4-bdde-1c815f5e5a30.png)

Hence confirming this issue.

Thanks

**Comment by ihor-sviziev** [comment]
@xmav @andrewbess, could we add this issue to the platform health?
