### ISSUE TITLE
Page Builder Error When Add Product List With Admin User Scope Limitation

### ISSUE THREAD

**Issue by manhtranisobar** [magento/magento2#35181]
### Preconditions (*)

1. Magento 2.4.1-p1

### Steps to reproduce (*)
1. Create multiple websites
2. Create new admin user role with Role Scopes only single website
3. Logout and login with new admin user
4. Go to edit a CMS page
5. Edit by PageBuilder and add Products to content 
6. Filter products by select a category
![image](https://user-images.githubusercontent.com/88669934/157831388-5081463f-f758-4e91-8176-2f1203f0f50a.png)
![image](https://user-images.githubusercontent.com/88669934/157831527-a3ffd2ee-31cc-4856-b522-53e3c0326cf0.png)

### Expected result (*)

1. Add Products successfully

### Actual result (*)
1. Show SQL exception 
![image](https://user-images.githubusercontent.com/88669934/157830617-a761f3a7-e878-4275-9c99-e567c78ba1c3.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop instance with Enterprise edition modules enabled but cannot able to reproduce the issue.
Steps performed:
1. Admin - Stores - Configuration - Content Management - Advanced Content Tools - Enable Page Builder
2. Multi store setup
3. Create New User Role - System - User Roles - Add New Role - set Role scope as below:
![image](https://user-images.githubusercontent.com/60198231/161499841-47c842fc-a0f7-4a40-89f8-7ad6744ce0b2.png)

5. Create New Admin user - System - All Users - Add new USer - assign user role and save
6. Logout and login with new admin user
7. Go to edit a CMS page
8. Edit by PageBuilder and add Products to content
No issue: User is able to add products by Category and condition and able to apply template and save.
![image](https://user-images.githubusercontent.com/60198231/161499980-84c25ca9-0c1c-43ba-a4b4-ff76ddc61984.png)

![image](https://user-images.githubusercontent.com/60198231/161499891-3b95df01-e8e5-4590-b4be-558104bc001f.png)
@manhtranisobar kindly recheck the issue on Magento 2.4-develop branch as it is having latest code base and upcoming 2.4.x release and elaborate missing steps if the issue is still reproducible.
Thank you.

**Comment by manhtranisobar** [comment]
Hi @engcom-November 

Thanks for your testing, 
Sorry because I have missing at Step to reproduce and have updated again. Please help to check again with updates:
- The first website have two store views 
Thank you!

**Comment by engcom-November** [comment]
Verified the issue again on Magento 2.4-develop branch with Enterprise edition module enabled and the issue is reproducible.
Hence confirming the issue
![image](https://user-images.githubusercontent.com/60198231/161765507-d6661ee3-94c1-47de-ab7a-fec027b28867.png)

`
[2022-04-05T13:31:10.192945+00:00] report.CRITICAL: PDOException: SQLSTATE[21000]: Cardinality violation: 1241 Operand should contain 1 column(s) in /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php:90
Stack trace:
#0 /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(90): PDOStatement->execute()
#1 /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(106): Magento\Framework\DB\Statement\Pdo\Mysql->Magento\Framework\DB\Statement\Pdo\{closure}()
#2 /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(91): Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute()
#3 /var/www/html/magce/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(313): Magento\Framework\DB\Statement\Pdo\Mysql->_execute()
#4 /var/www/html/magce/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
#5 /var/www/html/magce/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#6 /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(564): Zend_Db_Adapter_Pdo_Abstract->query()
#7 /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(631): Magento\Framework\DB\Adapter\Pdo\Mysql->_query()
#8 /var/www/html/magce/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query()
#9 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Data/Collection/Db/FetchStrategy/Query.php(21): Zend_Db_Adapter_Abstract->fetchAll()
#10 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(782): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll()
#11 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(677): Magento\Framework\Data\Collection\AbstractDb->_fetchAll()
#12 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(580): Magento\Framework\Data\Collection\AbstractDb->getData()
#13 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter()
#14 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Review\Model\ResourceModel\Review\Summary\Collection\Interceptor->___callParent()
#15 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Review\Model\ResourceModel\Review\Summary\Collection\Interceptor->Magento\Framework\Interception\{closure}()
#16 /var/www/html/magce/magento2/generated/code/Magento/Review/Model/ResourceModel/Review/Summary/Collection/Interceptor.php(32): Magento\Review\Model\ResourceModel\Review\Summary\Collection\Interceptor->___callPlugins()
#17 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(565): Magento\Review\Model\ResourceModel\Review\Summary\Collection\Interceptor->loadWithFilter()
#18 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Data/Collection.php(300): Magento\Framework\Data\Collection\AbstractDb->load()
#19 /var/www/html/magce/magento2/app/code/Magento/Review/Model/AppendSummaryData.php(52): Magento\Framework\Data\Collection->getFirstItem()
#20 /var/www/html/magce/magento2/app/code/Magento/Review/Block/Product/ReviewRenderer.php(111): Magento\Review\Model\AppendSummaryData->execute()
#21 /var/www/html/magce/magento2/app/code/Magento/Catalog/Block/Product/AbstractProduct.php(221): Magento\Review\Block\Product\ReviewRenderer->getReviewsSummaryHtml()
#22 /var/www/html/magce/magento2/app/code/Magento/CatalogWidget/view/frontend/templates/product/widget/content/grid.phtml(55): Magento\Catalog\Block\Product\AbstractProduct->getReviewsSummaryHtml()
#23 /var/www/html/magce/magento2/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(71): include('/var/www/html/m...')
#24 /var/www/html/magce/magento2/lib/internal/Magento/Framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php->render()
#25 /var/www/html/magce/magento2/lib/internal/Magento/Framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#26 /var/www/html/magce/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#27 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php(136): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#28 /var/www/html/magce/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(1117): Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData()
#29 /var/www/html/magce/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#30 /var/www/html/magce/magento2/app/code/Magento/Widget/Model/Template/Filter.php(156): Magento\Framework\View\Element\AbstractBlock->toHtml()
#31 /var/www/html/magce/magento2/app/code/Magento/Widget/Model/Template/Filter.php(167): Magento\Widget\Model\Template\Filter->generateWidget()
#32 [internal function]: Magento\Widget\Model\Template\Filter->widgetDirective()
#33 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Filter/DirectiveProcessor/LegacyDirective.php(42): ReflectionMethod->invokeArgs()
#34 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Filter/Template.php(192): Magento\Framework\Filter\DirectiveProcessor\LegacyDirective->process()
#35 /var/www/html/magce/magento2/app/code/Magento/Email/Model/Template/Filter.php(1106): Magento\Framework\Filter\Template->filter()
#36 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Email\Model\Template\Filter->filter()
#37 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Widget\Model\Template\Filter\Interceptor->___callParent()
#38 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Widget\Model\Template\Filter\Interceptor->Magento\Framework\Interception\{closure}()
#39 /var/www/html/magce/magento2/generated/code/Magento/Widget/Model/Template/Filter/Interceptor.php(32): Magento\Widget\Model\Template\Filter\Interceptor->___callPlugins()
#40 /var/www/html/magce/magento2/ext/magento/magento2-page-builder/app/code/Magento/PageBuilder/Model/Stage/Renderer/WidgetDirective.php(73): Magento\Widget\Model\Template\Filter\Interceptor->filter()
#41 /var/www/html/magce/magento2/ext/magento/magento2-page-builder/app/code/Magento/PageBuilder/Controller/Adminhtml/Stage/Preview.php(63): Magento\PageBuilder\Model\Stage\Renderer\WidgetDirective->render()
#42 /var/www/html/magce/magento2/ext/magento/magento2-page-builder/app/code/Magento/PageBuilder/Model/Stage/Preview.php(122): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview->Magento\PageBuilder\Controller\Adminhtml\Stage\{closure}()
#43 [internal function]: Magento\PageBuilder\Model\Stage\Preview->Magento\PageBuilder\Model\Stage\{closure}()
#44 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/State.php(187): call_user_func_array()
#45 /var/www/html/magce/magento2/ext/magento/magento2-page-builder/app/code/Magento/PageBuilder/Model/Stage/Preview.php(130): Magento\Framework\App\State->emulateAreaCode()
#46 /var/www/html/magce/magento2/ext/magento/magento2-page-builder/app/code/Magento/PageBuilder/Controller/Adminhtml/Stage/Preview.php(66): Magento\PageBuilder\Model\Stage\Preview->startPreviewMode()
#47 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview->execute()
#48 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->___callParent()
#49 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->Magento\Framework\Interception\{closure}()
#50 /var/www/html/magce/magento2/generated/code/Magento/PageBuilder/Controller/Adminhtml/Stage/Preview/Interceptor.php(23): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->___callPlugins()
#51 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/Action/Action.php(111): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->execute()
#52 /var/www/html/magce/magento2/app/code/Magento/Backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#53 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#54 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->___callParent()
#55 /var/www/html/magce/magento2/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(145): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->Magento\Framework\Interception\{closure}()
#56 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#57 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->Magento\Framework\Interception\{closure}()
#58 /var/www/html/magce/magento2/generated/code/Magento/PageBuilder/Controller/Adminhtml/Stage/Preview/Interceptor.php(32): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->___callPlugins()
#59 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/FrontController.php(245): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->dispatch()
#60 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#61 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#62 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#63 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#64 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#65 /var/www/html/magce/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#66 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#67 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#68 /var/www/html/magce/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#69 {main}

Next Zend_Db_Statement_Exception: SQLSTATE[21000]: Cardinality violation: 1241 Operand should contain 1 column(s), query was: SELECT `main_table`.*, `review_entity`.`entity_code` FROM `review_entity_summary` AS `main_table`
 LEFT JOIN `review_entity` ON main_table.entity_type = review_entity.entity_id WHERE (store_id = 1) AND (entity_pk_value = '5') AND (entity_code = 'product') AND (store_id = 1, 3) in /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php:109
Stack trace:
#0 /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(91): Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute()
#1 /var/www/html/magce/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(313): Magento\Framework\DB\Statement\Pdo\Mysql->_execute()
#2 /var/www/html/magce/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
#3 /var/www/html/magce/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#4 /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(564): Zend_Db_Adapter_Pdo_Abstract->query()
#5 /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(631): Magento\Framework\DB\Adapter\Pdo\Mysql->_query()
#6 /var/www/html/magce/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query()
#7 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Data/Collection/Db/FetchStrategy/Query.php(21): Zend_Db_Adapter_Abstract->fetchAll()
#8 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(782): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll()
#9 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(677): Magento\Framework\Data\Collection\AbstractDb->_fetchAll()
#10 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(580): Magento\Framework\Data\Collection\AbstractDb->getData()
#11 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter()
#12 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Review\Model\ResourceModel\Review\Summary\Collection\Interceptor->___callParent()
#13 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Review\Model\ResourceModel\Review\Summary\Collection\Interceptor->Magento\Framework\Interception\{closure}()
#14 /var/www/html/magce/magento2/generated/code/Magento/Review/Model/ResourceModel/Review/Summary/Collection/Interceptor.php(32): Magento\Review\Model\ResourceModel\Review\Summary\Collection\Interceptor->___callPlugins()
#15 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(565): Magento\Review\Model\ResourceModel\Review\Summary\Collection\Interceptor->loadWithFilter()
#16 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Data/Collection.php(300): Magento\Framework\Data\Collection\AbstractDb->load()
#17 /var/www/html/magce/magento2/app/code/Magento/Review/Model/AppendSummaryData.php(52): Magento\Framework\Data\Collection->getFirstItem()
#18 /var/www/html/magce/magento2/app/code/Magento/Review/Block/Product/ReviewRenderer.php(111): Magento\Review\Model\AppendSummaryData->execute()
#19 /var/www/html/magce/magento2/app/code/Magento/Catalog/Block/Product/AbstractProduct.php(221): Magento\Review\Block\Product\ReviewRenderer->getReviewsSummaryHtml()
#20 /var/www/html/magce/magento2/app/code/Magento/CatalogWidget/view/frontend/templates/product/widget/content/grid.phtml(55): Magento\Catalog\Block\Product\AbstractProduct->getReviewsSummaryHtml()
#21 /var/www/html/magce/magento2/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(71): include('/var/www/html/m...')
#22 /var/www/html/magce/magento2/lib/internal/Magento/Framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php->render()
#23 /var/www/html/magce/magento2/lib/internal/Magento/Framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#24 /var/www/html/magce/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#25 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php(136): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#26 /var/www/html/magce/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(1117): Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData()
#27 /var/www/html/magce/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#28 /var/www/html/magce/magento2/app/code/Magento/Widget/Model/Template/Filter.php(156): Magento\Framework\View\Element\AbstractBlock->toHtml()
#29 /var/www/html/magce/magento2/app/code/Magento/Widget/Model/Template/Filter.php(167): Magento\Widget\Model\Template\Filter->generateWidget()
#30 [internal function]: Magento\Widget\Model\Template\Filter->widgetDirective()
#31 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Filter/DirectiveProcessor/LegacyDirective.php(42): ReflectionMethod->invokeArgs()
#32 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Filter/Template.php(192): Magento\Framework\Filter\DirectiveProcessor\LegacyDirective->process()
#33 /var/www/html/magce/magento2/app/code/Magento/Email/Model/Template/Filter.php(1106): Magento\Framework\Filter\Template->filter()
#34 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Email\Model\Template\Filter->filter()
#35 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Widget\Model\Template\Filter\Interceptor->___callParent()
#36 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Widget\Model\Template\Filter\Interceptor->Magento\Framework\Interception\{closure}()
#37 /var/www/html/magce/magento2/generated/code/Magento/Widget/Model/Template/Filter/Interceptor.php(32): Magento\Widget\Model\Template\Filter\Interceptor->___callPlugins()
#38 /var/www/html/magce/magento2/ext/magento/magento2-page-builder/app/code/Magento/PageBuilder/Model/Stage/Renderer/WidgetDirective.php(73): Magento\Widget\Model\Template\Filter\Interceptor->filter()
#39 /var/www/html/magce/magento2/ext/magento/magento2-page-builder/app/code/Magento/PageBuilder/Controller/Adminhtml/Stage/Preview.php(63): Magento\PageBuilder\Model\Stage\Renderer\WidgetDirective->render()
#40 /var/www/html/magce/magento2/ext/magento/magento2-page-builder/app/code/Magento/PageBuilder/Model/Stage/Preview.php(122): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview->Magento\PageBuilder\Controller\Adminhtml\Stage\{closure}()
#41 [internal function]: Magento\PageBuilder\Model\Stage\Preview->Magento\PageBuilder\Model\Stage\{closure}()
#42 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/State.php(187): call_user_func_array()
#43 /var/www/html/magce/magento2/ext/magento/magento2-page-builder/app/code/Magento/PageBuilder/Model/Stage/Preview.php(130): Magento\Framework\App\State->emulateAreaCode()
#44 /var/www/html/magce/magento2/ext/magento/magento2-page-builder/app/code/Magento/PageBuilder/Controller/Adminhtml/Stage/Preview.php(66): Magento\PageBuilder\Model\Stage\Preview->startPreviewMode()
#45 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview->execute()
#46 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->___callParent()
#47 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->Magento\Framework\Interception\{closure}()
#48 /var/www/html/magce/magento2/generated/code/Magento/PageBuilder/Controller/Adminhtml/Stage/Preview/Interceptor.php(23): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->___callPlugins()
#49 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/Action/Action.php(111): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->execute()
#50 /var/www/html/magce/magento2/app/code/Magento/Backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#51 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#52 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->___callParent()
#53 /var/www/html/magce/magento2/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(145): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->Magento\Framework\Interception\{closure}()
#54 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#55 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->Magento\Framework\Interception\{closure}()
#56 /var/www/html/magce/magento2/generated/code/Magento/PageBuilder/Controller/Adminhtml/Stage/Preview/Interceptor.php(32): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->___callPlugins()
#57 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/FrontController.php(245): Magento\PageBuilder\Controller\Adminhtml\Stage\Preview\Interceptor->dispatch()
#58 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#59 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#60 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#61 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#62 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#63 /var/www/html/magce/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#64 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#65 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#66 /var/www/html/magce/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#67 {main} [] []
`
