### ISSUE TITLE
Magento 2 rest api (catalogProductAttributeRepositoryV1 POST METHOD)

### ISSUE THREAD

**Issue by dariovranjkovic** [magento/magento2#35222]
### Preconditions (*)

1. Magento 2.4.3 CE
2. Apache, PHP version 7.4.14, mysql  Ver 8.0.28-0ubuntu0.20.04.3 for Linux on x86_64

### Steps to reproduce (*)

1. Create custom attribute for magento product:
```
{
 "attribute": {
   "is_wysiwyg_enabled": false,
   "is_html_allowed_on_front": false,
   "used_for_sort_by": false,
   "is_filterable": true,
   "is_filterable_in_search": true,
   "is_used_in_grid": true,
   "is_visible_in_grid": false,
   "is_filterable_in_grid": true,
   "position": 0,
   "apply_to": [],
   "is_searchable": "1",
   "is_visible_in_advanced_search": "1",
   "is_comparable": "1",
   "is_used_for_promo_rules": "0",
   "is_visible_on_front": "0",
   "used_in_product_listing": "1",
   "is_visible": true,
   "scope": "global",
   "attribute_code": "color_test_10",
   "frontend_input": "select",
   "entity_type_id": "4",
   "is_required": false,
   "options": [
    {
      "label": "red",
      "value": "100"
    },
    {
      "label": "blue",
      "value": "101"
    },
    {
      "label": "green",
      "value": "102"
    }
  ],
 "is_user_defined": true,
 "default_frontend_label": "Color test 3",
 "frontend_labels": null,
 "backend_type": "int",
 "source_model": "Magento%5C%5CEav%5C%5CModel%5C%5CEntity%5C%5CAttribute%5C%5CSource%5C%5CTable",
"default_value": "",
"is_unique": "0"
 }
}
```

### Expected result (*)

1. Expected correct response
2.

```
### Actual result (*)
<!--- Tell us what happened instead. Include error messages and issues. -->
1. 
{
    "message": "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`arvid_database`.`eav_attribute_option_value`, CONSTRAINT `EAV_ATTR_OPT_VAL_OPT_ID_EAV_ATTR_OPT_OPT_ID` FOREIGN KEY (`option_id`) REFERENCES `eav_attribute_option` (`option_id`) ON DELETE CASC), query was: INSERT INTO `eav_attribute_option_value` (`option_id`, `store_id`, `value`) VALUES (?, ?, ?)",
    "code": 23000,
    "trace": "#0 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(92): Magento\\Framework\\DB\\Statement\\Pdo\\Mysql->tryExecute(Object(Closure))\n#1 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\\Framework\\DB\\Statement\\Pdo\\Mysql->_execute(Array)\n#2 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)\n#3 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ea...', Array)\n#4 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(560): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `ea...', Array)\n#5 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(627): Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->_query('INSERT INTO `ea...', Array)\n#6 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->query('INSERT INTO `ea...', Array)\n#7 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute.php(561): Zend_Db_Adapter_Abstract->insert('eav_attribute_o...', Array)\n#8 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute.php(412): Magento\\Eav\\Model\\ResourceModel\\Entity\\Attribute->_updateAttributeOptionValues(100, Array)\n#9 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute.php(388): Magento\\Eav\\Model\\ResourceModel\\Entity\\Attribute->_processAttributeOptions(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor), Array)\n#10 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute.php(235): Magento\\Eav\\Model\\ResourceModel\\Entity\\Attribute->_saveOption(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#11 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-catalog/Model/ResourceModel/Attribute.php(84): Magento\\Eav\\Model\\ResourceModel\\Entity\\Attribute->_afterSave(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#12 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(863): Magento\\Catalog\\Model\\ResourceModel\\Attribute->_afterSave(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#13 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(424): Magento\\Framework\\Model\\ResourceModel\\Db\\AbstractDb->processAfterSaves(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#14 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Framework\\Model\\ResourceModel\\Db\\AbstractDb->save(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#15 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Catalog\\Model\\ResourceModel\\Attribute\\Interceptor->___callParent('save', Array)\n#16 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-catalog-search/Model/Attribute/SearchWeight.php(62): Magento\\Catalog\\Model\\ResourceModel\\Attribute\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#17 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(135): Magento\\CatalogSearch\\Model\\Attribute\\SearchWeight->aroundSave(Object(Magento\\Catalog\\Model\\ResourceModel\\Attribute\\Interceptor), Object(Closure), Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#18 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Catalog\\Model\\ResourceModel\\Attribute\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#19 /home/arvid/public_html/magento2-arvid-nilsson/generated/code/Magento/Catalog/Model/ResourceModel/Attribute/Interceptor.php(32): Magento\\Catalog\\Model\\ResourceModel\\Attribute\\Interceptor->___callPlugins('save', Array, Array)\n#20 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-catalog/Model/Product/Attribute/Repository.php(182): Magento\\Catalog\\Model\\ResourceModel\\Attribute\\Interceptor->save(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#21 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Catalog\\Model\\Product\\Attribute\\Repository->save(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#22 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Catalog\\Model\\Product\\Attribute\\Repository\\Interceptor->___callParent('save', Array)\n#23 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Catalog\\Model\\Product\\Attribute\\Repository\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#24 /home/arvid/public_html/magento2-arvid-nilsson/generated/code/Magento/Catalog/Model/Product/Attribute/Repository/Interceptor.php(32): Magento\\Catalog\\Model\\Product\\Attribute\\Repository\\Interceptor->___callPlugins('save', Array, Array)\n#25 [internal function]: Magento\\Catalog\\Model\\Product\\Attribute\\Repository\\Interceptor->save(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#26 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)\n#27 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#28 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#29 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#30 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#31 /home/arvid/public_html/magento2-arvid-nilsson/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#32 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/App/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#33 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/App/Bootstrap.php(264): Magento\\Framework\\App\\Http->launch()\n#34 /home/arvid/public_html/magento2-arvid-nilsson/pub/index.php(29): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#35 {main}"
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the iissue with same payload:
No issue: Response retrieved as expected:
![image](https://user-images.githubusercontent.com/60198231/159899512-7c08c081-ced8-4739-9451-5fe9e33d648e.png)

![image](https://user-images.githubusercontent.com/60198231/159899250-6919787b-17a3-4ae6-a0ee-ab3a248e5020.png)
@dariovranjkovic kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release and have latest code base. Provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by dariovranjkovic** [comment]
> I edited text above and write more info regarding this bug.
> ### Preconditions (*)
> 1. Magento 2.4.3 CE
> 2. Apache, PHP version 7.4.14, mysql Ver 8.0.28-0ubuntu0.20.04.3 for Linux on x86_64
> 
> ### Steps to reproduce (*)
> 1. Create custom attribute with options using API catalogProductAttributeRepositoryV1
>    Code exaple:
> 
> `{ "attribute": { "is_wysiwyg_enabled": false, "is_html_allowed_on_front": false, "used_for_sort_by": false, "is_filterable": true, "is_filterable_in_search": true, "is_used_in_grid": true, "is_visible_in_grid": false, "is_filterable_in_grid": true, "position": 0, "apply_to": [], "is_searchable": "1", "is_visible_in_advanced_search": "1", "is_comparable": "1", "is_used_for_promo_rules": "0", "is_visible_on_front": "0", "used_in_product_listing": "1", "is_visible": true, "scope": "global", "attribute_code": "color_test_10", "frontend_input": "select", "entity_type_id": "4", "is_required": false, "options": [ { "label": "red", "value": "100" }, { "label": "blue", "value": "101" }, { "label": "green", "value": "102" } ], "is_user_defined": true, "default_frontend_label": "Color test 3", "frontend_labels": null, "backend_type": "int", "source_model": "Magento%5C%5CEav%5C%5CModel%5C%5CEntity%5C%5CAttribute%5C%5CSource%5C%5CTable", "default_value": "", "is_unique": "0" } }`
> 
> ### Expected result (*)
> 1. Expected result response, also this API works fine when I remove value from options
>    `{ "extension_attributes": { "is_pagebuilder_enabled": false }, "is_wysiwyg_enabled": false, "is_html_allowed_on_front": false, "used_for_sort_by": false, "is_filterable": true, "is_filterable_in_search": true, "is_used_in_grid": true, "is_visible_in_grid": false, "is_filterable_in_grid": true, "position": 0, "apply_to": [], "is_searchable": "1", "is_visible_in_advanced_search": "1", "is_comparable": "1", "is_used_for_promo_rules": "0", "is_visible_on_front": "0", "used_in_product_listing": "1", "is_visible": true, "scope": "global", "attribute_id": 399, "attribute_code": "color_test_12", "frontend_input": "select", "entity_type_id": "4", "is_required": false, "options": [ { "label": " ", "value": "" }, { "label": "red", "value": "100" }, { "label": "blue", "value": "101" }, { "label": "green", "value": "102" } ], "is_user_defined": true, "default_frontend_label": "Color test 3", "frontend_labels": [], "backend_type": "int", "source_model": "Magento\\Eav\\Model\\Entity\\Attribute\\Source\\Table", "default_value": "", "is_unique": "0", "validation_rules": [] }`
> 
> ### Actual result (*)
> 1. [Screenshots, logs or description]
>    `{ "message": "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`arvid_database`.`eav_attribute_option_value`, CONSTRAINT `EAV_ATTR_OPT_VAL_OPT_ID_EAV_ATTR_OPT_OPT_ID` FOREIGN KEY (`option_id`) REFERENCES `eav_attribute_option` (`option_id`) ON DELETE CASC), query was: INSERT INTO `eav_attribute_option_value` (`option_id`, `store_id`, `value`) VALUES (?, ?, ?)", "code": 23000, "trace": "#0 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(92): Magento\\Framework\\DB\\Statement\\Pdo\\Mysql->tryExecute(Object(Closure))\n#1 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\\Framework\\DB\\Statement\\Pdo\\Mysql->_execute(Array)\n#2 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)\n#3 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ea...', Array)\n#4 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(560): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `ea...', Array)\n#5 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(627): Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->_query('INSERT INTO `ea...', Array)\n#6 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `ea...', Array)\n#7 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute.php(561): Zend_Db_Adapter_Abstract->insert('eav_attribute_o...', Array)\n#8 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute.php(412): Magento\\Eav\\Model\\ResourceModel\\Entity\\Attribute->_updateAttributeOptionValues(100, Array)\n#9 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute.php(388): Magento\\Eav\\Model\\ResourceModel\\Entity\\Attribute->_processAttributeOptions(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor), Array)\n#10 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute.php(235): Magento\\Eav\\Model\\ResourceModel\\Entity\\Attribute->_saveOption(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#11 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-catalog/Model/ResourceModel/Attribute.php(84): Magento\\Eav\\Model\\ResourceModel\\Entity\\Attribute->_afterSave(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#12 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(863): Magento\\Catalog\\Model\\ResourceModel\\Attribute->_afterSave(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#13 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(424): Magento\\Framework\\Model\\ResourceModel\\Db\\AbstractDb->processAfterSaves(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#14 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Framework\\Model\\ResourceModel\\Db\\AbstractDb->save(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#15 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Catalog\\Model\\ResourceModel\\Attribute\\Interceptor->___callParent('save', Array)\n#16 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-catalog-search/Model/Attribute/SearchWeight.php(62): Magento\\Catalog\\Model\\ResourceModel\\Attribute\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#17 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(135): Magento\\CatalogSearch\\Model\\Attribute\\SearchWeight->aroundSave(Object(Magento\\Catalog\\Model\\ResourceModel\\Attribute\\Interceptor), Object(Closure), Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#18 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Catalog\\Model\\ResourceModel\\Attribute\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#19 /home/arvid/public_html/magento2-arvid-nilsson/generated/code/Magento/Catalog/Model/ResourceModel/Attribute/Interceptor.php(32): Magento\\Catalog\\Model\\ResourceModel\\Attribute\\Interceptor->___callPlugins('save', Array, Array)\n#20 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-catalog/Model/Product/Attribute/Repository.php(182): Magento\\Catalog\\Model\\ResourceModel\\Attribute\\Interceptor->save(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#21 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Catalog\\Model\\Product\\Attribute\\Repository->save(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#22 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Catalog\\Model\\Product\\Attribute\\Repository\\Interceptor->___callParent('save', Array)\n#23 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Catalog\\Model\\Product\\Attribute\\Repository\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#24 /home/arvid/public_html/magento2-arvid-nilsson/generated/code/Magento/Catalog/Model/Product/Attribute/Repository/Interceptor.php(32): Magento\\Catalog\\Model\\Product\\Attribute\\Repository\\Interceptor->___callPlugins('save', Array, Array)\n#25 [internal function]: Magento\\Catalog\\Model\\Product\\Attribute\\Repository\\Interceptor->save(Object(Magento\\Catalog\\Model\\ResourceModel\\Eav\\Attribute\\Interceptor))\n#26 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)\n#27 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#28 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#29 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#30 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#31 /home/arvid/public_html/magento2-arvid-nilsson/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#32 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/App/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#33 /home/arvid/public_html/magento2-arvid-nilsson/vendor/magento/framework/App/Bootstrap.php(264): Magento\\Framework\\App\\Http->launch()\n#34 /home/arvid/public_html/magento2-arvid-nilsson/pub/index.php(29): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#35 {main}" }`
> 
> Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.
> 
> * [ ]  Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
> * [ ]  Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
> * [ ]  Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
> * [ ]  Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
> * [ ]  Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
This issue is not reproducible on clean vanilla 2.4-develop instance but is reproducible when Enterprise edition modules are enabled. Hence transferring this issue to partners-magento2ee repository.
`[2022-04-04T10:08:54.329042+00:00] report.CRITICAL: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magce`.`eav_attribute_option_value`, CONSTRAINT `EAV_ATTR_OPT_VAL_OPT_ID_EAV_ATTR_OPT_OPT_ID` FOREIGN KEY (`option_id`) REFERENCES `eav_attribute_option` (`option_id`) ON DELETE CASCADE) in /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php:90
Stack trace:
#0 /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(90): PDOStatement->execute()
#1 /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(106): Magento\Framework\DB\Statement\Pdo\Mysql->Magento\Framework\DB\Statement\Pdo\{closure}()
#2 /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(91): Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute()
#3 /var/www/html/magce/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(313): Magento\Framework\DB\Statement\Pdo\Mysql->_execute()
#4 /var/www/html/magce/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
#5 /var/www/html/magce/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#6 /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(564): Zend_Db_Adapter_Pdo_Abstract->query()
#7 /var/www/html/magce/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(631): Magento\Framework\DB\Adapter\Pdo\Mysql->_query()
#8 /var/www/html/magce/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query()
#9 /var/www/html/magce/magento2/app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute.php(561): Zend_Db_Adapter_Abstract->insert()
#10 /var/www/html/magce/magento2/app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute.php(412): Magento\Eav\Model\ResourceModel\Entity\Attribute->_updateAttributeOptionValues()
#11 /var/www/html/magce/magento2/app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute.php(388): Magento\Eav\Model\ResourceModel\Entity\Attribute->_processAttributeOptions()
#12 /var/www/html/magce/magento2/app/code/Magento/Eav/Model/ResourceModel/Entity/Attribute.php(235): Magento\Eav\Model\ResourceModel\Entity\Attribute->_saveOption()
#13 /var/www/html/magce/magento2/app/code/Magento/Catalog/Model/ResourceModel/Attribute.php(84): Magento\Eav\Model\ResourceModel\Entity\Attribute->_afterSave()
#14 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Model/ResourceModel/Db/AbstractDb.php(841): Magento\Catalog\Model\ResourceModel\Attribute->_afterSave()
#15 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Model/ResourceModel/Db/AbstractDb.php(402): Magento\Framework\Model\ResourceModel\Db\AbstractDb->processAfterSaves()
#16 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save()
#17 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ResourceModel\Attribute\Interceptor->___callParent()
#18 /var/www/html/magce/magento2/app/code/Magento/CatalogSearch/Model/Attribute/SearchWeight.php(62): Magento\Catalog\Model\ResourceModel\Attribute\Interceptor->Magento\Framework\Interception\{closure}()
#19 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\CatalogSearch\Model\Attribute\SearchWeight->aroundSave()
#20 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ResourceModel\Attribute\Interceptor->Magento\Framework\Interception\{closure}()
#21 /var/www/html/magce/magento2/generated/code/Magento/Catalog/Model/ResourceModel/Attribute/Interceptor.php(32): Magento\Catalog\Model\ResourceModel\Attribute\Interceptor->___callPlugins()
#22 /var/www/html/magce/magento2/app/code/Magento/Catalog/Model/Product/Attribute/Repository.php(182): Magento\Catalog\Model\ResourceModel\Attribute\Interceptor->save()
#23 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Catalog\Model\Product\Attribute\Repository->save()
#24 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Catalog\Model\Product\Attribute\Repository\Interceptor->___callParent()
#25 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Catalog\Model\Product\Attribute\Repository\Interceptor->Magento\Framework\Interception\{closure}()
#26 /var/www/html/magce/magento2/generated/code/Magento/Catalog/Model/Product/Attribute/Repository/Interceptor.php(32): Magento\Catalog\Model\Product\Attribute\Repository\Interceptor->___callPlugins()
#27 [internal function]: Magento\Catalog\Model\Product\Attribute\Repository\Interceptor->save()
#28 /var/www/html/magce/magento2/app/code/Magento/Webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()
#29 /var/www/html/magce/magento2/app/code/Magento/Webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()
#30 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
#31 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
#32 /var/www/html/magce/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
#33 /var/www/html/magce/magento2/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
#34 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
#35 /var/www/html/magce/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#36 /var/www/html/magce/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#37 {main}`
![image](https://user-images.githubusercontent.com/60198231/161523181-383ebf17-da97-4eb6-a471-3c070f666141.png)
