### ISSUE TITLE
When changing from PHP 7.4 to PHP 8.1.3 I cannot use console commands anymore: "Fatal error: During inheritance of Countable"

### ISSUE THREAD

**Issue by C4rter** [magento/magento2#35314]
### Preconditions (*)

1. Running Magento Version 2.4.4 with PHP 8.1.3 after update from Magento 2.4.3

### Steps to reproduce (*)
1. Update from 2.4.3 to 2.4.4 with PHP 7.4
2. Switch PHP to 8.1.3
3. Try to run commands like bin/magento setup:upgrade
4. Throws error: PHP Fatal error:  During inheritance of Countable: Uncaught Exception: Deprecated Functionality: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/composer/composer/src/Composer/Repository/ArrayRepository.php on line 277 in /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61

### Expected result (*)
1. Be able to run commands without error

### Actual result (*)
1. Every Magento console command throws the error above

Stacktrace:
PHP Fatal error:  During inheritance of Countable: Uncaught Exception: Deprecated Functionality: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/composer/composer/src/Composer/Repository/ArrayRepository.php on line 277 in /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /var/www/html/vendor/composer/composer/src/Composer/Repository/ArrayRepository.php(28): Magento\Framework\App\ErrorHandler->handler(8192, 'Return type of ...', '/var/www/html/v...', 277)
#1 /var/www/html/vendor/composer/ClassLoader.php(571): include('/var/www/html/v...')
#2 /var/www/html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/html/v...')
#3 /var/www/html/vendor/composer/composer/src/Composer/Repository/PlatformRepository.php(31): Composer\Autoload\ClassLoader->loadClass('Composer\\Reposi...')
#4 /var/www/html/vendor/composer/ClassLoader.php(571): include('/var/www/html/v...')
#5 /var/www/html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/html/v...')
#6 /var/www/html/vendor/composer/composer/src/Composer/Package/Loader/ValidatingArrayLoader.php(375): Composer\Autoload\ClassLoader->loadClass('Composer\\Reposi...')
#7 /var/www/html/vendor/composer/composer/src/Composer/Package/Loader/RootPackageLoader.php(70): Composer\Package\Loader\ValidatingArrayLoader::hasPackageNamingError('magento/project...')
#8 /var/www/html/vendor/composer/composer/src/Composer/Factory.php(368): Composer\Package\Loader\RootPackageLoader->load(Array, 'Composer\\Packag...', '/var/www/html')
#9 /var/www/html/vendor/composer/composer/src/Composer/Factory.php(595): Composer\Factory->createComposer(Object(Composer\IO\BufferIO), Array, false)
#10 /var/www/html/vendor/magento/framework/Composer/ComposerFactory.php(47): Composer\Factory::create(Object(Composer\IO\BufferIO), '/var/www/html/c...')
#11 /var/www/html/vendor/magento/framework/Composer/ComposerInformation.php(368): Magento\Framework\Composer\ComposerFactory->create()
#12 /var/www/html/vendor/magento/framework/Composer/ComposerInformation.php(381): Magento\Framework\Composer\ComposerInformation->getComposer()
#13 /var/www/html/vendor/magento/framework/Composer/ComposerInformation.php(244): Magento\Framework\Composer\ComposerInformation->getLocker()
#14 /var/www/html/vendor/magento/framework/App/ProductMetadata.php(120): Magento\Framework\Composer\ComposerInformation->getSystemPackages()
#15 /var/www/html/vendor/magento/framework/App/ProductMetadata.php(80): Magento\Framework\App\ProductMetadata->getSystemPackageVersion()
#16 /var/www/html/vendor/magento/framework/Console/Cli.php(98): Magento\Framework\App\ProductMetadata->getVersion()
#17 /var/www/html/bin/magento(22): Magento\Framework\Console\Cli->__construct('Magento CLI')
#18 {main} in /var/www/html/vendor/composer/composer/src/Composer/Repository/ArrayRepository.php on line 28

**Comment by C4rter** [comment]
https://github.com/magento/magento2/issues/35306
