### ISSUE TITLE
Email module breaks setup:upgrade in 2.4.3-p2

### ISSUE THREAD

**Issue by enr-beck-mellow** [magento/magento2#35342]
### Preconditions (*)

1. Magento 2.4.3-p2
2. PHP 7.3

### Steps to reproduce (*)

1. Setup new environment with magento 2.4.3-p2 and php 7.3
Running composer create-project command does not give any error but running php bin/magento setup:install command returns an error which is not meaningful / clear
### Expected result (*)

composer create-project command returns below meaningful error:
https://github.com/magento/magento2/issues/35342#issuecomment-1106489093
![image](https://user-images.githubusercontent.com/60198231/164721394-a6d75cb6-85c1-4059-8c2c-0f954222e5d0.png)

### Actual result (*)

1. A syntax error occurs when Composer ClassLoader includes "Magento\Email\Console\Command\DatabaseTemplateCompatibilityCommand" because php 7.4 functionality is used (typed properties: https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.core.typed-properties)
2. `syntax error, unexpected 'CollectionFactory' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)#0 /var/www/html/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/v...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Magento\\Email\\C...')
#2 [internal function]: spl_autoload_call('Magento\\Email\\C...')
#3 /var/www/html/vendor/magento/framework/ObjectManager/Relations/Runtime.php(38): class_exists('Magento\\Email\\C...')
#4 /var/www/html/vendor/magento/framework/Interception/Config/Config.php(157): Magento\Framework\ObjectManager\Relations\Runtime->has('Magento\\Email\\C...')
#5 /var/www/html/vendor/magento/framework/Interception/Config/Config.php(180): Magento\Framework\Interception\Config\Config->_inheritInterception('Magento\\Email\\C...')
#6 /var/www/html/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php(61): Magento\Framework\Interception\Config\Config->hasPlugins('Magento\\Email\\C...')
#7 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(47): Magento\Framework\Interception\ObjectManager\Config\Developer->getInstanceType('Magento\\Email\\C...')
#8 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Email\\C...')
#9 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(206): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Email\\C...')
#10 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(182): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray(Array)
#11 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, NULL, Array, 'commands', 'Magento\\Framewo...')
#12 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument('Magento\\Framewo...', Array, Array)
#13 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Framewo...', Array, Array)
#14 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#15 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#16 /var/www/html/vendor/magento/framework/Console/Cli.php(153): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...')
#17 /var/www/html/vendor/magento/framework/Console/Cli.php(134): Magento\Framework\Console\Cli->getApplicationCommands()
#18 /var/www/html/vendor/symfony/console/Application.php(1274): Magento\Framework\Console\Cli->getDefaultCommands()
#19 /var/www/html/vendor/symfony/console/Application.php(629): Symfony\Component\Console\Application->init()
#20 /var/www/html/vendor/symfony/console/Application.php(237): Symfony\Component\Console\Application->find('s:up')
#21 /var/www/html/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#24 {main}`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
Even though technically Magento 2.4.3-p2 is installable with PHP 7.3 using composer (not sure why they still allow this?), it's not recommended and the [system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) specify that it was only tested with PHP 7.4.

So I'm not sure if they will consider this as a valid bug report. You'd probably best want to upgrade to PHP 7.4 in order to solve this.

**Comment by enr-beck-mellow** [comment]
Good point. I didnt lookup the system requirements because composer installed it without any problems (also with 2.4.2).

**Comment by CronoxAU** [comment]
Just want to add a comment that I encountered the same issue testing 2.4.3-p2 on PHP 7.3.

This thread was invaluable in finding the issue, and thanks @hostep for the system requirements chart which does make the issue clear.

Given that previously 2.4.3 ran without any issues on PHP 7.3 I think adding some clear notification that PHP 7.4 is now required would be very beneficial.

**Comment by engcom-November** [comment]
Hi @enr-beck-mellow ,
Thank you for reporting and collaboration. Verified this issue by installing Magento 2.4.3-p2 with php 7.3 and running composer create-project does not give any error but running php bin/magento setup:install command returns an error which is not meaningful / clear
![image](https://user-images.githubusercontent.com/60198231/164718680-b98d44ad-8fe9-4fea-91da-b48b86d4c5cd.png)

Expected behavior:
composer create-project command returns below meaningful error:
![image](https://user-images.githubusercontent.com/60198231/164718613-45af29d5-7184-49ed-ae96-4c3b2129d992.png)

Hence confirming this issue.

**Comment by engcom-Bravo** [comment]
Hi @enr-beck-mellow,

Thanks for your reporting and collaboration.

We are closing this issue.

Thanks.
