### ISSUE TITLE
Magento 2.4.4 Can't Save customer if date attribute with default value exists.

### ISSUE THREAD

**Issue by MargoKep** [magento/magento2#35435]
Preconditions (*)

Magento 2.4.4
PHP 8.1

Steps to reproduce (*)
1.Create new customer attribute with Input Type=Date and set default value--> Save
2 Go to the creation a new customer and fill in the required fields--> Save

Expected result (*)

Success  save customer.
Actual result (*)
Error and  Can't Save customer
ValueError: bcsub(): Argument #1 ($num1) is not well-formed in /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/zendframework1/library/Zend/Locale/Math.php:259
Stack trace:
#0 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/zendframework1/library/Zend/Locale/Math.php(259): bcsub()
#1 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/zendframework1/library/Zend/Locale/Format.php(385): Zend_Locale_Math::Sub()
#2 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/zendframework1/library/Zend/Locale/Format.php(662): Zend_Locale_Format::toNumber()
#3 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/zendframework1/library/Zend/Filter/NormalizedToLocalized.php(106): Zend_Locale_Format::toFloat()
#4 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/Data/Form/Filter/Date.php(69): Zend_Filter_NormalizedToLocalized->filter()
#5 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/module-customer/Model/Metadata/Form/AbstractData.php(197): Magento\Framework\Data\Form\Filter\Date->inputFilter()
#6 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/module-customer/Model/Metadata/Form/Date.php(20): Magento\Customer\Model\Metadata\Form\AbstractData->_applyInputFilter()
#7 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/module-customer/Model/Metadata/Form.php(244): Magento\Customer\Model\Metadata\Form\Date->extractValue()
#8 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Model\Metadata\Form->extractData()
#9 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Model\Metadata\Form\Interceptor->___callParent()
#10 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Model\Metadata\Form\Interceptor->Magento\Framework\Interception\{closure}()
#11 /var/www/vhosts/8.1/mg244eemultyup/generated/code/Magento/Customer/Model/Metadata/Form/Interceptor.php(23): Magento\Customer\Model\Metadata\Form\Interceptor->___callPlugins()
#12 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/module-customer/Controller/Adminhtml/Index/Save.php(215): Magento\Customer\Model\Metadata\Form\Interceptor->extractData()
#13 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/module-customer/Controller/Adminhtml/Index/Save.php(185): Magento\Customer\Controller\Adminhtml\Index\Save->_extractData()
#14 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/module-customer/Controller/Adminhtml/Index/Save.php(328): Magento\Customer\Controller\Adminhtml\Index\Save->_extractCustomerData()
#15 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Controller\Adminhtml\Index\Save->execute()
#16 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callParent()
#17 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->Magento\Framework\Interception\{closure}()
#18 /var/www/vhosts/8.1/mg244eemultyup/generated/code/Magento/Customer/Controller/Adminhtml/Index/Save/Interceptor.php(23): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callPlugins()
#19 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/App/Action/Action.php(111): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->execute()
#20 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#21 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#22 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callParent()
#23 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->Magento\Framework\Interception\{closure}()
#24 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#25 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->Magento\Framework\Interception\{closure}()
#26 /var/www/vhosts/8.1/mg244eemultyup/generated/code/Magento/Customer/Controller/Adminhtml/Index/Save/Interceptor.php(32): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callPlugins()
#27 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/App/FrontController.php(245): Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->dispatch()
#28 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#29 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#30 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#31 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#32 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#33 /var/www/vhosts/8.1/mg244eemultyup/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#34 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#35 /var/www/vhosts/8.1/mg244eemultyup/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#36 /var/www/vhosts/8.1/mg244eemultyup/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#37 {main}

Severity (*) S2

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch with Enterprise edition modules installed and the issue is reproducible.
Hence updating description and confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/167105875-76814071-abbe-4438-beae-c2a48f4e9a32.png)
![image](https://user-images.githubusercontent.com/60198231/167105918-4e78ad26-4bdc-43b0-b417-fe68664b397d.png)
