### ISSUE TITLE
rtrim() expects parameter 1 to be string, bool given vendor/magento/framework/Encryption/Adapter/Mcrypt.php(171): rtrim()

### ISSUE THREAD

**Issue by hoangngo-calvin** [magento/magento2#35464]
### Preconditions (*)

1. Magento 2.4.3-p2
2. php7.4.29
3. MySQL 8.0
4. Ubuntu 22.04

### Steps to reproduce (*)

1. Run composer to download source code
2. run the install command
```
php bin/magento setup:install \
 --base-url=http://mc243p2.local/ \
 --db-host=127.0.0.1:8030 \
 --db-user=root \
 --db-password=RootAD111!!! \
 --backend-frontname=admin \
 --admin-firstname=admin \
 --admin-lastname=admin \
 --admin-email=adminwww@admin.com \
 --admin-user=admin \
 --admin-password=Admin111!!! \
 --use-rewrites=1 \
--elasticsearch-host=127.0.0.1 \
--elasticsearch-port=9230 \
--elasticsearch-index-prefix=demo_mc243p2 \
 --db-name=demo_mc243p2_01
```

### Expected result (*)

Command run successfully

### Actual result (*)

There is an exception
```
[Progress: 1015 / 1382]
Module 'Dotdigitalgroup_Email':
Installing data... Upgrading data... 
Enabling caches:
Current status:
layout: 1
block_html: 1
full_page: 1
rtrim() expects parameter 1 to be string, bool given#0 /var/www/mc243p2/vendor/magento/framework/Encryption/Adapter/Mcrypt.php(171): rtrim()
#1 /var/www/mc243p2/vendor/magento/framework/Encryption/Encryptor.php(452): Magento\Framework\Encryption\Adapter\Mcrypt->decrypt()
#2 /var/www/mc243p2/vendor/magento/module-config/Model/Config/Backend/Encrypted.php(111): Magento\Framework\Encryption\Encryptor->decrypt()
#3 /var/www/mc243p2/generated/code/Magento/Config/Model/Config/Backend/Encrypted/Interceptor.php(32): Magento\Config\Model\Config\Backend\Encrypted->processValue()
#4 /var/www/mc243p2/vendor/magento/framework/App/Config/MetadataConfigTypeProcessor.php(133): Magento\Config\Model\Config\Backend\Encrypted\Interceptor->processValue()
#5 /var/www/mc243p2/vendor/magento/framework/App/Config/MetadataConfigTypeProcessor.php(152): Magento\Framework\App\Config\MetadataConfigTypeProcessor->processScopeData()
#6 /var/www/mc243p2/vendor/magento/framework/App/Config/PostProcessorComposite.php(36): Magento\Framework\App\Config\MetadataConfigTypeProcessor->process()
#7 /var/www/mc243p2/generated/code/Magento/Framework/App/Config/PostProcessorComposite/Proxy.php(95): Magento\Framework\App\Config\PostProcessorComposite->process()
#8 /var/www/mc243p2/vendor/magento/module-config/App/Config/Type/System.php(397): Magento\Framework\App\Config\PostProcessorComposite\Proxy->process()
#9 /var/www/mc243p2/vendor/magento/framework/Cache/LockGuardedCacheLoader.php(136): Magento\Config\App\Config\Type\System->readData()
#10 /var/www/mc243p2/vendor/magento/module-config/App/Config/Type/System.php(281): Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData()
#11 /var/www/mc243p2/vendor/magento/module-config/App/Config/Type/System.php(207): Magento\Config\App\Config\Type\System->loadDefaultScopeData()
#12 /var/www/mc243p2/vendor/magento/module-config/App/Config/Type/System.php(181): Magento\Config\App\Config\Type\System->getWithParts()
#13 /var/www/mc243p2/vendor/magento/framework/App/Config.php(132): Magento\Config\App\Config\Type\System->get()
#14 /var/www/mc243p2/vendor/magento/framework/App/Config.php(80): Magento\Framework\App\Config->get()
#15 /var/www/mc243p2/vendor/magento/framework/App/Config.php(93): Magento\Framework\App\Config->getValue()
#16 /var/www/mc243p2/vendor/dotmailer/dotmailer-magento2-extension/Setup/UpgradeData.php(400): Magento\Framework\App\Config->isSetFlag()
#17 /var/www/mc243p2/vendor/dotmailer/dotmailer-magento2-extension/Setup/UpgradeData.php(170): Dotdigitalgroup\Email\Setup\UpgradeData->upgradeFourFiveTwo()
#18 /var/www/mc243p2/setup/src/Magento/Setup/Model/Installer.php(1076): Dotdigitalgroup\Email\Setup\UpgradeData->upgrade()
#19 /var/www/mc243p2/setup/src/Magento/Setup/Model/Installer.php(960): Magento\Setup\Model\Installer->handleDBSchemaData()
#20 [internal function]: Magento\Setup\Model\Installer->installDataFixtures()
#21 /var/www/mc243p2/setup/src/Magento/Setup/Model/Installer.php(389): call_user_func_array()
#22 /var/www/mc243p2/setup/src/Magento/Setup/Console/Command/InstallCommand.php(231): Magento\Setup\Model\Installer->install()
#23 /var/www/mc243p2/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\InstallCommand->execute()
#24 /var/www/mc243p2/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#25 /var/www/mc243p2/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#26 /var/www/mc243p2/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun()
#27 /var/www/mc243p2/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#28 /var/www/mc243p2/bin/magento(23): Symfony\Component\Console\Application->run()
#29 {main}
```
![image](https://user-images.githubusercontent.com/31319355/168054774-26f4f1bf-2cb2-4517-9563-8ebd6cc69246.png)

**Comment by hoangss** [comment]
While I'm debugging I saw this method return false: openssl_decrypt() in:
```
\phpseclib\Crypt\Base::decrypt
vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php:1084
```

![image](https://user-images.githubusercontent.com/31319355/168067350-6068fc46-b3ce-4e19-89d6-0934ca39bcfc.png)

Im not quite sure what is wrong.

**Comment by shoaibpnp** [comment]
I had the same issue today. I found out the php mcrypt library was not installed.

I just installed it on my server using `apt install php7.4-mcrypt`

Now installation worked perfectly

**Comment by engcom-Dash** [comment]
Hello @Reporter,

We have tried to reproduce the issue in Magento 2.4.3-p2 instance. the issue is not reproducible. Please refer the below screenshot for the reference;

![Screenshot from 2022-05-17 17-43-48](https://user-images.githubusercontent.com/60198592/168808730-5c8e8c73-23cc-4cd6-97b0-f8ed1fac8e22.png)
![Screenshot from 2022-05-17 17-44-00](https://user-images.githubusercontent.com/60198592/168808735-5e7159f3-a1b2-4f06-9aef-ce4902935b19.png)
![Screenshot from 2022-05-17 17-45-08](https://user-images.githubusercontent.com/60198592/168808780-2dc2bc82-50a8-4456-b3c4-08f1eb235153.png)
![Screenshot from 2022-05-17 17-45-11](https://user-images.githubusercontent.com/60198592/168808783-884e1d0f-7d03-4210-9ea0-1299215884c7.png)
![Screenshot from 2022-05-17 17-45-21](https://user-images.githubusercontent.com/60198592/168808788-da6eafef-2d4d-4a0d-a1ff-bdce67b9477c.png)
![Screenshot from 2022-05-17 17-45-35](https://user-images.githubusercontent.com/60198592/168808793-85955a4e-0097-4b6d-a44f-458763755bba.png)

We have followed the below steps in order to reproduce the issue:
1.To Install Magento 2.4.3-p2 Instance
2. Run setup Install Comment.
3.Comment Runned Sucessfully.
...

Let us know in case we have missed anything.

Thanks

**Comment by hoangss** [comment]
So, do we need to have mcrypt extension?
According to devdocs  [System requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#php-extensions): seem we don't need it.

**Comment by pnt9948** [comment]
Thanks @shoaibpnp for notifying about the mcrypt issue. After installing the extension, it got resolved.

**Comment by engcom-Dash** [comment]
Hello @hoangss ,

We have tried to reproduce the issue in Magento 2.4-develop branch the issue is not reproducible. Please refer the below screenshot for the reference;

![Screenshot from 2022-05-31 14-55-20](https://user-images.githubusercontent.com/60198592/171141000-48fd1a45-c997-4fb3-b78f-0d26dd7b5e87.png)


We have followed the below steps in order to reproduce the issue:


1.Run composer to download source code
2.run the install command
3.Even Installed and verified with M crypt Extension
4.Command Ran Successfully.
...

Let us know in case we have missed anything.

Thanks

**Comment by hoangss** [comment]
Thank @engcom-Dash 
Yes mcrypt resolved the issue for me. But according the devdocs, mcrypt is not in required extension list. 

So is it out of date document or something wrong with code?

**Comment by engcom-Dash** [comment]
Hi @hoangss 
We were Worked With mcrypt extension as well as Without Mcrypt Extension.But We are not able to Reproduce the Issue.We got Expected Result in 2.4.3-p2.

**Comment by hoangss** [comment]
hi @engcom-Dash,
Thank you for the info.
You are not able to reproduce this issue even you don't have mcrypt installed in your system, is my understanding correct?

**Comment by hostep** [comment]
@hoangss: out of curiosity, did you had the sodium php extension installed when you ran against the problem? (you can find it via `php -m` on the cli) Not saying it will solve your problem, but it might, so this is just a guess ...

**Comment by hoangss** [comment]
@hostep Thank you for replying
Yes. I have sodium(also openssl) installed when I run magento install command

**Comment by engcom-Dash** [comment]
Hi @hoangss ,
Thanks for your Reply.
Yes,we tried to reproduce the issue with M crypt extension as well as without M crypt also.But we were unable to reproduce.

**Comment by engcom-Dash** [comment]
Hi @hoangss ,
We are used following php without Mcrypt and with Mcrypt.
ext-bcmath
ext-ctype
ext-curl
ext-dom
ext-fileinfo
ext-gd
ext-hash
ext-iconv
ext-intl
ext-json
ext-libxml
ext-mbstring
ext-openssl
ext-pcre
ext-pdo_mysql
ext-simplexml
ext-soap
ext-sockets
ext-sodium
ext-tokenizer
ext-xmlwriter
ext-xsl
ext-zip
lib-libxml
lib-openssl




Thanks.

**Comment by hoangss** [comment]
> lib-openssl
hi @engcom-Dash, thank you for the response.
Sorry I may ask stupid questions: what is this extension: ```lib-openssl```, and how to install it? seems it's different with openssl, isn't it?

**Comment by engcom-Dash** [comment]
Hi @hoangss ,
Yes ,for php 7.4 we did't use this extension...its come under the system requirements.

**Comment by engcom-Hotel** [comment]
Hello @hoangss,

I think SSL support doesn't depend on an extension, it's already built into Ubuntu's PHP. We haven't installed it separately. 

You can check it via the output of `<?php phpinfo() ?>`.

We have also rechecked the issue in another system without the MCrypt library and the Magento installation is successful. 

I have also checked the [PHP Doc](https://www.php.net/manual/en/intro.mcrypt.php), The MCrypt feature was DEPRECATED in PHP 7.1.0 and REMOVED in PHP 7.2.0. The alternative for the same is:

- Sodium
- OpenSSL

I request you to please recheck the same with removing MCrypt and installing Sodium, and OpenSSL, and let us know in case you face any issues.

Thanks

**Comment by hoangss** [comment]
Hi @engcom-Hotel 

In earlier comment, I mentioned that I have both Sodium and OpenSSl installed and I still got the issue. 

https://github.com/magento/magento2/issues/35464#issuecomment-1145880824

**Comment by hostep** [comment]
@hoangss: just out of curiosity, I've tried it myself as well without the mcrypt extension being installed.
And a clean installation of Magento 2.4.3-p2 with PHP 7.4.29 works just fine, no errors.

Here's my full php extensions list:

```
$ php -m
[PHP Modules]
apcu
bcmath
blackfire
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
intl
json
libxml
mbstring
mongodb
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
ssh2
standard
tokenizer
xdebug
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
blackfire
```

What I do notice as a difference, is that in my case, I'm seeing 1383 steps in the installation output, and you only get 1382 steps, so it sounds like one module is maybe not being installed, maybe the absence of that one module causes trouble somehow?

**Comment by hoangss** [comment]
hi @hostep 
thank you for helping me. This is my PHP's extension list

```
php -m
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
intl
json
libxml
mbstring
mcrypt <======== I installed this to bypass the issue
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xdebug
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
```

> I'm seeing 1383 steps in the installation output,

Do you mind sharing your installation output? is that CE or EE version?

**Comment by hostep** [comment]
It's CE (which is called Open Source these days).
Just try setting up Magento 2.4.3-p2 again from scratch, maybe some dependency got some newer version and that bumps the number by one?

If you still run into the same problem when the mcrypt extension is not installed, try debugging [these lines](https://github.com/magento/magento2/blob/2.4.3-p2/lib/internal/Magento/Framework/Encryption/Encryptor.php#L511-L551), and see why they return an Mcrypt instance and maybe also [what exact data](https://github.com/magento/magento2/blob/2.4.3-p2/app/code/Magento/Config/Model/Config/Backend/Encrypted.php#L109-L112) is trying to be decrypted, and where that data comes from.

**Comment by hoangss** [comment]
hi @hostep 
According to this comment: https://github.com/magento/magento2/issues/35464#issuecomment-1124892017
I tried to debug, IIRC It seems doesn't return the Mcrypt instance, It used OpenSSL to decrypt and the data returned by `processValue()` is `false` (in the image)
And then it throw the exception
```rtrim() expects parameter 1 to be string, bool given#0 /var/www/mc243p2/vendor/magento/framework/Encryption/Adapter/Mcrypt.php(171): rtrim()```

openssl_decrypt was called:
```$plaintext = openssl_decrypt($ciphertext, $this->cipher_name_openssl, $this->key, $this->openssl_options);```

**Comment by engcom-Hotel** [comment]
Thanks, @hostep for the guidance.

Hello @hoangss,

We have tried to debug the issue as per this https://github.com/magento/magento2/issues/35464#issuecomment-1160022835 and add a breakpoint in the `getCrypt` method at line no. 517 and 538. As we can see, it always returns the `SodiumChachaIetf` object and does not break on line 538.

Thanks

**Comment by zeljko989** [comment]
> I had the same issue today. I found out the php mcrypt library was not installed.
> 
> I just installed it on my server using `apt install php7.4-mcrypt`
> 
> Now installation worked perfectly

YEAH,  that was issue with my setup also, and I got this error below ( maybe to someone will be helpful ):

- During the upgrade command process

```
Type Error occurred when creating object: Magento\Framework\Locale\Resolver, rtrim() expects parameter 1 to be string, bool given
In AbstractFactory.php line 131:
  Type Error occurred when creating object: Magento\Framework\Locale\Resolver, rtrim() expects parameter 1 to be string, bool given
```

**Comment by engcom-Hotel** [comment]
Hello @zeljko989,

Thanks for the contribution!

Please let us know from which version to which version you are trying to upgrade the Magento.

Thanks

**Comment by shuvoenr** [comment]
@engcom-Hotel 

Please do try with configuration @hoangngo-calvin at first line.

Magento 2.4.3-p2
php7.4.30
MySQL 8.0
Ubuntu 22.04

With ubuntu 22.04.

I tried with that configuration and every-time found same issue & that's weird.

apt install php7.4-mcrypt install solved the issue but which obviously not optimal. As Magento release on 12 April. On the other hand ubuntu release on 21st april.

There may be compatibility issue

**Comment by engcom-Hotel** [comment]
Hello @hoangngo-calvin @shuvoenr,

Thanks for the report and collaboration!

We are able to reproduce the issue with Magento 2.4.3-P2 with the below configuration:

- PHP 7.4.30
- Mysql 8.0
- Ubuntu 22.04

![Versions](https://user-images.githubusercontent.com/51681618/177771973-0cfc4e1b-0a95-430c-b8e6-049320dfa82d.jpg)

Getting the error:
![error](https://user-images.githubusercontent.com/51681618/177777179-5ea175c6-717c-4311-b9eb-9ef13916d0c3.jpg)

But after installing Mcrypt, the installation is successful:
![after_mcrypt_installation](https://user-images.githubusercontent.com/51681618/177777257-56519b09-dbc2-4e59-8470-aae39ecd55d7.jpg)

We have also tried to install Magento 2.4.4 and 2.4-develop with the below configuration:

- PHP 8.1
- Mysql 8.0
- Ubuntu 22.04

The installation is successfully done. 

So confirming this issue for 2.4.3-p2.

Thanks

**Comment by hoangngo-calvin** [comment]
Hi @engcom-Hotel 
Thank you so much for your effort.

**Comment by webloft** [comment]
This bug appeared out of nowhere yesterday. The mcrypt workaround solved the issue it seems.

What happens in background? The log says it tries to decrypt the value 'Paypal'. Is that something related to an invalid API key or something?

`Magento\\Framework\\Encryption\\Encryptor->decrypt('PayPal')`
