### ISSUE TITLE
PHP Fatal error in cron job magento_giftcardaccount_update_states

### ISSUE THREAD

**Issue by engcom-November** [magento/magento2#35523]
@fredden Reopening this issue reported by you as the old one is transferred to partnersee-repo
https://github.com/magento/partners-magento2ee/issues/681
### Preconditions and environment

1. Tested with Adobe Commerce v2.4.3-p1. Other versions are also affected.
2. Create a new Website and associated Store but no store view
3. cron enabled

### Steps to reproduce

1. Created new website and Store (Stores - All Stores) but no store view
2. Reindex and clear cache
3. Inserted record in cron_schedule table with job_code "jmagento_giftcardaccount_update_states"
4. ran cron job from CLI:
5. php bin/magento cron:run --group magento_giftcardaccount_update_states;
Output: Job ran successfully without any errors
6. Verify message in cron_schedule table:

Note: Other records inserted gives no errors.
Note: If Store view is created for the new store, error is not displayed on performing above steps.

### Expected result

No PHP error should be displayed.

### Actual result

    PHP Fatal error is thrown.

app@686b4c600be7:~/html$ vendor/bin/n98-magerun2 sys:cron:run magento_giftcardaccount_update_states
Run Magento\GiftCardAccount\Model\Cron::updateStates PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /var/www/html/vendor/magento/module-gift-card-account/Model/Cron.php:91
Stack trace:
#0 phar:///var/www/html/vendor/n98/magerun2-dist/n98-magerun2/src/N98/Magento/Command/System/Cron/RunCommand.php(66): Magento\GiftCardAccount\Model\Cron->updateStates(Object(Magento\Cron\Model\Schedule\Interceptor))
magento/magento2#1 /var/www/html/vendor/symfony/console/Command/Command.php(255): N98\Magento\Command\System\Cron\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
magento/magento2#2 phar:///var/www/html/vendor/n98/magerun2-dist/n98-magerun2/src/N98/Magento/Command/AbstractMagentoCommand.php(363): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
magento/magento2#3 phar:///var/www/html/vendor/n98/magerun2-dist/n98-magerun2/vendor/symfony/console/Application.php(1027): N98\Magento\Command\AbstractMagentoCommand->run(Object(S in /var/www/html/vendor/magento/module-gift-card-account/Model/Cron.php on line 91

Fatal error: Uncaught Error: Call to a member function getId() on null in /var/www/html/vendor/magento/module-gift-card-account/Model/Cron.php:91
Stack trace:
#0 phar:///var/www/html/vendor/n98/magerun2-dist/n98-magerun2/src/N98/Magento/Command/System/Cron/RunCommand.php(66): Magento\GiftCardAccount\Model\Cron->updateStates(Object(Magento\Cron\Model\Schedule\Interceptor))
magento/magento2#1 /var/www/html/vendor/symfony/console/Command/Command.php(255): N98\Magento\Command\System\Cron\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
magento/magento2#2 phar:///var/www/html/vendor/n98/magerun2-dist/n98-magerun2/src/N98/Magento/Command/AbstractMagentoCommand.php(363): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
magento/magento2#3 phar:///var/www/html/vendor/n98/magerun2-dist/n98-magerun2/vendor/symfony/console/Application.php(1027): N98\Magento\Command\AbstractMagentoCommand->run(Object(S in /var/www/html/vendor/magento/module-gift-card-account/Model/Cron.php on line 91
app@686b4c600be7:~/html$ 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Created new issue as this issue got moved to partners-ee repo: https://github.com/magento/partners-magento2ee/issues/681. Hence confirming the issue here.

**Comment by fredden** [comment]
@engcom-November can the original issue not be transferred back here?
It looks like the formatting of the issue has been lost in the copy/paste.

**Comment by fredden** [comment]
@engcom-November please can you fix the formatting of this issue to match the original I submitted.

**Comment by engcom-Delta** [comment]
Hi @fredden ,

Thanks for your reporting and collaboration.
We have re-verified the issue in Latest 2.4-develop instance , but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Created new website and Store (Stores - All Stores) but no store view
2. Reindex and clear cache
3. Inserted record in cron_schedule table with job_code "jmagento_giftcardaccount_update_states"
4. ran cron job from CLI:
5. php bin/magento cron:run --group magento_giftcardaccount_update_states;
6. Output: Job ran successfully without any errors
Expected result
No PHP error should be displayed.
![image](https://github.com/user-attachments/assets/59568858-3397-4d71-aa1e-deecedfc0b0f)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by fredden** [comment]
@engcom-November please see https://github.com/magento/magento2/issues/35523#issuecomment-2475657737

**Comment by engcom-November** [comment]
Hello @fredden ,

We followed the steps outlined above and attempted to reproduce the issue, but were unable to do so. Could you please try it on your end and let us know if you're still encountering the same problem?

Additionally, please let us know if there's anything we might be missing in our reproduction process.

Looking forward to your response.
Thank you!

**Comment by fredden** [comment]
@engcom-November please see https://github.com/magento/magento2/issues/35523#issuecomment-2475657737

**Comment by lbajsarowicz** [comment]
Gift Card Account is a Commerce-only module and is not part of magento/magento2. Please report this through the Adobe Commerce support channel.

cc @hostep
