### ISSUE TITLE
Get error while create new customer

### ISSUE THREAD

**Issue by devphoenix2404** [magento/magento2#35575]
### Preconditions and environment

- Magento version : 2.4.3-p2
- Anything else that would help a developer reproduce the bug
can you help here

### Steps to reproduce

Create a new account

### Expected result

```
TypeError: Return value of Magento\Framework\Mail\TransportInterfaceFactory::create() must be an instance of Magento\Framework\Mail\TransportInterface, instance of Sendinblue\Sendinblue\Model\Transport returned in /var/www/html/lib/internal/Magento/Framework/Mail/TransportInterfaceFactory.php:53
Stack trace:
#0 /var/www/html/lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php(337): Magento\Framework\Mail\TransportInterfaceFactory->create(Array)
#1 /var/www/html/generated/code/Magento/Framework/Mail/Template/TransportBuilder/Interceptor.php(113): Magento\Framework\Mail\Template\TransportBuilder->getTransport()
#2 /var/www/html/app/code/Magento/Newsletter/Model/Subscriber.php(574): Magento\Framework\Mail\Template\TransportBuilder\Interceptor->getTransport()
#3 /var/www/html/app/code/Magento/Newsletter/Model/Subscriber.php(520): Magento\Newsletter\Model\Subscriber->sendEmail('newsletter/subs...', 'newsletter/subs...')
#4 /var/www/html/generated/code/Magento/Newsletter/Model/Subscriber/Interceptor.php(212): Magento\Newsletter\Model\Subscriber->sendConfirmationSuccessEmail()
#5 /var/www/html/app/code/Magento/Newsletter/Model/SubscriptionManager.php(329): Magento\Newsletter\Model\Subscriber\Interceptor->sendConfirmationSuccessEmail()
#6 /var/www/html/app/code/Magento/Newsletter/Model/SubscriptionManager.php(167): Magento\Newsletter\Model\SubscriptionManager->sendEmailAfterChangeStatus(Object(Magento\Newsletter\Model\Subscriber\Interceptor))
#7 /var/www/html/app/code/Magento/Newsletter/Model/SubscriptionManager.php(136): Magento\Newsletter\Model\SubscriptionManager->updateCustomerSubscription(10, 1, true)
#8 /var/www/html/app/code/Magento/Newsletter/Model/Plugin/CustomerPlugin.php(141): Magento\Newsletter\Model\SubscriptionManager->subscribeCustomer(10, 1)
#9 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(146): Magento\Newsletter\Model\Plugin\CustomerPlugin->afterSave(Object(Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor), Object(Magento\Customer\Model\Data\Customer), Object(Magento\Customer\Model\Data\Customer), '4e538964a5f8a65...')
#10 /var/www/html/app/code/Magento/Customer/Model/Plugin/CustomerRepository/TransactionWrapper.php(44): Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Customer\Model\Data\Customer), '4e538964a5f8a65...')
#11 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Customer\Model\Plugin\CustomerRepository\TransactionWrapper->aroundSave(Object(Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor), Object(Closure), Object(Magento\Customer\Model\Data\Customer), '4e538964a5f8a65...')
#12 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Customer\Model\Data\Customer), '4e538964a5f8a65...')
#13 /var/www/html/generated/code/Magento/Customer/Model/ResourceModel/CustomerRepository/Interceptor.php(23): Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->___callPlugins('save', Array, Array)
#14 /var/www/html/app/code/Magento/Customer/Model/AccountManagement.php(927): Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->save(Object(Magento\Customer\Model\Data\Customer), '4e538964a5f8a65...')
#15 /var/www/html/generated/code/Magento/Customer/Model/AccountManagement/Interceptor.php(104): Magento\Customer\Model\AccountManagement->createAccountWithPasswordHash(Object(Magento\Customer\Model\Data\Customer), '4e538964a5f8a65...', NULL)
#16 /var/www/html/app/code/Magento/Customer/Model/AccountManagement.php(874): Magento\Customer\Model\AccountManagement\Interceptor->createAccountWithPasswordHash(Object(Magento\Customer\Model\Data\Customer), '4e538964a5f8a65...', NULL)
#17 /var/www/html/generated/code/Magento/Customer/Model/AccountManagement/Interceptor.php(95): Magento\Customer\Model\AccountManagement->createAccount(Object(Magento\Customer\Model\Data\Customer), 'Phoenix@2404_', NULL)
#18 /var/www/html/app/code/Magento/Customer/Controller/Account/CreatePost.php(380): Magento\Customer\Model\AccountManagement\Interceptor->createAccount(Object(Magento\Customer\Model\Data\Customer), 'Phoenix@2404_', NULL)
#19 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Customer\Controller\Account\CreatePost->execute()
#20 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent('execute', Array)
#21 /var/www/html/app/code/Magento/Customer/Controller/Plugin/Account.php(64): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
#22 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Customer\Controller\Plugin\Account->aroundExecute(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Closure))
#23 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
#24 /var/www/html/generated/code/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(41): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins('execute', Array, Array)
#25 /var/www/html/lib/internal/Magento/Framework/App/Action/Action.php(111): Magento\Customer\Controller\Account\CreatePost\Interceptor->execute()
#26 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent('dispatch', Array)
#28 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#29 /var/www/html/generated/code/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(50): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins('dispatch', Array, Array)
#30 /var/www/html/lib/internal/Magento/Framework/App/FrontController.php(245): Magento\Customer\Controller\Account\CreatePost\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /var/www/html/lib/internal/Magento/Framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magento\Customer\Controller\Account\CreatePost\Interceptor), Object(Magento\Framework\App\Request\Http))
#32 /var/www/html/lib/internal/Magento/Framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Customer\Controller\Account\CreatePost\Interceptor))
#33 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#35 /var/www/html/app/code/Magento/Store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#36 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 /var/www/html/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#38 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#39 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#40 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#41 /var/www/html/lib/internal/Magento/Framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#42 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#43 /var/www/html/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#44 /var/www/html/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#45 {main}<br />
<b>Fatal error</b>:  Uncaught Exception: User Error: Some transactions have not been committed or rolled back in /var/www/html/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php on line 4050 in /var/www/html/lib/internal/Magento/Framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler-&gt;handler(256, 'Some transactio...', '/var/www/html/l...', 4050, Array)
#1 /var/www/html/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(4050): trigger_error('Some transactio...', 256)
#2 [internal function]: Magento\Framework\DB\Adapter\Pdo\Mysql-&gt;__destruct()
#3 {main}
  thrown in <b>/var/www/html/lib/internal/Magento/Framework/App/ErrorHandler.php</b> on line <b>61</b><br />
```

### Actual result

It should create a new user without any error

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hello @devphoenix2404 , 
We have tried to reproduce the issue in Magento 2.4-develop branch the issue is not reproducible.

Please refer the below screenshot for the reference;
![Screenshot from 2022-06-03 15-32-26](https://user-images.githubusercontent.com/60198592/171837105-4742abb3-e2c2-4671-b122-338904c2b969.png)
![Screenshot from 2022-06-03 15-32-33](https://user-images.githubusercontent.com/60198592/171837114-8c4c07b9-db0d-419d-a0bd-71270003518c.png)
![Screenshot from 2022-06-03 15-32-38](https://user-images.githubusercontent.com/60198592/171837119-fc110754-d4f7-4920-a704-adffc20598b8.png)

We have followed the below steps in order to reproduce the issue:
1.Open Magento  Customers view Page
2.Create New Account
3.Should Able Create a Account.

 Let us know in case we have missed anything. 2

Thanks

**Comment by hostep** [comment]
@devphoenix2404: your error mentions SendInBlue, which isn't part of core Magento. You probably want to talk to the developers of the [SendInBlue Magento module](https://marketplace.magento.com/sendinblue-module-sendinblue.html) instead of trying to find help here on github 🙂

**Comment by engcom-Dash** [comment]
Hi @devphoenix2404 ,
We are trying to reproduce the issue but we are not able to reproduce because sendinblue is not part of magento.

**Comment by devphoenix2404** [comment]
Thanks you guys 😊
I will do the needful :) 
One more question, is there any redirection or parmalinks I need to set after installation of magento?

**Comment by engcom-Dash** [comment]
Hi @devphoenix2404 ,
Thanks for your reply...
I am not sure is there any redirection or parmalinks I need to set after installation of magento. But we did't follow any redirection as well as paramalinks after the magento Installation. 

Thanks.

**Comment by devphoenix2404** [comment]
Thanks
