### ISSUE TITLE
Inserting products in database issue in magento with excel import

### ISSUE THREAD

**Issue by Tahermoti** [magento/magento2#35599]
We have built custom utility to upload product on Magento ver. 2.3.5-p1 asp.net from local computer to ubuntu server 20.04 AWS mysql server 8.0 and php ver 7.2 with apache 2.4 the product is upload with excel file

Date Time : 6/9/2022 1:25:50 PM
-------------------------------------------------------------------------
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.Close()
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MagentoImport.UI.Dashboard.UpdateName(MySqlCommand command, String item_code, String item_name, String item_name_ar)
=========================================================================
=========================================================================
Date Time : 6/9/2022 2:14:11 PM
-------------------------------------------------------------------------
Input string was not in a correct format.
=========================================================================
=========================================================================
Date Time : 6/9/2022 2:14:11 PM
-------------------------------------------------------------------------
Input string was not in a correct format.
=========================================================================
=========================================================================
Date Time : 6/9/2022 2:14:34 PM
-------------------------------------------------------------------------
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.Close()
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at MagentoImport.UI.Dashboard.btnImport_Click(Object sender, EventArgs e)
=========================================================================
=========================================================================
Date Time : 6/9/2022 2:16:11 PM
-------------------------------------------------------------------------
Error inserting item : 8273-1211_7810 into Database or product with this sku already present
=========================================================================
=========================================================================
Date Time : 6/9/2022 2:16:11 PM
-------------------------------------------------------------------------
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.Close()
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MagentoImport.UI.Dashboard.UpdateName(MySqlCommand command, String item_code, String item_name, String item_name_ar)
=========================================================================
=========================================================================
Date Time : 6/9/2022 2:23:07 PM
-------------------------------------------------------------------------
Input string was not in a correct format.
=========================================================================
=========================================================================
Date Time : 6/9/2022 2:23:07 PM
-------------------------------------------------------------------------
Input string was not in a correct format.
=========================================================================
=========================================================================
Date Time : 6/9/2022 2:23:09 PM
-------------------------------------------------------------------------
Thread was being aborted.
=========================================================================
=========================================================================
Date Time : 6/9/2022 2:25:53 PM
-------------------------------------------------------------------------
Error inserting item : 8273-1211_7810 into Database or product with this sku already present
=========================================================================
=========================================================================
Date Time : 6/9/2022 2:25:54 PM
-------------------------------------------------------------------------
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.Close()
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MagentoImport.UI.Dashboard.UpdateName(MySqlCommand command, String item_code, String item_name, String item_name_ar)
=========================================================================
=========================================================================
Date Time : 6/9/2022 2:40:35 PM
-------------------------------------------------------------------------
Error inserting item : 5651-2934_9045 into Database or product with this sku already present
=========================================================================
=========================================================================
Date Time : 6/9/2022 2:40:35 PM
-------------------------------------------------------------------------
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.Close()
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at MagentoImport.UI.Dashboard.UpdateName(MySqlCommand command, String item_code, String item_name, String item_name_ar)

**Comment by engcom-Hotel** [comment]
Hello @Tahermoti,

thanks for the report and collaboration!

As per looking into the stack trace and error, it doesn't look like an issue in the Magento core library. Please check the customized module from which you have tried to upload the images.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @Tahermoti,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
