### ISSUE TITLE
Can't use Braintree Paypal without enabling Braintree Credit Card

### ISSUE THREAD

**Issue by nick-ose** [magento/magento2#35698]
### Preconditions and environment

- Magento version 2.4.4
- Braintree PayPal enabled
- Braintree Card Payments Disabled

### Steps to reproduce

1. Enable Braintree in Admin
2. Set 'Enable Card Payments' to 'No'.
3. Set 'Enable PayPal through Braintree' to 'Yes'
4. Navigate to frontend
5. Add product to cart
6. Go to Checkout
7. Select the BrainTree Paypal method

### Expected result

PayPal method is selected and PayPal button appears

### Actual result

Method is not selected, page loader is stuck and an error appears in the console.

adapter.js:66 Uncaught TypeError: Cannot read properties of undefined (reading 'clientToken')
    at Object.getClientToken (adapter.js:66:66)
    at Object.setup (adapter.js:181:23)
    at UiClass.reInitPayPal (paypal.js:290:27)
    at UiClass.onActiveChange (paypal.js:195:18)
    at setNested (objects.js:44:25)
    at Object.nested (objects.js:118:20)
....

### Additional information

After some investigation it seems this is happening due to a change in the following class:

PayPal\Braintree\Model\Ui\ConfigProvider

public function getConfig(): array
{
    if (!$this->config->isActive()) {
        return [];
    }

There is now a check that will return an empty array if the braintree credit card method is not active. This was not in older versions. This data maps to the frontend javascript settings of 'window.checkoutConfig.payment["braintree"]'

In the paypal method renderer it calls for the web/js/view/payment/adapter.js which expects there to be settings under the above 'payment["braintree"]' section. When it cannot find these settings it errors and cannot load.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue on both 2.4.4 project-community-edition and Magento 2.4-develop branch and the issue is reproducible. Hence confirming this issue.
![image](https://user-images.githubusercontent.com/60198231/178260760-da8fcc58-0b3a-4ee3-a8c6-dc0c55afb0a4.png)

Thank you.

**Comment by yogesh-valiya** [comment]
@magento I am working on this

**Comment by yogesh-valiya** [comment]
This duplicates - https://github.com/magento/magento2/issues/35961

**Comment by engcom-Bravo** [comment]
Hi @nick-ose,

As per this comment https://github.com/magento/magento2/issues/35961#issuecomment-2579169289 we are closing this issue.

Thanks.
