### ISSUE TITLE
Breaking change and incorrect docs for `AccountManagement::resetPassword` in 2.4.3-p2+

### ISSUE THREAD

**Issue by kardeiz** [magento/magento2#35726]
### Preconditions and environment

- Magento version 2.4.3-p2 (looks like it also applies to 2.4.4)

### Steps to reproduce

Post an empty string (`''`) as the `email` parameter to POST `/customers/resetPassword` API endpoint.

### Expected result

Expected service returns 200 OK, with password reset appropriately.

### Actual result

Endpoint will respond with 400:
```
{
    "message": "\"%fieldName\" is required. Enter and try again.",
    "parameters": {
        "fieldName": "email"
    }
}
```

The 2.4.3-p2 docs suggest that an empty email will be replaced by lookup via the resetPassword token:

https://github.com/magento/magento2/blob/1dd4ee8c3ab26dbb762fbaf9893c1f75148bb35b/app/code/Magento/Customer/Api/AccountManagementInterface.php#L146-L158

However, looking at the actual implementation, this does not appear to be the case: it is now set to throw the error above:

https://github.com/magento/magento2/blob/1dd4ee8c3ab26dbb762fbaf9893c1f75148bb35b/app/code/Magento/Customer/Model/AccountManagement.php#L714-L721

This is a pretty major change from 2.4.3-p1:

https://github.com/magento/magento2/blob/8afdb9858d238392ecb5dbfe556068ec1af137bc/app/code/Magento/Customer/Model/AccountManagement.php#L714-L721

And it is completely breaking our reset password functionality for users.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @kardeiz ,
Thanks for raising an issue , Need help on the request body that you have tried , so that we can replicate it .

In fact , we have tried below request but getting different error.

Request:
{
email: "roni_cost@example.com",
resetPasswordToken: "gh80pkjGdsPyiXc0sUUXswX1uGN7crUr",
newPassword: "new_password"

}

Response:
{
    "message": "Decoding error."
}

**Comment by kardeiz** [comment]
Our request body looks like:

```
{
    "newPassword": "newPassword",
    "resetToken": "resetToken",
    "email": ""
 }
```

Note the empty string for `email`. As far as I can tell, the token key is still `resetToken` not `resetPasswordToken` in 2.4.3-p2 (and possibly 2.4.4).

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi Kardeiz,
We tried to reproduce the issue on magento 2.4 develop , issue is reproducible , Hence issue has been confirmed.

followed steps:
1. Run below API

Endpoint----->. PUT -->   http://localhost/rest/default/V1/customers/password
Body: 
{
  "email": "teslatester@gmail.com",
  "template": "email_reset"
}

Response: 
true

2. Run below API
Endpoint----->. POST -->  http://localhost/rest/default/V1/customers/resetPassword

Body:
{
"email": "",
"resetToken": "00:3:yy/6Rj33nHPHL+mpHTWp6dlHUqtzVNNA0bTUG1PqsfRBJxcLiLHAwr77xQTQprpyijY6V5Fs/rP+AWXf",
"newPassword":"Tester@321"
}

Response:
{
    "message": "\"%fieldName\" is required. Enter and try again.",
    "parameters": {
        "fieldName": "email"
    },
    "trace": "#0 /opt/homebrew/var/www/magento24d3/magento2/generated/code/Magento/Customer/Model/AccountManagementApi/Interceptor.php(86): Magento\\Customer\\Model\\AccountManagement->resetPassword('', '00:3:yy/6Rj33nH...', 'Tester@321')\n#1 [internal function]: Magento\\Customer\\Model\\AccountManagementApi\\Interceptor->resetPassword('', '00:3:yy/6Rj33nH...', 'Tester@321')\n#2 /opt/homebrew/var/www/magento24d3/magento2/app/code/Magento/Webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)\n#3 /opt/homebrew/var/www/magento24d3/magento2/app/code/Magento/Webapi/Controller/Rest.php(195): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#4 /opt/homebrew/var/www/magento24d3/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#5 /opt/homebrew/var/www/magento24d3/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#6 /opt/homebrew/var/www/magento24d3/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#7 /opt/homebrew/var/www/magento24d3/magento2/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#8 /opt/homebrew/var/www/magento24d3/magento2/lib/internal/Magento/Framework/App/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#9 /opt/homebrew/var/www/magento24d3/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\\Framework\\App\\Http->launch()\n#10 /opt/homebrew/var/www/magento24d3/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#11 /opt/homebrew/var/www/magento24d3/magento2/pub/index.php(31): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#12 {main}"
}

**screenshot** 

<img width="1007" alt="Screenshot 2022-07-22 at 6 13 47 PM" src="https://user-images.githubusercontent.com/51681379/180442276-539c8abd-d909-4326-a9df-d864d32002e1.png">

**Despite of providing valid email id and valid reset_token , api is not working .**

<img width="997" alt="Screenshot 2022-07-22 at 6 23 50 PM" src="https://user-images.githubusercontent.com/51681379/180443472-42bc1619-d44a-4ee2-8128-f9a7ab848d9c.png">

**Comment by engcom-Delta** [comment]
Hi @kardeiz ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance and the issue is reproducible.
Kindly refer the screenshots.

**Steps to reproduce -** 

1. Post an empty string ('') as the email parameter to POST /customers/resetPassword API endpoint.
![image](https://github.com/user-attachments/assets/7fa65f6c-c507-4fa8-9141-86cb949dd8be)
2. Now, Enter the email id and run the API
![image](https://github.com/user-attachments/assets/ec875a21-af08-4ceb-926c-7338c8c87ce0)
Observe without email user is not able to reset password

Thanks.
