### ISSUE TITLE
Product grid is not getting displayed, getting undefined array key "name" in logs.

### ISSUE THREAD

**Issue by malikt** [magento/magento2#35783]
### Preconditions and environment

- Magento 2.4.4
- Upgraded from M2.4.1
- PHP 8.1

### Steps to reproduce

1. Login as admin.
2. Go to Store->attributes->product search code "name" and set Values Required to "NO"
3. Create a product without name in 2.4.1 and then upgrade to 2.4.4 along with PHP.
4. Now, create a Product without name after setting the 'Name' attribute as not mandatory.

### Expected result

The Product Grid should load fine as usual.

### Actual result

The Product Grid throws an alert of something went wrong and freezes.

### Additional information

The Log shows the below error:
`main.CRITICAL: Exception: Warning: Undefined array key "name" in /vendor/magento/module-catalog/Ui/Component/Listing/Columns/ProductActions.php on line 61 in /vendor/magento/framework/App/ErrorHandler.php:61`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:** Product grid is not displayed in the admin panel.

**Pre-requisite:**

1. Install fresh M 2.4.1
2. Upgrade to latest version.
3. PHP 8.1

**Steps to reproduce:**

1. Install 2.4.1.
3. Login as admin.
4. Go to Store->attributes->product search code "name" and set Values Required to "NO"
5. Create a product without name in 2.4.1 and then upgrade to latest version of Magento along with PHP.
6. Now, create a Product without name after setting the 'Name' attribute as not mandatory.


**Expected result:** Grid should be displayed.
**Actual result:** In my case, grid is not visible and getting error in the admin panel.
Screenshots:
![Screenshot from 2022-07-21 12-47-06](https://user-images.githubusercontent.com/60198022/180153317-2187daaf-e8d7-43b7-80bb-d03d01839d21.png)

![Screenshot from 2022-07-21 12-42-11](https://user-images.githubusercontent.com/60198022/180153343-d87a8f8d-926d-4063-ae56-43a59874422e.png)

Found new issue related to this issue : https://github.com/magento/magento2/issues/35789
Hence, confirming this issue.

Thanks

**Comment by Nuranto** [comment]
We can confirm this issue too.

**Comment by rohit-prjpt** [comment]
This could happen when there is any product stored without required attribute "name" and either you can add name value or remove that bad created product.

**Comment by RiccardoRoscilli** [comment]
Is there a way to find with a query the product without name?

**Comment by rohit-prjpt** [comment]
@RiccardoRoscilli Here is the query to find out products without name

`SELECT sku,entity_id FROM `catalog_product_entity` WHERE `entity_id` NOT IN (SELECT `entity_id` FROM `catalog_product_entity_varchar` WHERE `attribute_id` IN (SELECT attribute_id FROM `eav_attribute` WHERE `attribute_code`='name'))`

**Comment by PaperDS** [comment]
> `SELECT sku,entity_id FROM `catalog_product_entity`WHERE`entity_id`NOT IN (SELECT`entity_id`FROM`catalog_product_entity_varchar`WHERE`attribute_id`IN (SELECT attribute_id FROM`eav_attribute`WHERE`attribute_code`='name'))`

This worked great for me. Found 6 products and then ran an import on those products to add a name/Product Name and that sorted the issue.

**Comment by vandijkstef** [comment]
Reconfirming issue on 2.4.4 - Not sure why it has been able to save product entities without a name (title) set (on the base store view) but it happened. This is fully breaking the admin grid functionality, even in production, due to attempted rendering of an aria label. (So high impact for a 'minor' feature).

Fix as per comment https://github.com/magento/magento2/issues/35783#issuecomment-1189348535 is solid. Not sure why this low hanging fruit with high impact is on the low prio backlog. Will slam in a PR in a minute

**Comment by jonathanribas** [comment]
Hi, confirming this issue on `2.4.5` too, we have this issue very often on production too.

**Comment by alitopaloglu** [comment]
I'm pretty sure it's the name attribute because the error message says 

Warning: Undefined array key "name" in vendor/magento/module-catalog/Ui/Component/Listing/Columns/ProductActions.php on line 61

**Comment by rohit-prjpt** [comment]
@alitopaloglu You might have caching issue or try to print the product object to debug on the same file 
vendor/magento/module-catalog/Ui/Component/Listing/Columns/ProductActions.php on line 61
so you'll see which product is causing issues

**Comment by vandijkstef** [comment]
There is a PR up to solve this on the rendering layer, but I have no clue how to move forward from here.

**Comment by asim-blueprintprep** [comment]
This error has also occurred for us when using the native product import - the default amount of errors is set to 10 for some reason, so you can import products with no name.

**Comment by MIANZAHOOR** [comment]
This error occurs when you have imported any product without a name.
You have to remove the error by replacing the following code in the path file.

> /vendor/magento/module-catalog/Ui/Component/Listing/Columns/ProductActions.php

`if (isset($dataSource['data']['items'])) {
            $storeId = $this->context->getFilterParam('store_id');

            foreach ($dataSource['data']['items'] as &$item) {
                if (isset($item['name'])) {
                    $item[$this->getData('name')]['edit'] = [
                        'href' => $this->urlBuilder->getUrl(
                            'catalog/product/edit',
                            ['id' => $item['entity_id'], 'store' => $storeId]
                        ),
                        'ariaLabel' => __('Edit ') . $item['name'],
                        'label' => __('Edit'),
                        'hidden' => false,
                    ];
                } else {
                    $item[$this->getData('name')]['edit'] = [
                        'href' => $this->urlBuilder->getUrl(
                            'catalog/product/edit',
                            ['id' => $item['entity_id'], 'store' => $storeId]
                        ),
                        'label' => __('Edit'),
                        'hidden' => false,
                    ];
                }
            }
        }
`

**Comment by MilenV** [comment]
Hello @MIANZAHOOR, @hgati @malikt and Team,

We observe similar issue on Production where we are on Adobe Commerce ver. *2.4.5-p2*
Actual Exception being thrown refers to Undefined array key "visibility"
`Exception: Warning: Undefined array key "visibility" in /app/vka64lyl5tm4m/vendor/amasty/pgrid/Plugin/Catalog/Ui/DataProvider/Product/ProductDataProvider.php on line 286`

Please could you advise us how this can be troubleshooted and resolved potentially?

Regards,
Milen Velinov

**Comment by rohit-prjpt** [comment]
> Hello @MIANZAHOOR, @hgati @malikt and Team,
> 
> We observe similar issue on Production where we are on Adobe Commerce ver. _2.4.5-p2_ Actual Exception being thrown refers to Undefined array key "visibility" `Exception: Warning: Undefined array key "visibility" in /app/vka64lyl5tm4m/vendor/amasty/pgrid/Plugin/Catalog/Ui/DataProvider/Product/ProductDataProvider.php on line 286`
> 
> Please could you advise us how this can be troubleshooted and resolved potentially?
> 
> Regards, Milen Velinov

You must have NULL values stored for attribute "visibility", so use the following query to find out those products

`SELECT sku,entity_id FROM catalog_product_entity WHERE entity_id NOT IN (SELECT entity_id FROM catalog_product_entity_int WHERE attribute_id IN (SELECT attribute_id FROM eav_attribute WHERE attribute_code='visibility'))`

**Comment by MIANZAHOOR** [comment]
Hi @rohit-prjpt,
Go to ProductDataProvider.php  file and edit the code on line 286.
Here, you have to add check if array key "visibility" is set then execute the code.

**Comment by rohit-prjpt** [comment]
Yes, that is patch in code, instead fix the value in database to fix it with current code,

> Hi @rohit-prjpt, Go to ProductDataProvider.php file and edit the code on line 286. Here, you have to add check if array key "visibility" is set then execute the code.

**Comment by MilenV** [comment]
Hello @rohit-prjpt @MIANZAHOOR @hgati 

We executed suggested query below in the database on Production, but unfortunately returned results were **EMPTY**. 
`SELECT sku,entity_id FROM catalog_product_entity WHERE entity_id NOT IN (SELECT entity_id FROM catalog_product_entity_int WHERE attribute_id IN (SELECT attribute_id FROM eav_attribute WHERE attribute_code='visibility'))`
Do you have any other suggestions you might be able to provide us with?

Can you please give us an idea what we should do with below line of code 286?

> Go to ProductDataProvider.php file and edit the code on line 286.
Here, you have to add check if array key "visibility" is set then execute the code.

Regards,
Milen Velinov

**Comment by rohit-prjpt** [comment]
> Hello @rohit-prjpt @MIANZAHOOR @hgati
> 
> We executed suggested query below in the database on Production, but unfortunately returned results were **EMPTY**. `SELECT sku,entity_id FROM catalog_product_entity WHERE entity_id NOT IN (SELECT entity_id FROM catalog_product_entity_int WHERE attribute_id IN (SELECT attribute_id FROM eav_attribute WHERE attribute_code='visibility'))` Do you have any other suggestions you might be able to provide us with?
> 
> Can you please give us an idea what we should do with below line of code 286?
> 
> > Go to ProductDataProvider.php file and edit the code on line 286.
> > Here, you have to add check if array key "visibility" is set then execute the code.
> 
> Regards, Milen Velinov

@MilenV In that case more detailed debug required, can't guess what is going on without debugging.

**Comment by MilenV** [comment]
Hello @rohit-prjpt 

I am providing you with the whole error we caught.

`Exception: Warning: Undefined array key "visibility" in /app/vka64lyl5tm4m/vendor/amasty/pgrid/Plugin/Catalog/Ui/DataProvider/Product/ProductDataProvider.php on line 286 in /app/vka64lyl5tm4m/vendor/magento/framework/App/ErrorHandler.php:62
Stack trace:
#0 /app/vka64lyl5tm4m/vendor/amasty/pgrid/Plugin/Catalog/Ui/DataProvider/Product/ProductDataProvider.php(286): Magento\Framework\App\ErrorHandler->handler()
#1 /app/vka64lyl5tm4m/vendor/amasty/pgrid/Plugin/Catalog/Ui/DataProvider/Product/ProductDataProvider.php(427): Amasty\Pgrid\Plugin\Catalog\Ui\DataProvider\Product\ProductDataProvider->_initExtra()
#2 /app/vka64lyl5tm4m/vendor/amasty/pgrid/Plugin/Catalog/Ui/DataProvider/Product/ProductDataProvider.php(389): Amasty\Pgrid\Plugin\Catalog\Ui\DataProvider\Product\ProductDataProvider->processExtraColumn()
#3 /app/vka64lyl5tm4m/vendor/magento/framework/Interception/Interceptor.php(146): Amasty\Pgrid\Plugin\Catalog\Ui\DataProvider\Product\ProductDataProvider->afterGetData()
#4 /app/vka64lyl5tm4m/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Ui\DataProvider\Product\ProductDataProvider\Interceptor->Magento\Framework\Interception\{closure}()
#5 /app/vka64lyl5tm4m/generated/code/Magento/Catalog/Ui/DataProvider/Product/ProductDataProvider/Interceptor.php(23): Magento\Catalog\Ui\DataProvider\Product\ProductDataProvider\Interceptor->___callPlugins()
#6 /app/vka64lyl5tm4m/vendor/magento/module-ui/Component/Listing.php(38): Magento\Catalog\Ui\DataProvider\Product\ProductDataProvider\Interceptor->getData()
#7 /app/vka64lyl5tm4m/vendor/magento/framework/View/Element/UiComponent/Context.php(250): Magento\Ui\Component\Listing->getDataSourceData()
#8 /app/vka64lyl5tm4m/vendor/magento/framework/View/Layout/Generic.php(75): Magento\Framework\View\Element\UiComponent\Context->getDataSourceData()
#9 /app/vka64lyl5tm4m/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout\Generic->build()
#10 /app/vka64lyl5tm4m/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Generic\Interceptor->___callParent()
#11 /app/vka64lyl5tm4m/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Generic\Interceptor->Magento\Framework\Interception\{closure}()
#12 /app/vka64lyl5tm4m/generated/code/Magento/Framework/View/Layout/Generic/Interceptor.php(23): Magento\Framework\View\Layout\Generic\Interceptor->___callPlugins()
#13 /app/vka64lyl5tm4m/vendor/magento/framework/View/Layout/Generator/Structure.php(46): Magento\Framework\View\Layout\Generic\Interceptor->build()
#14 /app/vka64lyl5tm4m/vendor/magento/module-ui/TemplateEngine/Xhtml/Result.php(102): Magento\Framework\View\Layout\Generator\Structure->generate()
#15 /app/vka64lyl5tm4m/vendor/magento/module-ui/TemplateEngine/Xhtml/Result.php(124): Magento\Ui\TemplateEngine\Xhtml\Result->appendLayoutConfiguration()
#16 /app/vka64lyl5tm4m/vendor/magento/module-ui/Controller/Adminhtml/Index/Render.php(91): Magento\Ui\TemplateEngine\Xhtml\Result->__toString()
#17 /app/vka64lyl5tm4m/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Ui\Controller\Adminhtml\Index\Render->execute()
#18 /app/vka64lyl5tm4m/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callParent()
#19 /app/vka64lyl5tm4m/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}()
#20 /app/vka64lyl5tm4m/generated/code/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(23): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callPlugins()
#21 /app/vka64lyl5tm4m/vendor/magento/framework/App/Action/Action.php(111): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->execute()
#22 /app/vka64lyl5tm4m/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#23 /app/vka64lyl5tm4m/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#24 /app/vka64lyl5tm4m/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callParent()
#25 /app/vka64lyl5tm4m/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}()
#26 /app/vka64lyl5tm4m/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#27 /app/vka64lyl5tm4m/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}()
#28 /app/vka64lyl5tm4m/generated/code/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(32): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callPlugins()
#29 /app/vka64lyl5tm4m/vendor/magento/framework/App/FrontController.php(245): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->dispatch()
#30 /app/vka64lyl5tm4m/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#31 /app/vka64lyl5tm4m/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#32 /app/vka64lyl5tm4m/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#33 /app/vka64lyl5tm4m/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#34 /app/vka64lyl5tm4m/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#35 /app/vka64lyl5tm4m/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#36 /app/vka64lyl5tm4m/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#37 /app/vka64lyl5tm4m/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#38 /app/vka64lyl5tm4m/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#39 {main}`

I hope this is helpful enough for troubleshooting and narrow down where the issue comes from and how to fix it.

Regards,
Milen Velinov

**Comment by rohit-prjpt** [comment]
@MilenV looking at error log, seems to be error from amasty plugin, try to disable plugin amasty/pgrid and check.

**Comment by MIANZAHOOR** [comment]
Hello @MilenV 
It's a bug of amasty plugin so you have to edit the code in the file ProductDataProvider.php.
Can you share code from 280 line to 295 line?

**Comment by rohit-prjpt** [comment]
> Hello @MilenV It's a bug of amasty plugin so you have to edit the code in the file ProductDataProvider.php. Can you share code from 280 line to 295 line?

@MilenV 
Please find the below line 
`if ((int)$row['visibility'] !== Visibility::VISIBILITY_NOT_VISIBLE) {`

And change it to the following:
`if (isset($row['visibility']) && (int)$row['visibility'] !== Visibility::VISIBILITY_NOT_VISIBLE) {`

Let me know if that works or not!

**Comment by MilenV** [comment]
Hello @rohit-prjpt 

`  274      protected function _initExtra(array &$row, string $column): void
   275      {
   276          if (isset($row['store_id']) && $row['store_id'] !== 0) {
   277              $store = $this->storeManager->getStore($row['store_id']);
   278          } else {
   279              $store = $this->storeManager->getWebsite($row['website_ids'][0] ?? null)->getDefaultStore();
   280          }
   281
   282          switch ($column) {
   283              case 'amasty_link':
   284                  $row[$column] = '';
   285
   286                  if ((int)$row['visibility'] !== Visibility::VISIBILITY_NOT_VISIBLE) {
   287                      if (!empty($row['request_path'])) {
   288                          $row[$column] = $store->getUrl('', ['_direct' => $row['request_path']]);
   289                      } else {
   290                          $row[$column] = $store->getUrl(
   291                              null,
   292                              ['_direct' => 'catalog/product/view/id/' . $row['entity_id']]
   293                          );
   294                      }
   295                      break;
   296                  }
   297          }
   298      }`

**Comment by MilenV** [comment]
Hello @rohit-prjpt 

Below is the part of the code between lines 274 and 298:



 274      protected function _initExtra(array &$row, string $column): void
   275      {
   276          if (isset($row['store_id']) && $row['store_id'] !== 0) {
   277              $store = $this->storeManager->getStore($row['store_id']);
   278          } else {
   279              $store = $this->storeManager->getWebsite($row['website_ids'][0] ?? null)->getDefaultStore();
   280          }
   281
   282          switch ($column) {
   283              case 'amasty_link':
   284                  $row[$column] = '';
   285
   286                  if ((int)$row['visibility'] !== Visibility::VISIBILITY_NOT_VISIBLE) {
   287                      if (!empty($row['request_path'])) {
   288                          $row[$column] = $store->getUrl('', ['_direct' => $row['request_path']]);
   289                      } else {
   290                          $row[$column] = $store->getUrl(
   291                              null,
   292                              ['_direct' => 'catalog/product/view/id/' . $row['entity_id']]
   293                          );
   294                      }
   295                      break;
   296                  }
   297          }
   298      }

Regards,
Milen Velinov

**Comment by rohit-prjpt** [comment]
> > Hello @MilenV It's a bug of amasty plugin so you have to edit the code in the file ProductDataProvider.php. Can you share code from 280 line to 295 line?
> 
> @MilenV Please find the below line `if ((int)$row['visibility'] !== Visibility::VISIBILITY_NOT_VISIBLE) {`
> 
> And change it to the following: `if (isset($row['visibility']) && (int)$row['visibility'] !== Visibility::VISIBILITY_NOT_VISIBLE) {`
> 
> Let me know if that works or not!

change your line 286 as per my reply above

**Comment by MIANZAHOOR** [comment]
@MilenV 

You have to add an additional check in which it will check the "visibility" index is set(available) or not because in you condition it doesn't found "visibility" index for $row array.
so you can do it by replacing 286 line by following line of code.

`if (isset($row['visibility']) && (int)$row['visibility'] !== Visibility::VISIBILITY_NOT_VISIBLE) {`

@rohit-prjpt you are right.

**Comment by mattb-ascend** [comment]
> This error has also occurred for us when using the native product import - the default amount of errors is set to 10 for some reason, so you can import products with no name.

I can reproduce using the import AND including the name field. If I specify `store_view_code` for a newly added product, it seems that the "default" view is what the admin grid uses.

**Comment by rohit-prjpt** [comment]
> > This error has also occurred for us when using the native product import - the default amount of errors is set to 10 for some reason, so you can import products with no name.
> 
> I can reproduce using the import AND including the name field. If I specify `store_view_code` for a newly added product, it seems that the "default" view is what the admin grid uses.

When you import with store_view_code then it must set all values under defined store_view only but when you load the grid page by default it must have ADMIN Default Values but if you have store view filters in place then it must take values from specific store view, 

For this specific issue, you only need to query to fix NULL value in your database, nothing else

**Comment by vakokakokit** [comment]
For Enterprise version .
Query to get product with no name.

`SELECT
	sku,
	entity_id 
FROM
	catalog_product_entity 
WHERE
	row_id NOT IN (
	SELECT
		row_id 
	FROM
		catalog_product_entity_varchar 
WHERE
	attribute_id IN ( SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'name' AND entity_type_id = 4 ))`

**Comment by motomaxinc** [comment]
Hi, I am new to magento and I got the same issue. I have made a website on cloudways auto installation so I am unable to find these steps. But I did find it through another directory and set product searchable vale for name to NO but the issue is still not fixed. Can someone help? Thank you. 

> ### Steps to reproduce
> 1. Login as admin. - OK
> 2. Go to Store->attributes->product search code "name" and set Values Required to "NO"
> 3. Create a product without name in 2.4.1 and then upgrade to 2.4.4 along with PHP.
> 4. Now, create a Product without name after setting the 'Name' attribute as not mandatory.

**Comment by dev-intraweb** [comment]
Hello,
run the query and delete all the products with no name. There's no way they can fix it

**Comment by RiccardoRoscilli** [comment]
Hello,
run the query and delete all the products with no name. There's no way they can fix it

**Comment by motomaxinc** [comment]
Thank you. I did not know how to run a query so I edited the product name in csv file, re-imported the file and it fixed the issue. 

> Hello, run the query and delete all the products with no name. There's no way they can fix it

**Comment by engcom-Delta** [comment]
Hi @malikt ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance and the issue is reproducible.
Kindly refer the screenshots.

**Steps to reproduce**
1. Login as admin.
2. Go to Store->attributes->product search code "name" and set Values Required to "NO"
![image](https://github.com/user-attachments/assets/622d54f5-f7af-4f9f-9072-4343092fb155)
3. Import product with no name.
4. Access Catalog>Products
5. Observe Error displays when product is imported with no name
![image](https://github.com/user-attachments/assets/2aed14f1-0f01-4716-9a26-d1ba56c09793)

Thanks.

**Comment by Kishorchhugani** [comment]
vendor/magento/module-catalog/Ui/Component/Listing/Columns/ProductActions.php

From 
'ariaLabel' => __('Edit ') . $item['name'],
To
'ariaLabel' => __('Edit ') . @$item['name'],

**Comment by ityetti** [comment]
You just could clean your ui_bookmark table for the needed admin customer and your grid will work as you expected.

**Comment by rohit-prjpt** [comment]
> You just could clean your _ui_bookmark_ table for the needed admin customer and your grid will work as you expected.

Yes, sometimes that could be the reason but the main issue could occur when the product "name" field value is blank
