### ISSUE TITLE
Internal Server Error in /V1/products/{sku}/links API Endpoints

### ISSUE THREAD

**Issue by mlf20** [magento/magento2#35923]
### Preconditions and environment

- Magento version 2.4

### Steps to reproduce

1. Retrieve auth token from the admin endpoint /V1/integration/admin/
2. Request PUT endpoint: /rest/default/V1/products/{sku}/links with payload:
_{
  "entity": {
  }
}_

### Expected result

Returns a 400 error as the request is malformed.

### Actual result

Returns a 500 status code as an error is thrown as $sku is a null argument in Magento\Catalog\Model\ProductRepository::getProductFromLocalCache()

### Additional information

output of var/log/system.log:

```
[2022-08-01T11:14:05.418205+00:00] main.CRITICAL: TypeError: Magento\Catalog\Model\ProductRepository::getProductFromLocalCache(): Argument #1 ($sku) must be of type string, null given, called in /magento/vendor/magento/module-catalog/Model/ProductRepository.php on line 284 and defined in /magento/vendor/magento/module-catalog/Model/ProductRepository.php:813
	Stack trace:
	#0 /magento/vendor/magento/module-catalog/Model/ProductRepository.php(284): Magento\Catalog\Model\ProductRepository->getProductFromLocalCache()
	#1 /magento/generated/code/Magento/Catalog/Model/ProductRepository/Interceptor.php(23): Magento\Catalog\Model\ProductRepository->get()
	#2 /magento/vendor/magento/module-catalog/Model/ProductLink/Repository.php(137): Magento\Catalog\Model\ProductRepository\Interceptor->get()
	#3 /magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ProductLink\Repository->save()
	#4 /magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ProductLink\Repository\Interceptor->___callParent()
	#5 /magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ProductLink\Repository\Interceptor->Magento\Framework\Interception\{closure}()
	#6 /magento/generated/code/Magento/Catalog/Model/ProductLink/Repository/Interceptor.php(23): Magento\Catalog\Model\ProductLink\Repository\Interceptor->___callPlugins()
	#7 [internal function]: Magento\Catalog\Model\ProductLink\Repository\Interceptor->save()
	#8 /magento/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()
	#9 /magento/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()
	#10 /magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
	#11 /magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
	#12 /magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
	#13 /magento/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
	#14 /magento/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
	#15 /magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
	#16 /magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
	#17 /magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
	#18 {main} [] []
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible. Hence updating the description and confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/184872299-8b5f1f1a-87b5-4293-a918-534eb0bac247.png)
