### ISSUE TITLE
Cannot set custom filename for \Psr\Log\LoggerInterface

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#36083]
### Preconditions and environment

- 2.4.3-p1

### Steps to reproduce

1. Create a helper class that is used for example on a cli command or a cron job that requires a custom logger filename

```php
use Magento\Catalog\Model\Product\Attribute\Source\Status;
use Magento\Catalog\Model\ResourceModel\Product\CollectionFactory;
use Magento\Framework\App\Area;
use Magento\Framework\App\Filesystem\DirectoryList;
use Magento\Framework\DB\Select;
use Magento\Store\Model\App\Emulation;
use Monolog\Handler\StreamHandler;
use Psr\Log\LoggerInterface;

class Product
{
    protected $collectionFactory;
    protected $directoryList;
    protected $emulation;
    /** @var LoggerInterface */
    protected $logger;
    protected $productResource;

    public function __construct(CollectionFactory                            $collectionFactory,
                                Emulation                                    $emulation,
                                LoggerInterface                              $logger,
                                DirectoryList                                $directoryList,
                                \Magento\Catalog\Model\ResourceModel\Product $productResource)
    {
        $this->directoryList = $directoryList;
        $this->emulation = $emulation;
        $this->collectionFactory = $collectionFactory;
        $this->productResource = $productResource;
        $this->logger = $logger;
        $logger->info("Initializing logger");
        $this->logger->pushHandler(
            new StreamHandler($this->directoryList->getRoot() . '/var/log/ioweb_product_number.log')
        );
    }

    /**
     * @return LoggerInterface
     */
    public function getLogger(): LoggerInterface
    {
        return $this->logger;
    }

}
```

In your cli command or cron job try to invoke this logger 

```php
                $this->productHelper->getLogger()->info(
                    sprintf(
                        "Saving product %s: %s with product number %s",
                        $item->getId(),
                        $item->getSku(),
                        $paddedNumber
                    )
                );
```

You face an exception 

```php
PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Framework\Logger\LoggerProxy::pushHandler() in /httpdocs/app/code/Ioweb/ProductAutomation/Helper/Product.php:41
Stack trace:
#0 /httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Ioweb\ProductAutomation\Helper\Product->__construct()
#1 /httpdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#2 /httpdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#3 /httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#4 /httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#5 /httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\Obje in /httpdocs/app/code/Ioweb/ProductAutomation/Helper/Product.php on line 41
```

By looking at the generated code for the proxy 

```php
<?php
namespace Psr\Log\LoggerInterface;

/**
 * Proxy class for @see \Psr\Log\LoggerInterface
 */
class Proxy implements \Psr\Log\LoggerInterface, \Magento\Framework\ObjectManager\NoninterceptableInterface
{
    /**
     * Object Manager instance
     *
     * @var \Magento\Framework\ObjectManagerInterface
     */
    protected $_objectManager = null;

    /**
     * Proxied instance name
     *
     * @var string
     */
    protected $_instanceName = null;

    /**
     * Proxied instance
     *
     * @var \Psr\Log\LoggerInterface
     */
    protected $_subject = null;

    /**
     * Instance shareability flag
     *
     * @var bool
     */
    protected $_isShared = null;

    /**
     * Proxy constructor
     *
     * @param \Magento\Framework\ObjectManagerInterface $objectManager
     * @param string $instanceName
     * @param bool $shared
     */
    public function __construct(\Magento\Framework\ObjectManagerInterface $objectManager, $instanceName = '\\Psr\\Log\\LoggerInterface', $shared = true)
    {
        $this->_objectManager = $objectManager;
        $this->_instanceName = $instanceName;
        $this->_isShared = $shared;
    }

    /**
     * @return array
     */
    public function __sleep()
    {
        return ['_subject', '_isShared', '_instanceName'];
    }

    /**
     * Retrieve ObjectManager from global scope
     */
    public function __wakeup()
    {
        $this->_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    }

    /**
     * Clone proxied instance
     */
    public function __clone()
    {
        $this->_subject = clone $this->_getSubject();
    }

    /**
     * Get proxied instance
     *
     * @return \Psr\Log\LoggerInterface
     */
    protected function _getSubject()
    {
        if (!$this->_subject) {
            $this->_subject = true === $this->_isShared
                ? $this->_objectManager->get($this->_instanceName)
                : $this->_objectManager->create($this->_instanceName);
        }
        return $this->_subject;
    }

    /**
     * {@inheritdoc}
     */
    public function emergency($message, array $context = [])
    {
        return $this->_getSubject()->emergency($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function alert($message, array $context = [])
    {
        return $this->_getSubject()->alert($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function critical($message, array $context = [])
    {
        return $this->_getSubject()->critical($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function error($message, array $context = [])
    {
        return $this->_getSubject()->error($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function warning($message, array $context = [])
    {
        return $this->_getSubject()->warning($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function notice($message, array $context = [])
    {
        return $this->_getSubject()->notice($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function info($message, array $context = [])
    {
        return $this->_getSubject()->info($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function debug($message, array $context = [])
    {
        return $this->_getSubject()->debug($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function log($level, $message, array $context = [])
    {
        return $this->_getSubject()->log($level, $message, $context);
    }
}
```

I notice that the pushHandler method is not availble. 
However on the actual subject the method is available 

Moreover by checking previous Magento versions like 2.3.2 this was possible because of this preference 

```xml
<preference for="Psr\Log\LoggerInterface" type="Magento\Framework\Logger\Monolog" />
```

Now this has been changed to 

```xml
    <preference for="Psr\Log\LoggerInterface" type="Magento\Framework\Logger\LoggerProxy" />
```

Forcing us to use the proxy thus disabling the ability to set custom filenames for logs 

### Expected result

We can use pushHandler to set the filename for the log. Custom logs are important. 

### Actual result

We can no longer use custom log filenames with Monolog and have to use a workaround by using Zend_Logger

```php
        $writer = new \Zend_Log_Writer_Stream(BP . '/var/log/filename.log');
        $logger = new \Zend_Log();
        $logger->addWriter($writer);
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
Not sure if issue is fully valid.

But in case it helps, we are able to use custom log names like this, which is purely done in a `di.xml` file with 2 `virtualType`'s, [like this](https://github.com/baldwin-agency/magento2-module-image-cleanup/blob/fe0c8a91d826eefe3fdd45bca5f4d2fe024d0513/etc/di.xml#L12-L25).

You then need to [inject your virtual Logger type](https://github.com/baldwin-agency/magento2-module-image-cleanup/blob/fe0c8a91d826eefe3fdd45bca5f4d2fe024d0513/etc/di.xml#L27-L31), into a class that has a dependency on `Psr\Log\LoggerInterface` which then overwrites it (fe [this one over here](https://github.com/baldwin-agency/magento2-module-image-cleanup/blob/fe0c8a91d826eefe3fdd45bca5f4d2fe024d0513/Logger/Logger.php#L14))

**Comment by ioweb-gr** [comment]
True it can also be done via di.xml with virtual types or via custom classes that extend the original Monolog logger class but it's still a workaround imo. We're adding multiple classes in the system just to change a filename in the log. 

Don't you think it's overkill?

**Comment by engcom-Hotel** [comment]
Hello @ioweb-gr,

Thanks for the reporting and collaboration!

We have gone through with the issue description and reviewed the codebase, and found that setting the custom filename is not possible for `\Psr\Log\LoggerInterface`, but possible for `monolog` but it seems an expected behavior of Magento. 

We request you to please go through the below documentation related with it and let us know your views for the same:

https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/logs/custom-log-files.html?lang=en

Thanks

**Comment by ioweb-gr** [comment]
The confusion here is that in the past, the preference was 

`<preference for="Psr\Log\LoggerInterface" type="Magento\Framework\Logger\Monolog" />`

Now this has been changed to

`<preference for="Psr\Log\LoggerInterface" type="Magento\Framework\Logger\LoggerProxy" />`

This is a BC break that's not documented.

**Comment by engcom-Hotel** [comment]
Hello @ioweb-gr,

Thanks for the reply!

I agree that it's not backward compatible. It was updated here in this https://github.com/magento/magento2/commit/28d2a5bf4bd3588dfe6f0d3d0fc2036c6fcc9ef7 commit.

Hence confirming the issue.

Thanks

**Comment by Bashev** [comment]
Issue comes if some of the third-party modules have requirements limited only to version `^1.0` of the `psr/log` module. Correct way is if magento not support it, to define it in the proper way in the composer.json as requirement, not leave this option to the installer.
