### ISSUE TITLE
magento deploy:mode:set production fails with MAMP PRO

### ISSUE THREAD

**Issue by ghost** [magento/magento2#3644]
I'm running a development installation on MAMP PRO and when I'm trying to `deploy:mode:set production` it fails at `setup:static-content:deploy`. When running `setup:static-content:deploy` directly from CLI it succeeds without problems.

Any ideas what might be wrong?

```
$ php bin/magento deploy:mode:set production -vvv
Enabled maintenance mode
Static content deployment start
Command returned non-zero exit code:
`php -f /path/to/magento/bin/magento setup:static-content:deploy fi_FI 2>&1`
#0 /path/to/magento/vendor/magento/module-deploy/Model/Filesystem.php(142): Magento\Framework\Shell->execute('php -f /Users/r...')
#1 /path/to/magento/vendor/magento/module-deploy/Model/Filesystem.php(119): Magento\Deploy\Model\Filesystem->deployStaticContent(Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /path/to/magento/vendor/magento/module-deploy/Model/Mode.php(83): Magento\Deploy\Model\Filesystem->regenerateStatic(Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /path/to/magento/vendor/magento/module-deploy/Console/Command/SetModeCommand.php(100): Magento\Deploy\Model\Mode->enableProductionMode()
#4 /path/to/magento/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Magento\Deploy\Console\Command\SetModeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /path/to/magento/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /path/to/magento/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Deploy\Console\Command\SetModeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /path/to/magento/vendor/magento/framework/Console/Cli.php(49): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /path/to/magento/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /path/to/magento/bin/magento(25): Symfony\Component\Console\Application->run()
#10 {main}
```

**Comment by piotrekkaminski** [comment]
Magento is not compatible with MAMP due to different version requirements. Do you still have this issue in 2.1? if yes, please open a new ticket.
