### ISSUE TITLE
Unable to ship / notify ready for pickup when an MSI pickup order has some items refunded

### ISSUE THREAD

**Issue by ArronKing** [magento/magento2#36783]
### Preconditions and environment

- 2.4.5
- MSI enabled with store pickup

### Steps to reproduce

1. Setup an MSI store - "Warehouse" and "Store" as stock sources
2. Enable "Store" as pickup location
3. Create "Website" stock - "Warehouse" and "Store" as the stock sources, sales channel should be the website
4. Create 2 products, Product A - stock of 10 at "Store", Product B - stock of 10 at "Store"
5. Place an order on the frontend, ordering 10 x Product A and 10 x Product B. Make sure the order is a "pickup" from  "Store"
6. Login as an admin, issue a refund on the order for Product A. And drop it's quantity to 0. (Simulating where  Product A isn't actually in stock, we've only just realised so we'll refund the customer and correct stock level).
7. Try to Ship / "Notify Order is Ready for Pickup"

### Expected result

Order is shipped, customer is notified. Shipment should only contain 10 x Product B as we've refunded Product A.

### Actual result

Admin is told "The order is not ready for pickup" - unable to ship

### Additional information

Exception is thrown from `Magento\InventoryInStorePickupSales\Model\Order:57`

Tracing that back, bug is in `Magento\InventoryInStorePickupSales\Model\Order\IsFulfillable:77`:

`if (!$this->isItemFulfillable($item->getSku(), $sourceCode, (float)$item->getQtyOrdered())) {`

That line checks if there's enough stock to fulfil the items quantity ordered.  That shouldn't be the case, it needs to check on the level it needs to ship.

-------------------
To workaround this issue you need to give Product A enough stock to pass this check.
When the shipment is created, product A isn't on the shipment (which is correct).
Then re-adjust Product A stock level

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by abdel-aouby** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance with extensions magento/inventory

**Comment by engcom-Alfa** [comment]
https://github.com/magento give me 2.4-develop instance with extensions magento/inventory

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance with extensions magento/inventory

**Comment by engcom-Alfa** [comment]
Hi @ArronKing 

Thanks for reporting the ticket.

we are not able to reproduce this issue as retested on the 2.4-develop branch, which is updated amongst all the branches, 

Video Attachment:
https://user-images.githubusercontent.com/51679138/216607702-386d77dc-d999-4ed1-9d29-9e487f2c6c35.mov

**Comment by ArronKing** [comment]
Hi

I've just tested this on the latest develop branch and the bug is still appearing. I've put together some more detailed steps if this helps. Looking at your video - it looks like you've not used the "pickup at store" shipping method. 

1. Create new source "Shop", enable "use as pickup location" for shop
2. Create new source "Warehouse", not enabled for "use pickup as location"
3. Create new stock "UK" - using shop and warehouse as stock sources
4. Edit store config - enable "In store delivery" as a shipping method
5. Edit product 1 - assign sources (shop and warehouse). Add 10 items to Shop stock location
6. Edit product 2 - assign sources (shop and warehouse) . Add 10 items to Shop stock location
7. On front end, place order for 10x product 1 and 10x product 2
8. During checkout, select shop as pickup location and place order
9. In admin - issue an invoice for the full order (this isn't necessary if you're using an instant payment method. But if you're testing with check etc it is required)
10. In admin - issue a credit note for 10x product 1
11. In admin - set product 1 stock at shop to 0
12. In admin - attempt to "Notify Order is Ready for Pickup". 
13. Receive the "The order is not ready for pickup" message, instead of notifying customer the rest of the order can be picked up

I've set up this scenario on the develop instance, order #000000003. Not sure how long the instance lasts however.

Thanks

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance with extensions magento/inventory

**Comment by engcom-Alfa** [comment]
Hey @ArronKing,

Thanks for reporting the ticket with updated information.
As per retesting, the issue is still not reproducible on the 2.4.x-Developer branch. however, I faced an actual error from the issue only once but later found if we refresh the browser then the issue does not reproduce.

Suggestion: kindly check the issue retesting on the in-cognitive browser and if trying on a normal browser then please try by refreshing the page.

**Video Attachment** 
https://user-images.githubusercontent.com/51679138/216988287-3be83e95-6199-49fb-aaf6-7cf2794a307f.mp4

**Comment by ArronKing** [comment]
Hi

Thanks for looking info this and the video - really helpful.

Unfortunately, there's an extra step. After you create the credit memo - you must adjust the product ("product a") you've refunded stock level to 0.

After which the order will not ship, even though it doesn't need to ship "product a". It still checks "product a" stock level meets that of the ordered amount, not the amount it needs to ship.

Hope this helps

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance with extensions magento/inventory

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance with extensions magento/inventory

**Comment by engcom-Alfa** [comment]
Hi @ArronKing 

Thanks for the information. 
As per retesting, the issue has been confirmed on 2.4.x Develop.

**Steps to reproduce**
1. Create a new source "Shop", and enable "use as pickup location" for the shop
2. Create a new source "Warehouse", not enabled for "use pickup as location"
3. Create new stock "UK" - using shop and warehouse as stock sources
4. Edit store config - enable "In-store delivery" as a shipping method
5. Edit product 1 - assign sources (shop and warehouse). Add 10 items to the 'Shop' stock location
6. Edit product 2 - assign sources (shop and warehouse). Add 10 items to the 'Shop' stock location
7. On the front end, place an order for 10x product 1 and 10x product 2
8. During checkout, select shop as the pickup location and place the order
9. In admin - issue an invoice for the full order (this isn't necessary if you're using an instant payment method. But if you're testing with a check or cash, etc it is required)
10. In admin - issue a credit note for 10x product 1 (means, allot the refund for product -1 from the order)
11. In admin - set product 1 stock at the shop to 0 (meaning either make the quantity 0 or set status out of stock in Product Catalog for Product -1)
12. In admin >> Sales >> order >> attempt to click on "Notify Order is Ready for Pickup".
13. Check if the admin user is able to pick up the order with a success message, by step 12 or facing any error message saying "The order is not ready for pickup"

**Expected result**
1. Order should be picked up and a success message should be displayed for the customer to be notified. 
2. Order should be shipped for only product-2 with 10X quantity as ordered 
3. Product-A should be marked as refunded and stock for the same should be updated accordingly as refunded quantity.

**Actual result**
Admin is getting an error message saying  "The order is not ready for pickup" when clicking on the "Notify Order is Ready for Pickup" link to attempt partial shipment

**Attachment**
<img width="1552" alt="Snapshot_issues:36783" src="https://user-images.githubusercontent.com/51679138/217171512-6b9bb40e-fe22-408e-9a62-0aab750c8abf.png">

**Comment by engcom-Bravo** [comment]
Hi @ArronKing,

Thanks for your reporting and collaboration.

We have tried to reproduce the issue in Latest 2.4-develop instance and the issue is still reproducible.Kindly refer the screenshots.


<img width="1436" alt="Image" src="https://github.com/user-attachments/assets/36e2b567-d7ac-47af-81c7-4cd6d6ce1ced" />



Admin is told "The order is not ready for pickup" - unable to ship.

Hence Confirming the issue.


Thanks.

**Comment by hthetiot** [comment]
Here is the stack from the error "The order is not ready for pickup" 

```
[2025-10-07T22:30:44.842767+00:00] main.CRITICAL: Magento\Framework\Exception\LocalizedException: The order is not ready for pickup in /magento/module-inventory-in-store-pickup-sales/Model/Order/CreateShippingDocument.php:57
Stack trace:
#0 /magento/module-inventory-in-store-pickup-sales/Model/NotifyOrdersAreReadyForPickup.php(116): Magento\InventoryInStorePickupSales\Model\Order\CreateShippingDocument->execute(Object(Magento\Sales\Model\Order\Interceptor))
#1 /magento/module-inventory-in-store-pickup-sales-admin-ui/Controller/Adminhtml/Order/NotifyPickup.php(81): Magento\InventoryInStorePickupSales\Model\NotifyOrdersAreReadyForPickup->execute(Array)
#2 /magento/framework/Interception/Interceptor.php(58): Magento\InventoryInStorePickupSalesAdminUi\Controller\Adminhtml\Order\NotifyPickup->execute()
#3 /magento/framework/Interception/Interceptor.php(138): Magento\InventoryInStorePickupSalesAdminUi\Controller\Adminhtml\Order\NotifyPickup\Interceptor->___callParent('execute', Array)
#4 /magento/framework/Interception/Interceptor.php(153): Magento\InventoryInStorePickupSalesAdminUi\Controller\Adminhtml\Order\NotifyPickup\Interceptor->Magento\Framework\Interception\{closure}()
#5 /var/www/html/generated/code/Magento/InventoryInStorePickupSalesAdminUi/Controller/Adminhtml/Order/NotifyPickup/Interceptor.php(23): Magento\InventoryInStorePickupSalesAdminUi\Controller\Adminhtml\Order\NotifyPickup\Interceptor->___callPlugins('execute', Array, Array)
#6 /magento/framework/App/Action/Action.php(111): Magento\InventoryInStorePickupSalesAdminUi\Controller\Adminhtml\Order\NotifyPickup\Interceptor->execute()
#7 /magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /magento/framework/Interception/Interceptor.php(138): Magento\InventoryInStorePickupSalesAdminUi\Controller\Adminhtml\Order\NotifyPickup\Interceptor->___callParent('dispatch', Array)
#10 /magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\InventoryInStorePickupSalesAdminUi\Controller\Adminhtml\Order\NotifyPickup\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\InventoryInStorePickupSalesAdminUi\Controller\Adminhtml\Order\NotifyPickup\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /magento/framework/Interception/Interceptor.php(153): Magento\InventoryInStorePickupSalesAdminUi\Controller\Adminhtml\Order\NotifyPickup\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /var/www/html/generated/code/Magento/InventoryInStorePickupSalesAdminUi/Controller/Adminhtml/Order/NotifyPickup/Interceptor.php(32): Magento\InventoryInStorePickupSalesAdminUi\Controller\Adminhtml\Order\NotifyPickup\Interceptor->___callPlugins('dispatch', Array, Array)
#14 /magento/framework/App/FrontController.php(245): Magento\InventoryInStorePickupSalesAdminUi\Controller\Adminhtml\Order\NotifyPickup\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magento\InventoryInStorePickupSalesAdminUi\Controller\Adminhtml\Order\NotifyPickup\Interceptor), Object(Magento\Framework\App\Request\Http))
#16 /magento/framework/App/FrontController.php(146): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\InventoryInStorePickupSalesAdminUi\Controller\Adminhtml\Order\NotifyPickup\Interceptor))
#17 /magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#19 /magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#21 /magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#23 /magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent('launch', Array)
#24 /graycore/magento2-cors/Plugin/FastLauncher.php(71): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#25 /magento/framework/Interception/Interceptor.php(135): Graycore\Cors\Plugin\FastLauncher->aroundLaunch(Object(Magento\Framework\App\Http\Interceptor), Object(Closure))
#26 /magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#27 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, NULL)
#28 /magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#29 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#30 {main} {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): The order is not ready for pickup at /magento/module-inventory-in-store-pickup-sales/Model/Order/CreateShippingDocument.php:57)"} []
```

**Comment by hthetiot** [comment]
The reason I had this issue was because the assigned stock for the given source to some product in the item was not available in stock anymore.

**Comment by lbajsarowicz** [comment]
InventoryInStorePickupSales lives in the magento/inventory repository, not magento/magento2. Please move this issue there.

cc @hostep
