### ISSUE TITLE
compile error MiBsyntax error, unexpected token "catch"#0

### ISSUE THREAD

**Issue by mramitsingh85** [magento/magento2#36853]
### Preconditions and environment

Magento CLI 2.4.5
PHP 8.1.2-1ubuntu2.10

### Steps to reproduce

Steps to reproduce 
running 
php bin/magento setup:di:compile

### Expected result

compile successfull 

### Actual result

got below error 

Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% < 1 sec 119.0 MiBsyntax error, unexpected token "catch"#0 /var/www/html/magento2/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 /var/www/html/magento2/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists()
#3 /var/www/html/magento2/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#4 /var/www/html/magento2/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
#5 /var/www/html/magento2/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList()
#6 /var/www/html/magento2/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#7 /var/www/html/magento2/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process()
#8 /var/www/html/magento2/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute()

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mramitsingh85** [comment]
Deleted the vendor folder and ran the composer install and update seems fixed it
