### ISSUE TITLE
Added encode diacritics breaks on rp_token

### ISSUE THREAD

**Issue by mischabraam** [magento/magento2#37326]
The change from https://github.com/magento/magento2/pull/36027/files   seems to be not backwards compatible with existing customer data coming from an earlier Magento version. 

This change validates input with transliteration. However, this is done on every value. Also on values which are not transliterable (is that a word?). Anyway... if we use the Magento API to change an existing customer per following REST API, this translit breaks on the existing `rp_token`.

```
PUT https://www.magento.com/rest/all/V1/customers/:id
```

With body to update the customer including the password like per example.

```
{
  "customer": {
    "email": "onno@example.com",
    "Gender": 1,
    "Lastname": "Testing",
    "Store_id": 1,
    "Firstname": "Önno",
    "addresses": [
      {
        "street": [
          "Somewhere street"
        ],
        "Lastname": "Testing",
        "Postcode": "1231 EC",
        "Telephone": "0",
        "firstname": "Önno",
        "Middlename": " ",
        "country_id": "NL",
        "Default_billing": true,
        "Default_shipping": true,
        "custom_attributes": [
          {
            "value": "236",
            "attribute_code": "house_number"
          },
          {
            "value": "D",
            "attribute_code": "house_number_addition"
          }
        ],
        "city": "TEST CITY"
      }
    ],
    "Middlename": " ",
    "Website_id": 1,
    "custom_attributes": [
      {
        "value": null,
        "attribute_code": "sales_representative"
      },
      {
        "value": "5682",
        "attribute_code": "customer_group"
      },
    ],
    "id": 12345
  },
  "password": "passwordChangeLater@11"
}
```

Error in logging.

```
[2023-03-30T13:16:19.193625+00:00] report.CRITICAL: Exception: Notice: iconv(): Detected an incomplete multibyte character in input string in /var/domains/magento.shop/magento2_staging/releases/1680163528/vendor/magento/module-ea
v/Model/Attribute/Data/Text.php on line 190 in /var/domains/magento.shop/magento2_staging/releases/1680163528/vendor/magento/framework/App/ErrorHandler.php:62
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(8, 'iconv(): Detect...', '/var/domains/...', 190)
#1 /var/domains/magento.shop/magento2_staging/releases/1680163528/vendor/magento/module-eav/Model/Attribute/Data/Text.php(190): iconv('UTF-8', 'ASCII//TRANSLIT...', 'b\xA85\xBA:\xA9s\x01p\x83Pn\xA9\xE3\xEF...')
#2 /var/domains/magento.shop/magento2_staging/releases/1680163528/vendor/magento/module-eav/Model/Attribute/Data/Text.php(83): Magento\Eav\Model\Attribute\Data\Text->encodeDiacritics('b\xA85\xBA:\xA9s\x01p\x83Pn\xA9\xE3\xEF...')
```

![Screenshot_2023-03-31_at_11_31_25](https://user-images.githubusercontent.com/19824986/229449241-7f856b69-b288-4d70-bc39-19fa5a6a6d7a.png)

_Originally posted by @mischabraam in https://github.com/magento/magento2/issues/36027#issuecomment-1493867333_

**Comment by jeffyl** [comment]
I've just run into this issue myself. Not even using the API, just trying to edit the customer in the Magento backend will fail. Logs for that:

```
[2023-04-03T20:37:52.428761+00:00] main.CRITICAL: Exception message: Notice: iconv(): Detected an incomplete multibyte character in input string in /home/forge/magento.store/vendor/magento/module-eav/Model/Attribute/Data/Text.php on line 190
Trace: <pre>#1 iconv() called at [vendor/magento/module-eav/Model/Attribute/Data/Text.php:190]
#2 Magento\Eav\Model\Attribute\Data\Text->encodeDiacritics() called at [vendor/magento/module-eav/Model/Attribute/Data/Text.php:83]
#3 Magento\Eav\Model\Attribute\Data\Text->validateValue() called at [vendor/magento/module-eav/Model/Validator/Attribute/Data.php:141]
#4 Magento\Eav\Model\Validator\Attribute\Data->isValid() called at [vendor/magento/framework/Validator/Constraint.php:51]
#5 Magento\Framework\Validator\Constraint->isValid() called at [vendor/magento/framework/Validator.php:61]
#6 Magento\Framework\Validator->isValid() called at [vendor/magento/module-customer/Model/ResourceModel/Customer.php:261]
#7 Magento\Customer\Model\ResourceModel\Customer->_validate() called at [vendor/magento/module-customer/Model/ResourceModel/Customer.php:194]
#8 Magento\Customer\Model\ResourceModel\Customer->_beforeSave() called at [vendor/magento/module-eav/Model/Entity/VersionControl/AbstractEntity.php:90]
#9 Magento\Eav\Model\Entity\VersionControl\AbstractEntity->save() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#10 Magento\Customer\Model\ResourceModel\Customer\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#11 Magento\Customer\Model\ResourceModel\Customer\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-checkout/Model/Plugin/RecollectQuoteOnCustomerGroupChange.php:77]
#12 Magento\Checkout\Model\Plugin\RecollectQuoteOnCustomerGroupChange->aroundSave() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#13 Magento\Customer\Model\ResourceModel\Customer\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#14 Magento\Customer\Model\ResourceModel\Customer\Interceptor->___callPlugins() called at [generated/code/Magento/Customer/Model/ResourceModel/Customer/Interceptor.php:104]
#15 Magento\Customer\Model\ResourceModel\Customer\Interceptor->save() called at [vendor/magento/framework/Model/AbstractModel.php:663]
#16 Magento\Framework\Model\AbstractModel->save() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#17 Magento\Customer\Model\Backend\Customer\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#18 Magento\Customer\Model\Backend\Customer\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#19 Magento\Customer\Model\Backend\Customer\Interceptor->___callPlugins() called at [generated/code/Magento/Customer/Model/Backend/Customer/Interceptor.php:23]
#20 Magento\Customer\Model\Backend\Customer\Interceptor->save() called at [vendor/magento/module-customer/Model/ResourceModel/CustomerRepository.php:257]
#21 Magento\Customer\Model\ResourceModel\CustomerRepository->save() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#22 Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#23 Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-customer/Model/Plugin/CustomerRepository/TransactionWrapper.php:44]
#24 Magento\Customer\Model\Plugin\CustomerRepository\TransactionWrapper->aroundSave() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#25 Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#26 Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->___callPlugins() called at [generated/code/Magento/Customer/Model/ResourceModel/CustomerRepository/Interceptor.php:23]
#27 Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->save() called at [vendor/magento/module-customer/Controller/Adminhtml/Index/Save.php:382]
#28 Magento\Customer\Controller\Adminhtml\Index\Save->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#29 Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#30 Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#31 Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callPlugins() called at [generated/code/Magento/Customer/Controller/Adminhtml/Index/Save/Interceptor.php:23]
#32 Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#33 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:151]
#34 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#35 Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#36 Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:145]
#37 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#38 Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#39 Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->___callPlugins() called at [generated/code/Magento/Customer/Controller/Adminhtml/Index/Save/Interceptor.php:32]
#40 Magento\Customer\Controller\Adminhtml\Index\Save\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#41 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#42 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:147]
#43 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#44 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#45 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#46 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#47 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#48 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#49 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#50 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
```

**Comment by mischabraam** [comment]
[GITHUB-37326_Ignore_secure_attribute_encode_diacritics__v1.composer.patch](https://github.com/magento/magento2/files/11148011/GITHUB-37326_Ignore_secure_attribute_encode_diacritics__v1.composer.patch)

I've created a composer patch for this issue. The patch ignores the `rp_token`. Probably not the way to go for a proper solution, but it resolves the issue for now.

**Comment by cschuler-mocap** [comment]
I was able to make the issue go away by modifying _beforeSave() in Magento\Customer\Model\ResourceModel\Customer.  I just moved this:

        if (!$customer->getData('ignore_validation_flag')) {
            $this->_validate($customer);
        }

so that it is called _after_ the next block:

         if ($customer->getData('rp_token')) {
            $rpToken = $customer->getData('rp_token');
            $customer->setRpToken($this->encryptor->encrypt($rpToken));
        }

That next block sets the token to a serialized string, which isn't going to contain any diacritics, and therefore won't cause any issues when iconv() is called against it.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @mischabraam,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

1.Try to update existing customer using REST Api.

We are able to update successfully using REST Api.

<img width="1057" alt="Screenshot 2023-04-12 at 2 34 42 PM" src="https://user-images.githubusercontent.com/51680745/231412947-6da4aba3-26d5-4c61-87de-78b6df82214a.png">



<img width="1425" alt="Screenshot 2023-04-12 at 2 39 38 PM" src="https://user-images.githubusercontent.com/51680745/231413008-8234d237-21ae-4c76-b620-58328369bba8.png">



<img width="1407" alt="Screenshot 2023-04-12 at 2 40 14 PM" src="https://user-images.githubusercontent.com/51680745/231413038-028b4965-1e30-443a-a84d-396f0e0ba6d4.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by cschuler-mocap** [comment]
Could the failure to reproduce this error be caused by the fact that it seems to only happen on older customers that were converted from Magento V1 to V2?  mischabraam mentioned that he was having this problem with customers that came from earlier versions of Magento, and the customer who brought error this to my attention was an older customer who had been converted from V1.

If I look at the rp_token field on older customers, I see a hex value, which looks something like this:
b62cb2863a181348b584453c9c8d11d2

But on newer customers, the value has been encrypted differently:
0:3:pquLCjwnjqXRPAIrH8yFvgUv8IIknfEy4oN7ysOqFW5n0xJ+qXY+G8Vwdlofa/CHWAoNRCLmpRmT6RxS

Maybe this is what is causing the issue to only affect older customers?

**Comment by mischabraam** [comment]
@cschuler-mocap Yep that is correct. But the customers in my case aren't that old ;), I mean not coming from Magento1. This project started with Magento 2.3.5-p1 and periodically upgraded to the current version 2.4.6. Since we upgraded from 2.4.5-p1 to 2.4.6 we are having these issues. 
So, new customers created with 2.4.6 can be updated using the REST API (or admin grid, see @jeffyl 's comment). But, customers created with 2.4.5-p1 or an older Magento version can NOT be updated.

@engcom-Bravo did you test correct?

- You should install Magento 2.4.5
- Create a customer, and use it (so activate its account, do some stuff like password resets and such, maybe order something... dunno)
- Update the customer using the admin grid or REST API

**Comment by cschuler-mocap** [comment]
I found a consistent way to reproduce this error.

- Manually edit the `rp_token` field on a customer record in `customer_entity` and set it to 'f37ce941d293e34d25e635ee0b0d6f16'
- Edit & Save that same customer in admin.

You should now get the "we can't save the customer" error message

**Comment by MageCloudTeam** [comment]
We have a same issue in our projects!

**Comment by engcom-Bravo** [comment]
Hi @mischabraam,

Thanks for your update.

Verified the issue while upgrading from Magento 2.4.5 to Magento 2.4.6 instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- You should install Magento 2.4.5
- Create a customer, and use it (so activate its account, do some stuff like password resets and such, maybe order something... dunno)
- Upgrade Magento to 2.4.6
- Update the customer using the admin grid or REST API


<img width="1502" alt="Screenshot 2023-04-14 at 3 57 12 PM" src="https://user-images.githubusercontent.com/51680745/232022030-cc34fde3-306d-4b4e-8e18-530e3d8ac1e2.png">




<img width="1109" alt="Screenshot 2023-04-14 at 4 03 05 PM" src="https://user-images.githubusercontent.com/51680745/232022157-c94cd26f-0cdf-4172-8396-917b3524d551.png">




<img width="1483" alt="Screenshot 2023-04-14 at 4 03 55 PM" src="https://user-images.githubusercontent.com/51680745/232022156-ac05a529-431d-4148-9070-04ed6a8a7d98.png">

We are able to update customer successfully.

Kindly let us know if we are missing anything.


Thanks.

**Comment by cschuler-mocap** [comment]
> Verified the issue while upgrading from Magento 2.4.5 to Magento 2.4.6 instance and the issue is not reproducible.

@engcom-Bravo  Did you try setting the rp_token to f37ce941d293e34d25e635ee0b0d6f16?

As I mentioned in a previous comment, the issue here is that the code is calling the validator:

```
    if (!$customer->getData('ignore_validation_flag')) {
        $this->_validate($customer);
    }
```

before calling the function to encrpyt the rp_token:

```
     if ($customer->getData('rp_token')) {
        $rpToken = $customer->getData('rp_token');
        $customer->setRpToken($this->encryptor->encrypt($rpToken));
    }
```

Which means that the validator is is attempting to do a character conversion on raw binary data.  And I think this might be why it is hard to reproduce -- the contents of that binary data are entirely random, and only certain combinations of random bytes cause an issue for the character conversion function.   I had to test a dozen different customer's rp_tokens before I found one that caused the error.

**Comment by engcom-Bravo** [comment]
Hi @cschuler-mocap @mischabraam,

Thanks for your update.

We have tried following steps


- Manually edit the rp_token field on a customer record in customer_entity and set it to 'f37ce941d293e34d25e635ee0b0d6f16'
- Edit & Save that same customer in admin.

We are not able to reproduce the issue.We are able to save and update the customer successfully.


<img width="647" alt="Screenshot 2023-04-20 at 1 17 29 PM" src="https://user-images.githubusercontent.com/51680745/233341065-e6a057cd-9c35-4b53-aa7e-43a15440bb51.png">



<img width="1050" alt="Screenshot 2023-04-20 at 1 18 03 PM" src="https://user-images.githubusercontent.com/51680745/233341120-d00b6455-81e5-4232-8b8b-f4fa25714d98.png">



<img width="1415" alt="Screenshot 2023-04-20 at 1 17 11 PM" src="https://user-images.githubusercontent.com/51680745/233341148-39dcf3c8-eb2a-4406-a9fe-dbd1c5b76858.png">



We have tried with different diacritics to update the customers using PUT method.


Kindly provide exact steps to reproduce the issue It will help us to reproduce the issue.

Thanks.

**Comment by mischabraam** [comment]
I'm working on a test scenario. I have a project where this error is prominent. I'll create some test data in a dump for you.

**Comment by mischabraam** [comment]
Ok, I have a project with this issue. I have not been able to exactly track the resource of the issue. But I have a working DB dump you can use to trace and fix it. 
One side note: this specific project is a Magento Commerce project, so you'll need a license for this. (I've tried to downscale the DB to OpenSource but haven't succeeded in that yet).

Steps to get it working.

- Install Magento Commerce 2.4.6. 
- Replace the created DB with the dump to find below.
- Replace the `config.php` with the one to find below. (Not sure if this is required)
- Run `bin/magento set:up` and `bin/magento inde:rein`. (You'll need a working Elasticsearch instance running on localhost:9200 or change the config)
- Use Postman to GET a customer to verify it's working.
- Use Postman to PUT a change to that customer to see the error.


[magento-commerce.sql.gz](https://github.com/magento/magento2/files/11331638/magento-commerce.sql.gz)

[config.php.zip](https://github.com/magento/magento2/files/11331643/config.php.zip)

https://api.postman.com/collections/371535-4de80353-35ea-458b-8b7a-28e9f3e7e776?access_key=PMAT-01GYYHFGFWDH6E7WN6ZQZSYQGN

**Comment by rsisco** [comment]
We were facing this issue as well. One oddity we faced was that the issue was not reproducible in any other environment (staging or local) using an exact database dump and the same code base.

Out solution was to nullify all `rp_token` and `rp_token_create_at` values in the `customer_entity` table.

**Comment by simonmaass** [comment]
we can confirm this issue - we are facing the exact same problem - using magento 2.4.6!

**Comment by adamstapley** [comment]
Same issue here after updating from 2.4.2 to 2.4.6 [cschuler-mocap] fix worked for us

**Comment by ga3003** [comment]
Hi Everyone, I am also facing the same issue. I was struggling for around 6 hours to find the exact issue, as the admin's customer edit form shows an error related to customer data in the customer-assistance module. But when I debugged further, I found it was because of this "iconv" method. Then, for the time being(as a workaround), I have deleted the rp_token from the customer_entity table so that it should work properly. So if someone wants an urgent fix, you guess can follow this.

But we need a permanent solution for this.

**Comment by Zwernemann** [comment]
Same issue here after updating from 2.4.5 to 2.4.6 (only for one customer with rp_token=qbAzBSoSFbzw7MWpwrprn28d1x2jshXR)

**Comment by HenKun** [comment]
Same issue after updating to 2.4.6. Customers are not from Magento 1, but from Magento before 2.4.6
This issue also prevents Amazon Pay Express payment from succeeding, if the customer already existed before payment. So it is an urgent issue.

**Comment by jonathanribas** [comment]
Same issue here on `2.4.6` with `rp_token` `fvD2CYhnbsC3WkemK3OBYwGE5aSBh64s`.

**Comment by maaarghk** [comment]
hello,

straight off the bat I want to say the "old version" thing is a red herring and I see this with a value in the format `0:3:<base64 string>`.

@magento-engcom-team  / @engcom-Bravo   you are saying you cannot reproduce this issue which demonstrates that you did not first try to understand the bug report. 

(a) the field holds encrypted data which means the tokens that people are giving you will result in different binary data within the customer model depending on value of `crypt/key` - you can't expect the behaviour to be reproduced by simply entering the values provided by users in this issue without also having their crypt/key which they obviously should not be sharing. i'm not surprised by random users posting these values here as they might not be aware of the inner workings of magento, but it's a really basic oversight for someone who works for adobe 

(b) the issue is obviously not going to be reproducible every time since the data being validated are by definition random bytes. not all random byte sequences result in iconv heuristics thinking it is a malformed multibyte sequence rather than random binary data. you would need to be doing password reset more than 10 times and trying to save the customer between each attempt to be guaranteed to reproduce the bug. if you don't understand, [i've provided an 3v4l](https://3v4l.org/WWqEi) which demonstrates the principle 

(c) even considering the above it is conceptually trivial to understand that the "text" validator should not be used on arbitrary binary data such as random keys, it is not necessary to attempt to reproduce the bug to grasp that the core has bad behaviour 

I reckon a dev rather than a tester needs to have a proper look at this. For now the patch in `Text` provided by @mischabraam is sufficient to workaround the bug. But there is a lot more to consider for a proper fix:

* from the perspective of the core, the frontend model of this being `hidden` is essentially a `text` type eav attribute which is not conceptually the same as binary data and shouldn't be using the text validateValue function anyway - it should be encouraged to have a custom model used which overrides this function to return true when there is no possible validation to be made
* `hidden` in general automatically becoming `Text` when the backend_type is `static` is a bit lame anyway, because the type of the column on the entity table could be anything. `failures_num` is a hidden "static" field which is a `smallint` but being validated as if it's text
* iconv can throw an E_NOTICE error but there is no `try/catch` block around the call to the function which is why the error message is opaque - in case of text where there actually is malformed UTF-8 data being provided, it would actually be a useful validation result to say so
* I don't think this transliterate diacritic step is actually necessary because the strlen check uses `mb_strlen` which is appropriate for if the string contains diacritics. However this may be an issue of backwards compatibility being broken for custom input rules which may not use multibyte functions - and I think it's fair enough if you don't expect _the ecosystem_ of third party module providers to properly understand this issue
* In the specific case of rp_token, the transliterate step happens before calling `validateLength` and `validateInputRule` functions. Those functions both check `$attribute->getValidateRules()` before doing anything. In the case of `rp_token`, that is an empty array, so no further processing actually takes place and the validation always returns successful. So there is an opportunity to do an early return here whilst retaining the transliteration function for strings where it is actually required. personally I've patched it like this:

```diff
--- Model/Attribute/Data/Text.php	2023-07-06 14:19:18.505501382 +0100
+++ Model/Attribute/Data/Text.php	2023-07-06 14:11:21.857329218 +0100
@@ -79,6 +79,10 @@
             return $errors;
         }
 
+        if (empty($attribute->getValidateRules())) {
+            return true;
+        }
+
         // if string with diacritics encode it.
         $value = $this->encodeDiacritics($value);
 ```

this is a general performance microimprovement which I think fixes the bug as a side effect, and there still needs to be a more comprehensive investigation into the whole system design here.

cheers,
M

**Comment by maaarghk** [comment]
addendum: Have looked at #36027 which introduced this bug I suggest it should be reverted in next patch release and re-implemented in some other way. I'll write on that PR about that.

**Comment by mobweb** [comment]
Same issue here, happening only to some customers that have been migrated from M1 a long time ago. Error message also tells me this:

_> Notice: iconv(): Detected an incomplete multibyte character in input string in vendor/magento/module-eav/Model/Attribute/Data/Text.php on line 190_

If we look at the data that gets passed to this method we can see that the field in question is "rp_token", and the token looks something like this:

_> %¨°ßkt^4ÔH;¨¡˜hixxAZÒ_

**Comment by sonbuic** [comment]
I think the issue relate with this commit https://github.com/magento/magento2/commit/e0f1e4653fb6f3a6eaf7816a59b21d4a6ae14688
They add encrypt on the token when saving but didn't add migrate for current tokens
For simple, just remove all the tokens or create a migrate for current ones

**Comment by sonbui00** [comment]
I think the issue relate with this commit [e0f1e46](https://github.com/magento/magento2/commit/e0f1e4653fb6f3a6eaf7816a59b21d4a6ae14688)
They add encrypt on the token when saving but didn't add migrate for current tokens
For simple, just remove all the tokens or create a migrate for current ones

**Comment by sonbui00** [comment]
> We are not able to reproduce the issue.We are able to save and update the customer successfully.

@engcom-Bravo you're updating customer (with the token) use API -> can't reproduce the issue
The issue can reproduce if you update token in DB directly (like old token after upgrade), and then go to admin -> customer -> save
Please follow this to reproduce the issue https://github.com/magento/magento2/issues/37326#issuecomment-1507164728

**Comment by jonathanribas** [comment]
Hi @sonbui00, you can use this patch to fix this issue: https://github.com/magento/quality-patches/blob/master/patches/os/ACSD-52133_2.4.6.patch

**Comment by sonbui00** [comment]
@jonathanribas Thank you. The patch should work. But there is another issue, the token is still not encrypted (expect from here https://github.com/magento/magento2/commit/e0f1e4653fb6f3a6eaf7816a59b21d4a6ae14688). So customers can't use the link with the token that was sent before. I think it's better to migrate all token to be encrypted

**Comment by jonathanribas** [comment]
@sonbui00, I see but `rp_token` should have a few days validity for security reasons.

**Comment by sonbuic** [comment]
Thank @jonathanribas . I think we can close this issue

**Comment by sonbui00** [comment]
Thank @jonathanribas . I think we can close this issue

**Comment by engcom-Hotel** [comment]
Hello @maaarghk,

Thanks for the detailed explanation of the issue https://github.com/magento/magento2/issues/37326#issuecomment-1623679106 here!

We have tried multiple values as well as multiple diacritics words in order to reproduce the issue, and tried with multiple password strings as well. But the issue is still unable to reproduce. Also tried to hit the rest API multiple times as mentioned here:

> (b) the issue is obviously not going to be reproducible every time since the data being validated are by definition random bytes. not all random byte sequences result in iconv heuristics thinking it is a malformed multibyte sequence rather than random binary data. you would need to be doing password reset more than 10 times and trying to save the customer between each attempt to be guaranteed to reproduce the bug. if you don't understand, [i've provided an 3v4l](https://3v4l.org/WWqEi) which demonstrates the principle

It seems the issue is reproducible for specific diacritics words or characters. I am keeping this issue on `Needs Update` for more suggestions or activities.

Thanks

**Comment by maaarghk** [comment]
@engcom-Hotel any possibility of getting me access to one of your deployment service app instances to try to come up with something reproducible - don't have much time to set up a stock 2.4 instance myself rn

**Comment by engcom-Hotel** [comment]
Hello @maaarghk,

Thanks for the reply!

You can deploy a test instance via below command:

@magento give me 2.4-develop instance

And also please go through with the below devdocs to deploy the instances;

https://developer.adobe.com/commerce/contributor/guides/code-contributions/#deploy-vanilla-magento-open-source-instance

But in the above instances, you are not able to SSH the server.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @maaarghk,

Have you had a chance to check this comment https://github.com/magento/magento2/issues/37326#issuecomment-1681658296?

Thanks

**Comment by ljr95** [comment]
Hello,
In my case I needed to transfer the ecommerce data to a new clean M2.4.6 install and forgot to update the encryption key in env.php based on the first install.
that fixed the problem.
Good day

**Comment by engcom-Hotel** [comment]
Hello @mischabraam @maaarghk,

As there is no activity on this issue, we assume that the issue has been fixed for you. Hence closing this issue for now. Please feel free to comment here, if you have further information on this issue.

We will be happy to help you.

Thanks

**Comment by andriydeveloper** [comment]
Hello.
I had the same issue after updating from 2.4.3 to 2.4.6
Changing the **crypt** value in env.php solved this issue.

**Comment by PascalBrouwers** [comment]
Can't believe this issue has been closed. @mischabraam can you reopen it?

**Comment by maaarghk** [comment]
@engcom-Hotel  I was on holiday for most of the time, otherwise I'd have commented "oops I was wrong sorry please close". 

@magento give me 2.4-develop instance

**Comment by maaarghk** [comment]
Ah, a workaround was made here: https://github.com/magento/magento2/commit/b2f10630626a162934398e4d8225d08d4f38fa70 which was merged to 2.4-develop here https://github.com/magento/magento2/commit/eb34e3477994257e0601bd1a92a04f92152c1919 on September 1st. So hopefully this will drop in the next release.

It uses the patch suggested in this thread of not calling encode diacritics, unfortunately ignoring the advice where translit shouldn't be called anyway - the appropriate bug fix for #12075 was actually just to remove an override on Symfony\Mailer (from memory) - but that's a discussion for another thread I suppose. For now this is fine closed as it is worked around.

**Comment by HenKun** [comment]
Can confirm https://github.com/magento/magento2/commit/b2f10630626a162934398e4d8225d08d4f38fa70 works so far. I am using it as a patch to 2.4.6-p2

**Comment by ivanenkoaleksei** [comment]
I've also caugth this issue for 'rp_token' = '0:3:6/exwfOKIwyOyTI/A8SOaFhufrY49fPpnmjph7dLcHFh/9WzT94IvqVPX26vVLhY5P+emw==';

**Comment by frostitution** [comment]
Just discovered this issue on Magento EE 2.4.6 while cleaning up some customer records.

**Comment by maaarghk** [comment]
Totally agree with the above, I lost the energy to write a similar comment before because I don't think anyone who works for Adobe will be able to understand it.

TBH I would be surprised if there is not some kind of security bug introduced by the allow_diacritics """feature""" - it means that the email address as seen by the validator is different than the e-mail address which gets stored; and it would allow arbitrary binary bytes to be inserted to the email column so long as they don't throw an error during iconv/translit. It's hard to imagine there is not some kind of CVE that fall out of the back of "we allow binary data in an email column".

But who cares, I'm approaching the point where I'm thinking about becoming abusive on this repo so I get banned and I can tell my clients "I'm literally unable to work with Magento because I am banned from the project by Adobe". Then I will never have to think about it ever again.

**Comment by mfickers** [comment]
The fix from https://github.com/magento/magento2/commit/b2f10630626a162934398e4d8225d08d4f38fa70 doesn't even work for me. I've applied it as a patch to a Magento 2.4.6-p2 and got this error while trying to save a customer via the REST API:
```
 "message": "Warning: Undefined array key \"customer_address\" in /var/www/html/vendor/magento/module-eav/Model/Attribute/Data/Text.php on line 94",
```

There are no `encodeAttributesByTypesList` defined for the type customer_address so this is an illegal array access for entity type customer_address:
```php
if (in_array($attribute->getAttributeCode(), $this->encodeAttributesByTypesList[$attribute->getEntityType()->getEntityTypeCode()])) {
```

**Comment by mischabraam** [comment]
So, this is fixed in a MR to the 2.4-develop branch. Is this released in the latest security patch? Or what release is targeted to?

**Comment by reniraj** [comment]
Is this fix is available in Magento Cloud 2.4.6-p2 ??

**Comment by mfickers** [comment]
The fix has been merged to 2.4-develop only and is neither part of 2.4.7-beta1 nor 2.4.7-beta2. It definitely isn't fixed for 2.4.6-p3 or earlier.

2.4.7-beta3 will be released on March 19, 2024, so I guess this might still get merged into 2.4.7, which will release on April 9, 2024.

**Comment by tuyennn** [comment]
Same issue on current project 2.4.5-p5

**Comment by rhoerr** [comment]
Ran into this with sporadic customer saves on a site recently updated to 2.4.6-p3, also caused by false positives/attempts to convert `rp_token` binary values.

**Comment by wag1j1costa** [comment]
> I was able to make the issue go away by modifying _beforeSave() in Magento\Customer\Model\ResourceModel\Customer. I just moved this:
> 
> ```
>     if (!$customer->getData('ignore_validation_flag')) {
>         $this->_validate($customer);
>     }
> ```
> 
> so that it is called _after_ the next block:
> 
> ```
>      if ($customer->getData('rp_token')) {
>         $rpToken = $customer->getData('rp_token');
>         $customer->setRpToken($this->encryptor->encrypt($rpToken));
>     }
> ```
> 
> That next block sets the token to a serialized string, which isn't going to contain any diacritics, and therefore won't cause any issues when iconv() is called against it.

That solved the issue for me, thanks.

**Comment by danieluniform** [comment]
This issue still exists in Magento 2.4.6-p8 

Why is this issue closed? It's clearly an issue and it was trying to run the encodeDiacritics() on binary output from rp_token. I understand that it is a difficult ticket to reproduce do to the encryption key of the install combination. I think what @engcom-Hotel  should be looking for and confirming, is that rp_token DOES NOT RUN through encodeDiactrics. That logic doesn't make sense and can be easily tested, rather than having to run through edge case binary data. It's faulty in the first place that rp_token runs through encodeDiactrics.

**Comment by rossparachute** [comment]
> I was able to make the issue go away by modifying _beforeSave() in Magento\Customer\Model\ResourceModel\Customer. I just moved this:
> 
> ```
>     if (!$customer->getData('ignore_validation_flag')) {
>         $this->_validate($customer);
>     }
> ```
> 
> so that it is called _after_ the next block:
> 
> ```
>      if ($customer->getData('rp_token')) {
>         $rpToken = $customer->getData('rp_token');
>         $customer->setRpToken($this->encryptor->encrypt($rpToken));
>     }
> ```
> 
> That next block sets the token to a serialized string, which isn't going to contain any diacritics, and therefore won't cause any issues when iconv() is called against it.

This worked perfectly for us, v2.4.6-p10.
