### ISSUE TITLE
Elasticsearch missing info about stock data

### ISSUE THREAD

**Issue by cptX** [magento/magento2#37381]
### Preconditions and environment

- Magento version 2.4.6
- Elasticsuite 2.11.0

### Steps to reproduce

I'm not quite sure what happened but after some SKU and category changes, and maybe some configuration, in my site carousel condition "Only in stock products" (which I think is part of elasticsuite) stopped returning any results. Initially I thought it was an elasticsuite problem so I reported it here https://github.com/Smile-SA/elasticsuite/discussions/2907, but after days of researching I realized that in elasticsearch index the following data was completely missing from every product:
`"stock" : { "is_in_stock" : true, "qty" : 100 }`
so probably Elasticsuite has nothing to do with it.

I also have other test instances (both 2.4.5 and 2.4.6) on the same server and they all work fine and this stock data in the elasticsearch json exists as expected.
So I have no clue what caused the issue and how to fix it. At the moment I cannot use the condition "Only in stock products" (which is part of elasticsuite if I'm not mistaken) and I need it.

Any help would be much appreciated...

### Expected result

In elasticsearch index the data stored for every product should include the `"stock" : { "is_in_stock" : true, "qty" : 100 }` info for every product.

### Actual result

In elasticsearch the data stored for every product are missing `"stock" : { "is_in_stock" : true, "qty" : 100 }` info from every product. This results in 0 products returned for the carousel condition "Only in stock products" , so I cannot filter out the out-of-stock products as this condition is not working at all at the moment.

In the logs I see this:

`main.CRITICAL: InvalidArgumentException: Class does not exist in /var/www/electrons_test_02/vendor/magento/module-rule/Model/ConditionFactory.php:50
Stack trace:
#0 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Rule\Model\ConditionFactory->create()
#1 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Rule\Model\ConditionFactory\Interceptor->___callParent()
#2 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Rule\Model\ConditionFactory\Interceptor->Magento\Framework\Interception\{closure}()
#3 /var/www/electrons_test_02/generated/code/Magento/Rule/Model/ConditionFactory/Interceptor.php(23): Magento\Rule\Model\ConditionFactory\Interceptor->___callPlugins()
#4 /var/www/electrons_test_02/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Combine.php(113): Magento\Rule\Model\ConditionFactory\Interceptor->create()
#5 /var/www/electrons_test_02/vendor/magento/module-rule/Model/AbstractModel.php(320): Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Combine->loadArray()
#6 /var/www/electrons_test_02/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(101): Magento\Rule\Model\AbstractModel->loadPost()
#7 /var/www/electrons_test_02/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(242): Magento\PageBuilder\Model\Catalog\ProductTotals->decodeConditions()
#8 /var/www/electrons_test_02/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(150): Magento\PageBuilder\Model\Catalog\ProductTotals->applyConditionsToCollection()
#9 /var/www/electrons_test_02/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(170): Magento\PageBuilder\Model\Catalog\ProductTotals->getProductCollection()
#10 /var/www/electrons_test_02/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(258): Magento\PageBuilder\Model\Catalog\ProductTotals->getEnabledCount()
#11 /var/www/electrons_test_02/vendor/magento/module-page-builder/Controller/Adminhtml/Form/Element/ProductTotals.php(56): Magento\PageBuilder\Model\Catalog\ProductTotals->getProductTotals()
#12 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(58): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals->execute()
#13 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(138): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callParent()
#14 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->Magento\Framework\Interception\{closure}()
#15 /var/www/electrons_test_02/generated/code/Magento/PageBuilder/Controller/Adminhtml/Form/Element/ProductTotals/Interceptor.php(23): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callPlugins()
#16 /var/www/electrons_test_02/vendor/magento/framework/App/Action/Action.php(111): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->execute()
#17 /var/www/electrons_test_02/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#18 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#19 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(138): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callParent()
#20 /var/www/electrons_test_02/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->Magento\Framework\Interception\{closure}()
#21 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#22 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->Magento\Framework\Interception\{closure}()
#23 /var/www/electrons_test_02/generated/code/Magento/PageBuilder/Controller/Adminhtml/Form/Element/ProductTotals/Interceptor.php(32): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callPlugins()
#24 /var/www/electrons_test_02/vendor/magento/framework/App/FrontController.php(245): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->dispatch()
#25 /var/www/electrons_test_02/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#26 /var/www/electrons_test_02/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#27 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#28 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#29 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#30 /var/www/electrons_test_02/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#31 /var/www/electrons_test_02/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#32 /var/www/electrons_test_02/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#33 /var/www/electrons_test_02/pub/index.php(30): Magento\Framework\App\Bootstrap->run()`

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by cptX** [comment]
I'm raising Severity to S0, as I'm researching a whole week for a workaround without success...

**Comment by cptX** [comment]
I also found an older log which is slightly different than the above

`[2023-03-13T20:29:55.887950+00:00] main.CRITICAL: InvalidArgumentException: Class does not exist in /var/www/electrons_test_02/vendor/magento/module-rule/Model/ConditionFactory.php:50
Stack trace:
#0 /var/www/electrons_test_02/vendor/magento/module-rule/Model/Condition/Combine.php(243): Magento\Rule\Model\ConditionFactory->create()
#1 /var/www/electrons_test_02/vendor/magento/module-rule/Model/AbstractModel.php(320): Magento\Rule\Model\Condition\Combine->loadArray()
#2 /var/www/electrons_test_02/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(101): Magento\Rule\Model\AbstractModel->loadPost()
#3 /var/www/electrons_test_02/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(242): Magento\PageBuilder\Model\Catalog\ProductTotals->decodeConditions()
#4 /var/www/electrons_test_02/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(150): Magento\PageBuilder\Model\Catalog\ProductTotals->applyConditionsToCollection()
#5 /var/www/electrons_test_02/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(170): Magento\PageBuilder\Model\Catalog\ProductTotals->getProductCollection()
#6 /var/www/electrons_test_02/vendor/magento/module-page-builder/Model/Catalog/ProductTotals.php(258): Magento\PageBuilder\Model\Catalog\ProductTotals->getEnabledCount()
#7 /var/www/electrons_test_02/vendor/magento/module-page-builder/Controller/Adminhtml/Form/Element/ProductTotals.php(56): Magento\PageBuilder\Model\Catalog\ProductTotals->getProductTotals()
#8 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(58): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals->execute()
#9 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(138): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callParent()
#10 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->Magento\Framework\Interception\{closure}()
#11 /var/www/electrons_test_02/generated/code/Magento/PageBuilder/Controller/Adminhtml/Form/Element/ProductTotals/Interceptor.php(23): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callPlugins()
#12 /var/www/electrons_test_02/vendor/magento/framework/App/Action/Action.php(111): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->execute()
#13 /var/www/electrons_test_02/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#14 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#15 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(138): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callParent()
#16 /var/www/electrons_test_02/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->Magento\Framework\Interception\{closure}()
#17 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#18 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->Magento\Framework\Interception\{closure}()
#19 /var/www/electrons_test_02/generated/code/Magento/PageBuilder/Controller/Adminhtml/Form/Element/ProductTotals/Interceptor.php(32): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->___callPlugins()
#20 /var/www/electrons_test_02/vendor/magento/framework/App/FrontController.php(245): Magento\PageBuilder\Controller\Adminhtml\Form\Element\ProductTotals\Interceptor->dispatch()
#21 /var/www/electrons_test_02/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#22 /var/www/electrons_test_02/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#23 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#24 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#25 /var/www/electrons_test_02/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#26 /var/www/electrons_test_02/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#27 /var/www/electrons_test_02/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#28 /var/www/electrons_test_02/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#29 /var/www/electrons_test_02/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#30 {main} [] []`

**Comment by cptX** [comment]
False alarm. The issue was that I have copied some databases in order to make test copies of my website and in the views in the database there were references to the other databases not the current ones

I'm closing this now!
