### ISSUE TITLE
Deprecated Functionality: Creation of dynamic property Magento\Framework\Acl::$_roleRegistry

### ISSUE THREAD

**Issue by gladroger** [magento/magento2#37469]
### Preconditions and environment

After updating Magento CE from 2.4.5-p1 to 2.4.6, cant enter admin panel anymore.

Found the same error mentioned here: https://magento.stackexchange.com/questions/366673/deprecated-functionality-error-in-sessionmanager-php-on-line-186-after-update-to

PHP 8.2.5 on Centos 7 

- Magento version 2.4.6
`- 1 exception(s):
Exception #0 (Exception): Deprecated Functionality: Creation of dynamic property Magento\Framework\Acl::$_roleRegistry is deprecated in vendor/magento/framework/Session/SessionManager.php on line 186

Exception #0 (Exception): Deprecated Functionality: Creation of dynamic property Magento\Framework\Acl::$_roleRegistry is deprecated in vendor/magento/framework/Session/SessionManager.php on line 186
<pre>#1 session_start() called at [vendor/magento/framework/Session/SessionManager.php:186]
#2 Magento\Framework\Session\SessionManager->start() called at [generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php:32]
#3 Magento\Backend\Model\Auth\Session\Interceptor->start() called at [vendor/magento/framework/Session/SessionManager.php:123]
#4 Magento\Framework\Session\SessionManager->__construct() called at [vendor/magento/module-backend/Model/Auth/Session.php:104]
#5 Magento\Backend\Model\Auth\Session->__construct() called at [generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php:14]
#6 Magento\Backend\Model\Auth\Session\Interceptor->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#7 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#8 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#9 Magento\Framework\ObjectManager\Factory\Compiled->get() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:79]
#10 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#11 Magento\Framework\ObjectManager\Factory\Compiled->get() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:79]
#12 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#13 Magento\Framework\ObjectManager\Factory\Compiled->get() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:125]
#14 Magento\Framework\ObjectManager\Factory\Compiled->parseArray() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:86]
#15 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#16 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/App/FrontController.php:109]
#17 Magento\Framework\App\FrontController->__construct() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:14]
#18 Magento\Framework\App\FrontController\Interceptor->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#19 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#20 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:70]
#21 Magento\Framework\ObjectManager\ObjectManager->get() called at [vendor/magento/framework/App/Http.php:115]
#22 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#23 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#24 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>`

### Steps to reproduce

1. Open admin panel after upgrade

### Expected result

Get into admin

### Actual result

Error. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gladroger** [comment]
I have also solved it temporary by editing SessionManager.php

//                if (isset($_SESSION['destroyed'])
//                    && $_SESSION['destroyed'] < time() - $this->sessionConfig->getCookieLifetime()
//                ) {
//                    $this->destroy(['clear_storage' => true]);
//                }

                if (isset($_SESSION['destroyed'])
                    && $_SESSION['destroyed'] < time() - $this->sessionConfig->getCookieLifetime()
                ) {
                    $this->destroy(['clear_storage' => true]);
                } elseif (!isset($this->_roleRegistry)) {
                    $this->_roleRegistry = null;
                }

**Comment by yohangwak** [comment]
@gladroger Thanks for this!

After I apply your solution, I get other error on front-end and admin

main.CRITICAL: Exception: Deprecated Functionality: Creation of dynamic property Magento\Framework\Session\Generic\Interceptor::$_roleRegistry is deprecated in vendor/magento/framework/Session/SessionManager.php on line 198 in vendor/magento/framework/App/ErrorHandler.php:62
Stack trace:
#0 vendor/magento/framework/Session/SessionManager.php(198): Magento\Framework\App\ErrorHandler->handler()
#1 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\Session\SessionManager->start()
#2 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Session\Generic\Interceptor->___callParent()
#3 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\Session\Generic\Interceptor->Magento\Framework\Interception{closure}()
#4 generated/code/Magento/Framework/Session/Generic/Interceptor.php(41): Magento\Framework\Session\Generic\Interceptor->___callPlugins()
#5 vendor/magento/framework/Session/SessionManager.php(123): Magento\Framework\Session\Generic\Interceptor->start()
#6 generated/code/Magento/Framework/Session/Generic/Interceptor.php(14): Magento\Framework\Session\SessionManager->__construct()
#7 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\Session\Generic\Interceptor->__construct()
#8 vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#9 vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create()
#10 vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get()
#11 vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create()
#12 vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get()
#13 vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create()
#14 vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get()
#15 vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create()
#16 vendor/magento/framework/ObjectManager/Factory/Compiled.php(125): Magento\Framework\ObjectManager\Factory\Compiled->get()
#17 vendor/magento/framework/ObjectManager/Factory/Compiled.php(86): Magento\Framework\ObjectManager\Factory\Compiled->parseArray()
#18 vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Compiled->create()
#19 vendor/magento/framework/App/FrontController.php(109): Magento\Framework\ObjectManager\ObjectManager->get()
#20 generated/code/Magento/Framework/App/FrontController/Interceptor.php(14): Magento\Framework\App\FrontController->__construct()
#21 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\App\FrontController\Interceptor->__construct()
#22 vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#23 vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Compiled->create()
#24 vendor/magento/framework/App/Http.php(115): Magento\Framework\ObjectManager\ObjectManager->get()
#25 generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#26 vendor/magento/framework/App/Bootstrap.php

**Comment by gladroger** [comment]
@yohangwak

I was in a hurry to get live again so I also changed the error reporting setting. I had lots of small problems during the day but some where due to 3rd party modules. 

app/bootstrap.php
`error_reporting(E_ALL & ~E_DEPRECATED & ~E_STRICT);`

**Comment by gladroger** [comment]
What php version are you using when testing?

**Comment by engcom-Bravo** [comment]
Hi @gladroger,

Thanks for your update.

We are using php 8.1.

<img width="686" alt="Screenshot 2023-05-11 at 12 36 14 PM" src="https://github.com/magento/magento2/assets/51680745/9899322e-2bee-41eb-8f31-be9371ad6f26">


Thanks.

**Comment by yohangwak** [comment]
> Hi @gladroger,
> 
> Thanks for your update.
> 
> We are using php 8.1.
> 
> <img alt="Screenshot 2023-05-11 at 12 36 14 PM" width="686" src="https://user-images.githubusercontent.com/51680745/237601020-9899322e-2bee-41eb-8f31-be9371ad6f26.png">
> Thanks.

Can you try with php 8.2? I get error with php 8.2

**Comment by engcom-Bravo** [comment]
Hi @gladroger,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by minhluan259** [comment]
@gladroger  I have similar issue with v2.4.7-beta1

I fixed it by adding:
`public $roleRegistry;`
to
vendor/magento/framework/Acl.php:34

**Comment by domeglic** [comment]
I had the same problem while updating from 2.4.5 to 2.4.6. I think it happens if you have an admin session and then update, because after clearing the sessions I didn't have this problem. That class must somehow be serialized in the session with the old variable name _roleRegistry which got renamed.

**Comment by arunkumar2687** [comment]
I see the same on Upgrading from Adobe Commerce Cloud 2.4.3-p1 to 2.4.6-p4

report.CRITICAL: Exception: Deprecated Functionality: Creation of dynamic property Magento\Framework\Session\Generic\Interceptor::$_roleRegistry is deprecated in /app//vendor/magento/framework/Session/SessionManager.php on line 197 in /app//vendor/magento/framework/App/ErrorHandler.php:62

**Comment by cbradleyacadaca** [comment]
Issue is caused by existing admin session. All you need to do is clear browser cookies and I also ran this MySQL script: `delete from admin_user_session;`

**Comment by engcom-Hotel** [comment]
Hello @gladroger,

Thanks for reporting the issue!

The issue is reproducible for us, we are getting the error after upgrading Magento to 2.4.7-p1. 

@cbradleyacadaca Thanks for the resolution. 

Confirming this issue for further processing.

Thanks

**Comment by santibm** [comment]
> Issue is caused by existing admin session. All you need to do is clear browser cookies and I also ran this MySQL script: `delete from admin_user_session;`

And after that, maybe you might need to clear the browser cookies/cache
