### ISSUE TITLE
HTML Escaper Issue

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#37693]
### Preconditions and environment

- Magento version 2.4.6-p1

### Steps to reproduce

1. Edit a theme template (header.phtml for instance)
2. Add this line somewhere : `<?= $escaper->escapeHtml('Speed < 10m/s', ['b']); ?>`

### Expected result

Displays `Speed < 10m/s`

### Actual result

Displays `Speed`.

Generates exception : 

```
main.CRITICAL: InvalidArgumentException: DOMDocument::loadHTML(): htmlParseStartTag: invalid element name in Entity, line: 1 in /var/www/html/vendor/magento/framework/Escaper.php:96
Stack trace:
#0 [internal function]: Magento\Framework\Escaper->Magento\Framework\{closure}(2, 'DOMDocument::lo...', '/var/www/html/v...', 108)
#1 /var/www/html/vendor/magento/framework/Escaper.php(108): DOMDocument->loadHTML('<html><body id=...')
#2 /var/www/html/app/design/frontend/Namespace/theme/Magento_Theme/templates/html/header.phtml(69): Magento\Framework\Escaper->escapeHtml('Speed < 10m/s', Array)
#3 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/a...')
```

### Additional information

It only fails when there is html tags exception : `<?= $escaper->escapeHtml('Speed < 10m/s'); ?>` works correctly.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jerro9** [comment]
If you're encountering an issue with HTML escaping, it typically means that certain characters in your HTML code are being displayed as their corresponding HTML entities instead of rendering as intended. To address this issue, you can follow these steps:

Identify the characters causing the problem: Take note of the specific characters or symbols that are not rendering correctly. Common examples include "<" (less than), ">" (greater than), "&" (ampersand), and quotation marks.

Use HTML escape sequences or entities: Replace the problematic characters with their respective HTML escape sequences or entities. For example, "<" can be replaced with "<", ">" with ">", "&" with "&", and quotation marks with """ for double quotes or "'" for single quotes.

Check for unintended HTML encoding: Ensure that your HTML code is not already encoded or escaped unnecessarily. For instance, if you have text that includes "<p>", it might appear on the page [best linear switches](https://clickyboard.com/10-akko-linear-switches/) as "<p>" instead of rendering as a paragraph tag. In such cases, remove the unnecessary HTML encoding to allow the code to render correctly.

**Comment by engcom-Hotel** [comment]
Hello @Nuranto,

Thanks for the report and collaboration!

We have tried to reproduce the issue with the mentioned steps in the main description in the 2.4-develop branch and the issue is reproducible for us.

Please have a look at the below screenshot for reference:

![image](https://github.com/magento/magento2/assets/51681618/e2378cd4-8fd7-41c0-bd31-8b427e4e75a5)

Hence confirming the issue.

Thanks

**Comment by ihor-sviziev** [comment]
@Nuranto, I think for HTML you should use html symbol `&#60;` which is HTML equivalent for `<`

**Comment by Nuranto** [comment]
I simplified the case to reproduce, but actually the content with `<` comes from a product attribute filled by admin users.
Also, if it works without tag exceptions, it should works also with exceptions.
But maybe that's a solution : html encode in escapeHtml if the `DOMDocument::loadHTML()` fails !
