### ISSUE TITLE
report.CRITICAL: TypeError on Login as Customer

### ISSUE THREAD

**Issue by lfluvisotto** [magento/magento2#37723]
### Preconditions and environment

- Adobe Commerce ver. 2.4.5-p3

### Steps to reproduce

1. Customers > All customers > Select any customer
2. Click on login as customer

### Expected result

Login as customer selected.

### Actual result

```
[2023-07-05T21:34:34.018540+00:00] report.CRITICAL: TypeError: Magento\LoginAsCustomer\Model\AuthenticateCustomerBySecret\Interceptor::execute(): Argument #1 ($secret) must be of type string, null given, called in /app/4ebxve7ph74no/vendor/magento/module-login-as-customer-frontend-ui/Controller/Login/Index.php on line 113 and defined in /app/4ebxve7ph74no/generated/code/Magento/LoginAsCustomer/Model/AuthenticateCustomerBySecret/Interceptor.php:20
Stack trace:
#0 /app/4ebxve7ph74no/vendor/magento/module-login-as-customer-frontend-ui/Controller/Login/Index.php(113): Magento\LoginAsCustomer\Model\AuthenticateCustomerBySecret\Interceptor->execute(NULL)
#1 /app/4ebxve7ph74no/vendor/magento/framework/Interception/Interceptor.php(58): Magento\LoginAsCustomerFrontendUi\Controller\Login\Index->execute()
#2 /app/4ebxve7ph74no/vendor/magento/framework/Interception/Interceptor.php(138): Magento\LoginAsCustomerFrontendUi\Controller\Login\Index\Interceptor->___callParent('execute', Array)
#3 /app/4ebxve7ph74no/vendor/magento/framework/Interception/Interceptor.php(153): Magento\LoginAsCustomerFrontendUi\Controller\Login\Index\Interceptor->Magento\Framework\Interception\{closure}()
#4 /app/4ebxve7ph74no/generated/code/Magento/LoginAsCustomerFrontendUi/Controller/Login/Index/Interceptor.php(23): Magento\LoginAsCustomerFrontendUi\Controller\Login\Index\Interceptor->___callPlugins('execute', Array, Array)
#5 /app/4ebxve7ph74no/vendor/magento/framework/App/FrontController.php(248): Magento\LoginAsCustomerFrontendUi\Controller\Login\Index\Interceptor->execute()
#6 /app/4ebxve7ph74no/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magento\LoginAsCustomerFrontendUi\Controller\Login\Index\Interceptor), Object(Magento\Framework\App\Request\Http))
#7 /app/4ebxve7ph74no/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\LoginAsCustomerFrontendUi\Controller\Login\Index\Interceptor))
#8 /app/4ebxve7ph74no/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /app/4ebxve7ph74no/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#10 /app/4ebxve7ph74no/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /app/4ebxve7ph74no/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /app/4ebxve7ph74no/vendor/fastly/magento2/Model/FrontControllerPlugin.php(135): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /app/4ebxve7ph74no/vendor/magento/framework/Interception/Interceptor.php(135): Fastly\Cdn\Model\FrontControllerPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /app/4ebxve7ph74no/vendor/amasty/aminvisiblecaptcha/Plugin/Framework/App/FrontControllerInterface/ValidateCaptcha.php(124): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /app/4ebxve7ph74no/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\InvisibleCaptcha\Plugin\Framework\App\FrontControllerInterface\ValidateCaptcha->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /app/4ebxve7ph74no/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /app/4ebxve7ph74no/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /app/4ebxve7ph74no/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#19 /app/4ebxve7ph74no/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#20 /app/4ebxve7ph74no/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /app/4ebxve7ph74no/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#22 /app/4ebxve7ph74no/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#23 {main} [] []
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @lfluvisotto,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance with EE edition and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**


- Customers > All customers > Select any customer
- Click on login as customer




https://github.com/magento/magento2/assets/51680745/a591172a-8624-43c2-a787-03f0364b8364



We are able to click login as customer and customer is able to login successfully.


Kindly recheck the behaviour on Magento 2.4-develop instance with EE edition. and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by lfluvisotto** [comment]
@engcom-Bravo https://github.com/magento/magento2/pull/37729

**Comment by engcom-Bravo** [comment]
Hi @lfluvisotto,

Thanks for your update.

As per this comment https://github.com/magento/magento2/issues/37723#issuecomment-1623171974 issue is not reproducible in Magento 2.4-develop instance could please provide update and elaborate the steps to reproduce if we are missing anything.

Kindly recheck the behaviour on Magento 2.4-develop instance with EE edition. and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @lfluvisotto,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by engcom-Lima** [comment]
@magento give me 2.4.5 instance

**Comment by lfluvisotto** [comment]
@engcom-Bravo, @engcom-Lima 
PR > https://github.com/magento/magento2/pull/37729
