### ISSUE TITLE
Error: Call to a member function getCustomer() on null on Login as Customer Logging

### ISSUE THREAD

**Issue by lfluvisotto** [magento/magento2#37737]
### Preconditions and environment

- Adobe Commerce 2.4.5-p3

### Steps to reproduce

1. Login as any customer on admin
2. After logged in
3. Logout typing the URL https://your_hostname/customer/account/logout on browser and pressing enter.

### Expected result

Logout without Error: Call to a member function getCustomer() on null

### Actual result

```
Error: Call to a member function getCustomer() on null in /var/www/html/vendor/magento/module-login-as-customer-logging/Observer/LogUpdateQtyObserver.php:88
Stack trace:
#0 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\LoginAsCustomerLogging\Observer\LogUpdateQtyObserver->execute(Object(Magento\Framework\Event\Observer))
#1 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\LoginAsCustomerLogging\Observer\LogUpdateQtyObserver), Object(Magento\Framework\Event\Observer))
#2 /var/www/html/vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#3 /var/www/html/generated/code/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch('sales_quote_ite...', Array)
#4 /var/www/html/vendor/magento/module-quote/Model/Quote/Item.php(368): Magento\Staging\Model\Event\Manager\Proxy->dispatch('sales_quote_ite...', Array)
#5 /var/www/html/vendor/magento/module-multishipping/Plugin/MultishippingQuoteRepository.php(152): Magento\Quote\Model\Quote\Item->setQty(2.0)
#6 /var/www/html/vendor/magento/module-multishipping/Plugin/MultishippingQuoteRepository.php(116): Magento\Multishipping\Plugin\MultishippingQuoteRepository->getQuoteItems(Object(Magento\Quote\Model\Quote\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#7 /var/www/html/vendor/magento/module-multishipping/Plugin/MultishippingQuoteRepository.php(56): Magento\Multishipping\Plugin\MultishippingQuoteRepository->processQuote(Object(Magento\Quote\Model\Quote\Interceptor))
#8 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Multishipping\Plugin\MultishippingQuoteRepository->afterGet(Object(Magento\Quote\Model\QuoteRepository\Interceptor), Object(Magento\Quote\Model\Quote\Interceptor), '1146', Array)
#9 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteRepository\Interceptor->Magento\Framework\Interception\{closure}('1146', Array)
#10 /var/www/html/generated/code/Magento/Quote/Model/QuoteRepository/Interceptor.php(23): Magento\Quote\Model\QuoteRepository\Interceptor->___callPlugins('get', Array, Array)
#11 /var/www/html/vendor/magento/module-quote/Model/QuoteRepository.php(168): Magento\Quote\Model\QuoteRepository\Interceptor->get('1146', Array)
#12 /var/www/html/generated/code/Magento/Quote/Model/QuoteRepository/Interceptor.php(41): Magento\Quote\Model\QuoteRepository->getActive('1146', Array)
#13 /var/www/html/vendor/magento/module-checkout/Model/Session.php(250): Magento\Quote\Model\QuoteRepository\Interceptor->getActive('1146')
#14 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\Session->getQuote()
#15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\Session\Interceptor->___callParent('getQuote', Array)
#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\Session\Interceptor->Magento\Framework\Interception\{closure}()
#17 /var/www/html/generated/code/Magento/Checkout/Model/Session/Interceptor.php(50): Magento\Checkout\Model\Session\Interceptor->___callPlugins('getQuote', Array, Array)
#18 /var/www/html/vendor/magento/module-checkout/Model/Session.php(476): Magento\Checkout\Model\Session\Interceptor->getQuote()
#19 /var/www/html/generated/code/Magento/Checkout/Model/Session/Interceptor.php(104): Magento\Checkout\Model\Session->clearQuote()
#20 /var/www/html/vendor/magento/module-checkout/Observer/UnsetAllObserver.php(33): Magento\Checkout\Model\Session\Interceptor->clearQuote()
#21 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Checkout\Observer\UnsetAllObserver->execute(Object(Magento\Framework\Event\Observer))
#22 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Checkout\Observer\UnsetAllObserver), Object(Magento\Framework\Event\Observer))
#23 /var/www/html/vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#24 /var/www/html/generated/code/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch('customer_logout', Array)
#25 /var/www/html/vendor/magento/module-customer/Model/Session.php(490): Magento\Staging\Model\Event\Manager\Proxy->dispatch('customer_logout', Array)
#26 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Model\Session->logout()
#27 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Model\Session\Interceptor->___callParent('logout', Array)
#28 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Model\Session\Interceptor->Magento\Framework\Interception\{closure}()
#29 /var/www/html/generated/code/Magento/Customer/Model/Session/Interceptor.php(185): Magento\Customer\Model\Session\Interceptor->___callPlugins('logout', Array, Array)
#30 /var/www/html/vendor/magento/module-customer/Controller/Account/Logout.php(88): Magento\Customer\Model\Session\Interceptor->logout()
#31 /var/www/html/vendor/sixtomartin/onelogin-module-saml2/Controller/Account/Logout.php(63): Magento\Customer\Controller\Account\Logout->execute()
#32 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Pitbulk\SAML2\Controller\Account\Logout->execute()
#33 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Pitbulk\SAML2\Controller\Account\Logout\Interceptor->___callParent('execute', Array)
#34 /var/www/html/vendor/magento/module-login-as-customer-logging/Plugin/LogCustomerAccountLogoutPlugin.php(98): Pitbulk\SAML2\Controller\Account\Logout\Interceptor->Magento\Framework\Interception\{closure}()
#35 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\LoginAsCustomerLogging\Plugin\LogCustomerAccountLogoutPlugin->aroundExecute(Object(Pitbulk\SAML2\Controller\Account\Logout\Interceptor), Object(Closure))
#36 /var/www/html/vendor/magento/module-customer/Controller/Plugin/Account.php(64): Pitbulk\SAML2\Controller\Account\Logout\Interceptor->Magento\Framework\Interception\{closure}()
#37 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Customer\Controller\Plugin\Account->aroundExecute(Object(Pitbulk\SAML2\Controller\Account\Logout\Interceptor), Object(Closure))
#38 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Pitbulk\SAML2\Controller\Account\Logout\Interceptor->Magento\Framework\Interception\{closure}()
#39 /var/www/html/generated/code/Pitbulk/SAML2/Controller/Account/Logout/Interceptor.php(23): Pitbulk\SAML2\Controller\Account\Logout\Interceptor->___callPlugins('execute', Array, Array)
#40 /var/www/html/vendor/magento/framework/App/Action/Action.php(111): Pitbulk\SAML2\Controller\Account\Logout\Interceptor->execute()
#41 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#42 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Pitbulk\SAML2\Controller\Account\Logout\Interceptor->___callParent('dispatch', Array)
#43 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Pitbulk\SAML2\Controller\Account\Logout\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#44 /var/www/html/generated/code/Pitbulk/SAML2/Controller/Account/Logout/Interceptor.php(32): Pitbulk\SAML2\Controller\Account\Logout\Interceptor->___callPlugins('dispatch', Array, Array)
#45 /var/www/html/vendor/magento/framework/App/FrontController.php(245): Pitbulk\SAML2\Controller\Account\Logout\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#46 /var/www/html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Pitbulk\SAML2\Controller\Account\Logout\Interceptor), Object(Magento\Framework\App\Request\Http))
#47 /var/www/html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Pitbulk\SAML2\Controller\Account\Logout\Interceptor))
#48 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#49 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#50 /var/www/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#51 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#52 /var/www/html/vendor/fastly/magento2/Model/FrontControllerPlugin.php(128): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#53 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Fastly\Cdn\Model\FrontControllerPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#54 /var/www/html/vendor/amasty/aminvisiblecaptcha/Plugin/Framework/App/FrontControllerInterface/ValidateCaptcha.php(124): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#55 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\InvisibleCaptcha\Plugin\Framework\App\FrontControllerInterface\ValidateCaptcha->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#56 /var/www/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#57 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#58 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#59 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#60 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#61 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#62 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#63 /var/www/html/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#64 {main}
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @lfluvisotto ,

Verified the issue in 2.4-develop instance and the issue is not reproducible,Kindly recheck the behaviour.
**Kindly refer the below video reference:**
https://github.com/magento/magento2/assets/60198592/3921c91c-58a9-4518-b774-4487921d55e7
**Steps to reproduce:**

- Login as any customer in admin 
- Logout using given URL in main Description

Customer can logged out without any issue.

Thanks
