### ISSUE TITLE
Noticed exception 'TypeError' when the product_list_order parameter is an array.

### ISSUE THREAD

**Issue by adam-krakowski-accenture** [magento/magento2#37827]
### Preconditions and environment

- Magento version: Adobe Commerce ver. 2.4.4-p4

### Steps to reproduce

1. Go to storefront, then into categories to see the products.
2. Change the product_list_order parameter in the URL to an array type.
3. Refresh the page with changed URL.

Examples of URL:
https://release4.proshop.pg.com/whitening/crest-whitestrips.html?product_list_order[]=price&product_list_dir=desc
https://ca.magento2.local/shop-by-product/crest-whitening.html?product_list_order[]

### Expected result

The product_list_order parameter with an array type is handled correctly. 

vendor/magento/module-catalog/Model/Product/ProductList/ToolbarMemorizer.php
The getOrder() function returns string|bool value as described in the @return tag

### Actual result

TypeError: Illegal offset type in isset or empty in /var/www/magento/vendor/magento/module-catalog/Block/Product/ProductList/Toolbar.php:280

vendor/magento/module-catalog/Model/Product/ProductList/ToolbarMemorizer.php 
The getOrder() function returns array value (invalid @return tag), which causes a TypeError

### Additional information

TypeError: Illegal offset type in isset or empty in /var/www/magento/vendor/magento/module-catalog/Block/Product/ProductList/Toolbar.php:280
Stack trace:
#0 /var/www/magento/app/code/PG/GaGtm/Model/ProductCollection/CategoryCollectionFilter.php(62): Magento\Catalog\Block\Product\ProductList\Toolbar->getCurrentOrder()
#1 /var/www/magento/app/code/PG/GaGtm/Model/ProductCollection/CollectionGetter.php(46): PG\GaGtm\Model\ProductCollection\CategoryCollectionFilter->filter()
#2 /var/www/magento/app/code/PG/GaGtm/Observer/Products/LoadCollection.php(58): PG\GaGtm\Model\ProductCollection\CollectionGetter->getCollection()
#3 /var/www/magento/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): PG\GaGtm\Observer\Products\LoadCollection->execute()
#4 /var/www/magento/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#5 /var/www/magento/vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#6 /var/www/magento/generated/code/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch()
#7 /var/www/magento/vendor/magento/framework/View/Result/Layout.php(169): Magento\Staging\Model\Event\Manager\Proxy->dispatch()
#8 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult()
#9 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent()
#10 /var/www/magento/vendor/magezon/module-core/Plugin/View/Result/Layout.php(24): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#11 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magezon\Core\Plugin\View\Result\Layout->aroundRenderResult()
#12 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#13 /var/www/magento/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(95): Magento\Framework\View\Result\Page\Interceptor->___callPlugins()
#14 /var/www/magento/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult()
#15 /var/www/magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#16 /var/www/magento/vendor/magento/framework/App/Bootstrap.php(267): Magento\Framework\App\Http\Interceptor->launch()
#17 /var/www/magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @adam-krakowski-accenture,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**

- Go to storefront, then into categories to see the products.
- Change the product_list_order parameter in the URL to an array type.
- Refresh the page with changed URL.

We are not getting any exception after changing the URL could you please let us know if we are missing anything.


https://github.com/magento/magento2/assets/51680745/5d724bd5-a71a-42d0-9e4e-892c9fd159b7



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by adam-krakowski-accenture** [comment]
Hello @engcom-Bravo,
Thank you for contact. Please try to change URL with sign "?" also. On the video I see that you are trying for example "product_list_order[]" instead "?product_list_order[] after ".html" so at the end of URL should be ".html?product_list_order[]".
Thanks

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @adam-krakowski-accenture,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible. Kindly refer the attached video.

**Steps to reproduce**

- Go to storefront, then into categories to see the products.
- Change the product_list_order parameter in the URL to an array type.
- Refresh the page with changed URL.

After changing the URL to an array type we are getting exception `An error has happened during application run. See exception log for details.`

<img width="1490" alt="Screenshot 2023-08-03 at 5 04 29 PM" src="https://github.com/magento/magento2/assets/51680745/91832fe5-e81a-4770-8175-dde9c6cd1a5d">




https://github.com/magento/magento2/assets/51680745/f8481389-d33b-4006-8bfa-1ffc68919935




Hence Confirming the issue.

Thanks.

**Comment by jenyatrishin** [comment]
@magento I am working on this

**Comment by jenyatrishin** [comment]
@magento add to contributors team

**Comment by jenyatrishin** [comment]
@magento I am working on this
