### ISSUE TITLE
Magento 2.4.5-p4 Braintree/Paypal dependency is broken on PHP7.4

### ISSUE THREAD

**Issue by vonhraban** [magento/magento2#37877]
### Preconditions and environment

- 2.4.5-p4
- PHP 7.4.29

- The issue happened after upgrading from 2.4.5-p3 to 2.4.5-p4 using `composer update-commerce -W` command

### Steps to reproduce

1. Run `magento setup:upgrade` while on PHP 7.4.29 using magento 2.4.5-p4
2. See error

### Expected result

`magento setup:upgrade` runs without errors

### Actual result

```
...
Repositories code generation... 1/9 [==>-------------------]  11% 1 sec 46.0 MiB
...
syntax error, unexpected '|', expecting ';' or '{'#0 /var/www/html/*/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/s...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('PayPal\\Braintre...')
#2 [internal function]: spl_autoload_call('PayPal\\Braintre...')
#3 /var/www/html/*/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('PayPal\\Braintre...')
#4 /var/www/html/*/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('PayPal\\Braintre...', '/var/www/html/s...')
```

### Additional information

Upon further digging I discovered that
- Magento 2.4.5-p4 requires paypal/module-braintree-core:4.4.0-p2
- paypal/module-braintree-core:4.4.0-p2 uses PHP8 syntax

```$ php -l vendor/paypal/module-braintree-core/Gateway/Command/GetPaymentNonceCommand.php
PHP Parse error:  syntax error, unexpected '|', expecting ';' or '{' in vendor/paypal/module-braintree-core/Gateway/Command/GetPaymentNonceCommand.php on line 74
Errors parsing vendor/paypal/module-braintree-core/Gateway/Command/GetPaymentNonceCommand.php```

while still claiming that requirement is

```        "php": "~7.4.0||~8.1.0",```

When trying to forcefully downgrade

```$ composer require paypal/module-braintree-core:4.4.0-p1
./composer.json has been updated
Running composer update paypal/module-braintree-core
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires paypal/module-braintree-core 4.4.0-p1, found paypal/module-braintree-core[4.4.0-p1] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - paypal/module-braintree 4.4.0-p2 requires paypal/module-braintree-core 4.4.0-p2 -> found paypal/module-braintree-core[4.4.0-p2] but it conflicts with your root composer.json require (4.4.0-p1).
    - magento/product-community-edition 2.4.5-p4 requires paypal/module-braintree 4.4.0-p2 -> satisfiable by paypal/module-braintree[4.4.0-p2].
    - magento/product-community-edition is locked to version 2.4.5-p4 and an update of this package was not requested.```

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by andrewbess** [comment]
Hello @vonhraban 
The Magento 2.4.5 doesn't support PHP 7.4.
Please take a look at [system requirements document](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html?lang=en).
This issue is not actual.

**Comment by vonhraban** [comment]
I see, thank you. In this case I believe https://github.com/magento/magento2/blob/2.4.5-p4/composer.json#L20 should be updated accordingly

**Comment by hostep** [comment]
I already reported this issue about a month ago and Adobe would bring it up with the Braintree developers. Although, I don't really expect much to happen...

I toatally agree with @vonhraban that the composer constraints should match with the PHP versions supported (which isn't the case with the Braintree module at this moment).
