### ISSUE TITLE
Creating Bundle Product via API - Property "BundleProductOptions" does not have accessor method "getBundleProductOptions"

### ISSUE THREAD

**Issue by chammedinger** [magento/magento2#38087]
### Preconditions and environment

- Magento version 2.4.5-p5

### Steps to reproduce

I'm following this guide (https://developer.adobe.com/commerce/webapi/rest/tutorials/bundle-product/create-bundle-product/) to create a Bundle Product

### Expected result

Creation of the Bundle Product

### Actual result

As a response I get following: 
{"message":"Internal Error. Details are available in Magento log file. Report ID: webapi-652d149be62d5"}

In Magento Log I get the following error:

```
[2023-10-16T10:46:51.943861+00:00] main.CRITICAL: LogicException: Property "BundleProductOptions" does not have accessor method "getBundleProductOptions" in class "Magento\Catalog\Api\Data\ProductInterface". in /var/www/magento2_staging/vendor/magento/framework/Reflection/NameFinder.php:103
Stack trace:
#0 /var/www/magento2_staging/vendor/magento/framework/Reflection/NameFinder.php(62): Magento\Framework\Reflection\NameFinder->findAccessorMethodName(Object(Laminas\Code\Reflection\ClassReflection), 'BundleProductOp...', 'getBundleProduc...', 'isBundleProduct...')
#1 /var/www/magento2_staging/vendor/magento/framework/Webapi/ServiceInputProcessor.php(289): Magento\Framework\Reflection\NameFinder->getGetterMethodName(Object(Laminas\Code\Reflection\ClassReflection), 'BundleProductOp...')
#2 /var/www/magento2_staging/vendor/magento/framework/Webapi/ServiceInputProcessor.php(514): Magento\Framework\Webapi\ServiceInputProcessor->_createFromArray('Magento\\Catalog...', Array)
#3 /var/www/magento2_staging/vendor/magento/framework/Webapi/ServiceInputProcessor.php(194): Magento\Framework\Webapi\ServiceInputProcessor->convertValue(Array, 'Magento\\Catalog...')
#4 /var/www/magento2_staging/vendor/magento/module-webapi/Controller/Rest/InputParamsResolver.php(115): Magento\Framework\Webapi\ServiceInputProcessor->process('Magento\\Catalog...', 'save', Array)
#5 /var/www/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest\InputParamsResolver->resolve()
#6 /var/www/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->___callParent('resolve', Array)
#7 /var/www/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->Magento\Framework\Interception\{closure}()
#8 /var/www/magento2_staging/generated/code/Magento/Webapi/Controller/Rest/InputParamsResolver/Interceptor.php(23): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->___callPlugins('resolve', Array, Array)
#9 /var/www/magento2_staging/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(85): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->resolve()
#10 /var/www/magento2_staging/vendor/magento/module-webapi/Controller/Rest.php(195): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
#11 /var/www/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#12 /var/www/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#13 /var/www/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /var/www/magento2_staging/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#15 /var/www/magento2_staging/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /var/www/magento2_staging/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#17 /var/www/magento2_staging/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#18 /var/www/magento2_staging/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#19 {main}

Next Exception: Report ID: webapi-652d149be62d5; Message: Property "BundleProductOptions" does not have accessor method "getBundleProductOptions" in class "Magento\Catalog\Api\Data\ProductInterface". in /var/www/magento2_staging/vendor/magento/framework/Webapi/ErrorProcessor.php:208
Stack trace:
#0 /var/www/magento2_staging/vendor/magento/framework/Webapi/ErrorProcessor.php(153): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(LogicException))
#1 /var/www/magento2_staging/vendor/magento/module-webapi/Controller/Rest.php(197): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(LogicException))
#2 /var/www/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#4 /var/www/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#5 /var/www/magento2_staging/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#6 /var/www/magento2_staging/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /var/www/magento2_staging/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#8 /var/www/magento2_staging/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#9 /var/www/magento2_staging/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#10 {main} [] []
```

Via the Magento Admin UI I can create the bundle product with the same properties. 
Via the API I get above error.
I have already tried to clean cache end re-compile everything etc.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @chammedinger,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- I'm following this guide (https://developer.adobe.com/commerce/webapi/rest/tutorials/bundle-product/create-bundle-product/) to create a Bundle Product.


<img width="1205" alt="Screenshot 2023-10-17 at 11 28 13 AM" src="https://github.com/magento/magento2/assets/51680745/0603568a-bf05-430a-a2f6-228b2c33f73d">



<img width="1454" alt="Screenshot 2023-10-17 at 11 27 53 AM" src="https://github.com/magento/magento2/assets/51680745/7b11121c-ef95-4296-9a49-8d55065b00ab">





We are able to create the Bundle Products.we have followed same document.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible


Thanks.

**Comment by chammedinger** [comment]
Thank you very much for checking.
I will closer examine my data to identify the problem.
