### ISSUE TITLE
PayPal Braintree: Error: Call to undefined method Magento\Payment\Gateway\Data\Order\AddressAdapter::getStreet()

### ISSUE THREAD

**Issue by tim-breitenstein-it** [magento/magento2#38092]
### Preconditions and environment

- Magento Version: 2.4.3-p3
- PayPal Braintree Version: 4.2.5
- PayPal Braintree Sandbox Account

### Steps to reproduce

1. Add Product to Cart
2. Got to Checkout
3. Log In: with Magento Account Credentials
4. Select Payment Method: PayPal
5. Log In: with PayPay Sandbox Credentials
6. Click: Checkout Now
7. See Checkout Cart Validation Messages Error: `Something went wrong with your request. Please try again later.`

### Expected result

Successfull Order with Payment Method PayPal

### Actual result

Ajax Request: `https://magento-2.dev/rest/de/V1/carts/mine/payment-information`

Status Code: 500 Internal Server Error

Response:
```
Error: Call to undefined method Magento\Payment\Gateway\Data\Order\AddressAdapter::getStreet() in /var/www/magento-2/vendor/paypal/module-braintree-core/Gateway/Request/AddressDataBuilder.php:102
Stack trace:
#0 /var/www/magento-2/vendor/magento/module-payment/Gateway/Request/BuilderComposite.php(50): PayPal\Braintree\Gateway\Request\AddressDataBuilder->build()
#1 /var/www/magento-2/vendor/paypal/module-braintree-core/Gateway/Command/GatewayCommand.php(111): Magento\Payment\Gateway\Request\BuilderComposite->build()
#2 /var/www/magento-2/vendor/magento/module-payment/Model/Method/Adapter.php(549): PayPal\Braintree\Gateway\Command\GatewayCommand->execute()
#3 /var/www/magento-2/vendor/magento/module-payment/Model/Method/Adapter.php(451): Magento\Payment\Model\Method\Adapter->executeCommand()
#4 /var/www/magento-2/generated/code/Magento/Payment/Model/Method/Adapter/Interceptor.php(248): Magento\Payment\Model\Method\Adapter->authorize()
#5 /var/www/magento-2/vendor/magento/module-sales/Model/Order/Payment/Operations/AuthorizeOperation.php(45): Magento\Payment\Model\Method\Adapter\Interceptor->authorize()
#6 /var/www/magento-2/vendor/magento/module-sales/Model/Order/Payment/Processor.php(72): Magento\Sales\Model\Order\Payment\Operations\AuthorizeOperation->authorize()
#7 /var/www/magento-2/vendor/magento/module-sales/Model/Order/Payment.php(1136): Magento\Sales\Model\Order\Payment\Processor->authorize()
#8 /var/www/magento-2/generated/code/Magento/Sales/Model/Order/Payment/Interceptor.php(302): Magento\Sales\Model\Order\Payment->authorize()
#9 /var/www/magento-2/vendor/magento/module-sales/Model/Order/Payment.php(458): Magento\Sales\Model\Order\Payment\Interceptor->authorize()
#10 /var/www/magento-2/vendor/magento/module-sales/Model/Order/Payment.php(385): Magento\Sales\Model\Order\Payment->processAction()
#11 /var/www/magento-2/generated/code/Magento/Sales/Model/Order/Payment/Interceptor.php(122): Magento\Sales\Model\Order\Payment->place()
#12 /var/www/magento-2/vendor/magento/module-sales/Model/Order.php(992): Magento\Sales\Model\Order\Payment\Interceptor->place()
#13 /var/www/magento-2/vendor/magento/module-sales/Model/Order.php(1214): Magento\Sales\Model\Order->_placePayment()
#14 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Order->place()
#15 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(138): Trustedshops\Trustedshops\Model\Rewrite\Sales\Order\Interceptor->___callParent()
#16 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(153): Trustedshops\Trustedshops\Model\Rewrite\Sales\Order\Interceptor->Magento\Framework\Interception\{closure}()
#17 /var/www/magento-2/generated/code/Trustedshops/Trustedshops/Model/Rewrite/Sales/Order/Interceptor.php(374): Trustedshops\Trustedshops\Model\Rewrite\Sales\Order\Interceptor->___callPlugins()
#18 /var/www/magento-2/vendor/magento/module-sales/Model/Service/OrderService.php(209): Trustedshops\Trustedshops\Model\Rewrite\Sales\Order\Interceptor->place()
#19 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\OrderService->place()
#20 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\OrderService\Interceptor->___callParent()
#21 /var/www/magento-2/vendor/magento/module-inventory-sales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php(195): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}()
#22 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\InventorySales\Plugin\Sales\OrderManagement\AppendReservationsAfterOrderPlacementPlugin->aroundPlace()
#23 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}()
#24 /var/www/magento-2/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(86): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins()
#25 /var/www/magento-2/vendor/magento/module-quote/Model/QuoteManagement.php(575): Magento\Sales\Model\Service\OrderService\Interceptor->place()
#26 /var/www/magento-2/vendor/magento/module-quote/Model/QuoteManagement.php(456): Magento\Quote\Model\QuoteManagement->submitQuote()
#27 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->submit()
#28 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent()
#29 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}()
#30 /var/www/magento-2/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(68): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins()
#31 /var/www/magento-2/vendor/magento/module-quote/Model/QuoteManagement.php(414): Magento\Quote\Model\QuoteManagement\Interceptor->submit()
#32 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->placeOrder()
#33 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent()
#34 /var/www/magento-2/vendor/creativestyle/magesuite-daily-deal/Plugin/VerifyOfferInCheckout.php(46): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}()
#35 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(135): MageSuite\DailyDeal\Plugin\VerifyOfferInCheckout->aroundPlaceOrder()
#36 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}()
#37 /var/www/magento-2/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(50): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins()
#38 /var/www/magento-2/vendor/magento/module-checkout/Model/PaymentInformationManagement.php(125): Magento\Quote\Model\QuoteManagement\Interceptor->placeOrder()
#39 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder()
#40 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callParent()
#41 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}()
#42 /var/www/magento-2/generated/code/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(23): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins()
#43 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder()
#44 /var/www/magento-2/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()
#45 /var/www/magento-2/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()
#46 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
#47 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
#48 /var/www/magento-2/vendor/cart2quote/module-features/Feature/ApiAccess/Rest.php(2): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
#49 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(135): Cart2Quote\Features\Feature\ApiAccess\Rest->aroundDispatch()
#50 /var/www/magento-2/vendor/cart2quote/module-features/Feature/ApiAccess/Rest.php(2): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
#51 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(135): Cart2Quote\Features\Feature\ApiAccess\Rest->aroundDispatch()
#52 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
#53 /var/www/magento-2/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
#54 /var/www/magento-2/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
#55 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#56 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent()
#57 /var/www/magento-2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#58 /var/www/magento-2/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins()
#59 /var/www/magento-2/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#60 /var/www/magento-2/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#61 {main}
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by chalov-anton** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @tim-breitenstein-it,

Thank you for reporting and collaboration.

We have verified the issue and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**

- Add Product to Cart
- Got to Checkout
- Log In: with Magento Account Credentials
- Select Payment Method: PayPal
- Log In: with PayPay Sandbox Credentials
- Click: Checkout Now

We are able to place the order successfully.


https://github.com/magento/magento2/assets/51680745/7647b909-fa35-46c7-a036-4f3f264768f2




So I request to please check the issue in Latest Version of Magento it might be issue got fixed.


Thanks.

**Comment by tim-breitenstein-it** [comment]
> So I request to please check the issue in Latest Version of Magento it might be issue got fixed.

OK,

but you agree with me that this could be a bug also in the Latest Version of Magento:

```
Error: Call to undefined method Magento\Payment\Gateway\Data\Order\AddressAdapter::getStreet() in /var/www/magento-2/vendor/paypal/module-braintree-core/Gateway/Request/AddressDataBuilder.php:102
Stack trace:
#0 /var/www/magento-2/vendor/magento/module-payment/Gateway/Request/BuilderComposite.php(50): PayPal\Braintree\Gateway\Request\AddressDataBuilder->build()
```
Because here [Magento/Payment/Gateway/Data/Order/AddressAdapter.php](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Payment/Gateway/Data/Order/AddressAdapter.php) there is no function `getStreet`!

**Comment by tim-breitenstein-it** [comment]
I found the extension that caused it!
