### ISSUE TITLE
Di-compile error on upgrade from Magento v2.4.6-p2  to v2.4.6-p3

### ISSUE THREAD

**Issue by hgati** [magento/magento2#38104]
### Preconditions and environment

- Magento v2.4.6-p2
- PHP 8.2

### Steps to reproduce

```bash
cd /var/www/magento
php bin/magento maintenance:enable
php bin/magento cron:remove
sudo systemctl restart php8.2-fpm.service

composer require-commerce magento/product-community-edition 2.4.6-p3 --no-update
composer update

php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy -f
php bin/magento cache:flush
php bin/magento setup:di:compile
php bin/magento indexer:reindex

php bin/magento cron:install
php bin/magento maintenance:disable
php bin/magento --version
```

### Expected result

It should be di-compiled successfully.

### Actual result

```bash
+ magento setup:di:compile
Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% 1 sec 133.0 MiB
There is an error in /var/www/magento/vendor/magento/module-re-captcha-ui/Model/ButtonLock.php at line: 12
Interface "Magento\Framework\View\Element\ButtonLockInterface" not found#0 /var/www/magento/vendor/composer/ClassLoader.php(576): include()
#1 /var/www/magento/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /var/www/magento/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists()
#4 /var/www/magento/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#5 /var/www/magento/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
#6 /var/www/magento/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList()
#7 /var/www/magento/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#8 /var/www/magento/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(209): Magento\Setup\Module\Di\App\Task\Manager->process()
#9 /var/www/magento/vendor/symfony/console/Command/Command.php(298): Magento\Setup\Console\Command\DiCompileCommand->execute()
#10 /var/www/magento/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#11 /var/www/magento/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#12 /var/www/magento/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
#13 /var/www/magento/vendor/symfony/console/Application.php(171): Magento\Framework\Console\Cli->doRun()
#14 /var/www/magento/bin/magento(23): Symfony\Component\Console\Application->run()
#15 {main}
```

### Additional information

`/var/www/magento/vendor/magento/module-re-captcha-ui/Model/ButtonLock.php`

The error occurs in the ButtonLock.php file, which is trying to inherit the Magento\Framework\View\Element\ButtonLockInterface class. However, **in Magento 2.4.6-p3, ButtonLockInterface.php does not exist**, leading to this issue.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hgati** [comment]
In version 2.4.6-p2, the file Magento\Framework\View\Element\ButtonLockInterface class exists.
https://github.com/magento/magento2/tree/2.4.6-p2/lib/internal/Magento/Framework/View/Element

However, in version 2.4.6-p3, the file Magento\Framework\View\Element\ButtonLockInterface is missing.
https://github.com/magento/magento2/tree/2.4.6-p3/lib/internal/Magento/Framework/View/Element

**Comment by hgati** [comment]
I just confirmed that the mentioned error occurred after upgrading while the Magento patch was already applied (Magento 2.4.6 Security Patch (MDVA-39305-V2)).

It seems that during the upgrade, I need to revert all the patches that were previously applied to their original state before performing the upgrade operation.
