### ISSUE TITLE
Integration test not working

### ISSUE THREAD

**Issue by francesco-oghabi** [magento/magento2#38145]
### Preconditions and environment

- Magento 2.4.6
- Vanilla Magento 2.4.6

### Steps to reproduce

Run
**vendor/bin/phpunit -c $(pwd)/dev/tests/integration/phpunit.xml**

### Expected result

Integration test succesfully completed

### Actual result

PHPUnit 9.6.13 by Sebastian Bergmann and contributors.

Warning:       Using a custom test suite loader is deprecated

S.........Unable to apply fixture: Magento/Catalog/_files/product_simple.php
#0 /var/www/html/dev/tests/integration/testsuite/Magento/AdvancedPricingImportExport/Model/Export/AdvancedPricingTest.php(82): Magento\AdvancedPricingImportExport\Model\Export\AdvancedPricingTest->testExport()

Caused By: The stock item was unable to be saved. Please try again.
#0 /var/www/html/vendor/magento/module-catalog-inventory/Model/StockRegistry.php(181): Magento\CatalogInventory\Model\Stock\StockItemRepository->save(Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
#1 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\CatalogInventory\Model\StockRegistry->updateStockItemBySku('simple', Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
#2 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogInventory\Model\StockRegistry\Interceptor->___callParent('updateStockItem...', Array)
#3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogInventory\Model\StockRegistry\Interceptor->Magento\Framework\Interception\{closure}('simple', Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
#4 /var/www/html/dev/tests/integration/tmp/sandbox-0-a5174074830fe8b6800b322a83f963a5a78520ed5e86e87acf5ab3a0e8cb6bb0/generated/code/Magento/CatalogInventory/Model/StockRegistry/Interceptor.php(95): Magento\CatalogInventory\Model\StockRegistry\Interceptor->___callPlugins('updateStockItem...', Array, Array)
#5 /var/www/html/vendor/magento/module-catalog-inventory/Observer/SaveInventoryDataObserver.php(125): Magento\CatalogInventory\Model\StockRegistry\Interceptor->updateStockItemBySku('simple', Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
#6 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\CatalogInventory\Observer\SaveInventoryDataObserver->execute(Object(Magento\Framework\Event\Observer))
#7 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\CatalogInventory\Observer\SaveInventoryDataObserver), Object(Magento\Framework\Event\Observer))
#8 /var/www/html/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#9 /var/www/html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('catalog_product...', Array)
#10 /var/www/html/vendor/magento/framework/Model/AbstractModel.php(837): Magento\Framework\Event\Manager\Proxy->dispatch('catalog_product...', Array)
#11 /var/www/html/vendor/magento/module-catalog/Model/Product.php(985): Magento\Framework\Model\AbstractModel->afterSave()
#12 /var/www/html/dev/tests/integration/tmp/sandbox-0-a5174074830fe8b6800b322a83f963a5a78520ed5e86e87acf5ab3a0e8cb6bb0/generated/code/Magento/Catalog/Model/Product/Interceptor.php(248): Magento\Catalog\Model\Product->afterSave()
#13 /var/www/html/vendor/magento/framework/EntityManager/Observer/AfterEntitySave.php(34): Magento\Catalog\Model\Product\Interceptor->afterSave()
#14 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Framework\EntityManager\Observer\AfterEntitySave->execute(Object(Magento\Framework\Event\Observer))
#15 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Framework\EntityManager\Observer\AfterEntitySave), Object(Magento\Framework\Event\Observer))
#16 /var/www/html/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#17 /var/www/html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('magento_catalog...', Array)
#18 /var/www/html/vendor/magento/framework/EntityManager/EventManager.php(50): Magento\Framework\Event\Manager\Proxy->dispatch('magento_catalog...', Array)
#19 /var/www/html/vendor/magento/framework/EntityManager/Operation/Create.php(123): Magento\Framework\EntityManager\EventManager->dispatchEntityEvent('Magento\\Catalog...', 'save_after', Array)
#20 /var/www/html/vendor/magento/framework/EntityManager/EntityManager.php(106): Magento\Framework\EntityManager\Operation\Create->execute(Object(Magento\Catalog\Model\Product\Interceptor), Array)
#21 /var/www/html/vendor/magento/module-catalog/Model/ResourceModel/Product.php(777): Magento\Framework\EntityManager\EntityManager->save(Object(Magento\Catalog\Model\Product\Interceptor))
#22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ResourceModel\Product->save(Object(Magento\Catalog\Model\Product\Interceptor))
#23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent('save', Array)
#24 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(58): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#25 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(28): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#26 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#27 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#28 /var/www/html/generated/code/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(194): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins('save', Array, Array)
#29 /var/www/html/vendor/magento/module-catalog/Model/ProductRepository.php(886): Magento\Catalog\Model\ResourceModel\Product\Interceptor->save(Object(Magento\Catalog\Model\Product\Interceptor))
#30 /var/www/html/vendor/magento/module-catalog/Model/ProductRepository.php(634): Magento\Catalog\Model\ProductRepository->saveProduct(Object(Magento\Catalog\Model\Product\Interceptor))
#31 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ProductRepository->save(Object(Magento\Catalog\Model\Product\Interceptor))
#32 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ProductRepository\Interceptor->___callParent('save', Array)
#33 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ProductRepository\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#34 /var/www/html/generated/code/Magento/Catalog/Model/ProductRepository/Interceptor.php(41): Magento\Catalog\Model\ProductRepository\Interceptor->___callPlugins('save', Array, Array)
#35 /var/www/html/dev/tests/integration/testsuite/Magento/Catalog/_files/product_simple.php(204): Magento\Catalog\Model\ProductRepository\Interceptor->save(Object(Magento\Catalog\Model\Product\Interceptor))
#36 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Fixture/LegacyDataFixture.php(38): require('/var/www/html/d...')
#37 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixtureSetup.php(54): Magento\TestFramework\Fixture\LegacyDataFixture->apply(Array)
#38 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/AbstractDataFixture.php(124): Magento\TestFramework\Annotation\DataFixtureSetup->apply(Array)
#39 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(37): Magento\TestFramework\Annotation\AbstractDataFixture->_applyFixtures(Array, Object(Magento\AdvancedPricingImportExport\Model\Export\AdvancedPricingTest))
#40 [internal function]: Magento\TestFramework\Annotation\DataFixture->startTestTransactionRequest(Object(Magento\AdvancedPricingImportExport\Model\Export\AdvancedPricingTest), Object(Magento\TestFramework\Event\Param\Transaction))
#41 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
#42 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(76): Magento\TestFramework\EventManager->fireEvent('startTestTransa...', Array)
#43 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(46): Magento\TestFramework\Event\Transaction->_processTransactionRequests('startTest', Object(Magento\AdvancedPricingImportExport\Model\Export\AdvancedPricingTest))
#44 [internal function]: Magento\TestFramework\Event\Transaction->startTest(Object(Magento\AdvancedPricingImportExport\Model\Export\AdvancedPricingTest))
#45 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
#46 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Event/PhpUnit.php(127): Magento\TestFramework\EventManager->fireEvent('startTest', Array)
#47 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php(440): Magento\TestFramework\Event\PhpUnit->startTest(Object(Magento\AdvancedPricingImportExport\Model\Export\AdvancedPricingTest))
#48 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php(663): PHPUnit\Framework\TestResult->startTest(Object(Magento\AdvancedPricingImportExport\Model\Export\AdvancedPricingTest))
#49 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(968): PHPUnit\Framework\TestResult->run(Object(Magento\AdvancedPricingImportExport\Model\Export\AdvancedPricingTest))
#50 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#51 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#52 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#53 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#54 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(651): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#55 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(144): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#56 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#57 /var/www/html/vendor/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
#58 /var/www/html/vendor/bin/phpunit(123): include('/var/www/html/v...')
#59 {main}

Caused By: {"error":"no handler found for uri [/magento2_product_1_v2/document/_bulk] and method [POST]"}
#0 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(333): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array)
#1 /var/www/html/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#2 /var/www/html/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php(65): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#3 /var/www/html/vendor/ezimuel/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#4 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(345): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#5 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(241): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#6 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(110): Elasticsearch\Connections\Connection->performRequest('POST', '/magento2_produ...', Array, '{"delete":{"_id...', Array, Object(Elasticsearch\Transport))
#7 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1929): Elasticsearch\Transport->performRequest('POST', '/magento2_produ...', Array, '{"delete":{"_id...', Array)
#8 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(347): Elasticsearch\Client->performRequest(Object(Elasticsearch\Endpoints\Bulk))
#9 /var/www/html/vendor/magento/module-elasticsearch-7/Model/Client/Elasticsearch.php(173): Elasticsearch\Client->bulk(Array)
#10 /var/www/html/vendor/magento/module-elasticsearch/Model/Adapter/Elasticsearch.php(312): Magento\Elasticsearch7\Model\Client\Elasticsearch->bulkQuery(Array)
#11 /var/www/html/vendor/magento/module-elasticsearch/Model/Indexer/IndexerHandler.php(186): Magento\Elasticsearch\Model\Adapter\Elasticsearch->deleteDocs(Array, '1', 'product')
#12 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext.php(220): Magento\Elasticsearch\Model\Indexer\IndexerHandler->deleteIndex(Array, Object(ArrayIterator))
#13 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext.php(198): Magento\CatalogSearch\Model\Indexer\Fulltext->processBatch(Object(Magento\Elasticsearch\Model\Indexer\IndexerHandler), Array, Array)
#14 /var/www/html/generated/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Interceptor.php(32): Magento\CatalogSearch\Model\Indexer\Fulltext->executeByDimensions(Array, Array)
#15 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext.php(152): Magento\CatalogSearch\Model\Indexer\Fulltext\Interceptor->executeByDimensions(Array, Object(ArrayIterator))
#16 /var/www/html/generated/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Interceptor.php(23): Magento\CatalogSearch\Model\Indexer\Fulltext->execute(Array)
#17 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext.php(261): Magento\CatalogSearch\Model\Indexer\Fulltext\Interceptor->execute(Array)
#18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\CatalogSearch\Model\Indexer\Fulltext->executeRow(1)
#19 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Model\Indexer\Fulltext\Interceptor->___callParent('executeRow', Array)
#20 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Model\Indexer\Fulltext\Interceptor->Magento\Framework\Interception\{closure}(1)
#21 /var/www/html/generated/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Interceptor.php(59): Magento\CatalogSearch\Model\Indexer\Fulltext\Interceptor->___callPlugins('executeRow', Array, Array)
#22 /var/www/html/vendor/magento/module-indexer/Model/Indexer.php(521): Magento\CatalogSearch\Model\Indexer\Fulltext\Interceptor->executeRow(1)
#23 /var/www/html/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php(277): Magento\Indexer\Model\Indexer->reindexRow(1)
#24 /var/www/html/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php(282): Magento\Indexer\Model\Indexer\DependencyDecorator->reindexRow(1)
#25 /var/www/html/vendor/magento/framework/Indexer/AbstractProcessor.php(54): Magento\Indexer\Model\Indexer\DependencyDecorator->reindexRow(1)
#26 /var/www/html/vendor/magento/module-catalog-inventory/Model/ResourceModel/Stock/Item.php(155): Magento\Framework\Indexer\AbstractProcessor->reindexRow(1)
#27 /var/www/html/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(841): Magento\CatalogInventory\Model\ResourceModel\Stock\Item->_afterSave(Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
#28 /var/www/html/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(402): Magento\Framework\Model\ResourceModel\Db\AbstractDb->processAfterSaves(Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
#29 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
#30 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogInventory\Model\ResourceModel\Stock\Item\Interceptor->___callParent('save', Array)
#31 /var/www/html/vendor/magento/module-inventory-catalog/Plugin/CatalogInventory/UpdateSourceItemAtLegacyStockItemSavePlugin.php(147): Magento\CatalogInventory\Model\ResourceModel\Stock\Item\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
#32 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\InventoryCatalog\Plugin\CatalogInventory\UpdateSourceItemAtLegacyStockItemSavePlugin->aroundSave(Object(Magento\CatalogInventory\Model\ResourceModel\Stock\Item\Interceptor), Object(Closure), Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
#33 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogInventory\Model\ResourceModel\Stock\Item\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
#34 /var/www/html/generated/code/Magento/CatalogInventory/Model/ResourceModel/Stock/Item/Interceptor.php(140): Magento\CatalogInventory\Model\ResourceModel\Stock\Item\Interceptor->___callPlugins('save', Array, Array)
#35 /var/www/html/vendor/magento/module-catalog-inventory/Model/Stock/StockItemRepository.php(193): Magento\CatalogInventory\Model\ResourceModel\Stock\Item\Interceptor->save(Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
#36 /var/www/html/vendor/magento/module-catalog-inventory/Model/StockRegistry.php(181): Magento\CatalogInventory\Model\Stock\StockItemRepository->save(Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
#37 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\CatalogInventory\Model\StockRegistry->updateStockItemBySku('simple', Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
#38 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogInventory\Model\StockRegistry\Interceptor->___callParent('updateStockItem...', Array)
#39 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogInventory\Model\StockRegistry\Interceptor->Magento\Framework\Interception\{closure}('simple', Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
#40 /var/www/html/dev/tests/integration/tmp/sandbox-0-a5174074830fe8b6800b322a83f963a5a78520ed5e86e87acf5ab3a0e8cb6bb0/generated/code/Magento/CatalogInventory/Model/StockRegistry/Interceptor.php(95): Magento\CatalogInventory\Model\StockRegistry\Interceptor->___callPlugins('updateStockItem...', Array, Array)
#41 /var/www/html/vendor/magento/module-catalog-inventory/Observer/SaveInventoryDataObserver.php(125): Magento\CatalogInventory\Model\StockRegistry\Interceptor->updateStockItemBySku('simple', Object(Magento\CatalogInventory\Model\Stock\Item\Interceptor))
#42 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\CatalogInventory\Observer\SaveInventoryDataObserver->execute(Object(Magento\Framework\Event\Observer))
#43 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\CatalogInventory\Observer\SaveInventoryDataObserver), Object(Magento\Framework\Event\Observer))
#44 /var/www/html/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#45 /var/www/html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('catalog_product...', Array)
#46 /var/www/html/vendor/magento/framework/Model/AbstractModel.php(837): Magento\Framework\Event\Manager\Proxy->dispatch('catalog_product...', Array)
#47 /var/www/html/vendor/magento/module-catalog/Model/Product.php(985): Magento\Framework\Model\AbstractModel->afterSave()
#48 /var/www/html/dev/tests/integration/tmp/sandbox-0-a5174074830fe8b6800b322a83f963a5a78520ed5e86e87acf5ab3a0e8cb6bb0/generated/code/Magento/Catalog/Model/Product/Interceptor.php(248): Magento\Catalog\Model\Product->afterSave()
#49 /var/www/html/vendor/magento/framework/EntityManager/Observer/AfterEntitySave.php(34): Magento\Catalog\Model\Product\Interceptor->afterSave()
#50 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Framework\EntityManager\Observer\AfterEntitySave->execute(Object(Magento\Framework\Event\Observer))
#51 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Framework\EntityManager\Observer\AfterEntitySave), Object(Magento\Framework\Event\Observer))
#52 /var/www/html/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#53 /var/www/html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('magento_catalog...', Array)
#54 /var/www/html/vendor/magento/framework/EntityManager/EventManager.php(50): Magento\Framework\Event\Manager\Proxy->dispatch('magento_catalog...', Array)
#55 /var/www/html/vendor/magento/framework/EntityManager/Operation/Create.php(123): Magento\Framework\EntityManager\EventManager->dispatchEntityEvent('Magento\\Catalog...', 'save_after', Array)
#56 /var/www/html/vendor/magento/framework/EntityManager/EntityManager.php(106): Magento\Framework\EntityManager\Operation\Create->execute(Object(Magento\Catalog\Model\Product\Interceptor), Array)
#57 /var/www/html/vendor/magento/module-catalog/Model/ResourceModel/Product.php(777): Magento\Framework\EntityManager\EntityManager->save(Object(Magento\Catalog\Model\Product\Interceptor))
#58 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ResourceModel\Product->save(Object(Magento\Catalog\Model\Product\Interceptor))
#59 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent('save', Array)
#60 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(58): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#61 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(28): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#62 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#63 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#64 /var/www/html/generated/code/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(194): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins('save', Array, Array)
#65 /var/www/html/vendor/magento/module-catalog/Model/ProductRepository.php(886): Magento\Catalog\Model\ResourceModel\Product\Interceptor->save(Object(Magento\Catalog\Model\Product\Interceptor))
#66 /var/www/html/vendor/magento/module-catalog/Model/ProductRepository.php(634): Magento\Catalog\Model\ProductRepository->saveProduct(Object(Magento\Catalog\Model\Product\Interceptor))
#67 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ProductRepository->save(Object(Magento\Catalog\Model\Product\Interceptor))
#68 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ProductRepository\Interceptor->___callParent('save', Array)
#69 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ProductRepository\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#70 /var/www/html/generated/code/Magento/Catalog/Model/ProductRepository/Interceptor.php(41): Magento\Catalog\Model\ProductRepository\Interceptor->___callPlugins('save', Array, Array)
#71 /var/www/html/dev/tests/integration/testsuite/Magento/Catalog/_files/product_simple.php(204): Magento\Catalog\Model\ProductRepository\Interceptor->save(Object(Magento\Catalog\Model\Product\Interceptor))
#72 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Fixture/LegacyDataFixture.php(38): require('/var/www/html/d...')
#73 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixtureSetup.php(54): Magento\TestFramework\Fixture\LegacyDataFixture->apply(Array)
#74 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/AbstractDataFixture.php(124): Magento\TestFramework\Annotation\DataFixtureSetup->apply(Array)
#75 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(37): Magento\TestFramework\Annotation\AbstractDataFixture->_applyFixtures(Array, Object(Magento\AdvancedPricingImportExport\Model\Export\AdvancedPricingTest))
#76 [internal function]: Magento\TestFramework\Annotation\DataFixture->startTestTransactionRequest(Object(Magento\AdvancedPricingImportExport\Model\Export\AdvancedPricingTest), Object(Magento\TestFramework\Event\Param\Transaction))
#77 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
#78 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(76): Magento\TestFramework\EventManager->fireEvent('startTestTransa...', Array)
#79 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(46): Magento\TestFramework\Event\Transaction->_processTransactionRequests('startTest', Object(Magento\AdvancedPricingImportExport\Model\Export\AdvancedPricingTest))
#80 [internal function]: Magento\TestFramework\Event\Transaction->startTest(Object(Magento\AdvancedPricingImportExport\Model\Export\AdvancedPricingTest))
#81 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
#82 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Event/PhpUnit.php(127): Magento\TestFramework\EventManager->fireEvent('startTest', Array)
#83 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php(440): Magento\TestFramework\Event\PhpUnit->startTest(Object(Magento\AdvancedPricingImportExport\Model\Export\AdvancedPricingTest))
#84 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php(663): PHPUnit\Framework\TestResult->startTest(Object(Magento\AdvancedPricingImportExport\Model\Export\AdvancedPricingTest))
#85 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(968): PHPUnit\Framework\TestResult->run(Object(Magento\AdvancedPricingImportExport\Model\Export\AdvancedPricingTest))
#86 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#87 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#88 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#89 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#90 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(651): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#91 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(144): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#92 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#93 /var/www/html/vendor/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
#94 /var/www/html/vendor/bin/phpunit(123): include('/var/www/html/v...')
#95 {main}

=== Memory Usage System Stats ===

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by francesco-di-marcantonio** [comment]
@magento give me 2.4-develop instance

**Comment by francesco-di-marcantonio** [comment]
still not working the integraiton test

**Comment by engcom-November** [comment]
Hello @francesco-di-marcantonio,

Thank you for the report!

In our case we were not able to reproduce this issue on 2.4-develop.
There might be an issue in your codebase, please re-verify why the product is not being saved by the data fixture.
Let us know if the issue persist.

Thank you.

**Comment by engcom-November** [comment]
Hello @francesco-di-marcantonio,

As there is no activity on this issue for a long time, we believe the issue has been resolved, hence closing this issue.
Feel free to raise a new issue or reopen this if you need more assistance.

Thank you.
