### ISSUE TITLE
Implement PHP 8.2 `SensitiveParameter` to redact sensitive/password data in backtraces.

### ISSUE THREAD

**Issue by convenient** [magento/magento2#38142]
### Summary

Currently if an exception is thrown while handling a sensitive parameter, part of that parameter is exposed in a stack trace.

We could enable `zend.exception_ignore_args` to turn off all the arguments from the traces, but that would affect the ability to support the sites and debug issues as we'd have no data.

As of PHP 8.2 there is support to provide annotations to function parameters to ensure they're excluded from back traces for this exact purpose.

It looks like

```php
function test(
    $foo,
    #[\SensitiveParameter] $bar,
    $baz
) {
```

And would prevent the contents of `$bar` being exposed in any traces

### Examples

For example it looks like this at a basic level
```php
<?php
class Example
{
    public function login($username, $password)
    {
        throw new \Exception('something unexpected happened');
    }
}

(new Example)->login('SomeCoolUsername', 'SomeCoolerPassword12345');
```
```log
PHP Fatal error:  Uncaught Exception: something unexpected happened in /Users/lukerodgers/src/example.php:6
Stack trace:
#0 /Users/lukerodgers/src/example.php(10): Example->login('SomeCoolUsernam...', 'SomeCoolerPassw...')
#1 {main}
  thrown in /Users/lukerodgers/src/example.php on line 6
```

See the the log contains `SomeCoolerPassw` which is not my full example password, but it is a lot.

The extensible nature of Magento means this kind of thing can happen in many core places

For example inside `performIdentityCheck` if someone had hooked into the observer `admin_user_authenticate_after` with some flaky logic that could trigger an exception, it could cause this function to fail like in the above demo.

This would result in part of the password being exposed in the logs

https://github.com/magento/magento2/blob/1819863b2045c78c9a258dfa230a6632f8afa9fd/app/code/Magento/User/Model/User.php#L965-L997

### Proposed solution

When it becomes time to drop PHP 8.1 support add `#[\SensitiveParameter] ` to all password / token fields in the codebase.

- https://wiki.php.net/rfc/redact_parameters_in_back_traces
- https://github.com/php/php-src/commit/90851977348cbb8c65fce19a1670868422414fae

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by convenient** [comment]
Here's a rector rule for anyone wanting to add to their codebase https://github.com/rectorphp/rector/blame/main/docs/rector_rules_overview.md#addsensitiveparameterattributerector

**Comment by convenient** [comment]
@engcom-Hotel While PHP 8.1 does not support this functionality, I do not believe that prevents this moving along. It would simply not take effect until PHP 8.2.

See this example file has `#[\SensitiveParameter] $password` in the function declaration

```php
// example.php
<?php
class Example
{

    public function login($username, #[\SensitiveParameter] $password)
    {
        throw new \Exception('something unexpected happened');
    }
}

(new Example)->login('SomeCoolUsername', 'SomeCoolerPassword12345');
```

### PHP 8.1
Runs as normal, still shows `SomeCoolerPassw...`

```
$ /opt/homebrew/opt/amp-php@8.1/bin/php example.php
PHP Fatal error:  Uncaught Exception: something unexpected happened in /Users/lukerodgers/example.php:7
Stack trace:
#0 /Users/lukerodgers/example.php(11): Example->login('SomeCoolUsernam...', 'SomeCoolerPassw...')
#1 {main}
  thrown in /Users/lukerodgers/example.php on line 7

Fatal error: Uncaught Exception: something unexpected happened in /Users/lukerodgers/example.php:7
Stack trace:
#0 /Users/lukerodgers/example.php(11): Example->login('SomeCoolUsernam...', 'SomeCoolerPassw...')
#1 {main}
  thrown in /Users/lukerodgers/example.php on line 7
```

### PHP 8.2
Runs as normal, shows `Object(SensitiveParameterValue)`

```
$ /opt/homebrew/opt/amp-php@8.2/bin/php example.php
PHP Fatal error:  Uncaught Exception: something unexpected happened in /Users/lukerodgers/example.php:7
Stack trace:
#0 /Users/lukerodgers/example.php(11): Example->login('SomeCoolUsernam...', Object(SensitiveParameterValue))
#1 {main}
  thrown in /Users/lukerodgers/example.php on line 7

Fatal error: Uncaught Exception: something unexpected happened in /Users/lukerodgers/example.php:7
Stack trace:
#0 /Users/lukerodgers/example.php(11): Example->login('SomeCoolUsernam...', Object(SensitiveParameterValue))
#1 {main}
  thrown in /Users/lukerodgers/example.php on line 7
```

**Comment by tr33m4n** [comment]
This is potentially blocked by https://github.com/laminas/laminas-code/pull/145. Magento's code generation will not currently create attributes in `\Magento\Framework\Interception\Code\Generator\Interceptor` when intercepting a class, leaving generated parameters in stack traces un-obscured. The underlying Laminas library doesn't support attributes currently, and the open PR to add this seems to have lost traction. We may need to patch/extend the library ourselves or gently encourage https://github.com/laminas/laminas-code/pull/145 to be merged haha
