### ISSUE TITLE
The consumer isn't authorized to access %resources. Magento 2.4.5-p1 on staging environment

### ISSUE THREAD

**Issue by nilaykumardeveloper** [magento/magento2#38426]
### Summary

In the testing environment, it gives below errors,

    {
    "message": "The consumer isn't authorized to access %resources.",
    "parameters": {
        "resources": "Magento_Sales::actions_view"
    },
    "trace": "#0 /var/www/html/vendor/magento/module-webapi/Controller/Rest/RequestValidator.php(68): Magento\\Webapi\\Controller\\Rest\\RequestValidator->checkPermissions()\n#1 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest\\RequestValidator->validate()\n#2 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\RequestValidator\\Interceptor->___callParent('validate', Array)\n#3 /var/www/html/vendor/paypal/module-braintree-core/Plugin/RestValidationPlugin.php(86): Magento\\Webapi\\Controller\\Rest\\RequestValidator\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#4 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): PayPal\\Braintree\\Plugin\\RestValidationPlugin->aroundValidate(Object(Magento\\Webapi\\Controller\\Rest\\RequestValidator\\Interceptor), Object(Closure))\n#5 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\RequestValidator\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#6 /var/www/html/generated/code/Magento/Webapi/Controller/Rest/RequestValidator/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\RequestValidator\\Interceptor->___callPlugins('validate', Array, NULL)\n#7 /var/www/html/vendor/magento/module-webapi/Controller/Rest/InputParamsResolver.php(108): Magento\\Webapi\\Controller\\Rest\\RequestValidator\\Interceptor->validate()\n#8 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver->resolve()\n#9 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver\\Interceptor->___callParent('resolve', Array)\n#10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#11 /var/www/html/generated/code/Magento/Webapi/Controller/Rest/InputParamsResolver/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver\\Interceptor->___callPlugins('resolve', Array, Array)\n#12 /var/www/html/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(85): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver\\Interceptor->resolve()\n#13 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(195): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#14 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#17 /var/www/html/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#18 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#19 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\\Framework\\App\\Http->launch()\n#20 /var/www/html/pub/index.php(30): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#21 {main}"
}

Its already Yes in: Allow OAuth Access Tokens.

I tried it in PHP script with Integration user as well as bearer token and not working in both scenario. The main thing is that live and local environment looks fine with same code file and DB setup.

**So my concern is that, Is any configuration on server can impact on this?**

PHP script:

    <?php  
 function sign($method, $url, $data, $consumerSecret, $tokenSecret)  
 {  
      $url = urlEncodeAsZend($url);  
      $data = urlEncodeAsZend(http_build_query($data, '', '&'));  
      $data = implode('&', [$method, $url, $data]);  
      $secret = implode('&', [$consumerSecret, $tokenSecret]);  
      return base64_encode(hash_hmac('sha256', $data, $secret, true));  
 }  
 function urlEncodeAsZend($value)  
 {  
      $encoded = rawurlencode($value);  
      $encoded = str_replace('%7E', '~', $encoded);  
      return $encoded;  
 }  
// REPLACE WITH YOUR ACTUAL DATA OBTAINED WHILE CREATING NEW INTEGRATION

$consumerKey = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX';
$consumerSecret = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX';
$accessToken = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX';
$accessTokenSecret = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX';
 $method = 'GET';  
 $url = 'http://xxxx.staging.com/rest/V1/orders/38024';  
   
 $data = [  
      'oauth_consumer_key' => $consumerKey,  
      'oauth_nonce' => md5(uniqid(rand(), true)),  
      'oauth_signature_method' => 'HMAC-SHA256',  
      'oauth_timestamp' => time(),  
      'oauth_token' => $accessToken,  
      'oauth_version' => '1.0',  
 ];  
 $data['oauth_signature'] = sign($method, $url, $data, $consumerSecret, $accessTokenSecret);  
 //print_r($data);
 $curl = curl_init();  
 curl_setopt_array($curl, [  
   CURLOPT_RETURNTRANSFER => 1,  
   CURLOPT_URL => $url,  
      CURLOPT_HTTPHEADER => [  
           'Authorization: OAuth ' . http_build_query($data, '', ',')  
      ]  
 ]);  
 $result = curl_exec($curl);
 $orderData = json_decode($result,true);
 curl_close($curl);  
 echo '<pre>';
 print_r($result);
 echo '</pre>';

?>
POSTMAN:
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/cWfil.png

### Examples

`
<?php  
 function sign($method, $url, $data, $consumerSecret, $tokenSecret)  
 {  
      $url = urlEncodeAsZend($url);  
      $data = urlEncodeAsZend(http_build_query($data, '', '&'));  
      $data = implode('&', [$method, $url, $data]);  
      $secret = implode('&', [$consumerSecret, $tokenSecret]);  
      return base64_encode(hash_hmac('sha256', $data, $secret, true));  
 }  
 function urlEncodeAsZend($value)  
 {  
      $encoded = rawurlencode($value);  
      $encoded = str_replace('%7E', '~', $encoded);  
      return $encoded;  
 }  
// REPLACE WITH YOUR ACTUAL DATA OBTAINED WHILE CREATING NEW INTEGRATION

$consumerKey = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX';
$consumerSecret = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX';
$accessToken = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX';
$accessTokenSecret = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX';
 $method = 'GET';  
 $url = 'http://xxxx.staging.com/rest/V1/orders/38024';  
   
 $data = [  
      'oauth_consumer_key' => $consumerKey,  
      'oauth_nonce' => md5(uniqid(rand(), true)),  
      'oauth_signature_method' => 'HMAC-SHA256',  
      'oauth_timestamp' => time(),  
      'oauth_token' => $accessToken,  
      'oauth_version' => '1.0',  
 ];  
 $data['oauth_signature'] = sign($method, $url, $data, $consumerSecret, $accessTokenSecret);  
 //print_r($data);
 $curl = curl_init();  
 curl_setopt_array($curl, [  
   CURLOPT_RETURNTRANSFER => 1,  
   CURLOPT_URL => $url,  
      CURLOPT_HTTPHEADER => [  
           'Authorization: OAuth ' . http_build_query($data, '', ',')  
      ]  
 ]);  
 $result = curl_exec($curl);
 $orderData = json_decode($result,true);
 curl_close($curl);  
 echo '<pre>';
 print_r($result);
 echo '</pre>';

?>`
I tried it in the PHP script with the Integration user as well as the bearer token and it did not work in both scenarios. The main thing is that the live and local environment looks fine with the same code file and DB setup.

So my concern is that, Is any configuration on server can impact on this?

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @nilaykumardeveloper,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the attached screenshots.

![Screenshot from 2024-02-07 14-20-35](https://github.com/magento/magento2/assets/51680745/b1e9c4f2-a9af-4d06-a225-8eccffa23be4)


We have given access for all the resources still we are getting the error.

Hence Confirming the issue.

Thanks.

**Comment by nilaykumardeveloper** [comment]
Sure! If anyone has any suggestions, please let me know. Your input would be greatly appreciated.

**Comment by thomas-kl1** [comment]
Related issue: https://github.com/magento/magento2/issues/36811

**Comment by thomas-kl1** [comment]
It seems that since a specific version of Magento, integrations must be secured to be used.
It means you have to setup a identity URL, a callback url and provide an email to your integration.

**Comment by WCL-joejones** [comment]
HI Guys

just wondering if theres any time estimation on this?

Kind Regards,
Joe

**Comment by bkuermayr** [comment]
need a fix on this too

**Comment by siliconalchemy** [comment]
@engcom-Bravo - has there been any internal development on this issue, is there a workaround?  It has completely broken integration with Magento for me, it's a really major bug.

**Comment by luka4** [comment]
Looks like issue is related to when your storefront URL is not same as your base url at "All Stores View".
For me it is still actual for 2.4.6-p4 EE

**Comment by craig-bartlett** [comment]
> Looks like issue is related to when your storefront URL is not same as your base url at "All Stores View". For me it is still actual for 2.4.6-p4 EE

Same for me on 2.4.5-p8 CE. Base URL is fine but storefront URL throws the error.

**Comment by lionalex** [comment]
There is not a solution? WIth magento 2.4.7 and 2.4.6 same error. Is really important bug.

**Comment by siliconalchemy** [comment]
> Looks like issue is related to when your storefront URL is not same as your base url at "All Stores View". For me it is still actual for 2.4.6-p4 EE

This occurs for all store URLs for me.

> There is not a solution? WIth magento 2.4.7 and 2.4.6 same error. Is really important bug.

Seems insane that this major bug isn't being addressed.  This is an open issue, P2 priority, confirmed, reproduced and sitting in high priority backlog for nearly half a year.

As a workaround, I hack vendor/magento/module-webapi/Controller/Rest/RequestValidator.php, and add an extra validator:
```
        $headers = $this->request->getHeaders()->toString();
        if (str_contains($headers, 'changethispasswordtoarandomsetofsquiggles')) {
            return;
        }
```

And then when I make a REST call, I add an extra header in the call:
```
            res = requests.get(
                url+"?"+urlparam, verify=self._verify_ssl,
                headers={
                    'Authorization': 'Bearer %s' % self._token,
                    'TempAuth': 'changethispasswordtoarandomsetofsquiggles',
                })
```

Obviously this isn't ideal as it's a reusable symmetric cleartext password and bypasses finegrained ACL, but at least it works for now..

**Comment by Paulsky** [comment]
Any update on this?

**Comment by Paulsky** [comment]
The only **workaround** I now see is the following. If you use the option 'Allow OAuth Access Tokens to be used as standalone Bearer tokens'. **And you trust the integration party**. You can bypass the (false negative) exception. I would ask the third party for their IP's and do the following:

Inside module-webapi/Controller/Rest/RequestValidator.php change 'checkPermissions()' and add a custom function:

```
/**
     * Perform authentication and authorization.
     *
     * @return void
     * @throws \Magento\Framework\Exception\AuthorizationException
     */
    private function checkPermissions()
    {
        $route = $this->router->match($this->request);
        if (!$this->authorization->isAllowed($route->getAclResources())) {

            //CUSTOM
            if ($this->isFullyTrustedToken()) {
                return;
            }

            $params = ['resources' => implode(', ', $route->getAclResources())];
            throw new AuthorizationException(
                __("The consumer isn't authorized to access %resources.", $params)
            );
        }
    }

    /**
     * CUSTOM
     * 
     * @return bool
     */
    private function isFullyTrustedToken()
    {
        $trustedTokens = [
            'token1' => ['ip1', 'ip2'], //integration 1
            'token2' => ['ip1', 'ip3']  //integration 2
        ];

        //See module-webapi/Model/Authorization/TokenUserContext processRequest()
        $authorizationHeaderValue = $this->request->getHeader('Authorization');
        if (!$authorizationHeaderValue) {
            return false;
        }

        $headerPieces = explode(" ", $authorizationHeaderValue);
        if (count($headerPieces) !== 2) {
            return false;
        }

        $tokenType = strtolower($headerPieces[0]);
        if ($tokenType !== 'bearer') {
            return false;
        }

        $bearerToken = $headerPieces[1];

        //See framework/HTTP/PhpEnvironment/Request.php getClientIp()
        $clientIp = $this->request->getClientIp();

        // Check if token exists and IP is allowed for that token
        if (isset($trustedTokens[$bearerToken]) && in_array($clientIp, $trustedTokens[$bearerToken])) {
            return true;
        }

        return false;
    }
```

Needless to say; **be careful**. I do not have tested this a lot. Use at your own risk.

**Comment by fabianaromagnoli** [comment]
I had the same issue when upgrading from Magento 2.4.2 to 2.4.7. From what I understand, security has been reinforced in the latest versions, and OAuth tokens can no longer be used as Bearer tokens by default. You need to [explicitly change the settings](https://developer.adobe.com/commerce/webapi/get-started/authentication/gs-authentication-token/#:~:text=However%2C%20while%20it%20is%20not%20recommended%2C%20this%20behavior%20can%20be%20restored%20in%20the%20Admin%20by%20setting%20the%20Stores%20%3E%20Configuration%20%3E%20Services%20%3E%20OAuth%20%3E%20Consumer%20Settings%20%3E%20Allow%20OAuth%20Access%20Tokens%20to%20be%20used%20as%20standalone%20Bearer%20tokens%20option%20to%20Yes.) to allow this behavior.

**Comment by lbajsarowicz** [comment]
fabianaromagnoli explained on 2025-04-14 that this is intentional security hardening: OAuth tokens are no longer usable as bearer tokens by default, and there's a documented setting to re-enable that. Can you confirm whether you've tried that setting, and if it doesn't resolve the issue, what error you get with it enabled?

**Comment by siliconalchemy** [comment]
This happens to me even with `oauth/consumer/enable_integration_as_bearer` set to 1, OP stated the same.

**Comment by siliconalchemy** [comment]
In addition this was confirmed by engcom-Bravo back in 2024.
