### ISSUE TITLE
DI compile failure after 2.4.4-p8 update

### ISSUE THREAD

**Issue by chazzs** [magento/magento2#38704]
### Summary

immediately after doing a composer update to magento 2.4.4-p8. code base will no longer compile with `setup:di:compile`

compiling completed successfully prior to upgrade then fails after.

`syntax error, unexpected '|', expecting ';' or '{'#0 /home/application/html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/home/applicati...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('PayPal\\Braintre...')
#2 [internal function]: spl_autoload_call('PayPal\\Braintre...')
#3 /home/application/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('PayPal\\Braintre...')
#4 /home/application/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('PayPal\\Braintre...', '/home/applicati...')
#5 /home/application/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract(Object(RecursiveIteratorIterator))
#6 /home/application/html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList('/home/applicati...')
#7 /home/application/html/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#8 /home/application/html/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process(Object(Closure), Object(Closure))
#9 /home/application/html/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/application/html/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/application/html/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DiCompileCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/application/html/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/application/html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/application/html/bin/magento(23): Symfony\Component\Console\Application->run()
#15 {main}
`

PHP 7.4.26 (cli) (built: Nov 18 2021 16:46:20) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with the ionCube PHP Loader + ionCube24 v11.0.0, Copyright (c) 2002-2021, by ionCube Ltd.
    with Zend OPcache v7.4.26, Copyright (c), by Zend Technologies
    with Xdebug v3.1.1, Copyright (c) 2002-2021, by Derick Rethans

### Examples

The system was funcitonal, operating and di:compile finished successfuly.  Then, to upgtade:

1. I edited composer.json and updates the required item `"magento/product-community-edition": "2.4.4-p4"` to `"magento/product-community-edition": "2.4.4-p8"`.  
2.  ran `compoer2 u` (after back up of functional composer.lock)
3. composer upgrade finishes successfully
4. ran `bin/magento setup:di:compile`
5. at step 1/9, the failure happens with a pretty useless stack trace or indications as to where this problem was found.  from the looks of it the Braintree module is not compatible with this new update?

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by chazzs** [comment]
@magento give me 2.4.4-p4-develop instance

**Comment by engcom-Dash** [comment]
Hi @chazzs 

Thanks for reporting and collaboration.

Verified the issue after upgrading the instance from 2.4.4-p4 to 2.4.4-p8 and the issue is reproducible.

Hence, confirming this issue.

setup:di:compile is failing with the below error:

1/9 [==>------------------]  11% 1 sec 117.0 MiBsyntax error, unexpected '|', expecting ';' or '{'#0 /usr/local/var/www/magento7/magento7/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/usr/local/var/...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('PayPal\\Braintre...')
#2 [internal function]: spl_autoload_call('PayPal\\Braintre...')
#3 /usr/local/var/www/magento7/magento7/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('PayPal\\Braintre...')
#4 /usr/local/var/www/magento7/magento7/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('PayPal\\Braintre...', '/usr/local/var/...')
#5 /usr/local/var/www/magento7/magento7/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract(Object(RecursiveIteratorIterator))
#6 /usr/local/var/www/magento7/magento7/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList('/usr/local/var/...')
#7 /usr/local/var/www/magento7/magento7/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#8 /usr/local/var/www/magento7/magento7/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process(Object(Closure), Object(Closure))
#9 /usr/local/var/www/magento7/magento7/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /usr/local/var/www/magento7/magento7/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /usr/local/var/www/magento7/magento7/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DiCompileCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /usr/local/var/www/magento7/magento7/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /usr/local/var/www/magento7/magento7/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /usr/local/var/www/magento7/magento7/bin/magento(23): Symfony\Component\Console\Application->run()
#15 {main}

Please refer the attached screenshot.

<img width="1440" alt="Screenshot 2024-05-08 at 6 28 51 PM" src="https://github.com/magento/magento2/assets/60198592/767fd154-e3e7-4281-a00d-ec77480d4e5b">

**Comment by chazzs** [comment]
I was playing around with this a little in the evening. switched from php7.4 to php8.1 and it was happy to compile.  Is php8 now required for this patch?

**Comment by ihor-sviziev** [comment]
@chazzs, according to system requirements, has been required since Magento 2.4.4 https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/system-requirements

**Comment by engcom-Dash** [comment]
Hi @chazzs 

As per the internal discussion, we are keeping this issue on hold. 

While installing 2.4.4-p4 we are getting errors.

We will update the ticket in a few days.

**Comment by hostep** [comment]
I think this duplicates:
- https://github.com/magento/magento2/issues/37935 (reported against 2.4.4-p5)
- https://github.com/magento/magento2/issues/38150 (reported against 2.4.5-p2)

I would still consider it a bug that you are allowed by composer to install these packages using PHP 7.4, but given that this still hasn't been solved in the latest patch release, I think it means that Adobe has given up on installations running PHP 7.4 and it's indeed time to move to 8.1
