### ISSUE TITLE
GraphQL OPTIONS request fails with error 500.

### ISSUE THREAD

**Issue by william-gooch** [magento/magento2#38738]
### Preconditions and environment

- Magento 2.4.7

### Steps to reproduce

1. Attempt to make an OPTIONS request against the GraphQL endpoint `curl -i -X OPTIONS http://test.site/graphql`

### Expected result

Returns the "unexpected EOF" error but with a 200 status code so that CORS requests succeed.

### Actual result

Returns the "unexpected EOF" error with a 500 status code, so CORS preflight requests always fail.

### Additional information

This seems like it re-introduces MDVA-35312 which was previously fixed in Magento 2.4.3.
I believe this is caused by https://github.com/magento/magento2/blame/c6bc8300e771e5e96ce9ac6c116746fe3de80544/app/code/Magento/GraphQl/Controller/GraphQl.php#L194 which parses the query and returns an error even if the request validators succeed.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by william-gooch** [comment]
@magento give me 2.4-develop instance

**Comment by william-gooch** [comment]
Confirmed to occur on 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @aaqtgft ,

Verified the issue on 2.4.7 and 2.4-develop, it is reproducible.

Hence, Confirming the issue.

Steps to reproduce:-

1. Attempt to make an OPTIONS request against the GraphQL endpoint curl -i -X OPTIONS http://test.site/graphql


2.4.7


<img width="1428" alt="Screenshot 2024-05-22 at 4 00 27 PM" src="https://github.com/magento/magento2/assets/51681379/da705dae-1cbb-40b1-88a5-29443209b575">


2.4-develop


<img width="1410" alt="Screenshot 2024-05-22 at 4 00 49 PM" src="https://github.com/magento/magento2/assets/51681379/03b41f35-4dff-4b48-a9fb-ef1f2f5ce1f0">

**Comment by Detzler** [comment]
Just upgraded from 2.4.6-p6 to 2.4.7-p1. Bug appeared under 2.4.7.

**Comment by lano-vargas** [comment]
Any updates/patch next release on the issue? 

I get the following error in the exception.log

`Next Exception: Report ID: graph-ql-66acbdf8dc7a9; Message: Syntax Error: Unexpected <EOF> in /var/www/vhosts/test.com/htdocs/vendor/magento/framework/GraphQl/Exception/ExceptionFormatter.php:64
Stack trace:
#0 /var/www/vhosts/test.com/htdocs/generated/code/Magento/Framework/GraphQl/Exception/ExceptionFormatter/Interceptor.php(23): Magento\Framework\GraphQl\Exception\ExceptionFormatter->create()
#1 /var/www/vhosts/test.com/htdocs/vendor/magento/module-graph-ql/Controller/GraphQl.php(210): Magento\Framework\GraphQl\Exception\ExceptionFormatter\Interceptor->create()
#2 /var/www/vhosts/test.com/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\GraphQl\Controller\GraphQl->dispatch()
#3 /var/www/vhosts/test.com/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\GraphQl\Controller\GraphQl\Interceptor->___callParent()
#4 /var/www/vhosts/test.com/htdocs/vendor/fastly/magento2/Model/FrontControllerPlugin.php(135): Magento\GraphQl\Controller\GraphQl\Interceptor->Magento\Framework\Interception\{closure}()
#5 /var/www/vhosts/test.com/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Fastly\Cdn\Model\FrontControllerPlugin->aroundDispatch()
#6 /var/www/vhosts/test.com/htdocs/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(72): Magento\GraphQl\Controller\GraphQl\Interceptor->Magento\Framework\Interception\{closure}()
#7 /var/www/vhosts/test.com/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#8 /var/www/vhosts/test.com/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\GraphQl\Controller\GraphQl\Interceptor->Magento\Framework\Interception\{closure}()
#9 /var/www/vhosts/test.com/htdocs/generated/code/Magento/GraphQl/Controller/GraphQl/Interceptor.php(23): Magento\GraphQl\Controller\GraphQl\Interceptor->___callPlugins()
#10 /var/www/vhosts/test.com/htdocs/vendor/magento/framework/App/Http.php(116): Magento\GraphQl\Controller\GraphQl\Interceptor->dispatch()
#11 /var/www/vhosts/test.com/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#12 /var/www/vhosts/test.com/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent()
#13 /var/www/vhosts/test.com/htdocs/vendor/magento/module-application-performance-monitor/Plugin/ApplicationPerformanceMonitor.php(38): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#14 /var/www/vhosts/test.com/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch()
#15 /var/www/vhosts/test.com/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#16 /var/www/vhosts/test.com/htdocs/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins()
#17 /var/www/vhosts/test.com/htdocs/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#18 /var/www/vhosts/test.com/htdocs/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#19 {main} {"exception":"[object] (Exception(code: 0): Report ID: graph-ql-66acbdf8dc7a9; Message: Syntax Error: Unexpected <EOF> at /var/www/vhosts/test.com/htdocs/vendor/magento/framework/GraphQl/Exception/ExceptionFormatter.php:64)
[previous exception] [object] (GraphQL\\Error\\SyntaxError(code: 0): Syntax Error: Unexpected <EOF> at /var/www/vhosts/test.com/htdocs/vendor/webonyx/graphql-php/src/Language/Parser.php:433)"} []`

**Comment by skaliszczak** [comment]
**Expected result should be** 
   Returns the "unexpected EOF" error but with a **400** status code.

500 is an unexpected server error - it indicates that something needs to be fixed on the server side
400 Bad Request - it indicates that it is an error on the client side with the badly prepared request which is our case.
200 means that everything is ok, definitely it is not OK, graphql always requires some body in request

**Comment by senthilengg** [comment]
Its due to https://github.com/magento/magento2/blob/2.4.7/app/code/Magento/GraphQl/Controller/GraphQl.php#L219 and you can replace ` if (!isset($data['query']) || strpos($data['query'], 'IntrospectionQuery') === false)` 

**with**  `if (strpos($query, 'IntrospectionQuery') === false)`

**Comment by engcom-Bravo** [comment]
Hi @william-gooch,

Thanks for your reporting and collaboration.

We have tried to reproduce the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1160" alt="Image" src="https://github.com/user-attachments/assets/d381a22b-915c-4771-99e6-5d80a850bca0" />



Hence we are closing this issue.

Thanks.
