### ISSUE TITLE
Magento_Paypal module has dependency on Magento_Csp module

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#38764]
### Preconditions and environment

- Magento Open Source 2.4.7

### Steps to reproduce

This file has a dependency on Magento_Csp: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Paypal/Model/Config.php#L9

However it's not listed in the modules module.xml.

### Expected result

Do not use Magento_Csp in module, or declare it as a dependency in the module.xml

### Actual result

When Magento_Csp is disabled product detail pages throw an error because of the missing dependency: 

==> exception.log <==
[2024-05-28T09:50:40.591031+00:00] main.CRITICAL: Error: Cannot instantiate interface Magento\Csp\Model\Collector\MergerInterface in vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121
Stack trace:
#0 vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#1 vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create()
#2 vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get()
#3 vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create()
#4 vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get()
#5 vendor/magento/framework/ObjectManager/ObjectManager.php(73): Magento\Framework\ObjectManager\Factory\Compiled->create()
#6 vendor/magento/module-paypal/Model/Config.php(642): Magento\Framework\ObjectManager\ObjectManager->get()
#7 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Paypal\Model\Config->__construct()
#8 vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#9 vendor/magento/framework/ObjectManager/ObjectManager.php(59): Magento\Framework\ObjectManager\Factory\Compiled->create()
#10 generated/code/Magento/Paypal/Model/ConfigFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create()
#11 vendor/magento/module-paypal/Model/PayLaterConfig.php(46): Magento\Paypal\Model\ConfigFactory->create()

### Additional information

As `Magento_Csp` module cannot be disabled with 2.4.7 as it is tightly integrated, this issue can be reproduced by disabling the `Magento_Csp` module in 2.4.6 and upgrade it to 2.4.7.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @dverkade,

Thank you for the report and collaboration!

We were not able to reproduce this issue on 2.4.7 community edition and 2.4-develop.
Because the `Magento_Csp` module is a required dependency in composer.json file of Paypal module.
<img width="419" alt="image" src="https://github.com/magento/magento2/assets/60198231/7f24d68d-e689-4b27-9d91-3fea2b9e9c66">

So whenever we try to disable `Magento_Csp` module it will throw below error:
```
Unable to change status of modules because of the following constraints:
Cannot disable Magento_Csp because modules depend on it:
Magento_Paypal: Magento_Paypal->Magento_Csp
```

Please let us know if we are missing something on this.

Thank you.

**Comment by hostep** [comment]
@dverkade: I've created https://github.com/baldwin-agency/magento2-module-csp-shim last week, if you at the moment don't want to use the CSP module and want to have a working Magento 2.4.7 project.

**Comment by leonhelmus** [comment]
@hostep Thanks for adding this module!

**Comment by NateSwanson7** [comment]
> Hello @dverkade,
> 
> Thank you for the report and collaboration!
> 
> We were not able to reproduce this issue on 2.4.7 community edition and 2.4-develop. Because the `Magento_Csp` module is a required dependency in composer.json file of Paypal module. <img alt="image" width="419" src="https://private-user-images.githubusercontent.com/60198231/334728199-7f24d68d-e689-4b27-9d91-3fea2b9e9c66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzQwMTIsIm5iZiI6MTcxODYzMzcxMiwicGF0aCI6Ii82MDE5ODIzMS8zMzQ3MjgxOTktN2YyNGQ2OGQtZTY4OS00YjI3LTlkOTEtM2ZlYTJiOWU5YzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE0MTUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmOTc3MzUyZTkzZDljYTI5NWI2OWVlN2JiOTVjODhmNTkxZmY1Y2NkNDNhMWNlYzE4OWU5M2NjZDgzNzY0NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bK9OmR-XD3h40ODNNz4SoKbkQ76mJ5DeBHzpW-hTGCE">
> 
> So whenever we try to disable `Magento_Csp` module it will throw below error:
> 
> ```
> Unable to change status of modules because of the following constraints:
> Cannot disable Magento_Csp because modules depend on it:
> Magento_Paypal: Magento_Paypal->Magento_Csp
> ```
> 
> Please let us know if we are missing something on this.
> 
> Thank you.

@engcom-November that's true, but if you already have the `Magento_Csp` module disabled you'll run into the error mentioned in the ticket description. I also get it when trying to view the payment methods in the admin config, and when trying to place an order.

**Comment by sprajapat770** [comment]
@engcom-November  getting similar error , currently we are not using CSP module

Error: Cannot instantiate interface Magento\Csp\Model\Collector\MergerInterface in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121

**Comment by engcom-November** [comment]
Hello @dverkade,

Thank you for the report and collaboration!

We are to to reproduce this issue with 2.4.6 and upgrading it to 2.4.7.
Disabled the `Magento_Csp` module in 2.4.6 and after updating it to 2.4.7, we got the below error:
```
main.CRITICAL: Error: Cannot instantiate interface Magento\Csp\Model\Collector\MergerInterface in /opt/homebrew/var/www/magento246p5ce/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121
```

Hence confirming this issue.

Thanks.

**Comment by magentoabu** [comment]
@magento I'm working on this

**Comment by lbajsarowicz** [comment]
Paypal/Model/Config.php still imports Magento\Csp\Helper\CspNonceProvider at line 9, and module.xml's sequence is missing Magento_Csp; PR #39450 was closed unmerged. A related issue (#39104) reports the same error from a different file in module-payment-services-paypal, kept as related, not a duplicate. Please re-QA on current 2.4-develop to confirm the missing sequence entry is still the cause and whether both files need the fix.
