### ISSUE TITLE
Updating from version 2.4.7 to 2.4.7-p1

### ISSUE THREAD

**Issue by sgeleon** [magento/magento2#38874]
### Preconditions and environment

Updating from version 2.4.7 to 2.4.7-p1

My composer file:

```
{
    "name": "XXX",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "version": "2.4.5",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "magento/magento-composer-installer": true,
            "laminas/laminas-dependency-plugin": true,
            "cweagans/composer-patches": true,
            "magento/composer-dependency-version-audit-plugin": true,
            "php-http/discovery": true
        }
    },
    "require": {
        "addressfinder/module-magento2": "2.*",
        "algolia/algoliasearch-magento-2": "3.8.1",
        "amasty/module-google-rich-snippets": "1.*",
        "creativestyle/magesuite-magepack": "1.*",
        "cweagans/composer-patches": "1.*",
        "ethanyehuda/magento2-cronjobmanager": "1.*",
        "experius/module-emailcatcher": "3.*",
        "fooman/sameorderinvoicenumber-m2": "3.*",
        "hubspot/hubspot-php": "5.*",
        "jalogut/magento2-deployer-plus": "2.*",
        "justbetter/magento2-sentry": "^3.4",
        "klaviyo/api": "5.1",
        "laminas/laminas-serializer": "2.*",
        "magento/product-community-edition": "2.4.7-p1",
        "mirasvit/module-cache-warmer": "*",
        "mirasvit/module-credit": "1.*",
        "mirasvit/module-indexer": "*",
        "mirasvit/module-kb": "*",
        "mirasvit/module-rma": "*",
        "onestepcheckout/iosc": "1.*",
        "snowdog/module-menu": "2.*",
        "xtento/customtrackers": "2.*",
        "xtento/module-stockimport": "2.*",
        "xtento/orderexport": "2.*",
        "xtento/orderimport": "2.*",
        "xtento/pdfcustomizer": "2.*",
        "xtento/productexport": "2.*",
        "xtento/trackingimport": "2.*",
        "yireo/magento2-replace-inventory": "*"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        },
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\PhpStan\\": "dev/tests/static/framework/Magento/PhpStan/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    
    "extra": {
        "magento-force": "override",
        "composer-exit-on-patch-failure": true,
        "patches": {
            "magento/framework": {
                "MDVA-43395 security patch": "patches/composer/MDVA-43395_framework.patch",
                "MDVA-43443 security patch": "patches/composer/MDVA-43443_EE_2.4.3-p1_COMPOSER_v1-framework.patch",
                "Bug M2.4.4 + php 8.1 static:content:deploy -f": "patches/composer/Bug_M2.4.4_+_php_8.1_static:content:deploy_-f.patch"
            },
            "paypal/module-braintree-core": {
                "Adding variable check to getShippingAddress method": "patches/composer/adding_variable_check_to_getShippingAddress_method.patch"
            },
            "magento/magento2-base": {
                "PHP-error-reporting-level": "patches/composer/PHP-error-reporting-level.patch"
            },
   
        },
        "enable-patching": true,
        "magento-deploy-ignore": {
            "*": [
                "/pub/.htaccess",
                "/.user.ini",
                "/pub/.user.ini",
                "/.gitignore"
            ]
        }
    }
}

```

### Steps to reproduce

1) Update by composer using the next command: 

```
composer require magento/product-community-edition 2.4.7-p1 -W
```
2) Execute bin/magento se:up
3) Get error

### Expected result

Get nothing in command line after execute step 2.

### Actual result

Error

```

There is an error in /var/www/html/vendor/magento/module-inventory-bundle-product-indexer/Indexer/SourceItemIndexerProcessor.php at line: 17
Interface "Magento\InventoryIndexer\Indexer\SourceItem\CompositeProductProcessorInterface" not found#0 /var/www/html/vendor/composer/ClassLoader.php(576): include()
#1 /var/www/html/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/var/www/html/v...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Magento\\Invento...')
#3 /var/www/html/vendor/magento/framework/ObjectManager/Relations/Runtime.php(38): class_exists('Magento\\Invento...')
#4 /var/www/html/vendor/magento/framework/Interception/Config/Config.php(157): Magento\Framework\ObjectManager\Relations\Runtime->has('Magento\\Invento...')
#5 /var/www/html/vendor/magento/framework/Interception/Config/Config.php(180): Magento\Framework\Interception\Config\Config->_inheritInterception('Magento\\Invento...')
#6 /var/www/html/vendor/magento/framework/Interception/Config/Config.php(213): Magento\Framework\Interception\Config\Config->hasPlugins('Magento\\Invento...')
#7 /var/www/html/vendor/magento/framework/Interception/Config/Config.php(190): Magento\Framework\Interception\Config\Config->generateIntercepted(Array)
#8 /var/www/html/vendor/magento/framework/Interception/Config/Config.php(122): Magento\Framework\Interception\Config\Config->initializeUncompiled(Array)
#9 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\Interception\Config\Config->__construct(Object(Magento\Framework\ObjectManager\Config\Reader\Dom\Proxy), Object(Magento\Framework\Config\Scope), Object(Magento\Framework\App\Cache\Type\Config), Object(Magento\Framework\ObjectManager\Relations\Runtime), Object(Magento\Framework\Interception\ObjectManager\Config\Developer), Object(Magento\Framework\ObjectManager\Definition\Runtime), 'interception', NULL, NULL)
#10 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#11 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(73): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#12 /var/www/html/vendor/magento/framework/App/ObjectManager/Environment/Developer.php(84): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#13 /var/www/html/vendor/magento/framework/App/ObjectManagerFactory.php(191): Magento\Framework\App\ObjectManager\Environment\Developer->configureObjectManager(Object(Magento\Framework\Interception\ObjectManager\Config\Developer), Array)
#14 /var/www/html/setup/src/Magento/Setup/Model/ObjectManagerProvider.php(62): Magento\Framework\App\ObjectManagerFactory->create(Array)
#15 /var/www/html/setup/src/Magento/Setup/Model/SearchConfigFactory.php(36): Magento\Setup\Model\ObjectManagerProvider->get()
#16 /var/www/html/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php(144): Magento\Setup\Model\SearchConfigFactory->create()
#17 /var/www/html/vendor/symfony/console/Command/Command.php(326): Magento\Setup\Console\Command\UpgradeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\UpgradeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/magento/framework/Console/Cli.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/symfony/console/Application.php(175): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#23 {main}
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
@sgeleon: please edit your post and remove the `repositories` section, because it's full of passwords you probably don't want to leak to the outside...

**Comment by sgeleon** [comment]
Hi @hostep 

> @sgeleon: please edit your post and remove the repositories section, because it's full of passwords you probably don't want to leak to the outside...

Thank you for your attention.

> As for the issue you are having, if I have to guess, it might be related to yireo/magento2-replace-inventory...
But you should seek help elsewhere, this is a project specific problem, this doesn't seem to be an issue in core Magento code, as many people already have upgraded to 2.4.7-p1 without this error.

I fixed it by change version of magento in **composer.js** and execute: **composer update** 

This bug reproduce then you try update by:

```
composer require magento/product-community-edition 2.4.7-p1 -W
```

**Comment by jorgb90** [comment]
@sgeleon 

Per [Magento Docs](https://experienceleague.adobe.com/en/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade) the command required for update is:

`composer require-commerce magento/product-community-edition 2.4.7-p1 --no-update`

and not

`composer require magento/product-community-edition 2.4.7-p1 -W`

Perhaps that would also fix your error.

**Comment by engcom-Dash** [comment]
Hi @sgeleon 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4.7-p1 after upgrading the instance from Magento 2.4.7.

We can upgrade the instance from 2.4.7 to 2.4.7-p1 successfully 

Please take a look at the screenshots I've attached. Let us know if we missed anything.

After upgrading the instance from 2.4.7 to 2.4.6-p1

<img width="1440" alt="Screenshot 2024-07-01 at 1 43 48 PM" src="https://github.com/magento/magento2/assets/60198592/c8e53785-0efd-4aa3-8122-11126a1434f8">

<img width="1440" alt="Screenshot 2024-07-01 at 1 45 42 PM" src="https://github.com/magento/magento2/assets/60198592/60db9eb1-b300-4a32-bb63-fe79731bb603">

After performing bin/magento setup: upgrade

<img width="1440" alt="Screenshot 2024-07-01 at 1 45 25 PM" src="https://github.com/magento/magento2/assets/60198592/641e9fa9-06ef-459b-8dd9-29bcab5748a5">
<img width="1440" alt="Screenshot 2024-07-01 at 1 45 29 PM" src="https://github.com/magento/magento2/assets/60198592/f684ca83-4baf-4500-ba8e-ed2624e06896">

**Comment by engcom-Dash** [comment]
Hi @sgeleon 

As there is no activity on this issue for a long time, we believe the issue has been resolved, hence closing this issue.
Feel free to raise a new issue or reopen this if you need more assistance.

Thank you.
