### ISSUE TITLE
JS error on the success page

### ISSUE THREAD

**Issue by sgeleon** [magento/magento2#38880]
### Preconditions and environment

- Magento version v2.4.7-p1
- My composer file:
```
{
    "name": "betterbatt/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "version": "2.4.5",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "magento/magento-composer-installer": true,
            "laminas/laminas-dependency-plugin": true,
            "cweagans/composer-patches": true,
            "magento/composer-dependency-version-audit-plugin": true,
            "php-http/discovery": true
        }
    },
    "require": {
        "addressfinder/module-magento2": "2.*",
        "algolia/algoliasearch-magento-2": "3.13.4",
        "amasty/module-google-rich-snippets": "1.*",
        "colinmollenhour/php-redis-session-abstract": "1.5.5",
        "creativestyle/magesuite-magepack": "1.*",
        "cweagans/composer-patches": "1.*",
        "ethanyehuda/magento2-cronjobmanager": "1.*",
        "experius/module-emailcatcher": "3.*",
        "fooman/sameorderinvoicenumber-m2": "3.*",
        "hubspot/hubspot-php": "5.*",
        "jalogut/magento2-deployer-plus": "2.*",
        "justbetter/magento2-sentry": "^3.4",
        "klaviyo/api": "^5.1",
        "laminas/laminas-serializer": "2.*",
        "magento/product-community-edition": "v2.4.7-p1",
        "mirasvit/module-cache-warmer": "*",
        "mirasvit/module-credit": "1.*",
        "mirasvit/module-indexer": "*",
        "mirasvit/module-kb": "*",
        "mirasvit/module-rma": "*",
        "onestepcheckout/iosc": "1.*",
        "snowdog/module-menu": "2.*",
        "xtento/customtrackers": "2.*",
        "xtento/module-stockimport": "2.*",
        "xtento/orderexport": "2.*",
        "xtento/orderimport": "2.*",
        "xtento/pdfcustomizer": "2.*",
        "xtento/productexport": "2.*",
        "xtento/trackingimport": "2.*",
        "yireo/magento2-replace-inventory": "*"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        },
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\PhpStan\\": "dev/tests/static/framework/Magento/PhpStan/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    
    "extra": {
        "magento-force": "override",
        "composer-exit-on-patch-failure": true,
        "patches": {
            
            "magento/framework": {
                "MDVA-43395 security patch": "patches/composer/MDVA-43395_framework.patch",
                "MDVA-43443 security patch": "patches/composer/MDVA-43443_EE_2.4.3-p1_COMPOSER_v1-framework.patch",
                "Bug M2.4.4 + php 8.1 static:content:deploy -f": "patches/composer/Bug_M2.4.4_+_php_8.1_static:content:deploy_-f.patch"

            },
       
         
        },
        "enable-patching": true,
        "magento-deploy-ignore": {
            "*": [
                "/pub/.htaccess"
            ]
        }
    }
}

```

### Steps to reproduce

1. Put something in the basket.
2. Finish process the checkout 
3. On the page checkout/onepage/success/ open dev tools of browser

### Expected result

The console in the browser should be without any error.

### Actual result

I have got the error:
```
customer-data.js:189 Uncaught TypeError: Cannot read properties of undefined (reading 'remove')
    at customer-data.js:189:25
    at Function.each (underscore.js:1330:17)
    at Object.remove (customer-data.js:188:15)
    at Object.invalidate (customer-data.js:359:20)
    at 85476d7025f78c1ee713247d0bb38174.js:3852:18
    at Object.execCb (85476d7025f78c1ee713247d0bb38174.js:1696:33)
    at Module.check (85476d7025f78c1ee713247d0bb38174.js:883:51)
    at Module.<anonymous> (85476d7025f78c1ee713247d0bb38174.js:1139:34)
    at 85476d7025f78c1ee713247d0bb38174.js:134:23
    at 85476d7025f78c1ee713247d0bb38174.js:1189:21
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by codilar-kishan** [comment]
@sgeleon can you tell me what exactly was the fix you made? I am facing the same issue
