### ISSUE TITLE
Unit tests failure

### ISSUE THREAD

**Issue by ksz2013** [magento/magento2#3901]
Hi,

After installing the latest version 2.0.2, and adding one test module which is adding only a new menu in the backend menu, no php functionality is included at all (Just registration.php  in the module and the configuration xml files.)  there are errors after running the unit tests.
(There are no functionality changes, no rewrites, just xml for a new admin menu)

_Issue can be reproduced even with the bare minimal configuration for a custom module._

**Tests trigger by:**
php bin/magento dev:tests:run unit

**Error result after test is finished:**
---- /var/www/m2prod/dev/tests/static/framework/tests/unit> php /var/www/m2prod/./vendor/phpunit/phpunit/phpunit  

PHPUnit 4.1.0 by Sebastian Bergmann.

Configuration read from /var/www/m2prod/dev/tests/static/framework/tests/unit/phpunit.xml.dist

...............................F...F......FFF.................... 65 / 66 ( 98%)
.

Time: 213 ms, Memory: 10.25Mb

There were 5 failures:

1) Magento\TestFramework\Dependency\PhpRuleTest::testGetDependencyInfo with data set "Extend class in different module" ('Magento\AnotherModule\SomeClass', 'something extends \Magento\SomeModule\Any\ClassName {', array(array('Magento\SomeModule', 'hard', 'Magento\SomeModule\Any\ClassName')))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => Array (...)
  )

/var/www/m2prod/dev/tests/static/framework/tests/unit/testsuite/Magento/TestFramework/Dependency/PhpRuleTest.php:42

2) Magento\TestFramework\Dependency\PhpRuleTest::testGetDependencyInfo with data set "Helper class from another module" ('Magento\AnotherModule\SomeClass', '$this->helper("Magento\SomeModule\Any\ClassName")', array(array('Magento\SomeModule', 'hard', 'Magento\SomeModule\Any\ClassName')))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => Array (...)
  )

/var/www/m2prod/dev/tests/static/framework/tests/unit/testsuite/Magento/TestFramework/Dependency/PhpRuleTest.php:42

3) Magento\TestFramework\Dependency\PhpRuleTest::testGetDependencyInfo with data set "Plugin on class in different module" ('Magento\Module1\Plugin2', 'Magento\Module2\Subject', array(array('Magento\Module2', 'soft', 'Magento\Module2\Subject')))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => Array (...)
  )

/var/www/m2prod/dev/tests/static/framework/tests/unit/testsuite/Magento/TestFramework/Dependency/PhpRuleTest.php:42

4) Magento\TestFramework\Dependency\PhpRuleTest::testGetDependencyInfo with data set "Plugin depends on arbitrary class in same module as subject" ('Magento\Module1\Plugin2', 'Magento\Module2\NotSubject', array(array('Magento\Module2', 'soft', 'Magento\Module2\NotSubject')))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => Array (...)
  )

/var/www/m2prod/dev/tests/static/framework/tests/unit/testsuite/Magento/TestFramework/Dependency/PhpRuleTest.php:42

5) Magento\TestFramework\Dependency\PhpRuleTest::testGetDependencyInfo with data set "Plugin depends on arbitrary class in arbitrary module" ('Magento\Module1\Plugin2', 'Magento\OtherModule\NotSubject', array(array('Magento\OtherModule', 'hard', 'Magento\OtherModule\NotSubject')))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => Array (...)
  )

/var/www/m2prod/dev/tests/static/framework/tests/unit/testsuite/Magento/TestFramework/Dependency/PhpRuleTest.php:42

FAILURES!  
Tests: 66, Assertions: 89, Failures: 5.

Similar issue was reported in this ticket: https://github.com/magento/magento2/issues/2639

Can you let me know if this is a problem of the framework, or am i setting up something incorrectly? Others are having similar issues with custom modules, after running unit tests on the whole framework?
I can even provide the test module.

Best regards,
Szabi

**Comment by mazhalai** [comment]
@ksz2013 Thank you! We have created ticket MAGETWO-51298 to fix.

**Comment by srqdeveloper** [comment]
The regular expression in Magento\TestFramework\DependencyPhpRule::getDependencyInfo was not matching the following class and module name pattern: \Magento\SomeModule\Any\ClassName

Changing the pattern to the following appears to pass all of the failed tests in this unit:

`$pattern = '~\b(?<class>(?<module>((' . implode(
            '|',
            Files::init()->getNamespaces()
        ) . ')[_|\\\\]?)[a-zA-Z0-9]+)[a-zA-Z0-9_\\\\]*)\b~';`

**Comment by elioermini** [comment]
Hello,
I've also encountered the same problem with PHPUnit 4.1.0, PHP 7.0.7 and Magento 2.0.7 Enterprise.
The fix suggested by @srqdeveloper lets the tests pass.

**Comment by waynetheisinger** [comment]
As well as the failures noted above I am also getting:

```
Fatal error: Class Mock_ProductOptionExtensionInterface_c2647204 contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Magento\Quote\Api\Data\ProductOptionExtensionInterface::getGiftcardItemOption, Magento\Quote\Api\Data\ProductOptionExtensionInterface::setGiftcardItemOption) in /app/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(290) : eval()'d code on line 1

---- /app/dev/tests/static/framework/tests/unit> php /app/./vendor/phpunit/phpunit/phpunit  

PHPUnit 4.1.0 by Sebastian Bergmann.

Configuration read from /app/dev/tests/static/framework/tests/unit/phpunit.xml.dist

...............................F...F......FFF.................... 65 / 66 ( 98%)
```

**Comment by francisrod01** [comment]
I have the same problem.

```bash
Time: 995 ms, Memory: 16.00MB

OK, but incomplete, skipped, or risky tests!
Tests: 165, Assertions: 320, Skipped: 1.    

---- /home/tosystems/projects/web/magento/mymagento/dev/tests/integration> php /home/tosystems/projects/web/magento/mymagento/./vendor/phpunit/phpunit/phpunit  

Exception: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)



  [InvalidArgumentException]
  Parameter validation failed



Exception trace:
 () at /home/tosystems/projects/web/magento/mymagento/setup/src/Magento/Setup/Console/Command/InstallCommand.php:150
 Magento\Setup\Console\Command\InstallCommand->initialize() at /home/tosystems/projects/web/magento/mymagento/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:236
 Symfony\Component\Console\Command\Command->run() at /home/tosystems/projects/web/magento/mymagento/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /home/tosystems/projects/web/magento/mymagento/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/Console/Cli.php:96
 Magento\Framework\Console\Cli->doRun() at /home/tosystems/projects/web/magento/mymagento/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /home/tosystems/projects/web/magento/mymagento/bin/magento:23


setup:install [--backend-frontname="..."] [--key="..."] [--session-save="..."] [--definition-format="..."] [--db-host="..."] [--db-name="..."] [--db-user="..."] [--db-engine="..."] [--db-password="..."] [--db-prefix="..."] [--db-model="..."] [--db-init-statements="..."] [-s|--skip-db-validation] [--http-cache-hosts="..."] [--base-url="..."] [--language="..."] [--timezone="..."] [--currency="..."] [--use-rewrites="..."] [--use-secure="..."] [--base-url-secure="..."] [--use-secure-admin="..."] [--admin-use-security-key="..."] [--admin-user="..."] [--admin-password="..."] [--admin-email="..."] [--admin-firstname="..."] [--admin-lastname="..."] [--cleanup-database] [--sales-order-increment-prefix="..."] [--use-sample-data] [--magento-init-params="..."]

 in /home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/Shell.php:61
Stack trace:
#0 /home/tosystems/projects/web/magento/mymagento/dev/tests/integration/framework/Magento/TestFramework/Application.php(464): Magento\Framework\Shell->execute('/usr/bin/php7.0...', Array)
#1 /home/tosystems/projects/web/magento/mymagento/dev/tests/integration/framework/bootstrap.php(68): Magento\TestFramework\Application->install()
#2 /home/tosystems/projects/web/magento/mymagento/vendor/phpunit/phpunit/src/Util/Fileloader.php(93): include_once('/home/tosystems...')
#3 /home/tosystems/projects/web/magento/mymagento/vendor/phpunit/phpunit/src/Util/Fileloader.php(77): PHPUnit_Util_Fileloader::load('/home/tosystems...')
#4 /home/tosystems/projects/web/magento/mymagento/vendor/phpunit/phpunit/src/TextUI/Command.php(806): PHPUnit_Util_Fileloader::checkAndLoad('/home/tosystems...')
#5 /home/tosystems/projects/web/magento/mymagento/vendor/phpunit/phpunit/src/TextUI/Command.php(636): PHPUnit_TextUI_Command->handleBootstrap('/home/tosystems...')
#6 /home/tosystems/projects/web/magento/mymagento/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit_TextUI_Command->handleArguments(Array)
#7 /home/tosystems/projects/web/magento/mymagento/vendor/phpunit/phpunit/src/TextUI/Command.php(132): PHPUnit_TextUI_Command->run(Array, true)
#8 /home/tosystems/projects/web/magento/mymagento/vendor/phpunit/phpunit/phpunit(55): PHPUnit_TextUI_Command::main()
#9 {main}

Next Magento\Framework\Exception\LocalizedException: Command returned non-zero exit code:
`/usr/bin/php7.0 -f '/home/tosystems/projects/web/magento/mymagento/bin/magento' setup:install -vvv --db-host='localhost' --db-user='root' --db-password='123123q' --db-name='magento_integration_tests' --backend-frontname='backend' --admin-user='user' --admin-password='password1' --admin-email='admin@example.com' --admin-firstname='firstname' --admin-lastname='lastname' --magento-init-params='MAGE_DIRS[etc][path]=/home/tosystems/projects/web/magento/mymagento/dev/tests/integration/tmp/sandbox-0-1605ce67d808da280ae517a8d11991d7/etc&MAGE_DIRS[var][path]=/home/tosystems/projects/web/magento/mymagento/dev/tests/integration/tmp/sandbox-0-1605ce67d808da280ae517a8d11991d7/var&MAGE_DIRS[media][path]=/home/tosystems/projects/web/magento/mymagento/dev/tests/integration/tmp/sandbox-0-1605ce67d808da280ae517a8d11991d7/pub/media&MAGE_DIRS[static][path]=/home/tosystems/projects/web/magento/mymagento/dev/tests/integration/tmp/sandbox-0-1605ce67d808da280ae517a8d11991d7/pub/static&MAGE_DIRS[generation][path]=/home/tosystems/projects/web/magento/mymagento/dev/tests/integration/tmp/sandbox-0-1605ce67d808da280ae517a8d11991d7/var/generation&MAGE_DIRS[cache][path]=/home/tosystems/projects/web/magento/mymagento/dev/tests/integration/tmp/sandbox-0-1605ce67d808da280ae517a8d11991d7/var/cache&MAGE_DIRS[log][path]=/home/tosystems/projects/web/magento/mymagento/dev/tests/integration/tmp/sandbox-0-1605ce67d808da280ae517a8d11991d7/var/log&MAGE_DIRS[session][path]=/home/tosystems/projects/web/magento/mymagento/dev/tests/integration/tmp/sandbox-0-1605ce67d808da280ae517a8d11991d7/var/session&MAGE_DIRS[tmp][path]=/home/tosystems/projects/web/magento/mymagento/dev/tests/integration/tmp/sandbox-0-1605ce67d808da280ae517a8d11991d7/var/tmp&MAGE_DIRS[upload][path]=/home/tosystems/projects/web/magento/mymagento/dev/tests/integration/tmp/sandbox-0-1605ce67d808da280ae517a8d11991d7/var/upload&MAGE_DIRS[pub][path]=/home/tosystems/projects/web/magento/mymagento/dev/tests/integration/tmp/sandbox-0-1605ce67d808da280ae517a8d11991d7/pub&MAGE_MODE=developer' 2>&1` in /home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/Shell.php:62
Stack trace:
#0 /home/tosystems/projects/web/magento/mymagento/dev/tests/integration/framework/Magento/TestFramework/Application.php(464): Magento\Framework\Shell->execute('/usr/bin/php7.0...', Array)
#1 /home/tosystems/projects/web/magento/mymagento/dev/tests/integration/framework/bootstrap.php(68): Magento\TestFramework\Application->install()
#2 /home/tosystems/projects/web/magento/mymagento/vendor/phpunit/phpunit/src/Util/Fileloader.php(93): include_once('/home/tosystems...')
#3 /home/tosystems/projects/web/magento/mymagento/vendor/phpunit/phpunit/src/Util/Fileloader.php(77): PHPUnit_Util_Fileloader::load('/home/tosystems...')
#4 /home/tosystems/projects/web/magento/mymagento/vendor/phpunit/phpunit/src/TextUI/Command.php(806): PHPUnit_Util_Fileloader::checkAndLoad('/home/tosystems...')
#5 /home/tosystems/projects/web/magento/mymagento/vendor/phpunit/phpunit/src/TextUI/Command.php(636): PHPUnit_TextUI_Command->handleBootstrap('/home/tosystems...')
#6 /home/tosystems/projects/web/magento/mymagento/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit_TextUI_Command->handleArguments(Array)
#7 /home/tosystems/projects/web/magento/mymagento/vendor/phpunit/phpunit/src/TextUI/Command.php(132): PHPUnit_TextUI_Command->run(Array, true)
#8 /home/tosystems/projects/web/magento/mymagento/vendor/phpunit/phpunit/phpunit(55): PHPUnit_TextUI_Command::main()
#9 {main}

=== Memory Usage System Stats ===
Memory usage (OS):	31.93M (798.24% of 4.00M reported by PHP)
Estimated memory leak:	27.93M (87.47% of used memory)


---- /home/tosystems/projects/web/magento/mymagento/dev/tests/static> php /home/tosystems/projects/web/magento/mymagento/./vendor/phpunit/phpunit/phpunit  



PHPUnit 4.1.0 by Sebastian Bergmann.

Configuration read from /home/tosystems/projects/web/magento/mymagento/dev/tests/static/phpunit.xml.dist

EE.......S.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS  63 / 371 ( 16%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 126 / 371 ( 33%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 189 / 371 ( 50%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...FF..FS.SSS..S... 252 / 371 ( 67%)
....................................................I.......... 315 / 371 ( 84%)
.............SSS....S........SSS......SSS.............

Time: 4.64 minutes, Memory: 484.00MB

There were 2 errors:

1) Magento\Test\Less\LiveCodeTest::testCodeStyle
Exception: The following patterns didn't return any result:
app/design/adminhtml/Magento/backend/Magento_Backend/web/css/source/_module-old.less
app/design/adminhtml/Magento/backend/Magento_Catalog/web/css/source/_module-old.less
app/design/adminhtml/Magento/backend/Magento_ConfigurableProduct/web/css/source/_module-old.less
app/design/adminhtml/Magento/backend/Magento_Developer/web/css/source/_module-old.less
app/design/adminhtml/Magento/backend/Magento_Enterprise/web/css/source/_module-old.less
app/design/adminhtml/Magento/backend/Magento_Msrp/web/css/source/_module-old.less
app/design/adminhtml/Magento/backend/Magento_Tax/web/css/source/_module-old.less
app/design/adminhtml/Magento/backend/Magento_Theme/web/css/source/_module-old.less
app/design/adminhtml/Magento/backend/Magento_Ui/web/css/source/_module-old.less
app/design/adminhtml/Magento/backend/web/app/setup/styles/less/lib/utilities/_grid-framework.less
app/design/adminhtml/Magento/backend/web/css/source/_grid.less
app/design/adminhtml/Magento/backend/web/css/source/components/_popups-old.less
app/design/adminhtml/Magento/backend/web/css/source/utilities/_grid-framework.less
app/design/adminhtml/Magento/backend/web/css/source/utilities/_spinner.less
app/design/adminhtml/Magento/backend/web/css/source/utilities/_spinner.less
app/design/adminhtml/Magento/backend/web/css/styles-old.less
app/design/adminhtml/Magento/backend/web/mui/clearless/_all.less
app/design/adminhtml/Magento/backend/web/mui/clearless/_arrows.less
app/design/adminhtml/Magento/backend/web/mui/clearless/_helpers.less
app/design/adminhtml/Magento/backend/web/mui/clearless/_icons.less
app/design/adminhtml/Magento/backend/web/mui/clearless/_settings.less
app/design/adminhtml/Magento/backend/web/mui/clearless/_sprites.less
app/design/adminhtml/Magento/backend/web/mui/styles/_abstract.less
app/design/adminhtml/Magento/backend/web/mui/styles/_table.less
app/design/adminhtml/Magento/backend/web/mui/styles/_vars.less

/home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/App/Utility/Files.php:1476
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Less/LiveCodeTest.php:76
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Less/LiveCodeTest.php:58

2) Magento\Test\Js\LiveCodeTest
Exception: The following patterns didn't return any result:
module Magento_Checkout view/frontend/web/js/opcheckout.js

/home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/App/Utility/Files.php:1476
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Js/LiveCodeTest.php:68

--

There were 3 failures:

1) Magento\Test\Integrity\ClassesTest::testClassNamespaces
Passed: 16224, Failed: 1, Incomplete: 0, Skipped: 0.
Data set: /home/tosystems/projects/web/magento/mymagento/vendor/magento/module-customer-sample-data/Magento/Framework/Mail/Transport/MailPlugin.php
Location of /home/tosystems/projects/web/magento/mymagento/vendor/magento/module-customer-sample-data/Magento/Framework/Mail/Transport/MailPlugin.php does not match formal namespace: Magento\Framework\Mail\Transport

Failed asserting that two strings are equal.
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ClassesTest.php:274
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ClassesTest.php:232
/home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/App/Utility/AggregateInvoker.php:56
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ClassesTest.php:234

/home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/App/Utility/AggregateInvoker.php:114
/home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/App/Utility/AggregateInvoker.php:70
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ClassesTest.php:234

2) Magento\Test\Integrity\ClassesTest::testClassReferences
Passed: 16223, Failed: 2, Incomplete: 0, Skipped: 0.
Data set: /home/tosystems/projects/web/magento/mymagento/vendor/magento/module-catalog-sample-data/Model/Attribute.php
Files not found for following usages in /home/tosystems/projects/web/magento/mymagento/vendor/magento/module-catalog-sample-data/Model/Attribute.php:
\Magento\Framework\Model\Exception
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ClassesTest.php:195
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ClassesTest.php:348
/home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/App/Utility/AggregateInvoker.php:56
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ClassesTest.php:369

Data set: /home/tosystems/projects/web/magento/mymagento/vendor/magento/module-cms-sample-data/Model/Block/Converter.php
Files not found for following usages in /home/tosystems/projects/web/magento/mymagento/vendor/magento/module-cms-sample-data/Model/Block/Converter.php:
\Magento\Framework\Object
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ClassesTest.php:195
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ClassesTest.php:348
/home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/App/Utility/AggregateInvoker.php:56
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ClassesTest.php:369

/home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/App/Utility/AggregateInvoker.php:114
/home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/App/Utility/AggregateInvoker.php:70
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ClassesTest.php:369

3) Magento\Test\Integrity\ComposerTest::testValidComposerJson
Passed: 114, Failed: 19, Incomplete: 0, Skipped: 0.
Data set: /home/tosystems/projects/web/magento/mymagento/vendor/magento/module-catalog-sample-data
This component is expected to depend on magento/framework
Failed asserting that object of class "stdClass" has attribute "magento/framework".
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php:248
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php:143
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php:61
/home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/App/Utility/AggregateInvoker.php:56
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php:63

Data set: /home/tosystems/projects/web/magento/mymagento/vendor/magento/module-product-links-sample-data
This component is expected to depend on magento/framework
Failed asserting that object of class "stdClass" has attribute "magento/framework".
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php:248
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php:143
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php:61
/home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/App/Utility/AggregateInvoker.php:56
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php:63


... and more...


Data set: /home/tosystems/projects/web/magento/mymagento/vendor/magento/module-offline-shipping-sample-data
This component is expected to depend on magento/framework
Failed asserting that object of class "stdClass" has attribute "magento/framework".
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php:248
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php:143
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php:61
/home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/App/Utility/AggregateInvoker.php:56
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php:63

/home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/App/Utility/AggregateInvoker.php:114
/home/tosystems/projects/web/magento/mymagento/vendor/magento/framework/App/Utility/AggregateInvoker.php:70
/home/tosystems/projects/web/magento/mymagento/dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php:63
                                                                                   
FAILURES!                                                                          
Tests: 367, Assertions: 23858, Failures: 3, Errors: 2, Incomplete: 1, Skipped: 238.
----------------------------------------------------------------------
FAILED - 3 of 5:
 - /home/tosystems/projects/web/magento/mymagento/dev/tests/unit> php /home/tosystems/projects/web/magento/mymagento/./vendor/phpunit/phpunit/phpunit 
 - /home/tosystems/projects/web/magento/mymagento/dev/tests/integration> php /home/tosystems/projects/web/magento/mymagento/./vendor/phpunit/phpunit/phpunit 
 - /home/tosystems/projects/web/magento/mymagento/dev/tests/static> php /home/tosystems/projects/web/magento/mymagento/./vendor/phpunit/phpunit/phpunit

... and others...

```

**Comment by waynetheisinger** [comment]
As noted by @srqdeveloper... The regular expression was not matching the following class and module name pattern: ``\Magento\SomeModule\Any\ClassName``

Changing the pattern to the following appears to pass all of the failed tests in this unit:

```
$pattern = '~\b(?<class>(?<module>((' . implode( '|', Files::init()->getNamespaces() ) . ')[_|\\\\]?)[a-zA-Z0-9]+)[a-zA-Z0-9_\\\\]*)\b~';
```

I've created PR https://github.com/magento/magento2/pull/8263 to address

**Comment by vherasymenko** [comment]
@ksz2013 Hi. We could not reproduce your bug on latest develop branch. Is actual this bug still now ??
If you can reproduce this bug explain please more detail steps for us.

**Comment by waynetheisinger** [comment]
No - it isn't relevant any more, in fact the PR was closed on the 27 of March as the test was no longer failing on Develop on that date...

**Comment by vherasymenko** [comment]
@waynetheisinger  Thanks. I close issue.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-65194
