### ISSUE TITLE
Some configurable products are not working (Argument #1 ($productType) must be of type string, null given)

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#39059]
### Preconditions and environment

- Magento version 2.4.6
- Applied patch: https://github.com/magento/inventory/commit/78eb15495ecb13fca7c6b38735cba081d3e5d9d5

### Steps to reproduce

Not so sure what is really wrong.
Working product: https://dartwinkel.nl/target-coolplay-hybrid-3-dart-polo-shirt
Exception: https://dartwinkel.nl/target-coolplay-collarless-dart-polo-shirt

In the exception log we see following:
```
main.CRITICAL: TypeError: Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute(): Argument #1 ($productType) must be of type string, null given, called in /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php on line 108 and defined in /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php:20
Stack trace:
#0 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php(108): Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor->execute()
#1 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php(75): Magento\InventorySales\Model\GetProductSalableQty->validateProductType()
#2 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/bsscommerce/product-stock-alert/Helper/ProductData.php(251): Magento\InventorySales\Model\GetProductSalableQty->execute()
#3 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/bsscommerce/product-stock-alert/Helper/ProductData.php(147): Bss\ProductStockAlert\Helper\ProductData->getStockNumber()
#4 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/bsscommerce/product-stock-alert/Plugin/Block/Product/View/Type/Configurable.php(87): Bss\ProductStockAlert\Helper\ProductData->getAllData()
#5 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Bss\ProductStockAlert\Plugin\Block\Product\View\Type\Configurable->afterGetJsonConfig()
#6 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Swatches\Block\Product\Renderer\Configurable\Interceptor->Magento\Framework\Interception\{closure}()
#7 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Swatches/Block/Product/Renderer/Configurable/Interceptor.php(149): Magento\Swatches\Block\Product\Renderer\Configurable\Interceptor->___callPlugins()
#8 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/hyva-themes/magento2-default-theme/Magento_ConfigurableProduct/templates/product/view/type/options/configurable.phtml(25): Magento\Swatches\Block\Product\Renderer\Configurable\Interceptor->getJsonConfig()
#9 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#10 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#11 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#12 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#13 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#14 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#15 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Swatches/Block/Product/Renderer/Configurable/Interceptor.php(428): Magento\Framework\View\Element\Template->fetchView()
#16 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/Template.php(293): Magento\Swatches\Block\Product\Renderer\Configurable\Interceptor->fetchView()
#17 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/module-swatches/Block/Product/Renderer/Configurable.php(481): Magento\Framework\View\Element\Template->_toHtml()
#18 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/module-swatches/Block/Product/Renderer/Configurable.php(459): Magento\Swatches\Block\Product\Renderer\Configurable->getHtmlOutput()
#19 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1128): Magento\Swatches\Block\Product\Renderer\Configurable->_toHtml()
#20 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Cache/LockGuardedCacheLoader.php(136): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#21 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1150): Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData()
#22 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(676): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#23 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/module-swatches/Block/Product/Renderer/Configurable.php(449): Magento\Framework\View\Element\AbstractBlock->toHtml()
#24 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Swatches\Block\Product\Renderer\Configurable->toHtml()
#25 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Swatches\Block\Product\Renderer\Configurable\Interceptor->___callParent()
#26 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Swatches\Block\Product\Renderer\Configurable\Interceptor->Magento\Framework\Interception\{closure}()
#27 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Swatches/Block/Product/Renderer/Configurable/Interceptor.php(68): Magento\Swatches\Block\Product\Renderer\Configurable\Interceptor->___callPlugins()
#28 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(578): Magento\Swatches\Block\Product\Renderer\Configurable\Interceptor->toHtml()
#29 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#30 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#31 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#32 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#33 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(527): Magento\Framework\View\Layout\Interceptor->renderElement()
#34 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(545): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#35 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/hyva-themes/magento2-default-theme/Magento_Catalog/templates/product/view/product-form.phtml(41): Magento\Catalog\Block\Product\View\Interceptor->getChildHtml()
#36 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#37 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#38 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#39 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#40 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#41 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#42 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(383): Magento\Framework\View\Element\Template->fetchView()
#43 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/Template.php(293): Magento\Catalog\Block\Product\View\Interceptor->fetchView()
#44 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1128): Magento\Framework\View\Element\Template->_toHtml()
#45 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1132): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#46 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(676): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#47 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock->toHtml()
#48 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Block\Product\View\Interceptor->___callParent()
#49 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/amasty/module-groupcat-hyva/Plugin/Catalog/Block/Product/View/HidePrice.php(104): Magento\Catalog\Block\Product\View\Interceptor->Magento\Framework\Interception\{closure}()
#50 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\GroupcatHyva\Plugin\Catalog\Block\Product\View\HidePrice->aroundToHtml()
#51 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Block\Product\View\Interceptor->Magento\Framework\Interception\{closure}()
#52 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(608): Magento\Catalog\Block\Product\View\Interceptor->___callPlugins()
#53 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(578): Magento\Catalog\Block\Product\View\Interceptor->toHtml()
#54 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#55 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#56 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#57 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#58 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(523): Magento\Framework\View\Layout\Interceptor->renderElement()
#59 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(545): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#60 /home/dartweb/domains/dartwinkel.nl/public_html/app/design/frontend/Wemessage/Biljartwinkel/Magento_Catalog/templates/product/view/product-info.phtml(59): Magento\Catalog\Block\Product\View\Interceptor->getChildHtml()
#61 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#62 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#63 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#64 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#65 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#66 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#67 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(383): Magento\Framework\View\Element\Template->fetchView()
#68 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/Template.php(293): Magento\Catalog\Block\Product\View\Interceptor->fetchView()
#69 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1128): Magento\Framework\View\Element\Template->_toHtml()
#70 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1132): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#71 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(676): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#72 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock->toHtml()
#73 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Block\Product\View\Interceptor->___callParent()
#74 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/amasty/module-groupcat-hyva/Plugin/Catalog/Block/Product/View/HidePrice.php(93): Magento\Catalog\Block\Product\View\Interceptor->Magento\Framework\Interception\{closure}()
#75 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\GroupcatHyva\Plugin\Catalog\Block\Product\View\HidePrice->aroundToHtml()
#76 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Block\Product\View\Interceptor->Magento\Framework\Interception\{closure}()
#77 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(608): Magento\Catalog\Block\Product\View\Interceptor->___callPlugins()
#78 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(578): Magento\Catalog\Block\Product\View\Interceptor->toHtml()
#79 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#80 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#81 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#82 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#83 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(523): Magento\Framework\View\Layout\Interceptor->renderElement()
#84 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(545): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#85 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/hyva-themes/magento2-default-theme/Magento_Catalog/templates/product/product-detail-page.phtml(22): Magento\Catalog\Block\Product\View\Interceptor->getChildHtml()
#86 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#87 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#88 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#89 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#90 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#91 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#92 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(383): Magento\Framework\View\Element\Template->fetchView()
#93 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/Template.php(293): Magento\Catalog\Block\Product\View\Interceptor->fetchView()
#94 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1128): Magento\Framework\View\Element\Template->_toHtml()
#95 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1132): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#96 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(676): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#97 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock->toHtml()
#98 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Block\Product\View\Interceptor->___callParent()
#99 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/amasty/module-groupcat-hyva/Plugin/Catalog/Block/Product/View/HidePrice.php(93): Magento\Catalog\Block\Product\View\Interceptor->Magento\Framework\Interception\{closure}()
#100 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\GroupcatHyva\Plugin\Catalog\Block\Product\View\HidePrice->aroundToHtml()
#101 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Block\Product\View\Interceptor->Magento\Framework\Interception\{closure}()
#102 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(608): Magento\Catalog\Block\Product\View\Interceptor->___callPlugins()
#103 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(578): Magento\Catalog\Block\Product\View\Interceptor->toHtml()
#104 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#105 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#106 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#107 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#108 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#109 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#110 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#111 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#112 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#113 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#114 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#115 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#116 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#117 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#118 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#119 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#120 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#121 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#122 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#123 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#124 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#125 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#126 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#127 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#128 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#129 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#130 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#131 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#132 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#133 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#134 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#135 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#136 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#137 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#138 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#139 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#140 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#141 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#142 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#143 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout\Interceptor->renderElement()
#144 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#145 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#146 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#147 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(347): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#148 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#149 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#150 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult()
#151 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent()
#152 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#153 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(95): Magento\Framework\View\Result\Page\Interceptor->___callPlugins()
#154 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult()
#155 /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#156 /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#157 /home/dartweb/domains/dartwinkel.nl/public_html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#158 {main} {"exception":"[object] (TypeError(code: 0): Magento\\InventoryConfiguration\\Model\\IsSourceItemManagementAllowedForProductType\\Interceptor::execute(): Argument #1 ($productType) must be of type string, null given, called in /home/dartweb/domains/dartwinkel.nl/public_html/vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php on line 108 at /home/dartweb/domains/dartwinkel.nl/public_html/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php:20)"} []
```

### Expected result

All products in backend are looking the same.
Not working product:
![Untitled-12](https://github.com/user-attachments/assets/cb73c5db-a235-4586-b1fd-5c2dda19a167)

Working product
![Untitled-1](https://github.com/user-attachments/assets/02a02d28-e0a5-4494-a118-4834ba1c92b8)

### Actual result

So any idea on how to fix this error ?

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @Naberdz,

Thanks for your reporting and collaboration.

Could you please elaborate the steps to reproduce to proceed further and check if any third party modules can causing this issue.

Thanks.

**Comment by Naberdz** [comment]
Hi @engcom-Bravo , 
i'm not sure what is really wrong.. i have created staging and upgraded all modules/magento to a new version. There i don't have this error.

so magento 2.4.7 doesn't have this error.

**Comment by engcom-Bravo** [comment]
Hi @Naberdz, 

Thanks for quick response.

As per this comment https://github.com/magento/magento2/issues/39059#issuecomment-2296327602 we are closing this issue.

Thanks.
