### ISSUE TITLE
Click Admin Stores Configuration shows console errors in legacy-build.min.js file

### ISSUE THREAD

**Issue by kanidaya** [magento/magento2#39066]
### Preconditions and environment

- Magento version 2.4.7-p2 Opensource

### Steps to reproduce

1.click Store configuration
2.click any of the section from side bar
3.open the any one og section 
4.it will not open an check the console

### Expected result

Nothing happen. we can able collapse and open any section

### Actual result

Can't able to open  system configuration sections shows below console errors

Uncaught TypeError: ah.attachEvent is not a function
    at s (legacy-build.min.js:12:31254)
    at Function.e [as observe] (legacy-build.min.js:12:31133)
    at form.js:114:11
    at Object.execCb (require.js:1696:33)
    at Module.check (require.js:883:51)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)Understand this error
theme.js:629 Uncaught TypeError: $(...).filter(...).collapse is not a function
    at HTMLDivElement.<anonymous> (theme.js:629:12)
    at Function.each (jquery.js:383:35)
    at theme.js:626:7
    at Object.execCb (require.js:1696:33)
    at Module.check (require.js:883:51)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    
    
    
    Uncaught TypeError: ah.dispatchEvent is not a function
    at r (legacy-build.min.js:12:32795)
    at D (legacy-build.min.js:12:32626)
    at HTMLDocument._methodized [as fire] (legacy-build.min.js:1:6441)
    at d (legacy-build.min.js:12:34954)
    at legacy-build.min.js:12:34408Understand this error
legacy-build.min.js:12 Uncaught TypeError: $(...).removeClassName is not a function
    at Object.applyCollapse (legacy-build.min.js:12:147567)
    at Object.toggleCollapse (legacy-build.min.js:12:148155)
    at HTMLAnchorElement.eventListener9tmbiETHAp (6c8471f696931ebcf4ba741ab4a76321ac03408b6b79a9af71a9e0f07aa8885b/:475:41)
    at element.onclick (6c8471f696931ebcf4ba741ab4a76321ac03408b6b79a9af71a9e0f07aa8885b/:486:52)Understand this error
about:blank:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was receivedUnderstand this error
6c8471f……71a9e0f07aa8885b/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was receivedUnderstand this error
2legacy-build.min.js:12 Uncaught TypeError: $(...).removeClassName is not a function
    at Object.applyCollapse (legacy-build.min.js:12:147567)
    at Object.toggleCollapse (legacy-build.min.js:12:148155)
    at HTMLAnchorElement.eventListenerIIMI4DNdRa (6c8471f696931ebcf4ba741ab4a76321ac03408b6b79a9af71a9e0f07aa8885b/:529:41)
    at element.onclick (6c8471f696931ebcf4ba741ab4a76321ac03408b6b79a9af71a9e0f07aa8885b/:540:52)
    
    
    
<img width="1029" alt="Screenshot 2024-08-20 085130" src="https://github.com/user-attachments/assets/8a005f1a-746d-44ec-9d61-e9debff19fa2">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @kanidaya  ,

Thanks for your reporting and collaboration.
We have verified the issue in magento 2.4.7-p2, but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**

1. Install magento 2.4.7-p2
2. Access admin
3. Navigate to Stores>Settings>Configuration
4. Observe user is able to access configuration.
User is able to access all areas of configuration without interruption.

https://github.com/user-attachments/assets/f4bc2bcd-1eb4-4f7a-96eb-f1d7a44d3a43

Please let us know if any other steps are needed to be performed.

Thanks.

**Comment by kanidaya** [comment]
@engcom-Delta  after click left side menu then click right section collabs

**Comment by nikolaykravchenko** [comment]
I have the same issue. It appears randomly on configuration admin page.

**Comment by engcom-Delta** [comment]
Hi @kanidaya ,

We have verified in our local, You can verify in 2.4-develop instance by calling @magento give me 2.4-develop instance.
Please let us know if any other steps are needed to be performed.

Thanks.

**Comment by Lathanao** [comment]
Same there

**Comment by thespacersm** [comment]
Same
![attachEvent](https://github.com/user-attachments/assets/21a5465b-cd23-4cbf-967b-5ab595c0db20)

**Comment by barryvdh** [comment]
We're having the same issue.

**Comment by likearocket** [comment]
Also having the same issue.

**Comment by hostep** [comment]
Instead of posting "happens as well", it would really help if people could specify exact steps to reproduce and some details about their environment and if JS files are being minified and/or bundled (using built-in Magento functionality or custom ones). Also if this happens consistently, or only "sometimes"?

**Comment by likearocket** [comment]
If I delete my browser history/cache and refresh the page after it happens, the page will load correctly but then occur again on another admin page.

Merge JavaScript Files: No
Enable JavaScript Bundling: Yes
Minify JavaScript Files: No

No custom modules doing this.

**Comment by sheepfy** [comment]
@kanidaya Can you confirm if you are having a patch applied from https://github.com/magento/magento2/issues/33593 (the one made by @AndresInSpace ) ?

**Comment by sheepfy** [comment]
@hostep @kanidaya 
Ok, I have found where this is coming from and I can confirm that is not reproductible on the latest upgrade.

Since I have 2 stores to work with, one store was having no overwrites over the mixins.js file. But my other store it was having various patches on mixins.js file with the scope of solving the https://github.com/magento/magento2/issues/33593 issue, which got solved thanks to @AndresInSpace.

My mixins.js file that was causin the issue it was having this lines:
```    var contexts = require.s.contexts,
        defContextName = '_',
        defContext = contexts[defContextName],
        unbundledContext = require.s.newContext('$'),
        defaultConfig = defContext.config,
        unbundledConfig = {
            baseUrl: defaultConfig.baseUrl,
            paths: defaultConfig.paths,
            shim: defaultConfig.shim,
            config: defaultConfig.config,
            map: defaultConfig.map
        },
        rjsMixins;```
instead of this:
```    var contexts = require.s.contexts,
        defContextName = '_',
        defContext = contexts[defContextName],
        unbundledContextName = '$',
        unbundledContext = contexts[unbundledContextName] = require.s.newContext(unbundledContextName),
        defaultConfig = defContext.config,
        unbundledConfig = {
            baseUrl: defaultConfig.baseUrl,
            paths: defaultConfig.paths,
            shim: defaultConfig.shim,
            config: defaultConfig.config,
            map: defaultConfig.map
        },
        rjsMixins;```


After removing the overwrites, the error is now gone.

**Comment by AndresInSpace** [comment]
I'd like to point out if you have Magento in production mode it's _probably from static content versioning change._
Do a static content deployment for admin side, then flush cache.

**Comment by AndresInSpace** [comment]
@kanidaya @likearocket @barryvdh @jointothedarkside

Please ensure if in production mode that you have redeployed admin static content and flushed cache first. 

If you still have this issue, please try my patch #39097 and let us know if that resolved it.

I see no requirejs/mixins.js in the stack traces provided, that is why I am thinking it's the mixin based issue - if not a deployment issue due to static-content version change.

**Comment by engcom-Delta** [comment]
Hi @kanidaya @jointothedarkside ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance and magento 2.4.7-p2, but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce :** 
1. Install 2.4.7 version
2. Upgrade to 2.4.7-p2 version
3. Create 2 stores
4. Navigate to Stores->Configuration->Customer Configuration
5. Observe error is not displaying in console.
![image](https://github.com/user-attachments/assets/68746817-8c2d-4519-a1a0-d30bd4f1ff66)

Please let us know if any other steps are needed to be performed.

Thanks.

**Comment by engcom-Delta** [comment]
Hi @kanidaya  @jointothedarkside ,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by engcom-Delta** [comment]
Hi @nikolaykravchenko ,

Thanks for your reporting and collaboration.
We have verified the issue in 2.4.7-p3 instance but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce:**
1. Open Stores -> Configuration.
2. Open chrome dev tools (console)
3. Update page via ctrl+f5 few times (5-10). You will see the error
![image](https://github.com/user-attachments/assets/f46024cf-dcc0-4f3f-b6d3-6b5fea13771c)

Thanks.

**Comment by PPekals** [comment]
@ricardomz 
Thank you, this fixed it!

> Hi there.
> 
> If there's somebody else facing the same issue, @m2-assistant please take this into consideration because this is a weird situation: the issue seems to be related with PayPal_Braintree, maybe with PayPal_Braintree/js/system.js and I think the reason you can't replicate the bug is that maybe you are testing with nginx instances. For some reason the static content versioning of this module is being handled different by nginx and apache, either in production or dev mode. I had the same issue with a fresh 2.4.7-p3 installation using apache but once I moved to nginx the error fully disappears.
> 
> To be sure I disabled PayPal_Braintree on the apache instance and the error disappears too: `bin/magento module:disable PayPal_BraintreeGraphQl bin/magento module:disable PayPal_BraintreeGiftWrapping bin/magento module:disable PayPal_BraintreeGiftCardAccount bin/magento module:disable PayPal_BraintreeCustomerBalance bin/magento module:disable PayPal_Braintree`
> 
> In short terms, if you are running Apache try to disable (in case you are not using it ) PayPal_Braintree. If you are running Nginx maybe you are not aware of this error.

**Comment by patoliyanimita** [comment]
I am facing same issue in 2.4.7-p3
let me know if anyone found the solution.

**Comment by miteshdhaduk1** [comment]
Issue in Adobe Commerce ver. 2.4.7-p3

**Comment by mflott** [comment]
Also having this issue, Adobe Commerce 2.4.7-p3.

**Comment by dphilipps** [comment]
I've spent some time troubleshooting this issue on a fresh composer install of 2.4.7-p3 and trying some of the suggestions above.  

Here are my findings:

- @ricardomz  **Disabling Paypal Braintree modules**:  Didn't work for me, I've disabled all of them, and I could still reproduce the issue.
- @ricardomz **Nginx vs Apache**: I switched my FPM between both and makes no difference.
- @AndresInSpace **Re-deploying static content (for admin or all)**: This made no difference either.

I have noticed it is a lot harder to reproduce when the store is in Production mode.  It can take 5 minutes of clicking around Stores->Configuration to see the issue.  In Developer mode, it only takes a couple of times.

**Can anyone please advise if it is possible this issue could affect the front-end of the store as well?** 

I could potentially live with this in production if it only affects the configuration page.  But from what I've read the cause may go deeper.  If there is a chance if could affect the front-end or other admin pages I can't risk it.

**Comment by lpwe** [comment]
same by me, 
![Image](https://github.com/user-attachments/assets/de13c5c1-acad-4403-9531-13ac84591ed7)

but sometimes it's not there, after refreshing 15x:
![Image](https://github.com/user-attachments/assets/40fc5a70-5f44-4540-ad4f-46358bd3a5c3)

**Comment by laccas** [comment]
Can confirm, the issue us still presyent!

**Comment by uegonzalez** [comment]
> Can confirm, the issue us still presyent!

I can confirm.  I was in developer mode and was pulling out my hair because i couldn't save any options.  Switching from Developer->Production did not fix the issue and in fact broke a lot of other things.  I had to start over and re-build the entire website from scratch and keep it in Production mode for these errors to go away.

This is still an issue in Developer mode, but NOT in Production mode.

**Comment by ZandaBear** [comment]
From the related issue #39541 what worked for me to get around the issue for now is to enable javascript file merging. Since the "Save Config" button is nonfunctional, use the following command in the CLI.

`bin/magento config:set dev/js/merge_files 1`

**Comment by GautierDig** [comment]
The issue still exist in 2.4.7-p5 ...

**Comment by MagentoGuysProjects** [comment]
The issue still exist in 2.4.8 as well Please provide the fixes as  ...

**Comment by amine-y** [comment]
Hello @engcom-Bravo, it happens in Microsoft Edge browser but not in Chrome
