### ISSUE TITLE
Cannot instantiate interface `Magento\Csp\Model\Collector\MergerInterface` when `Magento_Csp` is disabled

### ISSUE THREAD

**Issue by fritzmg** [magento/magento2#39104]
### Preconditions and environment

- Magento version: 2.4.7-p2
- `Magento_Csp` disabled

### Steps to reproduce

1. Update or install Magento `2.4.7-p2`.
2. Execute `bin/magento module:disable Magento_Csp`.
3. Go to the checkout.

### Expected result

The checkout should be rendered.

### Actual result

The following error is thrown:

```
Error: Cannot instantiate interface Magento\Csp\Model\Collector\MergerInterface in vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 vendor/magento/framework/ObjectManager/ObjectManager.php(73): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#1 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#2 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#3 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#4 vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#5 vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#6 vendor/magento/framework/ObjectManager/ObjectManager.php(73): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#7 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#8 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#9 vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#10 vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#11 vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#12 vendor/magento/framework/ObjectManager/ObjectManager.php(73): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#13 vendor/magento/module-payment-services-paypal/Model/ConfigProvider.php(65): Magento\Framework\ObjectManager\ObjectManager->get()
…
```

### Additional information

The cause are these lines within `vendor/magento/module-payment-services-paypal/Model/ConfigProvider.php`

```php
    //TODO:Just to be compatible with 2.4.6. Remove in future
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    try {
        $this->cspNonceProvider = $objectManager->get("\Magento\Csp\Helper\CspNonceProvider");
    } catch (\ReflectionException $e) {
        $this->cspNonceProvider = null;
    }
```

The error is not of type `\ReflectionException`, instead it is of type `\Error` - thus the error is not caught.

To fix it, it could be changed as follows:

```diff
    //TODO:Just to be compatible with 2.4.6. Remove in future
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    try {
        $this->cspNonceProvider = $objectManager->get("\Magento\Csp\Helper\CspNonceProvider");
-   } catch (\ReflectionException $e) {
+   } catch (\Throwable) {
        $this->cspNonceProvider = null;
    }
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Franciscof-Serfe** [comment]
Hi @fritzmg , 
 I think that this could be related to this security improvement: 
 https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/magento-open-source/2-4-7#:~:text=Changes%20to%20Content%20Security%20Policy
 
 Magento updated CSP to restrict mode at checkout. 
 You can use this module to bypass it meanwhile you fix the code to enable CSP. 
 
 https://github.com/yireo/Yireo_DisableCsp

**Comment by fritzmg** [comment]
Well Magento has support for CSP for some while now, not just recently. The issue is just with the `Magento_PaymentServicesPaypal` module that comes with Magento Community Edition. It currently has an erroneous hard dependency on `Magento_Csp`. Judging by the code it is supposed to be a soft dependency, but it currently does not work (due to the wrong catch type).

**Comment by Franciscof-Serfe** [comment]
Marcus, 
 As I mentioned in my previous note, after M2.4.7 Adobe decided to force CSP in restricted mode for the checkout and payment line. It's not an error.

Default config:
https://developer.adobe.com/commerce/php/development/security/content-security-policies/#default-configuration

Commit REF: https://github.com/magento/magento2/commit/25cf7f077cf06eafa145027ff70c55d297f4943c#diff-32ed90c0e573d5dd4047b67db44768fca797fa1df717c8d883956d3a6b8d2fd6

I understand that someone from the Adobe team should clarify this.
@nathanjosiah can you add your 2 cents?

Previous discussion on Magento_Csp behavior change at checkout: https://github.com/magento/magento2/issues/38823

Background info: https://m.academy/articles/magento-apsb24-40-security-patch-csp-checkout-updates/#:~:text=Impact%20on%20Checkout%20Functionality

**Comment by fritzmg** [comment]
> Adobe decided to force CSP in restricted mode for the checkout and payment line. It's not an error.

Nevertheless, modules that have a hard dependency on `Magento_Csp`  need to define it as such. Currently `Magento_PaymentServicesPaypal` has no dependency and thus `Magento_Csp` can be disabled, which leads to the aforementioned error.

**Comment by nathanjosiah** [comment]
The new CSP changes are new PCI requirements for all payment pages per PCI version 4 section 6.4.3. Since all of our supported versions must be PCI compliant this change had to be made. 

Having said that, it does appear there is an error with the type that violates our policies. But, I would strongly advise you to get your site working with CSP as this is the last line of defense against malware and card skimmers. Plus, it would put you at risk of PCI audit failure especially since the auditors will be on high alert since it's a new requirement.

**Comment by nathanjosiah** [comment]
@magento export issue to Jira project AC as Bug

**Comment by sidolov** [comment]
@magento export issue to Jira project AC as Bug

**Comment by Franciscof-Serfe** [comment]
Is the [Issue: Confirmed](https://github.com/magento/magento2/labels/Issue%3A%20Confirmed) tab necessary first?

**Comment by fritzmg** [comment]
> But, I would strongly advise you to get your site working with CSP as this is the last line of defense against malware and card skimmers. Plus, it would put you at risk of PCI audit failure especially since the auditors will be on high alert since it's a new requirement.

@nathanjosiah While I agree that CPS should be enabled in any case, CSP must not be a requirement, at least not for this reason. Your shop does not have to have an actual payment module. In our case the Magento instance is a B2C shop with a checkout that contains **no payment** options. In our case the fix is easy, as we can just disable the payment module itself (it was an error that we didn't).

The error is that `Magento_PaymentServicesPaypal` is missing the `Magento_Csp` dependency in its `composer.json` and `etc/module.xml`.

**Comment by nathanjosiah** [comment]
We are working on this internally. 

As a reference for any Adobe members, this was transferred from [AC-13063](https://jira.corp.adobe.com/browse/AC-13063) to [PAY-5690](https://jira.corp.adobe.com/browse/PAY-5690)

**Comment by fritzmg** [comment]
The same error happens within `Magento\AdminAnalytics\ViewModel\Metadata`:

https://github.com/magento/magento2/blob/5a2037c35de89ce2c50e230164ff3ea7b67ac127/app/code/Magento/AdminAnalytics/ViewModel/Metadata.php#L75-L77


It also has a hard dependency on `Magento_Csp`, but it is missing from the `module.xml`:

https://github.com/magento/magento2/blob/5a2037c35de89ce2c50e230164ff3ea7b67ac127/app/code/Magento/AdminAnalytics/etc/module.xml#L8-L10

**Comment by amine-y** [comment]
I have the same problem here on 2.4.6-p8. It is supposed to be just a security patch, but now we have a CSP problem. We were going to planify this for 2.4.7 version.

**Comment by usuyukiso** [comment]
Also reproduced for 2.4.8-p1
