### ISSUE TITLE
Magento doesn't work with Redis in cluster mode

### ISSUE THREAD

**Issue by speller** [magento/magento2#39224]
### Preconditions and environment

- Magento version 2.4.7
- ElastiCache Serverless Redis (cluster mode is always on)

### Steps to reproduce

Run cache clean command

### Expected result

It works properly

### Actual result

Error

```none
Error cleaning cache by mode matchingTag: CROSSSLOT Keys in request don't hash to the same slot
#0 /magento/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php(1010): Zend_Cache::throwException('Error cleaning ...', Object(CredisException))
#1 /magento/vendor/magento/zend-cache/library/Zend/Cache/Core.php(465): Cm_Cache_Backend_Redis->clean('matchingTag', Array)\n#2 /magento/vendor/magento/framework/Cache/Core.php(92): Zend_Cache_Core->clean('matchingTag', Array)
#3 /magento/vendor/magento/framework/Cache/Frontend/Adapter/Zend.php(103): Magento\\Framework\\Cache\\Core->clean('matchingTag', Array)\n#4 /magento/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(89): Magento\\Framework\\Cache\\Frontend\\Adapter\\Zend->clean('matchingTag', Array)
#5 /magento/vendor/magento/framework/Cache/Frontend/Decorator/TagScope.php(76): Magento\\Framework\\Cache\\Frontend\\Decorator\\Bare->clean('matchingTag', Array)
#6 /magento/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(89): Magento\\Framework\\Cache\\Frontend\\Decorator\\TagScope->clean('matchingTag', Array)
#7 /magento/vendor/magento/framework/Cache/Frontend/Decorator/Logger.php(47): Magento\\Framework\\Cache\\Frontend\\Decorator\\Bare->clean('matchingTag', Array)
#8 /magento/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(89): Magento\\Framework\\Cache\\Frontend\\Decorator\\Logger->clean('matchingTag', Array)
#9 /magento/vendor/magento/framework/App/Cache/Type/AccessProxy.php(107): Magento\\Framework\\Cache\\Frontend\\Decorator\\Bare->clean('matchingTag', Array)
#10 /magento/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(89): Magento\\Framework\\App\\Cache\\Type\\AccessProxy->clean('matchingTag', Array)
#11 /magento/vendor/magento/framework/Cache/Frontend/Decorator/TagScope.php(76): Magento\\Framework\\Cache\\Frontend\\Decorator\\Bare->clean('matchingTag', Array)
#12 /magento/vendor/magento/module-page-cache/Model/Cache/Type.php(52): Magento\\Framework\\Cache\\Frontend\\Decorator\\TagScope->clean('matchingTag', Array)
#13 /magento/vendor/magento/module-page-cache/Observer/FlushAllCache.php(66): Magento\\PageCache\\Model\\Cache\\Type->clean()
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
I'm not sure this should be reported to Magento, maybe a better place to report it would be to one of the colinmollenhour repo's that deal with the communication from Magento to Redis.

I think there are already some (old) attempts at adding that functionality, just posting some links, I'm not familiar with the technology so no idea if these make sense for your request:
- https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/pull/62
- https://github.com/colinmollenhour/php-redis-session-abstract/pull/62
- https://github.com/colinmollenhour/credis/pull/191

**Comment by speller** [comment]
@hostep the referenced PR suggests adding a new client class and Magento should also add support for it. So some work on the  Magento side is also required.

**Comment by JacobBrownAustin** [comment]
FYI, I'm already working on a pull request for the session part of it of it (not the cache backend).  It's a simple PR from the Magento side since it just exposes the new configuration options for clusters to the PR I've made to the php-redis-session-abstract.  I'm not working at all on the cache part at all, so I can't comment on that.

**Comment by engcom-Hotel** [comment]
Hello @speller,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the vanilla Magento 2.4-develop branch with Redis in cluster mode. The issue seems reproducible for us.

Hence confirming the issue.

Thanks
