### ISSUE TITLE
Uncaught TypeError: this._each is not a function

### ISSUE THREAD

**Issue by pjw345** [magento/magento2#39247]
### Preconditions and environment

- Magento 2.4.7-p2
- New Relic agents installed (not using Magento NewRelic modules)

### Steps to reproduce

1. Navigate to Dashboard (adminhtml)
2. check console log

### Expected result

Expect no console errors logged

### Actual result

Lots of errors logged repeatedly:
legacy-build.min.js:1 Uncaught TypeError: this._each is not a function
at e (legacy-build.min.js:1:14513)
at nr-spa-1.267.0.min.js:2:81604
at Array.forEach ()
at y.ce [as onFinished] (nr-spa-1.267.0.min.js:2:81583)
at y.finish (nr-spa-1.267.0.min.js:2:76545)
at nr-spa-1.267.0.min.js:2:76118

### Additional information

This is related to legacy-build.min.js which is released with Magento 2.4.7-p2.   If the file is replaced by the version released by Magento 2.4.7-p1 the error goes away.

See also issue logged on New Relic github:
https://github.com/newrelic/newrelic-browser-agent/issues/1201

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pisicabogdan** [comment]
Same error on Magento 2.4.6-p6

**Comment by mrafyq** [comment]
Same error on Magento 2.4.5-p10

**Comment by usuyukiso** [comment]
reproduced for me on 2.4.7-p3. It is only reproduced with New Relic installed.

**Comment by MagePsycho** [comment]
Same issue on Magento 2.4.5-p2.
It is only reproduced with New Relic installed. 
Got it fixed by using the legacy-build js file from Magento 2.4.7-p1 (still yet to check it's consequences)

**Comment by pjw345** [comment]
I've checked the bulletin and have not seen anything regarding legacy-build.min.js.

https://helpx.adobe.com/security/products/magento/apsb24-61.html

@bbrigagao can you remember where you read that or did I miss it?

**Comment by pisicabogdan** [comment]
Again, same error on Magento 2.4.6-p7 (last week upgraded from 2.4.6-p6).

**Comment by bbrigagao** [comment]
@pjw345 I found that the legacy-build.min.js is related to prototype js on this [issue](https://github.com/magento/magento2/issues/32853#issuecomment-885595723).
So, I suspected that could be related to this since on bulletin APSB24-61 there was a fix on prototype js scripts.

**Comment by MagePsycho** [comment]
I believe the issue can be resolved by fixing the `legacy-build.min.js` file directly. According to this ticket - https://github.com/newrelic/newrelic-browser-agent/issues/1201, it appears that the legacy JavaScript is overriding `Object.values()`, which is causing the problem.

Please let us know if the Magento team or any of you have identified a permanent fix.

**Comment by stefancic** [comment]
Same error on 2.4.4-p11, was not on 2.4.4-p4.

**Comment by alexgalco** [comment]
Confirmed on 2.4.7-p2

**Comment by pisicabogdan** [comment]
Changed legacy-build.min.js with the version from 2.4.6-p5 but with no effect; the problem isn't from legacy-build.min.js

**Comment by hostep** [comment]
[ACP2E-3375: [CLOUD] In admin there are many javascript error in console ](https://github.com/magento/magento2/commit/66c31215ceadde1c9b06c52f4db21672dc4a51f5) probably fixes this problem.

**Comment by jonaschen623** [comment]
adobe has an official patch for this issue, please raise a support ticket.
Below one is for magento 2.4.6
[ACSD-62427_2.4.6-p7.patch](https://github.com/user-attachments/files/17593954/ACSD-62427_2.4.6-p7.patch)

**Comment by stefancic** [comment]
None of last two patches fix this.

**Comment by engcom-Delta** [comment]
Hi @pjw345 ,

Thanks for your reporting and collaboration.
We have verified the issue in Latest 2.4-develop instance & 2.4.8-beta1 instance, but we are unable to reproduce the issue. Kindly refer the screenshots. 

**Steps to reproduce**
1. Install latest 2.4-develop instance
2. New Relic agents installed
3. Navigate to Dashboard (adminhtml)
4. check console log
Observe no console error is displaying
![image](https://github.com/user-attachments/assets/638eaeea-54ed-46f9-a114-8e79e81bad9d)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by bohdanbatsenko** [comment]
Hi @pjw345 ,
I have the same issue. It exists in admin panel -> Content -> Pages -> Page builder. Try to open page builder and check console. On my staging magento website, upgraded to magento 2.47, the issue exists only in page builder editing mode.
Thanks

**Comment by engcom-Delta** [comment]
Hi @pjw345  @bohdanbatsenko ,

Thanks for your reporting and collaboration.
We have verified the issue in Latest 2.4-develop instance and the issue is reproducible. Kindly refer the screenshots.

**Steps to reproduce**
1. Install latest 2.4-develop instance
2. New Relic agents installed
3. Navigate to Dashboard (adminhtml)
4. Navigate to content > pages > pagebuilder.
5. check console log
6. Lots of errors logged repeatedly
![image](https://github.com/user-attachments/assets/6f68e0de-ca8f-403e-afaa-fd3c3e2d33ac)

Thanks.

**Comment by bohdanbatsenko** [comment]
Hi @pjw345 
Is there any fix to this bug?

**Comment by pjw345** [comment]
@bohdanbatsenko as previously stated, replacing the legacy-build.min.js with the version of 2.4.7-p1 appeared to resolve the issue

**Comment by jtolhurst-trellis** [comment]
Replacing legacy-build.min.js with the version found in 2.4.7-p1 resolved the error for me.  Waiting on an official fix.

**Comment by hostep** [comment]
> [ACP2E-3375: [CLOUD] In admin there are many javascript error in console](https://github.com/magento/magento2/commit/66c31215ceadde1c9b06c52f4db21672dc4a51f5) probably fixes this problem.

Another extra change made it in the codebase today: [ACP2E-3459: Request for additional changes to fully complete the ACP2E-3375 fix](https://github.com/magento/magento2/commit/9408cfee9b5de0a3d8a18ce91e85846fe2ec8a34)

No idea if this will do anything in scope of this ticket...

**Comment by lamasfoker** [comment]
@BharathKumarZiffity if the patch that I provided it does not apply on 2.4.7-p3 version (cloud) then you can generate a new one for your version. I stated the diff in my previous message, in that way you can generate a patch for your version.

**Comment by kvydiuk** [comment]
Hi there,

I've seen this error on the Magento Cloud project (2.4.4-p11) when New Relic Browser's "Agent and account" setting was set to "Pro + SPA".
The error disappeared after switching this setting to "Pro"
<img width="755" alt="Screenshot 2024-12-06 at 2 59 08 pm" src="https://github.com/user-attachments/assets/7d3bf2da-eb9b-433c-87e1-4d666a90d97d">

Hopefully, this will help someone.

**Comment by abhilashvijayan** [comment]
Apply the patch ACSD-63244 for Adobe commerce cloud environment. Worked for me.
