### ISSUE TITLE
Cannot instantiate interface Magento\ServicesId\Model\ServicesConfigInterface

### ISSUE THREAD

**Issue by j2vos** [magento/magento2#39387]
### Preconditions and environment

Hello,

I am currently on the migration from 2.4.6p2 to 2.4.7p3 and during a setup:upgrade I get this error message:

```
Module 'Magento_ServicesId': 
2024-11-19T15:10:39.287144308Z 2024-11-19T15:10:39.287157301Z There is an error in /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php at line: 50 2024-11-19T15:10:39.287160569Z Cannot instantiate interface Magento\ServicesId\Model\ServicesConfigInterface#0 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(73): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() 
2024-11-19T15:10:39.287165109Z #1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\Ob
jectManager\ObjectManager->get() 
2024-11-19T15:10:39.287167809Z #2 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() 2024-11-19T15:10:39.287170497Z #3 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() 2024-11-19T15:10:39.287173150Z #4 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() 
2024-11-19T15:10:39.287175785Z #5 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() 2024-11-19T15:10:39.287178396Z #6 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() 2024-11-19T15:10:39.287180987Z #7 /var/www/html/setup/src/Magento/Setup/Model/Installer.php(1250): Magento\Framework\ObjectManager\ObjectManager->create() 
2024-11-19T15:10:39.287183505Z #8 /var/www/html/setup/src/Magento/Setup/Model/Installer.php(1668): Magento\Setup\Model\Installer->createSchemaDataHandler() 
2024-11-19T15:10:39.287186019Z #9 /var/www/html/setup/src/Magento/Setup/Model/Installer.php(1114): Magento\Setup\Model\Installer->getSchemaDataHandler() 
2024-11-19T15:10:39.287188550Z #10 /var/www/html/setup/src/Magento/Setup/Model/Installer.php(966): Magento\Setup\Model\Installer->handleDBSchemaData() 
2024-11-19T15:10:39.287191047Z #11 /var/www/html/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php(149): Magento\Setup\Model\Installer->installDataFixtures() 
2024-11-19T15:10:39.287194156Z #12 /var/www/html/vendor/symfony/console/Command/Command.php(326): Magento\Setup\Console\Command\UpgradeCommand->execute() 
2024-11-19T15:10:39.287204791Z #13 /var/www/html/vendor/symfony/console/Application.php(1078): Sy
mfony\Component\Console\Command\Command->run() 
2024-11-19T15:10:39.287207805Z #14 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand() 
2024-11-19T15:10:39.287210440Z #15 /var/www/html/vendor/magento/framework/Console/Cli.php(118): Symfony\Component\Console\Application->doRun() 
2024-11-19T15:10:39.287212960Z #16 /var/www/html/vendor/symfony/console/Application.php(175): Magento\Framework\Console\Cli->doRun() 
2024-11-19T15:10:39.287215461Z #17 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run() 
```

The module vendor is present, it is not disabled by the config.php

The Magento_Config and Magento_ServicesConnector dependencies are also present and not disabled.

I can't understand why, I'm a bit stuck, if you have any ideas.

### Steps to reproduce

php bin/magento se:up

### Expected result

Setup upgrade

### Actual result

Setup upgrade KO

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @j2vos,

This issue is being closed since it has not been updated in a long time.
Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
