### ISSUE TITLE
Fatal error on accessing web magento setup page 

### ISSUE THREAD

**Issue by kgvconsulting** [magento/magento2#4278]
After the update see #4260, front and back of magento works fine except one issue, following described. I found other articles about the same however there was no answer from Magento about that. Could you please advise?

other reported issues for that same error:
#4001

https://community.magento.com/t5/Technical-Issues/Fatal-error-magento-setup/m-p/26444#M335

Issue with web wizard setup page: I tried to access the web wizard setup page from admin back side and got this error

Fatal error: Uncaught exception 'Exception' with message 'Notice: Undefined index: arguments in /xxxx/xxxx/magento_root/vendor/magento/framework/ObjectManager/Config/Compiled.php on line 132' in /xxxx/xxxx/magento_root/vendor/magento/framework/App/ErrorHandler.php:61 Stack trace: #0 /xxxx/xxxx/magento_root/vendor/magento/framework/ObjectManager/Config/Compiled.php(132): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/xxxx/xxxx/...', 132, Array) #1 /xxxx/xxxx/magento_root/vendor/magento/framework/ObjectManager/ObjectManager.php(84): Magento\Framework\ObjectManager\Config\Compiled->extend(Array) #2 /xxxx/xxxx/magento_root/setup/src/Magento/Setup/Model/ObjectManagerProvider.php(62): Magento\Framework\ObjectManager\ObjectManager->configure(Array) #3 /xxxx/xxxx/magento_root/setup/src/Magento/Setup/Mvc/Bootstrap/InitParamListener.php(122): Magento\Setup\Model\ObjectManagerProvider->get() #4 [internal function]: Magento\Setup\Mvc\Bootstrap\InitParamListener->authPreDispatch(Object(Zen in /xxxx/xxxx/magento_root/vendor/magento/framework/App/ErrorHandler.php on line 61

**Comment by kgvconsulting** [comment]
it was resolved see #4260
