### ISSUE TITLE
Error after upgrading from 2.0.6 to 2.1-rc1

### ISSUE THREAD

**Issue by digitalpianism** [magento/magento2#4738]
## Steps to reproduce
1. `git checkout 2.1-rc1`
2. `composer update`
3. Access the backend
## Expected result
1. Backend is accessible
2. ...
## Actual result
1. Got the following exception

```
a:4:{i:0;s:327:"Strict Notice: Declaration of Magento\Store\Model\ResourceModel\Website\Interceptor::afterLoad() should be compatible with Magento\Framework\Model\ResourceModel\Db\AbstractDb::afterLoad(Magento\Framework\DataObject $object) in /var/www/magento2/var/generation/Magento/Store/Model/ResourceModel/Website/Interceptor.php on line 7";i:1;s:8658:"#0 /var/www/magento2/var/generation/Magento/Store/Model/ResourceModel/Website/Interceptor.php(7): Magento\Framework\App\ErrorHandler->handler(2048, 'Declaration of ...', '/var/www/magent...', 7, Array)
#1 /var/www/magento2/vendor/composer/ClassLoader.php(412): include('/var/www/magent...')
#2 /var/www/magento2/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/magent...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Magento\\Store\\M...')
#4 [internal function]: spl_autoload_call('Magento\\Store\\M...')
#5 /var/www/magento2/lib/internal/Magento/Framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Store\\M...')
#6 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Store\\M...')
#7 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Store\\M...')
#8 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Store\\M...', Array)
#9 /var/www/magento2/lib/internal/Magento/Framework/Model/ResourceModel/Db/Collection/AbstractCollection.php(461): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Store\\M...')
#10 /var/www/magento2/lib/internal/Magento/Framework/Model/ResourceModel/Db/Collection/AbstractCollection.php(123): Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection->getResource()
#11 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(109): Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection->__construct(Object(Magento\Framework\Data\Collection\EntityFactory), Object(Magento\Framework\Logger\Monolog), Object(Magento\Framework\Data\Collection\Db\FetchStrategy\Cache), Object(Magento\Framework\Event\Manager\Proxy), NULL, NULL)
#12 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Store\\M...', Array)
#13 /var/www/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Store\\M...', Array)
#14 /var/www/magento2/var/generation/Magento/Store/Model/ResourceModel/Website/CollectionFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create('\\Magento\\Store\\...', Array)
#15 /var/www/magento2/app/code/Magento/Store/Model/WebsiteRepository.php(122): Magento\Store\Model\ResourceModel\Website\CollectionFactory->create()
#16 /var/www/magento2/app/code/Magento/Store/Model/StoreResolver/Website.php(46): Magento\Store\Model\WebsiteRepository->getDefault()
#17 /var/www/magento2/app/code/Magento/Store/Model/StoreResolver.php(136): Magento\Store\Model\StoreResolver\Website->getAllowedStoreIds(NULL)
#18 /var/www/magento2/app/code/Magento/Store/Model/StoreResolver.php(122): Magento\Store\Model\StoreResolver->readStoresData()
#19 /var/www/magento2/app/code/Magento/Store/Model/StoreResolver.php(85): Magento\Store\Model\StoreResolver->getStoresData()
#20 /var/www/magento2/app/code/Magento/Store/Model/StoreManager.php(151): Magento\Store\Model\StoreResolver->getCurrentStoreId()
#21 /var/www/magento2/var/generation/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore(NULL)
#22 /var/www/magento2/app/code/Magento/Store/Model/Resolver/Store.php(29): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL)
#23 /var/www/magento2/lib/internal/Magento/Framework/App/Config/ScopePool.php(139): Magento\Store\Model\Resolver\Store->getScope(NULL)
#24 /var/www/magento2/lib/internal/Magento/Framework/App/Config/ScopePool.php(93): Magento\Framework\App\Config\ScopePool->_getScopeCode('store', NULL)
#25 /var/www/magento2/lib/internal/Magento/Framework/App/Config.php(45): Magento\Framework\App\Config\ScopePool->getScope('store', NULL)
#26 /var/www/magento2/app/code/Magento/Developer/Helper/Data.php(32): Magento\Framework\App\Config->getValue('dev/restrict/al...', 'store', NULL)
#27 /var/www/magento2/app/code/DigitalPianism/Commercebug/Observers/AbstractObserver.php(24): Magento\Developer\Helper\Data->isDevAllowed()
#28 /var/www/magento2/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(73): DigitalPianism\Commercebug\Observers\AbstractObserver->execute(Object(Magento\Framework\Event\Observer))
#29 /var/www/magento2/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(DigitalPianism\Commercebug\Observers\Collection), Object(Magento\Framework\Event\Observer))
#30 [internal function]: Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#31 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(146): call_user_func_array(Array, Array)
#32 /var/www/magento2/var/generation/Magento/Framework/Event/Invoker/InvokerDefault/Interceptor.php(26): Magento\Framework\Event\Invoker\InvokerDefault\Interceptor->___callPlugins('dispatch', Array, Array)
#33 /var/www/magento2/lib/internal/Magento/Framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault\Interceptor->dispatch(Array, Object(Magento\Framework\Event\Observer))
#34 [internal function]: Magento\Framework\Event\Manager->dispatch('core_collection...', Array)
#35 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(146): call_user_func_array(Array, Array)
#36 /var/www/magento2/var/generation/Magento/Framework/Event/Manager/Interceptor.php(26): Magento\Framework\Event\Manager\Interceptor->___callPlugins('dispatch', Array, Array)
#37 /var/www/magento2/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager\Interceptor->dispatch('core_collection...', Array)
#38 /var/www/magento2/lib/internal/Magento/Framework/Model/ResourceModel/Db/Collection/AbstractCollection.php(529): Magento\Framework\Event\Manager\Proxy->dispatch('core_collection...', Array)
#39 /var/www/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(569): Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection->_beforeLoad()
#40 /var/www/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(557): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#41 /var/www/magento2/lib/internal/Magento/Framework/Data/Collection.php(820): Magento\Framework\Data\Collection\AbstractDb->load()
#42 /var/www/magento2/app/code/Magento/Store/Model/Config/Reader/DefaultReader.php(65): Magento\Framework\Data\Collection->getIterator()
#43 /var/www/magento2/lib/internal/Magento/Framework/App/Config/ScopePool.php(104): Magento\Store\Model\Config\Reader\DefaultReader->read()
#44 /var/www/magento2/app/code/Magento/Backend/App/Config.php(41): Magento\Framework\App\Config\ScopePool->getScope('default', NULL)
#45 /var/www/magento2/app/code/Magento/Backend/App/Area/FrontNameResolver.php(82): Magento\Backend\App\Config->getValue('admin/url/use_c...')
#46 /var/www/magento2/app/code/Magento/Backend/Helper/Data.php(206): Magento\Backend\App\Area\FrontNameResolver->getFrontName(false)
#47 /var/www/magento2/app/code/Magento/Backend/App/Request/PathInfoProcessor.php(46): Magento\Backend\Helper\Data->getAreaFrontName()
#48 /var/www/magento2/var/generation/Magento/Backend/App/Request/PathInfoProcessor/Proxy.php(95): Magento\Backend\App\Request\PathInfoProcessor->process(Object(Magento\Framework\App\Request\Http), '/admin_1ai7c5/a...')
#49 /var/www/magento2/lib/internal/Magento/Framework/App/Request/Http.php(161): Magento\Backend\App\Request\PathInfoProcessor\Proxy->process(Object(Magento\Framework\App\Request\Http), '/admin_1ai7c5/a...')
#50 /var/www/magento2/lib/internal/Magento/Framework/HTTP/PhpEnvironment/Request.php(194): Magento\Framework\App\Request\Http->setPathInfo()
#51 /var/www/magento2/lib/internal/Magento/Framework/App/Request/Http.php(204): Magento\Framework\HTTP\PhpEnvironment\Request->getPathInfo()
#52 /var/www/magento2/lib/internal/Magento/Framework/App/Http.php(130): Magento\Framework\App\Request\Http->getFrontName()
#53 /var/www/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#54 /var/www/magento2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#55 {main}";s:3:"url";s:101:"/admin_1ai7c5/admin/cache/index/key/ee107cb7ed5ca3e08f0ff54d2552a015a92768197c289ffd4ac3cb3eaff70997/";s:11:"script_name";s:10:"/index.php";}
```

It has nothing to do with Alan Storm's `DigitalPianism_Commercebug` module.

The real problem is that the `afterSave` method declaration has changed from 2.0 to 2.1

2.0 version:

```
    public function afterLoad(\Magento\Framework\Model\AbstractModel $object)
    {
        $this->_afterLoad($object);
    }
```

2.1 version:

```
    public function afterLoad(\Magento\Framework\DataObject $object)
    {
        $this->_afterLoad($object);
    }
```

I ended up fixing the issue by running:

```
php bin/magento module:disable DigitalPianism_Commercebug`
rm -rf var/cache/ var/generation/ var/page_cache/`
php bin/magento setup:upgrade
php bin/magento module:enable DigitalPianism_Commercebug
```

**Comment by mazhalai** [comment]
@digitalpianism the proper steps for upgrading when using git versions are documented here: http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/dev_update-magento.html

Looks like you missed `setup:upgrade` which would have cleaned up di generation and cache. There is one open issue regarding cache not being enabled again after CLI upgrade, #4707, but everything else should be working fine.

**Comment by mazhalai** [comment]
@digitalpianism closing due to non-responsiveness.
