### ISSUE TITLE
Error while creating credit memo: Cannot save the credit memo

### ISSUE THREAD

**Issue by klict** [magento/magento2#4895]
When creating a credit memo in Magento 2.0.7, we get a the error "Cannot save the credit memo". When tracking it down, it seems we get an exception "There is no active transaction" in `vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:411`, which was caused in `vendor/magento/framework/Model/ResourceModel/AbstractResource.php:81` when executing `\Magento\Framework\Model\ResourceModel\AbstractResource::commit` on a `\Magento\Sales\Model\ResourceModel\Order\Creditmemo` object. 
## Steps to reproduce
1. Create new order.
2. Create invoice of order
3. Create credit memo for the order
## Expected result
1. New credit memo is created for the order
## Actual result

Error: Cannot save the credit memo?
![knipsel](https://cloud.githubusercontent.com/assets/16023301/15820873/8a56570e-2bec-11e6-912f-2a4d62f59285.PNG)

This is the exception we got:

```
There is no active transaction

 #0 /var/www/domains/webshop.nl/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(316): PDO->commit() 
 #1 /var/www/domains/webshop.nl/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(510): Zend_Db_Adapter_Pdo_Abstract->_commit() 
 #2 /var/www/domains/webshop.nl/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(239): Zend_Db_Adapter_Abstract->commit() 
 #3 /var/www/domains/webshop.nl/vendor/magento/framework/Model/ResourceModel/AbstractResource.php(82): Magento\Framework\DB\Adapter\Pdo\Mysql->commit() 
 #4 /var/www/domains/webshop.nl/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(408): Magento\Framework\Model\ResourceModel\AbstractResource->commit() 
 #5 /var/www/domains/webshop.nl/vendor/magento/module-sales/Model/Order/CreditmemoRepository.php(135): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Magento\Sales\Model\Order\Creditmemo\Interceptor)) 
 #6 [internal function]: Magento\Sales\Model\Order\CreditmemoRepository->save(Object(Magento\Sales\Model\Order\Creditmemo\Interceptor)) 
 #7 /var/www/domains/webshop.nl/vendor/magento/framework/Interception/Interceptor.php(144): call_user_func_array(Array, Array) 
 #8 /var/www/domains/webshop.nl/var/generation/Magento/Sales/Model/Order/CreditmemoRepository/Interceptor.php(78): Magento\Sales\Model\Order\CreditmemoRepository\Interceptor->___callPlugins('save', Array, Array) 
 #9 /var/www/domains/webshop.nl/vendor/magento/module-sales/Model/Service/CreditmemoService.php(151): Magento\Sales\Model\Order\CreditmemoRepository\Interceptor->save(Object(Magento\Sales\Model\Order\Creditmemo\Interceptor)) 
 #10 [internal function]: Magento\Sales\Model\Service\CreditmemoService->refund(Object(Magento\Sales\Model\Order\Creditmemo\Interceptor), true, false) 
 #11 /var/www/domains/webshop.nl/vendor/magento/framework/Interception/Interceptor.php(144): call_user_func_array(Array, Array) 
 #12 /var/www/domains/webshop.nl/var/generation/Magento/Sales/Model/Service/CreditmemoService/Interceptor.php(65): Magento\Sales\Model\Service\CreditmemoService\Interceptor->___callPlugins('refund', Array, Array) 
 #13 /var/www/domains/webshop.nl/vendor/magento/module-sales/Controller/Adminhtml/Order/Creditmemo/Save.php(106): Magento\Sales\Model\Service\CreditmemoService\Interceptor->refund(Object(Magento\Sales\Model\Order\Creditmemo\Interceptor), true, false) 
 #14 /var/www/domains/webshop.nl/var/generation/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/Save/Interceptor.php(25): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save->execute() 
 #15 /var/www/domains/webshop.nl/vendor/magento/framework/App/Action/Action.php(102): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->execute() 
 #16 /var/www/domains/webshop.nl/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) 
 #17 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http)) 
 #18 /var/www/domains/webshop.nl/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array) 
 #19 /var/www/domains/webshop.nl/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callParent('dispatch', Array) 
 #20 /var/www/domains/webshop.nl/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor), Array, 'adminAuthentica...') 
 #21 /var/www/domains/webshop.nl/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http)) 
 #22 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) 
 #23 /var/www/domains/webshop.nl/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array) 
 #24 /var/www/domains/webshop.nl/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor), Array, 'designLoader') 
 #25 /var/www/domains/webshop.nl/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http)) 
 #26 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) 
 #27 /var/www/domains/webshop.nl/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array) 
 #28 /var/www/domains/webshop.nl/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor), Array, 'adminMassaction...') 
 #29 /var/www/domains/webshop.nl/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) 
 #30 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) 
 #31 /var/www/domains/webshop.nl/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array) 
 #32 /var/www/domains/webshop.nl/var/generation/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/Save/Interceptor.php(40): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->___callPlugins('dispatch', Array, Array) 
 #33 /var/www/domains/webshop.nl/vendor/magento/framework/App/FrontController.php(55): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) 
 #34 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http)) 
 #35 /var/www/domains/webshop.nl/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array) 
 #36 /var/www/domains/webshop.nl/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array) 
 #37 /var/www/domains/webshop.nl/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install') 
 #38 /var/www/domains/webshop.nl/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) 
 #39 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) 
 #40 /var/www/domains/webshop.nl/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array) 
 #41 /var/www/domains/webshop.nl/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array) 
 #42 /var/www/domains/webshop.nl/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) 
 #43 /var/www/domains/webshop.nl/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch() 
 #44 /var/www/domains/webshop.nl/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http)) 
 #45 {main}
```

**Comment by NadiyaS** [comment]
Hi @klict ,
we can not reproduce this issue. Can you provide us what payment method do you use or other information which can affect this issue.
Thanks

**Comment by klict** [comment]
Hi @NadiyaS  ,
I have used 'Check / Money order' for payment method and we used 'Table Rates' as shipping method. We have tried to create credit memo of orders originated from backend and frontend but with both we can't create a credit memo.

**Comment by klict** [comment]
So we found the cause of the problem after few days of research and  it seems an another module is causing it.

**Comment by NadiyaS** [comment]
thank you for reporting this.

**Comment by btjackson11** [comment]
@klict do you remember which module it is? Having the same issue, but can't track down what is causing it.

**Comment by klict** [comment]
@btjackson11  
Hi, 
In our case it was "FollowupEmail" by Aheadworks. We don't know what they did but we couldn't create any creditmemo.

**Comment by NSanthoshpriya** [comment]
@klict 
How exactly did u solve this problem? I'm Having the Same issue but i'm not using the above stated module. So how to resolve?

**Comment by klict** [comment]
@NSanthoshpriya 
First I tried to backtrack to the source problem but I ended in a dead end. 
So I tried to disable all extensions and test it again. To my surprise I could create a credit memo with that result, it was clear that the problem was caused by an extension. So the next best thing I did was to enable one by one and test it again until I found the problem.

**Comment by Grietzz** [comment]
Is it possible this problem still exists? I have tried enabling all my extensions, but unfortunately it makes no differences. Using magnto 2.1.5.

**Comment by MonsterEdward** [comment]
How did U solve this problem finally?
![2yqd9 j1kodpeyh tnu1 0o](https://cloud.githubusercontent.com/assets/22072869/26815963/de9a72e2-4ac1-11e7-961f-0cc7114eb488.png)
I have the same issue,but I don't use any above module.The payment method is Authorize.net Direct Post.

**Comment by patrickpeng2091** [comment]
Mageplaza SMTP Plugin couldn't create any creditmemo.
