### ISSUE TITLE
When placing reorder: You need to choose options for your item.

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#4953]
When I want to reorder a product, I get the following error:

```
You need to choose options for your item.
#0 /var/www/awesome/var/generation/Magento/Sales/Model/AdminOrder/Create/Interceptor.php(141): Magento\Sales\Model\AdminOrder\Create->initFromOrder(Object(Magento\Sales\Model\Order))
#1 /var/www/awesome/vendor/magento/module-sales/Controller/Adminhtml/Order/Create/Reorder.php(27): Magento\Sales\Model\AdminOrder\Create\Interceptor->initFromOrder(Object(Magento\Sales\Model\Order))
#2 /var/www/awesome/var/generation/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder/Interceptor.php(25): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder->execute()
#3 /var/www/awesome/vendor/magento/framework/App/Action/Action.php(102): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->execute()
#4 /var/www/awesome/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#5 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /var/www/awesome/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#7 /var/www/awesome/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->___callParent('dispatch', Array)
#8 /var/www/awesome/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Array, 'adminAuthentica...')
#9 /var/www/awesome/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#10 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#11 /var/www/awesome/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#12 /var/www/awesome/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Array, 'designLoader')
#13 /var/www/awesome/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#14 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 /var/www/awesome/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#16 /var/www/awesome/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Array, 'adminMassaction...')
#17 /var/www/awesome/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /var/www/awesome/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#20 /var/www/awesome/var/generation/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder/Interceptor.php(40): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->___callPlugins('dispatch', Array, Array)
#21 /var/www/awesome/vendor/magento/framework/App/FrontController.php(55): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#22 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /var/www/awesome/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#24 /var/www/awesome/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#25 /var/www/awesome/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#26 /var/www/awesome/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /var/www/awesome/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#29 /var/www/awesome/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#30 /var/www/awesome/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /var/www/awesome/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#32 /var/www/awesome/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#33 {main}
```

However, this is a reorder of an already placed order earlier. I get this error as soon as I click 'reorder' in the backend. Anyone knows what might be going on here?

**Comment by mhabou** [comment]
Same error , but i got it just in one order.

Magento CE 2.07

```
You need to choose options for your item.
#0 /var/www/html/app/code/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder.php(27): Magento\Sales\Model\AdminOrder\Create->initFromOrder(Object(Magento\Sales\Model\Order))
#1 /var/www/html/var/generation/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder/Interceptor.php(25): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder->execute()
#2 /var/www/html/lib/internal/Magento/Framework/App/Action/Action.php(102): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->execute()
#3 /var/www/html/app/code/Magento/Backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#4 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#6 /var/www/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->___callParent('dispatch', Array)
#7 /var/www/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Array, 'adminAuthentica...')
#8 /var/www/html/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#9 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /var/www/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#11 /var/www/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Array, 'designLoader')
#12 /var/www/html/lib/internal/Magento/Framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#13 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#15 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Array, 'adminMassaction...')
#16 /var/www/html/app/code/Magento/Backend/App/Action/Plugin/MassactionKey.php(33): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#19 /var/www/html/var/generation/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder/Interceptor.php(40): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->___callPlugins('dispatch', Array, Array)
#20 /var/www/html/lib/internal/Magento/Framework/App/FrontController.php(55): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#21 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#23 /var/www/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#24 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#25 /var/www/html/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#26 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#28 /var/www/html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#29 /var/www/html/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /var/www/html/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#31 /var/www/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#32 {main}
```

**Comment by mhabou** [comment]
With fresh insallation , i got the same error

Magento CE 2.07

```
You need to choose options for your item.
#0 /var/www/html/app/code/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder.php(27): Magento\Sales\Model\AdminOrder\Create->initFromOrder(Object(Magento\Sales\Model\Order\Interceptor))
#1 /var/www/html/var/generation/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder/Interceptor.php(25): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder->execute()
#2 /var/www/html/lib/internal/Magento/Framework/App/Action/Action.php(102): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->execute()
#3 /var/www/html/app/code/Magento/Backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#4 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#6 /var/www/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->___callParent('dispatch', Array)
#7 /var/www/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Array, 'adminAuthentica...')
#8 /var/www/html/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#9 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /var/www/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#11 /var/www/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Array, 'designLoader')
#12 /var/www/html/lib/internal/Magento/Framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#13 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#15 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Array, 'adminMassaction...')
#16 /var/www/html/app/code/Magento/Backend/App/Action/Plugin/MassactionKey.php(33): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#19 /var/www/html/var/generation/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder/Interceptor.php(40): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->___callPlugins('dispatch', Array, Array)
#20 /var/www/html/lib/internal/Magento/Framework/App/FrontController.php(55): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#21 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#23 /var/www/html/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#24 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#25 /var/www/html/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#26 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#28 /var/www/html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#29 /var/www/html/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /var/www/html/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#31 /var/www/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#32 {main}
```

**Comment by mhabou** [comment]
I dont get the problem when the order state is canceled or pending

**Comment by andimov** [comment]
@kanduvisla, @Dayssam. We already have internal ticket MAGETWO-52946 to fix this issue

**Comment by Hawk30100** [comment]
Same problem for me with CE 2.1.0. Ordering a item with options lead to the text "You need to ..."

**Comment by kanduvisla** [comment]
Is this solved in 2.0.8?

**Comment by kanduvisla** [comment]
I just updated to 2.1.1 and this error still occurs when I try to place a reorder from the admin. The order in question has 2 simple products and 2 configurable products.

Is there any news on this issue? It breaks the possibility for my client to place a reorder.

**Comment by SerhiyShkolyarenko** [comment]
@kanduvisla please describe in a detailed way how to reproduce the issue if it's not the same as #6278.
We need all steps of order manipulations and all details of configurable products(options types, values, etc).
Also we need Magento mode you use to reproduce it.

**Comment by SerhiyShkolyarenko** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks. Please feel free to add your comments with details to reopen the issue.

**Comment by kvSanthosh** [comment]
Hi, 
I also have this issue, when I try to reorder some products. For these product, I changed the product name and that is the reason I assume. There are no custom options, also it's a simple product. But for other product with no changes in detail are able to reorder. As the product name is not a factor like options it should be able to reorder. please check and reply. Thanks.

**Comment by goeword** [comment]
Hi,

Is there an solution for this bug? I am experiencing same issue here. I cannot view and process orders now, this is very important issue.

**Comment by shirishShoptimize** [comment]
The error still occurs when we try to reorder from the admin.
Magento version: 2.1.15 CE

**Comment by jaykobi** [comment]
Error still present in Magento 2.2.6.

**Comment by jaykobi** [comment]
@magento-engcom-team Why is this issue closed?

**Comment by Sergio-Taddeo** [comment]
@magento-engcom-team I'm having the same issue.
Magento Version 2.1.6. I saw a reply saying the bug persists even on newest versions such as 2.2.6.
This is what I'm getting when trying to reorder through the admin:

![image](https://user-images.githubusercontent.com/46035402/50314000-14931380-0462-11e9-9e28-499e99bb8a0a.png)

Looking forward to hearing from you soon.
