### ISSUE TITLE
Upgrade from 2.0.7 to 2.1rc3 with command line

### ISSUE THREAD

**Issue by mhabou** [magento/magento2#5182]
## Steps to reproduce
1. cp composer.json composer.json.bak
2. composer require magento/product-community-edition 2.1.0-rc3 --no-update
3. composer require magento/module-bundle-sample-data:100.1.0-rc3 magento/module-widget-sample-data:100.1.0-rc3 magento/module-theme-sample-data:100.1.0-rc3 magento/module-catalog-sample-data:100.1.0-rc3 magento/module-customer-sample-data:100.1.0-rc3 magento/module-cms-sample-data:100.1.0-rc3  magento/module-catalog-rule-sample-data:100.1.0-rc3 magento/module-sales-rule-sample-data:100.1.0-rc3 magento/module-review-sample-data:100.1.0-rc3 magento/module-tax-sample-data:100.1.0-rc3 magento/module-sales-sample-data:100.1.0-rc3 magento/module-grouped-product-sample-data:100.1.0-rc3 magento/module-downloadable-sample-data:100.1.0-rc3 magento/module-msrp-sample-data:100.1.0-rc3 magento/module-configurable-sample-data:100.1.0-rc3 magento/module-product-links-sample-data:100.1.0-rc3 magento/module-wishlist-sample-data:100.1.0-rc3 magento/module-swatches-sample-data:100.1.0-rc3 magento/sample-data-media:100.1.0-rc3 magento/module-offline-shipping-sample-data:100.1.0-rc3 --no-update
4. composer update
## Expected result

No problems
## Actual result

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magento/product-community-edition 2.1.0-rc3 -> satisfiable by magento/product-community-edition[2.1.0-rc3].
    - magento/product-community-edition 2.1.0-rc3 requires composer/composer 1.0.0-beta1 -> satisfiable by composer/composer[1.0.0-beta1] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Installation request for magento/magento2ce 2.0.7 -> satisfiable by magento/magento2ce[2.0.7].
    - magento/module-catalog-sample-data 100.1.0-rc3 requires magento/module-sample-data 100.1.* -> satisfiable by magento/module-sample-data[100.1.0-rc1, 100.1.0-rc2, 100.1.0-rc3].
    - don't install magento/module-sample-data 100.1.0-rc1|remove magento/magento2ce 2.0.7
    - don't install magento/module-sample-data 100.1.0-rc2|remove magento/magento2ce 2.0.7
    - don't install magento/module-sample-data 100.1.0-rc3|remove magento/magento2ce 2.0.7
    - Installation request for magento/module-catalog-sample-data 100.1.0-rc3 -> satisfiable by magento/module-catalog-sample-data[100.1.0-rc3].

```

after that when i get back the old composer.json
& i want to go to the magento admin interface i got

```
exception 'Magento\Framework\Exception\LocalizedException' with message 'Source class "" for "Magento\Framework\App\Response\Http\Interceptor" generation does not exist.' in /var/www/html/lib/internal/Magento/Framework/Code/Generator.php:171 Stack trace: 

#0 /var/www/html/lib/internal/Magento/Framework/Code/Generator.php(100): Magento\Framework\Code\Generator->tryToLoadSourceClass('Magento\\Framewo...', Object(Magento\Framework\Interception\Code\Generator\Interceptor)) 

#1 /var/www/html/lib/internal/Magento/Framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Magento\\Framewo...') #2 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\\Framewo...') 

#3 /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(105): spl_autoload_call('Magento\\Framewo...') 

#4 /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array) 

#5 /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(130): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...') 

#6 /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php(67): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...') 

#7 /var/www/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...', Array) 

#8 /var/www/html/lib/internal/Magento/Framework/App/Bootstrap.php(233): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array) 

#9 /var/www/html/index.php(38): Magento\Framework\App\Bootstrap->createApplication('Magento\\Framewo...') #10 {main}
```

The apache log

```
[Thu Jun 23 11:36:12.823687 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP Warning:  ltrim() expects parameter 1 to be string, object given in /var/www/html/lib/internal/Magento/Framework/Code/Generator/EntityAbstract.php on line 152
[Thu Jun 23 11:36:12.823735 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP Stack trace:
[Thu Jun 23 11:36:12.823787 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   1. {main}() /var/www/html/index.php:0
[Thu Jun 23 11:36:12.823798 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   2. Magento\\Framework\\App\\Bootstrap->createApplication($type = *uninitialized*, $arguments = *uninitialized*) /var/www/html/index.php:38
[Thu Jun 23 11:36:12.823808 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   3. Magento\\Framework\\ObjectManager\\ObjectManager->create($type = *uninitialized*, $arguments = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/App/Bootstrap.php:233
[Thu Jun 23 11:36:12.823817 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   4. Magento\\Framework\\ObjectManager\\Factory\\Compiled->create($requestedType = *uninitialized*, $arguments = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:57
[Thu Jun 23 11:36:12.823826 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   5. Magento\\Framework\\ObjectManager\\Factory\\Compiled->get($type = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:67
[Thu Jun 23 11:36:12.823836 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   6. Magento\\Framework\\ObjectManager\\Factory\\Compiled->create($requestedType = *uninitialized*, $arguments = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:130
[Thu Jun 23 11:36:12.823845 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   7. Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject($type = *uninitialized*, $args = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:88
[Thu Jun 23 11:36:12.823854 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   8. spl_autoload_call(*uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:105
[Thu Jun 23 11:36:12.823862 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   9. Magento\\Framework\\Code\\Generator\\Autoloader->load($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:105
[Thu Jun 23 11:36:12.823871 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  10. Magento\\Framework\\Code\\Generator->generateClass($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator/Autoloader.php:35
[Thu Jun 23 11:36:12.823881 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  11. Magento\\Framework\\Code\\Generator->createGeneratorInstance($generatorClass = *uninitialized*, $entityName = *uninitialized*, $className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator.php:98
[Thu Jun 23 11:36:12.823890 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  12. Magento\\Framework\\ObjectManager\\ObjectManager->create($type = *uninitialized*, $arguments = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator.php:127
[Thu Jun 23 11:36:12.823900 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  13. Magento\\Framework\\ObjectManager\\Factory\\Compiled->create($requestedType = *uninitialized*, $arguments = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:57
[Thu Jun 23 11:36:12.823909 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  14. Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject($type = *uninitialized*, $args = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:88
[Thu Jun 23 11:36:12.823933 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  15. Magento\\Framework\\Code\\Generator\\EntityAbstract->__construct($sourceClassName = *uninitialized*, $resultClassName = *uninitialized*, $ioObject = *uninitialized*, $classGenerator = *uninitialized*, $definedClasses = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:97
[Thu Jun 23 11:36:12.823943 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  16. Magento\\Framework\\Code\\Generator\\EntityAbstract->_getFullyQualifiedClassName($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator/EntityAbstract.php:81
[Thu Jun 23 11:36:12.823950 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  17. ltrim(*uninitialized*, *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator/EntityAbstract.php:152
[Thu Jun 23 11:36:12.824026 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP Notice:  Uninitialized string offset: 0 in /var/www/html/lib/internal/Magento/Framework/Autoload/ClassLoaderWrapper.php on line 81
[Thu Jun 23 11:36:12.824032 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP Stack trace:
[Thu Jun 23 11:36:12.824046 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   1. {main}() /var/www/html/index.php:0
[Thu Jun 23 11:36:12.824054 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   2. Magento\\Framework\\App\\Bootstrap->createApplication($type = *uninitialized*, $arguments = *uninitialized*) /var/www/html/index.php:38
[Thu Jun 23 11:36:12.824063 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   3. Magento\\Framework\\ObjectManager\\ObjectManager->create($type = *uninitialized*, $arguments = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/App/Bootstrap.php:233
[Thu Jun 23 11:36:12.824071 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   4. Magento\\Framework\\ObjectManager\\Factory\\Compiled->create($requestedType = *uninitialized*, $arguments = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:57
[Thu Jun 23 11:36:12.824080 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   5. Magento\\Framework\\ObjectManager\\Factory\\Compiled->get($type = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:67
[Thu Jun 23 11:36:12.824088 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   6. Magento\\Framework\\ObjectManager\\Factory\\Compiled->create($requestedType = *uninitialized*, $arguments = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:130
[Thu Jun 23 11:36:12.824097 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   7. Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject($type = *uninitialized*, $args = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:88
[Thu Jun 23 11:36:12.824104 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   8. spl_autoload_call(*uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:105
[Thu Jun 23 11:36:12.824112 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   9. Magento\\Framework\\Code\\Generator\\Autoloader->load($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:105
[Thu Jun 23 11:36:12.824120 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  10. Magento\\Framework\\Code\\Generator->generateClass($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator/Autoloader.php:35
[Thu Jun 23 11:36:12.824129 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  11. Magento\\Framework\\Code\\Generator->tryToLoadSourceClass($className = *uninitialized*, $generator = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator.php:100
[Thu Jun 23 11:36:12.824137 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  12. Magento\\Framework\\Code\\Generator\\DefinedClasses->isClassLoadable($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator.php:169
[Thu Jun 23 11:36:12.824151 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  13. Magento\\Framework\\Code\\Generator\\DefinedClasses->isClassLoadableFromDisc($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator/DefinedClasses.php:24
[Thu Jun 23 11:36:12.824159 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  14. Magento\\Framework\\Autoload\\ClassLoaderWrapper->findFile($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator/DefinedClasses.php:47
[Thu Jun 23 11:36:12.824334 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP Notice:  Uninitialized string offset: 0 in /var/www/html/vendor/composer/ClassLoader.php on line 317
[Thu Jun 23 11:36:12.824340 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP Stack trace:
[Thu Jun 23 11:36:12.824346 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   1. {main}() /var/www/html/index.php:0
[Thu Jun 23 11:36:12.824354 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   2. Magento\\Framework\\App\\Bootstrap->createApplication($type = *uninitialized*, $arguments = *uninitialized*) /var/www/html/index.php:38
[Thu Jun 23 11:36:12.824363 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   3. Magento\\Framework\\ObjectManager\\ObjectManager->create($type = *uninitialized*, $arguments = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/App/Bootstrap.php:233
[Thu Jun 23 11:36:12.824371 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   4. Magento\\Framework\\ObjectManager\\Factory\\Compiled->create($requestedType = *uninitialized*, $arguments = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:57
[Thu Jun 23 11:36:12.824379 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   5. Magento\\Framework\\ObjectManager\\Factory\\Compiled->get($type = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:67
[Thu Jun 23 11:36:12.824388 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   6. Magento\\Framework\\ObjectManager\\Factory\\Compiled->create($requestedType = *uninitialized*, $arguments = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:130
[Thu Jun 23 11:36:12.824397 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   7. Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject($type = *uninitialized*, $args = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:88
[Thu Jun 23 11:36:12.824404 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   8. spl_autoload_call(*uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:105
[Thu Jun 23 11:36:12.824412 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   9. Magento\\Framework\\Code\\Generator\\Autoloader->load($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:105
[Thu Jun 23 11:36:12.824420 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  10. Magento\\Framework\\Code\\Generator->generateClass($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator/Autoloader.php:35
[Thu Jun 23 11:36:12.824428 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  11. Magento\\Framework\\Code\\Generator->tryToLoadSourceClass($className = *uninitialized*, $generator = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator.php:100
[Thu Jun 23 11:36:12.824437 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  12. Magento\\Framework\\Code\\Generator\\DefinedClasses->isClassLoadable($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator.php:169
[Thu Jun 23 11:36:12.824445 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  13. Magento\\Framework\\Code\\Generator\\DefinedClasses->isClassLoadableFromDisc($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator/DefinedClasses.php:24
[Thu Jun 23 11:36:12.824458 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  14. Magento\\Framework\\Autoload\\ClassLoaderWrapper->findFile($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator/DefinedClasses.php:47
[Thu Jun 23 11:36:12.824466 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  15. Composer\\Autoload\\ClassLoader->findFile($class = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Autoload/ClassLoaderWrapper.php:85
[Thu Jun 23 11:36:12.824491 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP Notice:  Uninitialized string offset: 0 in /var/www/html/vendor/composer/ClassLoader.php on line 349
[Thu Jun 23 11:36:12.824497 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP Stack trace:
[Thu Jun 23 11:36:12.824503 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   1. {main}() /var/www/html/index.php:0
[Thu Jun 23 11:36:12.824511 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   2. Magento\\Framework\\App\\Bootstrap->createApplication($type = *uninitialized*, $arguments = *uninitialized*) /var/www/html/index.php:38
[Thu Jun 23 11:36:12.824520 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   3. Magento\\Framework\\ObjectManager\\ObjectManager->create($type = *uninitialized*, $arguments = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/App/Bootstrap.php:233
[Thu Jun 23 11:36:12.824529 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   4. Magento\\Framework\\ObjectManager\\Factory\\Compiled->create($requestedType = *uninitialized*, $arguments = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:57
[Thu Jun 23 11:36:12.824537 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   5. Magento\\Framework\\ObjectManager\\Factory\\Compiled->get($type = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:67
[Thu Jun 23 11:36:12.824546 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   6. Magento\\Framework\\ObjectManager\\Factory\\Compiled->create($requestedType = *uninitialized*, $arguments = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:130
[Thu Jun 23 11:36:12.824555 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   7. Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject($type = *uninitialized*, $args = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:88
[Thu Jun 23 11:36:12.824562 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   8. spl_autoload_call(*uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:105
[Thu Jun 23 11:36:12.824570 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP   9. Magento\\Framework\\Code\\Generator\\Autoloader->load($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:105
[Thu Jun 23 11:36:12.824578 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  10. Magento\\Framework\\Code\\Generator->generateClass($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator/Autoloader.php:35
[Thu Jun 23 11:36:12.824587 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  11. Magento\\Framework\\Code\\Generator->tryToLoadSourceClass($className = *uninitialized*, $generator = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator.php:100
[Thu Jun 23 11:36:12.824595 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  12. Magento\\Framework\\Code\\Generator\\DefinedClasses->isClassLoadable($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator.php:169
[Thu Jun 23 11:36:12.824603 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  13. Magento\\Framework\\Code\\Generator\\DefinedClasses->isClassLoadableFromDisc($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator/DefinedClasses.php:24
[Thu Jun 23 11:36:12.824616 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  14. Magento\\Framework\\Autoload\\ClassLoaderWrapper->findFile($className = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Code/Generator/DefinedClasses.php:47
[Thu Jun 23 11:36:12.824625 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  15. Composer\\Autoload\\ClassLoader->findFile($class = *uninitialized*) /var/www/html/lib/internal/Magento/Framework/Autoload/ClassLoaderWrapper.php:85
[Thu Jun 23 11:36:12.824633 2016] [:error] [pid 9921] [client 127.0.0.1:59923] PHP  16. Composer\\Autoload\\ClassLoader->findFileWithExtension($class = *uninitialized*, $ext = *uninitialized*) /var/www/html/vendor/composer/ClassLoader.php:329

```

The output of "bin/magento setup:upgrade" and " bin/magento setup:di:compile"

```
  [ErrorException]                                        
  ltrim() expects parameter 1 to be string, object given  

setup:upgrade [--keep-generated] [--magento-init-params="..."]
```

**Comment by andimov** [comment]
@Dayssam thank you for reporting.
Please, attach your composer.json file

**Comment by mhabou** [comment]
@andimov : 

Sorry i deleted everything & i reinstalled magento 2.1rc3

But i got almost the same error when i compiled magento, i fixed it by deleting this folder var/di

**Comment by andimov** [comment]
@Dayssam, thank you for response.
I can not reproduce this bug.
Your steps is correct but there are no data of all preconditions.
If you think that it was an error in Magento, please provide additional data about precondition and environment.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
