### ISSUE TITLE
[CE 2.1.0 RC3] Reorder issue - The options you selected are not available

### ISSUE THREAD

**Issue by mhabou** [magento/magento2#5192]
## Steps to reproduce
1. Install Magento CE 2.1.0 RC3
2. Add Bundle Product to the cart
3. invoice & ship
4. reorder
## Expected result

No problem
## Actual result

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The options you selected are not available.

Exception #0 (Magento\Framework\Exception\LocalizedException): The options you selected are not available.
#0 /var/www/html/vendor/magento/module-sales/Controller/Adminhtml/Order/Create/Reorder.php(27): Magento\Sales\Model\AdminOrder\Create->initFromOrder(Object(Magento\Sales\Model\Order))
#1 /var/www/html/var/generation/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder/Interceptor.php(24): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder->execute()
#2 /var/www/html/vendor/magento/framework/App/Action/Action.php(102): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->execute()
#3 /var/www/html/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->___callParent('dispatch', Array)
#6 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Array, 'adminAuthentica...')
#7 /var/www/html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#8 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#9 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Array, 'adminMassaction...')
#10 /var/www/html/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /var/www/html/var/generation/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder/Interceptor.php(39): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->___callPlugins('dispatch', Array, Array)
#13 /var/www/html/vendor/magento/framework/App/FrontController.php(55): Magento\Sales\Controller\Adminhtml\Order\Create\Reorder\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /var/www/html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#17 /var/www/html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /var/www/html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#20 /var/www/html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#22 /var/www/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#23 {main}

```

**Comment by andimov** [comment]
@Dayssam 
The Bundle Product was created in 2.1.0-rc3 or was migrated from earlier versions?

**Comment by mhabou** [comment]
@andimov 

From fresh install , from the sample data

**Comment by veloraven** [comment]
Was not able to reproduce on fresh install without sample data

**Comment by VasylShvorak** [comment]
@Dayssam Is this issue still actual? We were not able to reproduce it on the ver. 2.1.7

**Comment by PascalBrouwers** [comment]
Issue is still active. This happens when:
- you order a bundle
- change the bundle but keep the same products (bundle option id's get changed)
- reorder

**Comment by PascalBrouwers** [comment]
@Dayssam can you change the title and remove "CE 2.1.0 RC3" ?

**Comment by magento-engcom-team** [comment]
@Dayssam, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
