### ISSUE TITLE
Products with Custom Options crash afther upgrading from M2.0.7 to M2.1-rc3 

### ISSUE THREAD

**Issue by salelsol** [magento/magento2#5384]
Upgrading it´s all O.K. but when go to a product with custom options then frontend crash:
1 exception(s):
Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/module-catalog/Block/Product/View/Options.php on line 213

Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/module-catalog/Block/Product/View/Options.php on line 213
#0 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/module-catalog/Block/Product/View/Options.php(213): Magento\Framework\App\ErrorHandler->handler(2, 'Invalid argumen...', '/home/39552-428...', 213, Array)
#1 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/module-catalog/view/frontend/templates/product/view/options.phtml(18): Magento\Catalog\Block\Product\View\Options->getJsonConfig()
#2 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/39552-428...')
#3 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Options), '/home/39552-428...', Array)
#4 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/39552-428...')
#5 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#6 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#7 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('product.info.op...')
#8 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('product.info.op...')
#9 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info.op...')
#10 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('product.info.op...', true)
#11 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(503): Magento\Framework\View\Layout\Interceptor->renderElement('product.info.op...', true)
#12 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(778): Magento\Framework\View\Element\AbstractBlock->getChildHtml('', true)
#13 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/module-catalog/view/frontend/templates/product/view/options/wrapper.phtml(15): Magento\Catalog\Block\Product\View\Interceptor->getChildHtml('', true)
#14 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/39552-428...')
#15 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Interceptor), '/home/39552-428...', Array)
#16 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(544): Magento\Framework\View\Element\Template->fetchView('/home/39552-428...')
#17 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Catalog\Block\Product\View\Interceptor->fetchView('/home/39552-428...')
#18 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#19 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(869): Magento\Framework\View\Element\AbstractBlock->toHtml()
#20 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Catalog\Block\Product\View\Interceptor->toHtml()
#21 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('product.info.op...')
#22 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('product.info.op...')
#23 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info.op...')
#24 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('product.info.op...', true)
#25 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(534): Magento\Framework\View\Layout\Interceptor->renderElement('product.info.op...', true)
#26 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(791): Magento\Framework\View\Element\AbstractBlock->getChildChildHtml('options_contain...', '', true)
#27 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/module-catalog/view/frontend/templates/product/view/form.phtml(35): Magento\Catalog\Block\Product\View\Interceptor->getChildChildHtml('options_contain...')
#28 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/39552-428...')
#29 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Interceptor), '/home/39552-428...', Array)
#30 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(544): Magento\Framework\View\Element\Template->fetchView('/home/39552-428...')
#31 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Catalog\Block\Product\View\Interceptor->fetchView('/home/39552-428...')
#32 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#33 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Catalog/Block/Product/View/Interceptor.php(869): Magento\Framework\View\Element\AbstractBlock->toHtml()
#34 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Catalog\Block\Product\View\Interceptor->toHtml()
#35 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('product.info')
#36 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('product.info')
#37 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info')
#38 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('product.info', true)
#39 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('product.info')
#40 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('product.info.ma...')
#41 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('product.info.ma...')
#42 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info.ma...')
#43 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('product.info.ma...', true)
#44 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('product.info.ma...')
#45 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#46 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#47 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#48 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#49 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#50 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main')
#51 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#52 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#53 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', true)
#54 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main')
#55 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('columns')
#56 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#57 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#58 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', true)
#59 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('columns')
#60 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.content')
#61 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#62 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#63 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
#64 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
#65 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#66 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#67 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#68 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#69 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#70 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#71 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#72 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#73 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#74 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#75 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Layout->getOutput()
#76 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#77 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#78 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#79 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#80 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#81 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#82 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#83 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#84 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#85 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#86 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#87 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#88 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#89 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#90 /home/39552-42818.cloudwaysapps.com/tmhajncrvn/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

**Comment by salelsol** [comment]
Confict with installed extension not upgraded to Magento 2.1.
