### ISSUE TITLE
Upgraded from 2.0.7 to 2.1.0 - Frontend Product goes to 404 error with CRITICAL: exception 'ReflectionException'

### ISSUE THREAD

**Issue by malaiselvan** [magento/magento2#5800]
Upgraded Magento from 2.0.7 to 2.1.0.   When the product is clicked on the front-end, the detail pages goes to 404 page not found.  In the exception it got the below error

```
[2016-07-25 22:34:44] main.CRITICAL: exception 'ReflectionException' with message 'Class Magento\Catalog\Model\Product\Attribute\Backend\Media does not exist' in /home/abcdnet/public_html/vendor/magento/framework/Code/Reader/ClassReader.php:19
Stack trace:
#0 /home/abcdnet/public_html/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Catalog...')
#1 /home/abcdnet/public_html/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Catalog...')
#2 /home/abcdnet/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Catalog...')
#3 /home/abcdnet/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...', Array)
#4 /home/abcdnet/public_html/vendor/magento/framework/Validator/UniversalFactory.php(36): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Catalog...', Array)
#5 /home/abcdnet/public_html/vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php(498): Magento\Framework\Validator\UniversalFactory->create('Magento\\Catalog...')
#6 /home/abcdnet/public_html/var/generation/Magento/Catalog/Model/ResourceModel/Eav/Attribute/Interceptor.php(1103): Magento\Eav\Model\Entity\Attribute\AbstractAttribute->getBackend()
#7 /home/abcdnet/public_html/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php(139): Magento\Catalog\Model\ResourceModel\Eav\Attribute\Interceptor->getBackend()
#8 /home/abcdnet/public_html/vendor/magento/framework/EntityManager/Operation/Read/ReadAttributes.php(59): Magento\Eav\Model\ResourceModel\ReadHandler->execute('Magento\\Catalog...', Array, Array)
#9 /home/abcdnet/public_html/vendor/magento/framework/EntityManager/Operation/Read.php(116): Magento\Framework\EntityManager\Operation\Read\ReadAttributes->execute(Object(Magento\Catalog\Model\Product\Interceptor), Array)
#10 /home/abcdnet/public_html/vendor/magento/framework/EntityManager/EntityManager.php(61): Magento\Framework\EntityManager\Operation\Read->execute(Object(Magento\Catalog\Model\Product\Interceptor), 7, Array)
#11 /home/abcdnet/public_html/vendor/magento/module-catalog/Model/ResourceModel/Product.php(655): Magento\Framework\EntityManager\EntityManager->load(Object(Magento\Catalog\Model\Product\Interceptor), 7)
#12 /home/abcdnet/public_html/var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(258): Magento\Catalog\Model\ResourceModel\Product->load(Object(Magento\Catalog\Model\Product\Interceptor), 7, NULL)
#13 /home/abcdnet/public_html/vendor/magento/framework/Model/AbstractModel.php(531): Magento\Catalog\Model\ResourceModel\Product\Interceptor->load(Object(Magento\Catalog\Model\Product\Interceptor), 7, NULL)
#14 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\Model\AbstractModel->load(7)
#15 /home/abcdnet/public_html/var/generation/Magento/Catalog/Model/Product/Interceptor.php(2301): Magento\Catalog\Model\Product\Interceptor->___callPlugins('load', Array, Array)
#16 /home/abcdnet/public_html/vendor/magento/module-catalog/Model/ProductRepository.php(241): Magento\Catalog\Model\Product\Interceptor->load(7)
#17 /home/abcdnet/public_html/var/generation/Magento/Catalog/Model/ProductRepository/Interceptor.php(37): Magento\Catalog\Model\ProductRepository->getById(7, false, '1', false)
#18 /home/abcdnet/public_html/var/generation/Magento/Catalog/Api/ProductRepositoryInterface/Proxy.php(111): Magento\Catalog\Model\ProductRepository\Interceptor->getById(7, false, '1', false)
#19 /home/abcdnet/public_html/vendor/magento/module-catalog/Helper/Product.php(417): Magento\Catalog\Api\ProductRepositoryInterface\Proxy->getById(7, false, '1')
#20 /home/abcdnet/public_html/vendor/magento/module-catalog/Helper/Product/View.php(212): Magento\Catalog\Helper\Product->initProduct(7, Object(Magento\Catalog\Controller\Product\View\Interceptor), Object(Magento\Framework\DataObject))
#21 /home/abcdnet/public_html/vendor/magento/module-catalog/Controller/Product/View.php(109): Magento\Catalog\Helper\Product\View->prepareAndRender(Object(Magento\Framework\View\Result\Page\Interceptor), 7, Object(Magento\Catalog\Controller\Product\View\Interceptor), Object(Magento\Framework\DataObject))
#22 /home/abcdnet/public_html/var/generation/Magento/Catalog/Controller/Product/View/Interceptor.php(24): Magento\Catalog\Controller\Product\View->execute()
#23 /home/abcdnet/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Product\View\Interceptor->execute()
#24 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Product\View\Interceptor->___callParent('dispatch', Array)
#26 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Product\View\Interceptor), Array, 'contextPlugin')
#27 /home/abcdnet/public_html/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Catalog\Controller\Product\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Product\View\Interceptor), Array, 'storeCheck')
#30 /home/abcdnet/public_html/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Catalog\Controller\Product\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Product\View\Interceptor), Array, 'customer-app-ac...')
#33 /home/abcdnet/public_html/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Catalog\Controller\Product\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Product\View\Interceptor), Array, 'tax-app-action-...')
#36 /home/abcdnet/public_html/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#37 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Catalog\Controller\Product\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#38 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Product\View\Interceptor), Array, 'weee-app-action...')
#39 /home/abcdnet/public_html/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Catalog\Controller\Product\View\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#40 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Catalog\Controller\Product\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#41 /home/abcdnet/public_html/var/generation/Magento/Catalog/Controller/Product/View/Interceptor.php(39): Magento\Catalog\Controller\Product\View\Interceptor->___callPlugins('dispatch', Array, Array)
#42 /home/abcdnet/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Product\View\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#43 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#44 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#45 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#46 /home/abcdnet/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#47 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#48 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#49 /home/abcdnet/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#50 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#51 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#52 /home/abcdnet/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#53 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#54 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#55 /home/abcdnet/public_html/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#56 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#57 /home/abcdnet/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#58 /home/abcdnet/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#59 /home/abcdnet/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#60 /home/abcdnet/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#61 {main} [] []
```
### Preconditions
1. Upgraded Magento from 2.0.7 to 2.1.0
2. fyi, it was originally migrated from 1.9.0.1 to 2.0.3 and to 2.0.7 and now 2.1.0
3. PHP 5.6.23 (cli) (built: Jun 24 2016 07:07:36)
### Steps to reproduce
1. Click on the product detail page
### Expected result
1. The product detail page should displayed
### Actual result
1. 404 Page not found error displayed
2. Error created in exception.log file

**Comment by dthampy** [comment]
@malaiselvan,

Did you get any error while upgrading from 2.0.7 to 2.1.0 via command line
bin/magento setup:upgrade

Also , just want to know if you cleared all directories and files under Magento’s var subdirectory ?
rm -rf cache/\* di/\* generation/\* page_cache/*

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
