### ISSUE TITLE
Upgraded from 2.0.7 to 2.1.0 - View Order - Exception occurred during order load

### ISSUE THREAD

**Issue by malaiselvan** [magento/magento2#5801]
Magento 2.1.0 throws error `Exception occurred during order load` when trying to view a single order from admin side.

```
[2016-07-25 22:45:07] main.CRITICAL: exception 'Magento\Framework\Exception\LocalizedException' with message 'Object DOMDocument should be created.' in /home/abcdnet/public_html/vendor/magento/framework/View/Element/UiComponent/Config/DomMerger.php:408
Stack trace:
#0 /home/abcdnet/public_html/vendor/magento/framework/View/Element/UiComponent/Config/Reader.php(95): Magento\Framework\View\Element\UiComponent\Config\DomMerger->getDom()
#1 /home/abcdnet/public_html/vendor/magento/module-ui/Model/Manager.php(258): Magento\Framework\View\Element\UiComponent\Config\Reader->read()
#2 /home/abcdnet/public_html/vendor/magento/module-ui/Model/Manager.php(166): Magento\Ui\Model\Manager->prepare('sales_order_edi...')
#3 /home/abcdnet/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(144): Magento\Ui\Model\Manager->prepareData('sales_order_edi...')
#4 /home/abcdnet/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(125): Magento\Framework\View\Element\UiComponentFactory->create('sales_order_edi...', NULL, Array)
#5 /home/abcdnet/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'sales_order_edi...', Array, Object(Magento\Framework\View\Layout\Interceptor))
#6 /home/abcdnet/public_html/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#7 /home/abcdnet/public_html/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#8 /home/abcdnet/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#9 /home/abcdnet/public_html/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#10 /home/abcdnet/public_html/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#11 /home/abcdnet/public_html/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#12 /home/abcdnet/public_html/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#13 /home/abcdnet/public_html/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#14 /home/abcdnet/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#15 /home/abcdnet/public_html/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#16 /home/abcdnet/public_html/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Sales::...')
#17 /home/abcdnet/public_html/vendor/magento/module-sales/Controller/Adminhtml/Order.php(140): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Sales::...')
#18 /home/abcdnet/public_html/vendor/magento/module-sales/Controller/Adminhtml/Order/View.php(30): Magento\Sales\Controller\Adminhtml\Order->_initAction()
#19 /home/abcdnet/public_html/var/generation/Magento/Sales/Controller/Adminhtml/Order/View/Interceptor.php(24): Magento\Sales\Controller\Adminhtml\Order\View->execute()
#20 /home/abcdnet/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->execute()
#21 /home/abcdnet/public_html/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->___callParent('dispatch', Array)
#24 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\View\Interceptor), Array, 'adminAuthentica...')
#25 /home/abcdnet/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#26 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\View\Interceptor), Array, 'adminMassaction...')
#28 /home/abcdnet/public_html/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#29 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /home/abcdnet/public_html/var/generation/Magento/Sales/Controller/Adminhtml/Order/View/Interceptor.php(39): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->___callPlugins('dispatch', Array, Array)
#31 /home/abcdnet/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#33 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#34 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#35 /home/abcdnet/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#36 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 /home/abcdnet/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#38 /home/abcdnet/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#39 /home/abcdnet/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#40 /home/abcdnet/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#41 {main} [] []
```
### Preconditions
1.  Magento 2.1.0, PHP 5.6.23
2. Upgraded from 2.0.7 to 2.1.0
3. fyi,  it was originally migrated from 1.9.0 to 2.0.3 using data migration tool
### Steps to reproduce
1.  Upgrade 2.0.7 to 2.1.0 using command line
2.  Click on Sales -> Orders
3.  Click on single order
### Expected result
1.  The order should be displayed
### Actual result
1. It lists the orders back with an error 'Exception occurred during order load'

**Comment by daschenbrener** [comment]
I get this exact error, have you got anywhere with this?

**Comment by snez** [comment]
+1

**Comment by lucscu** [comment]
+1

**Comment by nigelcopley** [comment]
is there a solve for this?

**Comment by nigelcopley** [comment]
This is happening on 2.1.5 after upgrade - odd if the only change was an update in copyrights.

**Comment by withtwogees** [comment]
+1
I've also checked the permissions on var/generation, var/di etc and all seem to be ok. Definitely looking for a fix

**Comment by sumit2jcommerce** [comment]
I do have the same issue on 2.1.3
Here is the fixes for the same:
https://magento.stackexchange.com/a/173055/50145

**Comment by magento-engcom-team** [comment]
@malaiselvan, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@malaiselvan, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0, 2.1.9

**Comment by magento-engcom-team** [comment]
@malaiselvan, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0, 2.1.9

**Comment by michelve** [comment]
same issue on 2.2.5
