### ISSUE TITLE
Upgraded from 2.0.7 to 2.1.0 - Exception while editing a migrated product

### ISSUE THREAD

**Issue by malaiselvan** [magento/magento2#5802]
Migrated the Magento from 2.0.7 to 2.1.0 using command line.  When a product is edited from the back-end it thows the below exception

```
a:4:{i:0;s:98:"The configuration parameter "componentType" is a required for "advanced_pricing_button" component.";i:1;s:8097:"#0 /home/abcdnet/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(362): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#1 /home/abcdnet/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(362): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#2 /home/abcdnet/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(362): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#3 /home/abcdnet/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(272): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#4 /home/abcdnet/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(164): Magento\Framework\View\Element\UiComponentFactory->mergeMetadata('product_form', Array, false)
#5 /home/abcdnet/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(125): Magento\Framework\View\Element\UiComponentFactory->create('product_form', NULL, Array)
#6 /home/abcdnet/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'product_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
#7 /home/abcdnet/public_html/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#8 /home/abcdnet/public_html/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#9 /home/abcdnet/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#10 /home/abcdnet/public_html/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#11 /home/abcdnet/public_html/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#12 /home/abcdnet/public_html/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#13 /home/abcdnet/public_html/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#14 /home/abcdnet/public_html/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#15 /home/abcdnet/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#16 /home/abcdnet/public_html/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#17 /home/abcdnet/public_html/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Catalog...')
#18 /home/abcdnet/public_html/vendor/magento/module-catalog/Controller/Adminhtml/Product/Edit.php(69): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Catalog...')
#19 /home/abcdnet/public_html/var/generation/Magento/Catalog/Controller/Adminhtml/Product/Edit/Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Product\Edit->execute()
#20 /home/abcdnet/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->execute()
#21 /home/abcdnet/public_html/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->___callParent('dispatch', Array)
#24 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Array, 'adminAuthentica...')
#25 /home/abcdnet/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#26 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Array, 'adminMassaction...')
#28 /home/abcdnet/public_html/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#29 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /home/abcdnet/public_html/var/generation/Magento/Catalog/Controller/Adminhtml/Product/Edit/Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#31 /home/abcdnet/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Product\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#33 /home/abcdnet/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#34 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#35 /home/abcdnet/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#36 /home/abcdnet/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 /home/abcdnet/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#38 /home/abcdnet/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#39 /home/abcdnet/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#40 /home/abcdnet/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#41 {main}";s:3:"url";s:111:"/index.php/shop/catalog/product/edit/id/1/key/f409d25b84bc91776d14f98f03a4f218622e50964fd735e6ee1dfd45b026baf9/";s:11:"script_name";s:10:"/index.php";}
```
### Preconditions
1. Magento 2.1.0, PHP 5.6.23
2. Upgraded from 2.0.7 to 2.1.0
3. fyi, it was originally migrated from 1.9.0.1 to 2.0.3 and then migrated to 2.0.7
### Steps to reproduce
1. Migrate from 2.0.7 to 2.1.0
2. Click on Catalog and Products
3. Click on a single product to edit
### Expected result
1.  The problem should open in the edit mode
### Actual result
1. Exception raised

Please note, the hack #5236 doesnt work for me.  After apply the hack it shows `Class Magento\Catalog\Model\Product\Attribute\Backend\Media does not exist`

**Comment by flexxus** [comment]
I have exactly the same problem

**Comment by dthampy** [comment]
internal jira ticket -MAGETWO-56063 created

**Comment by malucy** [comment]
Same issue here ...

**Comment by malucy** [comment]
``[2016-08-12 09:06:51] main.CRITICAL: exception 'ReflectionException' with message 'Class Magento\Catalog\Model\Product\Attribute\Backend\Media does not exist' in /home/genparts/public_html/mage2/vendor/magento/framework/Code/Reader/ClassReader.php:19
Stack trace:
#0 /home/genparts/public_html/mage2/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\Catalog...')
#1 /home/genparts/public_html/mage2/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\Catalog...')

**Comment by dgdevendra45** [comment]
main.CRITICAL: exception 'ReflectionException' with message 'Class Magento\Catalog\Model\Product\Attribute\Backend\Media does not exist' in /var/www/project/vendor/magento/framework/Code/Reader/ClassReader.php:19

Same here, you people find any solution?

**Comment by diegoalex90123** [comment]
![capture](https://cloud.githubusercontent.com/assets/23315630/20061925/d2ea5202-a4cf-11e6-9dca-0f55ba918c5e.JPG)

Same issue, doesn´t matter if trying to update a existing product or creating a new one, image attached.

**Comment by magento-engcom-team** [comment]
@malaiselvan, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
