### ISSUE TITLE
Click on Backup fails (Magento 2.0.8)

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#5815]
### Preconditions
1.  Magento 2.0.8
### Steps to reproduce
1.  Klick on System Backups
### Expected result
1. Page to do Backups will open
### Actual result
1. Error Message 
   Item (Magento\Framework\DataObject) with the same id "1469529628_db" already exist

```
Item (Magento\Framework\DataObject) with the same id "1469529628_db" already exist
#0 /home/zizzowa1/public_html/vendor/magento/framework/Data/Collection/Filesystem.php(324): Magento\Framework\Data\Collection->addItem(Object(Magento\Framework\DataObject))
#1 /home/zizzowa1/public_html/vendor/magento/framework/Data/Collection.php(677): Magento\Framework\Data\Collection\Filesystem->loadData(false, false)
#2 /home/zizzowa1/public_html/vendor/magento/framework/Data/Collection.php(286): Magento\Framework\Data\Collection->load()
#3 /home/zizzowa1/public_html/vendor/magento/module-backend/view/adminhtml/templates/widget/grid.phtml(51): Magento\Framework\Data\Collection->getSize()
#4 /home/zizzowa1/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/zizzowa1/...')
#5 /home/zizzowa1/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Widget\Grid), '/home/zizzowa1/...', Array)
#6 /home/zizzowa1/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/zizzowa1/...')
#7 /home/zizzowa1/public_html/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#8 /home/zizzowa1/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Backend\Block\Template->_toHtml()
#9 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#10 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('adminhtml.syste...')
#11 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('adminhtml.syste...')
#12 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('adminhtml.syste...')
#13 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('adminhtml.syste...', true)
#14 /home/zizzowa1/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(497): Magento\Framework\View\Layout\Interceptor->renderElement('adminhtml.syste...', true)
#15 /home/zizzowa1/public_html/vendor/magento/module-backup/view/adminhtml/templates/backup/list.phtml(10): Magento\Framework\View\Element\AbstractBlock->getChildHtml('grid')
#16 /home/zizzowa1/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/zizzowa1/...')
#17 /home/zizzowa1/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backup\Block\Adminhtml\Backup), '/home/zizzowa1/...', Array)
#18 /home/zizzowa1/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/zizzowa1/...')
#19 /home/zizzowa1/public_html/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#20 /home/zizzowa1/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Backend\Block\Template->_toHtml()
#21 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#22 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('adminhtml.syste...')
#23 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('adminhtml.syste...')
#24 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('adminhtml.syste...')
#25 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('adminhtml.syste...', true)
#26 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('adminhtml.syste...')
#27 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#28 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#29 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#30 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#31 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#32 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.col')
#33 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#34 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#35 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#36 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#37 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#38 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#39 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#40 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#41 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#42 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#43 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#44 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#45 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#46 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#47 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#48 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#49 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#50 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#51 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#52 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#53 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#54 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#55 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#56 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#57 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#58 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#59 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#60 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#61 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#62 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#63 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#64 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#65 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#66 /home/zizzowa1/public_html/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#67 /home/zizzowa1/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#68 /home/zizzowa1/public_html/vendor/magento/framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#69 /home/zizzowa1/public_html/vendor/magento/framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#70 /home/zizzowa1/public_html/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#71 /home/zizzowa1/public_html/vendor/magento/framework/App/View.php(221): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#72 /home/zizzowa1/public_html/vendor/magento/module-backup/Controller/Adminhtml/Index/Index.php(30): Magento\Framework\App\View->renderLayout()
#73 /home/zizzowa1/public_html/var/generation/Magento/Backup/Controller/Adminhtml/Index/Index/Interceptor.php(24): Magento\Backup\Controller\Adminhtml\Index\Index->execute()
#74 /home/zizzowa1/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor->execute()
#75 /home/zizzowa1/public_html/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#76 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#77 /home/zizzowa1/public_html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#78 /home/zizzowa1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor->___callParent('dispatch', Array)
#79 /home/zizzowa1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backup\\...', 'dispatch', Object(Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminAuthentica...')
#80 /home/zizzowa1/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#81 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#82 /home/zizzowa1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#83 /home/zizzowa1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backup\\...', 'dispatch', Object(Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor), Array, 'designLoader')
#84 /home/zizzowa1/public_html/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#85 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#86 /home/zizzowa1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(68): call_user_func_array(Array, Array)
#87 /home/zizzowa1/public_html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backup\\...', 'dispatch', Object(Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminMassaction...')
#88 /home/zizzowa1/public_html/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#89 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#90 /home/zizzowa1/public_html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#91 /home/zizzowa1/public_html/var/generation/Magento/Backup/Controller/Adminhtml/Index/Index/Interceptor.php(39): Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#92 /home/zizzowa1/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Backup\Controller\Adminhtml\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#93 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#94 /home/zizzowa1/public_html/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#95 /home/zizzowa1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#96 /home/zizzowa1/public_html/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#97 /home/zizzowa1/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#98 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#99 /home/zizzowa1/public_html/vendor/magento/framework/Interception/Interceptor.php(141): call_user_func_array(Array, Array)
#100 /home/zizzowa1/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#101 /home/zizzowa1/public_html/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#102 [internal function]: Magento\Framework\App\Http->launch()
#103 /home/zizzowa1/public_html/vendor/magento/framework/Interception/Interceptor.php(144): call_user_func_array(Array, Array)
#104 /home/zizzowa1/public_html/var/generation/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#105 /home/zizzowa1/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#106 /home/zizzowa1/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#107 {main}
```

**Comment by RomanKrut** [comment]
@flipflap Unfortunately, I could not reproduce the issue as you described it. Can you reproduce this issue on latest version of Magento2 ?

**Comment by flipflap** [comment]
I don't use system backup anymore. So I don't know. I think if no other people have this problem you can close it.

**Comment by veloraven** [comment]
I'm closing this issue as we were not able to reproduce it.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
