### ISSUE TITLE
Warning: Magento\Framework\Locale\TranslatedLists::getCountryTranslation():

### ISSUE THREAD

**Issue by mani-repos-link** [magento/magento2#5924]
I am new to Magento. I have installed new version 2.1.0_sample_data in my windows7 in localhost. 
I have installed magento. First there were missing some filesl so i run command `php bin/magento setup:static-content:deploy  it_IT`. This fix frontend but  in my chrome console i have this errors

```
jquery-migrate.js:21 JQMIGRATE: Logging is active

GET http://localhost/magento_2.1.0_sample/customer/section/load/?sections=directory-data&update_section_id=false&_=1470072550411 400 (Bad Request)  jquery.js:9666

Uncaught Error: [object Object] customer-data.js:86

GET http://localhost/magento_2.1.0_sample/customer/section/load/?sections=&update_section_id=false&_=1470072550410 400 (Bad Request) jquery.js:9666 

Uncaught Error: [object Object] customer-data.js:86  
```

I check  my /var/report directory : there were this log file 

```
a:4:{i:0;s:213:"Warning: Magento\Framework\Locale\TranslatedLists::getCountryTranslation(): Cannot load resource element 'AN' in C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\Locale\TranslatedLists.php on line 206";i:1;s:9042:"#0 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\Locale\TranslatedLists.php(206): Magento\Framework\App\ErrorHandler->handler(2, 'Magento\\Framewo...', 'C:\\xampp\\htdocs...', 206, Array)
#1 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\module-directory\Model\ResourceModel\Country\Collection.php(226): Magento\Framework\Locale\TranslatedLists->getCountryTranslation('AN')
#2 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\module-catalog\Model\Product\Attribute\Source\Countryofmanufacture.php(67): Magento\Directory\Model\ResourceModel\Country\Collection->toOptionArray()
#3 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\module-catalog\Ui\Component\ColumnFactory.php(65): Magento\Catalog\Model\Product\Attribute\Source\Countryofmanufacture->getAllOptions()
#4 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\module-catalog\Ui\Component\Listing\Columns.php(61): Magento\Catalog\Ui\Component\ColumnFactory->create(Object(Magento\Catalog\Model\ResourceModel\Eav\Attribute\Interceptor), Object(Magento\Framework\View\Element\UiComponent\Context), Array)
#5 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\View\Layout\Generator\UiComponent.php(148): Magento\Catalog\Ui\Component\Listing\Columns->prepare()
#6 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\View\Layout\Generator\UiComponent.php(145): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Catalog\Ui\Component\Listing\Columns))
#7 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\View\Layout\Generator\UiComponent.php(126): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Listing))
#8 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\View\Layout\Generator\UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'product_listing', Array, Object(Magento\Framework\View\Layout\Interceptor))
#9 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\View\Layout\GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#10 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\View\Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#11 C:\xampp\htdocs\magento_2.1.0_sample\var\generation\Magento\Framework\View\Layout\Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#12 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\View\Layout\Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#13 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\View\Page\Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#14 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\View\Layout\Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#15 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\View\Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#16 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\View\Layout.php(859): Magento\Framework\View\Layout->build()
#17 C:\xampp\htdocs\magento_2.1.0_sample\var\generation\Magento\Framework\View\Layout\Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#18 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\module-backend\Model\View\Result\Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#19 C:\xampp\htdocs\magento_2.1.0_sample\var\generation\Magento\Backend\Model\View\Result\Page\Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Catalog...')
#20 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\module-catalog\Controller\Adminhtml\Product\Index.php(39): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Catalog...')
#21 C:\xampp\htdocs\magento_2.1.0_sample\var\generation\Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Product\Index->execute()
#22 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\App\Action\Action.php(102): Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor->execute()
#23 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\module-backend\App\AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#24 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\Interception\Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#25 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor->___callParent('dispatch', Array)
#26 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor), Array, 'adminAuthentica...')
#27 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\module-backend\App\Action\Plugin\Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\Interception\Chain\Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor), Array, 'adminMassaction...')
#30 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\module-backend\App\Action\Plugin\MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#31 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\Interception\Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 C:\xampp\htdocs\magento_2.1.0_sample\var\generation\Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#33 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\App\FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Product\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#34 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\Interception\Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#35 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#36 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#37 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\Module\Plugin\DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#38 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\Interception\Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#39 C:\xampp\htdocs\magento_2.1.0_sample\var\generation\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#40 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\App\Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#41 C:\xampp\htdocs\magento_2.1.0_sample\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#42 C:\xampp\htdocs\magento_2.1.0_sample\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#43 {main}";s:3:"url";s:119:"/magento_2.1.0_sample/admin/catalog/product/index/key/2543998fbba29d2cb520dcf2a5cc2aa166b396ab949bf08116ae786e8746b080/";s:11:"script_name";s:31:"/magento_2.1.0_sample/index.php";}
```

**Comment by andimov** [comment]
@Phoenix404 
This is a duplicate issue of this https://github.com/magento/magento2/issues/5127. I'm closing this one.
