### ISSUE TITLE
Can't use "configurable" as group name in attribute sets M2.1

### ISSUE THREAD

**Issue by TClilMouse** [magento/magento2#6123]
### Preconditions
1. Magento 2.1
2. PHP 7.0.9, MySql 5.6.27
### Steps to reproduce

Steps to reproduce
1. Attribute Sets - > Default
2. Add New - > Configurable
3. Assigned any attributes
4. go to products -> catalog -> add product
### Expected result
1.  Able to add or edit product
### Actual result

```
a:4:{i:0;s:178:"Warning: Illegal offset type in /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/View/Element/UiComponent/Config/Provider/Component/Definition.php on line 75";i:1;s:8385:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'Illegal offset ...', '/var/www/vhosts...', 75, Array)
#1 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/View/Element/UiComponent/Config/Provider/Component/Definition.php(75): ArrayObject->offsetExists(Array)
#2 /var/www/vhosts/httpdocs/sample2/vendor/magento/module-ui/Model/Manager.php(207): Magento\Framework\View\Element\UiComponent\Config\Provider\Component\Definition->getComponentData(Array)
#3 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/View/Element/UiComponentFactory.php(347): Magento\Ui\Model\Manager->createRawComponentData(Array)
#4 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/View/Element/UiComponentFactory.php(360): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#5 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/View/Element/UiComponentFactory.php(272): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)
#6 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/View/Element/UiComponentFactory.php(164): Magento\Framework\View\Element\UiComponentFactory->mergeMetadata('product_form', Array, false)
#7 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(124): Magento\Framework\View\Element\UiComponentFactory->create('product_form', NULL, Array)
#8 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'product_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
#9 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#10 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#11 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout->generateElements()
#12 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#13 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#14 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#15 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#16 /var/www/vhosts/httpdocs/sample2/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout->getBlock('menu')
#17 /var/www/vhosts/httpdocs/sample2/vendor/magento/module-catalog/Controller/Adminhtml/Product/NewAction.php(71): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Catalog...')
#18 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Product\NewAction->execute()
#19 /var/www/vhosts/httpdocs/sample2/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->___callParent('dispatch', Array)
#22 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor), Array, 'adminAuthentica...')
#23 /var/www/vhosts/httpdocs/sample2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#24 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor), Array, 'adminMassaction...')
#26 /var/www/vhosts/httpdocs/sample2/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#27 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /var/www/vhosts/httpdocs/sample2/var/generation/Magento/Catalog/Controller/Adminhtml/Product/NewAction/Interceptor.php(26): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->___callPlugins('dispatch', Array, Array)
#29 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#32 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#33 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#34 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /var/www/vhosts/httpdocs/sample2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /var/www/vhosts/httpdocs/sample2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#38 /var/www/vhosts/httpdocs/sample2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#39 {main}";s:3:"url";s:129:"/sample2/admin_1vabwd/catalog/product/new/set/4/type/simple/key/12d4a80cb7aa75a0d1a9c5143214bedb11bc960b55075e5575b44a65717f233b/";s:11:"script_name";s:18:"/sample2/index.php";}
```

**Comment by wert2all** [comment]
Can you clean a cache and try to reproduce this issue again?

**Comment by TClilMouse** [comment]
Still the same issue.

**Comment by wert2all** [comment]
try to clean up browser cache.

**Comment by TClilMouse** [comment]
I did. still not working.

**Comment by wert2all** [comment]
I cannot reproduce the issue.
Please provide more preconditions to reproduce this issue: what did you added,  what did you  changed in 2.0 version?

**Comment by TClilMouse** [comment]
I found the main cause, it can't have a group name call configurable
Steps to reproduce

Attribute Sets - > Default
Add New - > Configurable
Assigned any attributes
go to products -> catalog -> add product

**Comment by veloraven** [comment]
@seavenger I was able to reproduce your issue and created internal ticket MAGETWO-57934.

**Comment by magento-engcom-team** [comment]
@TClilMouse, thank you for your report.
We've created internal ticket(s) MAGETWO-57934 to track progress on the issue.

**Comment by vrann** [comment]
#mm17es

**Comment by magento-engcom-team** [comment]
Hi @TClilMouse Thank you for reporting.

Unfortunately, this seems to be correct Magento behavior. You may find more arguments in this PR comment https://github.com/magento/magento2/pull/12014#issuecomment-347546321

Thank you for collaboration
