### ISSUE TITLE
Unable to save a product in the admin that has had images created for it using the REST API

### ISSUE THREAD

**Issue by gurubobnz** [magento/magento2#6279]
On a completely fresh Magento 2.2.0 (HEAD) install with an empty database I created a product and associated an image with it using the REST API. Then I logged into the admin, edited the product and clicked Save. I then get this message:

```
Item (Magento\Framework\DataObject) with the same ID "1" already exists.
```
### Preconditions / Environment / Setup:
- Ubuntu 16.04 LAMP stack: apt-get install -y apache2 mysql-server php-mysql php-mcrypt libapache2-mod-php unzip composer php-gd php-dom php-simplexml php-curl php-intl php-xsl php-mbstring php-zip git)
- Clone the repostory: git clone https://github.com/magento/magento2.git
- Install Magneto: bin/magento setup:install --base-url=http://example.com/ --backend-frontname=admin --db-host=localhost --db-name=magento --db-user=magento --db-password=magento --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=magento123 --language=en_AU --currency=AUD --timezone=Australia/Sydney --use-rewrites=1
- Deploy the static content: bin/magento setup:static-content:deploy
- Reindex: bin/magento indexer:reindex
### Steps to reproduce

\1. Use the REST API to create a product

```
    $api->post('products', ['json' => ['product' => [
        'type_id' => 'simple',
        'visibility' => 2,
        'attribute_set_id' => 4,
        'sku' => 'test',
        'name' => 'Test Product',
        'price' => 123.45,
    ]]]);
```

\2. Use the REST API to associate an image with the product.

```
    $api->post('products/test/media', ['json' => [
        'entry' => [
            'position' => 1,
            'types' => ['image', 'small_image', 'base', 'small', 'thumbnail', 'swatch'],
            'media_type' => 'image',
            'label' => 'test',
            'disabled' => false,
            'file' => './',
            'content' => [
                'base64_encoded_data' => base64_encode(file_get_contents('http://lorempixel.com/output/abstract-q-c-640-480-3.jpg')),
                'type' => 'image/jpeg',
                'name' => 'test.jpg'
            ]
        ]
    ]]);
```

\3. Locate the product in the admin, edit it and click Save.

Note: The API post code above is a simple wrapper around GuzzleHttp that will send the request along with the token provided by authenticating to the endpoint.
### Expected result

The product should save.
### Actual result

The product does not save with the message 

```
Item (Magento\Framework\DataObject) with the same ID "1" already exists.
```

Additionally the following stack trace is emitted into the exception.log:

```
[2016-08-22 21:54:00] main.CRITICAL: Exception: Item (Magento\Framework\DataObject) with the same ID "1" already exists. in /sites/magento/lib/internal/Magento/Framework/Data/Collection.php:406
Stack trace:
#0 /sites/magento/app/code/Magento/Catalog/Model/Product.php(1477): Magento\Framework\Data\Collection->addItem(Object(Magento\Framework\DataObject))
#1 /sites/magento/var/generation/Magento/Catalog/Model/Product/Interceptor.php(869): Magento\Catalog\Model\Product->getMediaGalleryImages()
#2 /sites/magento/app/code/Magento/Catalog/Model/Product/Image/Cache.php(84): Magento\Catalog\Model\Product\Interceptor->getMediaGalleryImages()
#3 /sites/magento/app/code/Magento/Catalog/Model/Product.php(931): Magento\Catalog\Model\Product\Image\Cache->generate(Object(Magento\Catalog\Model\Product\Interceptor))
#4 /sites/magento/var/generation/Magento/Catalog/Model/Product/Interceptor.php(362): Magento\Catalog\Model\Product->afterSave()
#5 /sites/magento/lib/internal/Magento/Framework/EntityManager/Observer/AfterEntitySave.php(34): Magento\Catalog\Model\Product\Interceptor->afterSave()
#6 /sites/magento/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(73): Magento\Framework\EntityManager\Observer\AfterEntitySave->execute(Object(Magento\Framework\Event\Observer))
#7 /sites/magento/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Framework\EntityManager\Observer\AfterEntitySave), Object(Magento\Framework\Event\Observer))
#8 /sites/magento/lib/internal/Magento/Framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#9 /sites/magento/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('magento_catalog...', Array)
#10 /sites/magento/lib/internal/Magento/Framework/EntityManager/EventManager.php(51): Magento\Framework\Event\Manager\Proxy->dispatch('magento_catalog...', Array)
#11 /sites/magento/lib/internal/Magento/Framework/EntityManager/Operation/Update.php(108): Magento\Framework\EntityManager\EventManager->dispatchEntityEvent('Magento\\Catalog...', 'save_after', Array)
#12 /sites/magento/lib/internal/Magento/Framework/EntityManager/EntityManager.php(87): Magento\Framework\EntityManager\Operation\Update->execute(Object(Magento\Catalog\Model\Product\Interceptor), Array)
#13 /sites/magento/app/code/Magento/Catalog/Model/ResourceModel/Product.php(611): Magento\Framework\EntityManager\EntityManager->save(Object(Magento\Catalog\Model\Product\Interceptor))
#14 /sites/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ResourceModel\Product->save(Object(Magento\Catalog\Model\Product\Interceptor))
#15 /sites/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent('save', Array)
#16 /sites/magento/app/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Plugin/Product.php(51): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#17 /sites/magento/app/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Plugin/Product.php(24): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#18 /sites/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#19 /sites/magento/lib/internal/Magento/Framework/App/Cache/FlushCacheByTags.php(60): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#20 /sites/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Framework\App\Cache\FlushCacheByTags->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#21 /sites/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#22 /sites/magento/var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(273): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins('save', Array, Array)
#23 /sites/magento/lib/internal/Magento/Framework/Model/AbstractModel.php(631): Magento\Catalog\Model\ResourceModel\Product\Interceptor->save(Object(Magento\Catalog\Model\Product\Interceptor))
#24 /sites/magento/var/generation/Magento/Catalog/Model/Product/Interceptor.php(2351): Magento\Framework\Model\AbstractModel->save()
#25 /sites/magento/app/code/Magento/Catalog/Controller/Adminhtml/Product/Save.php(111): Magento\Catalog\Model\Product\Interceptor->save()
#26 /sites/magento/var/generation/Magento/Catalog/Controller/Adminhtml/Product/Save/Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Product\Save->execute()
#27 /sites/magento/lib/internal/Magento/Framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->execute()
#28 /sites/magento/app/code/Magento/Backend/App/AbstractAction.php(227): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#29 /sites/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /sites/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callParent('dispatch', Array)
#31 /sites/magento/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(143): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 /sites/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 /sites/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /sites/magento/var/generation/Magento/Catalog/Controller/Adminhtml/Product/Save/Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callPlugins('dispatch', Array, NULL)
#35 /sites/magento/lib/internal/Magento/Framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#36 /sites/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /sites/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#38 /sites/magento/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#39 /sites/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#40 /sites/magento/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#41 /sites/magento/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#42 /sites/magento/lib/internal/Magento/Framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#43 /sites/magento/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#44 /sites/magento/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#45 {main} [] []
```

Happy to provide more information if required.

**Comment by veloraven** [comment]
@gurubobnz thank you for your report.
We have internal ticket MAGETWO-56868 with similar issue which is already fixed.
Could you please update your code, check that commit 8904497 is present and try once more.

**Comment by gurubobnz** [comment]
Thank for your prompt reply and sorry about the duplicate. I have confirmed this has been fixed as per https://github.com/magento/magento2/commit/890449744e228268ff67bf3513f634addcba2e99.

**Comment by veloraven** [comment]
@gurubobnz thank you for update!
