### ISSUE TITLE
Exception logged during "reorder" action:  Call to undefined method getAssociatedProductIds()

### ISSUE THREAD

**Issue by heldchen** [magento/magento2#6566]
our error logs show quite a few exceptions related to the configurable products that were previously associated with grouped products
### Preconditions
1. CE 2.1.1
2. configure php to log errors & exceptions into a file
### Steps to reproduce
1. create a grouped product with sku `G1`
2. add child product sku `S1` to `G1`
3. in the frontend: create an order with product `S1` in it (order id `123`)
4. delete grouped product sku `G1`
5. create configurable product with sku `A1`
6. make configuration and select the existing simple product `S1`
7. in the frontend: reorder the previous order id `123`
8. check the php error log
### Expected result
1. do not see exceptions logged
### Actual result

```
[10-Sep-2016 09:48:29 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Magento\ConfigurableProduct\Model\Product\Type\Configurable\Interceptor::getAssociatedProductIds() in /srv/httpd/prod/src/www/vendor/magento/module-catalog/Model/Product/Type/AbstractType.php:381
Stack trace:
#0 /srv/httpd/prod/src/www/vendor/magento/module-catalog/Model/Product/Type/AbstractType.php(448): Magento\Catalog\Model\Product\Type\AbstractType->_prepareProduct(Object(Magento\Framework\DataObject), Object(Magento\Catalog\Model\Product\Interceptor), 'full')
#1 /srv/httpd/prod/src/www/vendor/magento/module-quote/Model/Quote.php(1574): Magento\Catalog\Model\Product\Type\AbstractType->prepareForCartAdvanced(Object(Magento\Framework\DataObject), Object(Magento\Catalog\Model\Product\Interceptor), 'full')
#2 /srv/httpd/prod/src/www/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Quote\Model\Quote->addProduct(Object(Magento\Catalog\Model\Product\Interceptor), Object(Magento\Framework\DataObject))
#3 /srv/httpd/prod/src/www/var/generation/Magento/Qu in /srv/httpd/prod/src/www/vendor/magento/module-catalog/Model/Product/Type/AbstractType.php on line 381
```

there is no error report in `www/var/report/` related to these execptions and `www/var/log/system.log` has no messages around this timestamp either.

**Comment by Andrii-Deineha** [comment]
@heldchen Hi, is this issue still actual? Describe in more detail the 6 step and attach the screenshots, thank you.

**Comment by magento-engcom-team** [comment]
@heldchen we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
