### ISSUE TITLE
Magento 2.1 EE: is_file() error in the cache management page

### ISSUE THREAD

**Issue by enrico69** [magento/magento2#6647]
### Preconditions
1. **OS** of the server: Debian (Virtualized, with 3GB of memory)
2. **OS of the client**: Windows 7
3. *\* Browser of the client**: Chrome Version 52.0.2743.116 m (64-bit). Also tried with Firefox 44.0.2
4. **MySQL:** Ver 14.14 Distrib 5.6.31
5. **PHP:** PHP 7.0.8-1~dotdeb+8.1 (cli) ( NTS )
### Steps to reproduce
1.  In the back end, create some products attributes. Delete someones.
### Expected result
1. A message stating that you need to clear the cache will appear, with a link to the cache section. Click on the link, you should land on the cache management page.
### Actual result
1. Exception raised. In order to get my back on my feet, I need to clear the cache manually (via the console) and go back to the back end index page.

``` PHP
1 exception(s):
Exception #0 (Exception): Warning: is_file() expects parameter 1 to be a valid path, string given in /var/www/mycustomer/vendor/colinmollenhour/cache-backend-file/File.php on line 512

Exception #0 (Exception): Warning: is_file() expects parameter 1 to be a valid path, string given in /var/www/mycustomer/vendor/colinmollenhour/cache-backend-file/File.php on line 512
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'is_file() expec...', '/var/www/mycust...', 512, Array)
#1 /var/www/mycustomer/vendor/colinmollenhour/cache-backend-file/File.php(512): is_file('/var/www/mycust...')
#2 /var/www/mycustomer/vendor/colinmollenhour/cache-backend-file/File.php(227): Cm_Cache_Backend_File->_cleanNew('matchingTag', Array)
#3 /var/www/mycustomer/vendor/magento/zendframework1/library/Zend/Cache/Core.php(465): Cm_Cache_Backend_File->clean('matchingTag', Array)
#4 /var/www/mycustomer/vendor/magento/framework/Cache/Core.php(98): Zend_Cache_Core->clean('matchingTag', Array)
#5 /var/www/mycustomer/vendor/magento/framework/Cache/Frontend/Adapter/Zend.php(79): Magento\Framework\Cache\Core->clean('matchingTag', Array)
#6 /var/www/mycustomer/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(91): Magento\Framework\Cache\Frontend\Adapter\Zend->clean('matchingTag', Array)
#7 /var/www/mycustomer/vendor/magento/framework/Cache/Frontend/Decorator/TagScope.php(73): Magento\Framework\Cache\Frontend\Decorator\Bare->clean('matchingTag', Array)
#8 /var/www/mycustomer/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(91): Magento\Framework\Cache\Frontend\Decorator\TagScope->clean('matchingTag', Array)
#9 /var/www/mycustomer/vendor/magento/framework/Cache/Frontend/Decorator/Logger.php(47): Magento\Framework\Cache\Frontend\Decorator\Bare->clean('all', Array, 'all')
#10 /var/www/mycustomer/vendor/magento/module-backend/Controller/Adminhtml/Cache/FlushSystem.php(20): Magento\Framework\Cache\Frontend\Decorator\Logger->clean()
#11 /var/www/mycustomer/var/generation/Magento/Backend/Controller/Adminhtml/Cache/FlushSystem/Interceptor.php(24): Magento\Backend\Controller\Adminhtml\Cache\FlushSystem->execute()
#12 /var/www/mycustomer/vendor/magento/framework/App/Action/Action.php(102): Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->execute()
#13 /var/www/mycustomer/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /var/www/mycustomer/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /var/www/mycustomer/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->___callParent('dispatch', Array)
#16 /var/www/mycustomer/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor), Array, 'adminAuthentica...')
#17 /var/www/mycustomer/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /var/www/mycustomer/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /var/www/mycustomer/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor), Array, 'log')
#20 /var/www/mycustomer/vendor/magento/module-logging/App/Action/Plugin/Log.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /var/www/mycustomer/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Logging\App\Action\Plugin\Log->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /var/www/mycustomer/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor), Array, 'adminMassaction...')
#23 /var/www/mycustomer/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#24 /var/www/mycustomer/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /var/www/mycustomer/var/generation/Magento/Backend/Controller/Adminhtml/Cache/FlushSystem/Interceptor.php(39): Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->___callPlugins('dispatch', Array, Array)
#26 /var/www/mycustomer/vendor/magento/framework/App/FrontController.php(55): Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /var/www/mycustomer/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#28 /var/www/mycustomer/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#29 /var/www/mycustomer/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#30 /var/www/mycustomer/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /var/www/mycustomer/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /var/www/mycustomer/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#33 /var/www/mycustomer/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /var/www/mycustomer/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#35 /var/www/mycustomer/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#36 {main}
```

**Comment by crantron** [comment]
getting same error when trying to recompile

**Comment by veloraven** [comment]
@enrico69 thank you for your feedback.
If you experience any problems with Enterprise Edition, please address them to Magento Support.
