### ISSUE TITLE
Unable to install magento2 after taking the latest code from github

### ISSUE THREAD

**Issue by sakashNeev** [magento/magento2#668]
When I check my apache error log. It gives me the following error:-

PHP Fatal error:  Class 'Zend\Mvc\Service\ServiceManagerConfig' not found in /var/www/magento2/setup/index.php on line 32

**Comment by htongaria** [comment]
While installing Magento 2 (Downloaded on 18 Nov, 2015) on my local Wamp Server (Windows 10) 
I am receiving error: Readiness Check: 1 PHP Extension missing --> PHP Extension intl

After cross check my configuration I found that the extention is active.

What could be the problem and how to resolve.

**Comment by mazhalai** [comment]
@htongaria can you please elaborate how did you check your configuration? using phpinfo()? or php -m? Also, please avoid commenting on closed issues, it would be better to create a new issue.

**Comment by zulkhaery** [comment]
Install magento2 on trusty 14.04, nginx 1.8, mysql 5.6, php-fpm 5.6, using compser: http://magento2.local/setup

# 

 Magento
A 404 error occurred
Page not found

The requested URL could not be matched by routing.

No Exception available

#

**Comment by yashodhank** [comment]
Debian 8 (64 bit)
php 7.1 fpm
```
Error: The following error has occurred during the installation of application:
Installation of magento at https://stage.xxxxx.com/ failed. Non-zero exit status returned by script. Output stream: 'PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Parameter validation failed' in /var/www/vhosts/stage.xxxxx.com/httpdocs/setup/src/Magento/Setup/Console/Command/InstallCommand.php:150
Stack trace:
#0 /var/www/vhosts/stage.xxxxx.com/httpdocs/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(236): Magento\Setup\Console\Command\InstallCommand->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/vhosts/stage.xxxxx.com/httpdocs/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/vhosts/stage.xxxx.com/httpdocs/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\InstallCommand), Object(Symfony\Component\Console\Input in /var/www/vhosts/stage.xxxxxx.com/httpdocs/setup/src/Magento/Setup/Console/Command/InstallCommand.php on line 150
'. Error stream: 'PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Parameter validation failed' in /var/www/vhosts/stage.xxxx.com/httpdocs/setup/src/Magento/Setup/Console/Command/InstallCommand.php:150
Stack trace:
#0 /var/www/vhosts/stage.xxxxx.com/httpdocs/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(236): Magento\Setup\Console\Command\InstallCommand->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/vhosts/stage.xxxxxx.com/httpdocs/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/vhosts/stage.xxxxxx.com/httpdocs/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\InstallCommand), Object(Symfony\Component\Console\Input in /var/www/vhosts/stage.xxxxx.com/httpdocs/setup/src/Magento/Setup/Console/Command/InstallCommand.php on line 150
'.
```
