### ISSUE TITLE
M2.1.1 : REST API V1 - PUT /V1/guest-carts/{cartId} gives 401 authorization error

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#6819]
I try to assign a customer to a quote using the REST API. I do this according to the manual:

http://devdocs.magento.com/swagger/index.html#!/quoteGuestCartManagementV1/quoteGuestCartManagementV1AssignCustomerPut

This is a guest-endpoint so it should not require authentication. However, when I try to use it, the API tells me I am not allowed to do so
### Preconditions
1. Magento 2.1.1
### Steps to reproduce
1. Setup a quote as a guest and get it's masked ID (in this example it's `17ce47dfff93f4f07a2deec97dd5c3ab`.
2. Create a customer and get it's ID (in this example it's `10`)
3. Create the API call. For example:

```
curl -X PUT -H "Content-Type: application/json" \
    -d '{"customerId":10}' \
    "http://www.domain.com/rest/V1/guest-carts/17ce47dfff93f4f07a2deec97dd5c3ab/"
```
### Expected result
1. A logic response from the API and the customer saved to the quote (as documented)
### Actual result
1. 401 response with the following message:

```
{
  "message": "Consumer is not authorized to access %resources",
  "parameters": {
    "resources": "self"
  },
  "trace": "
#0 /var/www/public/vendor/magento/module-webapi/Controller/Rest/RequestValidator.php(70): Magento\\Webapi\\Controller\\Rest\\RequestValidator->checkPermissions()\n
#1 /var/www/public/vendor/magento/module-webapi/Controller/Rest/InputParamsResolver.php(80): Magento\\Webapi\\Controller\\Rest\\RequestValidator->validate()\n
#2 /var/www/public/vendor/magento/module-webapi/Controller/Rest.php(299): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver->resolve()\n
#3 /var/www/public/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n
#4 /var/www/public/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
#5 /var/www/public/vendor/magento/framework/App/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n
#6 /var/www/public/vendor/magento/framework/App/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n
#7 /var/www/public/pub/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n
#8 {main}"
}

```

**Comment by kanduvisla** [comment]
Further investigation:

could line 96-101 in `quote/webapi.xml` be the cause of this problem?

```
<route url="/V1/guest-carts/:cartId" method="PUT">
    <service class="Magento\Quote\Api\GuestCartManagementInterface" method="assignCustomer"/>
    <resources>
        <resource ref="self" />
    </resources>
</route>
```

Bug? Feature? Or am I just mis-understanding the guest-API-endpoints?

**Comment by kanduvisla** [comment]
Is there any news on this?

**Comment by RomanKrut** [comment]
@kanduvisla Hi, can you please provide all your requests with following bodies?

**Comment by magento-engcom-team** [comment]
@kanduvisla we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by Peekmo** [comment]
Hello,

I had the same issue and solved it by calling the endpoint with the `customer`'s token, it doesn't work with an `admin` token. Don't know if it's a bug or a feature, but... it works ^^

**Comment by LovelySetia** [comment]
I have same issue. Please guide me to solve it @kanduvisla .
