### ISSUE TITLE
Exceptions occurred during order load and view transactions - Magento 2.1.1

### ISSUE THREAD

**Issue by Dart18** [magento/magento2#6886]
Two Exceptions that occurred during order load and view transactions in the admin panel. Both errors are related to "**Class Magento\Sales\Model\Order\Payment\TransactionFactory does not exist**".
### Preconditions
1. Magento CE Version 2.1.1
2. PHP version 5.6.26-1
3. MySQL version 14.14
4. Ubuntu Server 16.04
### Steps to reproduce

1. Fresh install of Magento 2.1.1
2. Execute Data Migration Tool to import data and settings from a source Magento CE 1.9.0.1
3. After successful migration go to admin panel:
- 3.1 Sales -> Orders correctly displays the list of orders, but when I click on an Order or on the "View" link the system returns the error message: "Exception occurred during order load".
  This is the exception log:

```
Next exception 'ReflectionException' with message 'Class Magento\Sales\Model\Order\Payment\TransactionFactory does not exist' in /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Code/Reader/ClassReader.php:37
Stack trace:
#0 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Sales\\M...')
#1 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Sales\\M...')
#2 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Sales\\M...', Array)
#3 /var/www/magento2/www.testmigration1.it/vendor/magento/module-sales/Model/ResourceModel/Metadata.php(56): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Sales\\M...')
#4 /var/www/magento2/www.testmigration1.it/vendor/magento/module-sales/Model/Order/Payment/Transaction/Repository.php(231): Magento\Sales\Model\ResourceModel\Metadata->getNewInstance()
#5 /var/www/magento2/www.testmigration1.it/vendor/magento/module-sales/Model/ResourceModel/Transaction/Grid/TypeList.php(35): Magento\Sales\Model\Order\Payment\Transaction\Repository->create()
#6 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Argument/Interpreter/Options.php(48): Magento\Sales\Model\ResourceModel\Transaction\Grid\TypeList->toOptionArray()
#7 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Data/Argument/Interpreter/Composite.php(61): Magento\Framework\View\Layout\Argument\Interpreter\Options->evaluate(Array)
#8 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Reader/Block.php(339): Magento\Framework\Data\Argument\Interpreter\Composite->evaluate(Array)
#9 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Reader/Block.php(157): Magento\Framework\View\Layout\Reader\Block->evaluateArguments(Object(Magento\Framework\View\Layout\Element), Array)
#10 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Reader/Block.php(124): Magento\Framework\View\Layout\Reader\Block->scheduleBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Element))
#11 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/ReaderPool.php(105): Magento\Framework\View\Layout\Reader\Block->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element), Object(Magento\Framework\View\Layout\Element))
#12 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Reader/Block.php(134): Magento\Framework\View\Layout\ReaderPool->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element))
#13 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/ReaderPool.php(105): Magento\Framework\View\Layout\Reader\Block->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element), Object(Magento\Framework\View\Layout\Element))
#14 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Reader/Block.php(134): Magento\Framework\View\Layout\ReaderPool->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element))
#15 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/ReaderPool.php(105): Magento\Framework\View\Layout\Reader\Block->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element), Object(Magento\Framework\View\Layout\Element))
#16 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Reader/Block.php(134): Magento\Framework\View\Layout\ReaderPool->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element))
#17 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/ReaderPool.php(105): Magento\Framework\View\Layout\Reader\Block->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element), Object(Magento\Framework\View\Layout\Element))
#18 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Page/Config/Reader/Body.php(70): Magento\Framework\View\Layout\ReaderPool->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element))
#19 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/ReaderPool.php(105): Magento\Framework\View\Page\Config\Reader\Body->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element), Object(Magento\Framework\View\Layout\Element))
#20 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout.php(314): Magento\Framework\View\Layout\ReaderPool->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element))
#21 /var/www/magento2/www.testmigration1.it/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#22 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#23 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#24 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#25 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#26 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#27 /var/www/magento2/www.testmigration1.it/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#28 /var/www/magento2/www.testmigration1.it/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#29 /var/www/magento2/www.testmigration1.it/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Sales::...')
#30 /var/www/magento2/www.testmigration1.it/vendor/magento/module-sales/Controller/Adminhtml/Order.php(140): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Sales::...')
#31 /var/www/magento2/www.testmigration1.it/vendor/magento/module-sales/Controller/Adminhtml/Order/View.php(30): Magento\Sales\Controller\Adminhtml\Order->_initAction()
#32 /var/www/magento2/www.testmigration1.it/var/generation/Magento/Sales/Controller/Adminhtml/Order/View/Interceptor.php(24): Magento\Sales\Controller\Adminhtml\Order\View->execute()
#33 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/App/Action/Action.php(102): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->execute()
#34 /var/www/magento2/www.testmigration1.it/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#35 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#36 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->___callParent('dispatch', Array)
#37 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\View\Interceptor), Array, 'adminAuthentica...')
#38 /var/www/magento2/www.testmigration1.it/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#39 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#40 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Order\View\Interceptor), Array, 'adminMassaction...')
#41 /var/www/magento2/www.testmigration1.it/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#42 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#43 /var/www/magento2/www.testmigration1.it/var/generation/Magento/Sales/Controller/Adminhtml/Order/View/Interceptor.php(39): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->___callPlugins('dispatch', Array, Array)
#44 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/App/FrontController.php(55): Magento\Sales\Controller\Adminhtml\Order\View\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#45 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#46 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#47 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#48 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#49 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#50 /var/www/magento2/www.testmigration1.it/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#51 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#52 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#53 /var/www/magento2/www.testmigration1.it/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#54 {main} [] []
```
- 3.2 Sales->Transactions returns an error page "There has been an error processing your request".
  In var/report the exception log has the following content::

```
a:4:{i:0;s:73:"Class Magento\Sales\Model\Order\Payment\TransactionFactory does not exist";i:1;s:13241:"#0 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Sales\\M...')
#1 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Magento\\Sales\\M...')
#2 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Sales\\M...', Array)
#3 /var/www/magento2/www.testmigration1.it/vendor/magento/module-sales/Model/ResourceModel/Metadata.php(56): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Sales\\M...')
#4 /var/www/magento2/www.testmigration1.it/vendor/magento/module-sales/Model/Order/Payment/Transaction/Repository.php(231): Magento\Sales\Model\ResourceModel\Metadata->getNewInstance()
#5 /var/www/magento2/www.testmigration1.it/vendor/magento/module-sales/Model/ResourceModel/Transaction/Grid/TypeList.php(35): Magento\Sales\Model\Order\Payment\Transaction\Repository->create()
#6 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Argument/Interpreter/Options.php(48): Magento\Sales\Model\ResourceModel\Transaction\Grid\TypeList->toOptionArray()
#7 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Data/Argument/Interpreter/Composite.php(61): Magento\Framework\View\Layout\Argument\Interpreter\Options->evaluate(Array)
#8 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Reader/Block.php(339): Magento\Framework\Data\Argument\Interpreter\Composite->evaluate(Array)
#9 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Reader/Block.php(157): Magento\Framework\View\Layout\Reader\Block->evaluateArguments(Object(Magento\Framework\View\Layout\Element), Array)
#10 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Reader/Block.php(124): Magento\Framework\View\Layout\Reader\Block->scheduleBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Element))
#11 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/ReaderPool.php(105): Magento\Framework\View\Layout\Reader\Block->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element), Object(Magento\Framework\View\Layout\Element))
#12 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Reader/Block.php(134): Magento\Framework\View\Layout\ReaderPool->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element))
#13 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/ReaderPool.php(105): Magento\Framework\View\Layout\Reader\Block->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element), Object(Magento\Framework\View\Layout\Element))
#14 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Reader/Block.php(134): Magento\Framework\View\Layout\ReaderPool->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element))
#15 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/ReaderPool.php(105): Magento\Framework\View\Layout\Reader\Block->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element), Object(Magento\Framework\View\Layout\Element))
#16 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Reader/Block.php(134): Magento\Framework\View\Layout\ReaderPool->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element))
#17 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/ReaderPool.php(105): Magento\Framework\View\Layout\Reader\Block->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element), Object(Magento\Framework\View\Layout\Element))
#18 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Page/Config/Reader/Body.php(70): Magento\Framework\View\Layout\ReaderPool->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element))
#19 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/ReaderPool.php(105): Magento\Framework\View\Page\Config\Reader\Body->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element), Object(Magento\Framework\View\Layout\Element))
#20 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout.php(314): Magento\Framework\View\Layout\ReaderPool->interpret(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Element))
#21 /var/www/magento2/www.testmigration1.it/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#22 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#23 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#24 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#25 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#26 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#27 /var/www/magento2/www.testmigration1.it/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#28 /var/www/magento2/www.testmigration1.it/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#29 /var/www/magento2/www.testmigration1.it/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Sales::...')
#30 /var/www/magento2/www.testmigration1.it/vendor/magento/module-sales/Controller/Adminhtml/Transactions/Index.php(20): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Sales::...')
#31 /var/www/magento2/www.testmigration1.it/var/generation/Magento/Sales/Controller/Adminhtml/Transactions/Index/Interceptor.php(24): Magento\Sales\Controller\Adminhtml\Transactions\Index->execute()
#32 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/App/Action/Action.php(102): Magento\Sales\Controller\Adminhtml\Transactions\Index\Interceptor->execute()
#33 /var/www/magento2/www.testmigration1.it/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#35 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Sales\Controller\Adminhtml\Transactions\Index\Interceptor->___callParent('dispatch', Array)
#36 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Transactions\Index\Interceptor), Array, 'adminAuthentica...')
#37 /var/www/magento2/www.testmigration1.it/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#38 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Transactions\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#39 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Sales\\C...', 'dispatch', Object(Magento\Sales\Controller\Adminhtml\Transactions\Index\Interceptor), Array, 'adminMassaction...')
#40 /var/www/magento2/www.testmigration1.it/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Sales\Controller\Adminhtml\Transactions\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#41 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Transactions\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#42 /var/www/magento2/www.testmigration1.it/var/generation/Magento/Sales/Controller/Adminhtml/Transactions/Index/Interceptor.php(39): Magento\Sales\Controller\Adminhtml\Transactions\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#43 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/App/FrontController.php(55): Magento\Sales\Controller\Adminhtml\Transactions\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#44 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#45 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#46 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#47 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#48 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#49 /var/www/magento2/www.testmigration1.it/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#50 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#51 /var/www/magento2/www.testmigration1.it/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#52 /var/www/magento2/www.testmigration1.it/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#53 {main}";s:3:"url";s:169:"/magento2/www.testmigration1.it/admin_8ozfts/sales/transactions/index/key/ae0b07f0de7cda940e038bc87ecd6f68c21fd4b25c818d1af5fe01301721b4d0/";s:11:"script_name";s:71:"/magento2/www.testmigration1.it/index.php";}

```
### Expected result

1. Possibility to access to orders
2. Possibility to access to transactions
### Actual result

1. Unable to display an Order
2. Unable to display Transactions
   from admin panel.

If it can be useful, I noticed that PayPal settings were not imported in the new Magento 2 installation after migration of settings and that in the orders list the optional column "Payment Method" is empty.

Thanks in advance for any helpful trick or solution.

**Comment by Dart18** [comment]
SOLVED.
The exceptions depend from lack of permissions of var/generation folder. Fixed with chown.
