### ISSUE TITLE
Error after Updating From Magento 1.9.1 to 2.1

### ISSUE THREAD

**Issue by lerhum** [magento/magento2#6945]
### Preconditions
- have my database
- have Magento 1.9.1
### Steps to reproduce
1. type de command `bin/magento setup:upgrade`
2. i get the error `Duplicate entry '4-Images' for key 'EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_NAME'`
3. I rename  attribute_group_name who's make trouble to avoid the duplicate key problem 
   4 type the command `bin/magento setup:upgrade`
4. login to the admin and show categories
### Expected result

the categorres showed normaly
### Actual result

```
1 exception(s):
Exception #0 (Exception): Notice: Undefined offset: 63 in /var/www/html/magento2/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166

Exception #0 (Exception): Notice: Undefined offset: 63 in /var/www/html/magento2/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php on line 166
#0 /var/www/html/magento2/vendor/magento/module-eav/Model/ResourceModel/ReadHandler.php(166): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined offse...', '/var/www/html/m...', 166, Array)
#1 /var/www/html/magento2/vendor/magento/framework/EntityManager/Operation/Read/ReadAttributes.php(59): Magento\Eav\Model\ResourceModel\ReadHandler->execute('Magento\\Catalog...', Array, Array)
#2 /var/www/html/magento2/vendor/magento/framework/EntityManager/Operation/Read.php(116): Magento\Framework\EntityManager\Operation\Read\ReadAttributes->execute(Object(Magento\Catalog\Model\Category\Interceptor), Array)
#3 /var/www/html/magento2/vendor/magento/framework/EntityManager/EntityManager.php(61): Magento\Framework\EntityManager\Operation\Read->execute(Object(Magento\Catalog\Model\Category\Interceptor), 2, Array)
#4 /var/www/html/magento2/vendor/magento/module-catalog/Model/ResourceModel/Category.php(996): Magento\Framework\EntityManager\EntityManager->load(Object(Magento\Catalog\Model\Category\Interceptor), 2)
#5 /var/www/html/magento2/var/generation/Magento/Catalog/Model/ResourceModel/Category/Interceptor.php(336): Magento\Catalog\Model\ResourceModel\Category->load(Object(Magento\Catalog\Model\Category\Interceptor), 2, NULL)
#6 /var/www/html/magento2/vendor/magento/framework/Model/AbstractModel.php(531): Magento\Catalog\Model\ResourceModel\Category\Interceptor->load(Object(Magento\Catalog\Model\Category\Interceptor), 2, NULL)
#7 /var/www/html/magento2/var/generation/Magento/Catalog/Model/Category/Interceptor.php(1480): Magento\Framework\Model\AbstractModel->load(2, NULL)
#8 /var/www/html/magento2/vendor/magento/module-catalog/Controller/Adminhtml/Category.php(40): Magento\Catalog\Model\Category\Interceptor->load(2)
#9 /var/www/html/magento2/vendor/magento/module-catalog/Controller/Adminhtml/Category/Edit.php(75): Magento\Catalog\Controller\Adminhtml\Category->_initCategory(true)
#10 /var/www/html/magento2/var/generation/Magento/Catalog/Controller/Adminhtml/Category/Edit/Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Category\Edit->execute()
#11 /var/www/html/magento2/vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->execute()
#12 /var/www/html/magento2/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->___callParent('dispatch', Array)
#15 /var/www/html/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Array, 'adminAuthentica...')
#16 /var/www/html/magento2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /var/www/html/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Array, 'adminMassaction...')
#19 /var/www/html/magento2/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/magento2/var/generation/Magento/Catalog/Controller/Adminhtml/Category/Edit/Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#22 /var/www/html/magento2/vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Category\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#25 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#26 /var/www/html/magento2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /var/www/html/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#29 /var/www/html/magento2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\App\Http->launch()
#31 /var/www/html/magento2/var/generation/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#32 /var/www/html/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#33 /var/www/html/magento2/index.php(45): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#34 {main}
```

ReadHandler.php

```
161          $unionSelect = new \Magento\Framework\DB\Sql\UnionExpression(
162                 $selects,
163                \Magento\Framework\DB\Select::SQL_UNION_ALL
164            );
165           foreach ($connection->fetchAll($unionSelect) as $attributeValue) {
166               $entityData[$attributesMap[$attributeValue['attribute_id']]]=$attributeValue['value'];
167           }
168       }
169       return $entityData;
```

**Comment by shanevbg** [comment]
I had this same problem, I believe I had to rename 4-images entry to upgrade (it was a a while ago though, so I don't recall the exact steps)

**Comment by victor-v-rad** [comment]
I assume data inconsistency in DB. Some records in tables with foreign keys that points to non-existing records of other tables.

**Comment by magento-engcom-team** [comment]
Hi @lerhum 
For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool

Thank you.
