### ISSUE TITLE
Fatal error: Class undefined: Zend\\Stdlib\\ErrorHandler

### ISSUE THREAD

**Issue by craigcarnell** [magento/magento2#697]
0.1.0-alpha100, Viewing home page after command line install

```
[Mon Oct 20 09:34:38 2014] [hphp] [13767:7fdc40bff700:1:000001] [] \nFatal error: Class undefined: Zend\\Stdlib\\ErrorHandler in /var/www/vhosts/magento2-capistrano/releases/20141020090530/lib/internal/Zend/Validator/Hostname.php on line 550
```

hhvm --version
```
HipHop VM 3.4.0-dev~nightly.2014.10.19 (rel)
Compiler: heads/master-0-g65045d210089800965c6bfedf48f6a43770326c8
Repo schema: 5b442602629d089fc6082c6d4640be6f44644223
Extension API: 20140829
```

nginx -V
```
nginx version: nginx/1.6.2
built by gcc 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-log-path=/var/log/nginx/access.log --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --with-pcre-jit --with-debug --with-http_addition_module --with-http_dav_module --with-http_gzip_static_module --with-http_realip_module --with-http_stub_status_module --with-http_ssl_module --with-http_sub_module --with-ipv6 --with-mail --with-mail_ssl_module --with-pcre=/usr/local/src/pcre-8.32 --with-http_spdy_module
```

Command line install:
```
root@web:/var/www/vhosts/magento2-capistrano/current# php dev/shell/install.php -- --license_agreement_accepted yes --locale en_GB --timezone "Europe/London" --default_currency GBP --db_host 127.0.0.1 --db_name xxx_prod --db_user root --url "http://www.xxx.co.uk/" --use_rewrites yes --use_secure_admin no --admin_lastname Admin --admin_firstname Admin --admin_email "craig@xxx.co.uk" --admin_username admin --admin_password password --use_secure no --secure_base_url "http://www.xxx.co.uk/" --cleanup_database --skip_url_validation yes
exception 'Exception' with message 'Recoverable Error: Object of class Magento\Framework\Message\Error could not be converted to string in /var/www/vhosts/magento2-capistrano/releases/20141020090530/app/code/Magento/Install/App/Console.php on line 123' in /var/www/vhosts/magento2-capistrano/releases/20141020090530/lib/internal/Magento/Framework/App/ErrorHandler.php:77
Stack trace:
#0 (): Magento\Framework\App\ErrorHandler->handler()
#1 /var/www/vhosts/magento2-capistrano/releases/20141020090530/app/code/Magento/Install/App/Console.php(123): implode()
#2 /var/www/vhosts/magento2-capistrano/releases/20141020090530/app/code/Magento/Install/App/Console.php(159): Magento\Install\App\Console->_handleInstall()
#3 /var/www/vhosts/magento2-capistrano/releases/20141020090530/lib/internal/Magento/Framework/App/Bootstrap.php(203): Magento\Install\App\Console->launch()
#4 /var/www/vhosts/magento2-capistrano/releases/20141020090530/dev/shell/install.php(107): Magento\Framework\App\Bootstrap->run()
```

**Comment by maksek** [comment]
@craigcarnell seems like it is specific environmental issue. On version you tried we didn't announce support for HHVM. For now i am going to close the ticket.
