### ISSUE TITLE
Unable to run integration tests in docker environment 

### ISSUE THREAD

**Issue by brideo** [magento/magento2#7044]
### Preconditions
1. Magento EE v2.0.7 Installed
2. Docker environment setup with a container per service
3. Tests have been run already
### Steps to reproduce
1. Create an integration test with the `magentoDbIsolation` enabled
2. Login to the server
3. Run test with `../../../vendor/bin/phpunit ../../../app/code/Path/To/SomeTest.php`
### Expected result
1. The test should be run
### Actual result

1. Any Error is thrown

```
exception 'Exception' with message 'sh: mysql: command not found' in /var/www/vendor/magento/framework/Shell.php:61
Stack trace:
#0 /var/www/dev/tests/integration/framework/Magento/TestFramework/Db/Mysql.php(107): Magento\Framework\Shell->execute('mysql --default...', Array)
#1 /var/www/dev/tests/integration/framework/Magento/TestFramework/Application.php(457): Magento\TestFramework\Db\Mysql->restoreFromDbDump()
#2 /var/www/dev/tests/integration/framework/bootstrap.php(68): Magento\TestFramework\Application->install()
#3 /var/www/vendor/phpunit/phpunit/src/Util/Fileloader.php(93): include_once('/var/www/dev/te...')
#4 /var/www/vendor/phpunit/phpunit/src/Util/Fileloader.php(77): PHPUnit_Util_Fileloader::load('/var/www/dev/te...')
#5 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(806): PHPUnit_Util_Fileloader::checkAndLoad('/var/www/dev/te...')
#6 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(636): PHPUnit_TextUI_Command->handleBootstrap('/var/www/dev/te...')
#7 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit_TextUI_Command->handleArguments(Array)
#8 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(132): PHPUnit_TextUI_Command->run(Array, true)
#9 /var/www/vendor/phpunit/phpunit/phpunit(55): PHPUnit_TextUI_Command::main()
#10 {main}

Next exception 'Magento\Framework\Exception\LocalizedException' with message 'Command returned non-zero exit code:
`mysql --defaults-extra-file='/var/www/dev/tests/integration/tmp/sandbox-0-9319a4b1ae439813a3d1b2b4969a959e/defaults_extra.cnf' --host='db' 'magento2_test' < '/var/www/dev/tests/integration/tmp/sandbox-0-9319a4b1ae439813a3d1b2b4969a959e/setup_dump_magento2_test.sql' 2>&1`' in /var/www/vendor/magento/framework/Shell.php:62
Stack trace:
#0 /var/www/dev/tests/integration/framework/Magento/TestFramework/Db/Mysql.php(107): Magento\Framework\Shell->execute('mysql --default...', Array)
#1 /var/www/dev/tests/integration/framework/Magento/TestFramework/Application.php(457): Magento\TestFramework\Db\Mysql->restoreFromDbDump()
#2 /var/www/dev/tests/integration/framework/bootstrap.php(68): Magento\TestFramework\Application->install()
#3 /var/www/vendor/phpunit/phpunit/src/Util/Fileloader.php(93): include_once('/var/www/dev/te...')
#4 /var/www/vendor/phpunit/phpunit/src/Util/Fileloader.php(77): PHPUnit_Util_Fileloader::load('/var/www/dev/te...')
#5 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(806): PHPUnit_Util_Fileloader::checkAndLoad('/var/www/dev/te...')
#6 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(636): PHPUnit_TextUI_Command->handleBootstrap('/var/www/dev/te...')
#7 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit_TextUI_Command->handleArguments(Array)
#8 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(132): PHPUnit_TextUI_Command->run(Array, true)
#9 /var/www/vendor/phpunit/phpunit/phpunit(55): PHPUnit_TextUI_Command::main()
#10 {main}
```

This is happening because you are using exec directly and the PHP container does not have mysql installed on it which is common in docker environments.

**Comment by adifucan** [comment]
Hi @brideo!
It seems you need to install mysql-client to your php container to run integration tests. 
We faced the same issue with running integration tests on our Magento Developer Toolkit on Docker. So we added mysql-client to our web container: https://github.com/magento-tango/magento2devbox-web/blob/master/Dockerfile#L18

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by andkirby** [comment]
Hi team,

Could you reopen this issue? I got errors:
```
0 ✓ magento /var/www/html/dev/tests/integration
$ phpunit
[...]
Warning: exec(): Unable to fork [mysql --defaults-file='/var/www/html/dev/tests/integration/tmp/sandbox-0-54d83a72ee91b89607f8fa1881e21bd4/defaults_extra.cnf' --host='dbhost' --port='3306' 'launch2_integration_tests' < '/var/www/html/dev/tests/integration/tmp/sandbox-0-54d83a72ee91b89607f8fa1881e21bd4/setup_dump_launch2_integration_tests.sql' 2>&1] in /var/www/html/vendor/magento/framework/Shell.php:57.
PHP Fatal error:  Uncaught PHPUnit\Framework\Exception: Warning: exec(): Unable to fork [tasklist.exe /fi 'PID eq 1315' /fo CSV /nh 2>&1] in /var/www/html/vendor/magento/framework/Shell.php:57.

/var/www/html/dev/tests/integration/framework/bootstrap.php:130
/var/www/html/vendor/magento/framework/Shell.php:57
/var/www/html/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php:89
/var/www/html/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php:52
/var/www/html/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php:127
/var/www/html/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php:59
/var/www/html/dev/tests/integration/framework/Magento/TestFramework/Bootstrap/Memory.php:50

  thrown in /var/www/html/dev/tests/integration/framework/bootstrap.php on line 130
```
In the same time I was able to run the same mysql command:
```
2 ✗ magento /var/www/html/dev/tests/integration
$ mysql --defaults-file='/var/www/html/dev/tests/integration/tmp/sandbox-0-54d83a72ee91b89607f8fa1881e21bd4/defaults_extra.cnf' --host='dbhost' --port='3306' 'magento_integration_tests' < '/var/www/html/dev/tests/integration/tmp/sandbox-0-54d83a72ee91b89607f8fa1881e21bd4/setup_dump_magento_integration_tests.sql'

0 ✓ magento /var/www/html/dev/tests/integration
$
```

P.S.
And another question?.. Why `tasklist.exe` here in Linux system?
```
tasklist.exe /fi 'PID eq 1315' /fo CSV /nh 2>&1
```

**Comment by snez** [comment]
In an Ubuntu docker container, I'm getting:

```
Fatal error: Uncaught Exception: sh: 1: tasklist.exe: not found in /var/www/magento2/lib/internal/Magento/Framework/Shell.php:65
Stack trace:
#0 /var/www/magento2/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php(92): Magento\Framework\Shell->execute('tasklist.exe /f...', Array)
#1 /var/www/magento2/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php(58): Magento\TestFramework\Helper\Memory->_getWinProcessMemoryUsage(476)
#2 /var/www/magento2/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php(127): Magento\TestFramework\Helper\Memory->getRealMemoryUsage()
#3 /var/www/magento2/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php(59): Magento\TestFramework\MemoryLimit->_getUsage()
#4 /var/www/magento2/dev/tests/integration/framework/Magento/TestFramework/Bootstrap/Memory.php(50): Magento\TestFramework\MemoryLimit->printStats()
#5 [internal function]: Magento\TestFramework\Bootstrap\Memory->displayStats()
#6 {main}
```

**Comment by KernelFolla** [comment]
maybe it's too late but I've found a solution for who comes here, in docker container (or in your linux environment) ps command is missing so magento tries with tasklist.exe, to solve the issue you need to install ps (usually with apt install procps )
