### ISSUE TITLE
Upgrade 2.0.7 -> 2.1.2 problem Undefined index: PK_CMS_PAGE + installation 2.1.2 PK_CMS_PAGE error

### ISSUE THREAD

**Issue by pepepepowski** [magento/magento2#7061]
### Preconditions

1. 2.0.7 -> 2.1.2 (upgrade) 
2. mysql 5.6, php 7.0.12, plesk 12.5 
### Steps to reproduce

1. composer require magento/product-community-edition 2.1.2 --no-update
2. composer update
3. php bin/magento setup:upgrade
### Expected result

1. Upgrade done
### Actual result

1.  In ssh ->

```
  (....)
  Module 'Magento_Customer':
  Module 'Magento_BundleImportExport':
  Module 'Magento_CacheInvalidate':
  Module 'Magento_Indexer':
  Module 'Magento_Cms':
  Upgrading data..
  [Exception]
  Notice: Undefined index: PK_CMS_PAGE in /var/www/vhosts/pepe/httpdocs
  /vendor/magento/framework/EntityManager/EntityMetadata.php on line 96
```

when i open url in browser: 
`There has been an error processing your request Exception printing is disabled by default for security reasons.`
1. In var/raport ->

`a:4:{i:0;s:1168:"Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.  [.....]`

index status all ok, any ideas what should i do now?

---

**EDIT:**
With web setup the issue is the same (Readiness Check OK) log:
System Upgrade Status:
Update application is not running

```
(.....)
Module 'Magento_Theme':
Upgrading data.. 
Module 'Magento_Customer':
Upgrading data.. 
Module 'Magento_BundleImportExport':
Module 'Magento_CacheInvalidate':
Module 'Magento_Indexer':
Module 'Magento_Cms':
Upgrading data.. 
[2016-10-18 12:45:09 UTC] An error occurred while executing job "setup:upgrade {"command":"setup:upgrade"}": Could not complete setup:upgrade {"command":"setup:upgrade"} successfully: Notice: Undefined index: PK_CMS_PAGE in /var/www/vhosts/pepe/httpdocs/vendor/magento/framework/EntityManager/EntityMetadata.php on line 96
[2016-10-18 12:45:09 UTC] Job "setup:static:regenerate []" has started
```

**Comment by pepepepowski** [comment]
Ok so.... im trying to install fresh copy of magento 2.1.2 from magento website.

_Offcourse i had to change: "composer/composer": "@alpha" to: "composer/composer": "1.1.2 as 1.0.0-beta1"_ ...

Readiness Check OK etc, and then in install there is error:

```
[ERROR] Exception: Notice: Undefined index: PK_CMS_PAGE in /var/www/vhosts/pepe/httpdocs/vendor/magento/framework/EntityManager/EntityMetadata.php on line 96 in /var/www/vhosts/pepe/httpdocs/vendor/magento/framework/App/ErrorHandler.php:61
Stack trace:
#0 /var/www/vhosts/pepe/httpdocs/vendor/magento/framework/EntityManager/EntityMetadata.php(96): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/var/www/vhosts...', 96, Array)
#1 /var/www/vhosts/pepe/httpdocs/vendor/magento/framework/EntityManager/Db/CreateRow.php(77): Magento\Framework\EntityManager\EntityMetadata->getLinkField()
#2 /var/www/vhosts/pepe/httpdocs/vendor/magento/framework/EntityManager/Operation/Create/CreateMain.php(57): Magento\Framework\EntityManager\Db\CreateRow->execute('Magento\\Cms\\Api...', Array)
#3 /var/www/vhosts/pepe/httpdocs/vendor/magento/framework/EntityManager/Operation/Create.php(105): Magento\Framework\EntityManager\Operation\Create\CreateMain->execute(Object(Magento\Cms\Model\Page), Array)
#4 /var/www/vhosts/pepe/httpdocs/vendor/magento/framework/EntityManager/EntityManager.php(87): Magento\Framework\EntityManager\Operation\Create->execute(Object(Magento\Cms\Model\Page), Array)
#5 /var/www/vhosts/pepe/httpdocs/vendor/magento/module-cms/Model/ResourceModel/Page.php(397): Magento\Framework\EntityManager\EntityManager->save(Object(Magento\Cms\Model\Page))
#6 /var/www/vhosts/pepe/httpdocs/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Cms\Model\ResourceModel\Page->save(Object(Magento\Cms\Model\Page))
#7 /var/www/vhosts/pepe/httpdocs/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Cms\Model\ResourceModel\Page\Interceptor->___callParent('save', Array)
#8 /var/www/vhosts/pepe/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Mod...', 'save', Object(Magento\Cms\Model\ResourceModel\Page\Interceptor), Array, 'clean_cache')
#9 /var/www/vhosts/pepe/httpdocs/vendor/magento/framework/App/Cache/FlushCacheByTags.php(60): Magento\Cms\Model\ResourceModel\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Cms\Model\Page))
#10 /var/www/vhosts/pepe/httpdocs/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\App\Cache\FlushCacheByTags->aroundSave(Object(Magento\Cms\Model\ResourceModel\Page\Interceptor), Object(Closure), Object(Magento\Cms\Model\Page))
#11 /var/www/vhosts/pepe/httpdocs/var/generation/Magento/Cms/Model/ResourceModel/Page/Interceptor.php(143): Magento\Cms\Model\ResourceModel\Page\Interceptor->___callPlugins('save', Array, Array)
#12 /var/www/vhosts/pepe/httpdocs/vendor/magento/framework/Model/AbstractModel.php(631): Magento\Cms\Model\ResourceModel\Page\Interceptor->save(Object(Magento\Cms\Model\Page))
#13 /var/www/vhosts/pepe/httpdocs/vendor/magento/module-cms/Setup/InstallData.php(102): Magento\Framework\Model\AbstractModel->save()
#14 /var/www/vhosts/pepe/httpdocs/setup/src/Magento/Setup/Model/Installer.php(844): Magento\Cms\Setup\InstallData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext))
#15 /var/www/vhosts/pepe/httpdocs/setup/src/Magento/Setup/Model/Installer.php(796): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data')
#16 [internal function]: Magento\Setup\Model\Installer->installDataFixtures()
#17 /var/www/vhosts/pepe/httpdocs/setup/src/Magento/Setup/Model/Installer.php(344): call_user_func_array(Array, Array)
#18 /var/www/vhosts/pepe/httpdocs/setup/src/Magento/Setup/Controller/Install.php(109): Magento\Setup\Model\Installer->install(Array)
#19 /var/www/vhosts/pepe/httpdocs/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction()
#20 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#21 /var/www/vhosts/pepe/httpdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#22 /var/www/vhosts/pepe/httpdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#23 /var/www/vhosts/pepe/httpdocs/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#24 /var/www/vhosts/pepe/httpdocs/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#25 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#26 /var/www/vhosts/pepe/httpdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#27 /var/www/vhosts/pepe/httpdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#28 /var/www/vhosts/pepe/httpdocs/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#29 /var/www/vhosts/pepe/httpdocs/setup/index.php(31): Zend\Mvc\Application->run()
#30 {main}

```

Agin ... PK_CMS_PAGE ... in 2.0.7 there is no such as thing in all files.   Any one can help ?

**Comment by BaDos** [comment]
Hi @pepepepowski 

Thank you for you feedback.
Cannot reproduce this issue.

Are you using Sample Data?
Did you try to upgrade fresh installation 2.0.7 to 2.1.2?

**Comment by pepepepowski** [comment]
Hi,  @BaDos 
few days ago, i decided to "manual copy" data (html pages, blocks etc) from old version  to new fresh instalation - 2.1.1
It looks like there is some difference between cms_page tables/records  in 2.0.7/2.1.1 and magento have problems with update.

Instalation & Upgrade from 2.1.1 to 2.1.2 worked.

**Comment by BaDos** [comment]
@pepepepowski  What about fresh installation 2.0.7 and then upgrading to 2.1.2?
Do you have the same issue?

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
