### ISSUE TITLE
When the quote expires, an exception is thrown on Checkout refresh

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#7235]
- M2 2.1.1 
- PHP 7.0.12
### Steps to reproduce
1. Add something in Cart. Wait for it to expire. Or maybe remove the session cookie (haven't tried it, though).
2. Refresh checkout. I was on `/checkout/#payment`.
### Expected result
1. Redirected back to Cart page.
### Actual result

Got this exception:

```
1 exception(s):
Exception #0 (LogicException): Wrong argument type provided.

Exception #0 (LogicException): Wrong argument type provided.
#0 /vagrant/vendor/magento/module-payment/Observer/AbstractDataAssignObserver.php(57): Magento\Payment\Observer\AbstractDataAssignObserver->readArgument(Object(Magento\Framework\Event\Observer), 'data', 'Magento\\Framewo...')
#1 /vagrant/vendor/magento/module-braintree/Observer/DataAssignObserver.php(34): Magento\Payment\Observer\AbstractDataAssignObserver->readDataArgument(Object(Magento\Framework\Event\Observer))
#2 /vagrant/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Magento\Braintree\Observer\DataAssignObserver->execute(Object(Magento\Framework\Event\Observer))
#3 /vagrant/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Braintree\Observer\DataAssignObserver), Object(Magento\Framework\Event\Observer))
#4 /vagrant/vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#5 /vagrant/var/generation/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch('payment_method_...', Array)
#6 /vagrant/vendor/magento/module-payment/Model/Method/AbstractMethod.php(815): Magento\Staging\Model\Event\Manager\Proxy->dispatch('payment_method_...', Array)
#7 /vagrant/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Payment\Model\Method\AbstractMethod->isAvailable(NULL)
#8 /vagrant/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\OfflinePayments\Model\Checkmo\Interceptor->___callParent('isAvailable', Array)
#9 /vagrant/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Offline...', 'isAvailable', Object(Magento\OfflinePayments\Model\Checkmo\Interceptor), Array, 'paymentMethodIs...')
#10 /vagrant/vendor/magento/module-payment-staging/Plugin/Model/Method/PaymentMethodIsAvailable.php(48): Magento\OfflinePayments\Model\Checkmo\Interceptor->Magento\Framework\Interception\{closure}(NULL)
#11 /vagrant/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PaymentStaging\Plugin\Model\Method\PaymentMethodIsAvailable->aroundIsAvailable(Object(Magento\OfflinePayments\Model\Checkmo\Interceptor), Object(Closure))
#12 /vagrant/var/generation/Magento/OfflinePayments/Model/Checkmo/Interceptor.php(546): Magento\OfflinePayments\Model\Checkmo\Interceptor->___callPlugins('isAvailable', Array, Array)
#13 /vagrant/vendor/magento/module-offline-payments/Model/CheckmoConfigProvider.php(46): Magento\OfflinePayments\Model\Checkmo\Interceptor->isAvailable()
#14 /vagrant/vendor/magento/module-checkout/Model/CompositeConfigProvider.php(32): Magento\OfflinePayments\Model\CheckmoConfigProvider->getConfig()
#15 /vagrant/vendor/magento/module-checkout/Block/Onepage.php(91): Magento\Checkout\Model\CompositeConfigProvider->getConfig()
#16 /vagrant/vendor/magento/module-checkout/view/frontend/templates/onepage.phtml(26): Magento\Checkout\Block\Onepage->getCheckoutConfig()
#17 /vagrant/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/vagrant/vendor...')
#18 /vagrant/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Onepage), '/vagrant/vendor...', Array)
#19 /vagrant/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/vagrant/vendor...')
#20 /vagrant/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#21 /vagrant/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#22 /vagrant/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('checkout.root')
#23 /vagrant/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('checkout.root')
#24 /vagrant/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('checkout.root')
#25 /vagrant/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('checkout.root', true)
#26 /vagrant/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('checkout.root')
#27 /vagrant/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#28 /vagrant/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#29 /vagrant/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#30 /vagrant/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#31 /vagrant/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#32 /vagrant/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main')
#33 /vagrant/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#34 /vagrant/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#35 /vagrant/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', true)
#36 /vagrant/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main')
#37 /vagrant/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('columns')
#38 /vagrant/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#39 /vagrant/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#40 /vagrant/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', true)
#41 /vagrant/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('columns')
#42 /vagrant/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.content')
#43 /vagrant/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#44 /vagrant/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#45 /vagrant/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
#46 /vagrant/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
#47 /vagrant/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#48 /vagrant/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#49 /vagrant/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#50 /vagrant/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#51 /vagrant/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#52 /vagrant/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#53 /vagrant/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#54 /vagrant/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#55 /vagrant/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#56 /vagrant/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#57 /vagrant/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Layout->getOutput()
#58 /vagrant/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#59 /vagrant/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#60 /vagrant/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#61 /vagrant/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#62 /vagrant/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#63 /vagrant/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#64 /vagrant/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#65 /vagrant/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#66 /vagrant/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#67 /vagrant/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#68 /vagrant/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#69 /vagrant/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#70 /vagrant/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#71 /vagrant/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#72 /vagrant/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#73 {main}
```

So it ends up [here](https://github.com/magento/magento2/blob/76315a6caa4cabfd8da5ec3ea646440300ffa019/app/code/Magento/Payment/Observer/AbstractDataAssignObserver.php#L75), because `$argument` is `null` and `$type` is `\Magento\Framework\DataObject`.

**Comment by adragus-inviqa** [comment]
False alarm. I'm an idiot on fridays.
