### ISSUE TITLE
Getting "The resource isn't set". via Interceptor after Upgrading to 2.1.2

### ISSUE THREAD

**Issue by kirashet666** [magento/magento2#7275]
Hi there,

we recently upgraded Magento from 2.0 to 2.1.2.

In our project we created a new REST Service for getting additional information besides what `"CategoryTreeInterface"` delivers.

In Magento 2.0 we had no issues. After upgrading to 2.1.2 we get following error:

```
<response>
<message>The resource isn't set.</message>
<trace>
#0 /var/www/html/app/code/Magento/Catalog/Model/Category.php(936): Magento\Framework\Model\AbstractModel->_getResource() #1 /var/www/html/lib/internal/Magento/Framework/Reflection/DataObjectProcessor.php(86): Magento\Catalog\Model\Category->getProductCount() #2 /var/www/html/lib/internal/Magento/Framework/Reflection/DataObjectProcessor.php(113): Magento\Framework\Reflection\DataObjectProcessor->buildOutputDataArray(Object(Ruck\Catalog\Model\CategoryTreeExtendedImpl\Interceptor), '\\Ruck\\Catalog\\A...') #3 /var/www/html/lib/internal/Magento/Framework/Reflection/DataObjectProcessor.php(113): Magento\Framework\Reflection\DataObjectProcessor->buildOutputDataArray(Object(Ruck\Catalog\Model\CategoryTreeExtendedImpl\Interceptor), '\\Ruck\\Catalog\\A...') #4 /var/www/html/lib/internal/Magento/Framework/Reflection/DataObjectProcessor.php(113): Magento\Framework\Reflection\DataObjectProcessor->buildOutputDataArray(Object(Ruck\Catalog\Model\CategoryTreeExtendedImpl\Interceptor), '\\Ruck\\Catalog\\A...') #5 /var/www/html/lib/internal/Magento/Framework/Reflection/DataObjectProcessor.php(113): Magento\Framework\Reflection\DataObjectProcessor->buildOutputDataArray(Object(Ruck\Catalog\Model\CategoryTreeExtendedImpl\Interceptor), '\\Ruck\\Catalog\\A...') #6 /var/www/html/lib/internal/Magento/Framework/Webapi/ServiceOutputProcessor.php(107): Magento\Framework\Reflection\DataObjectProcessor->buildOutputDataArray(Object(Ruck\Catalog\Model\CategoryTreeExtendedImpl\Interceptor), '\\Ruck\\Catalog\\A...') #7 /var/www/html/lib/internal/Magento/Framework/Webapi/ServiceOutputProcessor.php(59): Magento\Framework\Webapi\ServiceOutputProcessor->convertValue(Object(Ruck\Catalog\Model\CategoryTreeExtendedImpl\Interceptor), '\\Ruck\\Catalog\\A...') #8 /var/www/html/app/code/Magento/Webapi/Controller/Rest.php(308): Magento\Framework\Webapi\ServiceOutputProcessor->process(Object(Ruck\Catalog\Model\CategoryTreeExtendedImpl\Interceptor), 'Ruck\\Catalog\\Ap...', 'getTreeByStoreC...') #9 /var/www/html/app/code/Magento/Webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest() #10 /var/www/html/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http)) #11 /var/www/html/lib/internal/Magento/Framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #12 /var/www/html/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch() #13 /var/www/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http)) #14 {main}
</trace>
</response>
```

If I overwrite the "getProductCount" method in the generated Interceptor.php, it works, but that can't be the solution.

So, why is the resource in` Magento\Catalog\Model\Category#getProductCount `not set?
What changed in that context between 2.0 and 2.1.2?

### Preconditions

1. Magento 2.1.2
2. PHP 7
3. Apache 2

Thanks,
Ali

**Comment by kirashet666** [comment]
Solved. The problem was that the implementation class which extended `CategoryTreeInterface` had no valid constructor.
