### ISSUE TITLE
Error after deleting website: Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity.

### ISSUE THREAD

**Issue by GuidoHub** [magento/magento2#7366]
### Preconditions
1.  Magento 2.1.2
2. PHP 7.0.x
3. MySQL 5.6
4, Running in developer mode

### Steps to reproduce

1. Create multiple websites that use the same store and different store view
2. Delete one of the websites
3. 

### Expected result

1. I would expect that the website would be deleted and I would return to the Stores page.

### Actual result

1. [Screenshot, logs]
Getting the following error. I have also tested it on my production server. It gave the same error. Also tried reindexing, cache:clean, cache:flush but nothing changes. I can still see the website with id=10 in table *_store. But in others it's gone. Looks like the delete query is not executed right. 

1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity.

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity.
#0 C:\xampp7\htdocs\vendor\magento\module-store\Model\Store.php(561): Magento\Store\Model\WebsiteRepository->getById('10')
#1 C:\xampp7\htdocs\var\generation\Magento\Store\Model\Store\Interceptor.php(115): Magento\Store\Model\Store->getWebsite()
#2 C:\xampp7\htdocs\vendor\magento\module-store\Model\Config\Reader\Store.php(71): Magento\Store\Model\Store\Interceptor->getWebsite()

**Comment by sevos1984** [comment]
How can multiple websites use same store? Could you please provide full configuration of your stores?

**Comment by GuidoHub** [comment]
See screenshot below. I have added 4 websites that all use the same store.

![magento](https://cloud.githubusercontent.com/assets/22280971/20273737/b8672464-aa92-11e6-97b9-278360dbf2c6.jpg)

**Comment by sevos1984** [comment]
Stores just have same name but ids would be different. Need more information to reproduce. How many root categories do you use?

**Comment by GuidoHub** [comment]
I use three different root categories. Every Store has his own root categorie. The websites, stores and categories are created in version 2.1.1

**Comment by crantron** [comment]
Just came across this as well. 2.1.2

**Comment by GuidoHub** [comment]
In 2.1.3 there is no error after deleting but in table "_store" and "_store_group" I have still records pointing to the website and view I have deleted. I noticed weird behavior when I added a category because the rewrite module added records with an empty store. Is it save to just delete the records in the two tables?

**Comment by GuidoHub** [comment]
Problem still occurs in version 2.1.5 Does nobody else have the same problem. Can't be I am the only one here. Which info do you need more to investigate?

**Comment by GuidoHub** [comment]
Still not solved in version 2.1.6, would be nice if it would be investigated or could some one tell me in which tables I need to delete records manually?

**Comment by GuidoHub** [comment]
Why is this problem ignored. The result is corrupt data in some tables and could give big problems in the future. You should check the delete action for web site.

**Comment by korostii** [comment]
@GuidoHub, It's not like _this_ specific issue is ignored. Processing GitHub issues on the Magento2 repository overall is moving quite slow, there is a plenty of issues that go unanswered for months.
Even if it gets fixed, plenty of bugfixes that remain unreleased (not released? this shouldn't even be a thing in real world) also for months and many versions.

IMHO, your best shot is looking for some kind of a workaround.

**Comment by pratikmage** [comment]
I have same issue how to fix?

**Comment by magento-engcom-team** [comment]
@GuidoHub, thank you for your report.
We were not able to reproduce this issue by following the steps you provided.
Please provide more information how did you create multiple websites that use the same store.

**Comment by magento-engcom-team** [comment]
@GuidoHub we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
