### ISSUE TITLE
can't generate sitemap.xml - make sure path writable but displays wrong path

### ISSUE THREAD

**Issue by ghost** [magento/magento2#7453]
Hi,

I'm trying to generate the sitemap.xml but I get the following error:

The path "/pub/sitemap:///opt/magento/opt/magento/" is not writable

my magento installation is in /opt/magento so I'm not sure why it's doubling up the path?

I added the path as "/pub/sitemap". Although it wouldn't save when i tried to use the admin option in marketing -> sitemaps. I had to edit mysql to do that. Whatever path i would try and put in the editor would result in:

"Please make sure that "/pub/sitemap/" is writable by the web-server."

It's is writable - I even made it 777 permission while trying to get it to work for now?

### Preconditions
1. php 7
2. rhel 7
3. magento 2.1.2

### Steps to reproduce

1. go to marketing -> sitemaps
2. either click generate
3. or click on a sitemap and try and change the path and click save or save and generate

### Expected result
1. it generates the sitemap

### Actual result
1. if you click generate on main sitemap screen then this error "The path "/pub/sitemap:///opt/magento/opt/magento/" is not writable"
2. if click on sitemap and click save or save and generate then this error: "Please make sure that "/pub/sitemap/" is writable by the web-server"

**Comment by ghost** [comment]
ok so i tried on my local mac and it worked?

I'm using rhel7 on the server but i'm also using an SSL for the front and backend of the site. This is the only difference?

If i create an empty sitemap.xml file then try and generate it i get this error:

1 exception(s):
Exception #0 (Magento\Framework\Exception\FileSystemException): The file "/opt/magento/pub/sitemap//sitemap.xml" cannot be deleted Warning!unlink(/opt/magento/pub/sitemap//sitemap.xml): Permission denied

Exception #0 (Magento\Framework\Exception\FileSystemException): The file "/opt/magento/pub/sitemap//sitemap.xml" cannot be deleted Warning!unlink(/opt/magento/pub/sitemap//sitemap.xml): Permission denied
#0 /opt/magento/vendor/magento/framework/Filesystem/Directory/Write.php(173): Magento\Framework\Filesystem\Driver\File->deleteFile('/opt/magento...')
#1 /opt/magento/vendor/magento/module-sitemap/Controller/Adminhtml/Sitemap/Save.php(62): Magento\Framework\Filesystem\Directory\Write->delete('/pub/sitemap//s...')
#2 /opt/magento/vendor/magento/module-sitemap/Controller/Adminhtml/Sitemap/Save.php(78): Magento\Sitemap\Controller\Adminhtml\Sitemap\Save->clearSiteMap(Object(Magento\Sitemap\Model\Sitemap))
#3 /opt/magento/vendor/magento/module-sitemap/Controller/Adminhtml/Sitemap/Save.php(150): Magento\Sitemap\Controller\Adminhtml\Sitemap\Save->saveData(Array)
#4 /opt/magento/var/generation/Magento/Sitemap/Controller/Adminhtml/Sitemap/Save/Interceptor.php(24): Magento\Sitemap\Controller\Adminhtml\Sitemap\Save->execute()
#5 /opt/magento/vendor/magento/framework/App/Action/Action.php(102): Magento\Sitemap\Controller\Adminhtml\Sitemap\Save\Interceptor->execute()
#6 /opt/magento/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /opt/magento/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /opt/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Sitemap\Controller\Adminhtml\Sitemap\Save\Interceptor->___callParent('dispatch', Array)
#9 /opt/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Sitemap...', 'dispatch', Object(Magento\Sitemap\Controller\Adminhtml\Sitemap\Save\Interceptor), Array, 'adminAuthentica...')
#10 /opt/magento/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#11 /opt/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sitemap\Controller\Adminhtml\Sitemap\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /opt/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Sitemap...', 'dispatch', Object(Magento\Sitemap\Controller\Adminhtml\Sitemap\Save\Interceptor), Array, 'adminMassaction...')
#13 /opt/magento/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Sitemap\Controller\Adminhtml\Sitemap\Save\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#14 /opt/magento/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Sitemap\Controller\Adminhtml\Sitemap\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 /opt/magento/var/generation/Magento/Sitemap/Controller/Adminhtml/Sitemap/Save/Interceptor.php(39): Magento\Sitemap\Controller\Adminhtml\Sitemap\Save\Interceptor->___callPlugins('dispatch', Array, Array)
#16 /opt/magento/vendor/magento/framework/App/FrontController.php(55): Magento\Sitemap\Controller\Adminhtml\Sitemap\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /opt/magento/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /opt/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#19 /opt/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#20 /opt/magento/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#21 /opt/magento/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /opt/magento/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#23 /opt/magento/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /opt/magento/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\App\Http->launch()
#25 /opt/magento/var/generation/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#26 /opt/magento/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#27 /opt/magento/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))

**Comment by ghost** [comment]
argh....it was selinux. For anyone else who has this issue i did:

chcon -R -t httpd_sys_rw_content_t pub/sitemap/
