### ISSUE TITLE
Zend_Db_Statement_Exception after refreshing browser with empty category

### ISSUE THREAD

**Issue by coresh** [magento/magento2#7523]
### Preconditions

1. Magento EE 2.1.2 without sample data is installed.
2. Clean install. Only with Test category setup.
4. No any products exists

### Steps to reproduce

1. Created testcategory.
2. Admin -> PRODUCTS -> Categories Tab: Selected "testcategory";
3. "testcategory" Settings:
   Content -> Add CMS Block Tab: select box with selected "Catalog Events Lister"
   Display Settings -> Display Mode Tab: select box with  selected "Static block and products" 
   Screenshot:
![untitled_3](https://cloud.githubusercontent.com/assets/9606476/20528145/f3ae8752-b0c2-11e6-999e-2fe230a2e7f1.jpg)

4. Saved Category settings.
5. magento cli commands - without any issues:
```
$ bin/magento cache:flush
$ bin/magento setup:upgrade
$ bin/magento indexer:reindex
$ bin/magento cache:flush
```
6. After opening a browser with created category: https://localhost/testcategoryurlkey
```
$ tail -1000 var/log/exeption.log

Next Zend_Db_Statement_Exception: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'entity_id' in where clause is ambiguous, query was: SELECT `main_table`.`entity_id`, `main_table`.`level`, `main_table`.`path`, `main_table`.`position`, `main_table`.`is_active`, `main_table`.`is_anchor`, `main_table`.`name`, `url_rewrite`.`request_path` FROM `catalog_category_flat_store_9` AS `main_table`
 LEFT JOIN `url_rewrite` ON url_rewrite.entity_id = main_table.entity_id AND url_rewrite.is_autogenerated = 1 AND url_rewrite.store_id = '9' AND url_rewrite.entity_type = 'category' WHERE (`path` LIKE '1/2/%') AND (`main_table`.`store_id` = '9') AND (`is_active` = '1') AND (`include_in_menu` = '1') AND (`entity_id` = '') ORDER BY position ASC
 in /m2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /m2/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 /m2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /m2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /m2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 /m2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(459): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 /m2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(514): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `main_ta...', Array)
#6 /m2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 /m2/vendor/magento/framework/Data/Collection/Db/FetchStrategy/Query.php(21): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select), Array)
#8 /m2/vendor/magento/framework/Data/Collection/AbstractDb.php(772): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll(Object(Magento\Framework\DB\Select), Array)
#9 /m2/vendor/magento/framework/Data/Collection/AbstractDb.php(668): Magento\Framework\Data\Collection\AbstractDb->_fetchAll(Object(Magento\Framework\DB\Select))
#10 /m2/vendor/magento/framework/Data/Collection/AbstractDb.php(572): Magento\Framework\Data\Collection\AbstractDb->getData()
#11 /m2/vendor/magento/framework/Data/Collection/AbstractDb.php(557): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#12 /m2/vendor/magento/framework/Data/Collection.php(820): Magento\Framework\Data\Collection\AbstractDb->load()
#13 /m2/vendor/magento/module-catalog-event/Block/Event/Lister.php(127): Magento\Framework\Data\Collection->getIterator()
#14 /m2/vendor/magento/module-catalog-event/Block/Event/Lister.php(95): Magento\CatalogEvent\Block\Event\Lister->getEvents()
#15 /m2/vendor/magento/module-catalog-event/Block/Event/Lister.php(210): Magento\CatalogEvent\Block\Event\Lister->canDisplay()
#16 /m2/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\CatalogEvent\Block\Event\Lister->_toHtml()
#17 /m2/vendor/magento/module-email/Model/Template/Filter.php(366): Magento\Framework\View\Element\AbstractBlock->toHtml()
#18 [internal function]: Magento\Email\Model\Template\Filter->blockDirective(Array)
#19 /m2/vendor/magento/framework/Filter/Template.php(141): call_user_func(Array, Array)
#20 /m2/vendor/magento/module-email/Model/Template/Filter.php(965): Magento\Framework\Filter\Template->filter('{{block class="...')
#21 /m2/vendor/magento/module-cms/Block/Block.php(72): Magento\Email\Model\Template\Filter->filter('{{block class="...')
#22 /m2/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Cms\Block\Block->_toHtml()
#23 /m2/vendor/magento/module-catalog/Block/Category/View.php(124): Magento\Framework\View\Element\AbstractBlock->toHtml()
#24 /m2/vendor/magento/module-catalog/view/frontend/templates/category/cms.phtml(19): Magento\Catalog\Block\Category\View->getCmsBlockHtml()
#25 /m2/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/lightt...')
#26 /m2/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Category\View), '/var/www/lightt...', Array)
#27 /m2/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/lightt...')
#28 /m2/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#29 /m2/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#30 /m2/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('category.cms')
#31 /m2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('category.cms')
#32 /m2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('category.cms')
#33 /m2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('category.cms', true)
#34 /m2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('category.cms')
#35 /m2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('category.view.c...')
#36 /m2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('category.view.c...')
#37 /m2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('category.view.c...')
#38 /m2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('category.view.c...', true)
#39 /m2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('category.view.c...')
#40 /m2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('columns.top')
#41 /m2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns.top')
#42 /m2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns.top')
#43 /m2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns.top', true)
#44 /m2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('columns.top')
#45 /m2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.content')
#46 /m2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#47 /m2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#48 /m2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
#49 /m2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
#50 /m2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#51 /m2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#52 /m2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#53 /m2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#54 /m2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#55 /m2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#56 /m2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#57 /m2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#58 /m2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#59 /m2/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#60 /m2/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Layout->getOutput()
#61 /m2/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#62 /m2/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#63 /m2/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#64 /m2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#65 /m2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#66 /m2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#67 /m2/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#68 /m2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#69 /m2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#70 /m2/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#71 /m2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#72 /m2/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#73 /m2/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#74 /m2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#75 /m2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

```

### Expected result

1. Screenshot:
![untitled_2](https://cloud.githubusercontent.com/assets/9606476/20528101/c98caefe-b0c2-11e6-9216-d4817ce81921.jpg)

### Actual result

1. [Screenshot]
![untitled_1](https://cloud.githubusercontent.com/assets/9606476/20528112/d352bd34-b0c2-11e6-80f9-20609dfce442.jpg)

### No issues with following category settings (Without Catalog Events Lister):
Admin -> PRODUCTS -> Categories Tab: Selected "testcategory";
Content -> Add CMS Block Tab: select box with selected "Static block and products"
Display Settings -> Display Mode Tab: select box with  selected "Static block and products"

**Comment by veloraven** [comment]
@coresh thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.

**Comment by vzabaznov** [comment]
closed as we don't receive update more than 2 week, @coreshplease feel free to write here/reopen or to open new issue

**Comment by adrian-martinez-interactiv4** [comment]
This issue is expected to be solved with pull request https://github.com/magento/magento2/pull/9400

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-68770
