### ISSUE TITLE
Saving card to vault breaks get order API method

### ISSUE THREAD

**Issue by alexnos88** [magento/magento2#7526]
### Preconditions
1. order placed with saved card

### Steps to reproduce
1. call /rest/V1/orders/{orderNo} OR /rest/V1/orders?searchCriteria[filter_groups][0][filters][0][field]=entity_id&searchCriteria[filter_groups][0][filters][0][value]={orderNo}

### Expected result
1. successful response with order info

### Actual result
1. error response:
```
<response>
  <message>Notice: Array to string conversion in /var/www/magento/html/vendor/magento/framework/Reflection/TypeCaster.php on line 34</message>
  <trace>#0 /var/www/magento/html/vendor/magento/framework/Reflection/TypeCaster.php(34): Magento\Framework\App\ErrorHandler-&gt;handler(8, 'Array to string...', '/var/www/magent...', 34, Array)
#1 /var/www/magento/html/vendor/magento/framework/Reflection/DataObjectProcessor.php(115): Magento\Framework\Reflection\TypeCaster-&gt;castValueToType(Array, 'string')
#2 /var/www/magento/html/vendor/magento/framework/Reflection/DataObjectProcessor.php(107): Magento\Framework\Reflection\DataObjectProcessor-&gt;buildOutputDataArray(Object(Magento\Sales\Model\Order\Payment\Interceptor), '\\Magento\\Sales\\...')
#3 /var/www/magento/html/vendor/magento/framework/Reflection/DataObjectProcessor.php(113): Magento\Framework\Reflection\DataObjectProcessor-&gt;buildOutputDataArray(Object(Magento\Sales\Model\Order), '\\Magento\\Sales\\...')
#4 /var/www/magento/html/vendor/magento/framework/Webapi/ServiceOutputProcessor.php(107): Magento\Framework\Reflection\DataObjectProcessor-&gt;buildOutputDataArray(Object(Magento\Sales\Model\ResourceModel\Order\Collection), '\\Magento\\Sales\\...')
#5 /var/www/magento/html/vendor/magento/framework/Webapi/ServiceOutputProcessor.php(59): Magento\Framework\Webapi\ServiceOutputProcessor-&gt;convertValue(Object(Magento\Sales\Model\ResourceModel\Order\Collection), '\\Magento\\Sales\\...')
#6 /var/www/magento/html/vendor/magento/module-webapi/Controller/Rest.php(312): Magento\Framework\Webapi\ServiceOutputProcessor-&gt;process(Object(Magento\Sales\Model\ResourceModel\Order\Collection), 'Magento\\Sales\\A...', 'getList')
#7 /var/www/magento/html/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest-&gt;processApiRequest()
#8 /var/www/magento/html/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest-&gt;dispatch(Object(Magento\Framework\App\Request\Http))
#9 /var/www/magento/html/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor-&gt;dispatch(Object(Magento\Framework\App\Request\Http))
#10 /var/www/magento/html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http-&gt;launch()
#11 /var/www/magento/html/pub/index.php(37): Magento\Framework\App\Bootstrap-&gt;run(Object(Magento\Framework\App\Http))
#12 {main}</trace>
</response>
```

As it was investigated, 
\vendor\magento\module-vault\Observer\PaymentTokenAssigner.php, *execute()* method has the following code:
```
    $paymentModel->setAdditionalInformation(
        Vault::TOKEN_METADATA_KEY,
        [
            PaymentTokenInterface::CUSTOMER_ID => $customerId,
            PaymentTokenInterface::PUBLIC_HASH => $tokenPublicHash
        ]
    );
```
which sets an array value to additionalInfo array.

Although API method \vendor\magento\module-sales\Api\Data\OrderPaymentInterface.php, getAdditionalInformation() method has the phpDoc:
```
* @return string[]
```

So there is an error in \vendor\magento\framework\Reflection\DataObjectProcessor.php : 115
when the type is string, but the value is a dictionary (from above).

Suggested fix is to set additionalInfo to separate keys, like that:
```
...
->setAdditionalInformation(
        Vault::TOKEN_METADATA_KEY . PaymentTokenInterface::CUSTOMER_ID,
        $customerId
    )
->setAdditionalInformation(
        Vault::TOKEN_METADATA_KEY . PaymentTokenInterface::PUBLIC_HASH,
        $tokenPublicHash
    )
```
and then write this info back from those separate keys as well.

Please consider to make an internal bug and to provide a fix.
thanks.

**Comment by YevSent** [comment]
Hi @alexnos88, this is known issue and already fixed on develop branch.

Closed as duplicate to https://github.com/magento/magento2/issues/6215.
