### ISSUE TITLE
Area code "_requirejs" does not exist, 404 on requirejs-config.js in admin?

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#7630]
### Preconditions
Magento devel, PHP 7, Mysq 5.7, Clean install of Magento 2

bin/magento deploy:mode:show
```
Current application mode: developer. (Note: Environment variables may override this value.)
```

The admin does not work properly (javascript error).

If I view the file directly, it does not 404 I get this error:

```
Area code "_requirejs" does not exist
#0 /Users/ccarnell/Sites/magento2/lib/internal/Magento/Framework/App/State.php(126): Magento\Framework\App\State->checkAreaCode('_requirejs')
#1 /Users/ccarnell/Sites/magento2/lib/internal/Magento/Framework/App/StaticResource.php(96): Magento\Framework\App\State->setAreaCode('_requirejs')
#2 /Users/ccarnell/Sites/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\StaticResource->launch()
#3 /Users/ccarnell/Sites/magento2/pub/static.php(13): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\StaticResource))
#4 {main}
```

### Steps to reproduce
View the admin

### Expected result
The side bars to be able to break out

### Actual result
```
GET https://www.xxx.co.uk.local/static/version1480517983/_requirejs/adminhtml/Magento/backend/en_US/secure/requirejs-config.js 
require.js:1895 GET https://www.xxx.co.uk.local/static/version1480517983/adminhtml/Magento/backend/en_US/jquery/ui.js req.load @ require.js:1895load @ require.js:1639load @ require.js:820fetch @ require.js:810check @ require.js:840enable @ require.js:1143enable @ require.js:1511(anonymous function) @ require.js:1128(anonymous function) @ require.js:132each @ require.js:57enable @ require.js:1090init @ require.js:774(anonymous function) @ require.js:1416
require.js:166 Uncaught Error: Script error for: jquery/ui(…)makeError @ require.js:166onScriptError @ require.js:1681
require.js:1895 GET https://www.xxx.co.uk.local/static/version1480517983/adminhtml/Magento/backend/en_US/jquery/jquery-storageapi.js req.load @ require.js:1895load @ require.js:1639load @ require.js:820fetch @ require.js:810check @ require.js:840enable @ require.js:1143enable @ require.js:1511(anonymous function) @ require.js:1128(anonymous function) @ require.js:132each @ require.js:57enable @ require.js:1090init @ require.js:774(anonymous function) @ require.js:1416
require.js:166 Uncaught Error: Script error for: jquery/jquery-storageapi(…)makeError @ require.js:166onScriptError @ require.js:1681
require.js:1895 GET https://www.xxx.co.uk.local/static/version1480517983/adminhtml/Magento/backend/en_US/prototype.js req.load @ require.js:1895load @ require.js:1639load @ require.js:820fetch @ require.js:810check @ require.js:840enable @ require.js:1143enable @ require.js:1511(anonymous function) @ require.js:1128(anonymous function) @ require.js:132each @ require.js:57enable @ require.js:1090init @ require.js:774callGetModule @ require.js:1170completeLoad @ require.js:1544onScriptLoad @ require.js:1671
require.js:166 Uncaught Error: Script error for: prototype(…)makeError @ require.js:166onScriptError @ require.js:1681
require.js:1895 GET https://www.xxx.co.uk.local/static/version1480517983/adminhtml/Magento/backend/en_US/text.js req.load @ require.js:1895load @ require.js:1639load @ require.js:820fetch @ require.js:810check @ require.js:840enable @ require.js:1143enable @ require.js:1511callPlugin @ require.js:1075fetch @ require.js:810check @ require.js:840enable @ require.js:1143enable @ require.js:1511(anonymous function) @ require.js:1128(anonymous function) @ require.js:132each @ require.js:57enable @ require.js:1090init @ require.js:774callGetModule @ require.js:1170completeLoad @ require.js:1544onScriptLoad @ require.js:1671
require.js:166 Uncaught Error: Script error for: text(…)makeError @ require.js:166onScriptError @ require.js:1681
require.js:166 Uncaught Error: Load timeout for modules: text!ui/template/modal/modal-popup.html_unnormalized2,text!ui/template/modal/modal-slide.html_unnormalized3,text!ui/template/modal/modal-custom.html_unnormalized4(…)
```

**Comment by centerax** [comment]
how did you solve it @craigcarnell ?
