### ISSUE TITLE
Cart id = null error

### ISSUE THREAD

**Issue by crantron** [magento/magento2#7635]
Magento 2.1.2 

### Steps to reproduce
1. Add an Item to cart.
2. Stay on cart page until session expires
3. Refresh Page
4. Error will result

### Expected result
1. Redirect to login page

### Actual result
```
1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with cartId = 

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with cartId = 
#0 /home/chef4/public_html/shop/vendor/magento/module-quote/Model/QuoteRepository.php(197): Magento\Framework\Exception\NoSuchEntityException::singleField('cartId', NULL)
#1 /home/chef4/public_html/shop/vendor/magento/module-quote/Model/QuoteRepository.php(101): Magento\Quote\Model\QuoteRepository->loadQuote('load', 'cartId', NULL, Array)
#2 /home/chef4/public_html/shop/var/generation/Magento/Quote/Model/QuoteRepository/Interceptor.php(24): Magento\Quote\Model\QuoteRepository->get(NULL, Array)
#3 /home/chef4/public_html/shop/vendor/magento/module-quote/Model/QuoteRepository.php(127): Magento\Quote\Model\QuoteRepository\Interceptor->get(NULL, Array)
#4 /home/chef4/public_html/shop/var/generation/Magento/Quote/Model/QuoteRepository/Interceptor.php(50): Magento\Quote\Model\QuoteRepository->getActive(NULL, Array)
#5 /home/chef4/public_html/shop/vendor/magento/module-quote/Model/Quote/Item/Repository.php(69): Magento\Quote\Model\QuoteRepository\Interceptor->getActive(NULL)
#6 /home/chef4/public_html/shop/vendor/magento/module-checkout/Model/Cart/ImageProvider.php(44): Magento\Quote\Model\Quote\Item\Repository->getList(NULL)
#7 /home/chef4/public_html/shop/vendor/magento/module-checkout/Model/DefaultConfigProvider.php(281): Magento\Checkout\Model\Cart\ImageProvider->getImages(NULL)
#8 /home/chef4/public_html/shop/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Checkout\Model\DefaultConfigProvider->getConfig()
#9 /home/chef4/public_html/shop/var/generation/Magento/Checkout/Model/DefaultConfigProvider/Interceptor.php(26): Magento\Checkout\Model\DefaultConfigProvider\Interceptor->___callPlugins('getConfig', Array, Array)
#10 /home/chef4/public_html/shop/vendor/magento/module-checkout/Model/CompositeConfigProvider.php(32): Magento\Checkout\Model\DefaultConfigProvider\Interceptor->getConfig()
#11 /home/chef4/public_html/shop/vendor/magento/module-checkout/Block/Cart/Shipping.php(54): Magento\Checkout\Model\CompositeConfigProvider->getConfig()
#12 /home/chef4/public_html/shop/app/design/frontend/ChefsToys/default/Magento_Checkout/templates/cart/shipping.phtml(28): Magento\Checkout\Block\Cart\Shipping->getCheckoutConfig()
#13 /home/chef4/public_html/shop/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/chef4/pub...')
#14 /home/chef4/public_html/shop/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Cart\Shipping), '/home/chef4/pub...', Array)
#15 /home/chef4/public_html/shop/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/chef4/pub...')
#16 /home/chef4/public_html/shop/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#17 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#18 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('checkout.cart.s...')
#19 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('checkout.cart.s...')
#20 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('checkout.cart.s...')
#21 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('checkout.cart.s...', true)
#22 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('checkout.cart.s...')
#23 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('cart.summary.bo...')
#24 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('cart.summary.bo...')
#25 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('cart.summary.bo...')
#26 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('cart.summary.bo...', true)
#27 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('cart.summary.bo...')
#28 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#29 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#30 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#31 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#32 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#33 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main')
#34 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#35 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#36 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', true)
#37 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main')
#38 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('columns')
#39 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#40 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#41 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', true)
#42 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('columns')
#43 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.content')
#44 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#45 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#46 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
#47 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
#48 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#49 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#50 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#51 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#52 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#53 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#54 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#55 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#56 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#57 /home/chef4/public_html/shop/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#58 /home/chef4/public_html/shop/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Layout->getOutput()
#59 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#60 /home/chef4/public_html/shop/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#61 /home/chef4/public_html/shop/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#62 /home/chef4/public_html/shop/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#63 /home/chef4/public_html/shop/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#64 /home/chef4/public_html/shop/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#65 /home/chef4/public_html/shop/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#66 /home/chef4/public_html/shop/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#67 /home/chef4/public_html/shop/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#68 /home/chef4/public_html/shop/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#69 /home/chef4/public_html/shop/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#70 /home/chef4/public_html/shop/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#71 /home/chef4/public_html/shop/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#72 /home/chef4/public_html/shop/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#73 /home/chef4/public_html/shop/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#74 {main}

```

**Comment by crantron** [comment]
This was due to overriding checkout_cart_index.xml, moving child containers out of checkout.cart.items container. 
This can be closed.

**Comment by dharake** [comment]
@crantron Can you please elaborate, having the same issue

**Comment by crantron** [comment]
@dharake from what I remember, are you trying to do some wild stuff with the minicart? If the minicart xml configs are not exactly correct, this will occur.

**Comment by hassanas** [comment]
https://magento.stackexchange.com/questions/261272/magento-2-2-7-no-such-entity-with-cartid/265089#265089
