### ISSUE TITLE
We are unable to add new 'User Roles' in the Magento backend.

### ISSUE THREAD

**Issue by kleverk-Designs** [magento/magento2#7656]
### Preconditions

Magento 2.1.2 PHP Version 7

### Steps to reproduce

1. Steps to reproduce: Log in, go to System > User Roles. Add New Role

### Expected result

1. Expected result: When pressing 'Save Rule,' the new User Role is added.

### Actual result

1. There is no response when pressing the 'Save Role' button. Additionally, under the 'Role Resources' tab, there is no Resources tree when selecting the 'Custom' Resource Access option. There are no errors being produced, save for this which is available in the Chrome console:

VM1248:1 Uncaught SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at getData (http://www.bharatkartonline.in/pub/static/adminhtml/Magento/backend/en_US/mage/apply/main.js:51:24)
at Array.map (native)
at Object.apply (http://www.bharatkartonline.in/pub/static/adminhtml/Magento/backend/en_US/mage/apply/main.js:67:18)
at HTMLDocument.bootstrap (http://www.bharatkartonline.in/pub/static/adminhtml/Magento/backend/en_US/mage/backend/bootstrap.js:70:14)
at fire (http://www.bharatkartonline.in/pub/static/adminhtml/Magento/backend/en_US/jquery.js:3099:30)
at Object.add [as done] (http://www.bharatkartonline.in/pub/static/adminhtml/Magento/backend/en_US/jquery.js:3145:7)
at jQuery.fn.init.jQuery.fn.ready (http://www.bharatkartonline.in/pub/static/adminhtml/Magento/backend/en_US/jquery.js:3379:25)
at jQuery.fn.init (http://www.bharatkartonline.in/pub/static/adminhtml/Magento/backend/en_US/jquery.js:2819:16)
at jQuery.fn.init (http://www.bharatkartonline.in/pub/static/adminhtml/Magento/backend/en_US/jquery/jquery-migrate.js:225:17)

**Comment by yaroslavGoncharuk** [comment]
@kleverk-Designs Thanks for reporting this issue. 

We cannot reproduce this issue as described.
In addition, identify, please:
- your application mode 
- if you have any extensions
- special options in Magento Configuration
- are you running clear 2.1.2 installation or upgraded from any previous version?

**Comment by kleverk-Designs** [comment]
Thanks for the reply.

We have 4 extension from same vendor.
We are running clear 2.1.2 install

Thanks

On Tue, Dec 6, 2016 at 7:03 PM, Yaroslav Goncharuk <notifications@github.com

**Comment by magento-engcom-team** [comment]
Hi @kleverk-Designs could you please try latest release? We can not reproduce the issue on our side.
