### ISSUE TITLE
Errors in the 'guest-carts' REST API

### ISSUE THREAD

**Issue by dreucifer** [magento/magento2#7783]
### Preconditions

1. Magento 2.1.2
2. Set 'Allow Anonymous Guest Access' to 'Yes'

### Steps to reproduce

1. Generate a new guest cart id:  
`POST /rest/default/V1/guest-carts`

2. Add products to that cart:  
    `POST /rest/default/V1/guest-carts/{cartId}/items {
        "cartItem": {
            "sku": "<item_sku>",
            "qty": 1
        }
    }`

### Expected result

1. A nice Status 200 response and see the product in the cart.

### Actual result

`{ "message": "No such entity with %fieldName = %fieldValue",
      "parameters": { "fieldName": "cartId", "fieldValue": null } }`

Adding `cartId` to the request returns:

    Next Exception: Message: Property "CartId" does not have corresponding setter in class "Magento\Quote\Api\Data\CartItemInterface". in <magento_root>/vendor/magento/framework/Webapi/ErrorProcessor.php:195
    Stack trace:
    #0 <magento_root>/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(LogicException))
    #1 <magento_root>/vendor/magento/module-webapi/Controller/Rest.php(219): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(LogicException))
    #2 <magento_root>/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
    #3 <magento_root>/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
    #4 <magento_root>/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
    #5 <magento_root>/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
    #6 {main} [] []

**Comment by dreucifer** [comment]
~~~Upon further review, an empty cart is created in the `quote` table, but `quote_id_mask` doesn't get populated, therefore the `quoteIdMaskFactory` methods in the `createEmptyCart()` function of `Magento\Quote\Model\GuestCart\GuestCartManagement` are silently failing.~~~

Nevermind, I was looking at the table sorted by masked_id, not quote ID. Disregard.

**Comment by dreucifer** [comment]
Another weird issue is If I create a new empty cart then immediately use `GET /V1/guest-carts/{cartId}/items`, I get the `{ "message": "No such entity with %fieldName = %fieldValue", "parameters": { "fieldName": "cartId", "fieldValue": null } }` error, but if I wait a few seconds and do it again, I get a proper response. Trying to add a product to that same cart still fails like cartId isn't being passed to the save function.

**Comment by dreucifer** [comment]
I forgot to include `quote_id` along with in the `cartItem` payload. I also forgot to strip the quotes from the value returned by `POST /rest/default/V1/guest-carts`. Everything appears to be in order, it was all just PEBKAC.
