### ISSUE TITLE
Error on Catalog Pages after 2.1.2 to 2.1.3: Call to a member function getStockStatus() on null in ../vendor/magento/module-configurable-product/Model/Product/Type/Configurable.php:1298

### ISSUE THREAD

**Issue by MorganGonzales** [magento/magento2#7870]
After upgrading from 2.1.2 to 2.1.3, I am getting this error whenever I visit catalog pages.

Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getStockStatus() on null in /home/staging213bsw/public_html/releases/20161215054523/vendor/magento/module-configurable-product/Model/Product/Type/Configurable.php:1298
Stack trace:
#0 [internal function]: Magento\\ConfigurableProduct\\Model\\Product\\Type\\Configurable->Magento\\ConfigurableProduct\\Model\\Product\\Type\\{closure}(Object(Magento\\Catalog\\Model\\Product\\Interceptor))
#1 /home/staging213bsw/public_html/releases/20161215054523/vendor/magento/module-configurable-product/Model/Product/Type/Configurable.php(1304): array_filter(Array, Object(Closure))
#2 /home/staging213bsw/public_html/releases/20161215054523/var/generation/Acidgreen/Fixedcore/Model/Product/Type/Configurable/Interceptor.php(479): Magento\\ConfigurableProduct\\Model\\Product\\Type\\Configurable->getSalableUsedProducts(Object(Magento\\Catalog\\Model\\Product\\Interceptor), NULL)
#3 /home/staging213bsw/public_html/releases/20161215054523/vendor/magento/module-configurable-product/...'

### Preconditions
Using
- Apache Server
- PHP 7.0.8
- Magento 2.1.3 installed

### Expected result
Catalog list page should display normally

### Actual result
It seems that $this->stockRegistry is null. By how code is implemented, di.xml is properly configured to inject the StockRegistry model but it seems it is returning null.

**Comment by MorganGonzales** [comment]
My apologies, it was a mistake that I overlooked a custom module that overrides the Configurable.php class. 

Closing this issue now.
