### ISSUE TITLE
Can't create two products via REST API with same name

### ISSUE THREAD

**Issue by careys7** [magento/magento2#8188]
### Preconditions

1. Magento 2.1.3 with Sample Data

### Steps to reproduce

1. Create two products via API with same name, eg:

**Request 1**
```
POST /rest/default/V1/products/ HTTP/1.1
Host: example.com
Authorization: OAuth oauth_consumer_key="sitoq7tu4b1aj7kikj4irkog8tggh1ch",oauth_token="kr3bly2kbbnrr9flyws9r4mxdaagxngo",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1484796895",oauth_nonce="ah5BdS",oauth_signature="kNaSGRy%2FNg5SYBf%2BI1AJuozM1hs%3D"
Content-Type: application/json
Cache-Control: no-cache

{
	"product": {
		"attribute_set_id": 4,
		"name": "Test API 1",
		"price": 254.13,
		"sku": "1234"
	}
}
```

**Request 2**
```
POST /rest/default/V1/products/ HTTP/1.1
Host: example.com
Authorization: OAuth oauth_consumer_key="sitoq7tu4b1aj7kikj4irkog8tggh1ch",oauth_token="kr3bly2kbbnrr9flyws9r4mxdaagxngo",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1484796895",oauth_nonce="ah5BdS",oauth_signature="kNaSGRy%2FNg5SYBf%2BI1AJuozM1hs%3D"
Content-Type: application/json
Cache-Control: no-cache

{
	"product": {
		"attribute_set_id": 4,
		"name": "Test API 1",
		"price": 254.13,
		"sku": "1235"
	}
}
```

### Expected result

1. Both products created successfully

### Actual result

1. Error "URL key for specified store already exists."

```
{"message":"URL key for specified store already exists.","trace":"#0 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(74): Magento\\UrlRewrite\\Model\\Storage\\AbstractStorage->replace(Array)\n#1 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Chain\/Chain.php(70): Magento\\UrlRewrite\\Model\\Storage\\DbStorage\\Interceptor->___callParent('replace', Array)\n#2 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\Interception\\Chain\\Chain->invokeNext('Magento\\\\UrlRewr...', 'replace', Object(Magento\\UrlRewrite\\Model\\Storage\\DbStorage\\Interceptor), Array, 'storage_plugin')\n#3 \/var\/www\/html\/vendor\/magento\/module-catalog-url-rewrite\/Model\/Category\/Plugin\/Storage.php(43): Magento\\UrlRewrite\\Model\\Storage\\DbStorage\\Interceptor->Magento\\Framework\\Interception\\{closure}(Array)\n#4 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(142): Magento\\CatalogUrlRewrite\\Model\\Category\\Plugin\\Storage->aroundReplace(Object(Magento\\UrlRewrite\\Model\\Storage\\DbStorage\\Interceptor), Object(Closure), Array)\n#5 \/var\/www\/html\/var\/generation\/Magento\/UrlRewrite\/Model\/Storage\/DbStorage\/Interceptor.php(65): Magento\\UrlRewrite\\Model\\Storage\\DbStorage\\Interceptor->___callPlugins('replace', Array, Array)\n#6 \/var\/www\/html\/vendor\/magento\/module-catalog-staging\/Model\/Url\/Storage.php(56): Magento\\UrlRewrite\\Model\\Storage\\DbStorage\\Interceptor->replace(Array)\n#7 \/var\/www\/html\/vendor\/magento\/module-catalog-url-rewrite\/Observer\/ProductProcessUrlRewriteSavingObserver.php(61): Magento\\CatalogStaging\\Model\\Url\\Storage->replace(Array)\n#8 \/var\/www\/html\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(73): Magento\\CatalogUrlRewrite\\Observer\\ProductProcessUrlRewriteSavingObserver->execute(Object(Magento\\Framework\\Event\\Observer))\n#9 \/var\/www\/html\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(61): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(Magento\\CatalogUrlRewrite\\Observer\\ProductProcessUrlRewriteSavingObserver), Object(Magento\\Framework\\Event\\Observer))\n#10 \/var\/www\/html\/vendor\/magento\/module-staging\/Model\/Event\/Manager.php(97): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, Object(Magento\\Framework\\Event\\Observer))\n#11 \/var\/www\/html\/var\/generation\/Magento\/Staging\/Model\/Event\/Manager\/Proxy.php(95): Magento\\Staging\\Model\\Event\\Manager->dispatch('catalog_product...', Array)\n#12 \/var\/www\/html\/vendor\/magento\/framework\/Model\/AbstractModel.php(802): Magento\\Staging\\Model\\Event\\Manager\\Proxy->dispatch('catalog_product...', Array)\n#13 \/var\/www\/html\/vendor\/magento\/module-catalog\/Model\/Product.php(921): Magento\\Framework\\Model\\AbstractModel->afterSave()\n#14 \/var\/www\/html\/var\/generation\/Magento\/Catalog\/Model\/Product\/Interceptor.php(362): Magento\\Catalog\\Model\\Product->afterSave()\n#15 \/var\/www\/html\/vendor\/magento\/framework\/EntityManager\/Observer\/AfterEntitySave.php(34): Magento\\Catalog\\Model\\Product\\Interceptor->afterSave()\n#16 \/var\/www\/html\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(73): Magento\\Framework\\EntityManager\\Observer\\AfterEntitySave->execute(Object(Magento\\Framework\\Event\\Observer))\n#17 \/var\/www\/html\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(61): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(Magento\\Framework\\EntityManager\\Observer\\AfterEntitySave), Object(Magento\\Framework\\Event\\Observer))\n#18 \/var\/www\/html\/vendor\/magento\/module-staging\/Model\/Event\/Manager.php(97): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, Object(Magento\\Framework\\Event\\Observer))\n#19 \/var\/www\/html\/var\/generation\/Magento\/Staging\/Model\/Event\/Manager\/Proxy.php(95): Magento\\Staging\\Model\\Event\\Manager->dispatch('magento_catalog...', Array)\n#20 \/var\/www\/html\/vendor\/magento\/framework\/EntityManager\/EventManager.php(51): Magento\\Staging\\Model\\Event\\Manager\\Proxy->dispatch('magento_catalog...', Array)\n#21 \/var\/www\/html\/vendor\/magento\/module-staging\/Model\/Operation\/Create.php(138): Magento\\Framework\\EntityManager\\EventManager->dispatchEntityEvent('Magento\\\\Catalog...', 'save_after', Array)\n#22 \/var\/www\/html\/vendor\/magento\/framework\/EntityManager\/EntityManager.php(87): Magento\\Staging\\Model\\Operation\\Create->execute(Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#23 \/var\/www\/html\/vendor\/magento\/module-catalog\/Model\/ResourceModel\/Product.php(695): Magento\\Framework\\EntityManager\\EntityManager->save(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#24 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(74): Magento\\Catalog\\Model\\ResourceModel\\Product->save(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#25 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Chain\/Chain.php(70): Magento\\Catalog\\Model\\ResourceModel\\Product\\Interceptor->___callParent('save', Array)\n#26 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Chain\/Chain.php(63): Magento\\Framework\\Interception\\Chain\\Chain->invokeNext('Magento\\\\Catalog...', 'save', Object(Magento\\Catalog\\Model\\ResourceModel\\Product\\Interceptor), Array, 'catalogsearchFu...')\n#27 \/var\/www\/html\/vendor\/magento\/module-catalog-search\/Model\/Indexer\/Fulltext\/Plugin\/Product.php(51): Magento\\Framework\\Interception\\Chain\\Chain->Magento\\Framework\\Interception\\Chain\\{closure}(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#28 \/var\/www\/html\/vendor\/magento\/module-catalog-search\/Model\/Indexer\/Fulltext\/Plugin\/Product.php(24): Magento\\CatalogSearch\\Model\\Indexer\\Fulltext\\Plugin\\Product->addCommitCallback(Object(Magento\\Catalog\\Model\\ResourceModel\\Product\\Interceptor), Object(Closure), Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#29 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Chain\/Chain.php(67): Magento\\CatalogSearch\\Model\\Indexer\\Fulltext\\Plugin\\Product->aroundSave(Object(Magento\\Catalog\\Model\\ResourceModel\\Product\\Interceptor), Object(Closure), Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#30 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\Interception\\Chain\\Chain->invokeNext('Magento\\\\Catalog...', 'save', Object(Magento\\Catalog\\Model\\ResourceModel\\Product\\Interceptor), Array, 'clean_cache')\n#31 \/var\/www\/html\/vendor\/magento\/framework\/App\/Cache\/FlushCacheByTags.php(71): Magento\\Catalog\\Model\\ResourceModel\\Product\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#32 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(142): Magento\\Framework\\App\\Cache\\FlushCacheByTags->aroundSave(Object(Magento\\Catalog\\Model\\ResourceModel\\Product\\Interceptor), Object(Closure), Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#33 \/var\/www\/html\/var\/generation\/Magento\/Catalog\/Model\/ResourceModel\/Product\/Interceptor.php(273): Magento\\Catalog\\Model\\ResourceModel\\Product\\Interceptor->___callPlugins('save', Array, Array)\n#34 \/var\/www\/html\/vendor\/magento\/module-catalog\/Model\/ProductRepository.php(538): Magento\\Catalog\\Model\\ResourceModel\\Product\\Interceptor->save(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#35 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(74): Magento\\Catalog\\Model\\ProductRepository->save(Object(Magento\\Catalog\\Model\\Product\\Interceptor), false)\n#36 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Chain\/Chain.php(70): Magento\\Catalog\\Model\\ProductRepository\\Interceptor->___callParent('save', Array)\n#37 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Chain\/Chain.php(63): Magento\\Framework\\Interception\\Chain\\Chain->invokeNext('Magento\\\\Catalog...', 'save', Object(Magento\\Catalog\\Model\\ProductRepository\\Interceptor), Array, 'configurablePro...')\n#38 \/var\/www\/html\/vendor\/magento\/module-configurable-product\/Model\/Plugin\/AroundProductRepositorySave.php(62): Magento\\Framework\\Interception\\Chain\\Chain->Magento\\Framework\\Interception\\Chain\\{closure}(Object(Magento\\Catalog\\Model\\Product\\Interceptor), false)\n#39 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Chain\/Chain.php(67): Magento\\ConfigurableProduct\\Model\\Plugin\\AroundProductRepositorySave->aroundSave(Object(Magento\\Catalog\\Model\\ProductRepository\\Interceptor), Object(Closure), Object(Magento\\Catalog\\Model\\Product\\Interceptor), false)\n#40 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\Interception\\Chain\\Chain->invokeNext('Magento\\\\Catalog...', 'save', Object(Magento\\Catalog\\Model\\ProductRepository\\Interceptor), Array, 'catalogInventor...')\n#41 \/var\/www\/html\/vendor\/magento\/module-catalog-inventory\/Model\/Plugin\/AroundProductRepositorySave.php(74): Magento\\Catalog\\Model\\ProductRepository\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Catalog\\Model\\Product\\Interceptor), false)\n#42 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(142): Magento\\CatalogInventory\\Model\\Plugin\\AroundProductRepositorySave->aroundSave(Object(Magento\\Catalog\\Model\\ProductRepository\\Interceptor), Object(Closure), Object(Magento\\Catalog\\Model\\Product\\Interceptor), false)\n#43 \/var\/www\/html\/var\/generation\/Magento\/Catalog\/Model\/ProductRepository\/Interceptor.php(52): Magento\\Catalog\\Model\\ProductRepository\\Interceptor->___callPlugins('save', Array, Array)\n#44 [internal function]: Magento\\Catalog\\Model\\ProductRepository\\Interceptor->save(Object(Magento\\Catalog\\Model\\Product\\Interceptor), false)\n#45 \/var\/www\/html\/vendor\/magento\/module-webapi\/Controller\/Rest.php(307): call_user_func_array(Array, Array)\n#46 \/var\/www\/html\/vendor\/magento\/module-webapi\/Controller\/Rest.php(216): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#47 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(146): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#48 \/var\/www\/html\/var\/generation\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(39): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#49 \/var\/www\/html\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#50 \/var\/www\/html\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#51 \/var\/www\/html\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#52 {main}"}
```

**Comment by misha-kotov** [comment]
@careys7 Thanks for reporting the issue. I've filed internal issue MAGETWO-64316. It happens, as you probably know, bc the SEO best practices dictate the url-key should be based on the product name (problem being that Name is not unique), and at the same time url-key needs to be unique. The simple work-around is to provide a unique url-key for the second product. 

As far as desired behavior, in Admin we append "-1" to the url key when there's a collision. We probably want to be consistent and do the same in WebAPI.

**Comment by sabarivelmks** [comment]
is this issue fixed?

**Comment by rhoerr** [comment]
Related issue: https://github.com/magento/magento2/issues/3525

**Comment by orlangur** [comment]
> As far as desired behavior, in Admin we append "-1" to the url key when there's a collision. We probably want to be consistent and do the same in WebAPI.

I believe @misha-kotov was referring to SKU field, not URL Key, here.

@careys7, system works as expected with the steps described. The same error will be shown if you add product using Admin UI.

Error message was improved on Magento 2.2.0 branch to give more information to merchant what exactly needs to be changed.
