### ISSUE TITLE
Installation Error: [ERROR] exception 'Zend\Stdlib\Exception\RuntimeException' with message 'glob('/home/mage2/domains/magento2.uldev.co/public_html/magento2/app/code/Magento/Store/data/*', 8192) failed' in /home/mage2/domains/magento2.uldev.co/public_html/magento2/vendor/zendframework/zend-stdlib/Zend/Stdlib/Glob.php:85

### ISSUE THREAD

**Issue by idawgik** [magento/magento2#827]
When attempting to install Magento2, it errors out at the beginning of the install process.

This is the output from the console log during install:

```
Starting Magento installation:
File permissions check...

Enabling Maintenance Mode...

Installing deployment configuration...

Installing database schema:
Schema creation/updates:
Module 'Magento_Core':

Module 'Magento_Store':
[ERROR] exception 'Zend\Stdlib\Exception\RuntimeException' with message 'glob('/home/mage2/domains/magento2.uldev.co/public_html/magento2/app/code/Magento/Store/data/*', 8192) failed' in /home/mage2/domains/magento2.uldev.co/public_html/magento2/vendor/zendframework/zend-stdlib/Zend/Stdlib/Glob.php:85 
Stack trace: 
#0 /home/mage2/domains/magento2.uldev.co/public_html/magento2/vendor/zendframework/zend-stdlib/Zend/Stdlib/Glob.php(46): Zend\Stdlib\Glob::systemGlob('/home/mage2/dom...', 32) 
#1 /home/mage2/domains/magento2.uldev.co/public_html/magento2/setup/module/Magento/Setup/src/Module/Setup/FileResolver.php(68): Zend\Stdlib\Glob::glob('/home/mage2/dom...', 32) 
#2 /home/mage2/domains/magento2.uldev.co/public_html/magento2/setup/module/Magento/Setup/src/Module/SetupModule.php(76): Magento\Setup\Module\Setup\FileResolver->getResourceCode('Magento_Store') 
#3 /home/mage2/domains/magento2.uldev.co/public_html/magento2/setup/module/Magento/Setup/src/Module/SetupFactory.php(62): Magento\Setup\Module\SetupModule->__construct(Object(Magento\Setup\Model\WebLogger), Object(Magento\Framework\Module\ModuleList), Object(Magento\Setup\Module\Setup\FileResolver), 'Magento_Store', Object(Magento\Framework\App\Resource)) 
#4 /home/mage2/domains/magento2.uldev.co/public_html/magento2/setup/module/Magento/Setup/src/Model/Installer.php(558): Magento\Setup\Module\SetupFactory->createSetupModule(Object(Magento\Setup\Model\WebLogger), 'Magento_Store') 
#5 [internal function]: Magento\Setup\Model\Installer->installSchema() 
#6 /home/mage2/domains/magento2.uldev.co/public_html/magento2/setup/module/Magento/Setup/src/Model/Installer.php(296): call_user_func_array(Array, Array) 
#7 /home/mage2/domains/magento2.uldev.co/public_html/magento2/setup/module/Magento/Setup/src/Controller/Install.php(79): Magento\Setup\Model\Installer->install(Array) 
#8 /home/mage2/domains/magento2.uldev.co/public_html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\Install->startAction() 
#9 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) 
#10 /home/mage2/domains/magento2.uldev.co/public_html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) 
#11 /home/mage2/domains/magento2.uldev.co/public_html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) 
#12 /home/mage2/domains/magento2.uldev.co/public_html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) 
#13 /home/mage2/domains/magento2.uldev.co/public_html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) 
#14 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) 
#15 /home/mage2/domains/magento2.uldev.co/public_html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) 
#16 /home/mage2/domains/magento2.uldev.co/public_html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) 
#17 /home/mage2/domains/magento2.uldev.co/public_html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) 
#18 /home/mage2/domains/magento2.uldev.co/public_html/magento2/setup/index.php(24): Zend\Mvc\Application->run() 
#19 {main}
```

It appears to be looking for the `app/code/Magento/Store/data/` directory which doesn't exist from the repo.

I have run the `composer install` in the webroot.

Am I missing something in the process?

**Comment by maksek** [comment]
Closed due long inactivity by creator. If you still have issue - feel free to reopen.
