### ISSUE TITLE
Stores -> Configuration dont work

### ISSUE THREAD

**Issue by ingvar911** [magento/magento2#8325]
I install Magento 2.1.2 with demo data template from TemplateMonster. Frontend work well, but Stores -> Configuration crashed with "There has been an error processing your request". In report:
```
a:4:{i:0;s:203:"Warning: DOMDocument::loadXML(): Opening and ending tag mismatch: section line 7 and group in Entity, line: 625 in C:\wamp65\www\vendor\magento\module-config\Model\Config\Structure\Reader.php on line 132";i:1;s:5166:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'DOMDocument::lo...', 'C:\\wamp65\\www\\v...', 132, Array)
#1 C:\wamp65\www\vendor\magento\module-config\Model\Config\Structure\Reader.php(132): DOMDocument->loadXML('<?xml version="...')
#2 C:\wamp65\www\vendor\magento\module-config\Model\Config\Structure\Reader.php(90): Magento\Config\Model\Config\Structure\Reader->processingDocument('<?xml version="...')
#3 C:\wamp65\www\vendor\magento\framework\Config\Reader\Filesystem.php(127): Magento\Config\Model\Config\Structure\Reader->_readFiles(Object(Magento\Framework\Config\FileIterator))
#4 C:\wamp65\www\vendor\magento\framework\Config\Data\Scoped.php(103): Magento\Framework\Config\Reader\Filesystem->read('adminhtml')
#5 C:\wamp65\www\vendor\magento\framework\Config\Data\Scoped.php(81): Magento\Framework\Config\Data\Scoped->_loadScopedData()
#6 C:\wamp65\www\vendor\magento\module-config\Model\Config\Structure.php(73): Magento\Framework\Config\Data\Scoped->get()
#7 C:\wamp65\www\var\generation\Magento\Config\Model\Config\Structure\Interceptor.php(14): Magento\Config\Model\Config\Structure->__construct(Object(Magento\Config\Model\Config\Structure\Data), Object(Magento\Config\Model\Config\Structure\Element\Iterator\Tab), Object(Magento\Config\Model\Config\Structure\Element\FlyweightFactory), Object(Magento\Config\Model\Config\ScopeDefiner))
#8 C:\wamp65\www\vendor\magento\framework\ObjectManager\Factory\AbstractFactory.php(93): Magento\Config\Model\Config\Structure\Interceptor->__construct(Object(Magento\Config\Model\Config\Structure\Data), Object(Magento\Config\Model\Config\Structure\Element\Iterator\Tab), Object(Magento\Config\Model\Config\Structure\Element\FlyweightFactory), Object(Magento\Config\Model\Config\ScopeDefiner))
#9 C:\wamp65\www\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Config\\...', Array)
#10 C:\wamp65\www\vendor\magento\framework\ObjectManager\ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Config\\...')
#11 C:\wamp65\www\vendor\magento\framework\ObjectManager\Factory\AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Config\\...')
#12 C:\wamp65\www\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Config\\...', NULL, 'configStructure', 'Magento\\Config\\...')
#13 C:\wamp65\www\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Config\\...', Array, Array)
#14 C:\wamp65\www\vendor\magento\framework\ObjectManager\ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Config\\...', Array)
#15 C:\wamp65\www\vendor\magento\framework\App\ActionFactory.php(40): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Config\\...')
#16 C:\wamp65\www\vendor\magento\framework\App\Router\Base.php(300): Magento\Framework\App\ActionFactory->create('Magento\\Config\\...')
#17 C:\wamp65\www\vendor\magento\framework\App\Router\Base.php(161): Magento\Framework\App\Router\Base->matchAction(Object(Magento\Framework\App\Request\Http), Array)
#18 C:\wamp65\www\vendor\magento\framework\App\FrontController.php(50): Magento\Framework\App\Router\Base->match(Object(Magento\Framework\App\Request\Http))
#19 C:\wamp65\www\vendor\magento\framework\Interception\Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#20 C:\wamp65\www\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#21 C:\wamp65\www\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#22 C:\wamp65\www\vendor\magento\framework\Module\Plugin\DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#23 C:\wamp65\www\vendor\magento\framework\Interception\Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#24 C:\wamp65\www\var\generation\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#25 C:\wamp65\www\vendor\magento\framework\App\Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#26 C:\wamp65\www\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#27 C:\wamp65\www\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#28 {main}";s:3:"url";s:102:"/admin/admin/system_config/index/key/3954f45e437246c3d6fa3b91667893b50380ba651566f1d2560ef31e6461b673/";s:11:"script_name";s:10:"/index.php";}
```
Please, help me and sorry my english.
```
bin/magento setup:upgrade
bin/magento setup:static-content:deploy
bin/magento setup:di:compile
bin/magento index:reindex
```
Dosn't help

**Comment by korostii** [comment]
The trace just says one of the adminhtml.xml files loaded is invalid, but doesn't say which one exactly. My guess would be it's coming from either your "template from TemplateMonster" (which exactly) or probably a 3rd party module (if you have any installed - I'd suggest disabling those one-by-one in order to find the buggy extension)

**Comment by ingvar911** [comment]
Thank you! Problem with 3th party module.
