### ISSUE TITLE
1 exception(s): Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in NotProtectedExtension.php on line 89

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#8348]
When viewing a product page I get a crash on NotProtectedExtension.php on line 89. This is due the following setting being empty and not checked before it is used:

'general/file/protected_extensions' in core_config_data

This was done using a clean install of Magento EE 2.1.3, then used the data migration tool to convert products/settings across. No such setting exists in M1 database and is not set in the M2 database.

### Preconditions
1. Magento EE 2.1.3
2. PHP 7.0.15
3. MySQL 5.7.17

### Steps to reproduce
1. View a product page

### Expected result
1. Product page and content to be displayed

### Actual result
1. Exception displayed:

```
1 exception(s):
Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-media-storage/Model/File/Validator/NotProtectedExtension.php on line 89

Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-media-storage/Model/File/Validator/NotProtectedExtension.php on line 89
#0 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-media-storage/Model/File/Validator/NotProtectedExtension.php(89): Magento\Framework\App\ErrorHandler->handler(2, 'Invalid argumen...', '/Users/ccarnell...', 89, Array)
#1 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-media-storage/Model/File/Validator/NotProtectedExtension.php(56): Magento\MediaStorage\Model\File\Validator\NotProtectedExtension->_initProtectedFileExtensions()
#2 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Magento\MediaStorage\Model\File\Validator\NotProtectedExtension->__construct(Object(Magento\Framework\App\Config))
#3 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\MediaSt...', Array)
#4 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\MediaSt...')
#5 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\MediaSt...')
#6 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\MediaSt...', NULL, 'validator', 'Magento\\Downloa...')
#7 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Downloa...', Array, Array)
#8 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Downloa...')
#9 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Downloa...')
#10 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Downloa...', NULL, 'fileContentUplo...', 'Magento\\Downloa...')
#11 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Downloa...', Array, Array)
#12 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Downloa...')
#13 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Downloa...')
#14 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Downloa...', NULL, 'linkRepository', 'Magento\\Downloa...')
#15 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Downloa...', Array, Array)
#16 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Downloa...')
#17 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/EntityManager/Operation/ExtensionPool.php(52): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Downloa...')
#18 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/EntityManager/Operation/Read/ReadExtensions.php(46): Magento\Framework\EntityManager\Operation\ExtensionPool->getActions('Magento\\Catalog...', 'read')
#19 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/EntityManager/Operation/Read.php(117): Magento\Framework\EntityManager\Operation\Read\ReadExtensions->execute(Object(Magento\Catalog\Model\Product\Interceptor), Array)
#20 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/EntityManager/EntityManager.php(61): Magento\Framework\EntityManager\Operation\Read->execute(Object(Magento\Catalog\Model\Product\Interceptor), 3806, Array)
#21 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-catalog/Model/ResourceModel/Product.php(655): Magento\Framework\EntityManager\EntityManager->load(Object(Magento\Catalog\Model\Product\Interceptor), 3806)
#22 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(258): Magento\Catalog\Model\ResourceModel\Product->load(Object(Magento\Catalog\Model\Product\Interceptor), 3806, NULL)
#23 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Model/AbstractModel.php(531): Magento\Catalog\Model\ResourceModel\Product\Interceptor->load(Object(Magento\Catalog\Model\Product\Interceptor), 3806, NULL)
#24 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\Model\AbstractModel->load(3806)
#25 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Catalog/Model/Product/Interceptor.php(2314): Magento\Catalog\Model\Product\Interceptor->___callPlugins('load', Array, Array)
#26 /Users/ccarnell/Sites/vax-uk2/app/code/VaxLtd/CheckoutLimit/Model/Product/Limit/Validator/Type/ProductId.php(29): Magento\Catalog\Model\Product\Interceptor->load(3806)
#27 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): VaxLtd\CheckoutLimit\Model\Product\Limit\Validator\Type\ProductId->__construct(Object(VaxLtd\CheckoutLimit\Helper\Config), Object(Magento\Catalog\Model\Product\Interceptor))
#28 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('VaxLtd\\Checkout...', Array)
#29 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('VaxLtd\\Checkout...', Array)
#30 /Users/ccarnell/Sites/vax-uk2/var/generation/VaxLtd/CheckoutLimit/Model/Factory/Product/Limit/ValidatorTypeFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create('VaxLtd\\Checkout...', Array)
#31 /Users/ccarnell/Sites/vax-uk2/app/code/VaxLtd/CheckoutLimit/Model/Factory/Product/Limit/ValidatorType.php(64): VaxLtd\CheckoutLimit\Model\Factory\Product\Limit\ValidatorTypeFactory->create(Array)
#32 /Users/ccarnell/Sites/vax-uk2/app/code/VaxLtd/CheckoutLimit/Model/Factory/Product/Limit/ValidatorType.php(55): VaxLtd\CheckoutLimit\Model\Factory\Product\Limit\ValidatorType->create(Array)
#33 /Users/ccarnell/Sites/vax-uk2/app/code/VaxLtd/CheckoutLimit/Model/Product/Limit/Validator.php(26): VaxLtd\CheckoutLimit\Model\Factory\Product\Limit\ValidatorType->getInstance(Object(VaxLtd\CheckoutLimit\Helper\Config))
#34 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): VaxLtd\CheckoutLimit\Model\Product\Limit\Validator->__construct(Object(VaxLtd\CheckoutLimit\Model\Factory\Product\Limit\ValidatorType), Object(VaxLtd\CheckoutLimit\Helper\Config))
#35 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('VaxLtd\\Checkout...', Array)
#36 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('VaxLtd\\Checkout...')
#37 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('VaxLtd\\Checkout...')
#38 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'VaxLtd\\Checkout...', NULL, 'validator', 'VaxLtd\\Checkout...')
#39 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('VaxLtd\\Checkout...', Array, Array)
#40 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('VaxLtd\\Checkout...')
#41 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('VaxLtd\\Checkout...')
#42 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'VaxLtd\\Checkout...', NULL, 'checkoutHelper', 'VaxLtd\\Checkout...')
#43 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('VaxLtd\\Checkout...', Array, Array)
#44 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('VaxLtd\\Checkout...')
#45 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('VaxLtd\\Checkout...')
#46 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Checkou...', NULL, 'checkoutCart', 'Magento\\Checkou...')
#47 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Checkou...', Array, Array)
#48 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Checkou...')
#49 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Checkou...')
#50 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Checkou...', NULL, 'cartHelper', 'Magento\\Catalog...')
#51 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Catalog...', Array, Array)
#52 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Catalog...')
#53 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Catalog...')
#54 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Catalog...', NULL, 'context', 'Magento\\Multipl...')
#55 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Multipl...', Array, Array)
#56 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Multipl...', Array)
#57 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Element/BlockFactory.php(45): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Multipl...', Array)
#58 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout/Generator/Block.php(257): Magento\Framework\View\Element\BlockFactory->createBlock('Magento\\Multipl...', Array)
#59 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout/Generator/Block.php(237): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('Magento\\Multipl...', Array)
#60 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout/Generator/Block.php(215): Magento\Framework\View\Layout\Generator\Block->createBlock('Magento\\Multipl...', 'multiple-wishli...', Array)
#61 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout/Generator/Block.php(124): Magento\Framework\View\Layout\Generator\Block->generateBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure), 'multiple-wishli...')
#62 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#63 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#64 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#65 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#66 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#67 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#68 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build()
#69 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/View/Page/Config.php(207): Magento\Framework\View\Page\Config->build()
#70 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/App/View.php(170): Magento\Framework\View\Page\Config->publicBuild()
#71 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/App/View.php(114): Magento\Framework\App\View->loadLayoutUpdates()
#72 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-catalog-search/Controller/Result/Index.php(90): Magento\Framework\App\View->loadLayout()
#73 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php(24): Magento\CatalogSearch\Controller\Result\Index->execute()
#74 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/App/Action/Action.php(102): Magento\CatalogSearch\Controller\Result\Index\Interceptor->execute()
#75 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#76 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent('dispatch', Array)
#77 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Array, 'contextPlugin')
#78 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#79 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#80 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Array, 'customer-segmen...')
#81 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-customer-segment/Model/App/Action/ContextPlugin.php(81): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#82 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\CustomerSegment\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#83 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Array, 'customer-app-ac...')
#84 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#85 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#86 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Array, 'storeCheck')
#87 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#88 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#89 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Array, 'weee-app-action...')
#90 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#91 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#92 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Array, 'tax-app-action-...')
#93 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#94 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#95 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php(39): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#96 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/App/FrontController.php(55): Magento\CatalogSearch\Controller\Result\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#97 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#98 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#99 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#100 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#101 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#102 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#103 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#104 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#105 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'searchautocompl...')
#106 /Users/ccarnell/Sites/vax-uk2/vendor/mirasvit/module-search-autocomplete/src/SearchAutocomplete/Model/App/FrontController/Plugin.php(130): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#107 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Mirasvit\SearchAutocomplete\Model\App\FrontController\Plugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#108 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#109 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#110 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#111 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#112 /Users/ccarnell/Sites/vax-uk2/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#113 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#114 /Users/ccarnell/Sites/vax-uk2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#115 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#116 /Users/ccarnell/Sites/vax-uk2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#117 /Users/ccarnell/Sites/vax-uk2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#118 {main}
```

**Comment by veloraven** [comment]
@craigcarnell thank you for your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.

**Comment by rakibabu** [comment]
This issue is still there in version 2.1.5

**Comment by shuaiZend** [comment]
This issue is still there in version 2.1.9

**Comment by mcjwsk** [comment]
This issue is still there in version 2.2.0 ;(

**Comment by magento-engcom-team** [comment]
Hi @craigcarnell. Thank you for your report. 
The issue has been fixed in magento/magento2#19012 by @RostislavS in 2.2-develop branch
Related commit(s):
 - [468f245adc3f8788209eeeb4250c675f63191ac5](https://github.com/magento/magento2/commit/468f245adc3f8788209eeeb4250c675f63191ac5)
 - [4c13ad766c85ea4514de90e0c9d0c035d5fc0172](https://github.com/magento/magento2/commit/4c13ad766c85ea4514de90e0c9d0c035d5fc0172)

The fix will be available with the upcoming 2.2.8 release.

**Comment by tuyennn** [comment]
Not sure but this issue still happened on M2.4.0

**Comment by Alexandre57370** [comment]
> Not sure but this issue still happened on M2.4.0

i'm agree

**Comment by puntable** [comment]
> Not sure but this issue still happened on M2.4.0

Can confirm this is still happening on M2.4.3

**Comment by perryholden** [comment]
For people who run into this in the future: For some strange reason, sometimes there will be a record in `core_config_data` at path `general` and value = NULL.

`SELECT * FROM core_config_data WHERE path = 'general';`

If this yields a record, delete it.
