### ISSUE TITLE
Fatal Error after installation: Cannot access admin

### ISSUE THREAD

**Issue by andonlin** [magento/magento2#8659]
### Preconditions

1.  PHP Version 7.0.12
2. Magento-CE-2.1.5

### Steps to reproduce

1. Downloaded Magento-CE-2.1.5
2. Install via web wizard
3. 

### Expected result

1. Able to access admin

### Actual result

Fatal error: Uncaught TypeError: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given in /home/prngne5/public_html/and/jsize/vendor/magento/framework/View/Element/Html/Calendar.php:86 Stack trace: #0 /home/prngne5/public_html/and/jsize/vendor/magento/framework/View/Element/Html/Calendar.php(86): iterator_to_array(NULL) #1 /home/prngne5/public_html/and/jsize/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Html\Calendar->_toHtml() #2 /home/prngne5/public_html/and/jsize/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml() #3 /home/prngne5/public_html/and/jsize/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('head.calendar') #4 /home/prngne5/public_html/and/jsize/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('head.calendar') #5 /home/prngne5/public_html/and/jsize/vendor/magento/fra in /home/prngne5/public_html/and/jsize/vendor/magento/framework/View/Element/Html/Calendar.php on line 86

What can I do to fix this?

**Comment by jordanbrauer** [comment]
Have you tried running any of these? Running these in this order will effectively rebuild your store.
```
$ magento setup:static-content:deploy
$ magento setup:upgrade
$ magento setup:di
```
Also have you set post-install permissions?

**Comment by veloraven** [comment]
@andonlin is this issue still actual?

**Comment by magento-engcom-team** [comment]
@andonlin we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by woshka** [comment]
I have reported this issue here
https://github.com/magento/magento2/issues/14068
