### ISSUE TITLE
Remove Design Group And Schedule Design Update from Attribute Set

### ISSUE THREAD

**Issue by neverovsky** [magento/magento2#8927]
### Preconditions

1. Magento CE 2.1.4
2. PHP 7.0.8

### Steps to reproduce

1.  Create new attribute set from Default 
2.  Create new product based on new attribute set
2.  Remove  Design Group And Schedule Design Update groups from the Attribute set 
3.  Click Edit product link

### Expected result

1.  Product Edit form

### Actual result

1. Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\Stdlib\ArrayManager::set() must be of the type array, null given, called in ..vendor/magento/module-catalog-staging/Ui/DataProvider/Product/Form/Modifier/ScheduleDesignUpdate.php on line 66 and defined in ..vendor/magento/framework/Stdlib/ArrayManager.php on line 66
2. 
<img src="https://monosnap.com/file/xQ5VBksvSzjQkN3DxXFbnWcUlGiqAP.png">

So now i know what we should not remove those groups , but Magento 2 allow to do it via standart interface !

**Comment by krutkoroma79911** [comment]
@neverovsky Hi, i tried to reproduce this issue as you described it but i can`t, when i remove these groups from attribute set and then try to edit product, my edit form is correct. Can you please check your problem on the latest version of Magento 2?

**Comment by magento-engcom-team** [comment]
@neverovsky we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Comment by Chuvisco88** [comment]
Instead of creating an attribute set from default it is also possible to create a completely new attribute set. The error is the same when switching the attribute sets on the product create form.

**Comment by damodamo** [comment]
I can reproduce this error in Magento 2.1.5.

`Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\Stdlib\ArrayManager::set() must be of the type array, null given, called in /home/jts/public_html/vendor/magento/module-catalog-staging/Ui/DataProvider/Product/Form/Modifier/ScheduleDesignUpdate.php on line 66 and defined in /home/jts/public_html/vendor/magento/framework/Stdlib/ArrayManager.php:66 Stack trace: #0 /home/jts/public_html/vendor/magento/module-catalog-staging/Ui/DataProvider/Product/Form/Modifier/ScheduleDesignUpdate.php(66): Magento\Framework\Stdlib\ArrayManager->set('data/config/lab...', NULL, 'Design') #1 /home/jts/public_html/vendor/magento/module-catalog/Ui/DataProvider/Product/Form/ProductDataProvider.php(68): Magento\CatalogStaging\Ui\DataProvider\Product\Form\Modifier\ScheduleDesignUpdate->modifyMeta(Array) #2 /home/jts/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(269): Magento\Catalog\Ui\DataProvider\Product\Form\ProductDataProvider->getMeta() #3 /home/jts/public_html/vendor/magento/framework/View/Elem in /home/jts/public_html/vendor/magento/framework/Stdlib/ArrayManager.php on line 66`

**Comment by Parakoopa** [comment]
I can confirm this issue still exists in Magento 2.3.
@magento-engcom-team, can you re-open the issue? The original description is still valid.

**Comment by Parakoopa** [comment]
Oh, actually, there is one more step to reproduce the issue in Magento 2.3. It only seems to happen if the attribute set is switched via the form when creating or editing a product. Should I open a new issue for this?

**Comment by Datta** [comment]
getting same issue in magento EE 2.3.1 after the upgrade. 

Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\Stdlib\ArrayManager::set() must be of the type array, null given, called in vendor/magento/module-catalog-staging/Ui/DataProvider/Product/Form/Modifier/ScheduleDesignUpdate.php on line 64 and defined in vendor/magento/framework/Stdlib/ArrayManager.php:72 Stack trace: #0 vendor/magento/module-catalog-staging/Ui/DataProvider/Product/Form/Modifier/ScheduleDesignUpdate.php(64): Magento\Framework\Stdlib\ArrayManager->set('data/config/lab...', NULL, 'Design') #1 vendor/magento/module-catalog/Ui/DataProvider/Product/Form/ProductDataProvider.php(73): Magento\CatalogStaging\Ui\DataProvider\Product\Form\Modifier\ScheduleDesignUpdate->modifyMeta(Array) #2 vendor/magento/framework/View/Element/UiComponentFactory.php(3 in vendor/magento/framework/Stdlib/ArrayManager.php on line 72

**Comment by magesanjay** [comment]
Getting same issue in Magento EE 2.3.2 fresh instance.

> Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\Stdlib\ArrayManager::set() must be of the type array, null given, called in /var/www/html/projectname/vendor/magento/module-catalog-staging/Ui/DataProvider/Product/Form/Modifier/ScheduleDesignUpdate.php on line 64 and defined in /var/www/html/projectname/vendor/magento/framework/Stdlib/ArrayManager.php on line 72


> TypeError: Argument 2 passed to Magento\Framework\Stdlib\ArrayManager::set() must be of the type array, null given, called in /var/www/html/projectname/vendor/magento/module-catalog-staging/Ui/DataProvider/Product/Form/Modifier/ScheduleDesignUpdate.php on line 64 in /var/www/html/projectname/vendor/magento/framework/Stdlib/ArrayManager.php on line 72

**Comment by sdzhepa** [comment]
Hello @neverovsky @magesanjay @Datta @Parakoopa 

Thank you for contribution and collaboration!

I moved this issue into Magento Commerce private repository where it could be fixed and delivered.

[Current repository](https://github.com/magento/magento2) and [issue tracker](https://github.com/magento/magento2/issues) aimed at Magento Open Source version only and the main focus is community contribution/collaboration. It described in [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and it is a part of the issue report template:
> Verify, that the issue you are about to report does not relate to the Magento Commerce. GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub. You can report Commerce-related issues in one of two ways:
> - You can use the Support portal associated with your account
> - If you are a Partner reporting on behalf of a merchant, use the Partner portal.
