### ISSUE TITLE
Unable to run js tests

### ISSUE THREAD

**Issue by Vinai** [magento/magento2#942]
I'm struggling to the the JavaScript tests to run.
Hopefully one of you will be able to point me in the right direction. I'll try to give as much information about what I've tried as possible in case its helpful.

First, I've set up the configuration according to https://wiki.magento.com/display/MAGE2DOC.

The file **dev/tests/js/jsTestDriver.php:**
```{.php}
<?php
return array(
    'server' => 'http://localhost:9876',
    'load' => array(
        '/dev/tests/js/framework',
        '/lib/web/mage/webapi.js',
        '/lib/web/mage/validation/validation.js',
        '/lib/web/jquery/jquery.tmpl.min.js',
        '/app/code/Magento/DesignEditor/view/adminhtml/web/js/infinitescroll.js',
        '/lib/web/jquery/jstree/jquery.jstree.js',
        '/lib/web/jquery/jquery-ui-timepicker-addon.js',
        '/lib/web/mage/cookies.js',
        '/lib/web/mage/calendar.js',
        '/lib/web/mage/loader_old.js',
        '/lib/web/mage/edit-trigger.js',
        '/lib/web/mage/translate-inline.js',
        '/lib/web/mage/translate-inline-vde.js',
        '/lib/web/mage/backend/form.js',
        '/lib/web/mage/backend/button.js',
        '/lib/web/mage/backend/tabs.js',
        '/lib/web/mage/backend/menu.js',
        '/lib/web/mage/backend/suggest.js',
        '/lib/web/mage/backend/tree-suggest.js',
        '/lib/web/mage/gallery.js',
        '/lib/web/mage/gallery-fullscreen.js',
        '/lib/web/mage/zoom.js',
    ),
    'test' => array('/dev/tests/js/testsuite'),
    'JsTestDriver' => '/Users/vinai/bin/JsTestDriver-1.3.5.jar',
);
```
I've also created a `/usr/local/bin/firefox` executable which opens the firefox application with the correct profile
```
% cat /usr/local/bin/firefox
#!/bin/sh

/Applications/Firefox.app/Contents/MacOS/firefox -P "selenium"
```

When I ran the script it produces some output (see below) and then hangs.
However, it quits PHPStorm automatically when I run the script!?!

It also created the file **jsTestDriver.conf** with the contents
```{.yaml}
server: http://localhost:9876
load:
  - ../../../lib/web/jquery/jquery.js
  - ../../../lib/web/jquery/jquery-migrate.js
  - ../../../lib/web/jquery/jquery-ui-1.9.2.js
  - ../../../dev/tests/js/framework/requirejs-util.js
  - ../../../lib/web/jquery/jquery.cookie.js
  - ../../../lib/web/mage/apply/main.js
  - ../../../lib/web/mage/mage.js
  - ../../../lib/web/mage/decorate.js
  - ../../../lib/web/jquery/jquery.validate.js
  - ../../../lib/web/jquery/jquery.metadata.js
  - ../../../lib/web/mage/translate.js
  - ../../../lib/web/mage/requirejs/plugin/id-normalizer.js
  - ../../../dev/tests/js/framework/qunit/qunit-1.14.0.js
  - ../../../dev/tests/js/framework/stub.js
  - ../../../lib/web/mage/webapi.js
  - ../../../lib/web/mage/validation/validation.js
  - ../../../lib/web/jquery/jquery.tmpl.min.js
  - ../../../app/code/Magento/DesignEditor/view/adminhtml/web/js/infinitescroll.js
  - ../../../lib/web/jquery/jstree/jquery.jstree.js
  - ../../../lib/web/jquery/jquery-ui-timepicker-addon.js
  - ../../../lib/web/mage/cookies.js
  - ../../../lib/web/mage/calendar.js
  - ../../../lib/web/mage/loader_old.js
  - ../../../lib/web/mage/edit-trigger.js
  - ../../../lib/web/mage/translate-inline.js
  - ../../../lib/web/mage/translate-inline-vde.js
  - ../../../lib/web/mage/backend/form.js
  - ../../../lib/web/mage/backend/button.js
  - ../../../lib/web/mage/backend/tabs.js
  - ../../../lib/web/mage/backend/menu.js
  - ../../../lib/web/mage/backend/suggest.js
  - ../../../lib/web/mage/backend/tree-suggest.js
  - ../../../lib/web/mage/gallery.js
  - ../../../lib/web/mage/gallery-fullscreen.js
  - ../../../lib/web/mage/zoom.js
test:
  - ../../../dev/tests/js/testsuite/lib/ko/datepicker/datepicker.js
  - ../../../dev/tests/js/testsuite/lib/storage/test-storage.js
  - ../../../dev/tests/js/testsuite/mage/_demo/test.js
  - ../../../dev/tests/js/testsuite/mage/accordion/accordion.js
  - ../../../dev/tests/js/testsuite/mage/button/button-test.js
  - ../../../dev/tests/js/testsuite/mage/calendar/calendar-qunit.js
  - ../../../dev/tests/js/testsuite/mage/calendar/calendar-test.js
  - ../../../dev/tests/js/testsuite/mage/calendar/date-range-test.js
  - ../../../dev/tests/js/testsuite/mage/collapsible/test-collapsible.js
  - ../../../dev/tests/js/testsuite/mage/design_editor/adminhtml/js/infinitescroll.js
  - ../../../dev/tests/js/testsuite/mage/dropdown/test-dropdown.js
  - ../../../dev/tests/js/testsuite/mage/edit_trigger/edit-trigger-test.js
  - ../../../dev/tests/js/testsuite/mage/form/form-test.js
  - ../../../dev/tests/js/testsuite/mage/gallery/gallery-fullscreen-test.js
  - ../../../dev/tests/js/testsuite/mage/gallery/gallery-test.js
  - ../../../dev/tests/js/testsuite/mage/list/jquery-list-test.js
  - ../../../dev/tests/js/testsuite/mage/loader/jquery-loader-test.js
  - ../../../dev/tests/js/testsuite/mage/loader/loader-test.js
  - ../../../dev/tests/js/testsuite/mage/menu/test-menu.js
  - ../../../dev/tests/js/testsuite/mage/requirejs/plugin/id-normalizer-test.js
  - ../../../dev/tests/js/testsuite/mage/search/regular-search-test.js
  - ../../../dev/tests/js/testsuite/mage/suggest/suggest-test.js
  - ../../../dev/tests/js/testsuite/mage/suggest/tree-suggest-test.js
  - ../../../dev/tests/js/testsuite/mage/tabs/tabs-test.js
  - ../../../dev/tests/js/testsuite/mage/tabs/tabs.js
  - ../../../dev/tests/js/testsuite/mage/translate/translate-test.js
  - ../../../dev/tests/js/testsuite/mage/translate_inline/translate-inline-test.js
  - ../../../dev/tests/js/testsuite/mage/translate_inline_vde/translate-inline-vde-dialog-test.js
  - ../../../dev/tests/js/testsuite/mage/translate_inline_vde/translate-inline-vde-test.js
  - ../../../dev/tests/js/testsuite/mage/validation/test-validation.js
  - ../../../dev/tests/js/testsuite/mage/zoom/zoom-test.js
  - ../../../dev/tests/js/testsuite/mage/decorate-test.js
  - ../../../dev/tests/js/testsuite/mage/mage-test.js
  - ../../../dev/tests/js/testsuite/mage/webapi-test.js
```

It also created the file **run_js_tests.sh***.
```{.sh}
LSOF=`/usr/sbin/lsof -i :9876 -t`
        if [ "$LSOF" != "" ];
        then
            kill -9 $LSOF
        fi

        DISPLAY_NUM=99
        ps -ef | egrep "[X]vfb.*:$DISPLAY_NUM"
        if [ $? -eq 0 ] ; then
            pkill Xvfb
        fi

        XVFB=`which Xvfb`
        if [ "$?" -eq 1 ];
        then
            echo "Xvfb not found."
            exit 1
        fi

        $XVFB :$DISPLAY_NUM -nolisten inet6 -ac &
        PID_XVFB="$!"        # take the process ID
        export DISPLAY=:$DISPLAY_NUM   # set display to use that of the Xvfb
        USER=`whoami`
        SUDO=`which sudo`

        # run the tests
        $SUDO -u $USER java -jar "/Users/vinai/bin/JsTestDriver-1.3.5.jar" --config "/Volumes/CaseSensitive/Workspace/m2.dev/htdocs/dev/tests/js/jsTestDriver.conf" --reset --port 9876 --browser "/usr/local/bin/firefox" --raiseOnFailure true --tests all --testOutput "/Volumes/CaseSensitive/Workspace/m2.dev/htdocs/dev/tests/js/test-output"

        kill -9 $PID_XVFB    # shut down Xvfb (firefox will shut down cleanly by JsTestDriver)
        echo "Done."
```
This is the output when I run the PHP CLI script:
```
% php run_js_tests.php
java -jar "/Volumes/Main/Users/vinai/bin/JsTestDriver-1.3.5.jar" --config "/Volumes/CaseSensitive/Workspace/m2.dev/htdocs/dev/tests/js/jsTestDriver.conf" --reset --port 9876 --browser "/usr/local/bin/firefox" --raiseOnFailure true --tests all --testOutput "/Volumes/CaseSensitive/Workspace/m2.dev/htdocs/dev/tests/js/test-output"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
[dix] Could not init font path element /System/Library/Fonts, removing from list!
```

This is the output when I run the run_js_tests.sh script directly
```
% ./run_js_tests.sh
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
[dix] Could not init font path element /System/Library/Fonts, removing from list!
setting runnermode QUIET
```
In both cases firefox opens, but nothing else happens.

Using Ctrl-C to quit the PHP CLI script produces the output:
```
^C
/Volumes/CaseSensitive/Workspace/m2.dev/htdocs/dev/tests/js/run_js_tests.sh: line 29: kill: (96326) - No such process
/Volumes/CaseSensitive/Workspace/m2.dev/htdocs/dev/tests/js/run_js_tests.sh: line 30: echo: write error: Broken pipe
```

Using Ctrl-C to quit the shell script produces the output:
```
^C./run_js_tests.sh: line 29: kill: (96917) - No such process
Done.
```

My next step was to modify the run_js_tests.php script so I can specify a Browser executable with options in the configuration:
```{.php}
if (isset($config['Browser'])) {
    $browser = $config['Browser'];
} else {
    if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
        $browser = 'C:\Program Files (x86)\Mozilla Firefox\firefox.exe';
    } else {
        $browser = exec('which firefox');
    }
    if (!file_exists($browser)) {
        reportError('Browser executable not found: ' . $browser);
    }
}
```
The browser config now is:
`    'Browser' => '/Applications/Firefox.app/Contents/MacOS/firefox -P "selenium"',`

Now running the script produces more errors (...looking promissing :))

```
% php run_js_tests.php                                                                                                                                                        ✹ ✭
java -jar "/Volumes/Main/Users/vinai/bin/JsTestDriver-1.3.5.jar" --config "/Volumes/CaseSensitive/Workspace/m2.dev/htdocs/dev/tests/js/jsTestDriver.conf" --reset --port 9876 --browser "/Applications/Firefox.app/Contents/MacOS/firefox -P "selenium"" --raiseOnFailure true --tests all --testOutput "/Volumes/CaseSensitive/Workspace/m2.dev/htdocs/dev/tests/js/test-output"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
[dix] Could not init font path element /System/Library/Fonts, removing from list!
Failures during test run.
Caused by:
Tried 1times:
com.google.jstestdriver.util.RetryException:
Failure 1: java.lang.NullPointerException
	at com.google.jstestdriver.util.RetryingCallable.call(RetryingCallable.java:62)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: java.lang.NullPointerException
	at com.google.jstestdriver.browser.CommandLineBrowserRunner.stopBrowser(CommandLineBrowserRunner.java:93)
	at com.google.jstestdriver.browser.BrowserControl.stopBrowser(BrowserControl.java:149)
	at com.google.jstestdriver.browser.BrowserCallable.call(BrowserCallable.java:30)
	at com.google.jstestdriver.util.RetryingCallable.call(RetryingCallable.java:49)
	... 10 more

	at com.google.jstestdriver.browser.BrowserActionExecutorAction.run(BrowserActionExecutorAction.java:154)
	at com.google.jstestdriver.ActionRunner.runActions(ActionRunner.java:81)
	at com.google.jstestdriver.embedded.JsTestDriverImpl.runConfigurationWithFlags(JsTestDriverImpl.java:342)
	at com.google.jstestdriver.embedded.JsTestDriverImpl.runConfiguration(JsTestDriverImpl.java:233)
	at com.google.jstestdriver.Main.main(Main.java:70)
Caused by:
Tried 1times:
com.google.jstestdriver.util.RetryException:
Failure 1: java.lang.NullPointerException
```
At this point I'm stumped. I've got experience with JS testing with selenium via PHPUnit and webdriver based runners like protractor and jasmine and also some phantomjs based ones, but this doesn't look familiar.

Any help is appreciated. Thanks.

**Comment by Vinai** [comment]
Thanks to @amacgregor I've tried to run jsTestRunner.jar directly with more success:
```
% java -jar "/Volumes/Main/Users/vinai/bin/JsTestDriver-1.3.5.jar" \
    --config "/Volumes/CaseSensitive/Workspace/m2.dev/htdocs/dev/tests/js/jsTestDriver.conf" \
    --reset --port 9876  --raiseOnFailure true --tests all \
    --browser '/Applications/Firefox.app/Contents/MacOS/firefox'
setting runnermode QUIET
Firefox: Reset
Firefox: Reset
......................................................................
......................................................................
...........................
Total 167 tests (Passed: 167; Fails: 0; Errors: 0) (2322,00 ms)
  Firefox 34.0 Mac OS: Run 167 tests (Passed: 167; Fails: 0; Errors 0) (2322,00 ms)
```
Much better, in fact, probably good enough. So once the jsTestDriver.conf file has been generated there is no further need for it.

**Comment by Vinai** [comment]
At the moment I'm fine runnig the tests through the PHPStorm plugin or by calling jsWebDriver.jar directly, so I'll close the issue.
