### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Rockfordgun** [magento/magento2#9535]
I am having a issue when i run the compiler i get a error on 14%

PHP 7.0.18 (cli) (built: Apr 13 2017 09:49:32) ( NTS )

`Compilation was started.
Proxies code generation... 0/7 [>---------------------------]   0% 1 sec 46.0 MiProxies code generation... 1/7 [====>-----------------------]  14% 1 sec 52.0 MiRepositories code generation... 1/7 [====>-----------------------]  14% 1 sec 52.0 MiBSegmentation fault
`
I have read through most of the threads but i can not get to the bottom of my issue

I have upgraded my magento from 2.1.3 to 2.1.6 thinking this could be the issue but its still on going

Updated the php version from 7 to 7.1 but 7.1 is incompatible with magento2 at the moment

This is the last log i have.
`a:4:{i:0;s:74:"Missing required argument $routerList of Magento\Framework\App\RouterList.";i:1;s:1616:"#0 /home/mediacen/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#1 /home/mediacen/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#2 /home/mediacen/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(126): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#3 /home/mediacen/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'routerList', 'Magento\\Framewo...')
#4 /home/mediacen/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(82): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Framewo...', Array, Array)
#5 /home/mediacen/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...')
#6 /home/mediacen/public_html/vendor/magento/framework/App/Http.php(134): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#7 /home/mediacen/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#8 /home/mediacen/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#9 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";}`

Im a bit new at Magento 2 so im a bit stuck i have reported this to the developer of the module aswelll but he says its definitely something on my side.

**Comment by alloylab** [comment]
What distribution of linux are you running? Also, what is your php memory limit?

**Comment by Rockfordgun** [comment]
Running Red Hat through A2 Hosting 

Linux version 2.6.32-673.26.1.lve1.4.20.el6.x86_64 (mockbuild@build.cloudlinux.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Tue Dec 27 17:42:53 EST 2016

These are the settins on the cpanel for the php 

 allow_url_fopen On
allow_url_include	Off
date.timezone	America/New_York
disable_functions	no value
display_errors	Off
error_log	/home/**************
error_reporting	E_ALL
expose_php	On
file_uploads	On
include_path	.:/opt/alt/php70/usr/share/pear
log_errors	Off
mail.force_extra_parameters	no value
max_execution_time	300
max_file_uploads	20
max_input_time	-1
max_input_vars	10000
memory_limit	2G
open_basedir	no value
output_buffering	4096
post_max_size	512M
session.gc_maxlifetime	1440
session.save_path	/tmp
short_open_tag	On
upload_max_filesize	512M
upload_tmp_dir	no value
zlib.output_compression	Off

**Comment by alloylab** [comment]
From the Kernel version, I am assuming you are running RHEL6. What version of php.. I am guessing 7? can you provide your php info(); to check required extensions? 

http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements-tech.html

**Comment by Rockfordgun** [comment]
Im not completly sure about the RHEL version where can i check it for you?

Hope this is ok if i paste the URL
http://www.mediacentrehub.net/phpinfo.php

Btw thx for the help

**Comment by alloylab** [comment]
np, you can take the php info down

**Comment by alloylab** [comment]
What is the module you are having issues with?

**Comment by Rockfordgun** [comment]
Im trying to install a pay module "Payfast"
When i installed the module it finishes but then when you run through the checkout it comes to a point and gives a error. 

ObjectDOM documnet should be created

and heres the logs

> LOG:

created.";i:1;s:12002:"#0 /home/mediacen/public_html/vendor/magento/framework/View/Element/UiComponent/Config/Reader.php(95): Magento\Framework\View\Element\UiComponent\Config\DomMerger->getDom()
#1 /home/mediacen/public_html/vendor/magento/module-ui/Model/Manager.php(258): Magento\Framework\View\Element\UiComponent\Config\Reader->read()
#2 /home/mediacen/public_html/vendor/magento/module-ui/Model/Manager.php(166): Magento\Ui\Model\Manager->prepare('checkout.root')
#3 /home/mediacen/public_html/vendor/magento/framework/View/Element/UiComponentFactory.php(144): Magento\Ui\Model\Manager->prepareData('checkout.root')
#4 /home/mediacen/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(124): Magento\Framework\View\Element\UiComponentFactory->create('checkout.root', NULL, Array)
#5 /home/mediacen/public_html/vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'checkout.root', Array, Object(Magento\Framework\View\Layout\Interceptor))
#6 /home/mediacen/public_html/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#7 /home/mediacen/public_html/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#8 /home/mediacen/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#9 /home/mediacen/public_html/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#10 /home/mediacen/public_html/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#11 /home/mediacen/public_html/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#12 /home/mediacen/public_html/vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build()
#13 /home/mediacen/public_html/vendor/magento/framework/View/Page/Config.php(217): Magento\Framework\View\Page\Config->build()
#14 /home/mediacen/public_html/vendor/magento/module-checkout/Controller/Index/Index.php(39): Magento\Framework\View\Page\Config->getTitle()
#15 /home/mediacen/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Checkout\Controller\Index\Index->execute()
#16 /home/mediacen/public_html/var/generation/Magento/Checkout/Controller/Index/Index/Interceptor.php(26): Magento\Checkout\Controller\Index\Index\Interceptor->___callPlugins('execute', Array, Array)

> 

So when i installed the module i can go through the checkout so i thought hell its the module mailed the developer and the developer pointed me to the issue at hand and said this is my issue and its not the module. 

With my knowledge of magento2 i could have missed it

**Comment by korostii** [comment]
The "Missing required argument" error might've been caused by not outdated files under `var/di` and `var/generation` folders after upgrading to the new version.
Please run `bin/magento setup:di:compile` from a terminal pointed at your Magento's installation folder and see if that resolves the issue.

Regarding the second error you've posted, "Object DOM document should be created" error just shows something went wrong while rendering checkout, but conceals the root exception causing the issue. I'd advise you to look for some extra different error entries in `var/log/*.log` which might've appeared at about the same time.

**Comment by orlangur** [comment]
@Rockfordgun please provide additional information on how to reproduce this issue on clean Magento installation if @korostii suggestion didn't work.

**Comment by magento-engcom-team** [comment]
@Rockfordgun we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
