### ISSUE TITLE
Import section - check data doesn't work - magento 213

### ISSUE THREAD

**Issue by lucasound** [magento/magento2#9602]
Hi,

I have an important problem with magento 2 import section.

if i import a product file csv, the page stop loading but the loading icon is always present and magento don't check data.
So this first step is blocked by hours and then i can't import product by csv file.

what is the problem? i haven't error in web console. The server is ok, other functions works correctly.
i have tryed magento setup:upgrade ecc but doesn't work.

What is the problem? Please help me to solve. I must import product!

Thanks 
Luca

**Comment by lucav90** [comment]
Hi have this error when i check the file before import:

<b>Fatal error</b>:  Uncaught Error: Call to a member function getName() on null in /var/www/vhosts/sito.com/httpdocs/vendor/magento/module-catalog-import-export/Model/Import/Product/CategoryProcessor.php:80
Stack trace:
#0 /var/www/vhosts/sito.com/httpdocs/vendor/magento/module-catalog-import-export/Model/Import/Product/CategoryProcessor.php(58): Magento\CatalogImportExport\Model\Import\Product\CategoryProcessor-&gt;initCategories()
#1 /var/www/vhosts/sito.com/httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Magento\CatalogImportExport\Model\Import\Product\CategoryProcessor-&gt;__construct(Object(Magento\Catalog\Model\ResourceModel\Category\CollectionFactory), Object(Magento\Catalog\Model\CategoryFactory))
#2 /var/www/vhosts/sito.com/httpdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory-&gt;createObject('Magento\\Catalog...', Array)
#3 /var/www/vhosts/sito.com/httpdocs/vendor/magento/framework/ObjectManager/Objec in <b>/var/www/vhosts/sito.com/httpdocs/vendor/magento/module-catalog-import-export/Model/Import/Product/CategoryProcessor.php</b> on line <b>80</b><br />

**Comment by veloraven** [comment]
@lucasound thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
If you are looking for discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) as  GitHub issue tracker is intended for technical issues only.

**Comment by magento-engcom-team** [comment]
@lucasound we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue

**Comment by webspeaks** [comment]
Issues exists in magento 2.2.2

**Comment by SolsWebdesign** [comment]
Issue also in 2.2.3 I would very much like to (re)open this issue. 

Preconditions:
1. Magento 2.2.3 (store A) without sample data installed (note that this problem also occurs in Magento 2.2.2)
2. Another Magento 2.2.3 (store B) is installed with migrated products from a Magento 1 store (in my case a Magento 1.8.1.0 store)
3. Create a product in the new store A (Magento 2.2.3), export and import it. Goes fine.
4. Export one or more product(s) from store B (Magento 2.2.3) with migrated products (note: no changes are made to the export file).
5. Import the newly created CSV file in store A (the first Magento 2.2.3 with no migrated products, just that one test product). Choose Entity Type Products (other settings don't really matter but try to keep them consistent with the settings used when exporting from store B). Choose the file you exported from store B with the migrated products and hit the button "Check Data".

Expected result:
Maybe some errors indicating things need to be changed in the CSV file or maybe some message saying it isn't compatible.

Actual result: 
An endless rotating "Please wait" icon....

But when opening the console you can see the Internal Sever error:

![internalservererror](https://user-images.githubusercontent.com/4403221/38050659-1005f570-32cc-11e8-87dd-fbced906e080.png)

Some digging around in the logging gives me the following:

[28-Mar-2018 18:53:35 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getFrontendInput() on boolean in ....
/vendor/magento/module-catalog-import-export/Model/Import/Product.php:2657
Stack trace:
#0 .../vendor/magento/module-catalog-import-export/Model/Import/Product.php(2593): Magento\CatalogImportExport\Model\Import\Product->parseAttributesWithWrappedValues('adwords_groupin...')
#1 ../vendor/magento/module-catalog-import-export/Model/Import/Product.php(2573): Magento\CatalogImportExport\Model\Import\Product->parseAdditionalAttributes('adwords_groupin...')
#2 ../vendor/magento/module-catalog-import-export/Model/Import/Product.php(2740): Magento\CatalogImportExport\Model\Import\Product->_parseAdditionalAttributes(Array)
#3 ../vendor/magento/module-catalog-import-export/Model/Import/Product.php(2775): Magento\CatalogImportExport\Model\Import\Product->_customFieldsMapping(Array)
#4 ../vendor/magento/module- in /home/scrittu/public_html/vendor/magento/module-catalog-import-export/Model/Import/Product.php on line 2657

Deleting the attribute that seems to be the problem (in my case adwords_grouping even though I had created this in store A as well) just gets me onto the next Internal Server Error:
[28-Mar-2018 19:15:47 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getFrontendInput() on boolean in /home/scrittu/public_html/vendor/magento/module-catalog-import-export/Model/Import/Product.php:2657
Stack trace:
#0 ../vendor/magento/module-catalog-import-export/Model/Import/Product.php(2593): Magento\CatalogImportExport\Model\Import\Product->parseAttributesWithWrappedValues('brand_se="Bomo ...')
and another attribute that exists in both stores becomes the problem.

I still need to investigate this further (so far I have created various products and exported and imported these fine in Magento 2.2.x stores and have exported migrated products fine but haven't been able to import these again) but I think Magento 2.2.2/2.2.3 should not throw an Internal Sever error when someone pushes the Check Data button.

I will add further findings.

**Comment by develth** [comment]
Almost a year "give a fuck" of importing products.

**Comment by develth** [comment]
Same issue on fresh installed 2.3.0 on check data

**Comment by AndyJAllen** [comment]
I receive this issue on 2.3.3 when clicking check data. Can't import products.

Nothing pertinent in exception or system log files. Network monitor shows 500 Internal Server Error on /admin/import/validate/key/***/?form_key=***

**Comment by LiamTrioTech** [comment]
Magento 2.3. trying to do a product csv import.

This is an issue when Fields enclosure box is ticked, which needs to be ticked to get special characters otherwise it stuffs up the encoding and gets scrambled stuff which might push some attributes such as meta_description past their 255 length validation.

Magento_Downloadable is irrelevant, but is enabled.

**Comment by olasco-ship** [comment]
Magento 2.3. trying to do a product csv import.

Does anyone has solution to above error, i am currently having the same issue and Magento_Downloadable is enabled

![image](https://user-images.githubusercontent.com/68552002/235941366-337f5fab-e0d2-413d-abef-8c614cf0dffe.png)
How do i solve this?

**Comment by hemant-vaniya** [comment]
I had same the issue. It is due to the CSV file format. Please update your CSV file with UTF-8 encode format and re-upload. It should work.

Thanks to callam_kidsaw

https://community.magento.com/t5/Magento-2-x-Technical-Issues/Importing-products-not-working-Mag-2-2-3/m-p/92719/highlight/true#M4750
