### ISSUE TITLE
Magento 2.1.5 Error while sending QUERY packet.

### ISSUE THREAD

**Issue by expertalex** [magento/magento2#9630]
Module 'Magento_Directory':
Installing data... 
[ERROR] Exception: Warning: Error while sending QUERY packet. PID=10468 in D:\home\site\wwwroot\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php on line 228 in D:\home\site\wwwroot\vendor\magento\framework\App\ErrorHandler.php:61 Stack trace: #0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'Error while sen...', 'D:\\home\\site\\ww...', 228, Array) #1 D:\home\site\wwwroot\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array) #2 D:\home\site\wwwroot\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #3 D:\home\site\wwwroot\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #4 D:\home\site\wwwroot\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #5 D:\home\site\wwwroot\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE `it_setu...', Array) #6 D:\home\site\wwwroot\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(465): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE `it_setu...', Array) #7 D:\home\site\wwwroot\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(520): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('UPDATE `it_setu...', Array) #8 D:\home\site\wwwroot\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(635): Magento\Framework\DB\Adapter\Pdo\Mysql->query('UPDATE `it_setu...', Array) #9 D:\home\site\wwwroot\vendor\magento\framework\Module\ModuleResource.php(129): Zend_Db_Adapter_Abstract->update('it_setup_module', Array, '(module = 'Mage...') #10 D:\home\site\wwwroot\setup\src\Magento\Setup\Model\Installer.php(854): Magento\Framework\Module\ModuleResource->setDataVersion('Magento_Directo...', '2.0.0') #11 D:\home\site\wwwroot\setup\src\Magento\Setup\Model\Installer.php(796): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data') #12 [internal function]: Magento\Setup\Model\Installer->installDataFixtures() #13 D:\home\site\wwwroot\setup\src\Magento\Setup\Model\Installer.php(344): call_user_func_array(Array, Array) #14 D:\home\site\wwwroot\setup\src\Magento\Setup\Controller\Install.php(109): Magento\Setup\Model\Installer->install(Array) #15 D:\home\site\wwwroot\vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Magento\Setup\Controller\Install->startAction() #16 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent)) #17 D:\home\site\wwwroot\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #18 D:\home\site\wwwroot\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #19 D:\home\site\wwwroot\vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #20 D:\home\site\wwwroot\vendor\zendframework\zend-mvc\src\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response)) #21 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent)) #22 D:\home\site\wwwroot\vendor\zendframework\zend-eventmanager\src\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #23 D:\home\site\wwwroot\vendor\zendframework\zend-eventmanager\src\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #24 D:\home\site\wwwroot\vendor\zendframework\zend-mvc\src\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure)) #25 D:\home\site\wwwroot\setup\index.php(31): Zend\Mvc\Application->run() #26 {main}

**Comment by minesh0111** [comment]
@expertalex this is related to your mysql setting. [max_allowed_packet](http://stackoverflow.com/questions/30753674/error-while-sending-query-packet)

**Comment by veloraven** [comment]
@expertalex please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by magento-engcom-team** [comment]
@expertalex we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
