### ISSUE TITLE
I was getting base table missing error during installation

### ISSUE THREAD

**Issue by dmj331** [magento/magento2#9738]
I was installing a memento 2 site on my local server and got this error.
And I am using Win 7.

[ERROR] exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'chocolatework.admin_user' doesn't exist' in C:\xampp\htdocs\chocolateworks\chocolateworks\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:228 Stack trace: #0 C:\xampp\htdocs\chocolateworks\chocolateworks\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array) #1 C:\xampp\htdocs\chocolateworks\chocolateworks\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #2 C:\xampp\htdocs\chocolateworks\chocolateworks\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #3 C:\xampp\htdocs\chocolateworks\chocolateworks\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array) #4 C:\xampp\htdocs\chocolateworks\chocolateworks\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('DESCRIBE admin...', Array) #5 C:\xampp\htdocs\chocolateworks\chocolateworks\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(465): Zend_Db_Adapter_Pdo_Abstract->query('DESCRIBEadmin...', Array) #6
![image](https://cloud.githubusercontent.com/assets/6643332/26356004/a38e33a2-3f98-11e7-9060-8960fc7d38c3.png)

Can anyone take a look at this? THX

**Comment by veloraven** [comment]
@dmj331 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.
Please note that Magento does not support the operating system you've listed. Please confirm that you can reproduce this issue on a supported platform. For an overview of supported technologies, see [System Requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-2.1-tech.html). 
If you are looking for an advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as GitHub issue tracker is intended for technical issues only.

**Comment by magento-engcom-team** [comment]
@dmj331 we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
