### ISSUE TITLE
after running magento setup:upgrade the permissions are changed

### ISSUE THREAD

**Issue by whatsnow** [magento/magento2#9769]
if i run php magento setup:upgrade i got the following error message in my logs

Sat May 27 23:07:13.048470 2017] [:error] [pid 6829] [client snip] PHP Fatal error:  Uncaught exception 'Magento\\Framework\\Exception\\LocalizedException' with message 'Can't create directory /var/www/htdocs/var/generation/Magento/Framework/App/ResourceConnection/.' in /var/www/htdocs/vendor/magento/framework/Code/Generator.php:103\nStack trace:\n#0 /var/www/htdocs/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\\Framework\\Code\\Generator->generateClass('Magento\\\\Framewo...')\n#1 [internal function]: Magento\\Framework\\Code\\Generator\\Autoloader->load('Magento\\\\Framewo...')\n#2 [internal function]: spl_autoload_call('Magento\\\\Framewo...')\n#3 /var//www/htdocs/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\\\Framewo...')\n#4 /var/www/htdocs/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\\Framework\\Code\\Reader\\ClassReader->getConstructor('Magento\\\\Framewo...')\n#5 /var/www/htdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Deve in /var/www/htdocs/vendor/magento/framework/Code/Generator.php on line 103

And then the magento shop is not working anymore until i change permissions on the var directory like: sudo chmod -R 0777 var

i can't find out why this happens, al the permissions are set like the documentation.

Anyone a idea?

**Comment by whatsnow** [comment]
Can be closed
